### ISSUE TITLE
`LightSwitch` height is incorrect

### ISSUE THREAD

**Issue by knd775** [skeletonlabs/skeleton#1003]
### Current Behavior

It is set to `w-6` instead of `h-6`, which leads to some weird issues (sometimes the width is `6`, sometimes it's `12`).

**Comment by mertcancam** [comment]
This fixed the issue for me. Thanks!

**Comment by endigo9740** [comment]
Just realized the PR wasn't linked to this issue, but this is fixed. Closing this out.
