### ISSUE TITLE
Error migrating from menu to popup

### ISSUE THREAD

**Issue by MisterJimson** [skeletonlabs/skeleton#1012]
### Current Behavior

Updating to `v0.132.5` and migrating from `menu` to `popup` results in the following console error and the menu/popups not working.

```
Uncaught (in promise) TypeError: Cannot destructure property 'computePosition' of 'get_store_value(...)' as it is undefined.
    at popup (popup.js:11:13)
    at Object.mount [as m] (+layout.svelte:51:56)
    at Object.mount [as m] (AppBar.svelte:40:78)
    at Object.mount [as m] (AppBar.svelte:48:7)
    at mount_component (index.mjs:1949:26)
    at Object.mount [as m] (+layout.svelte:58:75)
    at Object.mount [as m] (AppShell.svelte:35:93)
    at Object.mount [as m] (AppShell.svelte:71:6)
    at mount_component (index.mjs:1949:26)
    at mount (+layout.svelte:58:75)
```

### Steps To Reproduce

1. Write a component similar to the example in the docs.

```js
let examplesPopup: PopupSettings = {
		event: 'click',
		target: 'examples-nav',
		placement: 'top'
	};
	
<div>
	<button class="btn variant-ghost-surface mx-2" use:popup={examplesPopup}>Examples</button>
	<nav class="list-nav card p-4 shadow-xl" data-popup="examples-nav">
		<ul>
			<li>
				<a href="/examples/1">Item `</a>
			</li>
			<li>
				<a href="/examples/1">Item 2</a>
			</li>
		</ul>
	</nav>
</div>
```

2. Run the application

3. See error and popup not working.

**Comment by Sarenor** [comment]
Did you follow the steps in "Configure your project" on https://www.skeleton.dev/utilities/popups ?

Sadly can't link the headline yet, that's slated for the next update.

**Comment by endigo9740** [comment]
@MisterJimson As Sarenor mentioned Popups come with a new dependency. It's only required if you use the popup feature, but I realized this was absent from the migration guide in the release notes, so I've append that.

This should be your fix, but let us know if the issue continues and we'll reopen the ticket. Thanks!

**Comment by MisterJimson** [comment]
I did notice that and did install @floating-ui/dom, the issue persists. I can try getting a full reprod.

**Comment by endigo9740** [comment]
@MisterJimson thanks for confirming. I've reopened this for now.

Can you confirm you followed the setup instructions in your root layout shown in the documentation:
https://www.skeleton.dev/utilities/popups

![image](https://user-images.githubusercontent.com/1509726/220803523-8a33d47b-dc8e-4e92-a1ef-1878f14d558f.png)

**Comment by MisterJimson** [comment]
Yep that was the problem, my bad. For some reason I skimmed too quickly over that part and missed. Maybe the error message could be better if the `storePopup.set` hasn't been called. I could look into a PR for this if there is interest.
