### ISSUE TITLE
Expose Additional Floating-UI Props for popup

### ISSUE THREAD

**Issue by DevOfManyThings** [skeletonlabs/skeleton#1014]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Expose additional options for popup to take advantage of more floating-ui features.

**Compute Position**
This needs the `strategy` option available: https://floating-ui.com/docs/computePosition#strategy

**Middleware**
`size`: https://floating-ui.com/docs/size
`autoplacement`: https://floating-ui.com/docs/autoPlacement
 `hide`: https://floating-ui.com/docs/hide
`inline`: https://floating-ui.com/docs/inline

There's also a typo in the docs where it's typed 'middelware' [here](https://www.skeleton.dev/utilities/popups), and in the interface as 'Middlware` [here ](https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/utilities/Popup/types.ts
)

This is prompted from the discussion on discord [here](https://discord.com/channels/1003691521280856084/1077974624320622653)

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Adding one more feature request: hover delay time

**Comment by endigo9740** [comment]
Another request: better error handling when the action fails to discover the paired popup element (or it's missing outright)

**Comment by endigo9740** [comment]
Implemented as part of: https://github.com/skeletonlabs/skeleton/pull/1421
