### ISSUE TITLE
Popup cause weird scrolling behaviour

### ISSUE THREAD

**Issue by gwww** [skeletonlabs/skeleton#1018]
### Current Behavior

Using Skeleton .132.5; Firefox 110.0

Goto https://www.skeleton.dev/utilities/popups

Tap Menu Popup; tap Close Me.
Tap Dropdown menu. Select Books.

Scroll down. Page gets "stuck" right above the "Create a Popup" header. By stuck is mean I cannot scroll any further down the page.

### Steps To Reproduce

See above.

### Anything else?

I can reliably reproduce this in both Firefox and Chrome.

**Comment by endigo9740** [comment]
I've seen this as well. I'll look into this asap. Thanks Gwww!

**Comment by endigo9740** [comment]
Seems to be fixed as part of the incoming documentation updates on our dev branch.

Make sure to do a hard refresh on the page first (shift + refresh in the browser), then try this:

https://dev.skeleton.dev/utilities/popups

**Comment by endigo9740** [comment]
Reopening as this appears to still be present.

**Comment by endigo9740** [comment]
After QUITE a lot of time and effort, I've finally managed to track this issue down. There's a small one-line paragraph on the documentation that was the source of my confusion here:
https://floating-ui.com/docs/autoUpdate

Specifically it says:
> Only call this function when the floating element is open on the screen.

I missed this, which mean that I had mistakenly implement the autoUpdate to basically run continuously all the time. This has been changed to only run when a popup is open, only a single instance will be affected at a time, and best of all it cleans up after itself now when the popup closes.

In addition to fixing the page scroll issue, this also means our popups will be MUCH more performant across the board. In fact I can't emphasize how critical an update this was.

Thanks @gwww and everyone involved in reporting this. This should be a huge quality of life improvement going forward!

Please be aware this update will drop at part of the v1.0 release later this week. Thanks!
