### ISSUE TITLE
InputChips will submit a form when trying to delete one

### ISSUE THREAD

**Issue by Auros** [skeletonlabs/skeleton#1025]
### Current Behavior

On `0.132.5`, when trying to delete a chip from the `InputChip` component when that InputChip is in a `<form>`, will cause the form to submit early.

### Steps To Reproduce

1. Put an InputChip component inside of a `<form>`
2. Add a chip to the component.
3. Delete that chip
4. Form will submit

### Anything else?

This was introduced with b1a4ba28d1e79adcf475700d68d220936c0afccb, when the individual chip was changed from a `<span>` to a `<button>` with no type specified, so by default it submits the form when clicked.

**Comment by endigo9740** [comment]
Thanks Auros, I know exactly what this is - should be an easy fix. Thanks for reporting it.
