### ISSUE TITLE
Accordion: Prevent AccordionItem from opening when property is set

### ISSUE THREAD

**Issue by mc-0bit** [skeletonlabs/skeleton#1026]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Just like how `locked={true}` on Steps prevents Steppers to continue, it would be great to be able to prevent specific AccordionItems from opening. 

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Sounds more a disabled state, correct? Can you elaborate on the use case. I'm just curious.

**Comment by mc-0bit** [comment]
> Sounds more a disabled state, correct?

Yes.

> Can you elaborate on the use case. I'm just curious.

One use case would be that users can take on modules where they have to complete specific tasks. However, some tasks may depend on other tasks to be finished before they can be completed. Users will be able to complete tasks by submitting their result from within the AccordionItems content. (Not implemented yet) ![image](https://user-images.githubusercontent.com/77062151/220983940-66aa852b-c5b4-4afa-a56c-cf0f1befe0de.png)

The other use case is locking some items when the user does not have the required subscription to access them. (I am still not sure if I want to go down that route but it is a possibility)

**Comment by endigo9740** [comment]
Hmm, seems like a scenario that the Stepper solves. Any particular reason you went with an Accordion instead?

**Comment by endigo9740** [comment]
Thanks for sharing. This does seem to have some overlap with the role of the Stepper component. I'll noodle on this a bit longer before we make a knee jerk reaction. I can't say I've ever seen someone use an Accordion in that fashion.

The first thing we'll need to do is determine if this works within the guidelines provided by the WAI-ARIA APG guidelines:
https://www.w3.org/WAI/ARIA/apg/patterns/accordion/

At a glance, the only seem to describe the opposite behavior -> if the panel is open and can't be closed:

> If the accordion panel associated with an accordion header is visible, and if the accordion does not permit the panel to be collapsed, the header button element has [aria-disabled](https://w3c.github.io/aria/#aria-disabled) set to true.

**Comment by endigo9740** [comment]
@mc-0bit Sorry for the delay in returning to this. The v1.0 launch ended up taking most of our attention.

After reviewing for a bit I don't think we'll be able to implement this as requested. Per the ARIA APG guidelines mentioned above, only the opposite behavior seems to documented (set disabled to keep open). For Skeleton we prioritize a11y, which means we're subject to the guidelines as stated.

The good thing is these components are all open source. If you wish, you can copy an instance of the Accordion/AccordionItem components into your local project, modify the behavior as desired, then utilize that version instead.

You can find the source for these here:
https://github.com/skeletonlabs/skeleton/tree/dev/src/lib/components/Accordion

Alternatively I might suggest reviewing the Stepper component or consider building a custom component of your own.

**Comment by mc-0bit** [comment]
I ended up just editing the title and content off the accordion items when it is not available, but still letting the user interact with them. This is probably the way disabled accordion items are supposed to behave per ARIA guidelines.
