### ISSUE TITLE
Rating Component

### ISSUE THREAD

**Issue by Rusty-Gopher-Phoenix-Nest** [skeletonlabs/skeleton#1028]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I could really use a decent rating component for a few of my projects. Would be nice to have option for color changes per "star", number labels. length option ( 5 stars or 10 for example) Icons like hearts or thumbs up as well as star. Tool tip descriptions. Half selections like 3.5 etc. 

Thank You.

![screenshot-quasar dev-2023 02 23-08_48_14](https://user-images.githubusercontent.com/103464118/220940963-803320a2-0b69-4bd9-8e10-a5b52869c087.png)

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

https://quasar.dev/vue-components/rating

more basic one:
https://primeng.org/rating

**Comment by Ilchampo** [comment]
I actually had to implement something like this for a personal project. I added as params the `maxRating`, `icon`, `color` and `rating`. This is the result:
![image](https://user-images.githubusercontent.com/24512262/221030430-d581c6aa-10e0-4579-9510-c59e7903547f.png)

I would love to contribute to this Skeleton UI with this. What else should I take in consideration for this component?

**Comment by endigo9740** [comment]
@Ilchampo if you have something turnkey ready to go, I'd recommend reading our Contribution guidelines here:
https://www.skeleton.dev/docs/contributing

They're a bit dated and due for a facelift soon, so don't be afraid to ask questions. But general idea is to send a draft PR and I'll audit and review and provide feedback when possible.

Just know we're swamped with some documentation focused updates at the moment, so my response time might be slower than normal.

**Comment by Ilchampo** [comment]
Totally understandable. I just read the guidelines, would like to contribute by implementing this!

**Comment by endigo9740** [comment]
I appreciate the offer @Ilchampo but let's let this simmer a bit longer if you don't mind. We have sooo many things cooking right now, I wouldn't be able to devote time to a proper set of guidelines or handle PR reviews right now. Let's circle back after the v1 launch, ok?

**Comment by jamess-ais** [comment]
bump :)

**Comment by endigo9740** [comment]
> I just wanted to mention this again because I don't see any plans for this going forward. Thanks

We close issues we don't plan to move forward on, typically with an explanation why. If there's a feature you would like to see implemented sooner consider contributing and sending a PR though. This is how open source works :)

**Comment by FarhanAliRaza** [comment]
Can i contribute in this?

**Comment by endigo9740** [comment]
@FarhanAliRaza actually @Mahmoud-zino sent a PR for this 5 minutes before you commented. He asked to take it on via Discord and we forgot to assign him here. Sorry for the miscommunication! Feel free to take a look at the PR and suggest feedback though.
