### ISSUE TITLE
Table of Contents refactor

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1030]
As part of the recent Doc Shell update we've identified several issues with the [Table of Contents](https://www.skeleton.dev/components/table-of-contents) component:

- [ ] We should abstract the permalink/header id generator away from this component
- [ ] This component should become a "dumb" interface that just reacts to either manually or auto-assigned values
- [ ] https://github.com/skeletonlabs/skeleton/issues/1589
- [x] https://github.com/skeletonlabs/skeleton/issues/1143
- [x] https://github.com/skeletonlabs/skeleton/issues/1156

We should look to refactor this component to work in a more consistent manner.

**Comment by endigo9740** [comment]
New issue reported here: https://github.com/skeletonlabs/skeleton/issues/1438

**Comment by endigo9740** [comment]
https://github.com/skeletonlabs/skeleton/issues/1589

**Comment by Mahmoud-zino** [comment]
@endigo9740 can you please assign this to me, so we don't duplicate our efforts 😄.

**Comment by Sarenor** [comment]
you should also watch #1741 :)

**Comment by endigo9740** [comment]
This is done and will come as part of v2, so closing this issue out
