### ISSUE TITLE
Change so the modal is not a child of the backdrop so it can be blurred.

### ISSUE THREAD

**Issue by saturnonearth** [skeletonlabs/skeleton#1032]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I wanted to add a CSS blur to the backdrop region for my modal, but cannot do it as blur affects all children of the DIV.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Hey @saturnonearth, this is actually possible. We had a dedicated property for this, but it looks like it got nuked in a recent refactor. But I'll keep this ticket as a means to add it to back.

In the meantime, you can accomplish this using the following prop:

```html
<Modal regionBackdrop="bg-surface-backdrop-token backdrop-blur" />
```

This does two things:

- Persists the default backdrop color (thought you can change if you wish)
- Uses the [backdrop blur](https://tailwindcss.com/docs/backdrop-blur) utility class to blur the elements visible through the backdrop background

Keep an eye out for the next release and I'll aim to implement a dedicated `blur` prop that will allow you to specify this directly. Thanks!

**Comment by saturnonearth** [comment]
Ah yes` backdrop-blur-sm` works perfectly!
