### ISSUE TITLE
Stack based Modal Navigation

### ISSUE THREAD

**Issue by risalfajar** [skeletonlabs/skeleton#1034]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Currently, the Modal system is based on Queue (FIFO) principle. But in terms of navigation, a Stack (LIFO) is more commonly used.

Also, with the current system, a currently showing modal can't show another modal unless it has been closed **and** all the modals have been called/triggered beforehand:
```js
[1, 2, 3].forEach((dNum: number) => {
	const d: ModalSettings = {
		type: 'alert',
		title: `Modal ${dNum}`,
		body: `The modal body of ${dNum}.`
	};
	modalStore.trigger(d);
});
```

Transitioning to Stack based allows more control and customization, like:
1. A modal can have a child modal or shows another modal without closing itself.
2. Showing multiple modals at once is possible, if needed (by overriding Modal. svelte). This can be useful in some case since a Component Modal will lose its states when closed.

### What type of pull request would this be?

Enhancement

**Comment by risalfajar** [comment]
One suggested approach is to change `modalStore.close()` to use `pop()` instead of `shift()`, and replace any `$modalStore[0]` with `$modalStore[$modalStore.length - 1]` (or better, create a variable like `$modalStore.current`).
This is a breaking change though.

And for showing multiple modals at once, we can replace:
```svelte
{#if $modalStore.length > 0}
    {#key $modalStore}
```
in `Modal.svelte`, with 
```svelte
{#each $modalStore as store, index (index)}
```

Happy to create a PR if approach is approved.

**Comment by saturnonearth** [comment]
I would love to have overlapping modals. This is super useful if you want to alert the user when closing a modal, incase their work may be lost. 

Examples...

![image](https://user-images.githubusercontent.com/12503538/229000559-33ddab18-3f8e-4b4c-a1d8-5e70986dd9c5.png)

![image](https://user-images.githubusercontent.com/12503538/229000714-4789ec58-d06d-419f-a2d8-aa5e08f1fd27.png)

Placement would be important too. You want to anchor to the top of existing modal or center, or even be outside in it's own global space.

To not introduce a breaking chance, could there be a way to add a setting between creating a queued modal, and overlapping modal? Default would be queued, so no breaking change.

**Comment by Beiri22** [comment]
I also need to trigger stacked Modals as described here.

**Comment by endigo9740** [comment]
Yeah for anyone wondering, I'm still brainstorming this. We would have to find a way that doesn't cause layout issues (lots of modals on a small screen) and doesn't frustrate the user as described above. It sometimes takes a while to circle back to this, but it has remained in our queue because we plan to revisit at some point in the future.

**Comment by rskvazh** [comment]
Very requested feature. Simple use case: Delete button inside modal which should show a Prompt modal over it (or instead, but reopen previous if needed)

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2357
