### ISSUE TITLE
Typo in Quick Start

### ISSUE THREAD

**Issue by fidst** [skeletonlabs/skeleton#1037]
https://github.com/skeletonlabs/skeleton/blob/060db65d43b8ea6b3f060bd160f87afb27de5a5a/src/routes/(inner)/docs/quickstart/%2Bpage.svelte#LL77C3-L77C3

```
       </section>
		<a class="btn variant-filled-primary" href="https://kit.svelte.dev/" target="_blank" rel="noreferrer">SvelteKit</a>
		<a class="btn variant-filled-secondary" href="https://tailwindcss.com/" target="_blank" rel="noreferrer">Tailwind</a>
		<a class="btn variant-filled-tertiary" href="https://github.com/" target="_blank" rel="noreferrer">GitHub</a>
	</section>
```

should be

```
	<section>
		<a class="btn variant-filled-primary" href="https://kit.svelte.dev/" target="_blank" rel="noreferrer">SvelteKit</a>
		<a class="btn variant-filled-secondary" href="https://tailwindcss.com/" target="_blank" rel="noreferrer">Tailwind</a>
		<a class="btn variant-filled-tertiary" href="https://github.com/" target="_blank" rel="noreferrer">GitHub</a>
	</section>
```

/section -> section

**Comment by endigo9740** [comment]
Thanks @fidst, we have an on going effort to resolve issues like this after some technical prerequisite updates to our doc site. If you come across similar issues going forward please report it here:
https://github.com/skeletonlabs/skeleton/issues/783

For now I'll reference this issue in that ticket for you. Thanks for the heads up!
