### ISSUE TITLE
Set column width for one column (auto size the rest)

### ISSUE THREAD

**Issue by rconnol** [skeletonlabs/skeleton#1038]
### Current Behavior

for tailwind - they have a table-fixed option that will let you set the width instead of auto-sizing your columns for you
and I would like to set the width for the first column and have every other column get "auto-sized"

I have tried setting !w-[50px] on simultaneously on the table header and table data - but it just ignores it (specifically for the very first column)
the only way I can get it to allow me to set the width is by changing the table class (but that jacks up the formatting pretty badly and I would have to size all of the columns myself...)

### Anything else?

It was suggested I make a bug ticket for this issue in the following discord conversation:

https://discord.com/channels/1003691521280856084/1078736064237281393/1078736064237281393

**Comment by endigo9740** [comment]
@rconnol I apologize for not thinking of this sooner, but we do actually offer a way to do this is you're just creating a native HTML table and using our Tailwind Element styles for it:

https://www.skeleton.dev/elements/tables

![Screenshot 2023-03-07 at 4 06 33 PM](https://user-images.githubusercontent.com/1509726/223564456-6aaf6057-f19e-4697-8d35-de7e77f18a76.png)

You'll need to apply `.table-cell-fit` to both the header cell, as well as the matching body cell. When you do so, that column will then adjust to fill the width of the contents within.

Here's a quick example:

```html
<div class="table-container">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Position</th>
				<th class="table-cell-fit">Name</th>
				<th>Symbol</th>
				<th>Weight</th>
			</tr>
		</thead>
		<tbody>
			{#each tableArr as row, i}
				<tr>
					<td>{row.position}</td>
					<td class="table-cell-fit">{row.name}</td>
					<td>{row.symbol}</td>
					<td>{row.weight}</td>
				</tr>
			{/each}
		</tbody>
	</table>
</div>
```

If you need something similar for the Table component, then let me know and we'll flip this from a bug ticket to a feature request, as that's something that will need to be implemented as an addition.

Additionally, with the right selectors, you should be able to apply the styles for this using vanilla CSS. Here's how the class works:
https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/styles/elements/tables.css#L100

And here's the reference source:
https://stackoverflow.com/questions/11267154/fit-cell-width-to-content
