### ISSUE TITLE
Lightswitch with no background and props bgDark not applying style

### ISSUE THREAD

**Issue by parotech123** [skeletonlabs/skeleton#1042]
### Current Behavior

With release 0.132.4 the lightswitch is not applying the correct background color and the props "bgDark" and "bgLight" are not applying the correct class

![immagine](https://user-images.githubusercontent.com/49280466/221350495-f77d8a7d-126e-42fd-b9ef-d5ae18cae00a.png)
![immagine](https://user-images.githubusercontent.com/49280466/221350502-8b7a7d50-f146-4c72-b24c-66b5fc222f7f.png)

### Steps To Reproduce

1. Create a new sveltekit project
2. in +page.svelte import the Lightswitch module
3. Launch the app and see the defect.

**Comment by parotech123** [comment]
so with playing a bit with it, it seems like applying height="h-6" resolve the issue. is this intended?

**Comment by JustBarnt** [comment]
@parotech123 No this was an accidental typo in the props for height, this has already been fixed and will be updated in the next release :) so just make a note that during the next release you can remove that prop.

**Comment by parotech123** [comment]
thanks for the update!

**Comment by parotech123** [comment]
thanks for the notification. .sure will do
