### ISSUE TITLE
Minor bug on Docs Site

### ISSUE THREAD

**Issue by riziles** [skeletonlabs/skeleton#1044]
### Link to the Page

https://www.skeleton.dev/utilities/popups

### Describe the Issue

This is a minor bug, and I know you guys are working on overhauling the docs site, so apologies if this has already been caught.

If I go to [Popups](https://www.skeleton.dev/utilities/popups) and select one of the items in the "combobox" example then for some reason the "on this page" links on the right no longer work.

I'm using Google Chrome on a Windows PC.

### Are you able to create a Pull Request with the fix?

None

**Comment by endigo9740** [comment]
This is a duplicate https://github.com/skeletonlabs/skeleton/issues/1018

**Comment by riziles** [comment]
> This is a duplicate #1018

Ahh, sorry. I saw that but did not realize is was the same issue.
