### ISSUE TITLE
`LightSwitch` does not render correctly

### ISSUE THREAD

**Issue by MLNW** [skeletonlabs/skeleton#1046]
### Current Behavior

On a fresh site bootstrapped with the Skeleton CLI the `LightSwitch` component does not render correctly. I would expect a visual rendering like this:

![grafik](https://user-images.githubusercontent.com/20930814/221404373-be52f373-393c-4eac-b8b0-22cd25abcf9b.png)
![grafik](https://user-images.githubusercontent.com/20930814/221404380-0e29bd2b-7326-4b10-b7fe-0d89dad5abc6.png)

But what I get is this:

![grafik](https://user-images.githubusercontent.com/20930814/221404399-695f8e73-81fa-46a9-ae1c-f6abc7ee7dac.png)
![grafik](https://user-images.githubusercontent.com/20930814/221404408-00d7e51c-e3ad-4830-87ce-c460cd40d3fe.png)

Test with both Firefox (main driver) and Chrome. Same result.

### Steps To Reproduce

1. Create new site with Skeleton CLI
2. Add `LightSwitch` component anywhere
3. Observe that the toggle does not render correctly

**Comment by garlandcrow** [comment]
I saw that too and (temporarily because I suspect this is a bug) fixed it by adding `height="h-6"`

**Comment by MLNW** [comment]
> I saw that too and (temporarily because I suspect this is a bug) fixed it by adding `height="h-6"`

I can confirm this fixes the issue

**Comment by JustBarnt** [comment]
@garlandcrow @MLNW Yup! This has been addressed and will be fixed in the next release :). I would make a comment to remind yourselves to delete this, when the next update is released!

**Comment by endigo9740** [comment]
Alright found, fixed, and part of the next release as of 5 days ago:
https://github.com/skeletonlabs/skeleton/pull/1004
