### ISSUE TITLE
Module '"@skeletonlabs/skeleton' has no exported member 'storePopup"

### ISSUE THREAD

**Issue by carlskii** [skeletonlabs/skeleton#1048]
### Link to the Page

https://www.skeleton.dev/utilities/popups

### Describe the Issue

Hi, 

I'm following the docs for popup utility here: https://www.skeleton.dev/utilities/popups

However, I'm getting a "Module '"@skeletonlabs/skeleton' has no exported member 'storePopup" error for both the popup and popupStore. 

<img width="871" alt="Screenshot 2023-02-27 at 00 20 15" src="https://user-images.githubusercontent.com/555399/221446631-7826bc82-5ccb-436e-8516-b6e3f52be190.png">

### Are you able to create a Pull Request with the fix?

None

**Comment by endigo9740** [comment]
@carlskii We put out a quick hotpatch to resolve this. Make sure you're using the `x.x.5` version here:
https://github.com/skeletonlabs/skeleton/releases/tag/0.132.5

**Comment by carlskii** [comment]
Hi, yes I'm already using v0.132.5  - same problem.

**Comment by Sarenor** [comment]
Could you share a repository or a minimum reproduction?

**Comment by carlskii** [comment]
Sorry first push didn't have the popup code - just re-pushed

**Comment by endigo9740** [comment]
Hmm, I'm not sure what's up. The export is there and I'm seeing it when testing in a new project:

![Screenshot 2023-02-27 at 9 46 22 AM](https://user-images.githubusercontent.com/1509726/221610869-d61d2582-f602-4b73-b365-8e7571b7ef0b.png)

I see the export present when I browse `/node_modules/@skeletonlabs/skeleton/index.js`:

![Screenshot 2023-02-27 at 9 48 06 AM](https://user-images.githubusercontent.com/1509726/221611550-4bd4359b-0d8c-44a1-861d-339297381136.png)

Can you run `npm list` in your project directory within your terminal and provide the output here please. I know your package.json lists the `.5` version, just want to confirm.

**Comment by Sarenor** [comment]
You're missing floating-ui in your package.json.

**Comment by endigo9740** [comment]
Ahh, this is why early morning debugging is bad :) Thanks Sarenor!

**Comment by carlskii** [comment]
OK - So fixed that it was installed, just not in the package.json.

Getting this now. 
```
proxy.js?v=5c081724:15 [HMR][Svelte] Unrecoverable HMR error in <Root>: next update will trigger a full reload
logError @ proxy.js?v=5c081724:15
Proxy<Root> @ proxy.js?v=5c081724:380
initialize @ client.js?v=5c081724:432
_hydrate @ client.js?v=5c081724:1757
await in _hydrate (async)
start @ start.js:22
(anonymous) @ (index):4558
Promise.then (async)
(anonymous) @ (index):4557
+page.svelte? [sm]:35 Uncaught (in promise) ReferenceError: popup is not defined
    at mount (+page.svelte? [sm]:35:48)
    at targetCmp.$$.fragment.m (svelte-hooks.js?v=5c081724:291:24)
    at mount_component (index.mjs:1949:26)
    at Object.mount [as m] (root.svelte? [sm]:42:82)
    at Object.mount [as m] (+layout.svelte? [sm]:9:53)
    at Object.mount [as m] (AppShell.svelte:53:81)
    at mount_component (index.mjs:1949:26)
    at mount (+layout.svelte? [sm]:46:8)
    at targetCmp.$$.fragment.m (svelte-hooks.js?v=5c081724:291:24)
    at mount_component (index.mjs:1949:26)
```

**Comment by Sarenor** [comment]
Try:
```ts
import { popup } from '@skeletonlabs/skeleton';	
```
instead of
```ts
import type { popup } from '@skeletonlabs/skeleton';
```

**Comment by carlskii** [comment]
OK so that fixed that problem, no I'm seeing: 

```
proxy.js?v=5c081724:15 [HMR][Svelte] Unrecoverable HMR error in <Root>: next update will trigger a full reload
logError @ proxy.js?v=5c081724:15
Proxy<Root> @ proxy.js?v=5c081724:380
initialize @ client.js?v=5c081724:432
_hydrate @ client.js?v=5c081724:1757
await in _hydrate (async)
start @ start.js:22
(anonymous) @ (index):4558
Promise.then (async)
(anonymous) @ (index):4557
floating-ui.dom.browser.mjs:6 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'ownerDocument')
    at getWindow (floating-ui.dom.browser.mjs:6:39)
    at isNode (floating-ui.dom.browser.mjs:59:27)
    at getNodeName (floating-ui.dom.browser.mjs:36:10)
    at getParentNode (floating-ui.dom.browser.mjs:297:7)
    at getNearestOverflowAncestor (floating-ui.dom.browser.mjs:313:22)
    at getOverflowAncestors (floating-ui.dom.browser.mjs:330:30)
    at autoUpdate (floating-ui.dom.browser.mjs:593:202)
    at popup (popup.js:188:5)
    at mount (+page.svelte? [sm]:33:48)
    at targetCmp.$$.fragment.m (svelte-hooks.js?v=5c081724:291:24)
```

Is there any chance you can post a working example.

**Comment by endigo9740** [comment]
@carlskii we're actively working on some improvements to our documentation.

Maybe give the new popup section a glance?
https://dev.skeleton.dev/utilities/popups

Every documentation section includes a "page source" option, so here's what that looks like:
https://github.com/skeletonlabs/skeleton/blob/master/src/routes/(inner)/utilities/popups/%2Bpage.svelte

Our doc site is built on top of Skeleton, so it's a functional Skeleton app. Just note we reference imports locally rather than through the `@skeletonlabs/skeleton` page, so be sure to adjust accordingly.

**Comment by carlskii** [comment]
Thanks. I just did this. In the https://github.com/skeletonlabs/skeleton/blob/master/src/routes/(inner)/utilities/popups/%2Bpage.svelte where does `DocsShell` and `import { DocsFeature, type DocsShellSettings }` come from ?

**Comment by endigo9740** [comment]
@carlskii Those are custom feature for our documentation page structure. You can disregard those. Just focus on the items that make use of `popups`

**Comment by marke-dev** [comment]
Uncaught (in promise) TypeError: Cannot destructure property 'computePosition' of 'get_store_value(...)' as it is undefined.
```
"@floating-ui/dom": "^1.4.5",
"@skeletonlabs/skeleton": "^2.4.0",
"@skeletonlabs/tw-plugin": "^0.2.3",
```
popup.js file
```
export const storePopup = writable(undefined);
export function popup(triggerNode, args) {
const { computePosition, autoUpdate, offset, shift, flip, arrow, size, autoPlacement, hide, inline } = get(storePopup);
....
```

**Comment by Sarenor** [comment]
While I appreciate the comment, this issue is incredibly old and the solution you found is also very well documented: https://www.skeleton.dev/utilities/popups#installation

Are you facing any other issues @marke-dev ?
