### ISSUE TITLE
Audit and Improve Doc Content

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1049]
Per: https://github.com/skeletonlabs/skeleton/issues/783

The goal of this ticket will be to divvy up ownership of several sections of the documentation. Each volunteer will be assigned an allotment of pages that they will own. You should audit, review, and either submit feedback - or better yet send a PR with fixes and adjustments in place.

## How to Participate

> **Warning** please DO NOT volunteer if you cannot have your changes completed by Sunday March 5th.

1. Reach out in the `#docs-overhaul` channel on [Discord](https://discord.gg/EXqV7W8MtY) to volunteer
    - Post your GitHub username (I'll assign you below)
    - Let us know which section you wish to be assigned
2. Immediately create a draft PR (pull request), including your checklist as shown below ([reference](https://www.skeleton.dev/docs/contributing))
    - Important: You will not be considered assigned until a draft PR is available
4. As you complete changes per page, commit it, then tick the box in the PR to alert everyone of your progress
5. Set your PR to "ready for review" when all sections are complete
6. Finalize all changes by Sunday March 5!

### Can't submit a PR?

View the dev branch docs here:
https://dev.skeleton.dev/docs/introduction

You can still help by locating issues for other volunteers, reviewing the blog posts, or helping with PR reviews. When submitting feedback, tag the assigned user, or consider keeping feedback feedback localized in each PR thread. Use a checklist so we can tick off items as completed!

## Responsibilities 

> Try to follow any obvious existing conventions. Contact a contributor on Discord for additional questions!

- Scan the page for typos, grammar, etc (including each tab)
- Check the page for broken links
- Keep headings short, consistent, and semantic to the section (no wrapping in Table of Contents)
- Keep paragraph text short, concise, and descriptive - ideally 1-2 lines max
- Use `h2` for main headers, `h3` for subheaders
- Use `<section class="space-y-4">...</section>` to divide page sections
- `prop`, `slots` and `event` tab data is auto-documented via inline JSDocs comments ([reference](https://www.skeleton.dev/docs/contributing/documentation))
- Ensure auto-documented tables aren't missing props (it happens!) and descriptions are semantic
- The `classes`, `params`, and `keyboard` tabs are manually maintained, which means more room for error
- Avoid inserting Font Awesome icons in code snippets - Skeleton is icon library agnostic!
- On CodeBlock snippets remove trailing indents so that they are not copied over to the clipboard

> See the [Doc Updates](https://github.com/skeletonlabs/skeleton/issues/783) comments for suggestions made by other users.

## Standby Volunteers

Folks that aren't committing to any section, but are available to help scan for issues or check other's work:

- @riziles
- @SebasF1349 
- @dirk-bester
- (Hugos)

## Source

- `/src/lib/{category}/{feature}` - the library features themselves (components, element styles, etc)
- `/src/routes/{category}/{feature}` - the documentation pages for each respective feature

### Blog (open/anyone)

> **Note** - review each blog post. Scan for out of data info, typos, etc. Report issues in the comments below.

### Tailwind - Group 1 ([oatnog](https://github.com/oatnog))

PR: (not yet available)

- [ ] Core
- [ ] Typography
- [ ] Forms
- [ ] Alerts
- [ ] Badges

### Tailwind - Group 2 ([DukeRupert](https://github.com/DukeRupert))

PR: (not yet available)

- [x] Breadcrumbs
- [x] Buttons
- [x] Cards
- [x] Chips
- [x] Lists
- [x] Logo Clouds
- [x] Placeholders
- [x] Tables
- [x] Gradient Headings

### Svelte - Group 1 ([niktek](https://github.com/niktek))

PR: [1054](https://github.com/skeletonlabs/skeleton/pull/1054)

- [x] Clipboard
- [x] Filters
- [x] Focus Trap
- [x] Accordions
- [x] App Bar
- [x] App Rail
- [x] App Shell
- [x] Avatars
- [x] Conic Gradients
- [x] File Buttons
- [x] File Dropzone
- [x] Input Chips

### Svelte - Group 2 ([RyanTheGuy](https://github.com/RyanTheGuy))

PR: https://github.com/skeletonlabs/skeleton/pull/1055 (ready for review!)

- [x] Listboxes
- [x] Paginators
- [x] Progress Bars
- [x] Progress Radials
- [x] Radio Groups
- [x] Range Sliders
- [x] Slide Toggles
- [x] Steppers
- [x] Tabs
- [x] Tables
- [x] Table of Contents

### Utilities ([DukeRupert](https://github.com/DukeRupert))

PR: https://github.com/skeletonlabs/skeleton/pull/1071

- [x] Code Blocks
- [x] Drawers
- [x] Lightswitch
- [x] Local Storage Store
- [x] Modals
- [x] Toasts
- [x] Popups

### Docs Sections - Group 1 (@Sarenor)

PR: https://github.com/skeletonlabs/skeleton/pull/1084

- [x] Docs > Introduction
- [x] Docs > Get Started
- [x] Docs > Colors
- [x] Docs > Styling
- [x] Docs > Design Tokens
- [x] Docs > Variants
- [x] Docs > Theme generator
- [x] Docs > Quickstart

### Docs Sections - Group 2 (@Sarenor)

PR: https://github.com/skeletonlabs/skeleton/pull/1086

- [x] Docs > Contributing > Requirements
- [x] Docs > Contributing > Style Guide
- [x] Docs > Contributing > Documentation Guide
- [x] Routes > Templates > +page.svelte
- [x] README
- [x] Page footer

### Homepage

- See: https://github.com/skeletonlabs/skeleton/issues/1070

**Comment by niktek** [comment]
Just FYI that on my screen I'm seeing:
<img width="921" alt="image" src="https://user-images.githubusercontent.com/52020637/221745743-678b24f8-e84b-48a5-8780-d27af7b98679.png">

And also saw the highlight of current section in TOC disappear too.

**Comment by endigo9740** [comment]
Browser support indicators should be hardcoded to use green/yellow/red rather that using theme colors. They don't always keep the same meaning in other themes:

![image](https://user-images.githubusercontent.com/1509726/221757637-19e6e3dd-9e81-4c6a-bb3e-50273aa58c37.png)

![image](https://user-images.githubusercontent.com/1509726/221757679-8685ba33-51cc-4a32-891e-82b1d8a3e1fd.png)

**Comment by endigo9740** [comment]
Doc Shell header has a typo for Element pages:

![image](https://user-images.githubusercontent.com/1509726/221758263-970f7577-8d57-4135-aca4-fde85416c67d.png)

**Comment by RyanTheGuy** [comment]
Accessibility is spelled "Accessability" In several places outside my section, Modals, Drawers, Forms, and Focus-trap

**Comment by endigo9740** [comment]
The above "global" issue above have been addressed per https://github.com/skeletonlabs/skeleton/pull/1051

**Comment by endigo9740** [comment]
- [ ] After some back and forth, I think we'll be wise to go ahead and reimplement a small, minimal blurb on the Utility features that rely on stores and bring back the SSR warning. Here's the original markup for that:

```html
<h2>SvelteKit SSR Warning</h2>
<p>
	Be aware that there are <a
		href="https://github.com/sveltejs/kit/discussions/4339#discussioncomment-2384978"
		target="_blank"
		rel="noreferrer">known issues when using Svelte stores with SSR</a
	>, such as our drawer store. To prevent these issues please avoid the use of the drawer store within any SvelteKit Load function.
	Likewise, if you need a drawer to open on route initilization we advise triggering the <code>open()</code> method after the
	<a href="https://kit.svelte.dev/docs/modules#$app-environment" target="_blank" rel="noreferrer"
		>SvelteKit Browser environment context</a
	> is available.
</p>
<CodeBlock
	language="ts"
	code={`
import { browser } from '$app/environment';\n
if (browser) drawerStore.open(settings);
	`}
/>
<p>
	For additional context please see this <a href="https://github.com/skeletonlabs/skeleton/pull/580" target="_blank" rel="noreferrer"
		>thread</a
	>.
</p>
```

However, I think what I'd rather do is explain this in a external post - perhaps a Wiki page here on GitHub, and link to that rather than trying to explain this over and over per each of these features. It's not really our duty to police this, but there's no harm in giving it a shoutout to help educate folks.

**Comment by riziles** [comment]
Moving [this comment](https://github.com/skeletonlabs/skeleton/pull/1054#issuecomment-1452812586) here per @endigo9740 's [request](https://github.com/skeletonlabs/skeleton/pull/1054#issuecomment-1452902790).

@niktek , seems to be a minor issue on 

https://skeleton-docs-oi8f3pcbb-skeleton-labs.vercel.app/components/app-shell 
 |-> slots -> header

I believe this is the offending line: https://github.com/niktek/skeleton/blob/f4a0fa09a55f9f69d93f2e56d85bb79c1288a8c0/src/lib/components/AppShell/AppShell.svelte#L3

**Comment by Sarenor** [comment]
[] run a final global find & replace for abitrary -> arbitrary

**Comment by endigo9740** [comment]
@Sarenor the roadmap extensions post v1 will happen after the v1 launch and require some group meetings and planning. We have a lot of loose ideas, we just need to formalize those. Likewise we need to factor in my time, which will be devoted mainly to Skeleton Lab's project for a bit.

**Comment by Sarenor** [comment]
@endigo9740 All good, I guessed as much :)
We just link to the roadmap a couple of times and having it say "The road to v1.0" after 1.0 is something to fix, but not immediately.

Could do a temporary replace after the v1 launch: "Chris takes a well deserved rest" until you're back from resting and we had time to plan :)

**Comment by riziles** [comment]
- [ ] issue with Theme Generator page not loading correctly

If I enable preview on the Theme Generator, go to a different page and then come back to the Theme Generator then the page does not load correctly. Chrome dev tools shows the following error:

```
uncaught (in promise) cannot read properties of null (reading 'ownerDocument')
```

**Comment by endigo9740** [comment]
@riziles I've split your issue off to it's own ticket here: https://github.com/skeletonlabs/skeleton/issues/1105

With this I'd recommend that all remaining text changes come in as individual reports or PRs. I'm marking this complete for now.
