### ISSUE TITLE
Table of Contents Navigator on Docs stops functioning after changing internal tabs

### ISSUE THREAD

**Issue by RyanTheGuy** [skeletonlabs/skeleton#1052]
### Link to the Page

https://dev.skeleton.dev/components/listboxes

### Describe the Issue

This was found on the link attached, but is the same regardless of page. The "On This Page" table of contents on any docs page stops working as soon as the user changes tabs to props or slots or what have you.

To recreate
- Attempt navigation with table of contents
- Change tab to "props"
- Return to default "usage" tab
- Attempt navigation and it will fail

### Are you able to create a Pull Request with the fix?

None

**Comment by endigo9740** [comment]
Thanks @RyanTheGuy

**Comment by endigo9740** [comment]
@RyanTheGuy essentially what's happening here is the ToC checks the target region of the page for headers on load, and builds a list of target elements that it can scroll to. However, when you were to tab away, the contents of those elements (the headings) are destroyed and then recreated you tab back. As a result the ToC sees those as new/different elements and it fails to properly refresh and rebuild the queried list of headings.

To fix this, I'm now using a Svelte Key block which will update and re-render this list when a particular key value passed in as a prop is updated. This not only fixes the issue at hand, it means it will also switch to show headings under the other tabs. Such as the Accordion Props tab, which has the Accordion + AccordionItem headings. It's kind of neat so I'm gonna roll with it.

Thanks for the catch on this!
