### ISSUE TITLE
LogoCloud breakpoint

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#1057]
### Current Behavior

<img width="570" alt="image" src="https://user-images.githubusercontent.com/52020637/221758843-6b1021f4-51a0-4c8f-a422-114f74daddaf.png">
 
My half screen is finding all the wonky breakpoints!

**Comment by endigo9740** [comment]
Seems to be a quirk of rendering it within the preview given the thick padding. Man, container queries need to be widely available already!

**Comment by niktek** [comment]
Merged into responsive ticket
