### ISSUE TITLE
Responsive design audit

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1058]
### Link to the Page

(whole site)

### Describe the Issue

Given the recent doc page redesign and new preview elements, let's do another sweep to check for responsive issues throughout the site. We've already started to see a few creep up as part of the documentation content audit.

### Are you able to create a Pull Request with the fix?

No

**Comment by endigo9740** [comment]
- [ ] Just FYI that on my screen I'm seeing the TOC hide partially offscreen:

<img width="921" alt="image" src="https://user-images.githubusercontent.com/52020637/221745743-678b24f8-e84b-48a5-8780-d27af7b98679.png">

And also saw the highlight of current section in TOC disappear too.

**Comment by endigo9740** [comment]
![image](https://user-images.githubusercontent.com/1509726/221762035-743093b5-003e-492e-9026-3d0261d62b60.png)

**Comment by niktek** [comment]
![](https://user-images.githubusercontent.com/52020637/221758843-6b1021f4-51a0-4c8f-a422-114f74daddaf.png)

fix by going 3x2
