### ISSUE TITLE
allow `unstyle` class to inhibit `<del>`/`<ins>` typography

### ISSUE THREAD

**Issue by obayemi** [skeletonlabs/skeleton#1060]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

right now it is impossible to prevent skeleton from styling <del> and <ins>

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/styles/typography.css

**Comment by endigo9740** [comment]
Fixed as part of:
https://github.com/skeletonlabs/skeleton/pull/1061

@obayemi if you use `fixed #1061` it'll link the issue and PR so that the former is closed when the latter is merged.

Some GitHub magic! :)

**Comment by obayemi** [comment]
oh yes thx, I thought just mentioning the issue was enough :sweat_smile:
