### ISSUE TITLE
Sveld props not always showing

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#1072]
### Current Behavior

Some props are not being exported by sveld properly on the docs pages e.g. RadioItem only gets 2 of it's 4 exported props.  Changing the JSDoc block to be the expanded form with an `@type {foo}` in it seems to be reliably fixing it so far.    Just needs to be flagged for the type'ing pass before this goes 1.0

**Comment by endigo9740** [comment]
Currently working through this, should have something ready soon. One thing to take not of, backtick such as (`) appear to trip Sveld up. They're not parsed, even if otherwise it's a valid string.
