### ISSUE TITLE
Lightswitch setters imports wrong functions

### ISSUE THREAD

**Issue by stantonius** [skeletonlabs/skeleton#1074]
### Link to the Page

https://www.skeleton.dev/utilities/lightswitches

### Describe the Issue

Small one, but the current setter imports reference (I assume) old function imports. 

```
import { setUserPrefers, setMode } from '@skeletonlabs/skeleton';
```

should be

```
import { setModeUserPrefers, setModeCurrent } from '@skeletonlabs/skeleton';
```

Thanks for your efforts on this whole project btw. Its an awesome library.

### Are you able to create a Pull Request with the fix?

Yes

**Comment by Sarenor** [comment]
While We'd appreciate the PR, there's currently a big Doc Overhaul ongoing, including for the Utilities section:
https://github.com/skeletonlabs/skeleton/pull/1071

I'll cross post this over there :)

**Comment by endigo9740** [comment]
This appears to have been fixed during the documentation update, so I'm going to close this out.
