### ISSUE TITLE
AppRailTile example not valid svelte "Classes can only be applied to DOM elements, not components"

### ISSUE THREAD

**Issue by kasperlaursen** [skeletonlabs/skeleton#1075]
### Link to the Page

https://www.skeleton.dev/components/app-rail

### Describe the Issue

Creating the app using the CLI and pasting the example causes error.
<img width="895" alt="image" src="https://user-images.githubusercontent.com/8472619/222459605-e2d2b3e1-ff24-49b1-b188-13c2f63ebce8.png">

"Classes can only be applied to DOM elements, not components"

### Are you able to create a Pull Request with the fix?

No

**Comment by Sarenor** [comment]
https://dev.skeleton.dev/components/app-rail
Already fixed in the updated docs :)
