### ISSUE TITLE
Issues with `setInitialClassState` in LightSwitch

### ISSUE THREAD

**Issue by knd775** [skeletonlabs/skeleton#1076]
### Current Behavior

In production builds, the lightswitch is pretty flaky. It seems to be caused by an issue with the following line: https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/utilities/LightSwitch/LightSwitch.svelte#L65

The function string ends up minified, but the function call does not. Leading to this:
![image](https://user-images.githubusercontent.com/1235055/222479589-7303a403-9eca-47de-b054-dc5ff599e0e1.png)

It also sometimes gets injected into the head twice, but I haven't been able to figure out a pattern there.

**Comment by endigo9740** [comment]
@knd775 Can you provide a bit more information about your production build. Are you using a particular adapter, are your modifying the SSR at all?

Also it's not clear from your post, but you're not importing that method and using it alongside the Lightswitch correct? Everything should occur automatically, the imports are purely if you want to inspect and use the getters/setters that we use internally within the component. Typically for rolling your own lightswitch UI.

We've clarified this the upcoming doc revisions, but essentially you pick one and not mix and match. Just to ensure we're on the same page.

**Comment by knd775** [comment]
I'm not modifying the SSR process at all, and am using the vercel adapter. I am using the `LightSwitch` component on the page, and that's it. No manual function calls or anything.

I think the problem comes from `setInitialClassState.toString()` being within curly brackets, thus treated as js, and `setInitialClassState();` technically just being a string stuck on the page.

**Comment by knd775** [comment]
I figured out a solution using IIFE (immediately-invoked function expressions). Functionally identical, but works in all cases and doesn't rely on any specific adapter behavior. I'll submit a PR shortly.

**Comment by knd775** [comment]
I actually just checked the production docs site, and the issue is present there as well. It's just hidden by the fact that `setInitialClassState` is in the global scope (for some reason) 
![image](https://user-images.githubusercontent.com/1235055/222495767-cb479469-1c8a-47c2-bd9f-a47a3aa7d86d.png)
