### ISSUE TITLE
Only the left third of the FileDropzone is clickable in firefox

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#1078]
### Current Behavior

![image](https://user-images.githubusercontent.com/31982384/222711600-e4598709-e2eb-441f-b9f0-aebb288c8dcc.png)
The left third is clickable, the other parts of the Dropzone aren't

### Steps To Reproduce

Opening the Skeleton Docs for the FileDropzone with Firefox.

**Comment by endigo9740** [comment]
The hidden input field was not stretched to cover the entire width of the element. Here's the issue visualized:

![Screenshot 2023-03-07 at 5 14 50 PM](https://user-images.githubusercontent.com/1509726/223575829-d9bb89c6-2ad8-4712-8a95-9134a95cbc22.png)
