### ISSUE TITLE
Loading state for buttons

### ISSUE THREAD

**Issue by omar2205** [skeletonlabs/skeleton#1079]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Adding a loading (spinner) for buttons with custom text (please wait...)

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
This is already possible @omar2205, just combine any button element with a Progress Radial set to indeterminate mode.

- https://www.skeleton.dev/elements/buttons
- https://www.skeleton.dev/components/progress-radials

The result would be something like this:
https://tailwindcss.com/docs/animation#spin

All you would need to do is use Svelte `#if` conditions to modify the contents of the button during the loading/complete states
