### ISSUE TITLE
AppRail: click event not fired

### ISSUE THREAD

**Issue by Shackless** [skeletonlabs/skeleton#1082]
### Current Behavior

The click event of the AppRailTile component is not raised.

### Steps To Reproduce

```svelte
<script lang="ts">
   import { AppRail, AppRailTile } from '@skeletonlabs/skeleton';

   const handleClick = () => {
      console.log('clicked'); // never called
   }
</script>

<AppRail>
   <svelte:fragment slot="lead">
      <AppRailTile title="My Action" on:click={handleClick}>
         <svg ... />
      </AppRailTile>
   </svelte:fragment>
</AppRail>
```

### Anything else?

I also tried an inline function like `on:click={() => console.log('clicked')}` with no success.

**Comment by bennymi** [comment]
Hi @Shackless, I just had a quick look at the source code and I believe you still need to provide a `value` prop to `AppRailTile`. Then the click event will work as well.

**Comment by Shackless** [comment]
Hi @bennymi, thanks for the fast reply but unfortunately that does not fix it.

**Comment by bennymi** [comment]
@Shackless `AppRail` has an `active` prop. So you could set up `AppRail` with the store and your `AppRailTile` with a `value` and then give the `active` prop the same classes as the non-active states have. That way you can't tell a difference between a selected and non-selected state, but it will still fire. That might be a quick workaround?

About the API functionality, I'm not sure what the right approach here is. @endigo9740  can answer that better.

**Comment by Shackless** [comment]
@bennymi Ah yeah, thanks. I just set `$selectedTileStore` back to its initial value which selected nothing. This way other tiles can still look selected. Thank you!

As for the API: My suggestion would be to name your custom event `selected` and propagate `click` the usual "DOM" way like one would expect.

**Comment by endigo9740** [comment]
@Shackless @bennymi our dispatched `click` event when clicking the tile wasn't working as expected. I'm still not quite certain why, but there's a bit of a trick in Svelte where if you have a dispatched event AND a event forward, both will work fine in unison.

By doing this, this should provide what you're seeing, a way to create a simple tile with no tag or value, and just listen to the click event. In fact I've updated the documentation for the first item (hamburger menu icon) to use this.

Here's the changes:
https://github.com/skeletonlabs/skeleton/pull/1110/files

Here's the example of the simple click-only tile:
https://github.com/skeletonlabs/skeleton/blob/dev/src/routes/(inner)/components/app-rail/+page.svelte#L48

Hope this helps!
