### ISSUE TITLE
Appshell Sidebar !overflow-x-visible

### ISSUE THREAD

**Issue by Rar9** [skeletonlabs/skeleton#1092]
### Current Behavior

Buttons and Popups will not overflow outside the sidebars

![Screenshot-05-03-23-11-27-21](https://user-images.githubusercontent.com/2239608/222954958-a411e6da-f1a8-492d-a738-a9127c5f4502.png)

see 
https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/components/AppShell/AppShell.svelte#L36

### Steps To Reproduce

```html
<script>
	import '@skeletonlabs/skeleton/themes/theme-skeleton.css';
	import '@skeletonlabs/skeleton/styles/all.css';
	import '../app.postcss';

	import { AppShell } from '@skeletonlabs/skeleton';

	export let switchSideBar = false;
</script>

<AppShell>
	<!-- SideBar -->
	<svelte:fragment slot="sidebarLeft">
		<div
			id="sidebar-left"
			class="!overflow-x-visible bg-white dark:bg-gradient-to-r dark:from-surface-800 dark:via-surface-700
			dark:to-surface-500 text-center h-full relative border-r-2
			{switchSideBar ? 'w-[225px]' : 'w-[100px]'}"
		>
			<div class="bg-error-500">Sidebar Left</div>
			<!-- sidebar collapse button -->
			<button on:click={() => (switchSideBar = !switchSideBar)}>
				{#if !switchSideBar}
					<div class="btn variant-filled-primary absolute top-10 -right-5 rounded-full border-2 ">
						N
					</div>
				{:else}
					<div class="btn variant-filled-warning absolute top-10 -right-5 rounded-full border-2 ">
						W
					</div>
				{/if}
			</button>
		</div>
	</svelte:fragment>

	<slot />
</AppShell>

```

**Comment by endigo9740** [comment]
@Rar9 I'm actually not quite certain why, but it seems the Y-axis needs to be set visible as well. I altered the styles a bit in my local test version, but here's the result:

![Screenshot 2023-03-07 at 5 55 02 PM](https://user-images.githubusercontent.com/1509726/223582511-91a8a2d2-88d8-43a8-a0ec-1e1a90c5035a.png)

You'll need to make three changes:

1. Remove the wrapping `div` directly within your `<svelte:fragment slot="sidebarLeft">`
2. Move your style classes to the AppShell prop that targets the left sidebar
3. Add both `!overflow-x-visible !overflow-y-visible`

Here's a simplified version of what that might look like:

```html
<AppShell slotSidebarLeft="!overflow-x-visible !overflow-y-visible bg-white dark:bg-gradient-to-r dark:from-surface-800 dark:via-surface-700 dark:to-surface-500 text-center h-full relative border-r-2 {switchSideBar ? 'w-[225px]' : 'w-[100px]'}">
	<!-- SideBar -->
	<svelte:fragment slot="sidebarLeft">
		<div class="bg-error-500">Sidebar Left</div>
		<!-- sidebar collapse button -->
		<button on:click={() => (switchSideBar = !switchSideBar)}>
			{#if !switchSideBar}
				<div class="btn variant-filled-primary absolute top-10 -right-5 rounded-full border-2 ">
					N
				</div>
			{:else}
				<div class="btn variant-filled-warning absolute top-10 -right-5 rounded-full border-2 ">
					W
				</div>
			{/if}
		</button>
	</svelte:fragment>
	<slot />
</AppShell>
```

**Comment by Rar9** [comment]
But the appshell seams wrong as there are more slots like header/footer/sidebarright... That would be affected by overflow-visible then as well?

**Comment by endigo9740** [comment]
Perhaps you're thinking about the generic `class` attribute that would affect the parent element within the app shell. But by using `slotSidebarLeft` we only target those styles towards that one single slot. The other slots will not be affected.

![image](https://user-images.githubusercontent.com/1509726/223625335-75ac60e0-717d-44a7-841c-fc6e1d95a2e4.png)
