### ISSUE TITLE
Oncontextmenu

### ISSUE THREAD

**Issue by cycle4passion** [skeletonlabs/skeleton#1094]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Please forward oncontextmenu events for all components. This should allow it to be used for more complex right-click options like popups creating custom context menus.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Duplicate of: https://github.com/skeletonlabs/skeleton/issues/819
