### ISSUE TITLE
Button Groups Hover Effect outside the borders

### ISSUE THREAD

**Issue by fabi-flex** [skeletonlabs/skeleton#1096]
### Current Behavior

Docs > Tailwind > Buttons

If you have a theme with rounded buttons selected, the hover effect is visible outside the Borders.
You can see it in the picture below.

<img width="951" alt="image" src="https://user-images.githubusercontent.com/127057963/222989607-818fb23a-81e4-498a-a5e3-1c364398f82c.png">

### Steps To Reproduce

You can see it in the Documentation.

### Anything else?

I am still completely new to programming, I'm sorry if I am using this IssueTool incorrectly.
I just noticed it and wanted to let you guys know.

Have a nice day! Thanks for the great work

**Comment by ryceg** [comment]
Hey @fabi-flex I'm trying to reproduce this and am having some troubles. Can you provide exact steps for replication?

**Comment by niktek** [comment]
Also be handy to know what OS, what browser and the steps for the theme setup - did you just select Crimson ? did you make your own selections on the Theme Generator ?  Did you do this on the https://skeleton.dev version or on https://dev.skeleton.dev

**Comment by endigo9740** [comment]
Likewise I've tried and failed to replicate this. We'll need more info, including a code sample to test.

**Comment by fabi-flex** [comment]
I'm on this site: https://www.skeleton.dev/elements/buttons

System: Safari Version 16.3, Apple Macbook with M1

Yes, I selected the Crimson theme from the menu in the top right.
It also happens with the Sahara theme (I think every theme with rounded buttons).

The theme generator is not in the live preview mode.

**Comment by endigo9740** [comment]
Thanks @fabi-flex, it's subtle on some of the other themes but I do see it now. It does look to be a Safari-specific issue, so I think that's the piece of the puzzle we were missing. 

I'm not seeing it on our dev version of the library, but it's using a different variant here, which could be why. I'll look test the two other variants soon and reply back here with my findings:
https://dev.skeleton.dev/elements/buttons

**Comment by endigo9740** [comment]
I've found the issue, it's actually one I've run into with Safari in the past:
https://stackoverflow.com/a/58283449

A fix has been put in place and this will come as part of the next release. This will resolve the issue for both the horizontal and vertical modes.
