### ISSUE TITLE
Lightswitch width is applied twice instead of height

### ISSUE THREAD

**Issue by breadthe** [skeletonlabs/skeleton#1097]
### Current Behavior

The Lightswitch component is not rendered correctly because there are two width classes applied to it instead of width + height. Here's how it looks:

![CleanShot 2023-03-05 at 12 14 46](https://user-images.githubusercontent.com/17433578/222988941-e4012458-8cb6-4f04-8fce-0ae596f96a5d.gif)

This is the rendered code I see in dev tools:

```
<div class="lightswitch-track cursor-pointer transition-all duration-[200ms] w-12 w-6 ring-[1px] ring-surface-500/30 rounded-token bg-surface-50 " role="switch" aria-label="Light Switch" aria-checked="true" title="Toggle Dark Mode" tabindex="0">
  <div class="lightswitch-thumb aspect-square scale-[0.8] flex justify-center items-center transition-all duration-[200ms] w-6 rounded-token bg-surface-900 translate-x-[100%]">
    <!-- SVG markup -->
  </div>
</div>
```

Notice `w-12` and `w-6`.
I propose that `w-6` should be `h-6` instead.
Because `w-6` is applied after `w-12` it overrides it. When I remove the `w-6` the component renders correctly:

<img width="112" alt="CleanShot 2023-03-05 at 12 23 39@2x" src="https://user-images.githubusercontent.com/17433578/222989272-4b8913c7-d032-489e-97ee-8c596096106c.png">

### Steps To Reproduce

1. Using Lightswitch
2. Without any props, or overriding the width prop
3. When the component renders
4. It renders incorrectly due to `w-6` overriding the existing (correct) `w-12`, or other width classes (up until w-24) that might be applied

### Anything else?

Interestingly, if I try to use the `width` prop to override the default `w-12`, nothing happens until `w-24`, once again thanks to how the browser prioritizes class precedence. See these examples:

❌ w-12 w-6 - `w-6` takes precedence
<img width="231" alt="CleanShot 2023-03-05 at 12 27 50@2x" src="https://user-images.githubusercontent.com/17433578/222989633-e13e67a5-c9e2-4a6f-bd1c-72f22a94cf29.png">

❌ w-16 w-6 - `w-6` takes precedence
<img width="231" alt="CleanShot 2023-03-05 at 12 28 30@2x" src="https://user-images.githubusercontent.com/17433578/222989642-80409472-361e-4780-a4ac-f6467bb3c71f.png">

❌ w-20 w-6 - `w-6` takes precedence
<img width="209" alt="CleanShot 2023-03-05 at 12 28 51@2x" src="https://user-images.githubusercontent.com/17433578/222989646-29fab280-0477-4850-974b-fa2e2d311f64.png">

✅ w-24 w-6 - `w-24` takes precedence
<img width="222" alt="CleanShot 2023-03-05 at 12 29 22@2x" src="https://user-images.githubusercontent.com/17433578/222989651-d19b3c43-4e22-42e0-8708-c7d9c9f8959c.png">

**Comment by breadthe** [comment]
I realized this was fixed in https://github.com/skeletonlabs/skeleton/pull/1004 but not yet tagged. Since I'm on v0.132.5 I don't yet have the latest changes.

Apologies for the trouble and keep up the good work!

**Comment by endigo9740** [comment]
@breadthe the fix has not been released, but will come with the next release.

**Comment by breadthe** [comment]
> @breadthe the fix has not been released, but will come with the next release on March 11

Excellent! I should have done more due diligence before opening this.
