### ISSUE TITLE
Improvements to Theme Configuration

### ISSUE THREAD

**Issue by Eric-Arz** [skeletonlabs/skeleton#1098]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Disclaimer: I have only used skeleton for one small side project so i am not an expert and may not be aware of all options that are currently available.

From what i know the only/recommended way to create and use custom themes that are not provided by skeleton out of the box is by creating a css file by using the theme generator that is provided by the docs or write one yourself from scratch. While this certainly works, there are some issues with this approach:

- It kind of is counter intuitive for developers that are familiar with the default way of doing theming with tailwind

- After you have created your custom theme, the generator essentially becomes useless.  If you want to do some minor changes later you basicly have to edit the css file directly. There is now way to import your currently used theme to make further adjustments.

- Your are kind of depended on the generator in the docs. If there are ever breaking changes migrating looks kind of problematic. The documentation about the theme class selectors you can/need to provide seems to be a bit lackluster.

After having used other tailwind based extensions and component libraries like daisyUi i think it should be possible to do themeing by using the default tailwind configuration through the skeleton plugin. 

This is what it could rougly look like inside tailwind.config:

```
skeleton: {
    themes: [
      {
        name: {
          "primary": "#39a642",
          "secondary": "#377CFB",
          "success": "#36D399",
          "warning": "#FBBD23",
          "error": "#F87272",         
          ... 
        }
      },
    ],
  },
```

Alt least for me personally, i think this would really improve the developer experience for skeleton. I would also be inclined to help work on this myself if this is something you actually want to add. I really like skeleton and the stuff you are doing here. I believe this is really something that is going to bring the svelte ecosystem forwards. So props for that.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Our Tailwind plugin implements theme colors per Tailwind's recommendation here:
https://tailwindcss.com/docs/customizing-colors#using-css-variables

You can view this here:
https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/tailwind/theme/colors.cjs

Our plugin in modulate, so this is but one part of the entire plugin:
https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/tailwind/core.cjs#L8

**Comment by Eric-Arz** [comment]
Maybe i am missing something but while this certainly explains how exactly this currently works and follows their docs for using css variables it is not something that allows you to define your theme just by using tailwind.config like other tailwind based libraries do, which was the intention of my feature request.

**Comment by endigo9740** [comment]
@Eric-Arz, perhaps there's a bit of a miscommunication here. There's nothing stopping you from extending the theme using the standard Tailwind config. Follow the instructions here and you can add as many colors as you wish:
https://tailwindcss.com/docs/customizing-colors#using-css-variables

We cannot however, automatically generate [design tokens](https://www.skeleton.dev/elements/tokens) and extended set of Tailwind theme color. There's no mechanisms in Tailwind that would allow us to do this at present.

But the good news is here is you can still use these colors with Tailwind, you'll just need to use the standard format for this, imagining that `foo` represents the name of your custom color:

```
bg-foo-500
border-foo-500
fill-foo-500
```

If you wish to replicate a design token, the good news is they're not hard to produce individually. For example, let's take a built-in token such as `.bg-surface-50-900-token`. Here's how we generate that:

```css
.bg-surface-50-900-token {
    @apply bg-surface-50 dark:bg-surface-900;
}
```

That's it, that's all it's doing. If you wish to explore how we generate other tokens, you can find the logic here:
https://github.com/skeletonlabs/skeleton/tree/dev/src/lib/tailwind/tokens

We're also around both here and on Discord if you have a question about a particular one.
