### ISSUE TITLE
Serve Fonts locally

### ISSUE THREAD

**Issue by mschmdb** [skeletonlabs/skeleton#1112]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Hi,

would love to have documentation how to serve fonts locally.
Just like with _@layer base_ from tailwind.

### What type of pull request would this be?

Docs

### Any links to similar examples or other references we should review?

See current discussion in Discord: 1083050887875919883

**Comment by endigo9740** [comment]
Reported fixed on Discord:

![image](https://user-images.githubusercontent.com/1509726/223941674-dce7ec1b-6ce6-4a46-ac92-6acc71df869e.png)
