### ISSUE TITLE
Confirm modal only has 2 return types

### ISSUE THREAD

**Issue by sidharthv96** [skeletonlabs/skeleton#1118]
### Current Behavior

If we ask a user for confirmation, they currently have 2 options, Yes(`true`)/No(`false`).

But, there should be a third option, Cancel(`undefined`), which is returned if the user closes the dialog by clicking outside the modal. 

### Anything else?

I can work on a PR if the approach is approved.

**Comment by endigo9740** [comment]
@sidharthv96 I think this is a good idea for specificity, but this is riding the line of being a breaking issue. Some folks may have built their logic to expect the cancel and backdrop click to work the same way. If we find we're getting a lot of issues reported for this we may opt to revert the change.

@Sarenor @JustBarnt @SebasF1349 pinging you on this so you can help me monitor for support issues when this release drops.

**Comment by sidharthv96** [comment]
Thank you @endigo9740 !

**Comment by Sarenor** [comment]
Actually @sidharthv96 how would the behaviour differ between cancel and no? 🤔 

The breakage should probably be low, I expect most people have just used
```js
if(r) {
  //do the confirmed action
}
```

**Comment by sidharthv96** [comment]
Suppose there is an editor, the user hits the close button with unsaved changes. 

The dialogue had `Close without saving` & `Save and Close` as the options. There was no option to close the dialogue without closing the editor. 

Now, if we click outside, the dialogue can disappear, without closing the editor.
