### ISSUE TITLE
Unable to add class to RadioItem

### ISSUE THREAD

**Issue by gwww** [skeletonlabs/skeleton#1119]
### Current Behavior

Adding `class="<some class>"` is explicitly removed from RadioItem here: https://github.com/skeletonlabs/skeleton/blob/master/src/lib/components/Radio/RadioItem.svelte#L51. As a result I'm unable to use Tailwind classes to tailor the appearance of a RadioItem.

Work arounds are possible, e.g.: using a global style. 

Some discussion here: https://discord.com/channels/1003691521280856084/1083254085047832586

**Comment by Sarenor** [comment]
You should be able to provide any custom classes in the exported props:
```js
        export let rounded: CssClasses = getContext('rounded');
	export let padding: CssClasses = getContext('padding');
	export let active: CssClasses = getContext('active');
	export let hover: CssClasses = getContext('hover');
	export let color: CssClasses = getContext('color');
	export let fill: CssClasses = getContext('fill');
```
Tbf, they sound like they only take specific classes, but padding & rounding are always applied

**Comment by gwww** [comment]
That’s a good work around! Since I want to adjust padding I could put font size in that class list. 

I’ll play around some more.

**Comment by endigo9740** [comment]
@gwww Got a quick fix in place for this. This will be part of the next release this weekend!

**Comment by gwww** [comment]
Thanks! So much appreciated! Glad I can help, even if it’s not code contributions.
