### ISSUE TITLE
Tab Panel Transitions

### ISSUE THREAD

**Issue by cycle4passion** [skeletonlabs/skeleton#1136]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Like accordion was a special use case where it made a lot of sense to use a built in slide transition, I would like tab panel changes to be able to fade in/out and slide left/right (newly added built in svelte transition [Slide Axis](https://github.com/sveltejs/svelte/issues/6182)

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
I'm going to go ahead and fold this under a larger pending update to animations system wide in Skeleton. Please feel free to track progress here from this point forward:

- https://github.com/skeletonlabs/skeleton/issues/1322#issuecomment-1535420780
