### ISSUE TITLE
Tooltip for inputs is missing

### ISSUE THREAD

**Issue by kiryasolod** [skeletonlabs/skeleton#1138]
### Current Behavior

Hi, dear developing team! In previous version (0.99.5) there was a tooltip which I could import from the library:
`import { tooltip } from "@skeletonlabs/skeleton";`
Now there is no such component, so the following code
```
<label class="input-label" use:tooltip={{content: account_token_description, position: "bottom", inline: true, width: "!w-full"}}>
    <span>{$json("splash.register.token")}:</span>
    <input type="text" id="account_token" bind:value={account_token} required  class={is_account_token_valid ? "input-success" : "input-error"}>
</label>
```
doesn't work for me anymore. Of course I could stay at 0.99.5 version or use some placeholder instead of tooltip but still it would be better to have the same or richer functionality in newer versions instead of getting it poorer
If there is a different way how to do what I want in new version, please tell me
Thank you!

**Comment by endigo9740** [comment]
Hey @kiryasolod, we've actually merged the two features we called "tooltips" and "menus" into our new Popup feature:
https://www.skeleton.dev/utilities/popups

This does everything those did, but in a much more accurate, extensible, and performant manner. The syntax is fairly similar as well, just note this does come with the dependency of Floating UI:
https://floating-ui.com/

Which is the successor of the very popular:
https://popper.js.org/

Full instructions for integration are provided on the doc page above.

**Comment by kiryasolod** [comment]
Thanks very much! I just applied a new Popup feature, it works!
Happy coding! :)
