### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'response')

### ISSUE THREAD

**Issue by lcclcoder** [skeletonlabs/skeleton#1139]
### Current Behavior

When I click outside of the modal I get this error:

Uncaught TypeError: Cannot read properties of undefined (reading 'response')
    at onClose (Modal.svelte:59:22)
    at HTMLDivElement.onBackdropInteraction (Modal.svelte:55:5)

When I close the Modal the modal via modalStore.close() the error does not come up. 

### Steps To Reproduce

1. Setup TestComponent:
```
<script lang="ts">
	import { modalStore } from '@skeletonlabs/skeleton';
	export let parent: any;
</script>
<div>
	<header class={parent.regionHeader}>{$modalStore[0]?.title ?? '(title missing)'}</header>
	<main class={parent.regionMain}>{$modalStore[0]?.body ?? '(body missing)'}</main>
	<footer class="modal-footer {parent.regionFooter}">
		<button on:click={() => modalStore.close()}>Close</button>
	</footer>
</div>
```

2. Setup and trigger the modal in +layout.svelte
```
<script lang="ts">
         import { Modal, modalStore } from '@skeletonlabs/skeleton';
         import TesComponent from '$lib/components/TesComponent.svelte';

	function modalTest() {
		modalStore.trigger({
			type: 'component',
			component: { ref: TesComponent },
			title: 'Test Modal'
		});
	}
</script>

<Modal />
<button on:click={modalTest}> click </button>
```

3. Close the modal by clicking outside the modal

**Comment by lcclcoder** [comment]
This can be fixed by adding optional chaining to the onClose function:

    function onClose(): void {
        if ($modalStore[0]?.response) $modalStore[0].response(false);
        modalStore.close();
    }

**Comment by endigo9740** [comment]
@lcclcoder I can't replicate this in our custom modals, so I'm going to assume you were just self reporting your a fix for your own issue. I'll go ahead and close this out then.
