### ISSUE TITLE
TableOfContents it is not shown if it is mounted more than once

### ISSUE THREAD

**Issue by rammsesgit** [skeletonlabs/skeleton#1143]
### Current Behavior

If we put the TableOfContents component in a Drawer, the TableOfContents will showed only the first time.

### Current behavior:
https://user-images.githubusercontent.com/22653743/224597117-22eae4b6-d253-476d-aa41-519fe945bd9e.mp4

### Expected behavior (before version 1.0.0):
https://user-images.githubusercontent.com/22653743/224597595-c7d0efe6-ed79-4846-a69d-11cde09eb0f8.mp4

### Steps To Reproduce

1. Set a `Drawer` with `TableOfContents` on `routes/+layout.svelte`:
```
...
<Drawer>
	<TableOfContents target="#toc-target" />
</Drawer>
...
``` 

2. Open the `Drawer` from a page (Ex. `routes/+page.svelte`) with some content:
```
<script lang="ts">
	import { drawerStore } from '@skeletonlabs/skeleton';
</script>

<button class="btn variant-ghost-primary" on:click={() => drawerStore.open()}>Show TOC</button>

<div id="toc-target">
	<h2>Heading 2</h2>
	<h3>Heading 3</h3>
	<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit.</p>
</div>
```

3. Close the Drawer clicking outside.
4. Try to reopen the Drawer.

**Comment by endigo9740** [comment]
Grouping this task under a combined ticket here so all work can be addressed in unison:
https://github.com/skeletonlabs/skeleton/issues/1030
