### ISSUE TITLE
Add class="dark" to app.html is missing in manual instructions

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#1146]
### Link to the Page

https://www.skeleton.dev/docs/get-started -> Manual Tab

### Describe the Issue

https://discord.com/channels/1003691521280856084/1084745868361605154/1084747397470638151

### Are you able to create a Pull Request with the fix?

None

**Comment by Sarenor** [comment]
I'm able to create a PR, just need to figure out where to place it. Tailwind-Config?

**Comment by endigo9740** [comment]
We sent folks to the Lightswitch docs in the past, which had this. Not sure which approach would be bettr

**Comment by saostad** [comment]
The Lightswitch is what most people want anyway.

**Comment by endigo9740** [comment]
![Screenshot 2023-03-15 at 11 47 06 AM](https://user-images.githubusercontent.com/1509726/225381092-8e1737ca-7e01-4325-86c2-89a0442d79bd.png)
