### ISSUE TITLE
Animation bug in new documentation previews

### ISSUE THREAD

**Issue by MLNW** [skeletonlabs/skeleton#1148]
### Current Behavior

The new component previews in the documentation are great but their animation seems bugged when the color swatch is activated. Without activating it switching between the preview and the code is snappy maybe even without any animation. But once the backgrounds swatch is activated switching between the code and the preview uses an animation that feels cut off.

Maybe this is intended behaviour, if so please just close the issue.

### Steps To Reproduce

![firefox_OiXOHqbuNZ](https://user-images.githubusercontent.com/20930814/224773344-be2bb033-715c-4c9e-8214-3987a351ffd2.gif)

**Comment by endigo9740** [comment]
The color palette closing is intended, but the animation isn't quite playing as expected. We'll look into it. Thanks
