### ISSUE TITLE
Is it possible to list in the docs the size of each components, in KB?

### ISSUE THREAD

**Issue by saturnonearth** [skeletonlabs/skeleton#1150]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I would love to get started with Skeleton, but one thing that I am always thinking about is the weight of every third-party component or tool that is being tacked on. I want to keep my site functional, but also light-weight. It would be very helpful if the base Skeleton framework, along with the components, had a size listed in the documents to make it easier to see what impact it may have.

### What type of pull request would this be?

Docs

**Comment by Sarenor** [comment]
The library takes up ~401KB in your node modules folder if we disregard the license, readme, etc. That's still with types included and before minification or gzipping.

I don't think breaking that done by component or fully gathering that number after minification and gzipping is going to be very helpful, especially with SvelteKits build process of bundling things per route, etc.

**Comment by endigo9740** [comment]
I agree with @Sarenor here, unless you can provide a compelling use case. Then I'm afraid this might just eat time time and resources to find a way to automate this process for very little gain.

Components are small by nature. Bundled CSS can be a bit impactful, but we have the upcoming Purge CSS feature to help with that. Your biggest offender when it comes to size and performance is almost always going to be large media files and blocking JS logic. I'd recommend you focus your attention there.

I can appreciate limiting external dependencies and in fact we do the same. But remember Skeleton is open source. You have full access to see everything going on under the hood. Feel free to look and check these things directly.
