### ISSUE TITLE
VSCode reordening imports

### ISSUE THREAD

**Issue by SebasF1349** [skeletonlabs/skeleton#1152]
### Link to the Page

https://www.skeleton.dev/docs/get-started#stylesheets

### Describe the Issue

There is a VSCode setting that reorders imports (and do a bit of clean up)
```
"editor.codeActionsOnSave": {
    "source.sortImports": true
}
```
This setting is disabled by default, so it's not so common. But it will break the stylesheets order that's needed for Skeleton to work. 

I found out that if the imports are separated (by a new line or comment) then they won't be sorted. So copy/pasting from the docs without modifying should be ok (if they add a comment or new blank line at the end before importing anything else)
						
¿Should a message about this be added to the current warning? ¿Or as it is too niche it should be left as it is? The message `Please be careful when adding or modifying these!` should cover this too.

### Are you able to create a Pull Request with the fix?

Yes

**Comment by endigo9740** [comment]
I'd love to see this added, I just know WHERE yet. Maybe under Intro > FAQs? We don't really have area dedicated to loose tips like this. Maybe onboarding? But I'd trying to keep that as simple as possible so not to overwhelm.

**Comment by Cucumberrbob** [comment]
From what I can see, vscode will only reorder _within each paragraph_ so if you separate each import by a newline or comment, it shouldn't reorder them.
Can you confirm that behaviour works for you? It does for me.

**Comment by SebasF1349** [comment]
@Cucumberrbob Yes, that's what I mentioned in the issue.

@endigo9740 I was thinking in adding it to the link mentioned (Get Started -> Stylesheets), but yeah, probably a section dedicated to answering common questions we encounter in the Discord server would be a better idea. I'm pretty sure mods can easily fill it.

**Comment by jameslounds** [comment]
🤦my readin skills need work, apologies

**Comment by MLNW** [comment]
When I start a new project with Skeleton I usually move the theme imports from the `+layout.svelte` to the top of `app.postcss`. 
I just tested this case and VS code does not change the order of the imports when they are in `app.postcss`.

Maybe the simplest solution would be to put the imports into the `app.postcss` file by default.

**Comment by Sarenor** [comment]
That's not quite how Svelte & SvelteKit recommend to handle this though, so we're unsure about recommending that and if it won't have unforeseen side effects & consequences.

As far as I know, I haven't taken a look at moving imports around like that in a bit.
If this is save, it'd be a nice fix for a couple of things.

**Comment by MLNW** [comment]
Could you point me to any documentation related to this recommendation? It'd be great to find out why its not recommended

**Comment by endigo9740** [comment]
@MLNW either SvelteKit or Svelte-Add always import the `app.postcss` inside the root layout, so we just follow their lead. There's not really a best or recommended here, it's preference. We just opt into that because it's a consistent method that works. We're not against folks importing their stylesheets in a stylesheet. But I'd like to do more testing before we commit fully.

Given this is somewhat off topic, I'd welcome another issue for this process.

**Comment by MLNW** [comment]
@endigo9740 just so we are on the same page: The current default is to generate a `+layout.svelte` file like this:

```svelte
<!-- +layout.svelte -->
<script lang="ts">
  import '@skeletonlabs/skeleton/themes/theme-skeleton.css';
  import '@skeletonlabs/skeleton/styles/all.css';
  import '../app.postcss';
</script>
```

I'm proposing to change that to:

```svelte
<!-- +layout.svelte -->
<script lang="ts">
  import '../app.postcss';
</script>
```

And adding the imports to the `app.postcss`:

```postcss
/* app.postcss */
@import '@skeletonlabs/skeleton/themes/theme-skeleton.css';
@import '@skeletonlabs/skeleton/styles/all.css';

/* place global styles here */
html,
body {
  @apply h-full overflow-hidden;
}
```

That way VS code does not reorder the imports and all styling is done in a single place, the `app.postcss`.

> As far as I know, I haven't taken a look at moving imports around like that in a bit. If this is save, it'd be a nice fix for a couple of things.

It would be interesting to know what other things this would be a fix for @Sarenor

**Comment by Sarenor** [comment]
We've had some reports that trying to @apply Skeleton classes work better when it's imported in the ``.postcss`` file, as far as I remember.
