### ISSUE TITLE
Add High/Low Contrast Themes for light sensitive users

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#1153]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

A Low-contrast, low-intensity theme. Potentially automatically selected when the low-contrast media query applies.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Per prior request in the PR, let's fold this into the same issue:
https://github.com/skeletonlabs/skeleton/issues/1154

**Comment by endigo9740** [comment]
This issue has been consolidated into the linked theme generator updates ticket.
