### ISSUE TITLE
Include a High-Contrast Theme for people with impaired color vision

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#1154]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Similar to https://github.com/skeletonlabs/skeleton/issues/1153 I'd like to include a high contrast theme for people with impaired color vision.

We've discussed this idea in the past and are generally on board with it afaik, this issue is just a formal note that it would be cool to include it.

Potentially automatically selected when the high-contrast media query applies.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

Vercel white on black was used as a reference previously.

**Comment by endigo9740** [comment]
Duplicate: https://github.com/skeletonlabs/skeleton/issues/1153
