### ISSUE TITLE
Table of contents - null if scanned container header include <span>

### ISSUE THREAD

**Issue by rdzialdowski** [skeletonlabs/skeleton#1156]
### Current Behavior

In every heading I'm using <span> tag with emoji (But bug exists also with usual text), before 1.0 it was flawless, now I've nulls all over the place:
![image](https://user-images.githubusercontent.com/102575434/225011038-7c50c7f3-b85c-44fe-bf45-0916476224ae.png)

### Steps To Reproduce

1. Include component TableOfContents 
2. In "target" element use something like `<h2><span>🧮</span>Test:</h2>`
3. See generated null

**Comment by endigo9740** [comment]
It was changed to support the deep linking feature. We don't want the anchor embedded within the anchor to affect the table of content label like (Foofoo). 

I'm tempting to close this and fold it under this ticket as the work is related.
https://github.com/skeletonlabs/skeleton/issues/1030

For now we'll leave this, but understand we'll need a larger rework before can begin to address issues like this. So I would recommend being patient for now.

**Comment by Sarenor** [comment]
If you don't absolutely need the <span>, I would suggest dropping it for now, that's probably the easiest way.

**Comment by endigo9740** [comment]
Grouping this task under a combined ticket here so all work can be addressed in unison:
- https://github.com/skeletonlabs/skeleton/issues/1030
