### ISSUE TITLE
Popup combobox focusable after closed

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1157]
### Current Behavior

Discord discussion here:
https://discord.com/channels/1003691521280856084/1084964126893281335/1084964126893281335

Essentially the combobox appears to still grab tab focus AFTER the listbox has been interacted with, even when it's closed.

### Steps To Reproduce

1. View the combobox: https://www.skeleton.dev/utilities/popups#combobox
2. Test tab focus without interacting with combobox - works as intended
3. Interact with the combobox and select a list item
4. Test tab focus - the hidden elements still take focus

### Anything else?

The popup feature toggles `display: block|hidden` on the popup element so I wouldn't expect this to be possible. We'll have to do some more research to figure out what's going on here.

**Comment by jamess-ais** [comment]
Using the following code tabbing to invisible/hidden items is completely possible;
```
<div tabindex="0">Tabbable due to tabindex.</div>
<div tabindex="0" class="hide">Tabbable due to tabindex.</div>

<div tabindex="0">Tabbable due to tabindex.</div>

<style>
  .hide{
    display: hidden;
  }
</style>
```
The way to fix this is manually disabling tabindex. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) tabindex reference. On line `79` of `ListBoxItem.svelte`: `tabindex="0"` should be `tabindex={open ? "0" : "-1"}`

**Comment by endigo9740** [comment]
@jamess-ais Thanks for testing and sharing this info. That's very interesting. Feel free to continue to test, but I might suggest leaving this one to me. I want to ensure I fully understand what's happening here in case it impacts other portions of Skeleton going forward.

I need to test how child element tabindex is taken into account here, as the popup is typically a wrapping or parent element of the selectable elements here.

**Comment by jamess-ais** [comment]
Awesome, I'll leave it up to you. I'm curious what you end up doing about it so please don't hesitate to @ me with your fix. I've come across similar issues in my own internal svelte library

**Comment by endigo9740** [comment]
By commenting you're subscribed to updates on this ticket. I'll try to remember to echo the solution found here, but worse case the PR will be linked containing whatever fix is implemented!

**Comment by Cucumberrbob** [comment]
https://github.com/skeletonlabs/skeleton/blob/eecd968ba194e202e267551e9594b6d042a9a981/src/routes/(inner)/utilities/popups/%2Bpage.svelte#L74
already done and merged

**Comment by endigo9740** [comment]
@Cucumberrbob well heck, that's awesome! Closing this out!
