### ISSUE TITLE
Update project dependencies 

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1163]
See Alan's message on Discord. I think new a11y warnings have been added we should address:
https://discord.com/channels/1003691521280856084/1048010639219642419/threads/1085779837232365658

Additionally now that we're past the launch let's go ahead and do our normal round of dependency updates. We're likely overdue.

**Comment by endigo9740** [comment]
Seems there may be new a11y warnings we'll need to address, per:
https://github.com/sveltejs/svelte/pull/8167#issuecomment-1470484745

**Comment by endigo9740** [comment]
Note: update Drawer fly transition for Svelte 3.57
https://twitter.com/geoffrich_/status/1636758087771258881

**Comment by dummdidumm** [comment]
FYI will relax some of these in https://github.com/sveltejs/svelte/pull/8402

**Comment by endigo9740** [comment]
Thanks for the heads up @dummdidumm!
