### ISSUE TITLE
App Bar spacing prop

### ISSUE THREAD

**Issue by jnaklaas** [skeletonlabs/skeleton#1171]
### Current Behavior

Using the App Bar component with custom spacing property, it still adds the default value to the output classes.
In case you don't need spacing, you have to add the `space-y-0` class as value.

Component:
```
<Appbar spacing="space-y-0"`></Appbar>
```

HTML output:
```
<div class="app-bar flex flex-col space-y-4 space-y-0  p-4" ...></div>
```

I'd expect it to work the same as the other props but it does not:

Component:
```
<Appbar spacing="" padding=""></Appbar>
```
Output:
```
<!-- expected -->
<div class="app-bar flex flex-col" ...></div>
<!-- actual -->
<div class="app-bar flex flex-col space-y-4" ...></div>
```

**Comment by endigo9740** [comment]
Good catch @jnaklaas. We can get that sorted. Should be as simple as moving the base style up to be the prop default value. If you need a short term solution try using `!` for important, such as `!space-y-0`.

**Comment by jnaklaas** [comment]
It actually works without the `!`, because the `space-y-0` class is placed after the default. Still, it would be cleaner if no classes are shown, like `padding=""` is behaving.

**Comment by endigo9740** [comment]
@jnaklaas Ha, yeah no worries. Class precedence doesn't work quite like style precedence, so that's bit us a few times as well. One of the biggest caveats to Tailwind I've come across, it's always a bit of a guessing game, so including `!` is good practice when you're overwriting in some capacity.
