### ISSUE TITLE
Nested trigger displayed in Toast section code blocks

### ISSUE THREAD

**Issue by kerembakir** [skeletonlabs/skeleton#1172]
### Link to the Page

https://www.skeleton.dev/utilities/toasts

### Describe the Issue

In the "No timeout" and "Adjusted timeout" code block example code sections the trigger code has been written twice; one nested inside of the other.

### Are you able to create a Pull Request with the fix?

No

**Comment by endigo9740** [comment]
Appending this as well as a visual reference:
![Uploading image.png…]()
