### ISSUE TITLE
Allow toast to appear above modals

### ISSUE THREAD

**Issue by fatstack** [skeletonlabs/skeleton#1173]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I'm not sure if this is intended or not, but it would be nice if toasts had the ability to appear above modals. Right now, toasts are shown underneath the modal backdrop on Skeleton 1.0.0.

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
This is 100% intended as we designate modals as the most pressing or critical information. Here's the z-index we use for either feature:

* Modals: `z-[999]`
* Toasts: `z-[888]`

This will remain our default in Skeleton, however if you would like to change this in your project you can add the following class to the Toast component:

```html
<Toasts class="!z-[1000]" />
```

Alternatively you can also control this via CSS within your global stylesheet `/src/app.postcss`:

```css
.snackbar-wrapper { @apply !z-[1000]; }
```

General idea is to set the wrapping Toast element (we call it a "snackbar") to the highest z-index value.

Hope this helps!

**Comment by fatstack** [comment]
Got it, thank you very much for the helpful reply @endigo9740 - I appreciate it!
