### ISSUE TITLE
Theme Generator should pick colors and settings of selected theme

### ISSUE THREAD

**Issue by delight** [skeletonlabs/skeleton#1179]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

By default the Theme Generator is set to the colors of the skeleton theme. 

It would be nice if the Theme Generator would be set automatically to the properties of the selected theme.
This would make it easy to tweak one of the provided themes to your liking.

### What type of pull request would this be?

Docs / Adjustment to  Theme Generator (DocsThemer) component.

**Comment by Sarenor** [comment]
Good idea, I'll note it down in the big Theme Generator Ticket if that's alright with you :)
