### ISSUE TITLE
Opting out of default styles

### ISSUE THREAD

**Issue by oganexon** [skeletonlabs/skeleton#1181]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

A few months ago, it was possible to choose which stylesheets to import into the +layout.svelte root.

However, this is no longer possible, I am now stuck with `all.css`.

```js
// This contains the bulk of Skeletons required styles:
import '@skeletonlabs/skeleton/styles/all.css';
```

Currently migrating a project entirely in tailwind to skeleton, the developer experience is terrible. I have to put `unstyled` classes everywhere to get what I want.

```html
<h1 class="unstyled truncate text-2xl font-bold text-token">Foo</h1>
```

One of the basic principles of tailwind is that there is no base style, it's up to the developer to choose which classes to put. I know it's a choice of this library to do otherwise, but at least let the developer decide.

Typographic styles should be opt-in instead of being included by default. There is a *wonderful token system*, I would like to have the choice of when I want such header to be of such size.

Explanations on this change or advice on how to proceed would be welcome!

### What type of pull request would this be?

Other

### Any links to similar examples or other references we should review?

https://tailwindcss.com/docs/preflight

**Comment by endigo9740** [comment]
> A few months ago, it was possible to choose which stylesheets to import into the +layout.svelte root.

This is still possible, but no longer documented. You can replicate what `all.css` is doing if you please and replace what you wish as desired. But we felt the process of trying to explain how it works was too difficult for your average user. This lead to many support issues for people thinking they could pull in things willy nilly and order didn't matter.

> Currently migrating a project entirely in tailwind to skeleton, the developer experience is terrible. I have to put unstyled classes everywhere to get what I want.

I'm sorry to hear that, but perhaps you're going about this the wrong way? You shouldn't need this "everywhere". But only specifically for Typography that you wish to change. If you're having to do this over and over, then `unstyled` is the incorrect approach. Instead you should be writing style overrides in your global stylesheet. Then it's one and done.

That said, we have been considering opt-in styles for Typography. But no set ETA for when that might arrive. We're currently regrouping after the v1.0 and a large breaking change is not something we can and will implement without major consideration.

> One of the basic principles of tailwind is that there is no base style, it's up to the developer to choose which classes to put. 

This is actually not quite true. Tailwind, by default, implements a whole slew of resets. You and I can argue semantics here, but those are very much a modification to the base styles. Plus official plugins, such as the Forms plugin very intentionally modifies the base styles for inputs. If you think about what Skeleton is, a major portion of it is our Tailwind plugin. Our plugin isn't really different than an official plugin in that regard. 

Again, we're considering the opt-in change. So I'll have to ask for patience until we do. But until then I'd suggest implementing either global overrides as mentioned above. Handling the style imports yourself is an option, but not one we officially condone or support.

**Comment by oganexon** [comment]
Thanks a lot for providing all those explanations!
I would consider this to answer most of my questions, I will follow your advice.
