### ISSUE TITLE
Allow passing a `input` slot to `InputChip`

### ISSUE THREAD

**Issue by Cucumberrbob** [skeletonlabs/skeleton#1183]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I've made a mockup using my `focus` popup PR, slightly modified since the iframes caused `document.querySelector` to misbehave.
https://stackblitz.com/edit/skeletonlabs-repl-ja71ar?file=src/routes/+page.svelte

By allowing the user to provide their own input element, users can use different types of input (number etc), or listen to events on the input. Skeleton can still provide its existing input element as the fallback slot, so this would be fully backwards compatible.

I thought of this as a way to get a popup Autocomplete working for InputChips.

2 slot variables are needed, since the bindings only go from parent to slot, not the other way around (we can't `bind:value`). One to store the current input. value, and another to listen for the value changing. The `on:submit` handler on the form can be kept as is.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@Cucumberrbob as mentioned on Discord I owe you a proper response to this suggestion. I'll aim to get this asap this week

**Comment by endigo9740** [comment]
@Cucumberrbob I actually updated the Input chips to use an `input` property instead of a slot. This allowed us to handle what I think you were describing above. This is now merged into dev. Please feel free to review and if this meets your requirements then feel free to close this out. Otherwise we'll circle back next release.

**Comment by Cucumberrbob** [comment]
this works almost exactly as well as allowing an input slot. The only thing you lose is the ability to have say a `<input type="numeric">`, but that's not a massive issue
