### ISSUE TITLE
Popup action is not fire the `update()` when the arguments changed

### ISSUE THREAD

**Issue by direnbasol** [skeletonlabs/skeleton#1186]
### Current Behavior

Hello there, I hope you are all great. We already discussed this issue on Discord and decided to raise it here. I'm new to SvelteKit and it may be because of my lack of knowledge or bad implementation. So I'm sorry in advance if the situation is this.

What I am experiencing is that I have a draggable component in my project and a store to populate the component position as x and y values. The popup trigger and popup itself are in that container.

I'm using a combination of if and switch statements to apply the necessary changes to the placement in the popup settings. 

After those steps, the expected result will be the popup change its placement. Except it isn't.

@endigo9740 comes up with an idea that it's because when the `update()` occurred in the popup action the render method is not triggered till the `show()` method is triggered.  And he suggested triggering `render()` when the `update()` is triggered. 

### Steps To Reproduce

Here is the example stackblitz project:
[https://stackblitz.com/edit/draggable-popup-reproduction](url)

**Comment by Cucumberrbob** [comment]
This is because in the `update()` function returned from the `popup` action updates the `args` variable, but this is destructured (once) at the start of the function. I modified the `update()` function to set the variables as follows, and I think this fixes the bug

```ts
update(newArgs: PopupSettings) {
	event = newArgs.event;
	target = newArgs.target;
	placement = newArgs.placement;
	closeQuery = newArgs.closeQuery ?? '';
	middleware = newArgs.middleware;
	state = newArgs.state;
},
```

https://user-images.githubusercontent.com/128094686/226603690-4ebbc3a7-4347-41b7-9281-ef5ca599fdee.mp4

**Comment by direnbasol** [comment]
I can confirm that this is working. Thank you for your efforts @Cucumberrbob 

> This is because in the `update()` function returned from the `popup` action updates the `args` variable, but this is destructured (once) at the start of the function. I modified the `update()` function to set the variables as follows, and I think this fixes the bug
> 
> ```ts
> update(newArgs: PopupSettings) {
> 	event = newArgs.event;
> 	target = newArgs.target;
> 	placement = newArgs.placement;
> 	closeQuery = newArgs.closeQuery ?? '';
> 	middleware = newArgs.middleware;
> 	state = newArgs.state;
> 	isVisible && render()
> },
> ```
> 
> Demo with placement being changed at random
> 
> ```ts
> const placements: Placement[] = ['top', 'bottom', 'left', 'right'];
> setInterval(() => {
> 	exampleTooltip.placement = placements[Math.floor(Math.random() * placements.length)];
> }, 1000);
> ```
