### ISSUE TITLE
Use generics for types where possible

### ISSUE THREAD

**Issue by Cucumberrbob** [skeletonlabs/skeleton#1188]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Initially thought of this for the `Autocomplete` component, but after [discussion on Discord](https://discord.com/channels/1003691521280856084/1003699523522142399/1087811314526720091), it seems this may be a more sweeping change.

[Svelte has support for generic types](https://github.com/sveltejs/rfcs/pull/38). We can constrain them similar to `<T extends S>` in a generic:
```ts
type GenericType = $$Generic<{value: string}>;
export let selected: GenericType | undefined;
```
Now if we had a list of items of type `B = { value: string;  foo: Bar }`, and the user sets `bind:selected` on the parent, the type of `selected` would be `B`, instead of just `{value: string}`

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@ryceg I wanted to bring your attention to this as there may some overlap with what you're working through now.

**Comment by HugeLetters** [comment]
Hi, may I work on this enhancement by any chance? I've stumbled upon this issue for Autocomplete component and I think I got it working with generics in like 2 minutes so I would love to issue a PR - can't say I would be capable of doing the same for other components tho but I may give it a try if you would like to.

**Comment by endigo9740** [comment]
@HugeLetters of course, we always encourage help with outstanding issues like this. The only thing I'd encourage is not the keep the scope limited to only the Autocomplete component. I believe this issue for Modals is very much related:

https://github.com/skeletonlabs/skeleton/issues/1813

Likewise, there may be other portions of Skeleton that could benefit from the user of generics as well.

Unfortunately I haven't had time personally to audit and find all locations where this might be relevant. So perhaps that would be a great place to start?
