### ISSUE TITLE
Embed Font Awesome locally

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1190]
### Describe the Issue

For GDPR compliance we'll need to remove the remote embed of Font Awesome and instead reference this locally. This will also include performance benefits.

### Are you able to create a Pull Request with the fix?

Yes

**Comment by Sarenor** [comment]
Using web fonts apparently needs npm integration via env variable during the build as demonstrated here:
https://fontawesome.com/docs/web/setup/packages

Might be a problem during local development and definitely needs to be set up during build time, which only people with Vercel access can do.
