### ISSUE TITLE
Be more specific in stepTerm overwrite - Stepper component

### ISSUE THREAD

**Issue by SebasF1349** [skeletonlabs/skeleton#1196]
### Link to the Page

https://www.skeleton.dev/components/steppers

### Describe the Issue

At the end of the props tab this message is shown:

`Step can override: gap, stepTerm, justify, buttonBack, buttonBackLabel, buttonNext, buttonNextLabel, buttonComplete, buttonCompleteLabel.`

But in the case of stepTerm is maybe confusing what the override does. Looks like it should change the stepTerm in the Stepper, which is not possible because that's setup in the Stepper component. That prop only overrides the header fallback.

So maybe change it to 

`Step can override: stepTerm (on the header's fallback), gap, justify, buttonBack, buttonBackLabel, buttonNext, buttonNextLabel, buttonComplete, buttonCompleteLabel.`

### Are you able to create a Pull Request with the fix?

Yes

**Comment by endigo9740** [comment]
Adding a doc section that will explain this:

![Screenshot 2023-03-24 at 5 05 13 PM](https://user-images.githubusercontent.com/1509726/227652158-a7fd4947-5afe-4150-8bd6-5165d4c4a240.png)
