### ISSUE TITLE
Dismissed Toasts With Timeouts Close Other Toasts

### ISSUE THREAD

**Issue by ZWubs** [skeletonlabs/skeleton#1197]
### Current Behavior

Currently when opening multiple Toasts that have a timeout, if the first toast that was opened is dismissed, that toast's timeout will close other toasts.

### Steps To Reproduce

1. Trigger a Toast with a timeout (10000ms)
2. Wait a short amount of time (5000ms)
3. Trigger another Toast with the same timeout (10000ms)
4. Dismiss the toast triggered in step 1
5. Watch the toast triggered in step 3 close earlier than is should

This issue can also be easily tested on the [toast utility page](https://www.skeleton.dev/utilities/toasts) by using the "Adjusted Timeout" example.

### Explanation/References
This issue seems related to [this code in the toast store](https://github.com/skeletonlabs/skeleton/blob/d253a34872a2315bfdb7bd74f9121b490e40bee2/src/lib/utilities/Toast/stores.ts#L46-L50). When the index of the toast can't be found we're given back a `-1`. This affects the `splice(index,1)` by removing the most recently created toast.

### Potential Solutions
I'd be more than happy to open a PR for this and get it rolling but would love to first get some feedback on potential solutions from some contributors/community members. This to me seems like a great opportunity to implement a [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) or [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), but I personally haven't done much testing on a Svelte store with a `Set` or `Map`. 

As for a simpler solution a check could just be added to determine if the index wasn't found and execute an early return.

As well another solution could be storing the timeouts and calling `clearTimeout()` on them.

**Comment by Sarenor** [comment]
I think I'd like the ``clearTimeout()`` on dismiss the most :)

**Comment by endigo9740** [comment]
@ZWubs I've been aware of this one for an while and it's been driving me nuts. Sometimes you just need a second set of eyes to resolve stuff though. I'd welcome a PR addressing this.

My only requirement I'd put upfront would be to lean into the simplest and least invasive solution. Aim for something that doesn't change how the feature works for end users. We're now in v1.x.x, which means we have to keep breaking changes to an absolutely minumum.

> This to me seems like a great opportunity to implement a [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) or [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), but I personally haven't done much testing on a Svelte store with a Set or Map.

I don't quite follow how this would help with the timeout issue. Can you expand on this? Sounds like a fairly drastic change perhaps?

> As for a simpler solution a check could just be added to determine if the index wasn't found and execute an early return.

Seems reasonable.

> As well another solution could be storing the timeouts and calling clearTimeout() on them.

Seems like the simplest solution at first glance.

Feel free to submit a draft PR and ping me when you're ready for a review. Here's our contribution guidelines if you need some help getting started:
https://www.skeleton.dev/docs/contributing

**Comment by ZWubs** [comment]
Thanks @endigo9740 and @Sarenor for the feedback! I think I'll look into `clearTimeout`, as I agree it seems to be a simple and direct solution. I'll take some time here soon and get a PR tested and ready for some feedback and a review.
