### ISSUE TITLE
Broken link https://www.skeleton.dev/elements/tokens

### ISSUE THREAD

**Issue by mshirinyan** [skeletonlabs/skeleton#1207]
### Current Behavior

First link on this page: https://www.skeleton.dev/elements/core?ref=skeleton.ghost.io results in 404

### Steps To Reproduce

1. Go to page https://www.skeleton.dev/elements/core?ref=skeleton.ghost.io
2. Click 'design token' class URL or just go to https://www.skeleton.dev/elements/tokens

**Comment by MLNW** [comment]
I fixed a similar broken link yesterday: https://github.com/skeletonlabs/skeleton/pull/1199

Maybe all of them broke when the structure was changed?

**Comment by endigo9740** [comment]
Yeah we had some last minute changes to the docs and seems couple links were missed. I appreciate the reports and PRs!
