### ISSUE TITLE
unordered list text does not wrap

### ISSUE THREAD

**Issue by jeromecc** [skeletonlabs/skeleton#1211]
### Current Behavior

Unordered list text does not wrap on small screens.

```
<ul class="list">
    <li>very very very very very very very very very very long text</li>
    <li>very very very very very very very very very very long text</li>
</ul>
```

where as this wraps normally in the same page:

```
<ul>
    <li>very very very very very very very very very very long text</li>
    <li>very very very very very very very very very very long text</li>
</ul>
```

### Anything else?

a workaround is to remove "list" and add "space-y-4 p-2 m-0" to obtain the same styling with correct wrapping:

```
<ul class="space-y-4 p-2 m-0">
    <li>very very very very very very very very very very long text</li>
    <li>very very very very very very very very very very long text</li>
</ul>
```

In a ideal world, all list items would fit on one line in the smallest screen sizes, but some languages are more verbose and require more characters on average than English... :)

**Comment by jeromecc** [comment]
Hello [endigo9740](https://github.com/endigo9740)!
Thanks for the quick reply.
Could you please suggest a small snippet to make this work?

I tried this, but only the pure html and pure tailwind (first two) versions wrap.

Snippets using skeleton classes don't wrap correctly.

Don't you think skeleton components and styling should wrap correctly by default, just like the default html styling and Tailwind styling?

Thanks.

```
<script lang="ts">
import { CodeBlock } from '@skeletonlabs/skeleton';
</script>

<CodeBlock language="html" code={`<ul>
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ipsum arcu, sollicitudin eu aliquam id, interdum sed est. Curabitur luctus, leo sit amet placerat pharetra, justo justo euismod lectus, ac euismod libero felis id justo.</li>
</ul>`}></CodeBlock>
<ul>
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ipsum arcu, sollicitudin eu aliquam id, interdum sed est. Curabitur luctus, leo sit amet placerat pharetra, justo justo euismod lectus, ac euismod libero felis id justo.</li>
</ul>
<hr />

<CodeBlock language="html" code={`<ul class="list-none">
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ipsum arcu, sollicitudin eu aliquam id, interdum sed est. Curabitur luctus, leo sit amet placerat pharetra, justo justo euismod lectus, ac euismod libero felis id justo.</li>
</ul>`}></CodeBlock>
<ul class="list-none">
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ipsum arcu, sollicitudin eu aliquam id, interdum sed est. Curabitur luctus, leo sit amet placerat pharetra, justo justo euismod lectus, ac euismod libero felis id justo.</li>
</ul>
<hr />

<CodeBlock language="html" code={`<ul class="list">
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ipsum arcu, sollicitudin eu aliquam id, interdum sed est. Curabitur luctus, leo sit amet placerat pharetra, justo justo euismod lectus, ac euismod libero felis id justo.</li>
</ul>`}></CodeBlock>
<ul class="list">
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ipsum arcu, sollicitudin eu aliquam id, interdum sed est. Curabitur luctus, leo sit amet placerat pharetra, justo justo euismod lectus, ac euismod libero felis id justo.</li>
</ul>
<hr/>

<CodeBlock language="html" code={`<ul class="list">
    <li class="whitespace-normal break-normal">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ipsum arcu, sollicitudin eu aliquam id, interdum sed est. Curabitur luctus, leo sit amet placerat pharetra, justo justo euismod lectus, ac euismod libero felis id justo.</li>
</ul>`}></CodeBlock>
<ul class="list">
    <li class="whitespace-normal break-normal">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ipsum arcu, sollicitudin eu aliquam id, interdum sed est. Curabitur luctus, leo sit amet placerat pharetra, justo justo euismod lectus, ac euismod libero felis id justo.</li>
</ul>
<hr/>
```

**Comment by Sarenor** [comment]
As an interim Fix you can do ``<li class="!whitespace-normal !break-normal">`` @jeromecc .
The classes set in ``list > li`` have more specificity than just the classes you applied to the ``<li>`` element.

Definitely something we should take a look at though. @endigo9740 Just remove ``white-space: nowrap`` from ``list > li`` or did you have something else in mind?

**Comment by endigo9740** [comment]
Not sure, I'll need to take a look. But I reopened this ticket so that will happen soon.

**Comment by endigo9740** [comment]
@jeromecc @Sarenor I've implemented a change that should allow wrapping to occur by default for `<li>` elements. But please note that there are multiple uses cases for lists, which is why we have to be careful with these kinds of changes.

For example, you might be using:

```html
<li>(content)<li>
```

But we also support columns within LI tags, like so:

```html
<li>
    <span>(avatar)</span>
    <span>(content)</span>
    <span>(icon)</span>
<li>
```

When using columns we don't know WHICH span is going to contain content that needs to wrap, so that'll be up to user to handle. They could have 2, 3, 4, or potentially more columns here within each span.

But for now I've made it so the standard `.list ul` uses wrapping by default. Hopefully that provides the desired results. Here's a screenshot:

![Screenshot 2023-03-30 at 12 02 03 PM](https://user-images.githubusercontent.com/1509726/228912400-b89d925c-74d3-4b78-97d9-eed1dc49f218.png)
