### ISSUE TITLE
Minor Bug on table cells layout

### ISSUE THREAD

**Issue by delight** [skeletonlabs/skeleton#1212]
### Current Behavior

`<td>`'s in `<thead>` and `<tfoot>` are p-4 (1rem) while in a  <tbody> they are px-3 (0,75rem) / py-4 (1rem)

This is a very subtil difference and you have to look at it with a sharp eye but it is still there. Don't know if this is intended, but to me it felt a little wrong as you can achieve the subtile differenciation with the use of `<th />` font-bold - while keeping everything nicely aligned.

### Steps To Reproduce

using a table with thead, tbody and tfoot ... cells in tbody have a different horitzontal padding

### Anything else?

I'll submit a little patch - if you like it merge it - if not 🗑️

**Comment by delight** [comment]
before:

![image](https://user-images.githubusercontent.com/117198/227773567-b1e2bb14-551e-4efe-b4a7-b076f327c74a.png)

after:

![image](https://user-images.githubusercontent.com/117198/227773591-65072de3-85e7-4fe8-9d5d-18d79ffd9051.png)

**Comment by endigo9740** [comment]
@delight that's an intention design decision. I like the header row to stand out a bit. Thanks for the PR, but I will go ahead and close it out.

**Comment by delight** [comment]
I understand. Well I guess that's a matter of taste. To me it doesn't make it stand out, just looks a little crooked. 

Luckily I can easily fix everything to my liking in the app.postcss 😊

I love the flexibility of the skeleton and in general the current state of the framework. It's simply awesome 👍🏽
