### ISSUE TITLE
Chat bubbles!!!

### ISSUE THREAD

**Issue by FrodoTrash** [skeletonlabs/skeleton#1214]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It'd be really cool seeing chat bubbles like daisyUI

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

https://daisyui.com/components/chat/

**Comment by endigo9740** [comment]
@FrodoTrash Ha, I appreciate the excitement in your title.

I think this may overlap with an existing request here, so I'm going to go ahead and close this out. Please feel free to echo this within that ticket:
https://github.com/skeletonlabs/skeleton/issues/469

Even if these are 1:1, I would expect the work for both would occur at the same time given there's a lot of overlap. Hope that makes sense!
