### ISSUE TITLE
More control over animations

### ISSUE THREAD

**Issue by saturnonearth** [skeletonlabs/skeleton#1219]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Something I'd really like to see and is more control over the animations of components. I know some components have access to animation speed or direction, but actually changing the animation type would be great as well. I wonder if it's better to switch to some sort of CSS animation, as opposed to using Svelte transitions. This would make it easier to edit.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
This something I'd love to see as well, but unfortunately there's trade offs between Svelte Transitions and pure CSS animations.

### Svelte Transitions

These are fairly rigid. Each one has to be imported and scaffolded into the component. There's not really a great mechanism in place to just "swap them out". And the number of settings are fairly minimal between each - typically just direction and duration in most cases. However, they are the most dynamic, fully reacting to interruption in the state part way through the animation. This is great for animations that toggle, where you may not need the animation to complete in full before the next is applied.

### CSS Animations

Fairly open ended with lots of options. Can be passed straight in like any other utility class, fitting our prop paradigm. Unfortunately they can be a lot more difficult for your average user to setup. Plus their not "smart" like Svelte Transitions, meaning interruptions mid-animation are not always handled in a clean fashion.

That said, this is definitely something that's been on my mind for a while. If we can find a good way to handle it we will. But with Svelte 4 around the corner, it might be worth seeing what updates come in from upstream before we devote too much effort here.

**Comment by endigo9740** [comment]
Even though this issue came first, I'm going to mark this as a duplicate so we can funnel all discussion on this topic here:
- https://github.com/skeletonlabs/skeleton/issues/1322

We've established a more flushed out plan for how we want to approach this globally for all components. @JustBarnt will be assisting in implementing this.
