### ISSUE TITLE
AppRailTile detail more about the click handler firing

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#1230]
### Link to the Page

https://www.skeleton.dev/components/app-rail

### Describe the Issue

Just had a support issue and the follow on imho is that there needs to be more detail about the condition for firing the click event based on the AppRail having the selected store and the AppRailTile's having the value liked to it - it is clear form the code, but not clear to someone reading it who doesn't click on the show code slide toggle

### Are you able to create a Pull Request with the fix?

None

**Comment by endigo9740** [comment]
I think there's a few updates we need to this component:

1. We should consider making the anchor-tag option the default, as I think it's more widely used
2. We should update this to use the same input/binding method that features like Tabs and Radio Groups now use
3. By doing number 2 we can make the use of a store optional and opt-in

Once those changes are made then the documentation should be updated accordingly.

**Comment by endigo9740** [comment]
Note this may be sorted as part of the recent update to this component, but worth double checking

**Comment by Mahmoud-zino** [comment]
I just checked and I think everything is clear after the update.
