### ISSUE TITLE
Improve types for modal metadata

### ISSUE THREAD

**Issue by Cucumberrbob** [skeletonlabs/skeleton#1231]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I've had an interesting idea (may well just be an idea) around the typing of modalStore[number]['meta']. Similar to what Sveltekit does with the App namespace, Skeleton could declare a namespace, and reference types from that namespace. This lets the user override types where applicable. This seems useful as you would now get type errors like with props for passing data to your modal components.

If the user creates a discriminated union type with some key like _type to distinguish between types, then TS can ensure not just that it fits the general type of metadata, but the specific type said component needs:

```ts
// file: skeleton.d.ts in user's repo
type ChangeUsernameModalMeta = {
    currentUsername: string;
    _type: 'change-username';
};
type VerifyEmailModalMeta = {
    email: string;
    _type: 'verify-email';
};
declare namespace Skeleton {
    type ModalMeta = ChangeUsernameModalMeta | VerifyEmailModalMeta;
}
```
and in utilities/Modal/types.ts:
```ts
export interface ModalSettings {
  ...
    meta?: Skeleton.ModalMeta;
}
```

to clarify, this is fully backward compatible since `Skeleton.ModalMeta` will resolve to `any` when not overridden

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
I just noted the paired PR didn't properly link back to this issue, so I'm closing this. See my comments in the PR related to why this was closed.
