### ISSUE TITLE
Documentation links to Design Token

### ISSUE THREAD

**Issue by ucffool** [skeletonlabs/skeleton#1247]
> I looked for a repo but couldn't find one to just do this as a PR, so submitting here

##  Documentation Page
https://www.skeleton.dev/docs/themes#preset-extras (Backgrounds section)
- Design Token link points to:
  - https://www.skeleton.dev/elements/tokens but should be...
  - https://www.skeleton.dev/docs/tokens

There may be more but ran into this one first.

**Comment by endigo9740** [comment]
@ucffool just realized you filed this originally under the CLI project repo. Just FYI the main Skeleton project is built with SvelteKit. SvelteKit allows your library and docs to live within a single project. I've transferred the issue for you.

**Comment by endigo9740** [comment]
This didn't link properly so I'm closing this out manually.
