### ISSUE TITLE
Add props to Table component to control table head and table foot cell styling

### ISSUE THREAD

**Issue by Zantonius** [skeletonlabs/skeleton#1255]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Currently there is a way to style the text in a table cell in the body of the table with `regionCell`.

E.g.
`<Table ... regionCell="text-right" />` makes the text right-justified in a table cell (`td`) in the body.

The same is not currently possible for the `th` in the table head or `td` in the table footer and it would be great if it was possible.

Could be implemented as `<Table ... regionHeadCell="text-right" />` and `<Table ... regionFootCell="text-right" />`.

Could potentially change the name of the prop to `regionCell` to `regionBodyCell` to align all prop names for styling table cells. But that would be a (minor) breaking change and I leave that decision to someone more involved :) 

### What type of pull request would this be?

Enhancement/Feature

**Comment by endigo9740** [comment]
The PR with this change was accepted and merged, not sure why it didn't auto-close this. But handling this now!
