### ISSUE TITLE
closeQuery on popups does not work as documented

### ISSUE THREAD

**Issue by jjgmckenzie** [skeletonlabs/skeleton#1258]
### Current Behavior

On https://www.skeleton.dev/utilities/popups , the code and documentation:
```ts
let popupCombobox: PopupSettings = {
	event: 'focus-click',
	target: 'combobox',
	placement: 'bottom',
	// Close the popup when the item is clicked
	closeQuery: '.listbox-item'
};
```
Makes numerous reference to the intended behaviour of the popup being closed when a listbox item is selected.
This does not work. Tested on Chrome / Firefox 

### Steps To Reproduce

1. On https://www.skeleton.dev/utilities/popups
2. Click one of the listbox items in the combobox section
3. It does not close on firefox or chrome.

**Comment by endigo9740** [comment]
@jjgmckenzie it appears to be a bug with the new focus events added last patch. The other methods will work as expected. Either way we have a fix in place that will drop in the next release. Thanks for reporting though!
