### ISSUE TITLE
RangeSlider: ticks absent for negative values

### ISSUE THREAD

**Issue by ehahn9** [skeletonlabs/skeleton#1260]
Ticks are missing from negative values in the range:

` <RangeSlider name="size" ticked min={-4} max={4}>Size</RangeSlider>`

Renders as:

<img width="151" alt="Screenshot 2023-04-02 at 7 34 05 AM" src="https://user-images.githubusercontent.com/299134/229359626-1cd74d4c-5581-4b0d-9c2a-466f6f472564.png">

**Comment by salisshuaibu11** [comment]
@endigo9740 i would like to take this

**Comment by endigo9740** [comment]
Thanks @salisshuaibu11, first thing to test is if the native range type input with datasets support negative numbers:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#adding_tick_marks

If the browser doesn't support it, then we can't accept it. Also note not all browsers support ticks either - such as Safari. But Chrome should be fine.

**Comment by salisshuaibu11** [comment]
Alright, let me check
