### ISSUE TITLE
Manual installation error<title>

### ISSUE THREAD

**Issue by anpace** [skeletonlabs/skeleton#1261]
### Current Behavior

I get some errors after manual installation as you can see in the screenshot

<img width="1440" alt="tJLD6" src="https://user-images.githubusercontent.com/31728411/229380539-0dfd46f7-f226-4ab2-8b5c-2ad9d8cd9be9.png">

### Steps To Reproduce

npm create svelte@latest diceGame

cd diceGame

npm install

npm i @skeletonlabs/skeleton --save-dev

npx svelte-add@latest tailwindcss

npm install

**Comment by endigo9740** [comment]
As discussed on Discord, this is due to peer dependencies not matching what was expected. The Skeleton CLI will handle all this for you. Generally speaking, most frameworks have a max version of, say, Typescript they support. So installing the absolutely latest is not always advised.

**Comment by anpace** [comment]
I'm sorry for the post, I thought it would be good to report this kind of errors.
It was just to report about it.
I apologize and I thank you very much for the explanations and the answers.

**Comment by dlamon1** [comment]
Installing with the CLI is not possible when using something like Electron or Tauri. Please advise

**Comment by endigo9740** [comment]
@dlamon1 this is a closed issue which likely won't get very much visibility. Likewise this is the Skeleton project. The CLI repo is here:

https://github.com/skeletonlabs/create-skeleton-app

I'd suggest creating an issue there. Though currently official support for Electron and Tauri are not on our roadmap. I know folks are using it for this purpose though. I might suggest looking at how to integrate a Svelte/SvelteKit application first, then follow our manual instructions on our website to get you the rest of the way. But the client side requirements are:

1. Svelte (preferably SvelteKit)
2. Tailwind
3. Skeleton's NPM package
