### ISSUE TITLE
Recieve error when using form action to redirect page

### ISSUE THREAD

**Issue by saturnonearth** [skeletonlabs/skeleton#1264]
### Current Behavior

I am currently using a form hidden within a popup to allow the user to logout. This submits a form action which triggers a redirect. After the user is redirect, the popup no longer exists since you are now on a page without the popup element existing.

### Steps To Reproduce

1. Clone example repo [here](https://github.com/saturnonearth/my-skeleton-demo) (can't be done in Stackblitz as they don't allow form submissions)
2. Open console
3. Click _Dashboard_ in upper right
4. Click, _Click Me!_ button, then click Sign Out
5. See console for error

### Anything else?

Error as shown: 

`DOMException: Failed to execute 'querySelectorAll'(popup.js:105 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': The provided selector is empty.)`

**Comment by Sarenor** [comment]
Thanks for the excellent reproduction!
Seems to be a general issue with popups and this line in ``popup.ts``:
```ts
  const interactiveMenuElems = elemPopup?.querySelectorAll(args.closeQuery || '');
```
When no closeQuery is provided it will default to empty string and that leads to a syntax error:
> A string containing one or more selectors to match against. This string must be a valid [CSS selector](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) string; if it's not, a SyntaxError exception is thrown. See [Locating DOM elements using selectors](https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/Locating_DOM_elements_using_selectors) for more information about using selectors to identify elements. Multiple selectors may be specified by separating them using commas.
(Source: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll?retiredLocale=de)

Should be an easy fix, I'll throw together a PR.

Thanks for reporting!
