### ISSUE TITLE
Shouldn't the stepTerm be on a <Stepper> instead of the <Step> (which is the one that is currently in the docs.)? Images provided.

### ISSUE THREAD

**Issue by AdrianFerrer1** [skeletonlabs/skeleton#1272]
### Link to the Page

www.skeleton.dev/components/steppers

### Describe the Issue

![step](https://user-images.githubusercontent.com/112191768/229763840-da882aab-0795-4ff4-a89d-327e1fc45724.png)
This is what it currently looks like

![stepp](https://user-images.githubusercontent.com/112191768/229764013-e2113739-7d28-424f-9f01-74bbb7b15624.png)
Shouldn't it look like this? (it's the thing that works for me at least, it didn't do anything for me the way it is on the docs)

### Are you able to create a Pull Request with the fix?

None

**Comment by Sarenor** [comment]
You can do both:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/31982384/229770306-fb75c18f-4c0a-48d0-9389-7ffc8ee6a015.png">
Which is the important part to communicate

**Comment by endigo9740** [comment]
Sarenor is correct here, either is acceptable.
