### ISSUE TITLE
Non-inclusive terms in the docs

### ISSUE THREAD

**Issue by GreenHapi** [skeletonlabs/skeleton#1276]
### Link to the Page

https://www.skeleton.dev/components/autocomplete

### Describe the Issue

`blacklist` and `whitelist` words are outdated terms.
They can be replaced with `denylist` or `blocklist` and `allowlist`.

For reference:
https://developers.google.com/style/word-list#blacklist
https://developers.google.com/style/inclusive-documentation

### Are you able to create a Pull Request with the fix?

None

**Comment by endigo9740** [comment]
We'll have to implement in a backwards compatible way, but other than that I'm fine with this change. Thanks for the suggestion.

**Comment by endigo9740** [comment]
@GreenHapi I've updated this to use `allowlist` and `denylist`, while still being backwards compatible with white/blacklist to to prevent a breaking change. The old props are now marked as deprecated and we'll aim to remove this in an upcoming release. This should give folks a buffer to migrate to the replacements.
