### ISSUE TITLE
Popup only working (slightly) on AppBar during initial load.

### ISSUE THREAD

**Issue by saturnonearth** [skeletonlabs/skeleton#1281]
### Current Behavior

Popup behavior is odd when placed onto AppShell/AppBar.
Upon first load, clicking on it either works, or works and then quickly disappears.

You can see the button on each page that is outside the AppBar always works.

![chrome_0KApddxzNc](https://user-images.githubusercontent.com/12503538/230137631-a22a1843-748f-4d96-9bb3-9453970ab312.gif)

### Steps To Reproduce

1. Load Stackblitz link
2. Click Button in top-right on AppBar, the popup should open and then close, and cannot be opened again.
3. If you refresh, it will work again.

### Anything else?

Note that each page has its own layout with its own AppShell.

Stack blitz link here: 
https://stackblitz.com/edit/skeletonlabs-repl-pjj3ug?file=README.md[https://stackblitz.com/edit/skeletonlabs-repl-pjj3ug?file=README.md

**Comment by endigo9740** [comment]
Merged into: https://github.com/skeletonlabs/skeleton/issues/1282
