### ISSUE TITLE
Popup does not work after page change when on AppBar

### ISSUE THREAD

**Issue by saturnonearth** [skeletonlabs/skeleton#1282]
### Current Behavior

Popup behavior is odd when placed onto AppShell/AppBar. It stops working when either there is a hot-reload on dev mode, or when you change the page.

You can see the button on each page that is outside the AppBar always works.

![chrome_wbHapXbohs](https://user-images.githubusercontent.com/12503538/230138302-b350a805-c613-413b-a30d-5fcb4b393bb3.gif)

### Steps To Reproduce

1. Load Stackblitz link
2. Click "Authenticated" in top nav bar
5. Click button on top right of AppBar - it should "flash".

### Anything else?

Note that each page has its own layout with its own AppShell. This issue may be related to #1281

StackBlitz link: https://stackblitz.com/edit/skeletonlabs-repl-8scgxj?file=src/routes/(public)/+layout.svelte

**Comment by endigo9740** [comment]
@saturnonearth, going forward feel free to merge similar issues in one ticket. We can divide after the fact if we determine that's a good reason to. It just helps keep things organized. It also makes it easier to keep the discussion localized in one place.

For now I'll opt to discuss both issues in this ticket.

So the weird per here is your repro obvious replicates the issues described, but we have a prime example of this functionally working - which is the Explore and Theme popups used in the Skeleton docs site at the top of each page:
https://www.skeleton.dev/

These have been working for a long while without issue. Even in our local dev branch currently running the latest SvelteKit/Tailwind dependencies. The best way to diagnose the issues is to figure out what's different between your replications and our site.

I'll try to circle back on this soon, but off hand I'm not sure what's up here.

**Comment by endigo9740** [comment]
On second thought, I'm going to go ahead and link the other issue. Both these tasks can be handled together. We'll use this ticket as the centralize location for these tasks:
https://github.com/skeletonlabs/skeleton/issues/1281

**Comment by sumitshinde-84** [comment]
I would like to work on this issue can you please assign it to me?

**Comment by endigo9740** [comment]
Thanks @sumitshinde-84, done. Please make sure you you review #1281 as well, which may be related. If the issue resides on Floating UI's end, let's try to report the issue over to them here:
https://github.com/floating-ui/floating-ui

**Comment by endigo9740** [comment]
@sumitshinde-84 checking on the progress for this. I haven't seen a draft PR come through, which is typically our recommendation for contribution:
https://www.skeleton.dev/docs/contributing/requirements

If something has come up and you won't be able to address this just let me know. No harm done. I just don't want this to sit idle too long.

**Comment by Mahmoud-zino** [comment]
I fixed the issue by changing one of both popup settings **target**.
The target is used to query the element and when duplicated will always return the first one.

This is a working [Stackblitz link](https://stackblitz.com/edit/skeletonlabs-repl-xxnscb?file=src/routes/(public)/+page.svelte).

Maybe this should be mentioned in the documentation to avoid confusion.

**Comment by saturnonearth** [comment]
> I fixed the issue by changing one of both popup settings **target**. The target is used to query the element and when duplicated will always return the first one.

Good find!!

This makes sense now. It was a similar issue I was having when having the same targets from `#each`. I think in my mind, since they were different components or pages, and in Svelte, components are usually "self-contained", it would not matter - like other things such as CSS are abstracted without "global" tags, or even just normal vars.

But since it's just a normal HTML data attribute as a target, that makes sense!

I believe the PR for https://github.com/skeletonlabs/skeleton/issues/1336 would actually fix this issue in a way, as it would not rely on static data attribute values, but instead, actual references to the node.

But yea a note in the docs is a good idea as well.
