### ISSUE TITLE
`RangeSlider` tickmark test fails

### ISSUE THREAD

**Issue by Cucumberrbob** [skeletonlabs/skeleton#1284]
### Current Behavior

The [test](https://github.com/skeletonlabs/skeleton/blob/84714dc549763f52a4149d46b4ba59457d77d026/src/lib/components/RangeSlider/RangeSlider.test.ts#L30) to ensure that ticks are rendered via a `<datalist>` when `ticks={true}` doesn't work.

This is because of an issue with how the `component.$$.after_update` array is populated. It should (and does, in the browser) contain all the functions passed to it via `afterUpdate(fn)`. But in  the testing environment, this doesn't happen for some reason.

This is likely not an issue with `@testing-library/svelte`, as it is  [instantiating](https://github.com/testing-library/svelte-testing-library/blob/373a666b9a7b9f000ae1a6236b5edb8af9722ce7/src/pure.js#L57) the component in a standard way.

There is a closed (by author) [issue](https://github.com/sveltejs/svelte/issues/7267) on the `svelte` repo which addresses this. The author shows a workaround by exporting the handler (in this case, exporting `showTicks`), and calling it in the test.

### Steps To Reproduce

`pnpm test`

### Anything else?

the test also fails using `happy-dom`.
I made a minimal reproduction [here](https://github.com/Cucumberrbob/vitest-lifecycle-repro/tree/main/src/lib/components) ([stackblitz](https://stackblitz.com/fork/github/cucumberrbob/vitest-lifecycle-repro))

**Comment by Cucumberrbob** [comment]
I think this may be larger than just an issue with the test. I'm not sure what the intended behaviour is for redrawing the tickmarks, but it seems to break chrome and safari. Wrapping in a `{#key max}` makes safari work, but not chrome.

chrome

https://user-images.githubusercontent.com/128094686/230441765-a8443c53-a305-4fb9-94f2-c836fd0270b7.mp4

firefox

https://user-images.githubusercontent.com/128094686/230441769-24601de3-7232-41fe-953a-ec8a6e1d7144.mp4

safari

https://user-images.githubusercontent.com/128094686/230441772-2b438ace-e833-46aa-a4c3-6168a87e51de.mp4

**Comment by endigo9740** [comment]
The component is mostly just a wrapper around native range input functionality @Cucumberrbob. Can you test this using native elements outside of our component and verify the results.

I'm actually surprised to see this rendering ticks in Safari. Even per the docs we indicate that Safari support was minimal last I checked a couple weeks ago. Strangely enough the ticks also render differently for me (above rather than below the slider bar)

![Screenshot 2023-04-06 at 12 55 59 PM](https://user-images.githubusercontent.com/1509726/230458141-5587e03c-3e28-474f-8b5b-e1b510c65638.png)

I'm on macOS Ventura v13.2, which is running Safari v16.3.

**Comment by endigo9740** [comment]
Note @Cucumberrbob the original reported issue was in relation to failing tests. I've adjusted the range slider slightly to trigger the ticks on load, then kept the `afterUpdate` in the case that ticked/min/max change, it will recalculate the ticks. This also fixes a newly introduced issues with ListBoxItem's test, and silences a number of warnings about missing required props.

![Screenshot 2023-04-06 at 1 19 17 PM](https://user-images.githubusercontent.com/1509726/230463040-1dac9371-c5a8-4c33-b50d-6307a9306e53.png)

If you think the responsive ticks are a critical feature, then I suggest opening up a new ticket under the label of a feature request. This is out of scope of this (now closed) issue.
