### ISSUE TITLE
Investigate if moving CSS-Imports has any detrimental side effects

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#1286]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

We've found that Tailwind behaves differently when ``skeleton.css`` etc. are imported in ``app.postcss`` instead of the root ``+layout.svelte``.
So far, we don't officially recommend moving the imports there since we fear unknown side effects and things not working as expected with the way Tailwind behaves.

On the other hand, potentially having layer-directives & @apply available for Skeleton & End user classes could be a very valuable enhancement so we should devote some time to investigation. 

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

https://discord.com/channels/1003691521280856084/1093117288875569192

**Comment by MLNW** [comment]
Relates to https://github.com/skeletonlabs/skeleton/issues/1152

**Comment by endigo9740** [comment]
@MLNW just to make sure we're on the same page - the relation is that by moving the CSS imports into the stylesheet, that folks are free to use the automatic import reordering feature of VS code without issue. Is that correct?

If so I agree with that take. And we should weight that with considering this change.

**Comment by MLNW** [comment]
Yes, that's correct
