### ISSUE TITLE
Table sort classes are reversed

### ISSUE THREAD

**Issue by richarddavenport** [skeletonlabs/skeleton#1287]
According to the docs:

.table-sort-asc | - | Apply to a table heading cell to add a down arrow indicating ascending sort.
-- | -- | --
.table-sort-dsc | - | Apply to a table heading cell to add an up arrow indicating desending sort.

https://github.com/skeletonlabs/skeleton/blob/4f5212818d7989a7ffe0518d8a9c9e9799cf044c/src/lib/styles/elements/tables.css#L34-L40

My question is, isn't this counterintuitive? My interpretation of ascending means going up and descending is going down. Am I just confused here?

https://ux.stackexchange.com/questions/37564/use-up-or-down-arrow-to-represent-sort-ascending-at-table-header
This question has some good examples for both sides and different options. However, when I look around at other UI's (desktop, applications) most of the arrows point up for asc. and down for desc.

One example from MacOS Finder app:  
<img width="499" alt="Screenshot 2023-04-05 at 3 45 59 PM" src="https://user-images.githubusercontent.com/3596012/230207544-9c457313-2131-4fc6-8af8-ce01284ed868.png">

**Comment by endigo9740** [comment]
The sort features were includes as part of some initial prototyping for an in-house data table solution. That hasn't panned out, but we kept the styles just in case they proved useful to others. That said, I think you may be right about these being swapped. Seems like a simple fix, so we'll look to get this sorted soon. Thanks!
