### ISSUE TITLE
Input Chip/Autocomplete not behaving as expected

### ISSUE THREAD

**Issue by KristjanSever** [skeletonlabs/skeleton#1288]
### Current Behavior

https://dev.skeleton.dev/components/autocomplete#input-chip 
Under Input Chip example, you can test for yourself. When you select one option, a new chip appears, but if you remove it, it isnt added back to the Autocomplete component. It simply dissappears. This also happens when selecting multiple options => multiple chips appear, removing them 1 by one is alright right until you get to the last one, which will again, dissappear.

edit: if you repeat this, the old chip shows up again in the Autocomplete component, but the newer one is gone again..

### Steps To Reproduce

Input Chip with Autocomplete component, accessible on the [website even](https://dev.skeleton.dev/components/autocomplete#input-chip)
1) click on any option => chip appears, option is removed from the Autocomplete component
2) remove chip => chip is removed, option is NOT added back to the Autocomplete component

or 

1) select multiple options => multiple chips will appear
2) start removing chips => they will reappear in Autocomplete
3) when you get to the last chip, remove it => last chip is removed, but not added to the Autocomplete

### Anything else?

I would be happy to fix it myself, if you give me maybe some guidence. :)

**Comment by endigo9740** [comment]
I'm currently unable to replicate the described behavior. Can you check your console log and ensure there other errors or issues at place? Can you post your specific OS/Browser so we can try and replicate.

https://user-images.githubusercontent.com/1509726/230457064-586eb288-aa35-4940-b863-3c3fc3015d49.mp4

**Comment by KristjanSever** [comment]
As you can see, the last chip (Vanilla) was NOT added back to autocomplete even in your video.
Try to just click on (for example) Chocolate, and then remove the Chocolate chip, and the Chocolate element will not reappear in the Autocomplete. Hope you understand what i mean

Im using M1 MacOs with Brave browser. I can provide additional data but i think its not browser-specific.
I also checked with Safari and it behaves the same.

**Comment by KristjanSever** [comment]
https://user-images.githubusercontent.com/56491774/230458929-798a118d-fdf5-452e-a474-f6995e4167c4.mov

Maybe its more clear what i mean in this video

**Comment by endigo9740** [comment]
Yep I overlooked that it was only the last option. I'll need to investigate so I'll post back when I've had a chance to review.

**Comment by KristjanSever** [comment]
No need to rush, its not a deal breaker. Im also free to assist in any way i can

**Comment by endigo9740** [comment]
Feel free to pull down the code and take a look. If you find a cause then a PR is welcome as long as it's something trivial. If the issue is something substantial then I'd welcome some prior discussion either here or on Discord in the `#contributors` channel.

If you need help creating a PR, we provide resources here:
https://www.skeleton.dev/docs/contributing
