### ISSUE TITLE
applying skeleton-custom-classes leads to error at build time

### ISSUE THREAD

**Issue by delight** [skeletonlabs/skeleton#1302]
### Current Behavior

When I @apply a skeleton-custom-class like 
`@apply variant-ringed-primary`
it works as expected in dev mode `pnpm dev` but breaks the build with the following error message:

```
$ pnpm build

> csslayer@0.0.1 build /home/koko/devel/github/csslayer
> vite build


vite v4.2.1 building SSR bundle for production...
✓ 51 modules transformed.
transforming (52) node_modules/.pnpm/set-cookie-parser@2.6.0/node_modules/set-cookie-parser/lib/set-cookie.js13:04:39 [vite-plugin-svelte] ssr compile done.
package         files     time     avg
csslayer            2   44.7ms  22.3ms
@sveltejs/kit       1   41.8ms  41.8ms
✓ built in 1.38s
[vite-plugin-svelte] Error while preprocessing /home/koko/devel/github/csslayer/src/routes/+page.svelte - [postcss] /home/koko/devel/github/csslayer/src/routes/+page.svelte.postcss:3:3: The `variant-ringed-primary` class does not exist. If `variant-ringed-primary` is a custom class, make sure it is defined within a `@layer` directive.
file: /home/koko/devel/github/csslayer/src/routes/+page.svelte
error during build:
CssSyntaxError: Error while preprocessing /home/koko/devel/github/csslayer/src/routes/+page.svelte - [postcss] /home/koko/devel/github/csslayer/src/routes/+page.svelte.postcss:3:3: The `variant-ringed-primary` class does not exist. If `variant-ringed-primary` is a custom class, make sure it is defined within a `@layer` directive.
    at Input.error (/home/koko/devel/github/csslayer/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/input.js:148:16)
    at AtRule.error (/home/koko/devel/github/csslayer/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/node.js:60:32)
    at processApply (/home/koko/devel/github/csslayer/node_modules/.pnpm/tailwindcss@3.3.1_postcss@8.4.21/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:378:29)
    at /home/koko/devel/github/csslayer/node_modules/.pnpm/tailwindcss@3.3.1_postcss@8.4.21/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:535:9
    at /home/koko/devel/github/csslayer/node_modules/.pnpm/tailwindcss@3.3.1_postcss@8.4.21/node_modules/tailwindcss/lib/processTailwindFeatures.js:55:50
    at plugins (/home/koko/devel/github/csslayer/node_modules/.pnpm/tailwindcss@3.3.1_postcss@8.4.21/node_modules/tailwindcss/lib/plugin.js:38:63)
    at LazyResult.runOnRoot (/home/koko/devel/github/csslayer/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/koko/devel/github/csslayer/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/koko/devel/github/csslayer/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/home/koko/devel/github/csslayer/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:206:17)
 ELIFECYCLE  Command failed with exit code 1.
```

Boiling down to:

 The `variant-ringed-primary` class does not exist. If `variant-ringed-primary` is a custom class, make sure it is defined within a `@layer` directive.

I've found this on the tailwind docs:

https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css

Question is is there something we can do or should we at least document that @apply won't work with custom-classes at build time?

### Steps To Reproduce

I created a minimal demo to easily reproduce the problem

https://github.com/delight/csslayer

works fine at `pnpm dev` fails at `pnpm build`

### Anything else?

https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css

**Comment by delight** [comment]
Just found #992 ... similar problem I guess

**Comment by endigo9740** [comment]
@delight this is a known issue with how Tailwind works and scoping. It's not a bug on Skeleton's end.

We recommend folks do not try to use `@apply` with out classes because that's an abstraction of an abstraction and goes against Tailwind's utility-first design fundamentals:
https://tailwindcss.com/docs/utility-first

Utility classes are meant to be used inline in your template. Using `@apply` is an abuse. Plain and simple.

That said, if you feel this is the only way to accomplish what you're after, then moving the CSS imports from the root layout to the top of your `app.postcss` is a known work around. I'll mention once again, we do not recommend it. But it's a way to do what you seek.

**Comment by delight** [comment]
Thank you for your response!

It works fine if I apply the utility-classes to the markup - can't think of a case that would not be solved by it.

What bug-ed me though is the different behaviour between build and dev time - which gives the impression that everything is working fine until build time - where it ultimately fails.

I understand that there is nothing we can do on the end of skeleton - other then maybe documenting it.

**Comment by endigo9740** [comment]
Unfortunately if we documented every issue for Svelte/Kit and Tailwind, that's all our documentation would be. Tailwind covers the utility-first approach, which we lean into. So I'd say that will suffice for now.
