### ISSUE TITLE
Using multiple popup setting objects with Autocomplete

### ISSUE THREAD

**Issue by JustBarnt** [skeletonlabs/skeleton#1305]
### Current Behavior

Using multiple popup setting objects with Autocomplete creates odd behaviors where hitting tab causes input to focus on the div containing autocomplete list, followed by all the items in the list. 

Whereas when multiple autocompletes share the same setting object, and therefor the same name, hitting tab moves to the next input as I would expect it to. 

### Steps To Reproduce

Reproduced using this stackblitz link.

StackBlitz: https://stackblitz.com/edit/skeletonlabs-repl-22yqvw?file=src/routes/+page.svelte

**Comment by JustBarnt** [comment]
Additional issue related to this, Stackblitz should be updated to show a third input field in the first input group, when focused onto the first input and tab is pressed, it skips focusing the second input and moves straight to third.

**Comment by JustBarnt** [comment]
@endigo9740 I also have a solution for this in mind as well- it involves making `target` more of a string a selectors instead of a single selector. 

So that an array of selector(s) is retrieved and then only one settings object would be needed. Though this is quite a change I'm not entirely sure it would be "breaking" for users, as target technically doesn't change for them- but I have had to do quite a bit of re-working for the popup modification I am using for my application at work.

I can create a private gist and share with you if you want? Or if you have a better solution I am all for it!

**Comment by marke-dev** [comment]
Uncaught (in promise) TypeError: Cannot destructure property 'computePosition' of 'get_store_value(...)' as it is undefined.
```
"@floating-ui/dom": "^1.4.5",
"@skeletonlabs/skeleton": "^2.4.0",
"@skeletonlabs/tw-plugin": "^0.2.3",
```
popup.js file
```
export const storePopup = writable(undefined);
export function popup(triggerNode, args) {
const { computePosition, autoUpdate, offset, shift, flip, arrow, size, autoPlacement, hide, inline } = get(storePopup);
....
```
