### ISSUE TITLE
Stepper: Make header badges clickable, allow to hide/move prev & next buttons

### ISSUE THREAD

**Issue by Shackless** [skeletonlabs/skeleton#1308]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It would be great if we could click the badges on top of the stepper to move to this step.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/306996/231146914-b415608e-435f-4a7a-88a4-ca252c32c3e4.png">

In my case, I don't want the previous/next buttons to be visible at all (which I know I can do with classes). 
It would also be neat if I could display them on top of the content, so just below the badge area.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

somewhat related to https://github.com/skeletonlabs/skeleton/issues/1265

**Comment by endigo9740** [comment]
This comes up from time to time - the Stepper is meant to be traversed in a linear fashion. As in, you must go through the steps in order, for onboarding, etc. If you need to jump to various steps then a Stepper isn't the appropriate UI to use, you're looking for an accordion, list, or something more custom.

Sorry, but these are not features we're interested in implementing for this component.

**Comment by Shackless** [comment]
Gotcha, thanks. I used Tabs instead which makes more sense, I guess.
