### ISSUE TITLE
Toast wishlist

### ISSUE THREAD

**Issue by saturnonearth** [skeletonlabs/skeleton#1311]
### Toast enhancement wishlist

I wanted to keep a list of some things I would like to see for Toasts. I may implement some of these myself, but I thought it would be convenient to keep a list around in case anyone else wants to tackle some of these.

- [x] Animate on destroy
- [x] Smooth transitions when toasts are being shifted around
 (see  #1312) 
- [x] Ability to hide X (close) button
- [x] Remain visible if hovering
- [ ] Ability for rich content via targeting of html node or ID.
- [x] Ability to programmatically close specific toasts by reference
- [ ] Ability to pass promise to Toast to programmatically close when promise completes or fails.
   - This one is a bit more complex and may not need to be implemented.
   
![chrome_0YIMRIqh9g](https://github.com/skeletonlabs/skeleton/assets/12503538/a640104e-7cd2-441c-98f7-f6d9d96edc2d)

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Seems like some nice additions. 

> Animate on destroy
> Smooth transitions when toasts are being shifted around

Down for these. Eye candy is always nice.

> Ability to hide X (close) button

We would have to set some conditions for this, such as not being able to disable or set super long timeouts. Otherwise users end up with perma-visible toasts on their screen. That seems like bad UX.

> Remain visible if hovering

This would take a bit of a rework. I'm not sure the timeout features we're using would support an interruption like this as designed. Maybe eventually though.

> Support prefers-reduced-motion (I wasn't sure if this wasn't already the case)

It's my understanding the Svelte transitions utilize this by default. This is part of why we default to these.

**Comment by saturnonearth** [comment]
> > Animate on destroy
> > Smooth transitions when toasts are being shifted around
> 
> Down for these. Eye candy is always nice.

I added PR for implementation of this


> > Support prefers-reduced-motion (I wasn't sure if this wasn't already the case)
> 
> It's my understanding the Svelte transitions utilize this by default. This is part of why we default to these.

Awesome! I'll remove that one then.

**Comment by Mahmoud-zino** [comment]
@endigo9740 @saturnonearth 
I am not understanding this feature:
> Ability for rich content via targeting of html node or ID.

does it mean that the users will be able to write HTML in the message? because this is already implemented:
```svelte
<div class="text-base">{@html t.message}</div>
```

**Comment by saturnonearth** [comment]
> @endigo9740 @saturnonearth I don't understand this feature:
> 
> > Ability for rich content via targeting of html node or ID.
> 
> does it mean that the users will be able to write HTML in the message? because this is already implemented:
> 
> ```svelte
> <div class="text-base">{@html t.message}</div>
> ```

What I mean is, as far as I am aware, the only current way to write the content for the toast is via the "message" prop. But if the person wants to display something more complex like a component within a toast, it would be nice to set a node as a target, instead of "message". Does that make sense?

**Comment by endigo9740** [comment]
@saturnonearth toasts are usually pretty simple notifications, by intention, what would be the use case here. Can you provide an example?

**Comment by saturnonearth** [comment]
> @saturnonearth toasts are usually pretty simple notifications, by intention, what would be the use case here. Can you provide an example?

Well for instance, you may want to add a loading icon to your toast.

**Comment by Mahmoud-zino** [comment]
@saturnonearth @endigo9740 
I was looking at the rich content feature and I would suggest that we implement it first in v2:

IMO having a node object is very flexible and customizable, which is a lot better than passing a message and handling a custom action button separately, we should give the user the ability and the freedom to implement their toasts like they want and we don't want to handle/maintain all available options (win-win). 😉

These are breaking changes and even if we wanted to just implement the node beside all other options, we have the message as required so making it optional would also be a breaking change.

also, I think the "promise" feature is somewhat redundant, the user can with 0 effort achieve this by adding the close logic to their promise `finally` block. 

any thoughts?

**Comment by endigo9740** [comment]
@Mahmoud-zino I agree on holding off on rich content. It's not always a matter of "can we", but also "should we". Toasts are mean to be small bits of information. Icons can help, but not a hard requirement. If they take substantial changes to implement they may just not be worth it...yet.

Also agreed on the promise changes - we should revisit all notification (modals, dialogs, toasts) in the future to have built in support for async behavior, but this will be another foundation change. Not something I'm too keep to prioritize right now.
