### ISSUE TITLE
Autocomplete unresponsive with large options dataset

### ISSUE THREAD

**Issue by jer-0** [skeletonlabs/skeleton#1317]
### Current Behavior

Hello, svelte animate and transition directive are causing autocomplete to be slow and unresponsive when the options dataset is large. 

### Steps To Reproduce

stackblitz: https://stackblitz.com/edit/skeletonlabs-repl-wjppky?file=src/routes/+page.svelte

with animate and transition directive removed I didn't notice stuttering: 
https://github.com/skeletonlabs/skeleton/blob/da5d2999cdfb2dae8b3d89d23d518d40600aeaca/src/lib/components/Autocomplete/Autocomplete.svelte#L117

### Anything else?

tested on google chrome 111 & firefox 111 on windows 11 (Intel(R) Core(TM) i7-9750H CPU )

**Comment by niktek** [comment]
https://user-images.githubusercontent.com/52020637/231642009-8e135e11-0853-4d08-9207-af22844f9efc.mp4

Confirmed on local copy - you can also see some artefacts of the animation towards the end as well

**Comment by Hugos68** [comment]
Could it be an idea to conditionally enable disable transitions wether they are inside the autocomplete list viewport using intersection observer? You only need to animate those that are in the viewport (usually a max of 15 items or so).
