### ISSUE TITLE
I can not disable styles for a layout in sveltekit.

### ISSUE THREAD

**Issue by FarhanAliRaza** [skeletonlabs/skeleton#1320]
### Current Behavior

When i create a new layout it automatically applies all skeleton css to it.

### Steps To Reproduce

1. Create a sample project with skeleton cli
2. Create one layout which imports all CSS
3. Create another layout that does not import any css

### Anything else?

It should not import all CSS in new layout without specifying it to import.

**Comment by Sarenor** [comment]
First and foremost, you can do me and the other contributors and maintainers a favor and not open an issue and a discussion, please.

Next: Where do you create your layouts? It's native SvelteKit behaviour that the top level layout affects all sub layouts, could you provide a bit more of a project structure, maybe even a [Stackblitz](https://stackblitz.com/fork/github/skeletonlabs/repl/tree/main/welcome)?

**Comment by FarhanAliRaza** [comment]
sorry. will continue on the discussion page.

**Comment by FarhanAliRaza** [comment]
Sorry for opening two different channels.
![Screenshot (31)](https://user-images.githubusercontent.com/62690310/231727506-634c0548-1fdf-4440-9e74-1b8634d64c61.png)
My Dashboard Layout with styles
![Screenshot (30)](https://user-images.githubusercontent.com/62690310/231727591-3d809634-3863-41d6-a0c7-d006a4286024.png)
My new layout without styles

I do not have any root layout .. As you can see in both images

**Comment by FarhanAliRaza** [comment]
When i remove all the css files it loads the page without css for a second and then it loads the css. That i clearly do not have in me layout file. I used different browsers and hard reloading to eliminate the cache problem.

**Comment by Sarenor** [comment]
That makes no sense oO.
Can you share the full repository?

**Comment by niktek** [comment]
That's how it works with CSS, try entering the URL's directly in the browser for a page on each layout and you'll see it only loads the CSS as directed.  But if you load the page with Skeleton CSS already applied and then navigate to a page in the other layout, the CSS remains as it has already been loaded.  You can get around this by adding `data-sveltekit-reload` on the link that goes between the two different layouts e.g. `<a data-sveltekit-reload href="/l2">Layout 1</a>`

**Comment by FarhanAliRaza** [comment]
thanks for your help
