### ISSUE TITLE
Popup: Allow passing a reference to an element instead of a string id

### ISSUE THREAD

**Issue by treo** [skeletonlabs/skeleton#1336]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

At the moment we need to specify a target that matches a `data-popup` attribute:
```
let popupSettings: PopupSettings = {
	// Set the event as: click | hover | hover-click | focus | focus-click
	event: 'click',
	// Provide a matching 'data-popup' value.
	target: 'examplePopup'
};
<button ... use:popup={popupSettings}>Trigger</button>
<div ... data-popup="examplePopup">(popup)</div>
```

As far as I can tell we are then getting a reference to the element as essentially the first thing in the popup action
```
	const elemPopup: HTMLElement | null = document.querySelector(`[data-popup="${args.target}"]`);
```

For my use-case (a drop down menu I want to be able to use in different places), it would be far more convenient if I could simply pass the reference directly. 

It could look something like the following. Notice that I've renamed `target` to `targetRef` so both options are still possible.
```
let popup;
let popupSettings: PopupSettings = {
	// Set the event as: click | hover | hover-click | focus | focus-click
	event: 'click',
	// Provide a matching 'data-popup' value.
	targetRef: popup
};
<button ... use:popup={popupSettings}>Trigger</button>
<div bind:this={popup}>(popup)</div>
```

Unless I'm missing something, it is probably a one or two line change to make that functionality available.

### What type of pull request would this be?

Enhancement

**Comment by Sarenor** [comment]
We have someone with a similar issue here:
https://github.com/skeletonlabs/skeleton/issues/1323

And I think what you want is currently not possible, the popup div needs a guaranteed binding point. Having multiples points where the same popup opens is the wrong way, you'll need one popup per opening place as far as I can tell.

I'm not the authority on popups though, I've used them in 1 place in my Skeleton App so far

**Comment by endigo9740** [comment]
@treo it's an interesting use can, and definitely not one served by the current popup. I'll have to take this into consideration. Being technically feasible is one thing, but we have to make accommodations to ensure the API or outwards facing interface for this is still easy for your average user.

We actually have a number of requests for improvements to the popup feature, so I'm going to be looking to refactor it soon to accommodate an expanded feature set, while also trying to preserve backwards compatibility to so we don't have to issue this as a breaking change.

No ETA for that, given our attention is elsewhere right now. But I'll post here when we've made progress on this. For now, I do expect the current solution will stick around for a little while. So do please plan accordingly.

**Comment by treo** [comment]
If it helps, I can PR a minimal change that I think would keep the API essentially the same. But if the popup feature is going to be changing anyway, it may not be worth the effort.

**Comment by endigo9740** [comment]
Not worth the effort yet, I really need to oversee the change so it takes everything new into account. But thanks for the offer!
