### ISSUE TITLE
Popup hover: target popup disappears when mouseout on parent element

### ISSUE THREAD

**Issue by rskvazh** [skeletonlabs/skeleton#1338]
### Current Behavior

Popup disappears when hovering on it. I think there maybe an option to showing target popup when hovering over it. As an example implementation: change `mouseout` to `mouseleave` and hide only after some delay (300-500 ms should be fine I think)

**Comment by endigo9740** [comment]
This would fall under a feature request more than a bug ticket @rskvazh. The behavior your described was not not the intention of how the current event handlers were implemented, therefore the popup is currently working as intended in this regard.

That said, I understand your use case. We have some updates planned for the popup based on various feature requests and feedback. But not ETA for when this will occur. For now I'll relabel this ticket and keep this for consideration when we reach that point. Given we have a number of these requests I may opt to consolidate these into a singular ticket in the new future.

Either way, keep an eye out here for progress on this going forward.
