### ISSUE TITLE
Shadows are not applying to AppRail

### ISSUE THREAD

**Issue by JustBarnt** [skeletonlabs/skeleton#1344]
### Current Behavior

Trying to apply shadows to `AppRail` through a `class` attribute fails to apply an actual shadow.

### Reproduction / Steps To Reproduce

Create an `AppRail` apply a class attribute with any `shadow-` variant.

**Comment by endigo9740** [comment]
@JustBarnt we need a combined ticket that outlines this and the issues in this other ticket:
https://github.com/skeletonlabs/skeleton/issues/1230

I'd appreciate some help detailing all pending updates for this component. That way we can knock them all out at once.

**Comment by endigo9740** [comment]
@JustBarnt I'm unable to replicate, the shadow is working for or me using:

```html
<AppRail selected={storeValue} class="shadow-xl shadow-primary-500">
```

I've given the shadow a color to make it more visible here:

![Screenshot 2023-04-21 at 3 51 48 PM](https://user-images.githubusercontent.com/1509726/233732575-acb6558b-7625-4f83-b949-d5edf220bffe.png)

One thing to note is if you're dropping the App Rail into a App Shell sidebar slot - the sidebar utilizes an overflow style, which may cut off the shadow. In that case you'll need to use something like `!overflow-visible` on the App Shell sidebar slot to revert this.

https://tailwindcss.com/docs/overflow

**Comment by JustBarnt** [comment]
Ah that explains it. I am using it in the AppBar.
