### ISSUE TITLE
Implementing CSP with <Lightswitch />

### ISSUE THREAD

**Issue by MyraManes** [skeletonlabs/skeleton#1349]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

When using the standard Lightswitch component, it injects the following script into the head:
```
<script>
(function setInitialClassState() {
  const elemHtmlClasses = document.documentElement.classList;
  const condLocalStorageUserPrefs = localStorage.getItem("modeUserPrefers") === "false";
  const condLocalStorageUserPrefsExists = !("modeUserPrefers" in localStorage);
  const condMatchMedia = window.matchMedia("(prefers-color-scheme: dark)").matches;
  if (condLocalStorageUserPrefs || condLocalStorageUserPrefsExists && condMatchMedia) {
    elemHtmlClasses.add("dark");
  } else {
    elemHtmlClasses.remove("dark");
  }
})();
</script>
```

If a user configures SvelteKit to use CSP, the browser throws an error because the inline script does not contain a nonce.

> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

SvelteKit will automatically add the nonce if %sveltekit.nonce% is added to the script tag:
`<script nonce="%sveltekit.nonce%">`

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
https://kit.svelte.dev/docs/configuration#csp
https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/utilities/LightSwitch/LightSwitch.svelte#L65

**Comment by endigo9740** [comment]
Adding some additional context here:
https://discord.com/channels/1003691521280856084/1048010639219642419/threads/1099012032843485314

I think this is a valuable add. We'll aim to add the `nonce` attribute to the script tag, so that it's always present, but ONLY if that doesn't interfere with with apps not utilizing CSP.

If implementing the attribute does cause issue, we'll need to find a way to dynamically implement this on demand.

**Comment by endigo9740** [comment]
@MyraManes FYI I've implemented this and saw no noticeable issue. We'll dogfood this internally on our dev branch through the remainder of the week. If there's no issue then this will be part of next week's release. Hope that helps!
