### ISSUE TITLE
Popup refactor and extension

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1350]
We've had a number of issues and feature requests reported for the current popup implementation. Likewise we've had a bit of "feature creep" since the inception. Given this I'm going to aim for a refactor of this component utilizing all information we have available to us for this component.

This may include a number of new feature requests:

- [x] https://github.com/skeletonlabs/skeleton/issues/1014
- [x] Make it easier to create tooltips (reference [#1332](https://github.com/skeletonlabs/skeleton/pull/1332))
- [x] https://github.com/skeletonlabs/skeleton/issues/1338
- [x] https://github.com/skeletonlabs/skeleton/issues/1336

I'll also aim to address a number of reported bugs:

- [x] https://github.com/skeletonlabs/skeleton/issues/1345
- [x] https://github.com/skeletonlabs/skeleton/issues/1282
- [x] https://github.com/skeletonlabs/skeleton/issues/1337
- [x] https://github.com/skeletonlabs/skeleton/issues/1379 ([potential PR fix](https://github.com/skeletonlabs/skeleton/pull/1415))

New issues reported in the thread below:

- [x] Make considerations for popups used within a loop ([reference](https://discord.com/channels/1003691521280856084/1048010639219642419/threads/1099704955478212628))
- [x] consider a way to support multiple popups on one trigger - ex: tooltip + popup ([reference](https://discord.com/channels/1003691521280856084/1100073004815351939))
- [x] The closeQuery: `''` selector should default all child element closing the popup
- [x] Hover popups flicker when using an icon inside a button instead of text (CHRIS: `btn-icon` works best)
- [x] Document: The target in popup settings must be unique, otherwise this may lead to undesired behavior

If you have new ideas or suggestions related to the popup I'm going to ask that you focus them here for now. If the issues is large enough to require a dedicated ticket I'll split it off as need. But I think we need a "wholistic" approach to these updates to ensure everything continues to work in unison as expected.

---

Not implemented / Not supported

> NOTE: I'll move items down here that we don't intend to move forward with or cannot support. I'll response in each ticket with a detailed follow up for this designation 

- [x] https://github.com/skeletonlabs/skeleton/issues/1327
- [x] https://github.com/skeletonlabs/skeleton/issues/1323

**Comment by endigo9740** [comment]
To review:
https://discord.com/channels/1003691521280856084/1048010639219642419/threads/1099704955478212628

**Comment by endigo9740** [comment]
Note: consider a way to support multiple popups on one trigger (ex: tooltip + popup)

**Comment by endigo9740** [comment]
The `closeQuery: ''` selector is still not working as intended. This default to anchor/button, but should be used to clear and provide NO value. Currently users have to hack around this by passing a fake query element, like `closeQuery: 'x'`

**Comment by Mahmoud-zino** [comment]
The `target` in the popup settings must be unique, otherwise when duplicated the first popup defined in the DOM will always be triggered, which could lead to unwanted behavior.

A note in the popup documentation would be great.

**Comment by Schroedi** [comment]
Skeleton 1.2.5 produces flickering popups when run on my machine but not in a stackblitz playground. Version 1.2.0 does not have this issue. 
I tried using the same nodejs version as the stackblitz repl (v16.14.2) but that did not solve the problem.

Attached are videos of the bugged and bug free version.

Here is the test project:
https://stackblitz.com/edit/skeletonlabs-repl-ltvnu4?file=src/routes/+page.svelte


https://user-images.githubusercontent.com/97124/235256573-7dc1c4b0-2fe6-4477-8bea-95c8d4f2c9c7.mp4


https://user-images.githubusercontent.com/97124/235256575-13e5d464-99d9-4bc9-bc2a-a41f07f2dd34.mp4

Reporting here as suggested in Discord: https://discord.com/channels/1003691521280856084/1101608283808210944

**Comment by Sarenor** [comment]
https://github.com/skeletonlabs/skeleton/pull/1415#issuecomment-1529942148
Remember to go with ``mouseover`` and ``mouseleave`` for hover ;)

**Comment by endigo9740** [comment]
FYI I've updated the original post at the top of this thread, this now denotes all known issues to target and resolve as part of the upcoming update. I think at least couple of these are duplicates or related, but I'll use this list as a reference for test cases. I'll reach out to the user that reported issues if I need more information.

**Comment by endigo9740** [comment]
Alright folks, I've made a solid dent in the popup rework today. I'm rewriting large portions of the action to lay the groundwork for the upcoming fixes and updates:
https://github.com/skeletonlabs/skeleton/pull/1421

Preview here:
https://skeleton-docs-git-feat-popup-rework-skeleton-labs.vercel.app/utilities/popups

Per today's update, there are a few notable improvements:

- The action logic is a lot leaner and streamlined, while maintaining the same outwards facing API for params
- Events are limited, but better, including: `click | hover | focus-blur | focus-click`. I'll document these soon.
- The action now has error handling when it can't find the popup or a required Floating UI module (ex: computePosition)
- More and better examples have been provided on the documentation, with more still to come
- I'm nearly at feature parity with production, and expect to this this sometime tomorrow

Do please note that I have disabled the popups in the App Bar during testing. I will re-enable them soon!

**Comment by endigo9740** [comment]
I'm happy to report that I've now completed my first pass of the refactor. We should now have feature parity with the production version of the popup, as well as support for a number of new features and bugfixes.

Preview here:
https://skeleton-docs-git-feat-popup-rework-skeleton-labs.vercel.app/utilities/popups

I'll detail these below in no particular order:

1. We now optionally support additional Floating UI middleware, including: size, autoPlacement, hide, inline. However in testing these appear to alter the default behavior of all popups when enabled, so it's recommend you only enable them as needed and if you know what you're doing. Some refinement may be needed here, but the foundation is now laid.
2. I made considerations for creating a simpler way to create tooltips, however, I think the best option is just to inline in the `use:popup` params. No changes were implemented on my side for this, users can abstract this on their end if they prefer.
3. The `hover` event now uses `mouseover/mouseleave` in favor of `mouseover/mouseout`. This provides a number of fixes and improvements.
4. When focus is on the Trigger element you can now hit Tab/ArrowDown to jump to the popup. This will still auto-focus the first focusable child element within the popup, per ARIA APG guidelines. I've also modified the List element focus style to differentiate this from the active state. This should help prevent user confusion, thinking the focused item is active.
5. I also fixed a bug related to Tab/ArrowDown skipping options for Autocomplete options. This now correctly focuses the first item in the list.
6. Trigger elements can now support multiple `use:popup` actions. This means you can now have both a tooltip-like hover popup as well as a click-to-display drop down popup on the same trigger. Previously these would fight one another.
7. I've provided an official recommendation here when reacting popups within an `#each` loop: https://github.com/skeletonlabs/skeleton/issues/1323#issuecomment-1533690982
8. Fixed a bug with `closeQuery: ''`, this will now prevent child elements from closing the popup. Anchor/button are set by default if no value is provided here.
9. I provided a tip in the `hover` event type code snippet to prevent child elements, like icons, from closing the hovered popup early. In short, you need to disable pointer events for child elements on your target element (ex: button).

I've also made great strides to provide more and better documentation top-to-bottom for this feature. There's a lot more examples and the instruction should be much more clear. All requirements are laid out in full. However, I welcome feedback if you find any gaps!

**Comment by endigo9740** [comment]
Per the above message, I'm going to ping a number of users here to help review and test the changes to the popups in the pending pull request. If you have the ability to pull and test this, please do:

@Sarenor @JustBarnt  @Mahmoud-zino @Schroedi @cmjoseph07 @DevOfManyThings @saturnonearth @rskvazh @jeromecc @ecejeff @sssuneeth

Again, you can preview the updated documentation here:
https://skeleton-docs-git-feat-popup-rework-skeleton-labs.vercel.app/utilities/popups

View the code changes here:
https://github.com/skeletonlabs/skeleton/pull/1421

If anyone is interested in having a version of our package built against this branch, to test in your own projects, let me know. I'll be happy to provide that tomorrow!

**Comment by Mahmoud-zino** [comment]
@endigo9740 you didn't mention using only a unique popup `target` in the docs. related to #1282 

The code handling the target didn't change so maybe you forgot to mention it.

please tell me if I can help, I would be happy to.

**Comment by endigo9740** [comment]
@DevOfManyThings #3 from my list above:

> The hover event now uses mouseover/mouseleave in favor of mouseover/mouseout. This works much better in a number of scenarios and seems much less error prone.

@Mahmoud-zino this is present in the code snippet instruction for the featured demo at the top of the page:

![Screenshot 2023-05-04 at 10 39 24 AM](https://user-images.githubusercontent.com/1509726/236258212-d6fb59eb-97f0-4c12-90d9-f48eb7f741d7.png)
