### ISSUE TITLE
Forward on:blur/Enable submission of InputChip partial input.

### ISSUE THREAD

**Issue by Guyzeroth** [skeletonlabs/skeleton#1358]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Currently InputChip text requires a enter key press to submit the values. In the event that values are partially complete it would be helpful to be able to submit the partial input on blur. `on:blur` will need to be propagated up for this.  

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

An example of this is https://material.angular.io/components/chips/overview#chips-input

Here they have a ```addOnBlur``` flag This could also be a nice solution.

**Comment by endigo9740** [comment]
@Guyzeroth I've managed to squeeze this in before tomorrow's release. This will now forward both the `focus` and `blur` events on the input chip. Thanks for the suggestion!
