### ISSUE TITLE
The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.

### ISSUE THREAD

**Issue by bfovez** [skeletonlabs/skeleton#1359]
### Current Behavior

I post the issue here and in the Lucide github.
When using Skeleton and lucide-svelte, I get this:

> 10:59:41 [vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.
> lucide-svelte@0.176.0
> Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve for details.

### Reproduction / Steps To Reproduce

1. Create a bare bones Skeleton project : npm create skeleton-app@latest my-skeleton-app
2. Add lucide-svelte : npm i lucide-svelte
3. Add a icon on the +page.svelte (for instance \<LucideRefreshCw \/\>, along with "import { LucideRefreshCw } from 'lucide-svelte'" in the <script> section)
4. Launch the server: npm run:dev
5. Load the page in a browser
6. Quit the server (Ctrl-C / Cmd-C)

**Comment by Sarenor** [comment]
Have you tried this with just a SvelteKit starter? I'm 95% sure that it's a lucide problem we can't change.

**Comment by bfovez** [comment]
I'm pretty sure too. The issue is filed on their side too.
I'm checking with SvelteKit starter

**Comment by Sarenor** [comment]
Turns out you're completely right and new behaviour just caught me from left field.
Seems like we do need to update the package.json of the Skeleton Package to remove the ``"svelte"`` field and put that under the ``exports`` object.
Thanks for reporting!

(Lucide still needs to do this, too, afaik).

[this link](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve) provided by bfovez explains it pretty well.

**Comment by endigo9740** [comment]
Thanks for reporting this @bfovez we'll get this fixed asap. Of course a PR is welcome in the meantime.

**Comment by niktek** [comment]
Hi @bfovez,

I've removed the top level svelte field in the package.json and it seems to have cleared the issue.  If you are able to do a test locally to confirm on your side, that would be greatly appreciated.
[skeletonlabs-skeleton-v1.2.1.tgz](https://github.com/skeletonlabs/skeleton/files/11315468/skeletonlabs-skeleton-v1.2.1.tgz)

Instructions for adding a tarball are here: https://github.com/skeletonlabs/skeleton/wiki/Create-and-Install-Test-Packages#install-a-tarball-package

**Comment by bfovez** [comment]
Hi,

I've tested it locally as instructed, and I confirm that the message for
Skeleton no longer shows up. The remaining part is for Lucide, as expected.
Thank you very much for the fix, and more globally for bringing Skeleton
into our dev life!

Bertrand
