### ISSUE TITLE
Vertical orientation for the Range Slider component

### ISSUE THREAD

**Issue by roysupriyo10** [skeletonlabs/skeleton#1378]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I assume that this can be accomplished using the Tailwind library or plain CSS in general, however, the mouse interactivity remains an issue for different devices. A native solution to this would be great such as adding the prop `orientation="vertical"` would be great to relieve the development experience. It would be of great help to me and all the others who have a usecase of using the range slider component in the vertical orientation.

### What type of pull request would this be?

None

### Any links to similar examples or other references we should review?

The MaterialUI library of react has this feature as a prop that can be passed to the <Slider /> component. A similar implementation would be great.

**Comment by endigo9740** [comment]
Thanks for the request @roysupriyo10. This is something we considered when building the component, unfortunately it likely will be possible right now. The reason for this is we just wrap the native range input and provide a simple component-based API for utilizing the native feature.

Per the MDN docs, the vertical orientation is marked as "non standard", which means not all browsers support it:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

![Screenshot 2023-04-26 at 10 36 19 AM](https://user-images.githubusercontent.com/1509726/234627490-0e5e5143-54ec-43e5-a9fa-6462e3966de8.png)

Given this, the only option to implement would be recreate this element from the ground up. I'm assuming that's what libraries such as Angular do. That doesn't really align with Skeleton's goals for inputs - which is to say to keep things native first, wrap if we need to, and replace as a last ditch effort.

I will keep this idea in mind, but for now this likely will not be something we move forward with. That said, we do have plans to implement more standardized features, such as labels in the near future. So keep an eye out for that.
https://github.com/skeletonlabs/skeleton/issues/1066
