### ISSUE TITLE
Popup is not working fine on live as in dev env.

### ISSUE THREAD

**Issue by sssuneeth** [skeletonlabs/skeleton#1379]
### Current Behavior

Popup is working fine on dev env but when it comes in live, that popup disappears when I hover and move around on trigger div.
And I'm using popup inside a loop, here is the main code

```html
<script lang="ts">
	// skeleton and floating-ui
	import { popup } from '@skeletonlabs/skeleton';
	import type { PopupSettings } from '@skeletonlabs/skeleton';
	import { computePosition, autoUpdate, flip, shift, offset, arrow } from '@floating-ui/dom';
	import { storePopup } from '@skeletonlabs/skeleton';

	storePopup.set({ computePosition, autoUpdate, flip, shift, offset, arrow });

	let popupSettings: PopupSettings = {
		event: 'hover', // event
		target: 'my_list_popup' // data-popup value
	};
</script>

<div>
	<div>
		{#each my_list as anime}
			<div
				use:popup={popupSettings}
			>
				<div>
                                        <!-- trigger code -->
                                </div>
			</div>
                        <div
				data-popup="my_list_popup"
			>
				<!-- popup code -->
				<div class="arrow bg-surface-50" />
			</div>
		{/each}
	</div>
</div>
```

### Anything else?

[Screencast from 2023-04-26 20-34-04.webm](https://user-images.githubusercontent.com/114811070/234635596-3531c646-bd9f-4cae-b647-275d3fc63cbf.webm)

1st one is the live site and 2nd one is the dev env ( localhost )
The problem is with the 1st one ( live )

**Comment by sssuneeth** [comment]
>  you raised this question on Discord a couple days ago and received a couple responses.
 but did this not resolve your issue?

Yea, but It was an another issue, we fixed that.

Now its different, popup is showing but its kinda like flickering when I hover and move around the child elements.
Its fine on my dev env, here is the live site

https://core-project-v3-3nivi0l9q-suneethsunx.vercel.app/
Try hovering in that bottom cards

**Comment by endigo9740** [comment]
Ok thanks for confirming. I'll try to circle back to this soon. FYI we do have a notable update coming to the popup feature soon. So please note some popup-related updates will come as part of that:

https://github.com/skeletonlabs/skeleton/issues/1350

I've included your ticket on the list here just in case.

**Comment by Sarenor** [comment]
I'm sorry to say tis but it's a classic case of popup-in-each-block.
Each popup needs it's own unique ``data-popup`` id otherwise the flicker you mentioned happens.
Let me look around there should be a closed issue where I typed out the solution already

**Comment by Sarenor** [comment]
Got it:
https://github.com/skeletonlabs/skeleton/issues/1323#issuecomment-1511099756

**Comment by baseplate-admin** [comment]
Thanks for your answer and response. But may i ask this to be added to the documentation?

**Comment by Sarenor** [comment]
We'll have to think about how and where, just adding "a unique data-popup" value in the props tab is probably not enough.

Full popups-in-each-block example is probably the better choice with an explanatory message below.

I'll let @endigo9740 weigh in if that still makes sense before the popup refactoring before getting started with it though :)

**Comment by sssuneeth** [comment]
> Got it:
https://github.com/skeletonlabs/skeleton/issues/1323#issuecomment-1511099756

I saw this issue before and tried that same way, but Its not even showing back then.

>just adding "a unique data-popup" value in the props tab is probably not enough.

Yea thats right, with unique "data-popup" value it shows the data of first element in the loop, data is not updating when hovering other elements.

**Comment by Sarenor** [comment]
Do you still have an example of where you tried it?

**Comment by sssuneeth** [comment]
> Do you still have an example of where you tried it?

Actually I removed that, @baseplate-admin shows a different way.
Yea I can provide the code, please wait :)

**Comment by sssuneeth** [comment]
@Sarenor Hey! sorry for being late,
here is the code link
https://github.com/sssuneeth/CoreProject-V3-UI/blob/e1fc81cba23ec79c6e2101bc4203521ad004b185/src/routes/%2Bpage.svelte#L579-L697

And as I said earlier - its not even showing and has some ts errors in this code ( https://github.com/skeletonlabs/skeleton/issues/1323#issuecomment-1511099756 )

here is the current behaviour:
[Screencast from 2023-04-29 09-29-23.webm](https://user-images.githubusercontent.com/114811070/235282631-2e550d8f-c45c-412a-8915-3130b5b4798d.webm)

**Comment by Sarenor** [comment]
It should look like this on hover, shouldn't it?

<img width="414" alt="image" src="https://user-images.githubusercontent.com/31982384/235436874-7c74ace0-bb1c-41a7-bd80-8fdc33119332.png">

If so: While hovering the background div, it works with the ``+page.svelte`` version you linked.
It just fails when you hover over the buttons, because it left the background div.
We had a similar issue half a year ago I think and found a solution. I just can't remember it.
@endigo9740, can you (while I look around and try to remember)?

Also sorry for getting back to you so late, I was away over the weekend.

And beautiful site design! You definitely need to share this in the #showcase section in the Discord once you feel like it's done and ready, it's beautiful!

**Comment by Sarenor** [comment]
Ah. Yeah, I remember.
We had this issue in the previous version of popups (before we used floating-ui) because we used 
```js
  node.removeEventListener('mouseover', onMouseOver, true);
  node.removeEventListener('mouseout', onMouseOut, true);
```
Instead of [mouseenter](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event) and [mouseleave](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event).
Let me PR that again, should probably be in the next release.

**Comment by baseplate-admin** [comment]
Thank you @Sarenor, for your kind words.


> And beautiful site design! You definitely need to share this in the #showcase section in the Discord once you feel like it's done and ready, it's beautiful!

The design was done by @akindworld ( he is a pro ). 


We Will definitely showcase the site. But now its not yet quite upto our expectations. We will launch when we finish everything :)

**Comment by endigo9740** [comment]
Just a quick reminder that I will not be reviewing popup related issues until I put my full attention on the popup refactor issue. Everyone is to welcome to continue troubleshooting on their own, but I'm not going to devote time to a temporary solution that may or may not make it into the final update.

Your patience is welcome in the meantime. Just keep noting issues as you find them and I'll review all in one go when I reach that point.
