### ISSUE TITLE
Show how to reduce bundle size when using highlight.js in CodeBlocks

### ISSUE THREAD

**Issue by treo** [skeletonlabs/skeleton#1381]
### Link to the Page

https://www.skeleton.dev/utilities/codeblocks

### Describe the Issue

When using highlight.js as described, it results in a huge bundle size increase (+1MB). 

It would be good to document a different way of loading it, such that languages can be loaded dynamically.

My crude workaround for it looks like the following, but that is bad in many different ways. And shouldn't be copied. Unfortunately, I don't know of a better way to make it work. Dynamically loading from a library isn't supported by vite, so I used a public CDN for it, but that comes with its own problems, like being bound to a particular version.

Layout.svelte:
```
	import hljs from 'highlight.js/lib/core';
	import plaintext from 'highlight.js/lib/languages/plaintext';
	import 'highlight.js/styles/tomorrow-night-bright.css';
	import { storeHighlightJs } from '@skeletonlabs/skeleton';

	hljs.registerLanguage('plaintext', plaintext);
	storeHighlightJs.set(hljs);
```

CodeRenderer.svelte:
```
<script lang="ts">
    import hljs from 'highlight.js/lib/core';

    import { CodeBlock } from '@skeletonlabs/skeleton';
    import {browser} from "$app/environment";
	export let lang;
	export let text;

    $: actualLang = lang ? lang : 'plaintext'
    let loadedLangs = {
        plaintext: true
    }
    $: loadLanguage(actualLang)

    async function loadLanguage(actualLang) {
        if (!loadedLangs[actualLang] && browser) {
            try {
                /* @vite-ignore */
                const languageModule = await import(`https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/es/languages/${actualLang}.min.js`);
                hljs.registerLanguage(actualLang, languageModule.default);
                loadedLangs[actualLang] = true;
            }catch (e) {
                console.info(`Language ${actualLang} not found for highlight.js`);
            }
        }
    }
</script>

{#if loadedLangs[actualLang]}
    <CodeBlock language={actualLang} code={text} />
{:else}
    <CodeBlock language="plaintext" code={text} />
{/if}
```

### Are you able to create a Pull Request with the fix?

None

**Comment by endigo9740** [comment]
Hmm I haven't noticed bundle sizes reaching quite that scale. In fact the entire Skeleton documentation site, which utilizes nearly every feature we provide, is about 612 kb total.

That said, we do note there's some room for improvement in regards to CSS purging. But I agree with your suggestion here, more options are typically better. Thanks for the suggestion!

**Comment by endigo9740** [comment]
Note that this update will come as part of our transition to a standalone package for the Code Block feature.

**Comment by endigo9740** [comment]
Looks like this issue got orphaned from the PR. This is resolved, see the PR link above for details.
