### ISSUE TITLE
Autocomplete list limit

### ISSUE THREAD

**Issue by Jala015** [skeletonlabs/skeleton#1382]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Limit the size of the autocomplete list or just start showing it after the input value has length == n. Is useful when the options list is long.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

Check the minCharacters and maxResults options for SemanticUI search: [semantic-ui.com](https://semantic-ui.com/modules/search.html#/settings)

**Comment by endigo9740** [comment]
@JustBarnt feel free to tackle this if you get to it before me. Thanks for reporting this @Jala015.

**Comment by JustBarnt** [comment]
Sounds good I'll be pretty distant this week or so as I slowly work on all these edits from the wedding I did. But hopefully I'll be able to get back into some issues in the next week or so!

**Comment by endigo9740** [comment]
I had time to jump on this. The new prop will be called `limit`. Check the Props documentation for this when the next release drops. Thanks!
