### ISSUE TITLE
Popup first in animation looks off

### ISSUE THREAD

**Issue by sssuneeth** [skeletonlabs/skeleton#1384]
### Current Behavior

When I hover on trigger, popup shows without any animations like fade in.
Note: This happens only in the first opening, fine later

### Anything else?

[Screencast from 2023-04-27 19-14-39.webm](https://user-images.githubusercontent.com/114811070/234882645-3b431403-c408-468a-8f47-f0bb18a3bbd2.webm)

**Comment by endigo9740** [comment]
We currently have like 10 issues open just for popups alone. These loose tickets aren't very helpful given we have a centralized ticket for the upcoming refactor. Please move your comment here:
https://github.com/skeletonlabs/skeleton/issues/1350
