### ISSUE TITLE
Ability to Hide Toast Close Button When AutoHide is set to true.

### ISSUE THREAD

**Issue by LuminareHQ** [skeletonlabs/skeleton#1395]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

By the example below, the ability to hide a Toasts close button, such as when autohide on the ToastSettings is set to true, or in general having the option to hide the Toast's Close button with a boolean value.

By Default, the value being True and showing the Close Button, but giving the option to hide the Close button.

![image](https://user-images.githubusercontent.com/70502610/235054298-ddab7940-2d4d-493d-bcc4-b3c268e09fad.png)
![image](https://user-images.githubusercontent.com/70502610/235054255-0a0c59ba-ea81-499e-9ae5-f51a716b9215.png)

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

N/A

**Comment by endigo9740** [comment]
This is a duplicate to: https://github.com/skeletonlabs/skeleton/issues/1311

I covered some of my concerns with this here: https://github.com/skeletonlabs/skeleton/issues/1311#issuecomment-1504091874

Overall I think it's something we'll add, just as long as the constraints mentioned are put in place.
