### ISSUE TITLE
Missing vertical alignment for <ListBoxItem /> component

### ISSUE THREAD

**Issue by lucaskfp** [skeletonlabs/skeleton#1399]
### Current Behavior

When using the <ListBoxItem /> component with the "lead" or "trail" slots and if the slot and the content have different heights, we lose the vertical alignment

### Reproduction / Steps To Reproduce

![image](https://user-images.githubusercontent.com/19507510/235261469-9ba13980-158d-4743-a934-86ec1ccf5a0b.png)
![image](https://user-images.githubusercontent.com/19507510/235261311-e5084efa-1dea-42cf-a2a7-4844bb88d8d2.png)
![image](https://user-images.githubusercontent.com/19507510/235261336-1b2d097a-3e90-4307-afca-201fbfa474c6.png)

### Anything else?

[Thread on discord](https://discord.com/channels/1003691521280856084/1048010639219642419/threads/1101592578501115935)

**Comment by endigo9740** [comment]
Given the small change (one class name) I've included this as part of another PR. This change will be included in next week's release!

**Comment by lucaskfp** [comment]
> Given the small change (one class name) I've included this as part of another PR. This change will be included in next week's release!

Thanks
