### ISSUE TITLE
prevent modal closing on:backdrop

### ISSUE THREAD

**Issue by Kokoserver** [skeletonlabs/skeleton#1401]
### Describe the Issue

I try to look for a way to prevent the modal closing with on:backdrop, please is there any way to archieve this 

### Are you able to create a Pull Request with the fix?

None

**Comment by endigo9740** [comment]
@Kokoserver we do not support this, sorry. Please read our message about the impact on accessibility here:
https://www.skeleton.dev/utilities/modals#accessibility
