### ISSUE TITLE
InputChip form reset behaviour

### ISSUE THREAD

**Issue by SubjectiveTeam** [skeletonlabs/skeleton#1407]
### Current Behavior

When you have an InputChip component with a required property and for example add the tag 'strawberry' to it and then submit the form, the input will be cleared but the strawberry tag remains. This in and of itself isn't an issue but then when you try to submit the form again (with the strawberry tag already added from before last submit) the form wil not submit because we haven't filled anything in the inputchip yet because we have a 'required' tag on it. To fix this currently you need to remove the tag and add it again.

### Reproduction / Steps To Reproduce

1. Import a InputChip component in your html
2. Surround it with a form that can be submitted
3. Add use:enhance to the form (no callback needed for repro)
3. Add the required tag to the InputChip component
4. Add the name atrribute to the InputChip (what name is irrelevant)
5. Add any chip like 'strawberry' to the InputChip component
6. Submit the form
7. Observe the input chip stays even though other inputs like text, number, etc would reset normally
8. Try to submit again, it will fail due to the InputChip not having a value even though it does

Picture:
![image](https://user-images.githubusercontent.com/131908250/235371251-1ebf7709-6b2a-403f-994f-ac03d64574d6.png)

### Anything else?

I suggest you have an event listener that listens to its parent form with this: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset_event when that event fires you should clear the tags from the InputChip internally so that not only the input but also the tags get cleared on a form submission

**Comment by Sarenor** [comment]
https://www.skeleton.dev/blog/component-form-handling -> Resetting defaults
Currently, it's not a bug, it's working as intended.
We might be able to come up with a reset that sets it to the preferred default, but our current way is to leave this in the hands of the developer.

**Comment by SubjectiveTeam** [comment]
> https://www.skeleton.dev/blog/component-form-handling -> Resetting defaults Currently, it's not a bug, it's working as intended. We might be able to come up with a reset that sets it to the preferred default, but our current way is to leave this in the hands of the developer.

Surely its not intended behaviour to clear value's inside the html selects but keep them in the tags, that just creates an invalidate state, I suggest either keep both or remove both

**Comment by Sarenor** [comment]
Clearing the html input is sadly a default that I don't know how to override.

I haven't thought much about it, but I currently don't have a clear picture on how to figure out the (correct) parent Form element to attach the listener to, either.
Happy for suggestions if you have them!

**Comment by SubjectiveTeam** [comment]
thanks for the info, I'll look into a solution/suggestion myself
