### ISSUE TITLE
Animated App Shell

### ISSUE THREAD

**Issue by BartoszGe** [skeletonlabs/skeleton#1413]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Add animations to 'app shell' component when left or right sidebars are expanded

### What type of pull request would this be?

Enhancement

**Comment by BartoszGe** [comment]
https://jsfiddle.net/jpeter06/a5cu52oy/

**Comment by endigo9740** [comment]
@BartoszGe this is already possible by animating the contents within the sidebar slots. Additionally you can implement your own CSS Animations via the `slotSidebarLeft` and `slotSidebarRight` slots. This is a bit too opinionated to implement into the app shell itself.
