### ISSUE TITLE
Labeled slider shows a dropdown when slider is clicked but not dragged 

### ISSUE THREAD

**Issue by sachinbhutani** [skeletonlabs/skeleton#1420]
### Current Behavior

Labeled slider shows a dropdown when slider is clicked but not dragged 
![image](https://user-images.githubusercontent.com/6120010/235796772-81aead5d-bdf7-4c6e-9674-5a059f4ac5b8.png)

### Reproduction / Steps To Reproduce

Examples from docs page at https://www.skeleton.dev/components/range-sliders can be used 

### Anything else?

Noticed only on Firefox , using version 112.0.2 
May not be replicated on chrome.

**Comment by endigo9740** [comment]
@sachinbhutani Just for context, we implement this using a native input[range] element, so we're subject to how this operates in each browser:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#adding_tick_marks

Unfortunately bad news here. Looking into this a bit more I finally understand what this is doing - it's open up a browser native drop-down when you tap and hold on the meter (the draggable circle). This is implemented straight into the browser and reviewing the MDN documentation I see mention of showing or hiding this, though I was able to replicate on their docs:

![Screenshot 2023-05-04 at 3 51 01 PM](https://user-images.githubusercontent.com/1509726/236327096-55a448b2-a299-4be9-9587-32f2746e80a1.png)

The UX implementation of this is really poor IMO, but here's a few tidbits I noticed:

1. If you tap the track (the bar itself) this will not trigger
2. If you reload the page and drag the meter, this will not trigger
3. It's only when you tap and hold on the meter that this will trigger
4. Once it starts to appear it'll continue to appear from that point forward

Unfortunately this is an upstream issue. I would suggest filing a bug ticket with Firefox and see if they can provide any recommendations. Aside from creating a custom element (which is not likely) there's not much we can on our end.

Sorry we can't be more help!
