### ISSUE TITLE
AppRailTile still requires "value" prop for pageState usage

### ISSUE THREAD

**Issue by benbrunyee** [skeletonlabs/skeleton#1424]
### Current Behavior

I'm currently using a pre-built theme (specifically, the crimson theme) along with the [AppRailTile](https://www.skeleton.dev/components/app-rail) component. However, I've noticed that when I use the href prop instead of the value prop, the bg-primary-active-token class doesn't get removed when navigating away. This class is only removed if I also provide the value prop with the same value as the href prop, which seems unnecessary.

To clarify, when using the href prop without the value prop, the bg-primary-active-token class should be removed when navigating away, but this isn't happening. It's only removed if I also include the value prop with the same value as the href prop, which seems redundant.

### Reproduction / Steps To Reproduce

1. Use 2 `AppRailTile`'s and `crimson` theme (this may apply to other themes)
2. Add the following props
```
<AppRailTile
  tag="a"
  label="Home"
  href="/"
  class={"/" === $page.url.pathname ? "!bg-primary-500" : ""}
/>
<AppRailTile
  tag="a"
  label="Config"
  href="/config"
  class={"/config" === $page.url.pathname ? "!bg-primary-500" : ""}
/>
```
3. Navigate by clicking on the "Config" tile
4. Navigate back to the root page by clicking on the "Home" tile.
5. Watch as the active background persists on the "Config" AppRailTile.

### Anything else?

I believe the issue resides in the comparison made here: https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/components/AppRail/AppRailTile.svelte#L46

Where the comparison is made again the `value` prop, even when using `href`.

**Comment by Sarenor** [comment]
I thought we had a similar issue, but it might have been a discussion on discord instead.
If I remember correctly there was generally agreement to this being a good enhancement.

**Comment by endigo9740** [comment]
@benbrunyee FYI we had a contribution come in this week that alters the way the AppRail/Tile operates. When using anchor tiles you can now just opt for `href` and it'll take the place of `value`. Likewise this now supports passing a deferred store, which can be helpful when using the `page` store.

You can view the code changes here:
https://github.com/skeletonlabs/skeleton/pull/1402

And preview the documentation updates here:
https://skeleton-docs-git-fork-unlocomqx-feat-app-cbd12f-skeleton-labs.vercel.app/components/app-rail#page-state

I'd recommend you review this when it drops next week as I believe this may address your issue. If you continue to have issues, let me know and we'll gladly reopen this ticket.

Thanks!
