### ISSUE TITLE
Allow code as a slot in CodeBlock

### ISSUE THREAD

**Issue by h7kanna** [skeletonlabs/skeleton#1435]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Something similar to

```
<CodeBlock language="ts">
~~~
const skeleton: string = 'awesome';
~~~
</CodeBlock>
```

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@h7kanna unfortunately what you posted here is not valid markup. The page would try to render the tripe tilde and code between the `<CodeBlock>`. This is why we opted for the template literal. By converting to a string the code won't actually be triggered.
