### ISSUE TITLE
Sticky Sidebar

### ISSUE THREAD

**Issue by shadowempire123** [skeletonlabs/skeleton#1439]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Hi.
is there a way to have a sticky sidebar like you do in the pageheader (see https://www.skeleton.dev/components/app-shell).
thx

### What type of pull request would this be?

Other

**Comment by LukeHagar** [comment]
Hey @shadowempire123,

I'm not sure I fully understand the request. If you look at the link the existing leftSidebar is already **sticky** due to the way the app-shell works. 

I'm happy to look at this further if you can clarify what you mean.

**Comment by endigo9740** [comment]
@shadowempire123 yeah the sidebar positions for the app shell are fixed by default. If you can provide an example it might help.

**Comment by endigo9740** [comment]
No example provided, closing this out.
