### ISSUE TITLE
The `!min-w-fit` class does not exist.

### ISSUE THREAD

**Issue by calmdev** [skeletonlabs/skeleton#1443]
### Current Behavior

Using input group sample markup from documentation page:
https://www.skeleton.dev/elements/forms#input-groups

```html
<div class="input-group input-group-divider grid-cols-[auto_1fr_auto]">
	<div class="input-group-shim">(segment)</div>
	<input type="search" placeholder="Search..." />
	<button class="variant-filled-secondary">Submit</button>
</div>
```

Within an component results in vite exception:
> [plugin:vite:css] [postcss] 
node_modules/@skeletonlabs/skeleton/src/lib/styles/tailwind.css:13:1: 
The `!min-w-fit` class does not exist. 
If `!min-w-fit` is a custom class, make sure it is defined within a `@layer` directive.

![Screenshot 2023-05-05 at 3 29 47 PM](https://user-images.githubusercontent.com/461249/236553800-bd7fc61b-9281-4cbb-9f50-66d38689ffaf.png)

### Reproduction / Steps To Reproduce

1. Go to input groups docs: 
https://www.skeleton.dev/elements/forms#input-groups
2. Copy example code
```html
<div class="input-group input-group-divider grid-cols-[auto_1fr_auto]">
	<div class="input-group-shim">(segment)</div>
	<input type="search" placeholder="Search..." />
	<button class="variant-filled-secondary">Submit</button>
</div>
```
3. Place into a component
4. Try to use the component

### Anything else?

* Project was created with skeleton CLI.  
* Recently upgraded both skeleton and tailwind.
* I'm new to skeleton and tailwind. Maybe this is user error.  
* This is the only component I've tried that doesn't work for me so far...

```shell
/workspace # npm list --depth=0
my-skeleton-app@0.0.1 /workspace
├── @skeletonlabs/skeleton@1.2.5
├── @sveltejs/adapter-auto@2.0.1
├── @sveltejs/kit@1.16.0
├── @tailwindcss/forms@0.5.3
├── @tailwindcss/line-clamp@0.4.4
├── @tailwindcss/typography@0.5.9
├── @typescript-eslint/eslint-plugin@5.59.2
├── @typescript-eslint/parser@5.59.2
├── autoprefixer@10.4.14
├── eslint-plugin-svelte3@4.0.0
├── eslint@8.39.0
├── moment@2.29.4
├── postcss@8.4.23
├── svelte-check@3.3.0
├── svelte@3.58.0
├── tailwindcss@3.3.2
├── tslib@2.5.0
├── typescript@5.0.4
└── vite@4.3.4
```

tailwind.config.cjs
```js
const plugin = require('tailwindcss/plugin');

/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: 'class',
	content: ['./src/**/*.{html,js,svelte,ts}', require('path').join(require.resolve('@skeletonlabs/skeleton'), '../**/*.{html,js,svelte,ts}')],
	theme: {
		extend: {},
		minWidth: {
			'metrics': '140px',
		},
	},
	plugins: [
		require('@tailwindcss/forms'),
		require('@tailwindcss/typography'),
		...require('@skeletonlabs/skeleton/tailwind/skeleton.cjs')(),
	],
}
```

**Comment by endigo9740** [comment]
Hey @calmdev I see your error in the Tailwind config - don't worry this trips up a lot of fucks. It's one of those situations where they give you "just enough rope to hang yourself". But in the config you have `theme.extend` and `theme.minWidth`. If you place anything directly under theme (not within `extend`) you're basically telling Tailwind to nuke all the defaults it provides and replace them with only the values you specify.

In this case you're use of `theme.minWidth` is nuking all the min-width defaults!
https://tailwindcss.com/docs/min-width

Move that up into the theme object and you should be good to go!

**Comment by calmdev** [comment]
Thank you! That helped me and it works perfectly now.
