### ISSUE TITLE
Types not being found

### ISSUE THREAD

**Issue by aunumever** [skeletonlabs/skeleton#1445]
### Current Behavior

Cannot find type modules after basic initial installation. VSCode shows squiggly lines under `.$types`

Error: Cannot find module './$types' or its corresponding type declarations.

### Reproduction / Steps To Reproduce

This error does not happen using:
`npm create svelte@latest my-app`

Brand new install using skeleton caused issue:
`npm create skeleton-app@latest my-skeleton-app`

Add basic route file:
```
<script lang="ts">
	import type { PageData } from './$types';

	export let data: PageData;
</script>
```

Error: Cannot find module './$types' or its corresponding type declarations.

### Anything else?

I have tested this in a couple different installs, and they are all the same, posted to Svelte Discord with no suggestions.

**Comment by aunumever** [comment]
I didn't `npm install` and then start my server. Starting the server after an npm install cleared out the errors.

**Comment by endigo9740** [comment]
@aunumever this one bit me yesterday as well, running the server will solve it! Thanks for sharing the solution to help others!
