### ISSUE TITLE
Tab classes - fractional width issue (e.g. w-1/2)

### ISSUE THREAD

**Issue by fatstack** [skeletonlabs/skeleton#1446]
### Current Behavior

I was having issues with Tailwind fractional width classes not behaving as expected on Tabs. Such as w-1/2. If I set a standard value (e.g. w-48), the width class works as expected.

Using version 1.2.5. The styling was working as expected in earlier versions (1.1.0 or earlier), but broke for me in one of the updates - I haven't had a chance to look into fixing it until now.

The tab group is full screen width (for mobile). Changing the tab class fractional width does affect the size of the tab (e.g. w-1/12 or w-11/12, but it seems to be a fraction of what the default tab width would be.

I've found a work around by putting a div around the tabs and setting the fractional width there. But figured I'd report this here in case this behavior is not intentional. Screenshots using the tabs example from the Skeleton docs (https://www.skeleton.dev/components/tabs) attached.

Thank you.

### Reproduction / Steps To Reproduce

<img width="1978" alt="screenshot1" src="https://user-images.githubusercontent.com/40495144/236632995-773ced08-b070-4964-ab89-d92c6e56b434.png">
<img width="1905" alt="screenshot2" src="https://user-images.githubusercontent.com/40495144/236633000-6039d5c6-e4e8-4d00-97de-8577543825a7.png">

**Comment by endigo9740** [comment]
Thanks for the heads up @fatstack. I haven't personally used fractional sizes much in Tailwind yet, but we'll definitely give this a look!

**Comment by Mahmoud-zino** [comment]
can I work on this issue? I think i know what's causing it

**Comment by endigo9740** [comment]
Go for it @Mahmoud-zino, I'll assign it to you now. Thanks!
