### ISSUE TITLE
Some popups stop working during dev mode when content has been changed

### ISSUE THREAD

**Issue by saturnonearth** [skeletonlabs/skeleton#1466]
### Current Behavior

Odd behavior that I believe was happening before 1.5, where some popups stop working when in dev mode, after any files are edited, and Vite automatically changes the content.

I am not quite sure how to replicate this as some of my popups continue to work. Putting this here in case anyone else experiences this.

### Reproduction / Steps To Reproduce

1. Have popup
2. Edit svelte file in dev mode
3. Try to click popup trigger
4. ...
5. opposite of profit?

**Comment by endigo9740** [comment]
@saturnonearth I've seen similar behavior for other components. No clue how to resolve it unfortunately. Happy to leave this open for a bit to field other suggestions though. A hard refresh is typically the only viable fix I've stumbled upon.

**Comment by endigo9740** [comment]
Unfortunately I'm thinking this may be an issue that has to be taken upstream. If you (or anyone reading this) find a solution let me know.
