### ISSUE TITLE
Popup error since update. Caught TypeError: callback is not a function.

### ISSUE THREAD

**Issue by DelcoTrailersDev** [skeletonlabs/skeleton#1477]
### Current Behavior

Whenever I hover over my popup I am getting the following error in my console.

![image](https://github.com/skeletonlabs/skeleton/assets/123404286/b0c41fd2-1ffc-4452-bfb8-e5f145f54dfb)

### Reproduction / Steps To Reproduce

Simply hover over icon and error occurs in console of browser.

**Comment by endigo9740** [comment]
Duplicate of: https://github.com/skeletonlabs/skeleton/issues/1475

**Comment by DelcoTrailersDev** [comment]
@endigo9740 Hey man, this is ArcAstronaut. Can you do me a favor delete this by chance? I did not want to use this github account.
