### ISSUE TITLE
input divider issues when input class is used insider input-group

### ISSUE THREAD

**Issue by sachinbhutani** [skeletonlabs/skeleton#1481]
### Current Behavior

Check this recording for the two input group code blocks below 
https://github.com/skeletonlabs/skeleton/assets/6120010/29a0c3c4-cdf3-430c-9d38-cd353b3685b4

- first fiekd in the recording 
when <input class=input"... is used inside an input group the divider does not show correctly. 

-  second field in the recording. 
if input-group-divider is class is removed from the group div, a blue divider appears when input box is in focus 

### Reproduction / Steps To Reproduce

```html
<label class="label">
	<span>Namespace:</span><i class="fa-solid fa-asterisk text-error-500" />
	<div class="input-group input-group-divider grid-cols-[auto_1fr]">
		<div class="input-group-shim"><i class="fa-solid fa-clone" /></div>
		<input class="input" type="text" placeholder="Namespace" required />
	</div>
</label>
<label class="label">
	<span>Database:</span><i class="fa-solid fa-asterisk text-error-500" />
	<div class="input-group grid-cols-[auto_1fr]">
		<div class="input-group-shim"><i class="fa-solid fa-database" /></div>
		<input type="text" placeholder="Database" required />
	</div>
</label>
```

### Anything else?

workaround: 
- keep the input-group-divider class and remove class="input" from input tag.

**Comment by endigo9740** [comment]
@sachinbhutani So there's two issues here:

1. You've implemented `.input` for the input within the Namespace `.input-group`. This should not be present. Here's the corrected markup:

```html
<label class="label">
	<span>Namespace:</span><i class="fa-solid fa-asterisk text-error-500" />
	<div class="input-group input-group-divider grid-cols-[auto_1fr]">
		<div class="input-group-shim"><i class="fa-solid fa-clone" /></div>
		<!-- REMOVED class="input" -->
		<input type="text" placeholder="Namespace" required />
	</div>
</label>
```

The second issue was the blue ring style applying to inputs within input groups that do not implement `.input-group-divider`, such as your Database field. For this I've implemented a small change to the default styling on our side that should resolve this. This will go live with tomorrow's release.
