### ISSUE TITLE
Data Table Filter

### ISSUE THREAD

**Issue by smattera** [skeletonlabs/skeleton#1483]
Is there a way to filter the table rows like with TanStack Tables?

**Comment by Sarenor** [comment]
Data Tables are currently not actively supported.
There's a post that points you to some well maintained alternatives like [datatables](https://github.com/vincjo/datatables)

**Comment by endigo9740** [comment]
We're referring all data table discussion here: https://github.com/skeletonlabs/skeleton/issues/538
