### ISSUE TITLE
Bind ListBoxItem to object

### ISSUE THREAD

**Issue by geshl** [skeletonlabs/skeleton#1485]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I got into the following scenario. I wanted to bind `ListBoxItem` to object value extracted from the localStorage. It worked good at first look, but on page refresh it doesn't mark as active the last selected list item (the object value from the localStorage).

Object binding to  `ListBoxItem` might be a good in specific cases.

### Minimal example

```html
<script>
	import { ListBox, ListBoxItem } from '@skeletonlabs/skeleton';
	import { writable } from 'svelte/store';
	import { browser } from '$app/environment';

	// Store init
	const data = browser && JSON.parse(window.localStorage.getItem('test') || '{ "value": "" }');

	export const testStore = writable(data);

	testStore.subscribe((value) => {
		if (browser) {
			localStorage.setItem('test', JSON.stringify(value));
		}
	});

	// List of objects
	let listValues = [{ value: 'Books' }, { value: 'Movies' }, { value: 'TV' }];
</script>

<ListBox>
	{#each listValues as item}
		<ListBoxItem name="medium" value={item} bind:group={$testStore}>{item.value}</ListBoxItem>
	{/each}
</ListBox>
```

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

- https://dmitripavlutin.com/how-to-compare-objects-in-javascript
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is

**Comment by endigo9740** [comment]
It's mentioned in the thread above, but I want to emphasize that the fix will likely involve implementing the `Object.is()` syntax for object comparison per:
https://dmitripavlutin.com/how-to-compare-objects-in-javascript/

**Comment by Mahmoud-zino** [comment]
@endigo9740 just tested the `Object.is()` option and it is not working because it will compare the objects by reference.

I want to build a simple deep comparison function that compares any type of prop (not only objects but also numbers and strings etc...) does it sound good?
