### ISSUE TITLE
Modal: Disable backdrop click

### ISSUE THREAD

**Issue by boomfly** [skeletonlabs/skeleton#1488]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Is there a way to disable closing modal on backdrop click?

### What type of pull request would this be?

None

**Comment by Sarenor** [comment]
No:
https://www.skeleton.dev/utilities/modals#accessibility

**Comment by matthme** [comment]
I don't see how this feature would be disallowed by the accessibility guidelines you are pointing to. They state
> and in some implementations, attempts to interact with the inert content cause the dialog to close
Note how they write "in *some* implementations".
There are cases where pressing a button in a modal triggers actions that take a while to complete and closing the dialog during that time would mess up with the application state so disabling close on side-click would be disabled for all users during that limited amount of time. How else should such a case be handled?

**Comment by Sarenor** [comment]
By building your own Modal or using a dedicated page because _some implementations_ include ours.

You might have more luck in [v3](https://github.com/skeletonlabs/skeleton/issues/2357), but for v2 the stance is set and won't change to not break backwards compatibility and expectations: Backdrop Clicks will close the modal.

**Comment by polaroidkidd** [comment]
I keep on coming back to this pain-point. If you have a authenticate/register form implemented in a modal, hit "submit" and the click else where by accident, there is no way to inform the user that a request is pending. The modal simply closes.

Short of patching v2, could you recommend another way of handling this case or would you suggest to use another modal library all together?

**Comment by Sarenor** [comment]
> By building your own Modal* or using a dedicated page because some implementations include ours.

> You might have more luck in https://github.com/skeletonlabs/skeleton/issues/2357, but for v2 the stance is set and won't change to not break backwards compatibility and expectations: Backdrop Clicks will close the modal.

I'm sorry but I'll just bluntly copy my message above as an answer @polaroidkidd .

*You can of course copy the v2 Modal and edit it as you like for this step.

**Comment by polaroidkidd** [comment]
> I'm sorry [...]

all good, no hard feelings. :+1:. 

I wasn't sure if I was missing something or if that would have been the best way forward. Thanks for the quick reply.
