### ISSUE TITLE
Icon buttons do not animate on click

### ISSUE THREAD

**Issue by leElvyn** [skeletonlabs/skeleton#1492]
### Current Behavior

check at : https://www.skeleton.dev/elements/buttons

Icon buttons do not animate on click why text buttons do

### Reproduction / Steps To Reproduce

Create a div with the .btn-icon class, and try to click it

### Anything else?

text buttons animate correctly on click

**Comment by Mahmoud-zino** [comment]
@endigo9740 I can solve this quickly if it is ok?
