### ISSUE TITLE
Typescript import should be made with the .js extension

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#1501]
### Current Behavior

So it seems that without the extension it is fine for CJS, but not for ESM: https://www.typescriptlang.org/docs/handbook/esm-node.html#type-in-packagejson-and-new-extensions

But leaving off the .js extension is also causing some issues for some other people trying to get things to work in web pack.

It might be in our best interests to default to using .js on all appropriate imports by default to ensure the widest compatibility with environments we might not even be aware of.

@Firelight on discord pointed to this package that looks like it could do a global replace of those imports as a one off for us.

Clearly I would like to test this out more before giving a final opinion.
https://www.npmjs.com/package/ts-transform-esm-import

**Comment by AdrianGonz97** [comment]
We should add `"moduleResolution": "NodeNext"` in our `tsconfig.json` to help us catch this error. 

This is specified here in the SvelteKit docs: https://kit.svelte.dev/docs/packaging#caveats

**Comment by endigo9740** [comment]
Let's discuss if we -want- to support Webpack before we implement a sweeping change like this. Please :)

**Comment by niktek** [comment]
So that transform package only works on builds and doesn't transform source files.

The moduleResolution definitely helps to highlight errors and even index.ts shows up as broken for things like the Modal types and actions that must have been refactored at one point and no longer exist in a single file.  Which also goes to illustrate that a source file mass transform is probably not going to be a silver bullet solution.

Another issue that is coming up is the changes to importing from @skeletonlabs/skeleton in the Skeleton lib in the mono repo now shows as an error - but I want to wait till we have experimented with a few more Vite alias options before deciding to change them to relative path imports (I think there is also a way to do aliases in the tsconfig.json that might also work around this)

**Comment by niktek** [comment]
Just adding a note: packages/skeleton cannot import components from the `/src/index.ts` and must do a full relative path import instead to prevent errors.  Example https://github.com/skeletonlabs/skeleton/pull/1547
