### ISSUE TITLE
Popup is flickering when hovering children

### ISSUE THREAD

**Issue by sssuneeth** [skeletonlabs/skeleton#1509]
### Current Behavior

Hey there :)
I tried this tip https://www.skeleton.dev/utilities/popups#hover , but its not working as expected.

My popup is opening and closing when hovering children and also issue with hovering a trigger from one trigger element ( popup closes )
I raised similar issue before

Now using v1.5.1, it fixed some of my popup issues :)

### Reproduction / Steps To Reproduce

Current popup settings:
https://github.com/sssuneeth/CoreProject-V3-UI/blob/9ec2b20aa03b1ae411470c2f290d43b4373214da/src/routes/%2Bpage.svelte#L133-L152

Popup element:
https://github.com/sssuneeth/CoreProject-V3-UI/blob/9ec2b20aa03b1ae411470c2f290d43b4373214da/src/routes/%2Bpage.svelte#L559-L664

### Anything else?

Sorry, atm I cant provide screen rec. so please check this section instead :)

![Screenshot from 2023-05-16 15-54-02](https://github.com/skeletonlabs/skeleton/assets/114811070/5980a56a-4c4c-4f4f-9247-62c180d5bff4)

in this site: https://v3.coreproject.moe/

**Comment by Sarenor** [comment]
I've already spent far to much time analysing this while I should be working because I'm curious myself and I don't get it.
I added my own mouseenter & leave listeners to the use:popup divs:
```html
<div
                                on:mouseenter={() => {
                                    anime_name = anime.name;
                                    anime_cover = anime.cover;
                                    anime_synopsis = anime.synopsis;
                                    anime_current_episode = String(anime.current_episode);
                                    anime_episodes_count = String(anime.episodes_count);
                                    anime_genres = anime.genres;
                                    anime_type = anime.type;
                                    anime_release_date = String(anime.release_date);
                                    anime_studio_name = String(anime.studios[0]);
                                }}
                                class="group"
								on:mouseleave={(event) => {console.log("mouseleave",event.target)}}
								on:mouseenter={(event) => {console.log("mouseenter",event.target)}}
                                use:popup={mylistPopupSettings("my_list_popup" + i)}
                            >
```
And added a console.log() in my local popup.js files.
I'd expect both of them to fire at the same time, but instead I get very weird behaviour:
<img width="226" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/31982384/bf326410-774b-4ec2-86fb-385302d249d4">
Where it closes the popup 3 times already even though not a single mouseleave was fired.
Tbh, I'm pretty much stumped.

**Comment by sssuneeth** [comment]
@Sarenor 
> Your data-popup-ids still need to be unique:

Yea I added unique ids now, check this
https://github.com/sssuneeth/CoreProject-V3-UI/blob/547eb9c70188254477d4638d475eae613bd4d3bb/src/routes/%2Bpage.svelte#L145-L153

> I've already spent far to much time analysing this while I should be working because I'm curious myself and I don't get it.

Its because, when I do like this
```svelte
{#each animes as anime}
      <!-- in popup -->
      <div class="popup>
            {anime.name}
      </div>
{/each}
```
I gets the value of 1st element of the each loop only
so we used that way to update values on every mouseenter, hope you get it

> Where it closes the popup 3 times already even though not a single mouseleave was fired.

Actually, Idk either

These links may help
( changes I made )
https://github.com/sssuneeth/CoreProject-V3-UI/pull/154/files
( preview with latest changes )
https://core-project-v3-ui-git-popup-fix-suneethsunx.vercel.app/

**Comment by sssuneeth** [comment]
> I added my own mouseenter & leave listeners to the use:popup divs:

I added these codes
```js
                                on:mouseenter={() => {
                                    hovered_anime_id = anime.id;
                                    console.log(hovered_anime_id, anime.id);
                                    console.log("Mouse entered", event);
                                }}
                                on:mouseleave={(event) => {
                                    console.log("Mouse leaved", event);
                                }}
```

But for me it showing output as expected

![Screenshot from 2023-05-16 18-24-48](https://github.com/skeletonlabs/skeleton/assets/114811070/fce5c903-5c4f-423b-ba7b-385e0da7a93a)

And I got a another kind of error

**Comment by Sarenor** [comment]
The callback one should already be fixed in the next releas if I remember right.
Also strange that it works differently for you, I might just have to clone down the project cleanly again.

Will do so when I find the time after work 👍

**Comment by sssuneeth** [comment]
> Also strange that it works differently for you, I might just have to clone down the project cleanly again.
Will do so when I find the time after work +1

Yea thanks for that, We've been facing this issue for a while
Take your time :+1:

**Comment by Hugos68** [comment]
I've made [a simplified repro](https://stackblitz.com/edit/skeletonlabs-repl-4kfogk?file=src%2Froutes%2F%2Blayout.svelte,src%2Froutes%2F%2Bpage.svelte) for others to test on since it's not very pleasant to work on such a big codebase.

**Comment by endigo9740** [comment]
Typically with hover events you have to be careful with the children within the element. Features like buttons are their own block elements and mousing over these can act as if you hovered off the element - because technically you have. There's no even in JS that allows for "when entering/existing the boundaries of an element".

To work around these we've made a suggestion in the Hover event documention:

> TIP: apply [&>*]:pointer-events-none to your trigger element, to prevent child elements (ex: icons) from breaking the hover state and closing the popup early.

![Screenshot 2023-05-16 at 10 36 22 AM](https://github.com/skeletonlabs/skeleton/assets/1509726/602fee3c-3157-4971-b260-11023c40f260)

Please set the inner children elements within your button to have the pointer events disable. When you do this the mouse events will cover the entire button space so the hover effect works as desired.

**Comment by baseplate-admin** [comment]
> Typically with hover events you have to be careful with the children within the element. Features like inner buttons or text within buttons are their own block elements and mousing over these can act as if you hovered off the target element - because technically you have. There's no event in JS that allows for "when entering/existing the boundaries of an element".

Hi forgive me but I think this could be fixed somehow.

>  There's no event in JS that allows for "when entering/existing the boundaries of an element".

Tippy.js have figured it out.( maybe we can take some inspiration from them?? ) ( I didn't do a deep dive into it but [this](https://github.com/atomiks/tippyjs/blob/ad85f6feb79cf6c5853c43bf1b2a50c4fa98e7a1/src/createTippy.ts#L127-L166) seems like the code to create popups ) 

---

If you take another look into it, i would be really grateful.

Thanks.

**Comment by endigo9740** [comment]
They're likely just disabling the pointer event for children for you. However, this may not always be the preferred behavior, so right now we leave it in the user's hands.

We just underwent a major popup update that took nearly a week. I think at this point I've done everything I can for popups for a bit. We have the whole rest of the library to maintain. If you would like to review the code and contribute a change though, we would welcome it. Thanks
