### ISSUE TITLE
Popup with event hover error

### ISSUE THREAD

**Issue by KarolusD** [skeletonlabs/skeleton#1512]
### Current Behavior

![image](https://github.com/skeletonlabs/skeleton/assets/35146988/cc7dd1e0-fb2f-4ffe-b830-20c3fc8bd404)

As you can see popup hover has an error `callback is not a function` in this chunk of code:
![image](https://github.com/skeletonlabs/skeleton/assets/35146988/6b86aad8-2803-435e-a34f-712089916499)

---
**NOTE**
I also noticed that if you have multiple elements with applied popup on hover next to each other hover popup tends to disappear really fast.
---

### Reproduction / Steps To Reproduce

Open console in Skeleton docs and see what is happening when you hover multiple times here:
https://www.skeleton.dev/utilities/popups#hover

**Comment by KarolusD** [comment]
**Ad. Note**: seems like opening new popup also triggers closing functionality and the results is that both popups are closed immediately. This appears to be true also on other popup events like click.

**Comment by endigo9740** [comment]
Per your original post above - this has already been addressed and a fix will be part of the next release dropping next week:
- https://github.com/skeletonlabs/skeleton/pull/1479

> I also noticed that if you have multiple elements with applied popup on hover next to each other hover popup tends to disappear really fast.

If you're using hover, the popup will only remain visible while hovering the target element (ex: a button). Does your trigger element perhaps have child items, like icons? If so see the tip here. I've moved text to be more readily visible in the docs in the next release:

![Screenshot 2023-05-16 at 1 46 49 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/2bed893c-fda9-4cab-b201-a694cc6581cd)

> Ad. Note: seems like opening new popup also triggers closing functionality and the results is that both popups are closed immediately. This appears to be true also on other popup events like click.

The close method should always be localized to the trigger/popup and should never effect other popups. Actions can't communicate with one another like that. Can you explain on your use case here or provide a code sample?

**Comment by KarolusD** [comment]
Great! Skeleton is rocking ;) When it comes to my related issue (**note**) it happens to be issue only with my code, when looping through multiple popups you have to take care about different targets names, otherwise it will try to fire up the same popup and it will result in some unexpected behaviour. Thank you for quick response @endigo9740 , I am closing the issue.

**Comment by endigo9740** [comment]
Ahh yeah, loops keep tripping folks up. Just FYI we have some plans for the popups in the future that should improve this process. We're still working out the details, but keep an eye out for future releases.

Give it sounds like your issues are resolved I'll go ahead and close this out though.
