### ISSUE TITLE
Error while pressing tab on input with popup

### ISSUE THREAD

**Issue by eslym** [skeletonlabs/skeleton#1513]
### Current Behavior

pressing tab on input with popup is not working
![image](https://github.com/skeletonlabs/skeleton/assets/3667594/07168edb-429d-484f-858e-90eb733f8ee5)

### Reproduction / Steps To Reproduce

```svelte
<input use:popup{{...}}/>
```
then press tab

### Anything else?
i am sure this line is a mistake, `focusableAllowedList` is a constant string how does it ensure `focusablePoupupElements` is having something?
https://github.com/skeletonlabs/skeleton/blob/c0e42a296cdf7944c5439a53d0d191daa9f06bee/src/lib/utilities/Popup/popup.ts#L170
and the previous line `event.preventDefault()` also prevent the focus moving to next input even there is no focusable element in popup

**Comment by Sarenor** [comment]
You're right, that piece of code might be better as
`` ts
const triggerMenuFocused: boolean = popupState.open && document.activeElement === triggerNode;
if (triggerMenuFocused && (key === 'ArrowDown' || key === 'Tab')) {
  if (focusableAllowedList.length > 0 && focusablePopupElements.length > 0) {
   event.preventDefault();
   focusablePopupElements[0].focus();
 }
}
```
Do you want to open a PR for this or should I do it?

**Comment by eslym** [comment]
@Sarenor please do it, thank you
