### ISSUE TITLE
Auto detect language in codeblocks

### ISSUE THREAD

**Issue by TheHamkerCat** [skeletonlabs/skeleton#1516]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Can we have a feature to use `hljs.highlightAuto()` of highlight.js with `<CodeBlock/>` to auto-detect language?

**Something like [this](https://github.com/highlightjs/highlight.js#using-with-vuejs)**

This would be really helpful when we're unsure about the language, especially when working with LLMs.

Currently we use this syntax: 
```html
<CodeBlock language="ts" code={`const skeleton: string = 'awesome';`}></CodeBlock>
```

How about?

```html
<CodeBlock autodetect={true} code={`const skeleton: string = 'awesome';`}></CodeBlock>
```

I know this will dramatically increase bundle size, but maybe we can explicitly specify a list of languages we want support for when initializing.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

https://github.com/highlightjs/highlight.js#using-with-vuejs
https://github.com/highlightjs/highlight.js#nodejs-on-the-server

**Comment by TheHamkerCat** [comment]
https://github.com/skeletonlabs/skeleton/blob/52fc1d19b6f6f445bafa420f65ac3c3034caec03/src/lib/utilities/CodeBlock/CodeBlock.svelte#L70

Replacing `highlight()` with `highlightAuto()` and removing the language parameter works here temporarily, i'll use it until this feature is added

**Comment by endigo9740** [comment]
This is a bit at odds with: https://github.com/skeletonlabs/skeleton/issues/1381

But FYI we're in the process of some major structural changes to the Skeleton project - which includes migrating to a monorepo. When this is complete, the code blocks are one of a handful of features we're looking to spin off as standalone packages. When this occurs we'll revisit a lot of the feature set and capabilities provided.

This could include potentially switching to something like Prism.js in favor of Highlight.js. So just FYI there are some prerequisites before we move forward with improvements to the existing code blocks.

If you need a short term fix, consider cloning the component to your local project, and modifying the functionality locally. It won't receive upstream updates obviously, but it'll operate as you see fit.

**Comment by TheHamkerCat** [comment]
> If you need a short term fix, consider cloning the component to your local project

Thanks, i'll do this!

> You can find the source here: https://github.com/skeletonlabs/skeleton/tree/dev/src/lib/utilities/CodeBlock


Did you mean https://github.com/skeletonlabs/skeleton/tree/dev/packages/skeleton/src/lib/utilities/CodeBlock

**Comment by endigo9740** [comment]
@TheHamkerCat we literally just pushed the monorepo change so that path just updated accordingly. But yes that's the new corrected path, thanks!

**Comment by endigo9740** [comment]
Note that this will be considered as part of the transition to the Code Block becoming a standalone package.

**Comment by endigo9740** [comment]
> [!WARNING] 
> This issue is a work in progress.

This will act as a hub to centralize this information.

## Framework Status

* Svelte 5: Incomplete
* React: Incomplete

## Maintainer Requests

The following requests are coming straight from the Skeleton team. These are highly likely be implemented:

* (expect this to expand over time)

## Community Requests

The following requests have come from the community and are under consideration:
 
* n/a

## Bugs and Issues

* n/a

## Feedback

If you have additional updates or requests for this feature, please do so in the comments section below.
