### ISSUE TITLE
[Stepper]: Add "eager" possibility

### ISSUE THREAD

**Issue by simpros** [skeletonlabs/skeleton#1521]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Hi,

I just saw that the stepper is currently only adding the active Step to the DOM, which is kind of bad if you use it with forms, as the Form will only submit visible DOM-elements.

I would love to see the possibility to either "eager" load the steps which would add all to the dom and keep them there, or to do it "lazily" as the current solution does it.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

[Angular Material has something like that](https://material.angular.io/components/stepper/overview#lazy-rendering)

**Comment by endigo9740** [comment]
I've been considering something like this, definitely something we're interested in. Thanks for the suggestion.

**Comment by Mahmoud-zino** [comment]
I am thinking to make the steps hidden with CSS instead of hiding them using svelte-if if an ("eager") prop was set so that the form will still submit the values, and when the prop is not set it will behave like it did before.
If this sounds like a good solution, I would like to take this issue.

**Comment by endigo9740** [comment]
@Mahmoud-zino leave this one to me, I need to investigate how we go about this as it might affect other components in the future.
