### ISSUE TITLE
Allow `size` to be updated dynamically for `Paginator`

### ISSUE THREAD

**Issue by ollema** [skeletonlabs/skeleton#1527]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Hi!

I am using the `Paginator` component and it works great but I have one feature request.

In my page, I have:

```svelte
<script lang="ts>
  ...
  
  let search = '';
  
  $: filteredSource = source.filter((element) =>
    element.name.toLowerCase().includes(search.toLowerCase())
  );
  
  let page = {
    offset: 0,
    limit: 10,
    size: source.length,
    amounts: [10, 50, 100]
  };
<script>

<input class="input" type="search" bind:value={search}/>
...

<Paginator bind:settings={page} />
```

As you can see, I have implemented filters that change the number of available elements.

It would be great if it was possible to have the `size` property adapt to this change. Some of my users want to use the filters to figure out how many of source that meets this condition.

Setting it to something like `filteredSource.length` does not work right now.

Let me know if you would like further clarifications!

Thanks!

### What type of pull request would this be?

Enhancement

**Comment by ollema** [comment]
Two minutes after posting this feature request I wondered if making `page` a reactive statement would work and sure enough 🤦‍♂️ now it works!

For anyone else that has the same problem/question:
```svelte
	$: page = {
		offset: 0,
		limit: 10,
		size: filteredSource.length,
		amounts: [10, 50, 100]
	};
```

**Comment by ollema** [comment]
Actually, this did not work either. Now I can't choose how many items to display!

Is it possible to update `size` dynamically, or is this something that needs to be fixed/implemented?

**Comment by Sarenor** [comment]
If you're on Discord, we've had a similar support request there, recently and they got it working.
So I think there's something that's not quite working with your reactive declarations.

You can check it out here:
https://discord.com/channels/1003691521280856084/1108477321406582845/1108477321406582845

**Comment by AdrianGonz97** [comment]
@ollema As as @Sarenor stated and in the discussion that was linked, we just need to make `page.size` reactive like so:

```html
<script lang="ts">  
  let search = '';
  
  $: filteredSource = source.filter((element) => 
    element.name.toLowerCase().includes(search.toLowerCase())
  );

  // this line needs to be added so that page.size will update whenever filteredSource is mutated
  $: page.size = filteredSource.length
  
  let page = {
    offset: 0,
    limit: 10,
    size: source.length,
    amounts: [10, 50, 100]
  };
</script>
```

**Comment by ollema** [comment]
Aha, thanks a lot! I'll have to be honest, sometimes I get confused by these reactive statements. I tried something very similar, like:

```svelte
<script lang="ts">  
  let search = '';
  
  $: filteredSource = source.filter((element) => 
    element.name.toLowerCase().includes(search.toLowerCase())
  );

  // this line needs to be added so that page.size will update whenever filteredSource is mutated
  $: pageSize = filteredSource.length
  
  let page = {
    offset: 0,
    limit: 10,
    size: pageSize,
    amounts: [10, 50, 100]
  };
</script>
```
and that did not work at all.

But thanks a lot for the help!
