### ISSUE TITLE
Mesh background repeats itself

### ISSUE THREAD

**Issue by tizu69** [skeletonlabs/skeleton#1528]
### Current Behavior

When scrolling on a page, the background repeats itself because it isn't set to not do so.

### Reproduction / Steps To Reproduce

Simply create a page larger than 100vh without using any outside components.

```html
<div class='h-[150vh]' />
```

### Anything else?

![9feiwkw](https://github.com/skeletonlabs/skeleton/assets/60812901/3d5001fa-c867-462c-a92d-6daac3be3206)

**Comment by endigo9740** [comment]
Noting this here - we just need to set a background position and attachment style to resolve this. This will be defined in the optional mesh setting per each theme.

**Comment by endigo9740** [comment]
FYI I'm implementing the following to all themes that implement optional mesh backgrounds:

```
background-attachment: fixed;
background-position: center;
background-repeat: no-repeat;
background-size: cover;
```

This includes the following themes

- Gold Nouveau
- Modern
- Rocket
- Sahara
- Seafoam
- Skeleton
- Vintage

The idea here is that the background image will attempt to cover the entire visible space, be centered, will not repeat, and will be "fixed", which means it remains in place when you scroll up and down.

This will have no notable impact on users implementing the App Shell, but when implementing a custom layout I do suggest adding the following to your global stylesheet `/src/app.postcss`:

```css
html, body { @apply h-full; }
```

This will ensure the HTML and BODY tags always fill the canvas height a minimum.

I've updated the documentation in the Docs > Themes section to cover everything above.
