### ISSUE TITLE
Popups/Combobox example does not work in Safari

### ISSUE THREAD

**Issue by Shackless** [skeletonlabs/skeleton#1534]
### Current Behavior

The [docs example](https://www.skeleton.dev/utilities/popups#combobox) for a Combobox built by combining a Button, Popup, and ListBox does not work in Safari.

### Reproduction / Steps To Reproduce

Open the docs page in Safari and try to open the Combobox.

**Comment by endigo9740** [comment]
I've been able to replicate this. No errors are present in the console. We'll have to investigate a bit further.

**Comment by endigo9740** [comment]
@Shackless there seems to be some issue with the `focus-click` event when used on buttons in Safari. As a temporary fix I've changed the combobox popup to use the `click` event instead, which works universally.

**Comment by Shackless** [comment]
Great, thanks for the quick workaround!
