### ISSUE TITLE
pagination controls

### ISSUE THREAD

**Issue by Mahmoud-zino** [skeletonlabs/skeleton#1536]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

we need a pagination control (row of page numbers with `...` to limit horizontal space) to navigate easily between pages.
something like this:

![239981714-7839aa1b-20e7-412f-9c92-2d33ca2d92af](https://github.com/skeletonlabs/skeleton/assets/74062808/79c7a7d6-a94e-4f79-93e4-04509e0bd5db)

Mock-up and notes from @endigo9740 
![Screenshot_2023-05-22_at_1 06 35_PM](https://github.com/skeletonlabs/skeleton/assets/74062808/25a682dc-c41a-48d3-a773-e5db8d5f4753)

> Seems very busy on the right, so we'll probably want to make sure those are small buttons.

> We'll also need to track and active state for which button is currently selected. This should be prop class.

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

https://mantine.dev/core/pagination/
The animations here could be a nice addition also: https://nextui.org/docs/components/pagination

**Comment by endigo9740** [comment]
The use of a button group is advised here to help keep things simple:
https://www.skeleton.dev/elements/buttons#button-groups

**Comment by MLNW** [comment]
> The use of a button group is advised here to help keep things simple: https://www.skeleton.dev/elements/buttons#button-groups

Do you mean this is something users should implement themselves when ever they need it or that an eventual implementation in Skeleton should use button groups?
