### ISSUE TITLE
Broken "Menu" link in Sidebar Drawer tutorial

### ISSUE THREAD

**Issue by Wobbley** [skeletonlabs/skeleton#1542]
### Link to the Page

https://www.skeleton.dev/blog/how-to-implement-a-responsive-sidebar-drawer

### Describe the Issue

When talking about alternative UX considerations it links to a broken Menu component: https://www.skeleton.dev/utilities/menus?ref=skeleton.ghost.io

### Are you able to create a Pull Request with the fix?

No

**Comment by endigo9740** [comment]
This has been corrected, thanks @Wobbley
