### ISSUE TITLE
App Rail anchor tile missing the lead slot in example

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1549]
### Link to the Page

https://www.skeleton.dev/components/app-rail#apprailanchor

### Describe the Issue

Issue 1:

```html
<AppRailAnchor href="/" title="Dashboard" selected={$page.url.pathname === '/'}>
    <svelte:fragment slot="lead">(icon)</svelte:fragment>
    <span>(label)</span>
</AppRailAnchor>
```

Issue 2:

The AppRailAnchor lead slot does not center the icon content by default. Temporary fix is:

`regionLead="flex justify-center items-center"`

### Are you able to create a Pull Request with the fix?

Yes

**Comment by endigo9740** [comment]
We also had a request to mirror the `title` attribute to the standard rail tiles as well.

**Comment by Mahmoud-zino** [comment]
I would love to work on this issue.
Also one of the AppRailTile tests is failing so I would like to fix it.

**Comment by endigo9740** [comment]
Assigned! @Mahmoud-zino
