### ISSUE TITLE
New Paginator buttons are not working

### ISSUE THREAD

**Issue by PercivalFigaro** [skeletonlabs/skeleton#1550]
### Current Behavior

Hello!

I tried out the new Paginator buttons for going to first/last page. The `e.detail` I'm getting back from the onPageChange event is not an integer: [https://imgur.com/a/YLeuRIb](https://imgur.com/a/YLeuRIb)

**Comment by Sarenor** [comment]
That might be a bit of an oversight, yeah:
https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/components/Paginator/Paginator.svelte#L61
Should probably round that to the nearest full integer.

**Comment by Mahmoud-zino** [comment]
my bad, I will fix it.
