### ISSUE TITLE
Bug: unicode icons within button icons are not centered properly

### ISSUE THREAD

**Issue by ollema** [skeletonlabs/skeleton#1557]
### Current Behavior

The first/last icons are not centered in the button itself, as can be seen in the following picture:
<img width="329" alt="Screenshot 2023-05-24 at 17 41 18" src="https://github.com/skeletonlabs/skeleton/assets/31876997/3c625e4c-6284-452c-94ad-d9fd8dcb58eb">

This is not a major problem, since the `buttonTextFirst` and `buttonTextLast` props can be set to override this.

However, it could maybe be nice to have a (close to) pixel perfect look out of the box!

Right now, the following HTML-encoded characters are used:
```typescript
/** Set the text label for the Previous button. */
export let buttonTextPrevious: CssClasses = '&larr;';
/** Set the text label for the Next button. */
export let buttonTextNext: CssClasses = '&rarr;';
/** Set the text label for the First button. */
export let buttonTextFirst: CssClasses = '&laquo;';
/** Set the text label for the Last button. */
export let buttonTextLast: CssClasses = '&raquo;';
```

I tried to find better alternatives but without luck. So maybe additional CSS could be needed? Or some SVG embeds? Not sure!

### Reproduction / Steps To Reproduce

Just use the Paginator component with the default values and you should spot the problem.

Tested on Safari and Chrome

**Comment by endigo9740** [comment]
@Mahmoud-zino no rush, but here's the issue discussed on Discord.

FYI the issue is part of the button icon styles, not directly related to the paginator component. I'll update the title accordingly.

**Comment by Mahmoud-zino** [comment]
@endigo9740 ⯬🠨🠪⯮

**Comment by endigo9740** [comment]
@Mahmoud-zino unfortunately same deal as Discord.

![Screenshot 2023-05-26 at 3 03 39 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/af73aa94-e2c3-4446-b336-dcaaf9f4fe3a)

Unicode support is weird like this, there's kind of less popular characters like this that have spotty support on certain combinations of browsers and operating systems. Unfortunately, we have to stick to what's widely available. Even if it hurts our OCD a bit :D

**Comment by Mahmoud-zino** [comment]
@endigo9740 yeah, agree😄.

**Comment by Mahmoud-zino** [comment]
@endigo9740 should I add the symbols as SVGs as we discussed on Discord the other day or do you have something else in mind?

**Comment by endigo9740** [comment]
@Mahmoud-zino I'm leaning towards SVG symbols yes.

Let's go ahead and use Font Awesome's arrows for these, which have an SVG copy button:
https://fontawesome.com/icons/arrow-left?f=classic&s=solid
https://fontawesome.com/icons/arrow-right?f=classic&s=solid
https://fontawesome.com/icons/chevrons-left?f=classic&s=solid
https://fontawesome.com/icons/chevrons-right?f=classic&s=solid

Do one of two things:
1. Insert the SVG code directly inside the script tag as template literals
2. Insert them as template literals in a import `icons.ts` file that's located with the component

This should make it easier to write the template logic to fallback to the user-provided option.
