### ISSUE TITLE
Popup Double Click Problem

### ISSUE THREAD

**Issue by MrVauxs** [skeletonlabs/skeleton#1561]
### Current Behavior

When having multiple buttons for a dropdown, clicking multiple buttons consecutively that cause a popup will create a bug where the popup appears and then is subsequently closed, as if double clicked.

![chrome_ozNOvh1gd5](https://github.com/skeletonlabs/skeleton/assets/32039708/2728de27-84b1-47d4-a754-ab99c04bffc8)

The entire popup system also becomes unresponsive when editing code, requiring a refresh for it to work again.

### Reproduction / Steps To Reproduce

Here is a short copy of the code I was using:

```
<script>
	const popupFeatured = {
		event: 'click',
		target: 'dropdown',
		placement: 'bottom-start'
	};
</script>

<div class="flex flex-row flex-wrap whitespace-normal">
	{#each pages as link}
		{#if !(link.offline || link.type === 'divider')}
			{#if link.pages}
				<button
					class="flex btn btn-sm hover:variant-soft-primary"
					use:popup={popupFeatured}
					on:click={() => (tab = link)}
					id="navbtn"
				>
					<Fa icon={fort[pickRandom(link.icon)]} class="mr-1" />
					{link.label}
				</button>
			{:else}
				<a class="flex btn btn-sm hover:variant-soft-primary" href={link.href}>
					<Fa icon={fort[pickRandom(link.icon)]} class="mr-1" />
					{link.label}
				</a>
			{/if}
		{/if}
	{/each}
</div>

<div class="absolute variant-ghost-primary" data-popup="dropdown">
	{#if tab.pages}
		<div class="flex flex-col backdrop-blur-md p-1">
			{#each tab.pages as link}
				{#if !(link.offline || link.type === 'divider')}
					<Tab
						name={link.label}
						value={link}
						class={selected(link) ? 'variant-filled-primary selected-sub' : ''}
						id="dropdown"
					>
						<a class="flex" href={link.href}>
							<Fa icon={fort[pickRandom(link.icon)]} class="m-1" />
							{link.label}
						</a>
					</Tab>
				{/if}
			{/each}
		</div>
	{/if}
</div>
```

### Anything else?

[Discord Forum Thread](https://discord.com/channels/1003691521280856084/1111117462205907134/1111117462205907134)

**Comment by acdamiani** [comment]
This is because you have multiple buttons targeting the `div` with the `data-popup="dropdown"` attribute. When you click the button on the left to open the popup (with it already open from clicking the button on the right), it will briefly open the popup since you clicked the button, then close since the other button registers a click outside the dropdown's bounding box. Each button should be associated with a unique popup element.

**Comment by endigo9740** [comment]
@MrVauxs building off what @acdamiani said - currently our popups are design to be a 1 to 1 relationship between the trigger element and the popup. When you're using a loop you will need to spawn a unique popup instance per each loop. I detail a bit of this here:

https://github.com/skeletonlabs/skeleton/issues/1323#issuecomment-1533690982

I realize this is not the behavior most folks want, so it's on my agenda to tackle this another way. But movements on popups is paused while we introduce the new monorepo structure detailed in the latest release. The goal will be to split off popups to their own standalone library and extend them with new functionality.

No ETA for that, but just know that's in the works.
