### ISSUE TITLE
`bg-primary-hover-token` on select option only works in lightmode

### ISSUE THREAD

**Issue by MLNW** [skeletonlabs/skeleton#1574]
### Current Behavior

When applying the `bg-primary-hover-token` utility class to a select option, it only produces a visible result in lightmode.

![](https://cdn.discordapp.com/attachments/1025279710609014805/1111682381947076618/image.png)
![](https://cdn.discordapp.com/attachments/1025279710609014805/1111682382177775648/image.png)

### Reproduction / Steps To Reproduce

```html
<select class="select" size="4">
  <option class="bg-primary-hover-token">Foo</option>
  <option class="bg-primary-hover-token">Bar</option>
  <option class="bg-primary-hover-token">Baz</option>
</select>
```

**Comment by Mahmoud-zino** [comment]
yeah, I just checked the dark hover-token is missing. I will add it.

**Comment by endigo9740** [comment]
@Mahmoud-zino we shouldn't need an explicit dark token, that's not how Tailwind's dark mode work. In Tailwind there is no such thing as a light mode - you have a base value, and a dark value. We define the dark value, which should work for either mode. When dark mode is enabled, this just overwrites the base.

We have a base defined for this, but the lack of a dark mode variation should not remove the base.

**Comment by Mahmoud-zino** [comment]
@endigo9740 I think that was a miscommunication on my behalf.
I saw how you handle "the tokens stuff" and followed your pattern by adding this to `backgrounds.cjs`: 
```js
classes[`.dark .bg-${n}-hover-token:hover`] = { 'background-color': `rgb(var(--color-${n}-200) / ${hoverAlpha})` };
```
I then tested it, and it is working. please take a look at the PR when you have time and tell me if I need to change anything.

**Comment by endigo9740** [comment]
The question here is not whether it works, it's: why does this improve things, and why does it not work per the expectations I laid out above.

@AdrianGonz97 would this involve anything you did with the class parsing?

**Comment by AdrianGonz97** [comment]
@endigo9740 I don't think it would be unless the behavior is different in dev than it is when the project built.

**Comment by AdrianGonz97** [comment]
Played around with this a bit and I wanted to note that prefixing the class with a `!` makes it behave correctly. I'm no CSS wizard by any means, but I'm guessing that this is a cascade ordering issue? @endigo9740

**Comment by endigo9740** [comment]
The `!` of courses sets the style to `!important`, so I'm not surprised it works. But it's like taking a hammer to force this. I'm just curious why the base class is suddenly not working in dark mode, but only for this class in particular.
