### ISSUE TITLE
Add Map Serialization to localStorageStore

### ISSUE THREAD

**Issue by MrVauxs** [skeletonlabs/skeleton#1578]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

The current implementation fails to save `Map`s due to how JS stringifies it into JSON (Any Map becomes an empty object `{}`).

The following answer shows how one can do go around this issue:
https://stackoverflow.com/a/28918362/12227966

While I see that I can put a custom serializer in the third `Options` parameter, this is not in the documentation. Whether it is something that is not recommended or due to oversight, I don't know.

Either way, it would be nice to see the default JSON serializer be able to support more types.

### What type of pull request would this be?

Enhancement

**Comment by MrVauxs** [comment]
Note, this is the serializer that ended up working for me:
```js
const serializer = {
		parse: (data) => {
			return new Map(JSON.parse(data));
		},
		stringify: (data) => {
			return JSON.stringify([...data]);
		}
	}
```
I would make a PR if not for the fact I don't know TypeScript...

**Comment by endigo9740** [comment]
@MrVauxs the Local Storage Store is not a Skeleton produced or maintained feature. You can see our attribution at the bottom of the doc page:
https://www.skeleton.dev/utilities/local-storage-stores#attribution

What we do is essentially copy a version of this directly into the library, verbatim from the upstream source. If you would like changes to the source, you need to contribute that upstream here:
https://github.com/joshnuss/svelte-local-storage-store

Once accepted and merged, we'll be glad to mirror this on our side. Please notify me if/when this happens. Thanks.

**Comment by endigo9740** [comment]
And yes I know peer dependencies are a thing - but we can't change to that right now because it would require a breaking change. Definitely a consideration for v2 though.

**Comment by MrVauxs** [comment]
https://github.com/joshnuss/svelte-local-storage-store/issues/155
