### ISSUE TITLE
Using tabs for navigation

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#1583]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently to use navigation you have to either surround a tab with ``<a>`` tags or use ``goto()`` both comes with their own problems. The ``<a>`` solution will cause users to firstly tab onto the ``<a>`` and then the ``<div>`` with ``role="tab"``, another problem with this approach is that now the direct children of the tabgroup are not elements with the ``role="tab"`` attribute. The ``goto()`` method is a lot better but still not perfect since ``non-js`` users are now unable to visit certain parts of my website.

A suggested solution is the following, although it is far from fully thought out and sounds honestly a bit too complex for no reason:
Pass in a prop to ``TabGroup`` element called ``navigation`` either set to true or false (false by default) if this navigation property is set the tabs will be ``<a>'s`` instead of ``<div>'s``, the value of the tab's will now be passed into the ``href`` of that tab.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@Hugos68 the App Rail update recently was a test to another approach to this issue - maintaining a separate version of the component that acts purely as an anchor. I have some ideas to refine this a bit, but I think we could apply this here as well. Thanks for the request. I'll use this to try this out soon.

**Comment by Mahmoud-zino** [comment]
I would like to work on this feat.
