### ISSUE TITLE
Slots for Avatar component

### ISSUE THREAD

**Issue by CodingTeaMachine** [skeletonlabs/skeleton#1588]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

It would be nice if I could put custom content into the component, like icons and such, using a default slot in the component.

```HTML
<Avatar>
  <MyIcon />
</Avatar>
```

### What type of pull request would this be?

New Feature

**Comment by endigo9740** [comment]
@CodingTeaMachine an avatar typically has a semantic meaning - it represents the identify of a person.

If the avatar is interactive I might suggest using a button icon instead:
https://www.skeleton.dev/elements/buttons

If it's not, then try a badge icon:
https://www.skeleton.dev/elements/badges

You can see the latter showcased on the list doc page:
https://www.skeleton.dev/elements/lists
https://github.com/skeletonlabs/skeleton/blob/master/sites/skeleton.dev/src/routes/(inner)/elements/lists/+page.svelte

**Comment by CodingTeaMachine** [comment]
@endigo9740 sorry I missed the badge icon section in the docs. That is what I needed.
