### ISSUE TITLE
TableOfContents smooth scrolling poses accessibility issues

### ISSUE THREAD

**Issue by ryceg** [skeletonlabs/skeleton#1589]
### Current Behavior

Currently, the TableOfContents component will always scroll smoothly, regardless of whether the user has indicated that they would prefer reduced motion. 

### Expected Behavior

The behaviour of the scrolling should be exposed, and provided with a sane default of scrolling instantly if the `$prefersReducedMotion` store (introduced in #1533) is `true`. 

### Steps To Reproduce

1. Turn on prefers-reduced-motion media query
2. Use the TableOfContents to navigate around a page
3. Note how it still slides smoothly.

### More Information

I found this while I was investigating some other things that I wanted to change with the ToC; 

* Exposing the innerHTML permalink 🔗 as a parameter that defaults to 🔗
* Boolean flag to wrap the entire <h> tag in the permalink, rather than appending it
* Styling options exposed for the permalink (on hover permalinks are really trendy!)
* Expose the `block` and `inline` parameters of the `scrollIntoView` method.
* Expose the `headingSizeThreshold` as a parameter to customise when headings are added to `visibleHeadings`
* If the heading scanned has no `innerText` then the id will be `""`. It would be best to extract the logic for creating the ids, even better to expose it as a utility function.

**Comment by endigo9740** [comment]
As part of the v2 updates we now have a solution for this. This can now be considered complete:
https://www.skeleton.dev/utilities/table-of-contents#smooth-scrolling
