### ISSUE TITLE
Firefox: Modal with a single button can't be tabbed in

### ISSUE THREAD

**Issue by Mahmoud-zino** [skeletonlabs/skeleton#1591]
### Current Behavior

Firefox: if there is only one button even after tabbing it won't show the focus style however when there are multiple buttons tabbing will display the focus style correctly.

### Expected Behavior

tabbing should display the focused style even if there is only one button.

### Steps To Reproduce

1. Navigate to [Skeleton - Modals](https://www.skeleton.dev/utilities/modals)
2. click on the first "Show Modal"
3. tabbing won't change the style but clicking in the region of the button and then tabbing will display the correct style.
4. On the other hand, if you click on the "Confirm Modal" example which has two buttons, tabbing will work as expected.

**Comment by endigo9740** [comment]
FYI This appears to be limited to Firefox. On Chrome this behaves as expected.

**Comment by aaronmichaelhappe** [comment]
I would be happy to work on this issue.

**Comment by Sarenor** [comment]
@aaronmichaelhappe after an accidental oopsie: I assigned the issue to you.
Usually we ask people to open an early draft pr as soon as possible to mark it as "definitely being worked on", but seeing as this is probably mostly a debugging thing: Just keep us up to date?

**Comment by aaronmichaelhappe** [comment]
@Sarenor sure thing. I am aaronmichaelhappe on the discord server if you need to reach out and will keep you up to date.

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2357
