### ISSUE TITLE
Image Layout Features

### ISSUE THREAD

**Issue by DevOfManyThings** [skeletonlabs/skeleton#1594]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

There's not currently much in the way of image components in Skeleton yet, and as I'm making something similar for my personal project figured it'd be worthwhile making it in a generic fashion and contributing to Skeleton :)

There's quite a lot of possible image layouts that can be added, Flowbite has 7, MUI has 8, I think it would be worthwhile starting with some of the popular layouts then if there's demand we can add in more advanced variants in the future?

### Image List
This is the relatively standard image gallery users expect [Mui's Standard Image List](https://mui.com/material-ui/react-image-list/#standard-image-list), [Flowbite's Default Gallery](https://flowbite.com/docs/components/gallery/#default-gallery).
Generally speaking this will be a grid like structure with square images.

### Masonry
For the Masonry layout, there's two approaches that can be taken for how images are ordered, both have some complications/trade offs in how they'll work.

**Column Ordered**
[Flowbite Masonry Grid](https://flowbite.com/docs/components/gallery/#masonry-grid) & [MUI Image List Masonry](https://mui.com/material-ui/react-image-list/#masonry-image-list)
This is where images go descending down the first column, then wraps up to go down the 2nd column, then 3rd etc.

With this approach as the user passes in a single list of images, it can be hard to predict what the end user will see on their device. Normally the images at the top of each column should be the most important, but depending on the width of the device and how many columns are displayed, it could be image 23 at the top of column 2 or image 14.  Assuming the number of columns is fixed it would still require work on the part of the developer to get the order correct.

The main benefit of this approach is it plays nicer with SSR without any layout shifts.

| First Header  | Second Header | Column Three |
| ------------- | ------------- | ------------- |
| Image 1  | Image 4 | Image 7 |
| Image 2  | Image 5  | Image 8 |
| Image 3  | Image 6  | Image 9 |

**Row Ordered**
[MUI Image Masonry](https://mui.com/material-ui/react-masonry/#image-masonry)
Where images go left to right along the columns, this is closer to a standard image gallery.

| First Header  | Second Header | Column Three |
| ------------- | ------------- | ------------- |
| Image 1  | Image 2 | Image 3 |
| Image 4  | Image 5  | Image 6 |
| Image 7  | Image 8  | Image 9 |

I personally prefer row ordered, and think that's what most users would reasonably expect when implementing an Image Layout, otherwise it gets funky in how you can reasonably know the order of images that will be loaded.

What makes this approach for Masonry more complicated compared to a standard gallery is when you involve SSR, as behind the scenes you can't use a real grid here, and it looks roughly like this:
```
<div>
    <img 1>
    <img 4>
</div>
<div>
    <img2>
    <img5>
</div>
<div>
    <img3>
    <img6>
</div>
```
So if you want to change the number of columns, you need to shift about the positioning of elements to be in different columns manually.

During SSR, it's not possible to know whether there is 1 or 3 columns being rendered as the device size isn't known (and I don't think it's good practice to get into using request metadata to predict that).

I think the best solution to this is to use the same approach described in [How to implement a responsive sidebar drawer](https://www.skeleton.dev/blog/how-to-implement-a-responsive-sidebar-drawer). We can just render two galleries, and use tailwind responsive design to determine which is rendered. With that in mind, I think it's better just to have two options for number of columns, 1 for mobile, n for tablet+ sized devices (defaulting to 3).

To solve this problem MUI has the developer enter default values that are used in SSR, but that means you either design for mobile first and then desktop users see a single column until javascript is loaded and it flashes to n columns, or vice verse, using the above solution I think is better practice.

### Common Aspects

- There's pagespeed optimizations to be made such as ensuring images that cause layout shifts are loaded normally, and other images are lazily loaded.
- Alt text
- Accept an array of images so we can use srcset (load lower resolution images on smaller devices).
- Can use Skeleton placeholders to show loading placeholders by default

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

**Flowbite**
https://flowbite.com/docs/components/gallery/

**MUI**
https://mui.com/material-ui/react-image-list/
https://mui.com/material-ui/react-masonry/

**Comment by endigo9740** [comment]
Can you remind me your Discord username - I recall discussing this recently but have trouble keeping folks straight when 
the names differ on either side. (sorry!)

One of the reason we don't include dedicate components for these is that it's primarily a layout issue, not a image-specific problem whatsoever. I find components for layout are often times misguided when it comes to projects using Tailwind. The reason for this is expressed pretty well BY Flowbite's example - this can handled pretty much entirely using Tailwind's grid layouts:

```html
<div class="grid grid-cols-2 md:grid-cols-3 gap-4">
    <div>
        <img class="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/square/image.jpg" alt="">
    </div>
    <div>
        <img class="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/square/image-1.jpg" alt="">
    </div>
    <div>
        <img class="h-auto max-w-full rounded-lg" src="https://flowbite.s3.amazonaws.com/docs/gallery/square/image-2.jpg" alt="">
    </div>
</div>
```

Abstracting any part of this to a component or what we refer to as "element" styling would only take away the control from the end user. In this case, we would be re-inventing the wheel using tools Tailwind already provides directly.

However, I do think this is valuable information to convey to users - that this can be handled via Tailwind and providing a few basic examples. Our new "Tailwind Blocks" section is the perfect location for this to live. We would introduce nothing new to the library itself, merely show how to use Tailwind to solve for this. Much like the Gradient Heading examples.

I'd welcome a contribution for a new Tailwind > Blocks > Image List page that details this. It could literally use the same markup Flowbite provides (perhaps with attribution) though nothing here is specific to Flowbite except the images used. Those are owned and hosted by Flowbite. We would of course want to exchange for a set of images - like from Unsplash, ex:

```
// Format as: https://source.unsplash.com/{imageID}/{dimensions}
https://source.unsplash.com/YOErFW8AfkI/128x128
```

**Comment by DevOfManyThings** [comment]
Yeah the image list example is very basic and is pretty much straight tailwind, as you said that suits the blocks section quite well!

The masonry example Flowbite uses is column ordered, the row ordered one requires some custom logic (although not particularly advanced). Would you be interested that being added? Mine is basically as described above with some logic for placeholders and only loading images once they're in the viewport. As I said on discord I'm not 100% sure if that's something Skeleton would want to have, which is why I asked there first before raising the issue, if you're not interested that's completely understandable!

If you just want the blocks description it may be better closing this and adding what you've posted as a task item on that.

**Comment by endigo9740** [comment]
>  Would you be interested that being added?

You'll need to link the repo or send a draft PR, we can't really access without eyes on the code. Here's our contribution guidelines if it helps:
https://www.skeleton.dev/docs/contributing

But as it stands the answer would be no for creating new components given a lot of this can be created in the "Block" format. The goal with Skeleton is primarily to provide small privatives (the Lego blocks) so folks can put those together in any fashion they desire, with our theme system applied on top. We definitely don't want to reinvent what Tailwind provides if we can avoid it.

We do have a history of adding more complex components and features on occasion (ex: stepper). But typically folks aren't happy with the result - which tends to be more limited than full standalone libraries. This makes me leery to go down that path again if we can avoid it, and I worry a component like this might fall in that category.

But again, open to review and go from there.

**Comment by DevOfManyThings** [comment]
I'll just close this issue then, I thought it likely wasn't relevant to Skeleton which is why I checked on discord before raising the issue, don't think there's much point putting in the work refactoring it for review when it's unlikely to be merged in.

**Comment by endigo9740** [comment]
I've opened a ticket per the new Tailwind image layout block pages here for anyone interested:
https://github.com/skeletonlabs/skeleton/issues/1600
