### ISSUE TITLE
Conic Gradient legend floating point math problem

### ISSUE THREAD

**Issue by DGne-Nurag** [skeletonlabs/skeleton#1603]
### Current Behavior

I try to display a Conic Gradient with the results of a vote.
Here i did some math to get start and end points. The final stops look like this:
[
  {
    "label": "3",
    "color": "yellow",
    "start": "0.00",
    "end": "28.57"
  },
  {
    "label": "5",
    "color": "orange",
    "start": "28.57",
    "end": "85.71"
  },
  {
    "label": "8",
    "color": "purple",
    "start": "85.71",
    "end": "100.00"
  }
]

But the Gradiant looks like this
![image](https://github.com/skeletonlabs/skeleton/assets/661697/d8ad4be2-23d7-4383-83e6-676a4bd48d2b)

The Gradient itself is OK but the legend is strange.

A hint from Discord-User Sebas is that it is a floating point math problem in js.
![image](https://github.com/skeletonlabs/skeleton/assets/661697/ed676500-6764-48b0-8e5c-a4ce573bc5c5)

### Expected Behavior

If there are Values with 2 decimals provided there are only 2 decimals in the Legend

### Steps To Reproduce

1. create a Conic Gradient with given values
2. enable legend

**Comment by SebasF1349** [comment]
I can do a pr, just one question: should be defaulted to 2 digits?

**Comment by DGne-Nurag** [comment]
in my case 2 digits would be OK, but in my opinion configurable with 2 as default would be best

**Comment by endigo9740** [comment]
@SebasF1349 let's add a prop that decides the digits using [toFixed()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed). The prop can be something like this:

`export let digits = 2`

Then

`someValue.toFixed(digits);`

Thanks!
