### ISSUE TITLE
Drawer on:backdrop Triggers Inside Drawer

### ISSUE THREAD

**Issue by noot-tutel** [skeletonlabs/skeleton#1610]
### Current Behavior

When using a custom `on:backdrop` option for the Drawer utility, any interaction within the Drawer triggers the backdrop event.

A similar issue to #1240

### Expected Behavior

The `on:backdrop` should not be triggered when interacting within the Drawer.

### Steps To Reproduce

1. Create a Drawer component with a custom `on:backdrop` event
-- Reproduceable in both +layout.svelte and +page.svelte
-- Example: 
```
// Rest of <script lang='ts'> above this point //

	function consoleBackdrop() {
		console.log("backdrop triggered");
	};
</script>
<Drawer on:backdrop={consoleBackdrop} />
```
2. Monitor the Console Log while clicking/interacting inside the Drawer.

**Comment by Mahmoud-zino** [comment]
we can solve this easily by firing the event only when the click occurs on the backdrop like this: 
```ts
if (event.target === elemBackdrop) { 
        drawerStore.close();
	/** @event {{ event }} backdrop - Fires on backdrop interaction.  */
	dispatch('backdrop', event);
}
```
but maybe it would also be necessary to create a "on:drawerClick" event so we don't miss any functionality here.
@endigo9740 If this sounds good, I would like to fix this issue.

**Comment by endigo9740** [comment]
@Mahmoud-zino yep, that looks like the appropriate fix here.
