### ISSUE TITLE
Focus Trap loses focus after mouse click (or any other type of focus not from tabbing)

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#1613]
### Current Behavior

A good example of the behaviour is when opening the docs search and clicking on any element that is not the docs search bar or elements. After doing that and hitting tab the focus trap basically lost focus and this is undesired behaviour.

Demonstration: https://www.youtube.com/watch?v=axzLbWhhxsM

### Expected Behavior

When selecting anything else inside the dialog and then hitting tab again I would expect the focustrap to stay.

### Steps To Reproduce

1. Using focustrap
2. Click on any non-tabbable element.
3. Hit Tab
4. Focus trap is lost

### Link to Reproduction / Stackblitz

https://www.skeleton.dev/

### More Information

I have already found an pretty easy fix for this and will work on a PR immediately after submitting this issue.

**Comment by endigo9740** [comment]
I'm going to go ahead and file this as a duplicate under this ticket:

- https://github.com/skeletonlabs/skeleton/issues/1613

The fix described in this thread should resolve this issue and help keep focus where it needs to be (within the modal).
