### ISSUE TITLE
<MyModalComponent> received an unexpected slot "default"

### ISSUE THREAD

**Issue by AuroraLantean** [skeletonlabs/skeleton#1631]
### Current Behavior

When I click to open the modal, I got this warning in my browser console:
```
<ModalAddItem> received an unexpected slot "default".
```

### Expected Behavior

This warning should not happen

### Steps To Reproduce

Download and run my code from the attached repo.
Click on "Marketplace" on the left hand side bar.
Click on "Add Item Modal", which is located in the top middle position.
You will see the warning in your browser console.

### Link to Reproduction / Stackblitz

https://github.com/AuroraLantean/svelte-tailwind-skeleton

### More Information

I think this has something to do with the modalComponent slot from the doc https://www.skeleton.dev/utilities/modals
```
// Provide a template literal for the default component slot
    slot: '<p>Skeleton</p>'
```
What is the default component slot? 
Even if I remove the whole slot from the ModalComponent. the warning persists. 
I don't have any slot call "default". I have searched for it. Nothing. 

My modalComponent: https://github.com/AuroraLantean/svelte-tailwind-skeleton/blob/main/src/components/ModalAddItem.svelte
The parent component of the modalComponent: https://github.com/AuroraLantean/svelte-tailwind-skeleton/blob/main/src/routes/marketplace/%2Bpage.svelte 

Please advise. Thank you

**Comment by Mahmoud-zino** [comment]
As mentioned here https://github.com/skeletonlabs/skeleton/issues/979#issuecomment-1435092723
This is a svelte warning and you can just ignore it as it won't show in production.
