### ISSUE TITLE
Forward Relevant Events like `mouseover` in `AppRailTile | AppRail` Component

### ISSUE THREAD

**Issue by JustMrMendez** [skeletonlabs/skeleton#1632]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

The `AppRailTile` component currently forwards `on:click | on:change` events only https://github.com/skeletonlabs/skeleton/blob/91daeaa18abfce2ecb0fac241a3ed7ec5b2487da/packages/skeleton/src/lib/components/AppRail/AppRailTile.svelte#L70

It will be usefully to forward other relevant events like `mouseover | mouseleave` on the component wrapper.

https://github.com/skeletonlabs/skeleton/blob/91daeaa18abfce2ecb0fac241a3ed7ec5b2487da/packages/skeleton/src/lib/components/AppRail/AppRailTile.svelte#L65

this will enable the use of alternative state handlers like this

```svelte
{#each menuCategories as category}
    <AppRailTile 
     on:mouseover={() => ($storeCategory = category.id)}
     name={category.id} 
     value={category.id} 
      bind:group={$storeCategory}>
      (icon)
    </AppRailTile>
{/each}
```

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@JustMrMendez "relevant" is much less obvious than one might think when it comes to events. If you could provide a full list of what you would like to see we'll aim to include those.

**Comment by JustMrMendez** [comment]
> @JustMrMendez "relevant" is much less obvious than one might think when it comes to events. If you could provide a full list of what you would like to see we'll aim to include those.

I suggest `on:mouseover | on:mouseleave` and the **A11y** recommended `on:focus | on:blur`

or a custom event like on:hover which will take into account the state of them

**Comment by endigo9740** [comment]
@JustMrMendez thank you. Do you have a source for that a11y recommendation please?

**Comment by JustMrMendez** [comment]
> @JustMrMendez thank you. Do you have a source for that a11y recommendation please?

https://kit-docs-demo.vercel.app/docs/accessibility/warnings#a11y-mouse-events-have-key-events

it's throws a warning by the svelte compiler, not sure how important it is

**Comment by endigo9740** [comment]
@JustMrMendez FYI I went ahead and snuck this in. This will come as part of tomorrow's new release.
