### ISSUE TITLE
Add background prop to RadioItem

### ISSUE THREAD

**Issue by kylclrk** [skeletonlabs/skeleton#1636]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently, the `<RadioItem />` component cannot have a background color separate from the classes applied via the `active` prop. It would be nice to be able to provide a color for radio items that are not selected (active).

For example, I have this markup:

```
<RadioGroup active="bg-primary-700" >
	<RadioItem bind:group={selection} value={0} class="bg-surface-500">Item 1</RadioItem>
	<RadioItem bind:group={selection} value={1} class="bg-surface-500">Item 2</RadioItem>
	<RadioItem bind:group={selection} value={2} class="bg-surface-500">Item 3</RadioItem>
</RadioGroup>
```

Due to not being handled separately, an active radio item will get both background classes applied to it.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@kylclrk not sure we can provide this. The RadioItem components don't have a background color normally, they're transparent to show the RadioGroup background, then when in the active state the background is set to the Item to indicate selection. Are you sure you don't mean to change be Group instead? That is already supported.

Here's a quick illustration of what I mean:

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/c98b82fc-3fb8-4ade-b356-28c76fa38196)

- Blue - the background of the Group element
- Gray - the transparent background of each Item
- Yellow - the active item's color

If each default state color per item has a color I really worry about the accessibility and understanding which Item is highlighted.

**Comment by kylclrk** [comment]
I would say as long as there are more than 2 radio buttons, it would be fairly obvious which color represents the selected and which color represents the unselected items. I guess it would be up to the developer to make sure they're doing it in an accessible way.

That said, what I should actually be using is the Tab Control. I'm not sure why I was reaching for radio groups.

Thanks for this awesome project! I might try to contribute in the future. And I'll try to get my employer to sponsor (no promises)
