### ISSUE TITLE
Changeable "Next" button in stepper 

### ISSUE THREAD

**Issue by alanfaz** [skeletonlabs/skeleton#1644]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Make the stepper in a way that allows us to add a finish and next button so that when certain criteria is met, we can be able to submit the form. 

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

In this examples, the steps after the one rendered are optional. 

![image](https://github.com/skeletonlabs/skeleton/assets/1165001/538cdc4d-a966-4334-9e97-585540293386)

![image](https://github.com/skeletonlabs/skeleton/assets/1165001/9a66d5a6-30b6-4e32-b9cf-640eef149a14)

**Comment by endigo9740** [comment]
@alanfaz thanks for the clear explanation and great reference shots. I can see the benefit of this, we'll see what we can do.

**Comment by endigo9740** [comment]
Thanks for the great reference shots @alanfaz. I'll think about how we might implement this.

**Comment by Mahmoud-zino** [comment]
I would like to work on this issue.

**Comment by endigo9740** [comment]
This issue should now be considered consolidated here: https://github.com/skeletonlabs/skeleton/issues/1780
