### ISSUE TITLE
variant-ringed-primary not working in intellisense

### ISSUE THREAD

**Issue by t-lock** [skeletonlabs/skeleton#1650]
### Current Behavior

When using VSCode with the Tailwind Intellisense and PostCSS language support add-ons, `variant-ringed-primary` is missing from intellisense.

Notably, `variant-filled-primary` _**is not**_ suffering the same fate.

There may be other cases, but I have not found them. If I encounter any more, I will update this issue.

### Expected Behavior

`variant-ringed-primary` and `variant-filled-primary` have the same experience in intellisense.

### More Information

First mentioned in Discord support chat, where a core maintainer was able to reproduce the issue and subsequently asked to open this issue.

https://discord.com/channels/1003691521280856084/1116435442510872709/1116444096924491819

**Comment by AdrianGonz97** [comment]
Thanks for raising this issue!

Just for future reference, here's a list of variants that do appear in our intellisense:
![screenshot](https://i.imgur.com/hz5LY2n.png)

And here's a list of variants that do not appear in our intellisense plugin:
```
variant-outline-primary
variant-outline-secondary
variant-outline-tertiary
variant-outline-success
variant-outline-warning
variant-outline-error
variant-outline
variant-outline-surface

variant-filled-tertiary
variant-filled-success
variant-filled-warning
variant-filled-error

variant-ringed
variant-ringed-primary
variant-ringed-secondary
variant-ringed-tertiary
variant-ringed-success
variant-ringed-warning
variant-ringed-error
variant-ringed-surface

variant-ghost-primary
variant-ghost-secondary
variant-ghost-tertiary
variant-ghost-success
variant-ghost-warning
variant-ghost-error

variant-soft-primary
variant-soft-secondary
variant-soft-tertiary
variant-soft-success
variant-soft-warning
variant-soft-error

variant-glass-primary
variant-glass-secondary
variant-glass-tertiary
variant-glass-success
variant-glass-warning
variant-glass-error
variant-glass-surface
variant-glass

variant-gradient-primary-secondary
variant-gradient-secondary-tertiary
variant-gradient-tertiary-primary
variant-gradient-secondary-primary
variant-gradient-tertiary-secondary
variant-gradient-primary-tertiary
variant-gradient-success-warning
variant-gradient-warning-error
variant-gradient-error-success
variant-gradient-warning-success
variant-gradient-error-warning
variant-gradient-success-error
```

**Comment by LucasGabrielBravo** [comment]
I noticed this happens in other classes like `btn-lg btn-xl` among others. And as said by  @t-lock, there may be others.
I changed the package.json from `"@skeletonlabs/skeleton": "^1.7.1" ` to `"@skeletonlabs/skeleton": "1.5.1"` and intellisense is working again.
When changing to `"@skeletonlabs/skeleton": "1.6.0"` or greater the problem happens again

**Comment by endigo9740** [comment]
Thanks for the extra info @LucasGabrielBravo 

@AdrianGonz97 @niktek 1.6 would have been the introduction of the monorepo - do we think this might be related?

**Comment by AdrianGonz97** [comment]
@endigo9740 Yup! I know exactly what happened. My refactor of the plugin has fixed this so this should be resolved soon.
