### ISSUE TITLE
Stepper on:next prevent step

### ISSUE THREAD

**Issue by alanfaz** [skeletonlabs/skeleton#1652]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Finding a way to validate things before moving to the next step for instance:

	```
	function onNextHandler(e) {
		switch (e.detail.step) {
			case 0: //Login data
				if (!loginForm.checkValidity()) {
					return false; //Here the next stepper wont move to next step
				}
				return true; //Advance as normal
			case 1: //Subscription data
				break;
			case 2: //Payment data
				break;
			case 3: //Status data
				break;
		}
	}
	```

### What type of pull request would this be?

None

**Comment by vorian77** [comment]
Love Skeletons and thanks to the team for making it available!

This seems like a standard requirement for any use case that requires backend processing between steps. Is there a reason it wasn't included in the initial design?

**Comment by piperun** [comment]
I've wrestled with this issue myself and I think so far the best temporary fix for anyone using Stepper is to do all validation at the complete stage.
Or maybe you can try and store each step in a store and validate them within the switch case example you showed.

**Comment by vorian77** [comment]
I ended up validating each field on:change and on:keyup, and associated the step "locked" flag with the validation of the entire form. Now, the Next and Complete buttons are only available when the entire form is valid, at least on the client side. I submit the form in the next handler. There is still the potential problem when/if the database upsert fails.

**Comment by endigo9740** [comment]
This issue should now be considered consolidated here: https://github.com/skeletonlabs/skeleton/issues/1780
