### ISSUE TITLE
autoModeWatcher does not work when a content security policy blocking 'unsafe-inline' is set

### ISSUE THREAD

**Issue by fnimick** [skeletonlabs/skeleton#1657]
### Current Behavior

I'm not sure how to resolve this, as the Vite build process minifies the inlined code, so I can't reliably use a hash content security policy.

In addition, there appears to be no way to access the Svelte script nonce from a svelte template (only from app.html via `%sveltekit.nonce%` ), so a nonce-based policy also does not work.

### Expected Behavior

Ideally there would be a way to use this without inlining the script directly (as a module) - or maybe there is a way to reliably load this with a CSP set that I am not aware of?

### Steps To Reproduce

- Add `autoModeWatcher` to a sveltekit project as described
- Add a CSP with a `script-src` of `['self']`, in `svelte.config.js`:
```
const config = {
  preprocess: vitePreprocess(),

  kit: {
    csp: {
      directives: {
        "script-src": ["self"],
      },
    },
  },
};
```
- Observe CSP errors for the autoModeWatcher utility in the log

**Comment by endigo9740** [comment]
@AdrianGonz97 given you have a better understanding of the inner workings of Vite, Svelte, and SvelteKit, I'd love if you could give this a look. No rush, given current priorities for the v2 release, but I'd appreciate your input.

**Comment by endigo9740** [comment]
We're going to be trying a different approach to the OS preference strategy in Skeleton v3. I'm going to group this with that milestone.

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2359
