### ISSUE TITLE
InputChip incompatible with sveltekit superforms constraints

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#1665]
### Current Behavior

When spreading the ``{...$constraints}`` on a InputChip there are issues (see screenshot).
![image](https://github.com/skeletonlabs/skeleton/assets/63101006/de859abd-8f23-47c4-a4cb-693e90c89fbd)

### Expected Behavior

Spreading ``{...$constraints}`` should work like how it works on a ``select`` element

### Steps To Reproduce

1. Using InputChip
2. Create a zod schema
3. Create a superValidate form
4. Spread the constraints from the superForm function onto a Inputchip component
5. See typing errors

**Comment by endigo9740** [comment]
@Hugos68 was this one you were working to resolve? I'll assign the ticket to you if so. Just want to prevent duplicate effort.

**Comment by Hugos68** [comment]
> @Hugos68 was this one you were working to resolve? I'll assign the ticket to you if so. Just want to prevent duplicate effort.

I am not currently working on it no, I won't have time to work on it either so it's up for grabs, I think it only affects typescript users since it was a type error.

**Comment by endigo9740** [comment]
Ok cool, thanks for clarifying!

**Comment by AdrianGonz97** [comment]
So I've been looking into this issue and I noticed a couple of important errors:
1. `$$restProps` isn't being spread onto the `input` element like we [say it does here](https://www.skeleton.dev/components/input-chips) (click on the Props tab).
2. There's an export called `max` that's used for the "Maximum number of chips". This export needs to have a different name as there is an existing native attribute for `input` that's also called `max` that users should be able to pass through with the extras of `$$restProps`.
4. We also have other exports like `minlength` and `maxlength` that should be applied as attributes to the `input` element.
5. We should probably provide a way for users to add attributes to the `select` element as well.

Unfortunately, I don't see a path in resolving point 2 in in a non-breaking way. I would suggest that we add that onto our v2 task list.

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2364
