### ISSUE TITLE
TableOfContents does not update

### ISSUE THREAD

**Issue by royce-mathew** [skeletonlabs/skeleton#1666]
### Current Behavior

I have a setup where I've put the table of contents inside `routes/+layout.svelte`.  The TableOfContents is not updating whenever I switch the route. For example if I go from `/` to `/privacy`. I have to refresh the page to get the table of contents working each time. 

### Expected Behavior

The TableOfContents should update everytime a route switch happens.

### Steps To Reproduce

1. My `routes/layout.svelte` looks like this:
```svelte
<AppShell>
	<!-- Sidebar Slot -->
	<svelte:fragment slot="sidebarLeft">
		<StaticNav />
	</svelte:fragment>

	<!-- Table of Contents -->
	<svelte:fragment slot="sidebarRight">
		<div class="bg-surface-500/10 dark:bg-surface-800/40 w-0 lg:w-full h-full lg:px-5 py-5">
			<TableOfContents target="#toc-target"/>
		</div>
	</svelte:fragment>

	<slot />
</AppShell>
```

**Comment by Mahmoud-zino** [comment]
Yeah, right now It will only update `onMount`, However, we are planning to refactor the component in the near future, see #1030 

In the meantime (probably until v2), you can force the table of content to rerender when the page route changes by wrapping it with a `key` block.

```svelte
{#key $page.url.pathname}
    <TableOfContents target="#toc-target"/>
{/key}
```

see [Svelte - docs - key](https://svelte.dev/docs#template-syntax-key)

**Comment by endigo9740** [comment]
@royce-mathew the next time we revisit the table of contents will be the update Mahmoud mentioned above. It's intended to fix several known issues, such as this. For now I'd suggest his work around, then keep an eye out for the future update. Thanks for reporting this though!
