### ISSUE TITLE
Feature request for TreeView Component 

### ISSUE THREAD

**Issue by artello73** [skeletonlabs/skeleton#1668]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Hello,
Just would like to raise a feature request for TreeView Component which able to represent an navigate over hierarchical dat with ability to select the items (like in File Explorer for instance). 

Looking around the most feature rich component is TreeView from Framework7.io (https://framework7.io/svelte/treeview ) which does all the things, however it can't be used with Skeleton. 

![image](https://github.com/skeletonlabs/skeleton/assets/6637705/96a93505-e916-4cb3-a00e-167a27b55ffd)

The another version found on the web is TreeView from carbon-components-svelte (https://carbon-components-svelte.onrender.com/components/TreeView) which is more data driven component requiring a specifically formatted JSON data. 

![image](https://github.com/skeletonlabs/skeleton/assets/6637705/8cd82b33-1102-40d2-aa5e-a087dc6dd8cf)

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
Thanks @artello73. I cannot promise a quick turn around on this, but for anyone that needs a temporary solution, we might recommend using nested accordions. Personally I'd recommend the native Disclosure element over our components, just for simplicity:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by Mahmoud-zino** [comment]
I would like to work on this component.
Also, it would be great if we define which features we are going to include.

**Comment by endigo9740** [comment]
Thanks @Mahmoud-zino I'll go ahead and assign it. I'll be pressed for time on getting the reqs for this, but remind me in a couple days if you haven't seen anything from me please.
