### ISSUE TITLE
AppShell on:scroll={handler} gives invalid type for event

### ISSUE THREAD

**Issue by brugh** [skeletonlabs/skeleton#1670]
### Current Behavior

I've setup a default SkeletonUI project and want to use the on:scroll on the AppShell. But following the docs I get a warning: 
```
Argument of type '(event: UIEvent & { currentTarget: EventTarget & HTMLDivElement; }) => void' is not assignable to parameter of type '(e: Event) => void'.
  Types of parameters 'event' and 'e' are incompatible.
    Type 'Event' is not assignable to type 'UIEvent & { currentTarget: EventTarget & HTMLDivElement; }'.
      Type 'Event' is missing the following properties from type 'UIEvent': detail, view, which, initUIEvent
```

the handler looks like this: 
```
	function scrollHandler(event: UIEvent & { currentTarget: EventTarget & HTMLDivElement }) {
		$scrollY = event.currentTarget.scrollTop;
	}
```

The project compiles without error and the scrolling object that's using $scrollY from the store is working just fine. Only the IDE shows the abovementioned error. 

### Expected Behavior

the scrollHandler argument type should match the on:scroll defined type. 

### Steps To Reproduce

`<AppShell` ... on:scroll={scrollHandler}>`

`function scrollHandler(event: UIEvent & { currentTarget: EventTarget & HTMLDivElement; }) {
	console.log(event.currentTarget.scrollTop);
}`

**Comment by Mahmoud-zino** [comment]
I didn't test it yet, but the new Utility type `SvelteEvent` implemented by @AdrianGonz97 could solve this problem.

**Comment by endigo9740** [comment]
@Mahmoud-zino I think you may be right. @AdrianGonz97 if you can confirm we'll see about getting this updated.

**Comment by AdrianGonz97** [comment]
Technically, yes! The new utility type can help out here, but the user won't be the one using it. 

On our end, we'll have to enhance the event types by adding an [`$$Events` interface](https://github.com/dummdidumm/rfcs/blob/ts-typedefs-within-svelte-components/text/ts-typing-props-slots-events.md#detailed-design) inside of the component:
```ts
interface $$Events {
	scroll: SvelteEvent<UIEvent, HTMLDivElement>;
}
```

This will provide the correct event types for any events that we are forwarding. If we're also dispatching custom events, those will have to be added to this interface as well.

On the user's end, they will have to use a svelte provided utility type, [`ComponentEvents`](https://svelte.dev/docs/typescript#types-componentevents), to grab the component event type:
```svelte
<script>
	import { AppShell } from '@skeletonlabs/skeleton';
	import { writable } from 'svelte/store';
	import type { ComponentEvents } from 'svelte';
	
	const scrollY = writable(0);
	
	function scrollHandler(event: ComponentEvents<AppShell>['scroll']) {
		$scrollY = event.currentTarget.scrollTop;
	}
</script>

<AppShell on:scroll={scrollHandler}>
	<slot />
</AppShell>
```

**Comment by Mahmoud-zino** [comment]
@AdrianGonz97 I just tested it and I must say this looks really awesome, I've gone ahead and created a PR with your suggestion.

**Comment by endigo9740** [comment]
@Mahmoud-zino @AdrianGonz97 The idea of the users having to import a custom type for this feels...off.

I mean if it works it works, but I was hoping users wouldn't have to implement another step for something like this. What type would be set for someone doing this in their own route/component?

```html
<div on:scroll={scrollHandler} />
```

```ts
function scrollHandler(event: someEvent): void {
    // ...
}
```

All we're doing is forwarding that `on:scroll` event up - why do we have to introduce a custom type for something users would setup themselves. Would they have to setup a custom type for this too?

Maybe I misunderstand how it works though.

**Comment by Mahmoud-zino** [comment]
@endigo9740 
@AdrianGonz97 please correct me, if I am wrong!
This makes it safer & easier for users to access the target div.
I had always done something like this:
```ts
function scrollHandler(event: Event): void {
    const target = event.target as HTMLDIVElement;
    // do stuff with target
}
```
while this delivers the target type with it. essentially what the original code in the app shell tries to do.
but I get it, it could confuse new users....

**Comment by endigo9740** [comment]
Yeah, you gotta remember the DX on this one - they're already confused as to why they can't bind the window scroll. Now have to learn to use the App Shell's forwarded event, and then we're adding an additional step to import the scroll event type?

This is one of those parts where Typescript is kind of counter intuitive to Svelte. Svelte provides this really simple and elegant mechanic, and then we've gotta go and make it difficult by providing this additional type to be used.

It's not hard to do, it's just annoying.

**Comment by AdrianGonz97** [comment]
@Mahmoud-zino is correct. It provides the correct event type along with the correct element type that the event is targeting.

This is the recommended way of typing events in Svelte. If you don't register the types in the `$$Events` interface, users won't get the correct event types on our components.

> why do we have to introduce a custom type for something users would setup themselves. Would they have to setup a custom type for this too?

`ComponentEvents` is a type that's [provided by Svelte](https://svelte.dev/docs/typescript#types-componentevents). It's designed to be used this way..

Aside from that, users don't _have_ to do anything, really. If they just want to trigger some other action when the event fires, then they're free to define the handler like so: 

```svelte
<script lang="ts">
	function scrollHandler(e: Event) {
	    // do some stuff
	}
</script>

<div on:scroll={scrollHandler} />
```

It's only when the user _needs_ to have the additional typing from the specific event type, or the type of element it's targeting, then that's when they'd use `ComponentEvents`.

> Yeah, we've gotta remember the DX on this one 

The DX of not having the correct types is far worse than having to occasionally import `ComponentEvents` if the user needs further type safety.
