### ISSUE TITLE
Unexpected Drawer close animation with multiple Drawers

### ISSUE THREAD

**Issue by ollema** [skeletonlabs/skeleton#1671]
### Current Behavior

When using multiple Drawers, they slide out in unexpected directions when closing the last one

### Expected Behavior

When using multiple Drawers, they should slide out from where they came from

### Steps To Reproduce

Using the attached StackBlitz, press `l` -> `l` or `r` -> `r` to open and close a Drawer. Then it slides out and in as expected.

Using the attached StackBlitz, press for example `l` -> `r` -> `r` to first open the left Drawer, then close it and open the right Drawer and finally close the right Drawer as well. Notice how the right Drawer slides out in the wrong direction!

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-repl-agdvvz

### More Information

https://github.com/skeletonlabs/skeleton/assets/31876997/b8813832-8f24-441c-ad48-cdecd1e1d56f

**Comment by endigo9740** [comment]
@ollema It would be a strange use case that you would flip from one drawer to another like that, can you explain how that's being used in a real world scenario? Our expectation was always that the drawer would triggered from the underlying page(s), which means there would be a close triggered between each opening.

Reporting edge cases are fine, but we'll need to weight our priority against that.

**Comment by ollema** [comment]
> @ollema It would be a strange use case that you would flip from one drawer to another like that, can you explain how that's being used in a real world scenario? Our expectation was always that the drawer would triggered from the underlying page(s), which means there would be a close triggered between each opening.
> 
> Reporting edge cases are fine, but we'll need to weigh our priority against that.

The use case here is switching from one Drawer to the other. In this application, one Drawer is there for helping the user (keybinds, resources, legend etc) and the other Drawer is there for showing additional information about the data in question (technical terms like confidence, frame ID, file path).

Right now, you can toggle "help" by pressing `h` and you can toggle "info" by pressing `i`.

It is also possible to switch from "help" to "info" by pressing the "other" button so to speak.

> ...which means there would be a close triggered between each opening

As can be seen in the following snippet, included in the StackBlitz:
```ts
function on_window_keydown(e: KeyboardEvent) {
  if (e.key === 'l') {
    e.preventDefault();
    if ($drawerStore.open) {
      if ($drawerStore.id === 'left') {
        drawerStore.close();
      } else {
        drawerStore.close();
        open_left_drawer();
      }
    } else {
      open_left_drawer();
    }
  }
  if (e.key === 'r') {
    e.preventDefault();
    if ($drawerStore.open) {
      if ($drawerStore.id === 'right') {
        drawerStore.close();
      } else {
        drawerStore.close();
        open_right_drawer();
      }
    } else {
      open_right_drawer();
    }
  }
}
```
the previous Drawer is in fact closed between each opening, just before opening the next one. 

This fast `drawerStore.close();` followed by `open_right_drawer();` seems to work fine, looks great, but the problem arises when closing the final Drawer so to speak. Then the weird animation appears.

> Reporting edge cases are fine, but we'll need to weigh our priority against that

Of course, I just wanted to bring it up. This is by no means a deal breaker, just figured that maybe there is an easy fix. If not, feel free to put in the backlog or close the issue altogether of course!

**Comment by endigo9740** [comment]
I see, maybe as a temporary solution you could introduce a small delay somehow. Just to account for the close of the first drawer and open of the next?

In that case we'll go ahead and keep this open and either myself or another contributor can take a look at this in the near future. Thanks!

**Comment by ollema** [comment]
> I see, maybe as a temporary solution you could introduce a small delay somehow. Just to account for the close of the first drawer and open of the next? The logic would be something like "if drawer X is open, modify the timeout before drawer Y is opened"?
> 
@endigo9740 
> In that case we'll go ahead and keep this open and either myself or another contributor can take a look at this in the near future. Thanks!

```ts
drawerStore.close();
await new Promise((r) => setTimeout(r, 200));
open_info_drawer();
```
					
You know what, not only does it work but it also looks even better than the instant switch.

But I have to say I'm a bit confused. When switching between the panes, there is no (apparent) problem. The problem only occurs when closing the "final" drawer after a switch so to speak, see attached video in the original post.

But I don't really have to understand why it works I think. I'm happy!

**Comment by endigo9740** [comment]
That's great to hear!

Unfortunately I won't really have any insight until I dig into the issue. I built this feature months ago, so my recollection is a bit fuzzy. But I am curious to know what's up as well. When we return to this I'll try to post a summary of what we found.

**Comment by Mahmoud-zino** [comment]
I would like to work on this bug

**Comment by endigo9740** [comment]
Thanks @Mahmoud-zino, this has been assigned.
