### ISSUE TITLE
CSS class .table-compact doesnt really exists

### ISSUE THREAD

**Issue by eslym** [skeletonlabs/skeleton#1680]
### Current Behavior

no effect when use `.table-compact` or `.table-comfortable`

### Expected Behavior

Based on the doc
> Apply classes `.table-compact` or `.table-comfortable` to the table for tighter or looser row spacing.

but these 2 classes does not really exists

### Steps To Reproduce

```svelte
<div class="table-container">
<table class="table-compact table-hover">
...
</table>
</div>
```

### More Information

skeleton version: 1.7.1

**Comment by Sarenor** [comment]
https://github.com/skeletonlabs/skeleton/blob/dev/packages/skeleton/src/lib/styles/elements/tables.css#L67

Which version of Skeleton are you on because I can see it here in the CSS and with the ``!py-x`` it should take precedence, too.

**Comment by Mahmoud-zino** [comment]
The classes do not appear in IntelliSense, but I can confirm they exist, and using them will change the padding on the table.

**Comment by eslym** [comment]
@Sarenor i did mention the skeleton version is 1.7.1
```
yarn why v1.22.19
[1/4] Why do we have the module "@skeletonlabs/skeleton"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@skeletonlabs/skeleton@1.7.1"
info Has been hoisted to "@skeletonlabs/skeleton"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "11.83MB"
info Disk size with unique dependencies: "22.85MB"
info Disk size with transitive dependencies: "22.85MB"
info Number of shared dependencies: 2
Done in 0.75s.
```

@Mahmoud-zino i do confirm this with inspect element before open this issue, i tried with both `yarn dev` and `yarn build && yarn preview`, both missing `.table-compact`
![image](https://github.com/skeletonlabs/skeleton/assets/3667594/53f00cfd-f8ca-4630-a118-2aabff43925b)

**Comment by eslym** [comment]
ok, my bad, i looking at the wrong element, the styles are applying to td instead of tr, sorry

**Comment by endigo9740** [comment]
@eslym glad you got it sorted, FYI Intellisense feedback should be resolved in today's new release. Let us know if the issue persists after updating. Should be version 1.8.x.
