### ISSUE TITLE
Can't scroll to the top of a modal

### ISSUE THREAD

**Issue by JakeBriscoe** [skeletonlabs/skeleton#1683]
### Current Behavior

If the modal is taller than the screen a scrollbar appears but the top 20% of the modal is inaccessible. Issue for a modal with a long form and a phone.

![Screenshot 2023-06-20 at 5 05 25 PM](https://github.com/skeletonlabs/skeleton/assets/61378276/5934f11c-80c3-4acd-8436-a1297b6061fd)

### Expected Behavior

Being able to scroll to the top

### Steps To Reproduce

1. Create a tall modal
2. Reduce screen height (phone or dev tools)

### More Information

A PR adding the scrollbar on modals — the top was visible then [https://github.com/skeletonlabs/skeleton/pull/754](https://github.com/skeletonlabs/skeleton/pull/754)

**Comment by trentpeterson** [comment]
Great timing. I ran into this exact issue today.

My current workaround, with limited testing, is the following in `app.postcss`:

```
.modal-backdrop {
  @apply overflow-y-auto;
}
.modal-transition {
  @apply min-h-full;
  @apply h-fit;
}
```

This maintains a centered modal when its height is less than the height of its parent, but allows it to extend below with scroll when it's bigger than the parent.

**Comment by endigo9740** [comment]
@Mahmoud-zino GitHub won't let me assign this to you until you leave a comment. Sorry about that, but if you could please!

**Comment by Mahmoud-zino** [comment]
@endigo9740 yeah sure, thanks
