### ISSUE TITLE
Ratings issue buttons and interactive type

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1685]
Currently we've opted for `<button>` elements to support interactive mode. However this has an issue when not using interaction in that a pointer cursor will still appear - as if the icons are clickable.

To resolve this we should modify either the template, or the styles, to remove the pointer styling.

We should add a new `interactive` prop so that we know when interactive mode is activated. Then:

- Option 1: use `<svelte:element>` to modify the element - but then we have to juggle the `type="button"`
- Option 2: use CSS to disable the pointer events

Option 1 would use more semantically correct HTML, while Option 2 is simpler.

**Comment by endigo9740** [comment]
@Mahmoud-zino let me know if you would be interested in handling this. No pressure, whoever can get to it first!

**Comment by Mahmoud-zino** [comment]
@endigo9740 I mentioned this in the PR, but I think you missed it. I will create a PR immediately 👍 .

**Comment by endigo9740** [comment]
Yep, completely missed that. That's my bad. Focus styles should remain, but should only occur when using the `interactive` mode. Thanks Mahmoud!
