### ISSUE TITLE
Stepper Event Handlers documentation section is confusing

### ISSUE THREAD

**Issue by artello73** [skeletonlabs/skeleton#1687]
### Link to the Page

https://www.skeleton.dev/components/steppers

### Describe the Issue (screenshots encouraged!)

The examples on Next, Step and Previous Event Handlers are confusing ( its applies to latest 1.8.0 version of Skeleton).

The docs are saying: 
![image](https://github.com/skeletonlabs/skeleton/assets/6637705/ba047d81-e620-4645-bc38-6b4a743997d1)

And the handler function example
`function onStepHandler(e: {step: number, state: {current: number, total: number}}): void {
	console.log('event:step', e);
}`
should be changed to: 

`function onStepHandler(e: {step: number, detail: { state: { current: number; total: number }; step: number };
	});
}`

The TIP section below: 
![image](https://github.com/skeletonlabs/skeleton/assets/6637705/d8e85e7d-6eeb-46aa-9e1d-f7ae35d1e133)

> TIP: e.state.current contains the step shown to the user after navigation, e.step contains the step where navigation occurred.

Should be changed to:
`TIP: e.detail.state.current contains the step shown to the user after navigation, e.detail.step contains the step where navigation occurred.`  in order to reflect to correct CustomEvent object type.

There is another issue with Stepper Handlers  e.detail.step within CustomEvent shows correct step number until **Back** button is pressed. If you play with Back and Next buttons you'll see that this property living its own life :) Perhaps another issue needs to be raised for this.

**Comment by Sarenor** [comment]
Since you already have the solutions, do you want to raise a PR yourself?

**Comment by artello73** [comment]
@Sarenor Yes, I can give a try. Should I raise a separate issue for **e.detail.step** behavior?

**Comment by Sarenor** [comment]
Since it's not docs-related, probably yes.
I'm looking at the step code now though and I can't see the additional detail object that you seem to expect:
https://github.com/skeletonlabs/skeleton/blob/dev/packages/skeleton/src/lib/components/Stepper/Step.svelte#L63
so we might want to slow this down a bit and investigate
