### ISSUE TITLE
Drawer: disable opacity transition on demand

### ISSUE THREAD

**Issue by Mahmoud-zino** [skeletonlabs/skeleton#1694]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Add a boolean prop to disable the opacity animation of the fly transition in the drawer.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

As discussed in Discord: https://discord.com/channels/1003691521280856084/1121757065329770657

**Comment by endigo9740** [comment]
@Mahmoud-zino if possible I'd love for this to be included as part of the transition animations PR:
https://github.com/skeletonlabs/skeleton/issues/1322

**Comment by Mahmoud-zino** [comment]
@endigo9740 I just noticed that the transitions prop is being used by both transitions (fly and fade) so disabling it will disable both, which means you can't keep the opacity of the fly transition without disabling it which doesn't make sense.

we can make the boolean prop not only disable the opacity but also the backdrop, this solves the problem but complicates things a little bit, so should I do it?

**Comment by endigo9740** [comment]
@Mahmoud-zino hmm not sure offhand. Let me get review in the transition PR and then I'll circle back
