### ISSUE TITLE
variant-ghost-error not displaying the color

### ISSUE THREAD

**Issue by adminy** [skeletonlabs/skeleton#1698]
### Current Behavior

I have an element with the following classes: "card text-center variant-ghost-error"
and its fine if I just touched the code, but after a few clicks and navigation this card looses its colour.

Note that I'm adding the -error part dynamically in code. I suspect it could just be svelte loosing context or something.

### Expected Behavior

the red color shows up all the time.

### Steps To Reproduce

```svelte
<script>
const services = {title: {tags: [
   {tag: 'name', status: 'success'},
   {tag: 'name', status: 'success'}, 
   {tag: 'name', status: 'error'},         // This color is not what you see in UI
]}}
</script>
<div class="card variant-glass-secondary p-4 space-y-4">
		<nav class="grid sm:grid-cols-2 md:grid-cols-3 grid-cols-1 gap-5">
			{#each Object.entries(services) as [title, {icon, tags, state}]}
				<div
					on:click={_ => drawerStore.open({id: title, tags})}
					on:keydown={_ => drawerStore.open({id: title, tags})}
					class={'card p-4 hover:ring-surface-500/50 cursor-pointer space-y-4 hover:scale-105 transition-transform' + (state ? ' variant-ghost-' + state : '')}>
					<span class="text-center font-bold text-2xl" data-toc-ignore>{title}</span>
					{#each tags as {tag, status}}
						<p class={`card text-center variant-ghost-${status}`}>{tag}</p>
					{/each}
				</div>
			{/each}
		</nav>
</div>
```

### More Information

I'm actually exporting the services variable and using it like so:

```svelte
<Component services={someLetVariable} />
```

**Comment by Mahmoud-zino** [comment]
Tailwind doesn't support constructing class names dynamically.
https://tailwindcss.com/docs/content-configuration#dynamic-class-names
something like this should work for you:
{state === 'success' ?  'variant-ghost-success' : 'variant-ghost-error' }

**Comment by endigo9740** [comment]
Yep as @Mahmoud-zino mentioned, it's a limitation of how Tailwind works. His solution is the technique we use for this sort of thing within our features. It should do the trick!

**Comment by endigo9740** [comment]
@adminy you're seeing a bit of a red herring - if that class is used in other parts of your application then the Tailwind compiler will bundle that class. But if your only instance of the class is dynamically generated then it will be "missed" and won't be included in the bundle, meaning it won't work. So my guess is you used that class somewhere else in your app - which is why it worked. But definitely not a safe way to go about this!

**Comment by adminy** [comment]
:o You are correct. This is strange way to optimise class usage detection I guess. I can see a lot of use cases especially for colours where users will do intensity based on some variable, but I see that they also let you tell the compiler to load certain classes anyways, which is nice.

I'm quite new to tailwind, jumped from bulma sass where classes can be extended with @extend syntax making it really difficult in some cases to programatically address a class since its only useful information for the compiler and you can't really make use of it. But here you rely on the apply feature to group classes together, not sure if it behaves the same way as the extend yet. where you can't do a querySelector for a class that's being selected. On the other hand I understand that that is bad practice for the svelte compiler. Tricky treads everywhere with everything ever so slightly loosing touch with how the dom really behaves under the hood.

**Comment by endigo9740** [comment]
Yeah, there's some odd quirks like this that aren't immediately obvious, but a lot of it is covered in their docs.

I think their primary thing is they are aiming to boil down the final stylesheet to only the classes they detect you're using. Which is a good optimization, but causes situations like this.

Per `@apply` - it's honestly kind of considered bad practice to use unless you know what you're doing. It's like a sharp knife - very useful when used properly, but easy to cut yourself on. They provide some docs on this here:
https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply

Our use of it is technically outside of their recommendation, but we're making some changes to our plugin in v2 that might help work around some of this. Still very much a work in progress, but early testing is promising.

**Comment by adminy** [comment]
Thanks for linking the page. Its good to learn about apply and I agree with all the points made why not to use it. honestly I'm quite happy with as little to no css files if at all possible. Its a fresh way of looking at designing pages. its like doing everything with shell commands instead of scripting it with python or js. you get the huge advantage of not needing to install an interpreter in the first place. same here with not having to remember which css files where has which class names.

I'm curious about the upcoming changes, please tag me whenever they land.

**Comment by endigo9740** [comment]
We actually disclose progress publicly through our roadmap here:
https://github.com/skeletonlabs/skeleton/discussions/1367
