### ISSUE TITLE
Native Svelte(without Kit) setup

### ISSUE THREAD

**Issue by tobealive** [skeletonlabs/skeleton#1701]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Native Svelte support.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

How come to request this feature?

I used Svelte without Kit only before there was a SvelteKit. Since SvelteKit's early dev stage it was it for me. And I didn't thought that just Svelte will be a thing for serious projects.
But incorporating more work with tauri, things have taught me otherwise. It's quite common to use just Svelte as there is no need for the functionalities of Kit. 
So I hope it's not too much of a stretch to add native Svelte support as I'd love to be able to use Skelton when working on Svelte/Tauri apps with as much ease as it is with SvelteKit.

**Comment by endigo9740** [comment]
Hi @tobealive, we actually had support for Vite/Svelte (Svelte without Kit) and Astro early on, but ended up dropping this. You can see our full explanation for this here:

- https://github.com/skeletonlabs/skeleton/discussions/721

The usage numbers just aren't there for this to be something realistic for us right now. We would need one or more dedicated members working only on this to keep it viable.

That said, Skeleton is still compatible with both Vite/Svelte and Astro setups. I've heard of a handful of folks using it with Tauri apps specifically. But again, we do not support this in an official capacity, which means we do not maintain documentation or address bugs and issues users might find with this directly.

Feel free to reach out on the community on here (Discussions section) and/or our Discord channels if wish though. Someone may be able to help you out.

**Comment by tobealive** [comment]
Thanks for the reply.

No worries :+1: . I'm already using Skeleton with Svelte. I just thought it would be cool to officially support it without knowing that it was already there earlier but abandoned for the reasons you mentioned, which are totally understandable.

**Comment by endigo9740** [comment]
We do hope to return support again in the future, but again it's limit of time and logistics right now!
