### ISSUE TITLE
Fix Svelte 4 a11y warnings

### ISSUE THREAD

**Issue by AdrianGonz97** [skeletonlabs/skeleton#1708]
### Current Behavior

These are denoted with a `TODO: Remove for V2` tag so that they may be easily searchable.

**Comment by Mahmoud-zino** [comment]
Since the AppRailTile has also an issue with a11y, It could be a good opportunity to refactor it and implement keyboard support.

**Comment by ollema** [comment]
Just wanted to mention that I believe that one of the warnings was not silenced:
```
7:06:18 PM [vite-plugin-svelte] /node_modules/.pnpm/@skeletonlabs+skeleton@1.9.0_svelte@4.0.3/node_modules/@skeletonlabs/skeleton/dist/components/Ratings/Ratings.svelte:29:3 A11y: <svelte:element> with click handler must have an ARIA role
```
Maybe this was known?

**Comment by Mahmoud-zino** [comment]
I would like to work on this issue 🙏.

**Comment by endigo9740** [comment]
@Mahmoud-zino I might have you help me with one, but I really need to be hands on for anything a11y related. There's a lot of rules and we've gotta make sure changes are implemented exactly as need be. In this case I know we'll be refactoring a number of components, but I don't know the specifics needed. Each will be determined on a case-by-case basis - even though we might end up making similar changes in multiple places.

I'll try to ping you when I circle back to this though. Thanks!

**Comment by endigo9740** [comment]
Making a quick note here regarding these changes in regards to the Tab component specifically:

- https://github.com/skeletonlabs/skeleton/issues/1752#issuecomment-1712090347

**Comment by endigo9740** [comment]
I'm closing this as we will likely not have time to fix this in v2, and v3 will contain rewrites as we port to Svelte 5. Most, if not all, of these issues should be handled along the way. This means this issue is no longer relevant to active tasks.
