### ISSUE TITLE
Light Switch with OS Preference not work with 'csp' enabled

### ISSUE THREAD

**Issue by xenogew** [skeletonlabs/skeleton#1710]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

On https://www.skeleton.dev/utilities/lightswitches under "OS Preference".

Your suggestion codes are rendered to be inline JavaScript when page is loaded, then it harms the CSP security.

I would like to ask for a feature that can auto detect from OS/system but to be good with CSP enabled.

### What type of pull request would this be?

None

### Provide relevant links or additional information.

https://kit.svelte.dev/docs/configuration#csp

**Comment by Sarenor** [comment]
I think we had a similar discussion already, but I don't think that we came up with a satisfying solution. If you've got suggestions, we'd be very happy!

**Comment by endigo9740** [comment]
The OS preference solution is a temporary one until we can revisit some of the requirements of our Tailwind plugin described here:
https://github.com/skeletonlabs/skeleton/discussions/951

Essentially there is no simple solution here, but this is on my mind and we will find a solution that works when we can.

**Comment by xenogew** [comment]
I did a workaround with load your script function into `$lib/darkModeHelper.ts` then call to `autoModeWatcher()` function under `+layout.ts` on `load()` function.

But hope you can find a better solution for this soon. Thanks for visit my Feature Request issue.
