### ISSUE TITLE
"Custom content" toasts

### ISSUE THREAD

**Issue by tizu69** [skeletonlabs/skeleton#1711]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Toasts are cool, but I personally like having loading indicators in toasts.
The current system does not allow something like these.

![image](https://github.com/skeletonlabs/skeleton/assets/60812901/eee5bb52-d246-4e71-b516-1ba8b31ce052)

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

Probably something similar to how Modals work.

Chakra also has these [component toasts](https://chakra-ui.com/docs/components/toast/usage#custom-component).

**Comment by Mahmoud-zino** [comment]
This was discussed here lately: https://github.com/skeletonlabs/skeleton/issues/1311#issuecomment-1587863963
I still think this is a good idea for the future of toasts, but also agree with Chris on holding this for the moment.
