### ISSUE TITLE
Toast zIndex sets wrong class name

### ISSUE THREAD

**Issue by danielfogt** [skeletonlabs/skeleton#1714]
### Current Behavior

After using default Toast
```svelte
<Toast />
```
classes look in the following way:
```html
<div class="[...] z-[888]"></div>
```

but when Toast is used with custom `zIndex` it gives me wrong class name. E.g.:
```svelte
<Toast zIndex=900 />
```
```html
<div class="[...] 900"></div>
```

<hr> 

The only workaround that works for me is:
```svelte
<Toast zIndex=whatever123 class="z-[900]"/>
```
but classes look now in the following way
```html
<div class="[...] whatever123 z-[900]"></div>
```

### Expected Behavior

```svelte
<Toast zIndex=900 />
```
```html
<div class="[...] z-[900]"></div>
```

### Steps To Reproduce

See "Current Behavior" above

**Comment by danielfogt** [comment]
It turned out it works fine though. Just need to use
```svelte
<Toast zIndex="z-[900]" />
```
which is what I expected.

It confused me that in the modal I set ealier
```svelte
<Modal zIndex=999/>
```
and I got
```html
<div class="modal [...] z-[999]">
```
but it's a default value and I have must missed that. My bad

**Comment by Sarenor** [comment]
You always need to provide the full class name so that the tailwind compiler can pick it up and include it in the final CSS bundle.
