### ISSUE TITLE
Background hover tokens are not working as expected

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1718]
### Current Behavior

I've noted the `.bg-hover-primary-token` now shows a `surface` color tone. We should test secondary, tertiary, etc as well just in case. We should review how these are being inserted into the Tailwind plugin and ensure all is well.

@AdrianGonz97 pining you as an FYI.

### Expected Behavior

The `primary` version should have a semi-transparent green tone when using the Skeleton theme. However this is coming through as a neutral surface tone instead.

### Steps To Reproduce

View on any page that uses these styles, including our doc site navigation or the List element styles:
https://www.skeleton.dev/elements/lists

**Comment by AdrianGonz97** [comment]
Went digging through our past PRs to see where the first occurrence for this came from and I think it may have been this one: https://github.com/skeletonlabs/skeleton/pull/1577 which aimed to resolve this issue: https://github.com/skeletonlabs/skeleton/issues/1574.

**Comment by Mahmoud-zino** [comment]
ops, my fault 😅, let me know if I can help correct it, and sorry for the inconvenience.

**Comment by endigo9740** [comment]
@Mahmoud-zino if you're looking for an issue this might be one to jump on. I believe this is still in effect.
