### ISSUE TITLE
[Docs] Allowed Options seems not working

### ISSUE THREAD

**Issue by mmailaender** [skeletonlabs/skeleton#1723]
### Current Behavior

Although the allowed List is defined `[neapolitan, pineapple, peach]` options like `Vanilla` and `Chocolate` are also displayed
![image](https://github.com/skeletonlabs/skeleton/assets/87228994/d967b576-81ef-473b-a2fa-0e104a422db4)

### Expected Behavior

Only `neapolitan, pineapple, and peach` is displayed

### Link to Reproduction / Stackblitz

https://www.skeleton.dev/components/autocomplete#allowed-options

**Comment by Sarenor** [comment]
Neapolitan Ice Cream is a Mixture out of 3 ice creams: Chocolate, Strawberry and Vanilla.
https://github.com/skeletonlabs/skeleton/blob/master/sites/skeleton.dev/src/routes/(inner)/components/autocomplete/+page.svelte#L44
It's intended to show how the additional tags you can pass in optionally work and is intended behavior afaik.

**Comment by mmailaender** [comment]
I can't see your definition of Neapolitan (_Neapolitan Ice Cream is a Mixture out of 3 ice creams: Chocolate, Strawberry and Vanilla._) in the visual docs:
![image](https://github.com/skeletonlabs/skeleton/assets/87228994/985d5f6f-6cd8-4909-ab6e-60cd4d6f29df)
![image](https://github.com/skeletonlabs/skeleton/assets/87228994/f202695c-4be4-402e-9e82-0d0f8d1e93d9)
Neapolitan is also a dedicated point on the example list, in addition to chocolate, strawberry, and vanilla.

---

I understand `allowed options` as a white list. So only the items that are given in the white list array are displayed.

**The Allowed Options in the docs are defined as**:
- neapolitan 
- pineapple
- peach

The Full List is:
- Vanilla
- Chocolate
- Strawberry
- Neapolitan
- Pineapple
- Peach

So I would expect the following list:
- ~~Vanilla~~
- ~~Chocolate~~
- ~~Strawberry~~
- **Neapolitan**
- **Pineapple**
- **Peach**

But that's different from the current case. So I still think it's a bug in the docs. 🤔 
https://www.skeleton.dev/components/autocomplete#allowed-options
@Sarenor

**Comment by Sarenor** [comment]
I think you're right actually and I confused it with another part of the autocomplete docs that already had multiple issues.
You might even have found an issue with the autocomplete in general, it seems like the Allowlist isn't working as intended, at least in my local testing!

**Comment by Sarenor** [comment]
Changing that back didn't fix it for me, sadly.
