### ISSUE TITLE
Reinstantation of ``btn-base``

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#1724]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently the ``btn-base`` class from before february is automatically applied to the ``btn`` class, although this is nice and less boilerplate it doesn't account for this use case:
```html
<button class="btn btn-sm lg:btn-???">Button</button>
```
In the example you want a small button that gets bigger as the media queries get bigger but this currently isn't possible without skipping over the default btn size entirely.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Note this has been updated as part of the v2 branch, which is slated to be the next release.
