### ISSUE TITLE
Feature: Add rewind (or restart) button to Stepper component

### ISSUE THREAD

**Issue by artello73** [skeletonlabs/skeleton#1733]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Stepper Component has a great functionality, but missing a Rewind or Restart functionality to start everything from the scratch. 

![image](https://github.com/skeletonlabs/skeleton/assets/6637705/27da194d-1e63-4ef8-b371-23550a777d42)

The button should be locked on first step and unlockeв at further steps.

![image](https://github.com/skeletonlabs/skeleton/assets/6637705/0de04aff-97dc-4fff-82cb-58547b52d56b)

On clik it should fire up corresponding  on:rewind  event

May be it would need a own visibility flag to hide/unhide button.

### What type of pull request would this be?

Enhancement

**Comment by artello73** [comment]
I could work on a PR if maintainers consider this feature interesting.

**Comment by Sarenor** [comment]
There's a couple of Issues for the stepper currently, Chris might want to collect them into one.
I'd also like it if the stepper could be assigned an active step programmatically while it's rendered and not just during initial render.

**Comment by endigo9740** [comment]
As Sarenor mentioned, folks have been asking for several changes lately. Let me evaluate how all these will work together and then we'll move forward.

**Comment by artello73** [comment]
> As Sarenor mentioned, folks have been asking for several changes lately. Let me evaluate how all these will work together and then we'll move forward.

Sure, thing. Will wait then.

**Comment by endigo9740** [comment]
This issue should now be considered consolidated here: https://github.com/skeletonlabs/skeleton/issues/1780
