### ISSUE TITLE
Material floating Input

### ISSUE THREAD

**Issue by cycle4passion** [skeletonlabs/skeleton#1734]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I need to implement the [Material Floating Label](https://material-components.github.io/material-components-web-catalog/#/component/text-field) in skeleton ui. I really like the html first approach of skeleton ui (ie no Input components just native input tags without props galore). I though great, Ill just do it the same as the 'variant-form-material' had been implemented. Unfortunately, I quickly realized that this would require (I think) a component as the label size has so closely linked to the input. 

Is this a one off thing that I should do for myself or is it worthy of another skelton ui component (I'm guessing -no)? If not, is it worthy of a section in the docs to help the next person? Or maybe is there a plan for a section of "curated" or "unofficial" skeleton ui components, etc?

### What type of pull request would this be?

New Feature

**Comment by Sarenor** [comment]
Lots of questions.
> Is this a one off thing that I should do for myself or is it worthy of another skelton ui component (I'm guessing -no)?
Yup, probably not, although I'm not the final arbiter on that
>  If not, is it worthy of a section in the docs to help the next person?
For how to implement a floating-label specifically? Probably not, but I might be wrong about that.
> Or maybe is there a plan for a section of "curated" or "unofficial" skeleton ui components, etc?
Most definitely yes, that's how Chris & [Skeletonlabs ](https://www.skeletonlabs.co/services) plan to make money (partially, at least). You can check this weeks release notes for a sneak peak: https://github.com/skeletonlabs/skeleton/discussions/1716
No Material Component/theme yet, but that may change depending on demand.

**Comment by cycle4passion** [comment]
Thanks for the reply. I agree.  It's not so much I'm trying to recreate material ui but I will need a tremendous number of inputs on the same form and have to limit impact of label size. One off it is. Thanks. Maybe I get creative and make a combined shrinking out of sight label on focus.

**Comment by cycle4passion** [comment]
Thanks

**Comment by endigo9740** [comment]
Floating material labels are one of those signature features of Material UI. There's honestly a dozen of UI libraries out there that include floating labels and it's a very opinionated design. Skeleton is not Material Design and we have no intention for it to become that. The Material-like input variants are about the closest we'll likely ever get:

https://www.skeleton.dev/elements/forms#variants

I understand your UX concerns, but unfortunately I think this one is going to fall out of scope of something Skeleton supports directly. If you need something like this, it will likely be best to recreate in your own project.
