### ISSUE TITLE
Skeleton - Custom Transitions

### ISSUE THREAD

**Issue by Mahmoud-zino** [skeletonlabs/skeleton#1738]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

After v2 we want to introduce custom-made JS & CSS transitions.

These transitions could be used by our components when needed and users could use most of them easily with the help of the new dynamic-transitions feature #1533.

Please comment below, which custom transition you want to see in Skeleton in the future.
### Transitions
1. Swoop - Could be used on Toasts 🍞.
2. Flash - Could be used on Table-of-Contents headers 🔗.

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

Inspiration animation site suggested by Chris: https://animate.style/

**Comment by endigo9740** [comment]
Duplicate: https://github.com/skeletonlabs/skeleton/issues/1630
