### ISSUE TITLE
Table of Contents component does not support Chinese

### ISSUE THREAD

**Issue by theseazhang** [skeletonlabs/skeleton#1741]
### Current Behavior

> The component will scan the target region and query all matching headings. If a heading has an ID set, that will be used as the scroll target, otherwise an ID will be auto-generated and assigned.

If the title is in Chinese and no id is specified, the automatic generation will fail, and the display and scroll positioning of this component will be abnormal. Simple solution, should automatically assign a random character id.

**Comment by endigo9740** [comment]
Given the refactor will handle this I'll go ahead and close this out as a duplicate. Thanks for reporting though!
