### ISSUE TITLE
Forms : Material design variants do not build correctly

### ISSUE THREAD

**Issue by acekavi** [skeletonlabs/skeleton#1742]
### Current Behavior

There seems to be an issue with form inputs while building with `variant-form-material`
Everything works fine in the dev environment. But when I build the project all the material variant from inputs like text, password, etc.. seems to revert back to the standard variant.

Note: Inputs like text areas and input groups render fine.

### More Information

`<input
  class="input variant-form-material leading-5"
  title="Username or Email"
  name="username"
  type="text"
  placeholder="ghost"
  autocomplete="off"
/>`

A sample input that gets rendered incorrectly on the build.

I love this project and love to see this bug fixed if can. Thanks for making this excellent library <3

**Comment by Mahmoud-zino** [comment]
@acekavi 
I have just tested this on a fresh project and it is working as expected, the input you provided is rendering correctly for me.
Can you please provide more info on your setup and build settings so I can reproduce it?

**Comment by endigo9740** [comment]
No response and no reproduction provided, so closing this out due to inactivity. Happy to reopen if these conditions are met.
