### ISSUE TITLE
text & fill color breaks with thick border

### ISSUE THREAD

**Issue by bartduisters** [skeletonlabs/skeleton#1750]
### Link to the Page

https://www.skeleton.dev/docs/generator

### Describe the Issue (screenshots encouraged!)

The icon becomes overlapped by the border.

![Screenshot 2023-07-14 at 15 54 35](https://github.com/skeletonlabs/skeleton/assets/43420049/8ba21cfc-fa99-4db3-b103-169b19364760)

**Comment by endigo9740** [comment]
Hey @bartduisters thanks for bringing this to my attention. We have some major updates planned for the theme generator in the near future. I've gone ahead and noted this issue there and we'll address this then. Thanks!

https://github.com/skeletonlabs/skeleton/issues/1142
