### ISSUE TITLE
Autocomplete component is not working inside if block.

### ISSUE THREAD

**Issue by tastycrayon** [skeletonlabs/skeleton#1751]
#### Code below does not work
Nothing prints on the console when I click on the list items. The `on:selection and on:click` event never fires.
I have a search form, which turn `isFocused` to true when focused, and the `<Autocomplete/>` is visible to the screen. I click on the search item from the `<Autocomplete/>` list item, nothing gets printed on the screen.
```html
	{#if isFocused}
		<div class="absolute top-100 left-0 w-full p-4">
			<div class="card w-full max-w-sm max-h-48 p-4 overflow-y-auto" tabindex="-1">
				<Autocomplete
					bind:input={inputDemo}
					options={flavorOptions}
					on:selection={() => console.log('hello')}
					on:click={() => console.log('hello')}
					class="text-sm"
				/>
			</div>
		</div>
	{/if}
```
![image](https://github.com/skeletonlabs/skeleton/assets/37541747/50b7a19d-e97b-44e3-9ce8-74dc0c28898f)
As you can see, the console is empty.   
   
   
#### However, it works fine when `not inside an if block`
Now that it is not inside an {#if} block, it works fine.
```html
		<div class="absolute top-100 left-0 w-full p-4">
			<div class="card w-full max-w-sm max-h-48 p-4 overflow-y-auto" tabindex="-1">
				<Autocomplete
					bind:input={inputDemo}
					options={flavorOptions}
					on:selection={() => console.log('hello')}
					on:click={() => console.log('hello')}
					class="text-sm"
				/>
			</div>
		</div>
```
![image](https://github.com/skeletonlabs/skeleton/assets/37541747/5aec26b8-737f-4346-81b0-b9273ebde56d)
As you can see, without conditional rendering, `hello` gets printed on console.

### Expected Behavior

```js
on:selection={() => console.log('hello')}
on:click={() => console.log('hello')}
```
should print hello or even some error, but nothing happens.
the other functionalities of `<Autocomplete />` eg. search however works fine.

### Steps To Reproduce

```html 
<script>
	let inputDemo = '';

const flavorOptions: AutocompleteOption[] = [
	{ label: 'Vanilla', value: 'vanilla', keywords: 'plain, basic', meta: { healthy: false } },
	{ label: 'Chocolate', value: 'chocolate', keywords: 'dark, white', meta: { healthy: false } },
	{ label: 'Strawberry', value: 'strawberry', keywords: 'fruit', meta: { healthy: true } },
];
	let isFocused = false;
	const onFocus = () => (isFocused = true);
	const onBlur = () => (isFocused = false);
</script>
<div>
	<input
		bind:value={inputDemo}
		on:focus={onFocus}
		on:blur={onBlur}
		class="input"
		type="search"
		placeholder="Search..."
	/>
	{#if isFocused}
		<Autocomplete
			bind:input={inputDemo}
			options={flavorOptions}
			on:selection={() => console.log('hello')}
			on:click={() => console.log('hello')}
			class="text-sm"
		/>
	{/if}
</div>
```
Just need to render it conditionally.

### More Information

Component: https://www.skeleton.dev/components/autocomplete
This is the full source code: https://github.com/tastycrayon/pb-svelte-chatapp/blob/main/client/src/components/sidebar.svelte

**Comment by LeHyperion** [comment]
I have the same problem. Any suggestion on how to resolve this issue would be helpful. Thanks

**Comment by tastycrayon** [comment]
> I have the same problem. Any suggestion on how to resolve this issue would be helpful. Thanks

I have found the problem.

```html
<script>
	let isFocused = false;
	const onBlur = () => {
		isFocused = false; // <--- this is the problem
	};
</script>

<input
	on:blur={onBlur}
	type="search"
/>
{#if isFocused}
	<Autocomplete
		on:selection={() => console.log('hello')}
	/>
{/if}
```

Here, the moment you click on anywhere outside the input box, `on:blur` fires off, turning `isFocused = false`
The problem is `on:selection={() => console.log('hello')}` does not get the chance to fire cause `<Autocomplete/>` is hidden the moment `isFocused = false` happens.

#### Solution 1:

Do not turn `isFocused = false` immediately. Give some time for `on:selection={() => console.log('hello')}` to fire.
```js
let timer = 0;
const onBlur = () => {
	timer = setTimeout(() => {
		isFocused = false;
	}, 350);
};
```

Note: If you do use this approach, don't forget to clear the timer.
```js
onDestroy(() => {
	if (timer) clearTimeout(timer);
	timer = 0;
});
```

#### Solution 2:
Do not use `on:blur`, use `on:selection` to turn `isFocused = false`. Example below.
```js
{#if isFocused}
	<Autocomplete
		on:selection={(event) => {
			console.log('hello');
			isFocused = false;
		}}
	/>
{/if}
```

### Conclusion: 
`on:selection` and `on:click` might not have the chance to fire if it is inside an `if block`. Mentioning it in the `Autocomplete` component's `docs` will be quite helpful. May be just mention solution 2 at the end. 😁

**Comment by onim-at** [comment]
Hello, if it can help, a similar behavior can be obtained with the popup utility as described in the Popup section of the [Autocomplete docs](https://www.skeleton.dev/components/autocomplete)

**Comment by tastycrayon** [comment]
> Hello, if it can help, a similar behavior can be obtained with the popup utility as described in the Popup section of the [Autocomplete docs](https://www.skeleton.dev/components/autocomplete)

Popup uses [@floating-ui/dom](https://www.skeleton.dev/utilities/popups), which I did not want to use because my app barely has any popups. Modal also helped fill the gap.
