### ISSUE TITLE
Confirm Modal should submit on `Enter` key pressed

### ISSUE THREAD

**Issue by ibilux** [skeletonlabs/skeleton#1757]
Confirm Modal should submit true value on `Enter` key pressed (like closing on `Escape` key pressed).
We should change button type from `type="button"` to `type="submit"`.
Or use HTML Form Element `<form>`.

https://github.com/skeletonlabs/skeleton/blob/fa2af91a23e37a92ddf820c578ffaab135766a99/packages/skeleton/src/lib/utilities/Modal/Modal.svelte#L243C8-L243C8

**Comment by endigo9740** [comment]
@ibilux can you link to the source on this please. We follow the ARIA APG guidelines on these sorts of issues to meet a11y concerns:
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/

It may be in there, but they cover a lot so just let me know where specifically.

**Comment by riziles** [comment]
@ibilux , I found a good discussion here: https://ux.stackexchange.com/questions/130704/enter-key-action-on-modal-dialogs 

They assert that the enter key should do something, but if "submit" = fire nukes, than the default should probably be "cancel".

**Comment by endigo9740** [comment]
That generally meets my expectations as well, but some of this may be a limitation for our focus trap implementation. What I'm leaning towards is some ways for users to opt into and configuration this behavior in some fashion. Rather than just hardcoded on-by-default. It may not meet everyone's expectations.

**Comment by endigo9740** [comment]
Taking a deeper look at this - one option we have here is the `autofocus` attribute. The MDN docs even point out this specific use case for the Dialog element:

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus

> The autofocus global attribute is a Boolean attribute indicating that an element should be focused on page load, or when the <dialog> that it is part of is displayed.

This doesn't introduce the complexity or lead the possibility of side effects that a form and button type can lead to. However, SvelteKit provides warning against this:

![Screenshot 2023-07-19 at 11 11 48 AM](https://github.com/skeletonlabs/skeleton/assets/1509726/b5a8a5df-8050-4ca4-894b-ad764190d35c)

In this case I think they are technically correct, this should be used sparingly, but for our use case specifically I think this is the correct option. If so, we'll need to implement this and append a one-off comment to disable this warning like so:

```html
<!-- svelte-ignore a11y-autofocus -->
<button type="button" class="btn {buttonPositive}" on:click={onConfirm} autofocus>{buttonTextConfirm}</button>
```

@ibilux @riziles thoughts?

**Comment by ibilux** [comment]
@endigo9740 the `autofocus` attribute doesn't work well in SvelteKit, in some cases it won't work, or it will work only for the first time you call/import the component.
I'm using another working solution using the 'use directive' :
```svelte
<script lang="ts">
  import { tick } from "svelte";
  async function autofocus(node: HTMLElement){
    await tick();
    node.focus();
  }
</script>

<button type="button" class="btn {buttonPositive}" on:click={onConfirm} use:autofocus>
    {buttonTextConfirm}
</button>
```

> However, we should likely take the UX concerns into play here - that the positive action may not always be the desired focus element. In that case we will need a prop like export let autofocus = 'positive' to adjust focus, but only allow one option at a time.

You are right about the UX.

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2357
