### ISSUE TITLE
Custom class for ListBoxItem

### ISSUE THREAD

**Issue by Schroedi** [skeletonlabs/skeleton#1761]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I try to truncate text in a listbox with ellipsis (...).
- Adding `class="truncate"` to the `<ListBoxItem>` truncates the content but misses the ellipsis.
- Adding truncate to a span inside the `ListBoxItem` results in no truncation at all.
- Adding truncate to the `.listbox-label-content` class globally works but is not desirable.

Maybe there could be a property on the `<ListBoxItem>` to pass custom classes to the div that wraps the slot?

### What type of pull request would this be?

New Feature

### Discussion on Discord
https://discord.com/channels/1003691521280856084/1130867117638549624

### Screenshots of all three mentioned variants:
![SCR-20230718-moe](https://github.com/skeletonlabs/skeleton/assets/97124/c6f1bf27-d4d4-4664-9606-1d1c7dc9089f)
![SCR-20230718-l8x](https://github.com/skeletonlabs/skeleton/assets/97124/114322a3-f45d-457a-a797-8723d9481a8e)
![SCR-20230718-l8k](https://github.com/skeletonlabs/skeleton/assets/97124/42bfefd6-3765-4543-be71-4bba6eb5c8ca)

### Testing project
https://stackblitz.com/edit/skeletonlabs-repl-u7x3e8?file=src%2Froutes%2F%2Bpage.svelte

### A workaround provided by Dominik via Discord
```ts
<ListBoxItem bind:group={currA} name="a" value={item} class="[&>.listbox-label>.listbox-label-content]:truncate">
    span >{item}</span>
</ListBoxItem>
```

**Comment by Mahmoud-zino** [comment]
We should add region props to the list box to cover such use cases.
@endigo9740 If you don't have other plans I would be happy to jump in and update the component.

**Comment by endigo9740** [comment]
@Mahmoud-zino agreed - this was an early component that pre-dated the introduction of region props, but I think this makes total sense. Go for it!
