### ISSUE TITLE
Review GDPR friendly alternative to Google Fonts

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1770]
Let's take a look at: https://fonts.coollabs.io/

_Originally posted by @daanschenkel in https://github.com/skeletonlabs/skeleton/issues/1161#issuecomment-1640811590_

**Comment by Sarenor** [comment]
I'd love to have an alternative for Google Fonts, I'm afraid that from an initial overview, coollabs.io is also hosted and an online API.

Therefore it's still a third party where the users browser would request the fonts, and therefore a third party that would get the Users IP (which is protected data) without the users consent.

At least that's what I've gathered with a quick read.

**Comment by daanschenkel** [comment]
> I'd love to have an alternative for Google Fonts, I'm afraid that from an initial overview, coollabs.io is also hosted and an online API.
> 
> Therefore it's still a third party where the users browser would request the fonts, and therefore a third party that would get the Users IP (which is protected data) without the users consent.
> 
> At least that's what I've gathered with a quick read.

they say they dont store anything, idk if you can believe that tho

**Comment by endigo9740** [comment]
> idk if you can believe that tho

That's inherently the problem, it relies on trust. When it comes to GDPR and liability that's not enough.

Given this knowledge I'm going to go ahead an close this out.

**Comment by Sarenor** [comment]
> they say they dont store anything, idk if you can believe that tho

Afaik, that doesn't matter. They received it and could have stored it. And just for technical reasons of sending back the data they have to store the IP address for a couple of seconds.
GDPR is... Not good with technical realities like that, at least as far as I know.
I'm not a lawyer though, just a Software Engineer trying not to get sued.
