### ISSUE TITLE
Treeselect with single or multi-select support

### ISSUE THREAD

**Issue by jmonroe44** [skeletonlabs/skeleton#1773]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Recently saw the Tree View was excited because I thought it supported selection as well, sort of like Vue Treeselect. Essentially, it's the same format but allows you to select the options listed as children. The reference link provided below has more details and demos to see.

Example: 
![image](https://github.com/skeletonlabs/skeleton/assets/65633244/888e2ced-f21a-47ab-83e2-77a9093827bb)

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

Reference: https://vue-treeselect.js.org/

**Comment by endigo9740** [comment]
Pinging @Mahmoud-zino (Chad_GPT) in case he wants to take a look at this.

As a temporary solution I've suggested implementing the inputs yourself as part of the `lead` slot position in each TreeViewItem. But a more built-in solution might be nice here.

**Comment by Mahmoud-zino** [comment]
Sure, I expected the selection to be the next step for the tree view, I will jump in as soon as possible 👍
