### ISSUE TITLE
Paginator text "<x> of <n>"

### ISSUE THREAD

**Issue by g012** [skeletonlabs/skeleton#1776]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

In Paginator, we see "5-10 of 20" for instance. The text 'of' in this sentence is hardcoded. It should be localizable like the amount text, or use a '/' instead of 'of' to avoid the issue : "5-10 / 20".

### What type of pull request would this be?

None

**Comment by SebasF1349** [comment]
This should be easy to add, just don't know the best name for the prop. `labelOf`? Btw, I like a new prop more than a hardcoded `/`.

**Comment by endigo9740** [comment]
I'd recommend `seperatorLabel`or `seperatorText`, whatever is closest to our most common naming for text inserted via prop.
