### ISSUE TITLE
Theme Generator crashing site

### ISSUE THREAD

**Issue by salfel** [skeletonlabs/skeleton#1777]
### Current Behavior

I just wanted to create a theme myself, when the site crashed and the buttons didn't work anymore. 
When i enabled the theme preview everything worked fine, but as I disabled theme preview, the whole site crashed which means that the buttons didnt work anymore and also everything else besides links.
Even refreshing the site then doesnt work, so i have to go to the home page and then go back to theme generator, 
tried it both with chrome and opera but the issue persisted on both

### Steps To Reproduce

1. Open Skeleton site
2. go to theme generator
3. click the preview theme button twice, whole site should crash

OS windows 11

**Comment by endigo9740** [comment]
Hey @salfel we pushed out a change in yesterday's release related to the theme generator trying to pin down another bug. Can you try clearing local storage for the site in your browser and testing again? That should resolve the issue for you.

**Comment by endigo9740** [comment]
@salfel quick update - we've had another user report the issue on Discord and I've confirmed it as well. This appears to be a bug only happening in the deployed production app, so we missed it when testing locally.

It's likely related to this PR:
https://github.com/skeletonlabs/skeleton/pull/1745/files

@Mahmoud-zino and I are reviewing now and will aim to get a fix out asap.

**Comment by endigo9740** [comment]
@salfel we've seemingly tracked this down to a bad deployment due to a bug on Vercel's end yesterday:
https://www.vercel-status.com/incidents/5c0cpdhr3n4p

We've redeployed and this appears to be resolved for us. Please confirm and we'll close out this ticket if so.
