### ISSUE TITLE
Allow more PopupSettings events

### ISSUE THREAD

**Issue by royce-mathew** [skeletonlabs/skeleton#1778]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently, the popup setting is a bit limited in the case of what events it offers. Would it be possible to add a event to PopupSettings such that the popup stays visible when the user hovers over the popup. 

This can open up opportunities like creating a topbar navmenu where when you hover over one of the elements, a popup is shown with the subroutes. You wouldn't really want the popup to go away when you try hovering over it and clicking one of the subroutes. You would instead, want it to go away when the user hovers away from the popup and the element that triggered the popup.

### What type of pull request would this be?

New Feature

**Comment by Sarenor** [comment]
We've currently put a hold on new features for the popups.
After v2 there'll be a standalone skeleton-popup library that's going to improve ease of use and setup.
Should also allow for more options and configurability.

**Comment by LickABrick** [comment]
Was looking for these options as well (the one where the popup stays open when hovered).
@royce-mathew if you find a way to have the popup stay visible when hovered please let me know!

**Comment by endigo9740** [comment]
> this is mainly just a simple workaround until we actually reach Skeleton V3

Just to clarify, the popup update will be between v2 and v3. We have a plan for introducing the new standalone features alongside the core features between major releases so folks can slowly migrate over. Then when v3 drops it'll remove the original feature from the core library - that'll be the breaking change it implements. Just so everyone is on the same page!

**Comment by endigo9740** [comment]
FYI, as we begin prepping for the new standalone popup package, we're consolidating all known issues for popups into this new thread:

- https://github.com/skeletonlabs/skeleton/issues/1916

Your post will now be closed, but has been referenced in the post linked above. Please note that by doing this, your request is being folded into this larger effort. Please feel free to monitor the linked issue if you wish to track progress on this going forward.
