### ISSUE TITLE
Cookbook: Stepper

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1780]
> [!WARNING] 
> This issue is a work in progress.

This will act as a hub to centralize this information.

## Maintainer Requests

The following requests are coming straight from the Skeleton team. These are highly likely be implemented:

> [!NOTE] 
> We're aiming to retire the Stepper component in Skeleton v3 in favor of a [Cookbook](https://next.skeleton.dev/docs/resources/cookbook) recipe that teaches the core concepts for building a custom and unique stepper and/or multi-part form. We've not been satisfied with the reception of the feature in prior versions. We need a solution that's more flexible to the variety of use cases users have in mind for this feature.

<details>
	<summary>Show addition notes</summary>
	
- Each step should contribute to a multi-part form (ex: onboarding)
- Can navigate forward/back by clicking the numeric steps
- Better way to set a uniform height on the contents of each step
- More control over the button options provide per each step
- Programmatically control the stepper state (read: set current step)
</details>

## Community Requests

The following requests have come from the community and are under consideration:
 
- https://github.com/skeletonlabs/skeleton/issues/1952
- https://github.com/skeletonlabs/skeleton/issues/1733
- https://github.com/skeletonlabs/skeleton/issues/1717
- https://github.com/skeletonlabs/skeleton/issues/1652
- https://github.com/skeletonlabs/skeleton/issues/1644
- https://github.com/skeletonlabs/skeleton/issues/1521
- https://github.com/skeletonlabs/skeleton/issues/1795
- https://github.com/skeletonlabs/skeleton/pull/1712
- https://github.com/skeletonlabs/skeleton/issues/2026
- https://github.com/skeletonlabs/skeleton/issues/2146

## Bugs and Issues

* https://github.com/skeletonlabs/skeleton/issues/2457

## Feedback

If you have additional updates or requests for this feature, please do so in the comments section below.

**Comment by Josh-Nicholson** [comment]
It would be incredibly helpful if the complete button had more options, or if the stepper component allowed you to provide a custom complete button.

This would enable functionality such as disabling the button or adding a spinner, which would be particularly useful when the stepper component is used with a form. The complete button could then notify the user that something is happening in the background and that they cannot press the button until the operation is completed.

Currently I'm only able to do the following:
``` svelte
<Stepper
  buttonCompleteType="submit"
  buttonCompleteLabel={isSubmitting ? 'Creating Case...' : 'Create Case'}
  buttonComplete={isSubmitting ? 'btn variant-filled-warning' : 'btn variant-filled-primary'}
>
```

Where ideally I could do something like this
``` svelte
<Stepper buttonComplete={<CustomButton {isSubmitting} />} >
```

**Comment by endigo9740** [comment]
Thanks for the add Josh.

Just so everyone is aware, the direction I'm leaning on is to break this feature up to be a looser set of UI feature that allow users to construct this in any manner they see fit. We're never going to make a single component that checks off every wish list feature folks might have. But we can provide the specialized Lego pieces that allows folks to construct this as they see fit. This may even move from a component to a Tailwind > Blocks feature similar tot the Chat/Prompt interface. Much looser, but much more flexible.

**Comment by chazzmoney** [comment]
I'd also like to call out a way to intercept events in a handler. Like if you have a handler on:next={nextHandler} then in nextHandler you could call event.preventDefault() to prevent the next from occurring.

**Comment by zakariaboualaid** [comment]
Is there a clean way to move to the next step programmatically? I want to process some data before deciding whether I move the user to the next step or not.

**Comment by BlueFrog130** [comment]
I am very interested in an update to the stepper component. Trying to leverage the form validation API has been difficult with the current implementation.

**Comment by hugotox** [comment]
Any advice how to prevent the initial load "jump" of the content element? This is happening because the steps are rendered client side only, and even when used on not SEO pages, it is a bad UX to move things on load.

**Comment by djdembeck** [comment]
Would like to add clickable steps. They were added in 
https://github.com/skeletonlabs/skeleton/pull/752
but removed by
https://github.com/skeletonlabs/skeleton/commit/9c399576b871b10021a2d4f178b75c46279feb1a

**Comment by somadevmcc** [comment]
Hello, I would like to add a "reset" option for the stepper to return it to the first step.

**Comment by Darkskald** [comment]
> Would like to add clickable steps. They were added in #752 but removed by [9c39957](https://github.com/skeletonlabs/skeleton/commit/9c399576b871b10021a2d4f178b75c46279feb1a)

any progess in this? That would be an amazing feature!

**Comment by Sarenor** [comment]
@Darkskald it's going to be a part of the next Skeleton major version that's currently in early active development. So no progress or ETA for this specific feature, but we're getting there

**Comment by pixelrebel** [comment]
I'm here because of the deprecation update in the docs.  What does this mean for projects using the stepper today?  Does this mean that stepper will not be available in the initial v3 release?

**Comment by endigo9740** [comment]
@pixelrebel we've provide that information on the page itself for each feature. See the red alert here:
https://www.skeleton.dev/components/steppers

> This feature is being phased out as we transition to [Skeleton v3](https://github.com/skeletonlabs/skeleton/discussions/2375). This will remain functional for all 2.x releases. Expect a dedicated v3 alternative as soon as possible.
