### ISSUE TITLE
Popup getting stuck when the button that is defined on is disabled.

### ISSUE THREAD

**Issue by h7kanna** [skeletonlabs/skeleton#1782]
### Current Behavior

When we create a Popup with hover on a button and then after clicking the button, if the button is disabled on the onClick handler. then the Popup will be stuck. Moreover, even adding a closeQuery button within the Popup also does not work.

### Expected Behavior

Popup should fade away after the click of the button regardless of the button's enabled/disabled state.

### Steps To Reproduce

```ts
let startDisabled = false
function startAction() {
       startDisabled = true
}
let startPopupSettings: PopupSettings = {
	event: 'hover',
	target: 'startButtonTooltip',
	placement: 'top'
};
```

```svelte
<div class="card variant-filled-secondary p-4" data-popup="startButtonTooltip">
	Start the action
</div>
<button
	disabled={startDisabled}
	class="btn variant-filled [&>*]:pointer-events-none"
	use:popup={startPopupSettings}
	on:click={startAction}
>
Start
</button>

```

**Comment by Hugos68** [comment]
Hey @h7kanna I am unable to reproduce this locally, could you share what browser and operating system you are on? If you'd also could create a reproduction in a [Stackblitz](https://stackblitz.com/edit/skeletonlabs-repl-9jwm7z?file=README.md) that'd be great!

This is the behavior I'm seeing on my system, please let me know if this is the desired behavior or not:
![gif](https://i.imgur.com/Oqr6o8E.gif)

**Comment by h7kanna** [comment]
Oh, I am using Skeleton with [Tauri](https://tauri.app/),  It's not the browser but WebKit.

**Comment by h7kanna** [comment]
I will create a basic sample app to reproduce this.

**Comment by endigo9740** [comment]
@h7kanna we'll try to debug, but we're not really setup to test with Tauri and don't really provide official support for this. Skeleton is currently intended for standard web browsers. That said, if we can find a way to produce in a browser, we can certainly try to resolve this.

**Comment by endigo9740** [comment]
FYI, as we begin prepping for the new standalone popup package, we're consolidating all known issues for popups into this new thread:

- https://github.com/skeletonlabs/skeleton/issues/1916

Your post will now be closed, but has been referenced in the post linked above. Please note that by doing this, your request is being folded into this larger effort. Please feel free to monitor the linked issue if you wish to track progress on this going forward.
