### ISSUE TITLE
Resizable AppShell slots

### ISSUE THREAD

**Issue by Rimantovas** [skeletonlabs/skeleton#1783]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I think it would be useful to have the AppShell slots be resizable by dragging the corner.

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@Rimantovas the slots don't have an inherit size, they take the size of the element within. This means you could drop your own div elements in and use the resize styling:

- https://tailwindcss.com/docs/resize
- https://developer.mozilla.org/en-US/docs/Web/CSS/resize
