### ISSUE TITLE
TreeView shows double arrow on webkit browsers

### ISSUE THREAD

**Issue by ak4zh** [skeletonlabs/skeleton#1784]
### Current Behavior

Here's the screenshot from skeleton dev website:

<img width="482" alt="Screenshot 2023-07-20 at 5 41 10 PM" src="https://github.com/skeletonlabs/skeleton/assets/26350053/573ebc0d-9e5d-486f-b427-3a7922313280">

**Comment by endigo9740** [comment]
It's Safari - per the original post on Discord

![Screenshot 2023-07-20 at 11 03 03 AM](https://github.com/skeletonlabs/skeleton/assets/1509726/57519441-3a3b-469e-b8ee-10d7ef83d3b4)

**Comment by Mahmoud-zino** [comment]
I will include it in the PR 👍 , also I will set up my Ubuntu env to test Safari from now on to avoid such bugs, I just love the browsers war 😅

**Comment by endigo9740** [comment]
@Mahmoud-zino let me know if I can help test as well!

**Comment by ak4zh** [comment]
Yes, it's only on webkit based browsers.
Safari, Orion etc.
