### ISSUE TITLE
"Incorrect" suggestion in Radio Groups

### ISSUE THREAD

**Issue by SebasF1349** [skeletonlabs/skeleton#1786]
### Link to the Page

https://www.skeleton.dev/components/radio-groups#full-width

### Describe the Issue (screenshots encouraged!)

Documentation recommends using

`<RadioGroup display="flex">...</RadioGroup>`

"to stretch and fill the full width.", which is incorrect as it results in a not-streched group:

![vivaldi_EzNkqnD7mZ](https://github.com/skeletonlabs/skeleton/assets/33849340/d26a22d8-ca21-4d26-ab4d-84e86d55795e)

To achieve the desired result (see next pic) we need to use an arbitrary variant as there is no prop to add classes to the child labels. `class="flex [&>label]:flex-auto"` looks to work.

![vivaldi_PXcIeTq2O1](https://github.com/skeletonlabs/skeleton/assets/33849340/270683b1-ea18-4a18-a711-3939d066d8de)

I guess easiest fix is to add that class to the doc example, although maybe it can be useful to add a new prop.

Let me know which solution do you think it's best and I can make a pr.

**Comment by Mahmoud-zino** [comment]
I think `region`-Props are the best solution for such problems 👍.

**Comment by SebasF1349** [comment]
Great. Will add the prop and edit the docs. Btw, can both be done in the same pr (asking about the changesets)?

**Comment by endigo9740** [comment]
@SebasF1349 sure that sounds great to handle in a single PR.

**Comment by SebasF1349** [comment]
Sorry I just had time to look at it. Trying to think of the uses of the prop `regionLabel`. Do you think it's best suited for as a `RadioGroup` prop or as a `RadioItem` prop. I was going to do a `RadioGroup` one, but perhaps I'm missing an use case that needs a per item modification.

**Comment by Mahmoud-zino** [comment]
@SebasF1349 I think we need both in such situations, one on the group that is passed through the context, and one on the child so if users want to override them per item they can do it easily.
