### ISSUE TITLE
Popup doesn't animate on first click

### ISSUE THREAD

**Issue by baseplate-admin** [skeletonlabs/skeleton#1787]
### Current Behavior

So basically when i click popup for the first time, there's no animation.

But this behavior is unseen on the consequent clicks.

### Expected Behavior

Popup should animate on first click.

### Steps To Reproduce

1. Go to https://www.skeleton.dev/utilities/popups
2. Click Show Popups

**Comment by endigo9740** [comment]
@baseplate-admin I've seen a small delay for popups when a local dev server is started, including the popups in the top app bar on the Skeleton doc site. But this goes away after a few seconds. Likewise, the behavior doesn't continue after normal browsing. And it's never been present on the final build servers from our web host in production.

Can you confirm this is happening outside of those specific conditions?

**Comment by baseplate-admin** [comment]
> Can you confirm this is happening outside of those specific conditions?

I have seen this behavior on my production website.

---


This is the behavior on first click. ( See how the popup suddenly pops in? )

[screen-recorder-sat-jul-22-2023-06-57-39.webm](https://github.com/skeletonlabs/skeleton/assets/61817579/290c8b5a-2deb-4805-862f-ffa32662030c)


This behavior is absent on consequent clicks

[screen-recorder-sat-jul-22-2023-06-57-56.webm](https://github.com/skeletonlabs/skeleton/assets/61817579/c1bcf998-cb4a-4f81-b14a-3e107f7b7c60)


The second behavior looks normal to me

**Comment by endigo9740** [comment]
FYI, as we begin prepping for the new standalone popup package, we're consolidating all known issues for popups into this new thread:

- https://github.com/skeletonlabs/skeleton/issues/1916

Your post will now be closed, but has been referenced in the post linked above. Please note that by doing this, your request is being folded into this larger effort. Please feel free to monitor the linked issue if you wish to track progress on this going forward.

**Comment by baseplate-admin** [comment]
Sounds good
