### ISSUE TITLE
[Enhancement] Add hover variant for Cards

### ISSUE THREAD

**Issue by sakgoyal** [skeletonlabs/skeleton#1792]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I really like the default card styles but I would really like it if something similar to this could be added:

https://codepen.io/Gelsot/pen/xpGYyd
or something like: 
https://codepen.io/makaveli-dev-web/pen/Roxoqa

The existing card style is nice, but often there could be times where I want the text to be hidden so the image can be larger. Then show the text on hover. The second one is most similar to the existing theme of skeleton so that might be easier to implement. 

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@sakgoyal I'm not sure we could build a single variant that could do something like this. This is a combination of effects that Tailwind can though. It might involve several of the following features:

- https://tailwindcss.com/docs/translate
- https://tailwindcss.com/docs/brightness
- https://tailwindcss.com/docs/opacity
- https://tailwindcss.com/docs/transition-property (all transition settings)
- https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state

By using `group` you can target the children then the parent is hovered.

I'm not saying this will be a trivial thing to add, but all the tools are there. This is one of those cases where the effect is so unique that I think it's best for you to handle yourself here. The goal of Skeleton is to provide privative building blocks, but we don't want redundancy with what Tailwind provides.

Hope this helps.
