### ISSUE TITLE
Toast position is off in some browsers

### ISSUE THREAD

**Issue by risalfajar** [skeletonlabs/skeleton#1794]
### Current Behavior

In Vivaldi, the toast is always appear in top-left corner.
![image](https://github.com/skeletonlabs/skeleton/assets/28381124/7c7e5dc2-2c25-49fd-b6f9-3939460aab5c)

However this doesn't happen in Brave Browser. I've not tried with other browsers.

### Expected Behavior

It should appear according to its set position.

### Steps To Reproduce

1. Open https://www.skeleton.dev/utilities/toasts using Vivaldi
2. Trigger a Toast

**Comment by Sarenor** [comment]
I'm only using Vivaldi and can't recreate it.
Usually, all Chromium-Based Browsers show the same behaviour as well.

Can you share your Vivaldi version? Are you using any plugins or Vivaldi-Specific settings (like the build in add blocker or other build in features, although I can attest from personal experience that at least the add blocker shouldn't lead to that behaviour)

**Comment by risalfajar** [comment]
You are right, it was caused by [this extension](https://chrome.google.com/webstore/detail/clearly-reader-your-reade/odfonlkabodgbolnmmkdijkaeggofoop) even if I don't activate its Reader Mode.
