### ISSUE TITLE
Break Stepper + Step into Header, Content and Footer into named slots or seperate components

### ISSUE THREAD

**Issue by piperun** [skeletonlabs/skeleton#1795]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

At the moment `<Stepper>` & `<Step>` is not very modular, which makes it hard to adjust or replace certain parts of the multi form.

I'm suggesting the following (if named slots are too limited replace with components such as `<StepperHeader>`):

```js
<Stepper>
    <svelte:fragment slot="header">
        <!-- where the <StepperBar> can be loaded in and or other components -->
    </svelte:fragment>



    <svelte:fragment slot="footer">
        <!-- where the <StepperNav> can be loaded in and or other components-->
    </svelte:fragment>
</Stepper>
```

Then when it comes to content it could either be:
```js
    <svelte:fragment slot="content">
        <Step><!-- step 1 --></Step>
        <Step><!-- step 2 --></Step>
        <Step><!-- step 3 --></Step>
    </svelte:fragment>
```
Or simply:
```js
        <Step><!-- step 1 --></Step>
        <Step><!-- step 2 --></Step>
        <Step><!-- step 3 --></Step>
```

### What type of pull request would this be?

enhancement

### Provide relevant links or additional information.

https://tailwindcomponents.com/component/multistep-form-with-tailwindcss-and-alpinejs

One interactive example I found seems to at least incorporate essentially the same design.

**Comment by endigo9740** [comment]
See also: https://github.com/skeletonlabs/skeleton/issues/1780

**Comment by endigo9740** [comment]
I'm going to close this issue as it's redundant with #1780. But note this does link back to this thread for future reference.
