### ISSUE TITLE
Scrollbar corners are not being colored according to the theme

### ISSUE THREAD

**Issue by rinart73** [skeletonlabs/skeleton#1797]
### Current Behavior

Scrollbar corners appear when an element has both vertical and horizontal scrollbars.
Currently Skeleton doesn't apply any styles to them, so their apperance depends on a browser.
On the screenshot below - scrollbar corner in the bottom right is white because my OS and Chrome mode is light, even though website mode is dark.
![image](https://github.com/skeletonlabs/skeleton/assets/1765611/c67e20b0-c2cf-474a-b857-fd46961c700e)

### Expected Behavior

Expected to have scrollbar corner be styled according to the theme settings and mode (light/dark).

### Steps To Reproduce

1. Use any component/tag.
2. Ensure that it has both scrollbars. Example:
```html
<div class="overflow-auto w-20 h-32">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Aenean sed sagittis nibh, vel sollicitudin justo.
  Etiam dapibus ultricies felis, sit amet pellentesque justo sollicitudin sed.
  Suspendisse potenti.
</div>
```

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-repl-gh962k?file=src%2Froutes%2F%2Bpage.svelte

### More Information

This can be solved with the `::-webkit-scrollbar-corner` [CSS pseudo-element](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) by styling it according to the current theme and mode.

Alternatively the following style could be used, that way the corner will just match the background color of an element.
```css
::-webkit-scrollbar-corner { background-color: transparent; }
```

**Comment by brecht-vde** [comment]
I'm interested in giving this one a try if you think it's a good first issue.

**Comment by endigo9740** [comment]
Thanks for volunteering @brecht-vde - my only concern here is how this is handled with resizable elements, such as textareas. Those typically have a handle that should be draggable to resize.

Also note we're in a bit of a transitionary period as we move from v1 to v2. If you wish to send a pull request, make sure to based your branch off of the `v2` branch and add this to the `core.css` styles in our Tailwind plugin package found here in v2:
https://github.com/skeletonlabs/skeleton/blob/v2/packages/plugin/src/styles/base/core.css

I'm going to also ping @AdrianGonz97 to ensure this is the correct location. I believe he was looking to modify the location of the Core styes recently. Just want to make sure I'm pointing in the right location!

**Comment by endigo9740** [comment]
This was resolved in v2
