### ISSUE TITLE
Code completion in ModalComponent

### ISSUE THREAD

**Issue by risalfajar** [skeletonlabs/skeleton#1813]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

We can provide code completion by using Typescript generics in `ModalComponent`:
```ts
import { ComponentProps, SvelteComponent } from "svelte"

export declare type Constructor<T> = new (...args: any[]) => T;

export interface ModalComponent<T extends SvelteComponent> {
	/** Import and provide your component reference. */
	ref: Constructor<T>;
	/** Provide component props as key/value pairs. */
	props?: ComponentProps<T>;
	/** Provide an HTML template literal for the default slot. */
	slot?: string;
}
```

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

Code is taken from https://github.com/bryanmylee/svelte-render/blob/main/src/lib/createRender.ts

**Comment by endigo9740** [comment]
@AdrianGonz97 given you're taking a look at the Modal store soon, I thought I might bring this to your attention. We've had similar requests in the past. If you think it's better to handle separately that's fine too.

**Comment by endigo9740** [comment]
See also: https://github.com/skeletonlabs/skeleton/issues/1188

**Comment by HugeLetters** [comment]
@endigo9740 hi, as previously discussed I would like to take a shot at this issue as well - no promises tho since it seems like a much harder tasks than with Autocomplete ;)

**Comment by endigo9740** [comment]
@HugeLetters go for it. I'll assign this to you now. Thanks for your continued help!

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2357
