### ISSUE TITLE
Paginator ignores initial offset value

### ISSUE THREAD

**Issue by simplyfrancis** [skeletonlabs/skeleton#1818]
### Current Behavior

If I set offset to anything but zero, the value is ignored until I interact with the Next or Previous buttons.

For example, if I have the following settings:

```js
let page = {
  offset: 1,
  limit: 10,
  size: 50,
  amounts: [5, 10, 20, 50]
};

<Paginator bind:settings={page} />
```

I see the following:
`1-10 of 50`

Which ignores that it is meant to be offset by 10.

### Expected Behavior

I expect the page to take the initial offset value into account. 

For example, if I have the following settings:

```js
let page = {
  offset: 1,
  limit: 10,
  size: 50,
  amounts: [5, 10, 20, 50]
};

<Paginator bind:settings={page} />
```

I would expect to see:
`10-20 of 50`

### Steps To Reproduce

1. Set offset in PaginationSettings to be anything but 0
2. Initialize <Paginator /> component with PaginationSettings above
3. Load the page and view the page number widget

### Link to Reproduction / Stackblitz

https://vitejsvite9xhxiq-4chs--5173--d5d65229.local-credentialless.webcontainer.io

**Comment by Mahmoud-zino** [comment]
@simplyfrancis 
`offset` is used to skip items from the list.
![image](https://github.com/skeletonlabs/skeleton/assets/74062808/47645a54-7900-4638-ab62-121d21e591bc)
so setting the offset to 1 will make the item with index 1 (second item) act as the first item and start displaying from there.

Paginators are usually displayed from page 1 and I don't see any use cases where you would want to start from page 2, If you have one please feel free to share it here and we can look into it.

**Comment by simplyfrancis** [comment]
Thanks for the response. I think offset is actually the page number, no? It gets multiplied by the limit to determine the actual item offset. I think it's a little confusingly named, if so; I thought it was the number of items offset initially as well.

<img width="690" alt="Screenshot 2023-08-04 at 12 28 48 pm" src="https://github.com/skeletonlabs/skeleton/assets/116019211/0363d6e3-59a7-4cee-8e76-e294fdf37a60">

In terms of use case, I am trying to store state in the URL via search params, so let's say you have `?offset=1&limit=10` in the URL, it should load the second page of 10 items, but the paginator loads it with `offset: 0`.

It's because of this line, which resets offset to 0 when the component is first loaded:
https://github.com/skeletonlabs/skeleton/blob/dev/packages/skeleton/src/lib/components/Paginator/Paginator.svelte#L94

**Comment by Mahmoud-zino** [comment]
@simplyfrancis you are totally correct, the comment on the offset is somewhat misleading.
As for why we are resetting the offset in `onChangeLength`, @endigo9740 could have a reason for that, even though deleting it seems to work as expected.

**Comment by simplyfrancis** [comment]
@Mahmoud-zino I suspect the reason is that it's hard to work out which page it should be on when you select a new amount, so it's easier just to reset it to the first page.

**Comment by endigo9740** [comment]
@simplyfrancis there was a change around the time this feature was implemented and the name of the feature was never updated. Given it's a breaking change, we'll be making that as part of the v2 release as noted on our roadmap. Actually I'll be working on that today in fact!

**Comment by endigo9740** [comment]
FYI I have implemented the pagination change today per:

- https://github.com/skeletonlabs/skeleton/issues/1821

Per this commit:

- https://github.com/skeletonlabs/skeleton/pull/1822/commits/da5f2194f086938d136858e0ac9512cf6e50196d

This means this change will be a part of the v2 release. Assuming that satisfies any outstanding issues for this ticket I'll go ahead and close this out.

**Comment by simplyfrancis** [comment]
@endigo9740 Ah, the naming of the field is not actually the primary issue this ticket is about; I just mentioned that as a side note. The core issue is that the offset is reset to 0 when the component is initialized, so it cannot be set to a non-zero value. Unless you disagree that that is an issue, I would re-open this until it is addressed.

**Comment by Mahmoud-zino** [comment]
@endigo9740 now that I understand the problem I can fix it, should I create the PR on dev or v2?

**Comment by endigo9740** [comment]
@Mahmoud-zino see if there are any pending changes for the v2 branch, if not v1 will be fine.

**Comment by Mahmoud-zino** [comment]
@endigo9740 since this was targeting v2 you might want to close it manually. thank you 🙏
