### ISSUE TITLE
Accordions cannot be closed

### ISSUE THREAD

**Issue by ta3pks** [skeletonlabs/skeleton#1826]
### Current Behavior

It is not possible to close an accordion item  once it is opened

### Expected Behavior

it should toggle back and forth

### Steps To Reproduce

create accordion with children
click on a child
click on it again nothing will happen

This happens in the skeleton website as well under https://www.skeleton.dev/components/accordions

### Link to Reproduction / Stackblitz

https://www.skeleton.dev/components/accordions

**Comment by riziles** [comment]
@ta3pks , I believe the demo on the web page has `autocollapse` (aka Highlander mode) set to `true`. If you disable it, you can collapse an open accordion.

**Comment by endigo9740** [comment]
What Riziles said. The behavior closes based on the mode set. Not a bug.

**Comment by niktek** [comment]
I've just run into a use case where this would actually be preferable to be able to still toggle.  I have tall content in the accordion item that on smaller screens pushes down the following accordion item, so the user needs to scroll down to click the next one, but the auto collapse now moves the top of the newly expanded item off screen making it a very janky experience.


https://github.com/skeletonlabs/skeleton/assets/52020637/03bb03eb-9ec0-41c0-bc81-cb4dbde0e9f2

The auto collapse in my situation is also necessary as it is being used in a Summary->Detail situation where only one AccordionItem can be active/open at any time.

Fine to do a local version of the component for my project, but just want to flag it as another vote for changing to toggle able.

**Comment by riziles** [comment]
i.e. there can be only one... or none?

**Comment by endigo9740** [comment]
We're currently about to kick off on Skeleton v3. As part of this we'll be reviewing and updating a number of components. As part of this I'm going to go ahead and indicate this as a feature request for the v3 milestone.

**Comment by riziles** [comment]
@endigo9740 , based on my current reading of the docs, there is no way currently to programmatically open and close accordions. Not a high priority, but do you think that might be a possibility in Skeleton 3?

**Comment by endigo9740** [comment]
@riziles maybe. I'll see this thread when we're working on the update so we'll take that into consideration.

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2370
