### ISSUE TITLE
Make input group also inherit disabled styling like the input class does

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#1838]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently if you have an input like this:
```html
<input class="input" disabled />
```
It will get disabled styling because of the skeleton styling found [here](https://github.com/skeletonlabs/skeleton/blob/964afed490acf70455f6fac62693de73165f3ed4/packages/skeleton/src/lib/styles/elements/forms.css#L177)

When creating an input group like this:
```html
<div class="input-group input-group-divider grid-cols-[auto_1fr_auto]">
    <div class="input-group-shim">(segment)</div>
    <input disabled" />
    <button>Submit</button>
</div>
```
The input is already styled by the input group so skeleton does not need you to add the ``input`` class to the input element. This causes the disabled styling to not get added to this input. I think skeleton would benefit if this disabled style is consistent throughout all the inputs.

A simple fix for this would be:
```css
.input-group > input:disabled {
    @apply !opacity-50 !cursor-not-allowed hover:!brightness-100;
}
```

Let me know what you think, this issue was written because someone reached out in the skeleton support with the example scenario used above, the thread can be found [here](https://discord.com/channels/1003691521280856084/1138583719561666624).

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@Hugos68 I think is an interesting idea. If you want to send a PR of this I'd be happy to review. No rush obviously.

**Comment by Hugos68** [comment]
Alright, I created the PR, the disabled style isn't reflected on the neighbouring elements, only the element that has the disabled style on it.
