### ISSUE TITLE
Closed popup with 'opacity: 0' still clickable on firefox

### ISSUE THREAD

**Issue by id3nom** [skeletonlabs/skeleton#1843]
### Current Behavior

On firefox 102.14.0esr (64-bit), when the popup close, the popup still registers mouse event, even if it's opacity is set to 0.
Chrome is not affected by that problem.

### Expected Behavior

After the popup is closed, `display: none` should be used instead of or with `opacity: 0`.

### Steps To Reproduce

1. use firefox.
2. goto https://www.skeleton.dev/utilities/popups and click on the 'Show Popup' button.
3. Remember the location of the 'View on Twitter' button.
4. Close the popup and try to click at the same location where the 'View on Twitter' button was.
5. You will be redirected to the 'Twitter' page.

**Comment by Mahmoud-zino** [comment]
I am on the latest version and can't reproduce it:
![image](https://github.com/skeletonlabs/skeleton/assets/74062808/f239fc85-410a-4c55-8651-b5841f447fc2)

please try updating Firefox, and if the problem is still there try turning off any plugins you are using (preferably in Incognito mode) and try again. some plugins interfere with the website functionalities.

**Comment by Sarenor** [comment]
> Expected Behavior
After the popup is closed, display: none should be used instead of or with opacity: 0.

Can't do that I'm afraid, it needs to be "rendered" for floating UI to position it correctly (can only calculate the popup size when floating ui can find out how big it is)

**Comment by riziles** [comment]
@id3nom , you can probably use a state callback to change the z-index for this edge case

**Comment by id3nom** [comment]
> I am on the latest version and can't reproduce it: ![image](https://user-images.githubusercontent.com/74062808/259993830-f239fc85-410a-4c55-8651-b5841f447fc2.png)
> 
> please try updating Firefox, and if the problem is still there try turning off any plugins you are using (preferably in Incognito mode) and try again. some plugins interfere with the website functionalities.

I'm using debian 12 with the latest available firefox release on the platform. I tried with firefox 116 on windows and android and confirm that the issue is not present. I will try @riziles solution. thanks all.
