### ISSUE TITLE
Drawer in Safari isn't smooth

### ISSUE THREAD

**Issue by Zerotask** [skeletonlabs/skeleton#1848]
### Current Behavior

If I use the Drawer on https://www.skeleton.dev/utilities/drawers with the latest safari, the transition isn't smooth. It's a bit laggy.
In Brave for example, it's smooth though.

### Expected Behavior

Same smooth behavior as in Brave/Chrome.

### Steps To Reproduce

1. Open Safari
2. Open https://www.skeleton.dev/utilities/drawers
3. Click on the first example

**Comment by niktek** [comment]
Hey @Zerotask 

Any chance you could get a screen capture ? (I recommend Kap if you don't have one already) - I just tested this on an M1 8GB mini - pretty much the weakest Mac you can have and the animations didn't seem too different to me.

**Comment by Zerotask** [comment]
https://github.com/skeletonlabs/skeleton/assets/20150243/8cc04609-efe1-4c8b-b41e-a8f94539dfaa

You can barely see it in the recording at the first 2 clicks. The third one looks smoother.

**Comment by Zerotask** [comment]
@endigo9740 Thank you for your fast and detailed answer.
