### ISSUE TITLE
Audit icon support for popular icon libraries (Iconify, etc)

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1852]
Skeleton has been developed to be icon library agnostic, meaning you can use any icon solution you wish. However we tend to favor Font Awesome for the majority of our internal projects and documentation. The goal here should be to determine if additional settings or configuration is needed to support these alternatives.

We should do an audit and review how this works with other popular icons libraries, including but not limited to:

- [ ] [Iconify](https://iconify.design/)
- [ ] ...

Feel free to make suggestions in the comments for other libraries you wish for us to test.

**Comment by zim0369** [comment]
there's an alignment problem with icons from **ICONIFY** and **IMG**
example:
```html
<AppRail class="hidden md:block">
	<svelte:fragment slot="lead">
		<AppRailAnchor href="/">
      <Icon icon="mdi:home"/>
    </AppRailAnchor>
	</svelte:fragment>
	<!-- --- -->
	<AppRailTile bind:group={currentTile} name="tile-1" value={0} title="tile-1">
		<svelte:fragment slot="lead">
      <Icon class="text-2xl" icon="mdi:home"/>
    </svelte:fragment>
		<span>Tile 1</span>
	</AppRailTile>
	<AppRailTile class='text-3xl' bind:group={currentTile} name="tile-2" value={1} title="tile-2">
		<svelte:fragment slot="lead">🎇</svelte:fragment>
		<span>Tile 2</span>
	</AppRailTile>
	<AppRailTile bind:group={currentTile} name="tile-3" value={2} title="tile-3">
		<svelte:fragment slot="lead"><img src="/favicon.png"/></svelte:fragment>
		<span>Tile 3</span>
	</AppRailTile>
	<!-- --- -->
	<svelte:fragment slot="trail">
		<AppRailAnchor href="/" target="_blank" title="Account"><img src="/favicon.png"/></AppRailAnchor>
	</svelte:fragment>
</AppRail>
```
looks like this:
![image](https://github.com/skeletonlabs/skeleton/assets/85027668/6b5ccbbb-616b-440f-981c-bfbaa8a5d8c2)

**Comment by zim0369** [comment]
> there's an alignment problem with icons from **ICONIFY** and **IMG** example:
> 
> ```
> <AppRail class="hidden md:block">
> 	<svelte:fragment slot="lead">
> 		<AppRailAnchor href="/">
>       <Icon icon="mdi:home"/>
>     </AppRailAnchor>
> 	</svelte:fragment>
> 	
> 	<AppRailTile bind:group={currentTile} name="tile-1" value={0} title="tile-1">
> 		<svelte:fragment slot="lead">
>       <Icon class="text-2xl" icon="mdi:home"/>
>     </svelte:fragment>
> 		<span>Tile 1</span>
> 	</AppRailTile>
> 	<AppRailTile class='text-3xl' bind:group={currentTile} name="tile-2" value={1} title="tile-2">
> 		<svelte:fragment slot="lead">🎇</svelte:fragment>
> 		<span>Tile 2</span>
> 	</AppRailTile>
> 	<AppRailTile bind:group={currentTile} name="tile-3" value={2} title="tile-3">
> 		<svelte:fragment slot="lead"><img src="/favicon.png"/></svelte:fragment>
> 		<span>Tile 3</span>
> 	</AppRailTile>
> 	
> 	<svelte:fragment slot="trail">
> 		<AppRailAnchor href="/" target="_blank" title="Account"><img src="/favicon.png"/></AppRailAnchor>
> 	</svelte:fragment>
> </AppRail>
> ```
> 
> looks like this: ![image](https://user-images.githubusercontent.com/85027668/260146866-6b5ccbbb-616b-440f-981c-bfbaa8a5d8c2.png)

Adding `inline-block` to `app.postcss` helped me fix the problem:
```postcss
/*place global styles here */
html,
body {
	@apply h-full;
}
.iconify {
    display: inline-block
}
```

**Comment by endigo9740** [comment]
I already shared this with Zim on Discord, but a more localized option would be to implement the `inline-block` class PER icon:

```html
 <Icon class="text-2xl inline-block" icon="mdi:home"/>
```

This is a Tailwind class that will do the same thing, but per icon:
https://tailwindcss.com/docs/display

**Comment by eagerestwolf** [comment]
Sorry, I know this kind of old, but I can provide feedback on 2 libraries.

- [Tabler Icons](https://tabler-icons.io/) (somewhat popular in the React world, has a Svelte library): Doesn't work at all. It uses SVG icons that just don't render.
- [Material Symbols](https://fonts.google.com/icons) (used via [marella's npm library](https://github.com/marella/material-symbols/tree/main/material-symbols#readme)): work, but they don't size correctly. Changing the text size has no effect on the icon. You have to physically adjust the container size (this is probably a quirk of the icon library though).

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2353
