### ISSUE TITLE
Toast notification component to have a progress built-in

### ISSUE THREAD

**Issue by ysk3a** [skeletonlabs/skeleton#1855]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

toast to have cooldown/countdown/progress option built in like 
`https://www.melt-ui.com/docs/builders/toast` under 'With Progress' section
or
`https://grail-ui.vercel.app/svelte/toast`
for the `https://www.skeleton.dev/utilities/toasts` under 'timing' section.

### What type of pull request would this be?

None

**Comment by aaroncrockett** [comment]
I'll take a look at this if you would like.

**Comment by endigo9740** [comment]
Thanks @aaroncrockett, I'm consider a bigger change in regards to toasts/modals/drawers in the near future, so if you don't mind feel free to hold off for now. But I'll ping you something changes though!
