### ISSUE TITLE
Add border color customization

### ISSUE THREAD

**Issue by ak4zh** [skeletonlabs/skeleton#1856]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Presently, the theme generator automatically generates border colors based on the surface or primary color and opacity, without providing an option to manually select the border color. It would greatly enhance the user experience if there was an inclusion of the ability to choose both the border color and its opacity.

```
Border Opacity: XX
Border Color in Light Mode: [primary, secondary, tertiary, success, warning, error, surface]
Border Color in Dark Mode:  [primary, secondary, tertiary, success, warning, error, surface]
```

This enhancement could involve the option to either select from existing color choices or input a custom hex code for the border color.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Merging this into: https://github.com/skeletonlabs/skeleton/issues/1142
