### ISSUE TITLE
rtl problem in LightSwitch

### ISSUE THREAD

**Issue by mehradamiri** [skeletonlabs/skeleton#1857]
### Current Behavior

my project base is rtl
```html
<body dir="rtl"> /<body>
```
the problem with LightSwitch is icon goes out when you toggle it
![image](https://github.com/skeletonlabs/skeleton/assets/92649809/dc833457-695f-4104-84b7-bce1ce429a8b)
btw lots of component have problem with rtl and you can fix it this way 
```html
<div dir="ltr"><LightSwitch /></div>
```

**Comment by endigo9740** [comment]
@mehradamiri Skeleton doesn't support RTL yet and `rtl` is not a documented property because it doesn't exist on this or any other component. I'm not sure what you're using to introduce this feature into your project, but this is not something we would provide support for at this time.
