### ISSUE TITLE
Drawers example using the same function twice

### ISSUE THREAD

**Issue by Lanceqt** [skeletonlabs/skeleton#1860]
### Link to the Page

https://www.skeleton.dev/utilities/drawers

### Describe the Issue (screenshots encouraged!)

![image](https://github.com/skeletonlabs/skeleton/assets/6804298/c1ff2e07-32ff-4605-8d39-d2b206e60352)

I believe the correct implementation would be drawerClose for the second function

**Comment by niktek** [comment]
Pretty sure this has already been resolved in the v2 branch, will check again when we do the merging into dev later today

**Comment by niktek** [comment]
Confirmed re-written in v2
