### ISSUE TITLE
Swap default toasts and modals z-index

### ISSUE THREAD

**Issue by rinart73** [skeletonlabs/skeleton#1869]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently modals have `z-index: 999`, while toasts have `z-index: 888`.

I understand that it's a small change that could be done manually on per-project basis but I think it would be more logical to swap these values by default.

This would allow to display toasts in response to actions performed in a modal. So if we have an AJAX contact form in a modal, we could display a "Your message was successfully submitted" toast.

![image](https://github.com/skeletonlabs/skeleton/assets/1765611/35fad02d-913f-4c2f-a852-c6b624bcc04f)

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

Modals z-index: https://github.com/skeletonlabs/skeleton/blob/dev/packages/skeleton/src/lib/utilities/Modal/Modal.svelte#L52
Toasts z-index: https://github.com/skeletonlabs/skeleton/blob/dev/packages/skeleton/src/lib/utilities/Toast/Toast.svelte#L38

**Comment by endigo9740** [comment]
Per the ARIA APG guidelines:

https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/

> Inert content outside an active dialog is typically visually obscured or dimmed so it is difficult to discern, and in some implementations, attempts to interact with the inert content cause the dialog to close.

Also:

> The alertdialog role is a special-case dialog role designed specifically for dialogs that divert users' attention to a brief, important message.

We treat modals as the most critical information on the screen at that time, which is why they are given precedence. I know some folks want to break from recommended practices here, and that's why we provide an option to change this behavior.
