### ISSUE TITLE
Using checked input attribute on RadioItem component does not apply the active color variant

### ISSUE THREAD

**Issue by DrOncogene** [skeletonlabs/skeleton#1879]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

```
<RadioGroup>
     <RadioItem checked>1</RadioItem>
     <RadioItem>2</RadioItem>
</RadioGroup>
```

 `<RadioItem>` 1 above is selected but the active colour state in the UI is not applied until item 2 is selected and item 1 is reselected again. This means the user will not know that the item has already been selected by default. I only knew it is selected by default after examining the form data on the server-side form action.

Thank you to the developers. Great work!

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Hey @DrOncogene, I might recommend checking the documentation to learn more about this feature works:
https://www.skeleton.dev/components/radio-groups

You can tap the Code button on any examples to view a code snippet showing how the feature is constructed:
![image](https://github.com/skeletonlabs/skeleton/assets/1509726/bb408a31-bcd7-4b80-ab5a-50e7c007ce43)

Radio groups do not implement a `checked` property to handle state. Instead, we use the same model that native Radio Inputs use in Svelte itself:
https://svelte.dev/tutorial/group-inputs

```ts
let value: number = 0;
```

```html
<RadioGroup>
	<RadioItem bind:group={value} name="justify" value={0}>(label)</RadioItem>
	<RadioItem bind:group={value} name="justify" value={1}>(label)</RadioItem>
	<RadioItem bind:group={value} name="justify" value={2}>(label)</RadioItem>
</RadioGroup>
```

- You define a variable to hold the state, with a default value defined `0`
- This variable is applied to the binded `group` data
- A `name` field is required to describe the grouping
- An unique `value` is applied to each Radio Item
- You can also define a visible label between the Radio Item tags

I'm not sure we can provide any further assistance beyond this, so I'll go ahead and close out this issue. But feel free to follow up if we can clarify anything above.

**Comment by DrOncogene** [comment]
> Hey @DrOncogene, I might recommend checking the documentation to learn more about this feature works:
> https://www.skeleton.dev/components/radio-groups
> 
> You can tap the Code button on any examples to view a code snippet showing how the feature is implemented:
> ![image](https://github.com/skeletonlabs/skeleton/assets/1509726/bb408a31-bcd7-4b80-ab5a-50e7c007ce43)
> 
> Radio groups do not implement a `checked` property to handle state. Instead, we use the same model that native Radio Inputs use in Svelte itself:
> https://svelte.dev/tutorial/group-inputs
> 
> ```ts
> let value: number = 0;
> ```
> 
> ```html
> <RadioGroup>
> 	<RadioItem bind:group={value} name="justify" value={0}>(label)</RadioItem>
> 	<RadioItem bind:group={value} name="justify" value={1}>(label)</RadioItem>
> 	<RadioItem bind:group={value} name="justify" value={2}>(label)</RadioItem>
> </RadioGroup>
> ```
> 
> - You define a variable to hold the state, with a default (selected) value `0`
> - This variable is applied to the binded `group` data
> - A `name` field is required to describe the grouping
> - An unique `value` is applied to each Radio Item
> - You can also define a visible label between the Radio Item tags
> 
> I'm not sure we can provide any further assistance beyond this, so I'll go ahead and close out this issue. But feel free to follow up if we can clarify anything above.

Thank you. I realized my mistake. I should've set the initial value of the bind variable before binding it. It doesn't have to be 0. The important thing is for the value of the item I'm intending to select by default to be the same as the initial value of the bind variable. 

Fixed. Thanks 👍
