### ISSUE TITLE
Data-Driven Tree View Enhancements

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#1884]
### Events
Currently, a datadriven/recursive TreeView doesn't forward events. To be able to react to changes in the TreeView, it would be nice if the ChangeEvent in the [TreeViewDataDrivenItem](https://github.com/skeletonlabs/skeleton/blob/v2/packages/skeleton/src/lib/components/TreeView/TreeViewDataDrivenItem.svelte#L60) could bubble through the TreeView until it can be listened to by the caller.

###Ease of use:
Currently, the new datadriven/recursive TreeView marks nodes that have been checked only in the provided TreeViewNodes-List.

For ease of use it would be nice if it could also provide a bind-point for ``selectedTreeNodes`` or similar, that contains a list of only the selected nodes.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

https://carbon-components-svelte.onrender.com/components/TreeView

The reporting user mentioned Carbon TreeView as a reference, probably mostly for the selectedItems list. Although I only found that for initial selection, but my quick scan probably missed the other part.

[Discord Convo](https://discord.com/channels/1003691521280856084/1141301073714364416)

**Comment by Tihomir971** [comment]
> ### Provide relevant links or additional information.
> https://carbon-components-svelte.onrender.com/components/TreeView
> 
> The reporting user mentioned Carbon TreeView as a reference, probably mostly for the selectedItems list. Although I only found that for initial selection, but my quick scan probably missed the other part.
> 
> [Discord Convo](https://discord.com/channels/1003691521280856084/1141301073714364416)

activeId, selectedIds and expandedIds in Carbon TreeView are reactive and can be used both ways

**Comment by Mahmoud-zino** [comment]
Note: events forwarding is now included in #1910.
