### ISSUE TITLE
TreeView doesn't uncheck to root node only parent.

### ISSUE THREAD

**Issue by Tihomir971** [skeletonlabs/skeleton#1885]
### Current Behavior

![image](https://github.com/skeletonlabs/skeleton/assets/72653027/5784c2e6-61c2-4778-994b-22d2d28bafaf)

### Steps To Reproduce

If i check "Auto & Tires" and then "Baby Oils & Lotions", "Auto & Tires" stay chcked.

**Comment by Mahmoud-zino** [comment]
@Tihomir971 Thank you for reporting this bug, we are working on it.
please note until the fix is dropped the Tree-view recursive mode is broken, even with only two levels (parent/child).
