### ISSUE TITLE
[v2 rc] LightSwitch breaks(visually) after `pnpm build & preview`

### ISSUE THREAD

**Issue by johnwook** [skeletonlabs/skeleton#1889]
### Current Behavior

`LightSwitch` component visually breaks after `npm build`, although it shows correctly in `npm dev`

- broken in built(preview) mode: 
<img width="368" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/2437909/4502c60e-0c32-4d70-b8d4-26b913819342">

- fine in dev mode:
<img width="335" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/2437909/ce9de030-4ef5-47f8-9e60-33ab2bda5272">

### Expected Behavior

The component should look just the same as dev mode

### Steps To Reproduce

1. create project with `npm create svelte@rc my-skeleton-app`
2. Select, `AppShell starter`, `Skeleton(theme)`, `Tailwind forms & typography`, `TypeScript`, `none`
3. Add `LightSwitch` to header-trail slot of `src/routes/+layout.svelte`
4. `npm run build` & `npm run preview`
5. `npm run dev` looks fine.

**Comment by Sarenor** [comment]
Can you share the repository for that?
The create command isn't using the command I'd expect it to use for v2 and I think it might be a wrong setup issue:
``npm create skeleton-app@rc my-skeleton-app`` 
Is the command I'd expect to create a Skeleton App with v2

**Comment by johnwook** [comment]
And I just uploaded repo for reproduction

- https://github.com/johnwook/skeleton-lightswitch-bug-reproduct
- check the main page with
  - `pnpm dev`
  - `pnpm build` & `pnpm preview`

**Comment by Sarenor** [comment]
I actually have near 0 styling in pnpm preview, there's no colors or anything, even if I remove purgeCSS from the active Vite plugins.

**Comment by nicolas-albert** [comment]
Same here, `LightSwitch` styling isn't good in `build` mode (**with** or **without** the `static-adapter`).

I don't know if it's linked but I also add a custom class in `app.postcss` that exists in `dev` but not in `build` mode.

I tried with or without `purgeCSS` from a migrated project.

Fun fact, the blank project with the glowing skull look at the left in `dev` and at the right in `prod` (need another issue ?)

**Comment by Sarenor** [comment]
I think we can keep "styling is somehow very broken in v2 sometimes" here for now

**Comment by Rar9** [comment]
Same here, preview/build replaces/messes up styles.   
Even disabled my custom Lightswitch and purgeCSS without effect
Using custom Theme with prettier 3

**Comment by endigo9740** [comment]
Just FYI everyone, we've had a number of folks chime in about breaking style and theme issues suddenly this morning. Something (or somethings) have clearly introduced a regression here. We're going to be troubleshooting and will provide solutions asap.

Thanks for your patience in the meantime.

**Comment by AdrianGonz97** [comment]
@johnwook I've pushed an update to `vite-plugin-tailwind-purgecss` to fix this issue. If you don't mind upgrading it to version `0.1.2` and letting me know if that's working now, that'd be great!

**Comment by endigo9740** [comment]
FYI, testing a new Skeleton CLI project post-update of the PurgeCSS plugin I'm seeing the expected results. I'd ask that everyone please update the PurgeCSS plugin and test again.

Here's what I'm seeing when building and previewing the new project:

![Screenshot 2023-08-17 at 12 26 35 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/af600410-6420-4c54-a532-1d3dea5325b5)

![Screenshot 2023-08-17 at 12 26 40 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/fd2a97a1-4823-40fa-80a6-7c331f56ca46)

**Comment by endigo9740** [comment]
@johnwook @nicolas-albert @Rar9 

To help our debugging effort can you confirm which adapter you're using. If you didn't install an adapter then you should be using the default `auto-adapter` that SvelteKit provides out of the box.

**Comment by johnwook** [comment]
@AdrianGonz97 Updating `vite-plugin-tailwind-purgecss` fixed the issue! thanks!

@endigo9740 I'm using adapter-node(v1.3.1) :)

Please feel free to close the issue

**Comment by endigo9740** [comment]
Thanks for the info @johnwook - we've had a few other folks report similar issues here, #1891, and on Discord. So we'll keep this open a bit longer. But glad to hear that sorted it for you!

**Comment by johnwook** [comment]
@endigo9740 I'm not sure what's happening, but I think there's still a problem with deployment.

I have no problem with built things, which means when I run things with 'pnpm preview`
But the deployed version still shows the same problem. It looks like some css (like `scale-[0.8]`) got removed.

**Comment by endigo9740** [comment]
So `scale` style is pure Tailwind, nothing handled or controlled by Skeleton. If that's being removed it's likely a separate and possibly unrelated issue. Typically the local build preview is representative of what should be expected after deployed though. 

Out of curiosity, have you deployed a Skeleton project with v1 in the past with the Node adapter? I haven't personally used the Node adapter for any projects - so I don't know the specific requirements for deploying a SvelteKit app with it. We used the static adapter in the past, and now the auto or Vercel adapters between various projects.

**Comment by johnwook** [comment]
Yes I have deployed with v1 without any problem :) Yes, I have to dig into the issue. Thanks for your comment!

**Comment by johnwook** [comment]
the issue above was cache issue have nothing to do with skeleton :)

**Comment by endigo9740** [comment]
@johnwook @nicolas-albert @Rar9 

After reviewing with @niktek and @AdrianGonz97 in `#contributors` on Discord today, we believe most (if not all) issues seen with build previews are related to caching. That is, perhaps you've reviewed a prior build recently, then when you load the new build, the CSS is cached in a manner that provides the mixed results we're seeing. Where the styles (which include your theme settings) don't quite match what you were expecting.

Likewise, issues with the Lightswitch and light/dark mode may be attributed to the use of localstorage. There could be a caching issue present here that somehow affects the state of this.

Given this, the simplest way to test and confirm is to ensure you test your new builds in an Incognito tab, or make sure to manually purge any local data (cache, cookies, local storage, etc) between build previews. If the issue does not persist while doing this, you can safely assume it's related to caching.

@johnwook it seems you've already confirm this was your issue.

For everyone else, we're going to close this issue, but will monitor your results. Feel free to reach out on Discord if your issue persists though. We'll be happy to debug!
