### ISSUE TITLE
Add Disabled stylings to App Rail Tile/Anchor

### ISSUE THREAD

**Issue by MrVauxs** [skeletonlabs/skeleton#1890]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

As title implies, adding an optional `disabled` property with built-in styling and functionality that removes the ability to click the components would be appreciated.

It doesn't seem like it's possible to do it yourself currently.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
This would be a feature specific to the standard tiles, not available to the anchor tiles. A disabled state is both visual and functional, but anchors don't have disabled states, buttons do.

As a bit of a work around for now, what I might suggest is removing options that are not currently available to use via `if` statements.

**Comment by ak4zh** [comment]
@MrVauxs  May be you could do:

```
<AppRailTile class="grayscale" style="pointer-events: none">
	<span>Docs</span>
</AppRailTile>
```

**Comment by endigo9740** [comment]
Just noting that we may want to tackle this alongside this open ticket regarding a11y for certain components:

- https://github.com/skeletonlabs/skeleton/issues/1708
I believe the change we want would here would be similar in scope to what I noted around this tab issue earlier today:

- https://github.com/skeletonlabs/skeleton/issues/1752#issuecomment-1712090347

**Comment by endigo9740** [comment]
I think for now Ak4zh's answer above will suffice for this. We'll go ahead and sunset this one. Thanks!
