### ISSUE TITLE
Custom theme not working in preview/production 

### ISSUE THREAD

**Issue by Josh-Nicholson** [skeletonlabs/skeleton#1891]
### Current Behavior

After migrating my existing v1 custom theme to v2, i'm losing my custom theme styling in preview/production.
Works fine in dev.

### Expected Behavior

Custom theme styling to work on preview/production

### Steps To Reproduce

Using adapter-node v1.3.1 with npm run build

**Comment by endigo9740** [comment]
@Josh-Nicholson @Sarenor so not to make assumptions here, can you confirm you followed the migration process here:

- https://github.com/skeletonlabs/skeleton/discussions/1854

We had a user a couple days ago forget to add the Tailwind Directives mentioned in Step 4 and that caused no styles to display. Can you confirm you've added these?

**Comment by endigo9740** [comment]
@Josh-Nicholson I've updated my recommendation per: https://github.com/skeletonlabs/skeleton/issues/1889#issuecomment-1684141572

In a nutshell, please consider testing with an incognito when testing your preview build. We believe folks may be seeing a caching issue that affects the CSS of the build.

Given we've not seen a response in around 24 hours from you I'm going to go ahead and close this. But if the issue persists, let us know and we'll gladly reopen. Likewise, if this occurs, please share the contents of the custom theme so we can verify it's not a format issue.
