### ISSUE TITLE
Blog posts need to be updated for v2

### ISSUE THREAD

**Issue by SebasF1349** [skeletonlabs/skeleton#1906]
### Describe the Issue (screenshots encouraged!)

Blog posts tutorials need to be updated for the upcoming v2. These two will need some changes:

- [x] https://skeleton-docs-git-v2-skeleton-labs.vercel.app/blog/deep-dive-skeleton-styling
- [x] https://skeleton-docs-git-v2-skeleton-labs.vercel.app/blog/how-to-implement-a-responsive-sidebar-drawer 

I've never used Skeleton with other UI libs, so not sure about these two:

- [x] https://www.skeleton.dev/blog/skeleton-plus-tailwind-ui
- [x] https://www.skeleton.dev/blog/skeleton-plus-flowbite

Of course I may be missing other posts.

**Comment by endigo9740** [comment]
@SebasF1349 All of these have been updated, along with a small message stating such near the top of the article. If you find any others please let me know! Thanks!
