### ISSUE TITLE
TOC id generation conflict

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#1909]
### Current Behavior

At https://github.com/skeletonlabs/skeleton/blob/2f3eaf8015d3b44f8f5d01fb6d89677aa0b11253/packages/skeleton/src/lib/utilities/TableOfContents/crawler.ts#L42

It might be good to append a '-toc' or other random string to ensure that it doesn't conflict with any other element  id's that are the same as the textContent.  You can see this conflict on https://www.skeleton.dev/elements/chat when clicking on Prompt on the TOC.  I also query the logic of assigning an empty string for the id as a fallback as that would break navigation in situations where they might have an icon or other nested structure that doesn't resolve to text coming out ?

**Comment by endigo9740** [comment]
Good call!

**Comment by endigo9740** [comment]
Resolved per https://github.com/skeletonlabs/skeleton/pull/1915
