### ISSUE TITLE
Popup content remains clickable after closing the popup

### ISSUE THREAD

**Issue by JulienZD** [skeletonlabs/skeleton#1913]
### Current Behavior

Components opened via popups remain clickable after closing them, even though they're not visible.

### Expected Behavior

Components opened via popups are **not** clickable after closing them.

### Steps To Reproduce

1. Use a popup in combination with e.g. an Autocomplete
2. Open the popup, take note of the popup's placement
3. Close the popup
4. Click anywhere in the area the popup was visible at

(This can be performed on the Popup example on the [Autocomplete documentation](https://www.skeleton.dev/components/autocomplete)

### More Information

This issue appears to be caused by https://github.com/skeletonlabs/skeleton/pull/1721, which (accidentally?) removed the line `elemPopup.style.pointerEvents = 'none';`. After closing a popup, the content now still has `pointerEvents` set to `'auto'`, meaning it can be clicked, even when not visible. 

The fix should be really simple: just add back the line that was removed (I tested this by manually setting `pointerEvents` to `'none'` my browser and it seems to fix it).

**Comment by Mahmoud-zino** [comment]
@JulienZD Please specify which browser and what version you are using.
We are now using [inert](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) which indicates that the browser will ignore the element achieving the same goal.

**Comment by JulienZD** [comment]
@Mahmoud-zino Welp, turns out I had both an outdated Firefox (111) and Vivalid (5.2, Chromium 100). Updating both fixed it. I wasn't aware that Firefox wasn't set to auto-update, I had assumed it was on the latest version, that's my bad.
