### ISSUE TITLE
Performance Improvement for AutoComplete Component

### ISSUE THREAD

**Issue by ak4zh** [skeletonlabs/skeleton#1939]
### Current Behavior

The current implementation of the AutoComplete component relies on the JSON.stringify method for string formatting.

https://github.com/skeletonlabs/skeleton/blob/b329241ed2662089283cf9816b42298fc16b27d3/packages/skeleton/src/lib/components/Autocomplete/Autocomplete.svelte#L92

## Benchmark Results

I've benchmarked the existing `JSON.stringify` implementation against an alternative using String Interpolation. Here's what I found:

### With Keywords Array Provided

- JSON.stringify: 2,530,903 ops/sec ±0.76%
- String Interpolation: 9,642,194 ops/sec ±2.80%
- Fastest is String Interpolation

### Without Keywords Array Provided

- JSON.stringify: 4,792,242 ops/sec ±1.18%
- String Interpolation: 620,116,539 ops/sec ±0.08%
- Fastest is String Interpolation

## Relative Performance

With keywords array:

- String Interpolation: 100.00%
- JSON.stringify: 24.97%

Without keywords array:

- String Interpolation: 100.00%
- JSON.stringify: 0.77%

### Expected Behavior

Based on the benchmark, we can replace the usage of `JSON.stringify` in AutoComplete component with String Interpolation for improved performance.

**Comment by ak4zh** [comment]
Just jotting down some thoughts for later discussion.

Another alternative would bethat instead of generating the `optionFormatted` on each key input for all options, we generate a local copy of options with the `_metadata` attribute attached? This approach will require some `type` casting though.

```svelte
<script lang="ts">
    // ... (other imports and props)

    // Generate a local copy of options with metadata attached
    $: localOptionsMeta = options.map(option => {
        const metadata = `${option.label} ${option.value} ${option.keywords ? option.keywords.toString() : ''}`.toLowerCase();
        return { ...option, _metadata: metadata };
    });

    function filterOptions(): AutocompleteOption[] {
        const inputFormatted = String(input).toLowerCase().trim();

        return localOptionsMeta.filter(option => option._metadata.includes(inputFormatted));
    }
</script>
```

**Comment by ak4zh** [comment]
After careful consideration, the most versatile and backwards-compatible approach would involve allowing users to provide a `metadata?: string` property within the options.

When `metadata` is present, we'll filter the options exclusively based on that metadata string. Otherwise, we will proceed with the existing approach. This change empowers users with increased flexibility to determine the keywords they wish to match against, rather than assuming a match against both the value and label, along with the stringified version of value in the case of an `object`.

Given that the `value` in `AutoCompleteOption` is of type `unknown`, there can be scenarios when option values are like `{ name: 'option name', description: 'some description' }`. The current matching method returns all results when a typed keyword matches any of the keys within option values.

**Comment by ak4zh** [comment]
Moreover, unnecessary steps, like duplicating options locally inside filterOptions for each input, can be avoided. filterOptions could directly filter the original options array, eliminating the need for copying and spreading options unnecessarily.

**Comment by HugeLetters** [comment]
May I also request an option to provide custom keys for each blocks for `AutocompleteOption`? 
Since you're relying on an option object itself - if those object aren't stable at the very least transitions don't work properly and probably some performance hit for Svelte too since it most likely re-renders each element since all the keys have changed.
And in our app scenario autocomplete options come from the server so we would have to jump huge hoops in order to reach referential stability on changes - even Svelte docs discourage using object keys for data coming from the server.

I think doing something like will be a good option.
```ts
export interface AutocompleteOption<Value = unknown> {
    /** Provide a unique display label per option. */
    label: string;
    /** Provide a unique option value. */
    value: Value;
    /** Provide a comma separated list of keywords. */
    keywords?: any;
    /** Pass arbitrary data per option. */
    meta?: any;
    /** Pass arbitrary key for each blocks per option. If not provided whole option object will be used as a key instead */
    key?: any;
}
```
```ts
{#each optionsFiltered.slice(0, sliceLimit) as option (option.key ?? option)}
```

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2366
