### ISSUE TITLE
Tree-view recursive-mode events bug

### ISSUE THREAD

**Issue by Mahmoud-zino** [skeletonlabs/skeleton#1943]
### Current Behavior

there are tow issues related to events at the moment:
1. Unless a change also changes it's parents value the bind value does not trigger an update (reactivity).
2. clicking on a node with no children will trigger reactivity (the value of node's open prop is changing even if it doesn't have children)

### Expected Behavior

1. every change on the nodes object should trigger reactivity.
2. only nodes with children should trigger reactivity (if opened/closed)

### More Information

reported in https://discord.com/channels/1003691521280856084/1144130943527956510

**Comment by Sarenor** [comment]
Just as a node: When you do start refactoring the TreeView and adding tests to it, you might want to consider splitting it in 2 separate components for datadriven & manual mode for ease of use and testing.
Might help in reducing complexity :)
