### ISSUE TITLE
Stepper component often fails when handling dynamic Step content

### ISSUE THREAD

**Issue by Moosling** [skeletonlabs/skeleton#1952]
### Current Behavior

If one uses a set of `Step`s that dynamically change based on some selection within the `Stepper` flow, you will occasionally get to a "dead" page.

### Expected Behavior

`Step`s are dynamically swapped out without issues.

### Steps To Reproduce

1. Create a `Stepper` with conditionally rendered `Step`s based on a selection within a preceeding page.
2. Trigger the swap of these conditionally rendered `Step`s.
3. Try to move to the next page.
4. You will sometimes/often reach a dead page.

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-repl-dz2gs1?file=src%2Froutes%2F%2Bpage.svelte

### More Information

This happens as the `onDestroy` on the outgoing `Step` is sometimes called after the instantiation of the new `Step`. This can be handled on the user side through something like a `{#key ...}` wrapper around the dynamic `Step`s, but this feels a little bit clunky.

I have some basic idea of using a page list with dynamically generated keys rather than a basic counter but there might be a better alternative! If this is deemed to be a to-fix and this solution sounds reasonable I can make a PR for it.

**Comment by endigo9740** [comment]
I'm going to consolidate this under a larger initiative for the Stepper feature here:

- https://github.com/skeletonlabs/skeleton/issues/1780
