### ISSUE TITLE
Allow custom search solution for autocomplete component

### ISSUE THREAD

**Issue by karianpour** [skeletonlabs/skeleton#1966]
Is it ok to export the filter function so we can use our own filtering mechanism? I like to use a Fuzzy search with fuse.js

https://github.com/skeletonlabs/skeleton/blob/20af3ae37c6792cef598b404e0f513dd8885daaf/packages/skeleton/src/lib/components/Autocomplete/Autocomplete.svelte#L117

**Comment by endigo9740** [comment]
FYI I've clarified the request here via an update to the title. From my understanding you're requesting a ways to utilize your own search solution for our autocomplete feature.

Off hand I'm not sure if this will be possible, but we'll consider this. I'd welcome help from a contributor to review if this can be done.

**Comment by Mahmoud-zino** [comment]
@endigo9740 We can define the filter function as a prop with default value (our simple search function). 
If this sounds reasonable, I would like to handle this task 👍

**Comment by endigo9740** [comment]
@Mahmoud-zino That was a thought I had. The main thing is it needs to be backwards compatible. It can't be a breaking change. So the prop would have to be optional.
