### ISSUE TITLE
provide a way to extend the Autocomple option button using svelte slots

### ISSUE THREAD

**Issue by vboulaye** [skeletonlabs/skeleton#1967]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I started a project with skeleton where I want to use the Autocomplete component and display more than a text label for the selectable options.

I started by adding html tags inside the AutocompleteOption label property, but I can only put "standard" html tags this way and I'd like to use other svelte components there.

So I tried to do this by copying the skeleton Autocomplete.svelte into my project and added a named slot around the existing autocomplete Button (the button with the @html option.label still provides the default implementation) 

The `<slot>` definition can pass the `{option}` property into the slot, this way when you define the  corresponding `<svelte:fragment>`   you can use the `let:option={myOption}` attribute to retrieve the current option and use it inside your fragment. This is better  described in the [slot](https://svelte.dev/docs/special-elements#slot-slot-key-value) section of the svelte doc.  

I also tried passing the `onSelection` callback, it works but in the end it seems easier to just call my function directly using the option.value or meta property.

It seems to work, but would probably require additional testing...

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

The test I made by copying the Autocomplete component in my project and adding the slot is
[here](https://github.com/vboulaye/deezer-artist-playlist-organizer/blob/bfdad7e38af306b10379c2743acea3ee89d0dd51/src/lib/html/DeezerAutocomplete.svelte#L175)
```
                    <li
                            class="autocomplete-item {classesItem}"
                            in:dynamicTransition|local={{ transition: transitionIn, params: transitionInParams, enabled: transitions }}
                            out:dynamicTransition|local={{ transition: transitionOut, params: transitionOutParams, enabled: transitions }}
                    >
                        <slot name="optionButton" {option} {classesButton} {onSelection} >
                            <button class="autocomplete-button {classesButton}" type="button" on:click={() => onSelection(option)} on:click on:keypress>
                                {@html option.label}
                            </button>
                        </slot>
                    </li>
```

And the corresponding <svelte:fragment> where I use it is [there](https://github.com/vboulaye/deezer-artist-playlist-organizer/blob/bfdad7e38af306b10379c2743acea3ee89d0dd51/src/routes/playlists/%5Bid%5D/%2Bpage.svelte#L406)

The selectable option is mapped to the `artistOption` variable:

```
                <DeezerAutocomplete bind:input={$artistSearch} options={$artistsFound} >
                    <svelte:fragment slot="optionButton" let:option={artistOption} >
                        <span class="flex justify-between w-full items-center py-1">
                            <span class="flex items-center">
                                <img src="{artistOption.meta.picture_small}" alt="artist" class="mx-2"/>
                                {artistOption.meta.name}
                            </span>
                            <button class="btn"
                                    title="add all artist titles to the playlist"
                                    on:click={()=>addArtistTracks(artistOption.meta.id, trackSelections)}
                            ><AddIcon/></button>
                        </span>
                    </svelte:fragment>
                </DeezerAutocomplete>
```

**Comment by endigo9740** [comment]
Making a note that we'll evaluate this as part of Skeleton v3, which will support Svelte 5 and the new Snippet features.

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2366
