### ISSUE TITLE
Provide a means to bind to the input for FileDropzone

### ISSUE THREAD

**Issue by Mero-Plaform** [skeletonlabs/skeleton#1972]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

FileDropzone should provide `input` prop for make it possible get the input tag ref and manipulate it programmatically.

Right now such action as `reset button` can be implemented only by such crutch as saving input tag ref from input/change event.

Also need `focus` event for styling and other purposes.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@Mero-Plaform I haven't tested this personally to confirm, but FileDropzone supports Svelte's `$$restProps` feature, which allows for arbitrary attributes to be applied to the component. These are then applied to the targeted element (the input in this case).

In our case we pass these forward, but prune the redundant `class` attribute:
https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/components/FileDropzone/FileDropzone.svelte#L61

Not sure off hand if this works with a functional property like `bind` though. But might be worth a try.

**Comment by Mero-Plaform** [comment]
@endigo9740 You're right, it's possible to pass the `value` prop, but binding doesn't work and also it doesn't trigger the bounded `files` prop change.

If you drag/select files all is good - we can see the `files` prop has been changed, but no changes on this king of reset trick:

```
<script lang="ts">
  import { FileDropzone } from '@skeletonlabs/skeleton';

  let files: FileList;
  let value: string;

  const resetFileDropzone = () => {
    value = "";

    // `files` has been changed after reset!
    console.log(files);
  }
</script>

<button on:click={resetFileDropzone}> reset </button>

<FileDropzone bind:files bind:value name="files" />
<!-- <FileDropzone bind:files {value} name="files" /> -->

<!-- in both cases above we won't see changes here after reset -->
file: {files ? files[0].name : "empty"}
```

**Comment by endigo9740** [comment]
Ok, good to know. In that case we'll keep this open to investigate a way to implement `bind`, or some solution that makes resetting easier.

**Comment by Mero-Plaform** [comment]
Thx, and don't forget about `focus` event, I guess it won't be hard to implement.

**Comment by arrowwu** [comment]
It seems like the only way to reset the dropzone right now is:

```
const dropzone = document.getElementsByClassName("dropzone-input");
dropzone[0].value = ''
```

**Comment by Mero-Plaform** [comment]
@arrowwu yes, or you can do the same by getting input ref inside `on:change` from `event` and cache it.

**Comment by Mahmoud-zino** [comment]
from what I understood, we need to export a bound input reference, and expose the input focus input.
@endigo9740 If this sounds right I would be happy to take this issue.

**Comment by endigo9740** [comment]
@Mahmoud-zino sure, there's been some great suggestions above, with the goal of making it as simple as possible to reset this component. I'd suggest trying a few options and going with whatever feels the most intuative.

Also feel free to forward any relevant events, such as `on:focus` as mentioned above.
