### ISSUE TITLE
Issue when using Focus Trap on Listboxes

### ISSUE THREAD

**Issue by Mero-Plaform** [skeletonlabs/skeleton#1973]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

It would be just great to have possibility to use `focusTrap` for `Listboxes`

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@Mero-Plaform can you explain what's not working? Typically you can't put actions directly on components. However, you can always implement a wrapping element, like a div, which allows for this.

**Comment by Mero-Plaform** [comment]
@endigo9740 Yes, it's impossible to set `use` directive to the component, but it doesn't work with plain `div` wrap.

Or I'm just missing something:

```
<script lang="ts">
  import { focusTrap, ListBox, ListBoxItem } from "@skeletonlabs/skeleton";

  let valueSingle: string = "books";
</script>

<div use:focusTrap={true}>
  <ListBox>
    <ListBoxItem bind:group={valueSingle} name="medium" value="books"
      >Books</ListBoxItem
    >
    <ListBoxItem bind:group={valueSingle} name="medium" value="movies"
      >Movies</ListBoxItem
    >
    <ListBoxItem bind:group={valueSingle} name="medium" value="tv"
      >TV</ListBoxItem
    >
  </ListBox>
</div>
```

**Comment by endigo9740** [comment]
That looks like the correct implementation per the documentation:
https://www.skeleton.dev/actions/focus-trap

When you put tab focus within that region of the page, what is not working? I'd expect tab focus to remain within the listbox items. If it's not, that sounds more like a bug.

Essentially what where you expecting versus what is actually happening?

**Comment by Mahmoud-zino** [comment]
@endigo9740 
this is not related to the other issue. the error is in our query:
https://github.com/skeletonlabs/skeleton/blob/5bcf1da955254f35bfe03d78acd477ccf6e49345/packages/skeleton/src/lib/actions/FocusTrap/focusTrap.ts#L3
I tested the same query with `:not([tabindex="-1"])` after each selector and it is working as expected.
we can either modify the query to include :not after each selector or append it to the query using js.
let me know which way you prefer and I will create the PR 👍

**Comment by endigo9740** [comment]
Awesome, go for it @Mahmoud-zino
