### ISSUE TITLE
Enhancement: Drawer

### ISSUE THREAD

**Issue by Mero-Plaform** [skeletonlabs/skeleton#1974]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Need prop for managing `Esc` button action activity.

The component is multifunctional but without a hack for global keyboard listening on side module, we can't use it like a loading screen, anyone can close it wherever he wants.

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@Mero-Plaform first off I'm going to have to ask you slow down on the posts. Skeleton is open source, and we are glad to accept feature requests. But I would ask that you pace yourself. We're a small team and can only do so much at a time. If you would like to create a thread in Discussions to run a few ideas by me and the team, we would be happy to discuss a few things we might consider. But the shotgun approach isn't the right way to go about this.

Also keep in mind that Skeleton is open source, we do encourage community members to not only request features, but actively contribute them to help everyone. We take our contribution guidelines very seriously, which can be found here:
https://www.skeleton.dev/docs/contributing

Per this issue, this is not likely something we would be interested in implementing. Skeleton leans into accessibility and base a lot of functionally off the WAI-ARIA APG guidelines. Per most components we implement a link to the guidelines for each feature via a button like this on the doc page:

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/7d054c4a-8cce-4a67-a3e7-9aae663b2639)

Here's where this leads for Drawers:
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/

Per the accessibility outlines the ESC button works as intended. Diverting from that would be harmful to the accessibility guidelines. If you need or want different behavior you'll need to clone our feature (we're open source, you can do this) or implement your own approach.
