### ISSUE TITLE
When providing both `autohide: false` and `hideDismiss: true` to a `toastStore.trigger` call, `autohide` is ignored.

### ISSUE THREAD

**Issue by Arro** [skeletonlabs/skeleton#1985]
### Current Behavior

If I add a toast to the page like this:

```
	if ($errors.code) {
		toastStore.trigger({
			message: $errors.code.join('\n'),
			autohide: false,
			hideDismiss: true,
			background: 'variant-filled-error'
		});
	}
```

The `hideDismiss` portion is respected... the dismiss button is gone.

However, the toast autohides anyway.

This may seem like odd usage for a toast, but I'm using the toast to render a form error.  (The way to dismiss it would be to resubmit the form.)

As a stopgap workaround, I can provide a long timeout.

### Expected Behavior

I'd expect both params would be respected.  The toast should remain forever, and also have no way of dismissing it.  

### Steps To Reproduce

See "Current Behavior"

**Comment by endigo9740** [comment]
> I'd expect both params would be respected. The toast should remain forever, and also have no way of dismissing it.

This is exactly the scenario we're trying to avoid. This feature is working as intended. We do not want stranded toasts that remain forever. If you need to display something like this, you'll need to find another solution.

**Comment by let4be** [comment]
> > I'd expect both params would be respected. The toast should remain forever, and also have no way of dismissing it.
> 
> This is exactly the scenario we're trying to avoid. This feature is working as intended. We do not want stranded toasts that remain forever. If you need to display something like this, you'll need to find another solution.

lol what? this makes no sense whatsoever, let devs do what they want
spent half an hour trying to figure out wtf is going on, it's also not documented anywhere

**Comment by endigo9740** [comment]
> lol what? this makes no sense whatsoever, let devs do what they want

As stated above, implementing both of these features at once would result in a toast that's permanently present on the screen with no way to ever remove it. Like zero. It would be there forever. That's not really a great UX experience.

> spent half an hour trying to figure out wtf is going on, it's also not documented anywhere
We accept pull requests.

Welcome to open source, we accept pull requests. Feel free to send one :)

**Comment by let4be** [comment]
aka I obviously could do this it's just the lib would hide toast before I intend to do this with the code, unless I specify arbitrary large timeout(ignoring my `autoHide: false`)

**Comment by endigo9740** [comment]
@let4be yes I'm aware, I'm the author of this feature. I understand how it operates.

That said, we cannot depend on developers to use programmatic control. Meaning there's a use case that leaves end users with orphaned toasts. We are taking it upon ourselves to help avoid that - especially as it may occur unintentionally on the developer's part. So we've put a safety rail in place.

It sounds like you're trying to create a long lasting modal on the screen, which is not the intention of this feature. Toasts are intended to be brief messages that are either:

1. Dismissed by the user via the on-screen action
2. Auto-hide after X amount of time

Any use case beyond that is out of scope.

**Comment by let4be** [comment]
My use case seems to fit in a toast, it's just my time interval is dynamic and asynchronous task related

Aka I'm displaying "your request is being processed" toast and hide it when it's done(try/finally)

I can only do this using a programmatic interface which has some awkward restrictions, but yea I probably could go with a modal
