### ISSUE TITLE
Button accessiblity in Wintry theme

### ISSUE THREAD

**Issue by hmnd** [skeletonlabs/skeleton#1986]
### Current Behavior

Menu items in the new Wintry theme do not meet the WCAG minimum contrast ratios.
![image](https://github.com/skeletonlabs/skeleton/assets/12853597/c06c4cff-ba44-4b76-adc6-6311059dceac)

### Expected Behavior

Menu item text meets the WCAG contrast ratios.

### Steps To Reproduce

Use a contrast checker, such as one built into Firefox or at https://webaim.org/resources/contrastchecker/

### More Information

The primary background or active text color for the Wintry theme may need to change as a result of this issue.

**Comment by endigo9740** [comment]
@hmnd both the Primary and Secondary "on" color (which control text/fill contrast) were both a bit off. The new PR going in now will update both of these. Expect to see this as part of next week's release.

FYI we have some theme updates planned in the near future, so definitely plan to give each theme a bit more attention in this regard. In the meantime, thanks for the heads ups!
