### ISSUE TITLE
XSS Vulnerability in Table Component due to HTML tags

### ISSUE THREAD

**Issue by nas-tabchiche** [skeletonlabs/skeleton#1987]
Hello,

I have been using the Skeleton component library at work and have come across a potential security vulnerability in the [Table](https://www.skeleton.dev/components/tables) component. It parses raw HTML strings through HTML tags, which exposes it to cross-site scripting (XSS) attacks. I believe this needs to be addressed urgently.

## Details:

When strings are passed to the table component, it gets rendered through HTML tags, therefore circumventing Svelte's string sanitation, making it prone to XSS.

https://github.com/skeletonlabs/skeleton/blob/72bd820dc65fefa61523a7d71eef6feed354dfed/packages/skeleton/src/lib/components/Table/Table.svelte#L102

## Why this is a serious security risk:

Here the main danger is the fact that developers using the Table component might not be aware that cells are rendered through HTML tags, which is very dangerous in the event that user-input strings are passed to the component without sanitation. Which is likely, as Svelte already sanitizes strings (outside of HTML tags).

XSS vulnerabilities open us up to a whole world of hurt:

- An attacker can manipulate the table's data or any other DOM elements.
- If an attacker can run arbitrary JavaScript code, they can access and send the user's cookies to a remote server, compromising their session.
- The attacker can create fake overlays or pop-ups asking the user for sensitive information.
- The attacker could use XSS to redirect the user to malicious websites that host malware.

## Recommendations:

Best to worst in my opinion:

1. **Opt-in HTML tags:** Instead of default HTML parsing behavior, make it opt-in. This way, developers are actively making a choice to accept HTML content, hopefully with the understanding of its implications.
2. **Opt-out HTML tags:** If not opting in, allow developers to opt-out of the HTML parsing functionality. This would allow the patch to be non-breaking.
3. **Warning in the documentation:** At the very least, there should be a clear warning in the documentation stating that the table component parses raw HTML and that users should sanitize the input they pass to it.

Thank you for taking the time to consider this issue. I believe skeleton is bound to be a leader in the svelte space, and as such security should be paramount. As a user of the library, I am looking forward to seeing how it will evolve.

Best regards,

Nassim

**Comment by HugeLetters** [comment]
I agree options 1 or 2 should be added to the library - same goes for the Autocomplete component.
I think adding a prop to toggle this behavior should be a very easy-to-add solution.  

While I agree sanitation should be handled by the library users - I don't think that's the case here.
As in when I render a button I(and I assume most people) usually do this:
```html
<button>{label}</button>
```

not this
```html
<button>{@html sanitize(label)}</button>
```

**Comment by atuttle** [comment]
I just want to chime in to say that I'm intentionally using HTML inside of table contents to accomplish functionality that isn't available in a Skeleton table otherwise. Whatever is done, if anything, I do hope that there is a way to opt-in to continuing to render raw html.

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2361
