### ISSUE TITLE
InputChip component not correctly passing name through to input

### ISSUE THREAD

**Issue by zachsa999** [skeletonlabs/skeleton#1988]
### Current Behavior

InputChip doesn't seem to be passing `name` through to the component declaration. I just upgraded to version 2.0 and this is still an issue. 

It looks like name is applied to the text input, not the actual select array.

### Expected Behavior

```
<InputChip
  id="chips"
  bind:value={selectedItems}
  name={name}
  bind:searchString
  on:input={handleSearchInput}
  on:remove={() => focusChips()}
  {placeholder}
/>
```

name should appear as a name in the dom, but it doesn't

**Comment by Hugos68** [comment]
Hey @zachsa999, I tested this locally and in the skeleton fork. I am unable to reproduce this behavior, the name attribute is present and form submissions are working correctly. Could you create a [reproduction](https://stackblitz.com/fork/github/skeletonlabs/repl/tree/main/welcome)?
It would also be appreiciated if you could share your OS and browser where this issue occured.

**Comment by Hugos68** [comment]
Side note, I just realized the stackblitz currently doesn't use v2, this is known and will hopefully be adressed soon: #1995
Because you said you were experiencing the issue both in v1 and v2 I wouldn't mind a reproduction in the stackblitz but for best testing results a fresh project using the CLI provides the most accurate repro.

**Comment by zachsa999** [comment]
Closing this. I made a minimal reproduction of the issue, and solved the problem with using {name} instead of name={name}. This shouldn't change anything, but it did, and I so want to spend any more time on it

**Comment by Hugos68** [comment]
Doing shorthard ``{prop}`` syntax only works for props to components, not html attributes FYI.
