### ISSUE TITLE
Include appshell styles inside the component

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#1993]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

According to the docs in order for the App Shell to work correctly you need:
```css
html, body { @apply h-full overflow-hidden; }
```
and
```html
<body>
	<div style="display: contents" class="h-full overflow-hidden">%sveltekit.body%</div>
</body>
```
First of all, because of ``display: contents`` I am 99% sure you don't need ``h-full`` and ``overflow-hidden`` sine the body will ignore that div [according to mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/display#box). I have not tested this in practise though.

My proposed solution to this would be this:
```html
<style>
  :global(html, body) {
      height: 100%;
      overflow: hidden;
  }
</style>
```
If the ``h-full overflow-hidden`` classes are still required in the div of the body you could do this:
```html
<style>
   /* 
      Notice the :first-child selector, this allows people to add more divs inside their body if desired.
      This would break when people insert a div in front of the ``display: contents`` div, 
      perhaps a note should be added to the docs.
      This would be an extremely rare use case but a use case non-the-less.
   */
  :global(html, body, body > div:first-child) {
      height: 100%;
      overflow: hidden;
  }
</style>
```
The reason for this change is to remove the disconnected steps to get a working App Shell, if you remove the App Shell but forget to remove the global styles you can get some funky behavior (I've had this happen in the past). With this solution you wouldn't need to do any extra steps to get a working app shell since the styles come with the app shell rather than a manual step.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Cool idea, I like it. Some testing is required, but might be worthwhile!

**Comment by Hugos68** [comment]
Is it okay if I start testing this? Or is this something that won't be interesting until v3 becomes RC and all that stuff?

**Comment by endigo9740** [comment]
Leave this one to me for now. I'd like to investigate it first. It'll require several updates to the documentation if we move forward with this.

**Comment by tysonclugg** [comment]
I'm +½ on applying a `:global(...)` style.  I'm a little unclear on if this creates a demarcation issue - should the library user or library developer be ultimately responsible for applying necessary top-level application styles?

While addressing this, we should ensure `display: contents` is not used. MDN mentions [accessibility concerns](https://developer.mozilla.org/en-US/docs/Web/CSS/display-box#accessibility_concerns) regarding `display: contents` - it seems that [Safari still doesn't play nice](https://adrianroselli.com/2022/07/its-mid-2022-and-browsers-mostly-safari-still-break-accessibility-via-display-properties.html#Verdict) with accessibility apps when `display: contents` is in use.

**Comment by endigo9740** [comment]
@tysonclugg as Hugos mentioned, this is applied by SvelteKit by default. Here's Rich Harris reasoning for this:
https://github.com/sveltejs/kit/discussions/7585

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2383
