### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by cycle4passion** [skeletonlabs/skeleton#1994]
### Link to the Page

https://www.skeleton.dev/docs/transitions

### Describe the Issue (screenshots encouraged!)

Doesn't it seem like new transitions Component should be under Svelte section rather than Docs? Took me a while to find it.

**Comment by Sarenor** [comment]
It's not a component though, it's an overarching Skeleton Feature that allows for custom transitions on components that support it.
Components that support it also link to the transitions page:
<img width="769" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/31982384/429ae58f-5cee-4b95-b001-4a97eb6ffdc3">

It's the same place where variants and other over spanning concepts are explained so I think it fits quite well.

**Comment by cycle4passion** [comment]
OK, I get it, and agree.
