### ISSUE TITLE
Updated Stackblitz projects to Skeleton v2

### ISSUE THREAD

**Issue by cycle4passion** [skeletonlabs/skeleton#1995]
### Link to the Page

https://www.skeleton.dev/

### Describe the Issue (screenshots encouraged!)

With the official release of Version 2 the Stackblitz project needs updated to V2 too.

**Comment by endigo9740** [comment]
@niktek let me know if you want to take this, otherwise I'll try to jump on this sometime this week

**Comment by endigo9740** [comment]
Pending review here:
https://github.com/skeletonlabs/repl/pull/2
