### ISSUE TITLE
Transitions Docs Error?

### ISSUE THREAD

**Issue by cycle4passion** [skeletonlabs/skeleton#1996]
### Link to the Page

https://www.skeleton.dev/docs/transitions

### Describe the Issue (screenshots encouraged!)

The V2 Docs say

Parameters
You can modify parameters for both the default in and out transitions.

```HTML
<ExampleComponent transitionInParams={{ duration: 400 }} />
```

I believe it should be
```HTML
<ExampleComponent transitionParams={{ duration: 400 }} />
```

i.e. removing the "In". It is a little hard to verify this as the Transitions are handled within each support Component.

**Comment by endigo9740** [comment]
No I believe this is correct, Supporting the combined `transition` would have meant we needed to support combined/in/out, so we opted for explicit in/out only

**Comment by endigo9740** [comment]
@Mahmoud-zino can confirm if I'm incorrect here

**Comment by Mahmoud-zino** [comment]
> No I believe this is correct, Supporting the combined `transition` would have meant we needed to support combined/in/out, so we opted for explicit in/out only

Correct handling the combined prop will make the logic behind it a lot more complex and harder to maintain with very minimum benefits!
