### ISSUE TITLE
queryElements argument of tocCrawler has no effect

### ISSUE THREAD

**Issue by Eggrror404** [skeletonlabs/skeleton#1997]
### Current Behavior

Whatever `queryElements` is set to, the default value isn't changed (which is `h2, h3, h4, h5, h6`).

### Expected Behavior

The argument overrides the default value, querying what the user expected.

### Steps To Reproduce

1. Use the `tocCrawler` action, with `queryElements` set to something like `h1, h2`.
2. In `TableOfContents` component, only h2-h6 headings appear.

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-skeleton-template-bare-7e82xp?file=src%2Froutes%2F%2Bpage.svelte

### More Information

The issue happens here: https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/utilities/TableOfContents/crawler.ts#L28-L33

`queryElements` needs to be overridden before calling `querySelectorAll`.

**Comment by endigo9740** [comment]
@Eggrror404 make sure test on a CLI generated project, not the Stackblitz. The Stackblitz version is still running v1. We have an open ticket to address this soon.

Per the code you linked, you can see the provided querElements are set here:
https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/utilities/TableOfContents/crawler.ts#L33

**Comment by Eggrror404** [comment]
> Per the code you linked, you can see the provided querElements are set here:
> https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/utilities/TableOfContents/crawler.ts#L33

But they are set (on L33) _after_ the headings has been selected (on L29). Though tocCrawler has an update function, it wouldn't reflect on the latest queryElements.

> @Eggrror404 make sure test on a CLI generated project, not the Stackblitz. The Stackblitz version is still running v1.

I forked this project https://github.com/skeletonlabs/skeleton-template-bare into Stackblitz, which was on v2.0-rc. Sorry I didn't notice it's on rc.

I've updated it to v2.0, and the issue persists: queryElements is not overridden before the headings are selected.

@endigo9740 please check this issue again. I believe this isn't resolved just yet, or please correct me if I'm wrong.

**Comment by endigo9740** [comment]
Ok, we'll check again.

**Comment by endigo9740** [comment]
@Eggrror404 I confirmed this was a bug due to incorrect oder of operations in the located you reference. I've implemented a fix in the new pull request and this should go out as part of next week's release. Thanks for pointing this out!
