### ISSUE TITLE
Modal opens behind the Dialog Element

### ISSUE THREAD

**Issue by karianpour** [skeletonlabs/skeleton#2001]
### Current Behavior

If the page has Dialog (<dialog>) open, the modal opens behind the dialog.

### Expected Behavior

The modal should open in front of the <dialog> elements

### Steps To Reproduce

1. Have a <dialog> element in the page
2. Open a skeleton UI modal
3. you see that the modal is behind 

### More Information

I guess that we need to use the dialog element for the modal to work properly with the <dialog> tag

**Comment by Sarenor** [comment]
Do you mean the native html ``dialog`` element?
If so, is there a reason why you're mixing Skeleton Modals and html dialog?

Skeleton is unable to display content above a native html dialog for the reasons outlined in this stackoverflow post:
https://stackoverflow.com/a/41816764/9187412

@endigo9740 initially investigated using ``dialog`` elements to display a Modal, but things didn't pan out in the accessibility and customizabilty department so Skeleton is currently rolling a solution without the Dialog element.ö

**Comment by karianpour** [comment]
Thanks for the answer.

I need to have a dialog, in my web app, so I need to use a dialog. Then while the dialog is open, I need to prompt the user some information.

Having dialog with native html dialog tag is very convenient.

I understand that changing a library which many people is using is not trivial, however, as skeleton UI does not provide a dialog component, I need to address this issue in a way myself.

**Comment by Sarenor** [comment]
You could try flipping your contents around. First, use the modal to display the dialog, then use the dialog element to capture the additional information that you need.

If that's currently possible and makes sense. Good luck!
