### ISSUE TITLE
image zoom component

### ISSUE THREAD

**Issue by Vaalley** [skeletonlabs/skeleton#2005]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

A feature I think would be cool is a way to wrap our images into *something* and it would allow the user to click on it and it would zoom, if multiple images are wrapped it even allows to got through them using keyboard arrows, a good example of this is from Modrinth: https://modrinth.com/modpack/versatile/gallery

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

https://modrinth.com/modpack/versatile/gallery

**Comment by Mahmoud-zino** [comment]
Hey @Vaalley,
imho this sounds like a custom carousel.
I don't think this is something skeleton should handle because it is very specific and you can create it using the scroll-containers approach. see https://www.skeleton.dev/elements/scroll-containers#carousels

**Comment by endigo9740** [comment]
@Vaalley I agree with @Mahmoud-zino. This sounds like a custom modal using the combination of the following:

- https://www.skeleton.dev/utilities/modals#component-modals
- https://www.skeleton.dev/elements/scroll-containers

In fact we provide a image modal as once of the examples of custom component modals. Find the source here:
https://github.com/skeletonlabs/skeleton/blob/master/sites/skeleton.dev/src/lib/modals/examples/ModalExampleImage.svelte

We try to build Skeleton in such a way that it provides a set of privatives (read: building blocks) that can be composed in different ways to cover the specific needs of your project. In this case, I think this would be the ideal approach.

I'm going to close this issue, as this request should covered right now. But if you have any questions about implementing the above features I will see comments here - likewise we provide support through our GitHub Discussions section, as well as the support sections on our Discord. Happy to help as we can.

**Comment by Vaalley** [comment]
> @Vaalley I agree with @Mahmoud-zino. This sounds like a custom modal using the combination of the following:
> 
> * https://www.skeleton.dev/utilities/modals#component-modals
> * https://www.skeleton.dev/elements/scroll-containers
> 
> In fact we provide a image modal as one of the examples of custom component modals. Find the source here: https://github.com/skeletonlabs/skeleton/blob/master/sites/skeleton.dev/src/lib/modals/examples/ModalExampleImage.svelte
> 
> We try to build Skeleton in such a way that it provides a set of privatives (read: building blocks) that can be composed in different ways to cover the specific needs of your project. In this case, I think this would be the ideal approach.
> 
> I'm going to close this issue, as all of this should be possible right now. But if you have any questions about implementing the above features I will see comments here - likewise we provide support through our GitHub Discussions section, as well as the support sections on our Discord. Happy to help as we can.

Never thought of combining those utilities together, great idea!
