### ISSUE TITLE
Update theme override docs for custom fonts

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2008]
### Link to the Page

https://dev.skeleton.dev/docs/themes#custom-fonts

### Describe the Issue (screenshots encouraged!)

Per this Discord discussion:
https://discord.com/channels/1003691521280856084/1149358151171321856/1149358151171321856

We need to update the Theme > Custom Fonts documentation to reflect the correct selected for custom fonts in v2. Likewise, we should go ahead and include this as a tip in the migration guide (for late adopters)

**Comment by Elliott-Green** [comment]
I think users probably get tripped up because of this vite warning.

```bash
[vite:css] @import must precede all other statements (besides @charset or empty @layer)
4  |  @tailwind utilities;
5  |  @tailwind variants;
6  |  @import url('https://fonts.googleapis.com/css2?family=Phudu:wght@300;400;500;600;700;800;900&display=swap');
   |   ^
7  |  html,
8  |  body { (x2)
```

Can confirm moving it below the tw directives and then changing the :root selector to point at the theme name works! Thanks.

**Comment by endigo9740** [comment]
Hmm that is a frustrating error if so. Seems to be at odds with Tailwind's recommendation. I'll definitely try to have a fix for this in place by the new release next week though.
