### ISSUE TITLE
Unable to trigger response from custom modal if it was closed by backdrop click

### ISSUE THREAD

**Issue by Mero-Plaform** [skeletonlabs/skeleton#2009]
> #### Remark
> At this one I faced multiple problems, so I'm asking you not to close the issue immediately, I will extend in with > new comment after we deal with this one. Just don't want to spam with issues, it's the mutual theme for a few cases.

### Current Behavior

We can send response from our modal by `$modalStore[0].response('myResponseDataHere');` according to <a href="https://www.skeleton.dev/utilities/modals#component-modals"> skeleton.dev/utilities/modals#component-modals</a>.

But how we should achieve this for `modal:type="component"` when the modal is closing by backdrop click? (In this case we getting a response as `undefined`)

I didn't find any mentions or examples for this case.

There is `on:backdrop` event for `<Modal />` but in this case we need to store somewhere handler for the current open modal and set it on modal opens, so the `on:backdrop` will call the right handler for particular modal, which is quite too complicated then it should be.

Edit: Also modal `ESC` handler returns only `false`.

### Expected Behavior

Particular modal closing detection, like passing `on:backdrop` handler in `modalStore.trigger()` so and for closing by `ESC` button.

**Comment by Mahmoud-zino** [comment]
@Mero-Plaform 
This is still possible if you check the response for:
1. false -> closed
2. undefined -> backdrop click
3. your data -> prompt submit

and handle the different responses in your `ModalSettings`
