### ISSUE TITLE
Theme Generator and Tailwind Plugin issues with quoted font-family refs

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#2010]
### Current Behavior

In the theme generator, if you create a theme with a serif font, it incorrectly outputs a double quoted string:

`"--theme-font-family-base": "ui-serif, Georgia, Cambria, "Times New Roman", Times, serif",`

Furthermore, no matter what combo of " or ' or ` I use to try and escape that font-family ref, the plugin will barf about app.postcss (presumably from the injected classes) and I suspect that it might be doing something like a string split on the commas to get the font family names ?

**Comment by endigo9740** [comment]
Resolved by https://github.com/skeletonlabs/skeleton/pull/1999
