### ISSUE TITLE
New Component: Swapper

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#202]
Reference:
https://daisyui.com/components/swap/

Implementation should be as follows:

Should use the context API to communicate between parent/child components. This allows for an infinite number of items to toggle through. This would be useful for things like dark mode toggles where you have multiple states: `system | dark | light`
```html
<Swapper state={stringValue}>
    <SwapperItem value="a">Item A</SwapperItem>
    <SwapperItem value="b">Item B</SwapperItem>
    <SwapperItem value="c">Item C</SwapperItem>
</Swapper>
```

Please follow our contribution guidelines when implementing any new component!
https://skeleton.brainandbonesllc.com/docs/contributions

**Comment by endigo9740** [comment]
Alternative idea: apply a Svelte action to a parent element. Then follow the same logic flow. Initially on the first item is visible, each tap toggles to the next, and when you reach the end it returns to the start to loop again.

**Comment by ryceg** [comment]
I'll take this

**Comment by endigo9740** [comment]
I've assigned it to you. Thanks!

**Comment by endigo9740** [comment]
This is kind of fluff, so I'm going to retire it. We can always revisit another time.
