### ISSUE TITLE
Autocomplete HTML expression in label

### ISSUE THREAD

**Issue by HugeLetters** [skeletonlabs/skeleton#2022]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I think using an html expression for a label should be enabled by a prop - otherwise there's no way to escape this behavior if it's unwanted.

In our app user can attach tags to an entity - he can input arbitrary values but he also gets autocomplete for tags submitted by other users. So if I wanna display those tags as labels I would need to sanitize each submitted tag.

I can implement this feature and issue a PR myself.

However I would have to note that to me it seems logical the default behavior should be that html expression should be turned off - meaning it would be a breaking change for people who might be using it. 

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

Here's the [feature](https://github.com/skeletonlabs/skeleton/blob/620aaafa697043fd099c7abc3585e1b0b12b546c/packages/skeleton/src/lib/components/Autocomplete/Autocomplete.svelte#L162) I'm referring to.

**Comment by endigo9740** [comment]
I believe this may be a duplicate to this current proposal.

https://github.com/skeletonlabs/skeleton/issues/1987

I like the prop idea, so that might be one way to go about it. But yeah, we would need to match current behavior to implement in a non-breaking fashion.

**Comment by HugeLetters** [comment]
Duplicate of #1987

**Comment by HugeLetters** [comment]
Duplicate of #1987
