### ISSUE TITLE
Syntax highlighting in code blocks breaks with purgeCss

### ISSUE THREAD

**Issue by moritzhertler** [skeletonlabs/skeleton#2024]
### Link to the Page

https://www.skeleton.dev/utilities/codeblocks#configure-your-project

### Describe the Issue (screenshots encouraged!)

The "**Configure Your Project**" section may benefit from an example of how to configure `PurgeCSS` correctly when importing a `highlight.js` style sheet. Especially because create-skeleton-app now uses `PurgeCSS` by default. 

![image](https://github.com/skeletonlabs/skeleton/assets/25606653/e2beac3b-611f-42b7-8ec2-c4e428fc3071)

The correct configuration is already documented in the [PurgeCSS section](https://www.skeleton.dev/docs/purgecss#safelisting). Without safe-listing classes with the `hljs-` prefix, syntax highlighting won't work in the bundled app. When using the vite dev server though, highlighting works as expected. This makes this harder to catch but is easily preventable by improving the documentation.  

I'd be happy to fix this and open a PR.

**Comment by endigo9740** [comment]
I'm going to ping @AdrianGonz97 here to review, he's the author of the PurgeCSS plugin. We'll follow his recommendation here.

**Comment by AdrianGonz97** [comment]
@moritzhertler Thanks for raising an issue and for the suggestion! This is a great idea. Since the plugin is now installed by default, we should definitely add a note/reference to the plugin along with instructions for this particular configuration.
