### ISSUE TITLE
Stepper Update

### ISSUE THREAD

**Issue by cycle4passion** [skeletonlabs/skeleton#2026]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Considered Changes:
- Add Stepper component Events (on:init, on:abort, on:destroy) in addition to existing Events (on:next, on:back, on:complete)
- Add option 'canAbort' to allow aborting the Stepper and supporting UI implementation

Should I make a PR?

The Stepper component is by nature complex and multi-stepped. I had a use case where a Toggle would show/hide the Stepper. I needed to initialize some vars on showing, and clear them on closing whether completed or aborted. I tried to do this via the existing on:step (a component event not documented on site), however on:step is not called on first show of Step 1. This is probably an error in logic, but I didn't want to change it so as to not make a breaking change. 

What I needed was an on:init, so I added it and also threw in an on:destroy and on:abort (more to come for on:abort below).

When working within the Steps, the current implementation leaves you somewhat "locked in". You either have to include the [Navigation Slot](https://www.skeleton.dev/components/steppers#navigation-slot) to allow for abort (Step 1 Only), or go through it all the Steps and 'Complete" the Stepper. 

In my use case, I wanted to provider users an easy "abort" but not clutter up the UI. I added an optional 'canAbort' prop (in addition to buttonAbort prop for style, and buttonAbortLabel prop mimicking the same for Complete, Back, and Next). The UI implentation is an extra badge at the end of the steps in the timeline header. When clicked It calls the on:abort event.

What does it look like ?

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/skeletonlabs-repl-7p73u4?file=src%2Froutes%2F%2Bpage.svelte)

Should I make a PR?

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Hey @cycle4passion the Stepper is one of a small handful of features in Skeleton that we see a lot of issues around. As such, I am planning to invest some time into updating and reimagining this feature in the near future. We have an open issue for this here:

- https://github.com/skeletonlabs/skeleton/issues/1780

Right now we have a laundry list of ideas, but overall the goal is to create something less structured and formal so folks can bend this to the variety of use case they have in mind for a feature like this. As part of this process this feature is in somewhat of a feature freeze right now. As the more we build in now, the more we have to port forward going forward.

To put it another way. I can't promise every feature added will make it's way to the next version, which sets expectations that we might not be able to meet. Therefore I think it's wise to leave this as is for now.

If you have specific requirements for the feature, and it looks like you've already implemented, I'd suggest maybe just taking ownership of the feature for yourself. Create a local instance of the component with your changes for now. There's nothing wrong with that, and in fact the open nature of Skeleton encourages this.

Note that I'm going to close this thread, per the reasons stated above, but I WILL link to this in the main thread. That way this can be taken into consideration in the future. If you wish to add any other ideas, I'd ask that you please do so in the linked issue  comments. I will see them when we get to that point.
