### ISSUE TITLE
2.0 JS to CSS Theme integration fails to load *any* theme

### ISSUE THREAD

**Issue by traviszuleger** [skeletonlabs/skeleton#2028]
### Current Behavior

I followed the guide step for step to update and set up the CSS to JS custom theme, and yet nothing loads (this is the same behavior for when I do the skeleton default theme too)

### Expected Behavior

I expect my theme to work as expected, leaving my site exactly how it was before.

### Steps To Reproduce

1. From Skeleton 1.2, have a default project set up using JS typed typescript. (Skeleton project)
2. Update Skeleton to the latest
3. Create `custom-theme.js` in your root folder
4. Go to `tailwind.config.js` and update to look like the guide's version.
5. Go to `src/app.html` and update `<body>` with tag `data-theme` with value of `custom-theme`
6. `npm run dev`

### More Information

I also tried many other ideas to get it to work, including reproducing the same setup for the `skeleton.dev` website, as well as just trying with the simple preset theme of skeleton's.

Here are all my config files.

`vite.config.js`
```js
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()]
});
```

`tailwind.config.js`
```js
import { join } from 'path';
import { myCustomTheme } from './custom-theme';
import { skeleton } from '@skeletonlabs/tw-plugin';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: 'class',
	content: [
        '../**/*.{html,js,svelte,ts}', 
        join(require.resolve(
            '@skeletonlabs/skeleton'), 
            '../**/*.{html,js,svelte,ts}'
        )
    ],
	theme: {
		extend: {},
	},
	plugins: [
        forms,
        typography,
        skeleton({
            themes: {
                preset: [
                    "skeleton"
                ],
                custom: [
                    myCustomTheme
                ]
            }
        })
    ],
}
```

`svelte.config.js`
```js
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/kit/vite';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [
		vitePreprocess({
			style: {
				css: {
					postcss: join(__dirname, 'postcss.config.cjs')
				}
			}
		})
	],
	kit: {
		adapter: adapter()
		// https://kit.svelte.dev/docs/configuration#alias
	}
};

export default config;
```

`postcss.config.cjs`
```js
const path = require('path');
const tailwindcss = require('tailwindcss');
const autoprefixer = require('autoprefixer');

module.exports = {
	plugins: [tailwindcss(path.resolve(__dirname, './tailwind.config.js')), autoprefixer]
};
```

`custom-theme.js`
```js
/** @type {import('@skeletonlabs/tw-plugin').CustomThemeConfig} */
export const myCustomTheme = {
    name: 'deploy-mngr',
    properties: {
		// =~= Theme Properties =~=
		"--theme-font-family-base": "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
		"--theme-font-family-heading": "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
		"--theme-font-color-base": "0 0 0",
		"--theme-font-color-dark": "255 255 255",
		"--theme-rounded-base": "24px",
		"--theme-rounded-container": "6px",
		"--theme-border-base": "1px",
		// =~= Theme On-X Colors =~=
		"--on-primary": "0 0 0",
		"--on-secondary": "var(--color-primary-50)",
		"--on-tertiary": "0 0 0",
		"--on-success": "0 0 0",
		"--on-warning": "0 0 0",
		"--on-error": "255 255 255",
		"--on-surface": "var(--color-primary-50)",
		// =~= Theme Colors  =~=
		// primary | #00b315 
		"--color-primary-50": "217 244 220", // #d9f4dc
		"--color-primary-100": "204 240 208", // #ccf0d0
		"--color-primary-200": "191 236 197", // #bfecc5
		"--color-primary-300": "153 225 161", // #99e1a1
		"--color-primary-400": "77 202 91", // #4dca5b
		"--color-primary-500": "0 179 21", // #00b315
		"--color-primary-600": "0 161 19", // #00a113
		"--color-primary-700": "0 134 16", // #008610
		"--color-primary-800": "0 107 13", // #006b0d
		"--color-primary-900": "0 88 10", // #00580a
		// secondary | #015b13 
		"--color-secondary-50": "217 230 220", // #d9e6dc
		"--color-secondary-100": "204 222 208", // #ccded0
		"--color-secondary-200": "192 214 196", // #c0d6c4
		"--color-secondary-300": "153 189 161", // #99bda1
		"--color-secondary-400": "77 140 90", // #4d8c5a
		"--color-secondary-500": "1 91 19", // #015b13
		"--color-secondary-600": "1 82 17", // #015211
		"--color-secondary-700": "1 68 14", // #01440e
		"--color-secondary-800": "1 55 11", // #01370b
		"--color-secondary-900": "0 45 9", // #002d09
		// tertiary | #65a749 
		"--color-tertiary-50": "232 242 228", // #e8f2e4
		"--color-tertiary-100": "224 237 219", // #e0eddb
		"--color-tertiary-200": "217 233 210", // #d9e9d2
		"--color-tertiary-300": "193 220 182", // #c1dcb6
		"--color-tertiary-400": "147 193 128", // #93c180
		"--color-tertiary-500": "101 167 73", // #65a749
		"--color-tertiary-600": "91 150 66", // #5b9642
		"--color-tertiary-700": "76 125 55", // #4c7d37
		"--color-tertiary-800": "61 100 44", // #3d642c
		"--color-tertiary-900": "49 82 36", // #315224
		// success | #17c700 
		"--color-success-50": "220 247 217", // #dcf7d9
		"--color-success-100": "209 244 204", // #d1f4cc
		"--color-success-200": "197 241 191", // #c5f1bf
		"--color-success-300": "162 233 153", // #a2e999
		"--color-success-400": "93 216 77", // #5dd84d
		"--color-success-500": "23 199 0", // #17c700
		"--color-success-600": "21 179 0", // #15b300
		"--color-success-700": "17 149 0", // #119500
		"--color-success-800": "14 119 0", // #0e7700
		"--color-success-900": "11 98 0", // #0b6200
		// warning | #d19d00 
		"--color-warning-50": "248 240 217", // #f8f0d9
		"--color-warning-100": "246 235 204", // #f6ebcc
		"--color-warning-200": "244 231 191", // #f4e7bf
		"--color-warning-300": "237 216 153", // #edd899
		"--color-warning-400": "223 186 77", // #dfba4d
		"--color-warning-500": "209 157 0", // #d19d00
		"--color-warning-600": "188 141 0", // #bc8d00
		"--color-warning-700": "157 118 0", // #9d7600
		"--color-warning-800": "125 94 0", // #7d5e00
		"--color-warning-900": "102 77 0", // #664d00
		// error | #ad0000 
		"--color-error-50": "243 217 217", // #f3d9d9
		"--color-error-100": "239 204 204", // #efcccc
		"--color-error-200": "235 191 191", // #ebbfbf
		"--color-error-300": "222 153 153", // #de9999
		"--color-error-400": "198 77 77", // #c64d4d
		"--color-error-500": "173 0 0", // #ad0000
		"--color-error-600": "156 0 0", // #9c0000
		"--color-error-700": "130 0 0", // #820000
		"--color-error-800": "104 0 0", // #680000
		"--color-error-900": "85 0 0", // #550000
		// surface | #055c00 
		"--color-surface-50": "218 231 217", // #dae7d9
		"--color-surface-100": "205 222 204", // #cddecc
		"--color-surface-200": "193 214 191", // #c1d6bf
		"--color-surface-300": "155 190 153", // #9bbe99
		"--color-surface-400": "80 141 77", // #508d4d
		"--color-surface-500": "5 92 0", // #055c00
		"--color-surface-600": "5 83 0", // #055300
		"--color-surface-700": "4 69 0", // #044500
		"--color-surface-800": "3 55 0", // #033700
		"--color-surface-900": "2 45 0", // #022d00
		
	}
}
```

`src/app.html`
```html
<!DOCTYPE html>
<html lang="en" class="dark">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" href="%sveltekit.assets%/favicon.png" />
		<meta name="viewport" content="width=device-width" />
		%sveltekit.head%
	</head>
    <!-- Also tried the theme of "skeleton" -->
    <body data-theme="deploy-mngr">
        <div style="display: contents" class="h-full overflow-hidden">%sveltekit.body%</div>
    </body>
</html>
```

Stuck on working on this project until someone can tell me what I am doing wrong.

(I also removed all imports other than the `app.postcss` import in my `+layout.svelte` files and removed my old theme file from 1.2)

**Comment by Sarenor** [comment]
2 questions so far:
1) Considering the (thankfully extensive, thanks for that!) code samples, I assume it's a private project that you can't share?
2) does your ``app.postcss`` include the Tailwind directives?

**Comment by endigo9740** [comment]
@traviszuleger @Sarenor 

I'll append a couple other things of note from the original post above:

> 1. From Skeleton 1.2

Skeleton keeps a regular release cadence, pushing out a new update every 2 weeks. As such, v1.2 is from April, so a number of notable updates have dropped in that time. That may not have any impact on your issue at hand, but wanted to make sure it was statedly clearly here.

Here's the changelog if you would like to monitor changes since then:
https://github.com/skeletonlabs/skeleton/releases?page=4

> 2. Update Skeleton to the latest

Did you install the Skeleton Tailwind Plugin as well. This bullet point didn't make that clear. It's now a new standalone package that must be installed using (note the second package):

```
npm add -D @skeletonlabs/skeleton @skeletonlabs/tw-plugin
```

> 2. does your app.postcss include the Tailwind directives?

I'd also be curious to hear about the status of the the `@tailwind` directives. If those are present it can result in a project that appears to be unstyled (no theme colors)

**Comment by AdrianGonz97** [comment]
What the other two said 😄

I will add that I noticed that your `content` field in your `tailwind.config.js` has this `'../**/*.{html,js,svelte,ts}',`. This doesn't seem intentional and it will load _everything_ outside of your project, which will cause everything to slow down to a halt. You said things aren't "loading" so I'm inclined to say that this is the problem.

Change `'../**/*.{html,js,svelte,ts}'` to `'./src/**/*.{html,js,svelte,ts}'` instead.

**Comment by traviszuleger** [comment]
@Sarenor You are correct that it is a private repository, it is a project for my company, so it must remain private. I do not have the tailwind directives, it wasn't required in the 1.2 update (as far as I noticed from the old code I had) and there is nothing in the guides to add this. I assume this is just part of the initial startup template. After adding this, though, I get an error now: `EMFILE: too many open files, open 'C:\...\node_modules\js-yaml\lib\schema\json.js'`.

@endigo9740 it is still in the development phase, so as I've been developing (on and off) I've either decided to hold off on updating (A mistake on my part) or simply just forgot as I continued development.

@AdrianGonz97 I originally had it at `'src/**/*.{html,js,svelte,ts}'` but it wasn't working then either, I then saw inside of the repository for Skeleton (https://github.com/skeletonlabs/skeleton/blob/dev/sites/skeleton.dev/tailwind.config.js) that it had this format, so I was trying to relate it as closely as possible to solve this issue.

**Comment by Sarenor** [comment]
> 1.2 update (as far as I noticed from the old code I had) and there is nothing in the guides to add this.
Just to make sure, we are talking about these migration steps and especially 4) https://github.com/skeletonlabs/skeleton/discussions/1947 on the list?

I assume it's loading tailwind and the plugins correctly now but because it's scanning everything around your project as well, tailwind is opening to many files.
Try turning it back to ``'src/**/*.{html,js,svelte,ts}'``, Skeleton is set up that way because of it's mono repo structure and because the docs page needs to pull in the lib changes :)

**Comment by traviszuleger** [comment]
@Sarenor no I was referring to what was on the website. I did not know that guide existed. Let me look at that and respond momentarily on if it worked...

**Comment by traviszuleger** [comment]
@Sarenor @endigo9740 @AdrianGonz97
Thank you, it seems it was a combination of the tailwind directives and that path you mentioned.

As for feedback, it'd be nice if https://skeleton.dev could reference #1947 instead of only referencing bits and pieces, as it isn't  as easy to find guides through the repository.

**Comment by endigo9740** [comment]
@traviszuleger I'm not sure I follow. We link to both the release notes AND the migration guide directly on the homepage:

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/6ef9ae3e-c5cc-443f-9a2e-2a1bdab19ff3)

Additionally both posts are pinned on our GitHub Discussions section, and I believe we've reference both in all public announcements on Discord and Twitter.

The release notes themselves also link to the Migration guide as well.

We've tried to be very diligent about our redundancies for accessing this guide. Maybe we missed something?

**Comment by traviszuleger** [comment]
@endigo9740 As I am sure many people could agree with me, these websites are cached or bookmarked. I no longer first visit the homepage, and that toolbar doesn't show up on any other page. I would have never known about it if you didn't mention it now. That is my fault, but I would then suggest that that toolbar could be on all pages (with an option to dismiss it)

**Comment by endigo9740** [comment]
Gotcha, ok we'll keep that advice in mind for the future then! Glad you got things sorted though!
