### ISSUE TITLE
btn-group adds borders to children of children

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#2037]
### Current Behavior

When using the ``.btn-group`` like so:
```html
<div class="btn-group variant-filled">
    <button>
        <p>Text</p>
				<svg class="w-6 h-6">(some Icon)<svg>
    </button>
    <button>
			  <p>Text</p>
				<svg class="w-6 h-6">(some Icon)<svg>
    </button>
</div>
```
The buttons have a divider, but the text and icon inside the button *also* have a divider which is not wanted/expected behavior.

Illustration from @endigo9740:
https://cdn.discordapp.com/attachments/1151114412896309330/1151254611227852860/Screenshot_2023-09-12_at_3.34.37_PM.png

### Expected Behavior

Only direct buttons and anchors have a border, the rest is ignored

### Steps To Reproduce

1. Using the btn-group class
2. Apply it to a div
3. Add a button
4. Add a p to the button
5. Add a svg to the button
6. Observe small divider is inside the button

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-repl-cabu4o?file=src%2Froutes%2F%2Bpage.svelte

### More Information

This was discovered and discussed here: https://discord.com/channels/1003691521280856084/1151114412896309330/1151114412896309330

A possible fix would be to use the ``>`` css selector to only select children 1 level deep into the dom from the element where the ``btn-group`` is applied. We could also only allow ``button`` and ``anchor`` elements to be targeted with these styles so folks can even have other elements in the root level without being affected.

**Comment by Mahmoud-zino** [comment]
I'd suggest adding a new class, for example `group-item` and targeting the class instead to get rid of any conflicts.
On the down side, this would be a breaking change 😕

**Comment by endigo9740** [comment]
@Mahmoud-zino the change proposed would be very simple and shouldn't rock the boat at all

```css
.btn-group *+* { ... }
```

Now becomes:

```css
.btn-group > *+* { ... }
```

Simple and easy, and ensures it both works as originally intended, and meets users expectations.
