### ISSUE TITLE
Checkbox with indeterminate state

### ISSUE THREAD

**Issue by Tihomir971** [skeletonlabs/skeleton#2038]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

It would be useful to have checkbox with indeterminate state.

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@Tihomir971 this is possible with via an HTML checkbox element and a tiny bit of Javascript:

https://css-tricks.com/indeterminate-checkboxes/

```js
var checkbox = document.getElementById("some-checkbox");
checkbox.indeterminate = true;
```

In Svelte you would do something like this:

```js
const elemCheckbox;
elemCheckbox.indeterminate = true;
```
```html
<input bind:this={elemCheckbox} type="checkbox">
```

We cover our stance on this on the forms page, but we recommend you lean on native form inputs wherever possible. As such as would likely never abstract this to a component. However, you certain can if you wish!

![Screenshot 2023-09-13 at 10 44 50 AM](https://github.com/skeletonlabs/skeleton/assets/1509726/2336509f-735d-46e2-a599-20f66a05a5e8)
