### ISSUE TITLE
Refactor InputChips to use AllowList instead of WhiteList

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#2039]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

As terrxo pointed out on [Discord](https://discord.com/channels/1003691521280856084/1151473855131553852/1151487319069687900) we should be consistent in our naming and use Allow/Denylist everywhere.

Little late to notice and will have to wait until v3 for complete removal of whitelist, but at least soemone noticed.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2364
