### ISSUE TITLE
Popup element click bubbles up to parent

### ISSUE THREAD

**Issue by bighitbiker3** [skeletonlabs/skeleton#2045]
### Current Behavior

Currently if you click on an element with `use:popup` that click event bubbles up to the parent element. 

### Expected Behavior

I would expect the event to either stop propagating at the element with `use:popup` or at least be given an escape hatch to handle the click event myself

**Comment by Mahmoud-zino** [comment]
I don't think this is a responsibility of the popup, you can stop propagation yourself on the button.
something like this would work:
```svelte
<button use:popup={popupState} on:click|stopPropagation={HandleClick} >Show Popup</button>
```

**Comment by endigo9740** [comment]
I agree with @Mahmoud-zino on this one. The event modifier should be used to aid with this issue:
https://svelte.dev/docs/element-directives#on-eventname
