### ISSUE TITLE
Modals have hardcoded padding on transition element

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2050]
### Current Behavior

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/aa545a16-09e4-464b-87e3-6df59974499b)

As reported by Joost on Discord.

Let's review changing where this padding is set to ensure it's configurable per-instance. This is making it difficult for end users to create full screen components that fill the entire screen.

**Comment by Mahmoud-zino** [comment]
@endigo9740 this padding is fixed on the transition layer, since we already have a padding prop used on the modal itself should we add a new prop or just use the same prop for both?

**Comment by endigo9740** [comment]
@Mahmoud-zino I'm not sure, that's why I assigned this one to myself. I'll need to investigate. If we move forward with your approach in the PR I'll merge that, but either way I'll need to take a look and determine the best solution going forward. I'd actually like to build a full screen modal to share as one of our examples too - so we have this for reference in the future.

**Comment by Mahmoud-zino** [comment]
@endigo9740 I think you forgot to assign it to yourself, that's why I created the PR, but feel free to close it if needed 👍

**Comment by endigo9740** [comment]
Oops, yes thanks for the correction. I've assigned it and will review asap.

**Comment by endigo9740** [comment]
Including this in the v2 milestone, though I want to set expectations that this may slip to v3.
