### ISSUE TITLE
Paginators: make 'size' setting optional (fro Server-Side Pagination)

### ISSUE THREAD

**Issue by bfovez** [skeletonlabs/skeleton#2066]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

In a server-side pagination context, we often don't know in advance the size of the dataset.
Therefore, I should be great if the 'size' setting could be optional. In a such case, the showNumerals option would be 'false', and the paginator woudl show, say "11-20" and not "11-20 of 243".

Furthermore, this would be consistent with https://vincjo.fr/datatables components (the server-side pagination part of the API is https://vincjo.fr/datatables/remote).

### What type of pull request would this be?

Enhancement

**Comment by Sarenor** [comment]
Please put Stepper feedback into the appropriate refactoring issue: https://github.com/skeletonlabs/skeleton/issues/1780

**Comment by Sarenor** [comment]
Sorry for the confusing comment notification, I'm not quite awake today.
I think we'd need to do a bit more than that to get the Paginator fully working with SSR, but this is a good start!

**Comment by bfovez** [comment]
Thank you for your response.
Indeed, for now, that's all I need to get Paginator to work with
https://github.com/vincjo/datatables.
The Paginator's 'page' and 'amount' events would then send the relevant
data to the vincjo datatable remote handler.

**Comment by Sarenor** [comment]
For Vincjo, maybe. For actual pagination with SSR via query parameters & no client JS required, not quite.
We're aware of that, just haven't come up with a good solution yet.

**Comment by endigo9740** [comment]
@bfovez @Sarenor sorry for my late response on this one, but just so you're away, I'm overdue for creating a proper guide to using vincjo datatables. Given they are currently our official recommendation for datatables, we definitely want want all pagination features to work with these out of the box.

That said, I can see how size might pose an issue here. While most (read: good) server side solutions should be able to inform you of the total item size, I do agree that we should support those situations where this is not provided. Given this, I think it would be ideal to make `size` optional. This would involve two notable changes:

1. We need to make the `size` value optional in the type definition
2. We need to update the Pagination component UI to hide the size if not present.

> [!WARNING]  
> Just a heads up when implementing this - be mindful that Javascript can tree zero (`0`) the same as null/undefined, so we need to be very explicit with the logic used here.

@Mahmoud-zino if you're interested, this might be a great one for you to jump on!

**Comment by Mahmoud-zino** [comment]
@endigo9740 I would be happy to work on it 👍

**Comment by Sarenor** [comment]
Off you go then @Mahmoud-zino !

**Comment by bfovez** [comment]
Thank you for you reply.

Le ven. 6 oct. 2023 à 23:42, Chris Simmons ***@***.***> a
écrit :

**Comment by Mahmoud-zino** [comment]
@endigo9740 
some questions about the change:
1. if size is undefined we don't want to display a "last" button? or display it and forward its event?
2. I don't know what to do with NumericRow when size is undefined, should I just hide it?
3. I noticed the style of disabled buttons is not present (also on live), is this intended or a bug?

**Comment by endigo9740** [comment]
> I noticed the style of disabled buttons is not present (also on live), is this intended or a bug?

Pagination now uses `btn-group` styling, but it appear Group is not accounted for in the disabled state styles. So file this as a separate ticket:

https://github.com/skeletonlabs/skeleton/blob/master/packages/plugin/src/styles/components/buttons.css#L28

**Comment by Mahmoud-zino** [comment]
@endigo9740 Can you please review the first 2 questions above, I think you forgot them 😄

**Comment by endigo9740** [comment]
@Mahmoud-zino ping me about this tomorrow please. Too much going on today. Sorry!

**Comment by endigo9740** [comment]
@bfovez After doing a bit more research and testing this in the following PR, we have come to the conclusion this will not be a change we can support. I've explained the issue in detail here:

https://github.com/skeletonlabs/skeleton/pull/2193#issuecomment-1783103630

The screenshot and diagram provided should help visualize the issue. Pagination just doesn't work without knowing the max size of items.

> In a server-side pagination context, we often don't know in advance the size of the dataset.

I've worked in web dev for just over 20 years. There's always ways to determine the maximum count of items. If the data is local, you can check the the array length. If the data is being fetch from a server, then any standard pagination solution should include `size` as one of the provided response values. Calculating this as part of a SQL query should be trivial and performant. If your server solution doesn't, then my suggestion is to make a second call to fetch this value separately. Then away both calls to be satisfied before showing the pagination. Though I highly encourage the former idea instead.

@Mahmoud-zino and I are in agreement on this, and as such we're going to go ahead and close out this ticket. If you need pagination somehow doesn't support `size`, then my suggestion would be to roll your own. You're welcome to fork our component and go from there.

**Comment by bfovez** [comment]
Hi everyone,
Duly noted.
