### ISSUE TITLE
Lighthouse reports best practice error: "Registers an unload listener"

### ISSUE THREAD

**Issue by ZeynelKoca** [skeletonlabs/skeleton#2070]
### Current Behavior

Not a huge bug, but it is stopping my app from scoring 100 across the board 😞 

Lighthouse always scores lower for Best Practices because of an `unload` event listener somewhere. Could either be an issue in the Skeleton codebase or in that of a dependency.

### Expected Behavior

Lighthouse should score 100 for Best Practices for an empty project

### Steps To Reproduce

1. Use the CLI tool with any node version (I tried 18.15 and 18.18) to create a new project. Settings do not matter
2. `npm run build`
3. `npm run preview`
4. Generate a Lighthouse report using Chrome dev tools
5. Click on the Best Practices score (should score 92 for an empty project)
6. Error: Registers an `unload` listener (The `unload` event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Use `pagehide` or `visibilitychange` events instead)

![image](https://github.com/skeletonlabs/skeleton/assets/48792248/05a1e616-79bf-44af-ab1c-bc57ceda2622)

### More Information

Not the most important bug but at the same time, the solution could be as simple as updating a package dependency's version

**Comment by endigo9740** [comment]
@ZeynelKoca is this a stock project created with the CLI? We offer two template options out of the box - which did you choose? Just trying to narrow it down to what it could be, there's only a handful of components present in the stock configuration for the App Shell template, and should be zero components for the other.

The App Shell for example has a `on:scroll` event listener, but this is Svelte directive, which should unregister automatically:
https://github.com/skeletonlabs/skeleton/blob/dev/packages/skeleton/src/lib/components/AppShell/AppShell.svelte#L72

**Comment by ZeynelKoca** [comment]
> @ZeynelKoca is this a stock project created with the CLI? We offer two template options out of the box - which did you choose? Just trying to narrow it down to what it could be, there's only a handful of components present in the stock configuration for the App Shell template, and should be zero components for the other.
> 
> The App Shell for example has a `on:scroll` event listener, but this is Svelte directive, which should unregister automatically: https://github.com/skeletonlabs/skeleton/blob/dev/packages/skeleton/src/lib/components/AppShell/AppShell.svelte#L72

As I was going through your question I decided to check what would happen if I also created an empty svelte project. As it turns out, the same error occurs here. 
So the issue should be reported @ svelte instead. My bad!

**Comment by ZeynelKoca** [comment]
@Mahmoud-zino You're kidding 😅. That's the last thing I would've thought. Thanks!
