### ISSUE TITLE
LightSwitch has hardcoded english title attribute

### ISSUE THREAD

**Issue by Agnostion** [skeletonlabs/skeleton#2088]
### Current Behavior

I encountered a situation where there was a need to alter the attributes of LightSwitch component. It has the `title` attribute preset within the component definition. I am finding it challenging to modify this attribute without delving into the node modules and making changes there.

### Expected Behavior

I was expecting a prop.

### More Information

I would appreciate any guidance on how to achieve this modification in a more straightforward or proper manner currently.
Thank you very much in advance for your time and assistance in resolving this issue. 🙂

**Comment by endigo9740** [comment]
@Agnostion this will be fixed per this PR: https://github.com/skeletonlabs/skeleton/pull/2090

This will be deployed as part of our next release. We drop new releases every 2 weeks, so expect this the week after next
