### ISSUE TITLE
Props are not updated in Modal Settings

### ISSUE THREAD

**Issue by sorae42** [skeletonlabs/skeleton#2097]
### Link to the Page

https://www.skeleton.dev/utilities/modals#modal-settings

### Describe the Issue (screenshots encouraged!)

The type `buttonPositive` and `buttonNeutral` is does not exist but the docs still shows them.

<img width="688" alt="Screenshot 2023-10-02 at 19 52 06" src="https://github.com/skeletonlabs/skeleton/assets/34794115/998cd3e2-abeb-49e6-a45c-adf12fabb967">

**Comment by sorae42** [comment]
It seems that I misunderstood the docs. Sorry in advance.

**Comment by dnnsmnstrr** [comment]
@sorae42 May I ask how you misunderstood the docs? I ran into the same problem you seem to have had and was not able to find out how `buttonPositive` should be used.
My use case is to change the confirm button of a confirm modal to a red color for destructive actions, but as you mentioned, that is currently not possible according to the [ModalSettings](https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/utilities/Modal/types.ts#L14) type definition.

**Comment by sorae42** [comment]
> @sorae42 May I ask how you misunderstood the docs? I ran into the same problem you seem to have had and was not able to find out how `buttonPositive` should be used. My use case is to change the confirm button of a confirm modal to a red color for destructive actions, but as you mentioned, that is currently not possible according to the [ModalSettings](https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/utilities/Modal/types.ts#L14) type definition.

Oh, you are supposed to use these in the `<Modal>` tag. LIke so: `<Modal buttonPositive="...">`.

**Comment by endigo9740** [comment]
Yep, props go on the component definition, params go into the ModalSettings object. We have automated documentation of props, but unfortunately no params. We may end up manually documenting ModalSettings in the near future. For now here's a reference:

https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/utilities/Modal/types.ts#L40

We were aiming for parity between params and props wherever we can. Unfortunately it looks like we have a few that aren't represented in the params.

@dnnsmnstrr @sorae42 if you have a solid use case for this, feel free to reference this thread and post and create a feature request ticket. I'd be happy to look at adding these soon. Thanks!
