### ISSUE TITLE
Filter GitHub sponsor users list on the homepage

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2106]
### Link to the Page

https://www.skeleton.dev/

### Describe the Issue (screenshots encouraged!)

Looks like we have a couple users listed that should likely be filtered:

1. GitHub Actions (avatar with GitHub's icon)
2. Luke has two accounts (blue Tardis avatar), let's nix the one with the lesser contributions

Might also be nice to include more folks with smaller avatars - we have 90+ contributors, but only 50 are shown.

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/7feda70c-275c-4cc1-972f-389bf910b297)

**Comment by endigo9740** [comment]
It's grid based, show it should just be a matter of trying different combinations. The hard part shouldn't be the layout, it should be figuring out how to fetch this from GitHub. Right now I'm using a third party service that provides a restful call for this. I believe the only option GitHub provides for this directly would be GraphQL based.

Maybe start there, look into retrieving the data. Then if you feel you need help with the layout, let me know. Happy to jump into a PR and edit directly as well

**Comment by Mahmoud-zino** [comment]
@endigo9740 I just checked the docs, we are retrieving the contributors list from the official GitHub API:
`https://api.github.com/repos/skeletonlabs/skeleton/contributors` I wouldn't change this, I will just add `per_page=100` queryparam to get 100 results at once (It is still very fast, you won't notice the difference between 30 and 100).
I think the performance hit will be in the avatar trying to load everything at once, so we can add lazy loading to that.

**Comment by endigo9740** [comment]
@Mahmoud-zino good to know, that sounds much easier then! I do recall @AdrianGonz97 building some sort of caching into this to help with performance, but I don't recall the specifics. You might double check with him if you get a moment.

**Comment by AdrianGonz97** [comment]
@endigo9740 @Mahmoud-zino Caching is automatically done on Github's API end via cache headers. No need to do anything special on our end 😄

**Comment by endigo9740** [comment]
Welp, that's easy!
