### ISSUE TITLE
Tech Debt: Fix all "any" types used throughout the docs

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#2115]
### Describe the Issue (screenshots encouraged!)

When running ``pnpm lint`` you get a bunch of "any" warnings, this should be fixed.

**Comment by endigo9740** [comment]
I believe @AdrianGonz97 mentioned wanting to work through some of this well. I welcome a few folks splitting this up!

**Comment by jwatts777** [comment]
+1. Count me in

**Comment by endigo9740** [comment]
I'll have some time tomorrow, so I'll try to setup a new channel on Discord to discuss this. I'll post details here when ready.

**Comment by Hugos68** [comment]
+1

**Comment by endigo9740** [comment]
@ryceg any interest in joining in on this one?

**Comment by jwatts777** [comment]
- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\components\DocsIcon\icons.ts**
  - [ ] 7:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsShell\sveldMapper.ts**
  - [ ] 10:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  - [ ] 23:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  - [ ] 35:23  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  - [ ] 54:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsShell\types.ts**
  - [ ] 25:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsThemer\DocsThemer.svelte**
  - [ ] 15:11  warning  'storeTheme' is defined but never used  @typescript-eslint/no-unused-vars

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleEmbed.svelte**
  - [ ] 8:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleForm.svelte**
  - [ ] 4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleImage.svelte**
  - [ ] 4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleList.svelte**
  - [ ] 6:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\themes.ts**
  - [ ] 3:7   warning  'ghPath' is assigned a value but never used  @typescript-eslint/no-unused-vars
  - [ ] 4:22  warning  Unexpected any. Specify a different type     @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\components\input-chips\+page.svelte**
  - [ ] 39:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\get-started\SectionThemes.svelte**
  - [ ] 2:11  warning  'storeOnboardMethod' is defined but never used  @typescript-eslint/no-unused-vars
  - [ ] 18:33  warning  Unexpected any. Specify a different type        @typescript-eslint.no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\+page.svelte**
  - [ ] 3:45  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-vars

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\licensing\+page.svelte**
  - [ ] 3:11  warning  'Avatar' is defined but never used     @typescript-eslint/no-unused-vars
  - [ ] 3:19  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-vars

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\forms\+page.svelte**
  - [ ] 34:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  - [ ] 37:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  - [ ] 37:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  - [ ] 39:15  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\scroll-containers\+page.svelte**
  - [ ] 73:42  warning  '_' is defined but never used  @typescript-eslint/no-unused-vars

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\typography\+page.svelte**
  - [ ] 6:22  warning  'Accordion' is defined but never used      @typescript-eslint/no-unused-vars
  - [ ] 6:33  warning  'AccordionItem' is defined but never used  @typescript-eslint/no-unused-vars

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\+layout.svelte**
  - [ ] 121:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\blog\[slug]\+page.svelte**
  - [ ] 22:56  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  - [ ] 26:53  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

- [ ] **D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\blog\blog-service.ts**
  - [ ] 9:54  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  - [ ] 17:58  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
