### ISSUE TITLE
Provide redirect feature for modal buttons

### ISSUE THREAD

**Issue by muhsim** [skeletonlabs/skeleton#2127]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

In many situations, buttons such as 'cancel', 'confirm', and 'submit' require redirection to a different page. Introducing default variables like `buttonHrefCancel`, `buttonHrefConfirm`, and `buttonHrefSubmit` in the standard types (alert/confirm/prompt) would be advantageous. This concept is akin to text override options found here: https://github.com/skeletonlabs/skeleton/blob/dev/packages/skeleton/src/lib/utilities/Modal/types.ts#L38.

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@muhsim already possible in two ways:

1. For the canned modals (alert, prompt, confirm) you can listen to the `response()` callback. The positive action returns `true`, negative action returns `false`, while clicks in the backdrop return `undefined`. Then build your redirect logic accordingly.
2. Skeleton provides component modals to generate your own modals. This gives you freedom to create modals to operate how you wish, including built-in redirects.

That said, I do believe our documentation is lacking a clear explanation of how `response()` works, so we'll keep this issue and focus on improvements to the documentation around this.

**Comment by phamduylong** [comment]
I do agree that the response examples can be clearer. @endigo9740 if you can decide what to be done there, I can contribute.

**Comment by phamduylong** [comment]
I'll take a look and see if I can improve the docs here.

**Comment by endigo9740** [comment]
Thanks @phamduylong, I'd recommend including an additional accordion item under the Component Modal section and detail the three states as described in my message above.
