### ISSUE TITLE
disabled style of btn in btn-group

### ISSUE THREAD

**Issue by Mahmoud-zino** [skeletonlabs/skeleton#2135]
### Current Behavior

buttons in btn-group doesn't have a disabled style.

### Expected Behavior

disabled buttons in btn-group should have the same styling as a normal disabled button.

### Steps To Reproduce

1. navigate to [Paginators](https://www.skeleton.dev/components/paginators#demo)
2. check the "previous button" in the pagination demo.

### More Information

https://github.com/skeletonlabs/skeleton/blob/master/packages/plugin/src/styles/components/buttons.css#L28

**Comment by endigo9740** [comment]
We recently fixed a similar issue with `btn-icons`, so I'd encourage we evaluate any other scenario where this might be an issue. Get it sorted, less piecemeal fixes.

**Comment by Whimfoome** [comment]
Can confirm. Do you know what version did it break, because I would like to roll back, or is it since Skeleton v2?

**Comment by Whimfoome** [comment]
Thank you, I have made a temporary fix that sets the button's class that is disabled to `!opacity-50 !cursor-not-allowed active:scale-100 hover:brightness-100;`.

Recently I upgraded to Skeleton v2 and haven't noticed this until now, so maybe it's a regression between v1 and v2?
I tried the production version of our website which still uses v1 and it looks correct there.
But there were a lot of changes so maybe it worked in a different way before.

**Comment by endigo9740** [comment]
We may very little to no changes to the styles themselves between Skeleton v1 -> v2. We did however move requiring users to import the stylesheets for these directly in their project, to passing those styles to our Tailwind plugin. Which makes them more automatic. Tailwind can treat styles a bit differently when fed through the plugin like that, so you may be seeing a remnant of this. But again, if something changed between v1 and v2 for button group disabled state, it was an unintended side effect and not directly linked to any specific change by a contributor.

**Comment by Whimfoome** [comment]
> Just to make sure we're on the same page
> - `.btn-groups > buttons` - needs to be resolved per this ticket

Yes, something like this:
```js
<div class="btn-group variant-filled">
	<button>Months</button>
	<button disabled>Days</button>
	<button>Years</button>
</div>
```
