### ISSUE TITLE
Let us programmatically activate the back and next button on the stepper component? 

### ISSUE THREAD

**Issue by Jayrr-Dev** [skeletonlabs/skeleton#2136]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently, there's no way to programmatically activate the next and back button. This would be a great feature to make it more flexible. For instance, automatically trigger next with a function when all the states are true. That can create a great effect and save on a button click. 

### What type of pull request would this be?

Enhancement

**Comment by Sarenor** [comment]
That's very much in the cards and planned for the https://github.com/skeletonlabs/skeleton/issues/1780 Stepper refactor, which is why I'll be closing this issue.

For now it's not perfect, but you can always do ``document.getElementByQueryThatWorks().click()`` to get the next/previous button :)
