### ISSUE TITLE
Tech debt: type improvements to core features

### ISSUE THREAD

**Issue by jwatts777** [skeletonlabs/skeleton#2137]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

#2115 Only fixes docs.

Total project lint

Will update with more information.

### What type of pull request would this be?

Other

**Comment by jwatts777** [comment]
│2D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ConicGradient\ConicGradient.svelte
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\AppRail\AppRailTile.svelte
│   17:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   27:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\AppShell\AppShell.svelte
│3  14:12  warning  '$$Events' is defined but never used  @typescript-eslint/no-unused-vars
│   17:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   27:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\AppShell\AppShell.svelte
│   14:12  warning  '$$Events' is defined but never used  @typescript-eslint/no-unused-vars
│4D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ConicGradient\ConicGradient.svelte
│   27:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\AppShell\AppShell.svelte
│   14:12  warning  '$$Events' is defined but never used  @typescript-eslint/no-unused-vars
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ConicGradient\ConicGradient.svelte
│5  36:27  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\AppShell\AppShell.svelte
│   14:12  warning  '$$Events' is defined but never used  @typescript-eslint/no-unused-vars
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ConicGradient\ConicGradient.svelte
│   36:27  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│6  46:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
│   14:12  warning  '$$Events' is defined but never used  @typescript-eslint/no-unused-vars
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ConicGradient\ConicGradient.svelte
│   36:27  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   46:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
│7  50:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ConicGradient\ConicGradient.svelte
│   36:27  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   46:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
│   50:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│8  56:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   36:27  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   46:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
│   50:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   56:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│9  61:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
│   46:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
│   50:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   56:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   61:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
[10 lines collapsed]po\skeletonfork\packages\skeleton\src\lib\components\InputChip\InputChip.svelte
│   50:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   56:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   61:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\InputChip\InputChip.svelte
│ 1 44:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   56:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   61:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\InputChip\InputChip.svelte
│   44:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 2 64:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   61:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\InputChip\InputChip.svelte
│   44:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   64:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 3:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ListBox\ListBoxItem.svelteial.svelte
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\InputChip\InputChip.svelte
│   44:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   64:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ListBox\ListBoxItem.svelteial.svelte
│ 4 15:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   44:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   64:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ListBox\ListBoxItem.svelteial.svelte
│   15:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 5 19:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   64:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ListBox\ListBoxItem.svelteial.svelte
│   15:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   19:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 6 65:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ListBox\ListBoxItem.svelteial.svelte
│   15:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   19:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   65:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 7:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ProgressRadial\ProgressRadial.svelte
│   15:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   19:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   65:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ProgressRadial\ProgressRadial.svelte
│ 8 45:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   19:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   65:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ProgressRadial\ProgressRadial.svelte
│   45:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 9:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Radio\RadioItem.svelte
│   65:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ProgressRadial\ProgressRadial.svelte
│   45:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Radio\RadioItem.svelte
│20 12:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\ProgressRadial\ProgressRadial.svelte
│   45:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Radio\RadioItem.svelte
│   12:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 1 19:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   45:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Radio\RadioItem.svelte
│   12:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   19:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 2:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\RangeSlider\RangeSlider.svelte
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Radio\RadioItem.svelte
│   12:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   19:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\RangeSlider\RangeSlider.svelte
│ 3 47:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   12:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   19:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\RangeSlider\RangeSlider.svelte
│   47:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 4:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Tab\Tab.svelte
│   19:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\RangeSlider\RangeSlider.svelte
│   47:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Tab\Tab.svelte
│ 5 17:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\RangeSlider\RangeSlider.svelte
│   47:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Tab\Tab.svelte
│   17:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 6 27:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   47:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Tab\Tab.svelte
│   17:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   27:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 7:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Table\utils.ts
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Tab\Tab.svelte
│   17:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   27:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Table\utils.ts
│ 8 23:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   17:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   27:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Table\utils.ts
│   23:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 9 23:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   27:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Table\utils.ts
│   23:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   23:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│30 25:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\components\Table\utils.ts
│   23:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   23:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   25:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 1 32:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   23:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   23:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   25:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   32:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 2 32:51  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   23:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   25:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   32:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   32:51  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 3 37:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   25:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   32:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   32:51  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   37:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 4 37:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   32:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   32:51  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   37:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   37:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 5:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\CodeBlock\stores.ts
│   32:51  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   37:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   37:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\CodeBlock\stores.ts
│ 6 3:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyny
│   37:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   37:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\CodeBlock\stores.ts
│   3:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyny
│ 7:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Drawer\types.ts
│   37:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\CodeBlock\stores.ts
│   3:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyny
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Drawer\types.ts
│ 8 10:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\CodeBlock\stores.ts
│   3:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyny
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Drawer\types.ts
│   10:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ 9:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Modal\Modal.svelte
│   3:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyny
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Drawer\types.ts
│   10:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Modal\Modal.svelte
│40 110:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Drawer\types.ts
│   10:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Modal\Modal.svelte
│   110:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 1:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Modal\types.ts
│   10:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Modal\Modal.svelte
│   110:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Modal\types.ts
│ 2  7:7   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Modal\Modal.svelte
│   110:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Modal\types.ts
│    7:7   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 3 26:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│   110:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Modal\types.ts
│    7:7   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   26:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ 4 32:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Modal\types.ts
│    7:7   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   26:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│   32:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ 5 44:9   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│    7:7   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   26:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│   32:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│   44:9   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ 6:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Popup\popup.ts
│   26:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│   32:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│   44:9   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Popup\popup.ts
│ 7   5:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   32:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│   44:9   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Popup\popup.ts
│     5:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 8  67:49  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   44:9   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Popup\popup.ts
│     5:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│    67:49  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 9 139:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Popup\popup.ts
│     5:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│    67:49  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   139:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│50:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Popup\types.ts
│     5:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│    67:49  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   139:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Popup\types.ts
│ 1 11:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│    67:49  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   139:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Popup\types.ts
│   11:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 2 13:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   139:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Popup\types.ts
│   11:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   13:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ 3 15:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│ D:\Code\SkeletonRepo\skeletonfork\packages\skeleton\src\lib\utilities\Popup\types.ts
│   11:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   13:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   15:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   17:47  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   20:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   22:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   24:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
│   26:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

**Comment by endigo9740** [comment]
See also: https://github.com/skeletonlabs/skeleton/pull/2164

**Comment by endigo9740** [comment]
Give Skeleton v3 is going to contain a rewrite to support Svelte 5. We'll likely tackle this naturally as we go. Given this, we can go ahead and sunset a dedicated ticket for this. This should be handled feature to feature in v3.
