### ISSUE TITLE
Manually installing I get 'cjs' extensions instead of 'ts'.

### ISSUE THREAD

**Issue by gzuuus** [skeletonlabs/skeleton#2140]
### Current Behavior

Following the steps in the docs to install skeleton manually in an existing project, when I do the command 'npx svelte-add@latest tailwindcss' the files 'tailwind.config.cjs' and 'postcss.config.cjs' are generated with format 'cjs' instead of 'ts'.

### Expected Behavior

Instead of generating 'cjs' files, they should be created with the appropriate 'ts' extension.

**Comment by Sarenor** [comment]
That is something you'll have to take up with Svelte-Add I'm afraid, Skeleton doesn't maintain the Tailwind Installation using Svelte-Add.

**Comment by endigo9740** [comment]
@gzuuus what Sarenor said, I'd recommend taking this upstream.

That said, you should be able to manually rename the file to match your configured application settings (JS or TS). Then adjust the contents to what's shown in our docs.

**Comment by gzuuus** [comment]
Yes! I managed to get it working, but the content of tailwind.config.ts seems to be out of date in the docs as it didn't work with the suggested config. I had to use the config from another project where I was testing skeleton and created with skeleton cli.

**Comment by endigo9740** [comment]
@gzuuus interesting - do you have a diff to compare? The version shown in our docs is the base config, while the CLI will certainly add a few other things based on your prompts on setup - such as adding additional Tailwind plugins.

**Comment by gzuuus** [comment]
Yes sure
Docs purpose tailwind.config.ts
```
import { join } from 'path';
import type { Config } from 'tailwindcss';

// 1. Import the Skeleton plugin
import { skeleton } from '@skeletonlabs/tw-plugin';

const config = {
	// 2. Opt for dark mode to be handled via the class method
	darkMode: 'class',
	content: [
		'./src/**/*.{html,js,svelte,ts}',
		// 3. Append the path to the Skeleton package
		join(require.resolve(
			'@skeletonlabs/skeleton'),
			'../**/*.{html,js,svelte,ts}'
		)
	],
	theme: {
		extend: {},
	},
	plugins: [
		// 4. Append the Skeleton plugin (after other plugins)
		skeleton
	]
} satisfies Config;

export default config;
```

tailwind.config.ts generated by skeleton cli
```
import { join } from 'path'
import type { Config } from 'tailwindcss'
import { skeleton } from '@skeletonlabs/tw-plugin'

export default {
	darkMode: 'class',
	content: ['./src/**/*.{html,js,svelte,ts}', join(require.resolve('@skeletonlabs/skeleton'), '../**/*.{html,js,svelte,ts}')],
	theme: {
		extend: {},
	},
	plugins: [
		skeleton({
			themes: {
				preset: [
					{
						name: 'skeleton',
						enhancements: true,
					},
				],
			},
		}),
	],
} satisfies Config;
```

**Comment by endigo9740** [comment]
So I see three notable differences here - which are intended:

1. More comments on the doc version - which is intended
2. The export method style differs - also intended, and both operate the same
2. The CLI version takes an opinionated stance on the theme and theme settings

We can't and won't follow number 3 here, because those steps are covered in a subsequent step for the manual instruction where the path forks between using either a preset or custom theme. So overall they differ, but in an very intentional manner.

Thanks for sharing to confirm!
