### ISSUE TITLE
RecursiveTreeView unable to select parent nodes when depth greater than 2

### ISSUE THREAD

**Issue by RogerNoble** [skeletonlabs/skeleton#2144]
### Current Behavior

On first load, only able to select the leaf nodes and their direct parents of a RecursiveTreeView (haven't tried it with regular TreeView) with `selection`, `multiple `and `relational` enabled. Clicking any other parent node has no effect.

Clicking a second time fixes the issue and all nodes can then be selected.

### Expected Behavior

Are able to select any node in the TreeView without having to click a second time

### Steps To Reproduce

1. Add a RecursiveTreeView component to a page with `selection`, `multiple `and `relational` enabled.
2. Bind to a source of nodes that has nested children with a depth greater than 2
3. On page load click the first / top level node

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-repl-j4d2s8?file=src%2Froutes%2F%2Bpage.svelte

**Comment by Sarenor** [comment]
That's not going to make @Mahmoud-zino very happy but thank you for reporting the issue and thank you _very_ much for providing a stackblitz reproduction, that makes triage and testing so much easier!

**Comment by RogerNoble** [comment]
> That's not going to make @Mahmoud-zino very happy but thank you for reporting the issue and thank you _very_ much for providing a stackblitz reproduction, that makes triage and testing so much easier!

Sorry 😬, really amazing work @Mahmoud-zino. I really love the component, it's a central feature of the app I'm building!

**Comment by Mahmoud-zino** [comment]
> > That's not going to make @Mahmoud-zino very happy but thank you for reporting the issue and thank you _very_ much for providing a stackblitz reproduction, that makes triage and testing so much easier!
> 
> Sorry 😬, really amazing work @Mahmoud-zino. I really love the component, it's a central feature of the app I'm building!

Thank you very much for reporting the issue, I must have missed it during testing, I will take a look at it 👍

**Comment by endigo9740** [comment]
@Mahmoud-zino same deal here, assigned to you.
