### ISSUE TITLE
RecursiveTreeView - setting checkedNodes for a single item causes toggling behavior

### ISSUE THREAD

**Issue by RogerNoble** [skeletonlabs/skeleton#2145]
### Current Behavior

I have a use case where I need to set the checkedNodes of a RecursiveTreeView based on a users saved preferences. Only the id's of the leaf nodes are being saved, not the full path.

When they are applied the first time the nodes are checked. When the nodes are reapplied the nodes toggle off.

For example, given these nodes
```
[
	{
		content: 'Level 1',
		id: '1',
		children: [
			{
				content: 'Level 2',
				id: '2',
				children: [
					{
						content: 'Level 3',
						id: '3',
						children: [
							{
								content: 'Level 4',
								id: '4'
							}
						]
					}
				]
			}
		]
	}
];
```
Only `['4']` is being applied and not `['1', '2', '3', '4']`

As this only happens when setting an individual id this may be the expected behaviour??

### Expected Behavior

When reapplying the checkedNodes the previously checked nodes remain checked.

### Steps To Reproduce

1. Add a RecursiveTreeView component to a page with selection, multiple and relational enabled.
2. Bind to a source of nodes that has nested children
3. Set the selected nodes
4. Set the selected nodes again

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-repl-c6b7q5?file=src%2Froutes%2F%2Bpage.svelte

**Comment by Mahmoud-zino** [comment]
@RogerNoble Thank you for reporting this also, I can see a couple of weird behaviours here. I will aim to check these soon 👍

**Comment by endigo9740** [comment]
@Mahmoud-zino as per usual I've assigned this one to you. Thanks!
