### ISSUE TITLE
Transitions not working for Step in Stepper

### ISSUE THREAD

**Issue by wtfacoconut** [skeletonlabs/skeleton#2146]
### Current Behavior

The transition properties specified for <Step> within the <Stepper> component, does not appear to have any effect.
When refreshing the page or clicking on the "next" button in the stepper to proceed to the next step, the contents of the <Step> element do not display any kind of transition animation.

### Expected Behavior

My expectation is that when refreshing, or clicking on the next button provided by the Stepper component, the contents rendered by the <Step> component should show a transition animation.

### Steps To Reproduce

1. Add a Stepper component.
2. Add at least two Step components to the Stepper component and add some content to them too.
3. For each Step component, specify your desired transition in the transition property.
4. Refresh the page or click on the "next" button that the Stepper component provides. You should see that there is no transition animation being applied to the contents of the Step component.

NOTE: For reference, please see my code example in StackBlitz. A link has been provided in this issue. 

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-repl-nhaw4y?file=src%2Froutes%2F%2Bpage.svelte

**Comment by endigo9740** [comment]
@wtfacoconut The only transition currently available in the component is the header. It doesn't transition between the steps themselves, which understandably is a bit confusing.

Currently we're reviewing a wide ranging update to this component. Right now we're consolidating all Stepper related tickets here, so I'll close this ticket in favor of that:
https://github.com/skeletonlabs/skeleton/issues/1780

I'd advise subscribing to 1780 if you wish to track progress. Thanks for reporting this.

**Comment by wtfacoconut** [comment]
Hey @endigo9740 . Thanks for the information. If that is the case, then updates for the Step component's documentation might be nice as it does explicitly show transition properties.

**Comment by endigo9740** [comment]
@wtfacoconut correct, and to reiterate, it does supports transitions. In fact, you can see them implemented within the component here:
https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/components/Stepper/Step.svelte#L128

Unfortunately these are not implemented where folks would expect them. To add context - we just dropped in the dynamic transition system in to replace any location that already had transitions. But as the linked issue indicates, this component is falling short of expectations in a lot of regards, so do expect updates in the future.

If you have any other feedback regarding this please make sure to post it in the linked thread. That'll be the best hub for that going forward.
