### ISSUE TITLE
 Overriding `sidebarLeft` or `pageHeader` in Child Page with AppShell Implemented in `+layout.svelte`

### ISSUE THREAD

**Issue by Typogram** [skeletonlabs/skeleton#2153]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I've implemented `AppShell` in `+layout.svelte` according to the documentation. Everything seems to be working as expected, but I've encountered an issue when dealing with `sidebarLeft` in sub pages.

For `sidebarLeft`, some of my pages have a different sidebar than the root level page defined by `+layout.svelte`. 

### Question

Is there a way to override `sidebarLeft` or `pageHeader` in a child page while keeping the AppShell implementation intact in `+layout.svelte`?

Thank you in advance for your help!

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@Typogram I'd recommend looking into SvelteKit route groups or similar layout strategies:
https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-group

General idea is I'd recommend three layouts:

1. Keep your root layout, but with only `<slot />` and your global imports. I'll explain below.
2. Create a route group for for first layout
2. Create a route group for your second layout

In the root layout, you would do something like this:

```html
<script lang="ts">...</script>
<slot />
```

Use this layout for your global imports, such as your global stylesheet, modal/toast/drawer imports and components, and dependency imports such as Highlight.js for code blocks or Floating UI for popups.

**Comment by endigo9740** [comment]
Alternatively, Skeleton conditionally hides the left sidebar on the homepage. We do this by using the Sveltekit `$page` store state:
https://github.com/skeletonlabs/skeleton/blob/dev/sites/skeleton.dev/src/routes/%2Blayout.svelte#L166

This a bit more limited though

**Comment by Typogram** [comment]
Hey @endigo9740! Thanks a ton for the tip about using layout groups! 🚀 That seems like a neat solution to my problem, and it's probably the way I'll go. It solves the sidebar and header issue perfectly. Appreciate the help!
