### ISSUE TITLE
Accessibility (keyboard navigation) for AppRail tiles

### ISSUE THREAD

**Issue by geoffkendall** [skeletonlabs/skeleton#2163]
### Current Behavior

Currently there is no keyboard nav for AppRail tiles.

### Expected Behavior

Tabbing to the AppRail should allow the user to move up and down to select a tile, like in list boxes etc.

**Comment by aaroncrockett** [comment]
I'll take this issue if this is something yall want to tackle now.

**Comment by endigo9740** [comment]
@aaroncrockett go for it. I'll assign this to you now. Thanks!
