### ISSUE TITLE
Tech debt: type improvements to docs site features

### ISSUE THREAD

**Issue by jwatts777** [skeletonlabs/skeleton#2165]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

__Placeholder__

### What type of pull request would this be?

Other

**Comment by jwatts777** [comment]
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\components\DocsIcon\icons.ts
- [ ] │   7:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsShell\sveldMapper.ts
- [ ] │   23:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │  35:23  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\components\DocsIcon\icons.tst-any
- [ ] │   7:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsShell\sveldMapper.ts
- [ ] │   10:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │  23:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   7:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyy
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsShell\sveldMapper.tsy
- [ ] │   10:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   23:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │  35:23  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsShell\sveldMapper.tsy
- [ ] │   10:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   23:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   35:23  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
- [ ] │  54:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   10:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   23:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   35:23  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
- [ ] │   54:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsShell\types.ts
- [ ] │   23:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   35:23  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
- [ ] │   54:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsShell\types.ts
- [ ] │  25:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   35:23  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anylte
- [ ] │   54:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsShell\types.ts
- [ ] │   25:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsThemer\DocsThemer.sveltelte
- [ ] │   54:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsShell\types.ts
- [ ] │   25:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsThemer\DocsThemer.sveltelte
- [ ] │  15:11  warning  'storeTheme' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsShell\types.ts
- [ ] │   25:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsThemer\DocsThemer.sveltelte
- [ ] │   15:11  warning  'storeTheme' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] [ lines collapsed]po\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleEmbed.svelte
- [ ] │   25:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsThemer\DocsThemer.sveltelte
- [ ] │   15:11  warning  'storeTheme' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleEmbed.svelte
- [ ] │ 1 8:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\layouts\DocsThemer\DocsThemer.sveltelte
- [ ] │   15:11  warning  'storeTheme' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleEmbed.svelte
- [ ] │   8:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] \Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleForm.svelte
- [ ] │   15:11  warning  'storeTheme' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleEmbed.svelte
- [ ] │   8:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleForm.svelte
- [ ] │ 3 4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleEmbed.svelte
- [ ] │   8:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleForm.svelte
- [ ] │   4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ 4:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleImage.svelte
- [ ] │   8:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleForm.svelte
- [ ] │   4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleImage.svelte
- [ ] │ 5 4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleForm.svelte
- [ ] │   4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleImage.svelte
- [ ] │   4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ 6:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleList.svelte
- [ ] │   4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleImage.svelte
- [ ] │   4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleList.svelte
- [ ] │ 7 6:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleImage.svelte
- [ ] │   4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleList.svelte
- [ ] │   6:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\themes.ts
- [ ] │   4:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleList.svelte
- [ ] │   6:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\themes.ts
- [ ] │ 9 3:7   warning  'ghPath' is assigned a value but never used  @typescript-eslint/no-unused-varsnThemes.svelte
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\modals\examples\ModalExampleList.svelte
- [ ] │   6:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\themes.ts
- [ ] │   3:7   warning  'ghPath' is assigned a value but never used  @typescript-eslint/no-unused-varsnThemes.svelte
- [ ] │20 4:22  warning  Unexpected any. Specify a different type     @typescript-eslint/no-explicit-anyars
- [ ] │   6:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\themes.ts
- [ ] │   3:7   warning  'ghPath' is assigned a value but never used  @typescript-eslint/no-unused-varsnThemes.svelte
- [ ] │   4:22  warning  Unexpected any. Specify a different type     @typescript-eslint/no-explicit-anyars
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\components\input-chips\+page.svelte
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\lib\themes.ts
- [ ] │   3:7   warning  'ghPath' is assigned a value but never used  @typescript-eslint/no-unused-varsnThemes.svelte
- [ ] │   4:22  warning  Unexpected any. Specify a different type     @typescript-eslint/no-explicit-anyars
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\components\input-chips\+page.svelte
- [ ] │ 2 39:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   3:7   warning  'ghPath' is assigned a value but never used  @typescript-eslint/no-unused-varsnThemes.svelte
- [ ] │   4:22  warning  Unexpected any. Specify a different type     @typescript-eslint/no-explicit-anyars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\components\input-chips\+page.svelte
- [ ] │   39:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\get-started\SectionThemes.svelte
- [ ] │   4:22  warning  Unexpected any. Specify a different type     @typescript-eslint/no-explicit-anyars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\components\input-chips\+page.svelte
- [ ] │   39:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\get-started\SectionThemes.svelte
- [ ] │   2:11  warning  'storeOnboardMethod' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\components\input-chips\+page.svelte
- [ ] │   39:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\get-started\SectionThemes.svelte
- [ ] │    2:11  warning  'storeOnboardMethod' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] │  18:33  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any
- [ ] │   39:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\get-started\SectionThemes.svelte
- [ ] │    2:11  warning  'storeOnboardMethod' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] │   18:33  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\+page.svelte
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\get-started\SectionThemes.svelte
- [ ] │    2:11  warning  'storeOnboardMethod' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] │   18:33  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\+page.svelte
- [ ] │ 7 3:45  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] │    2:11  warning  'storeOnboardMethod' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] │   18:33  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\+page.svelte
- [ ] │   3:45  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\licensing\+page.svelte
- [ ] │   18:33  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\+page.svelte
- [ ] │   3:45  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\licensing\+page.svelte
- [ ] │  3:11  warning  'Avatar' is defined but never used     @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\+page.svelte
- [ ] │   3:45  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\licensing\+page.svelte
- [ ] │   3:11  warning  'Avatar' is defined but never used     @typescript-eslint/no-unused-vars
- [ ] │   3:19  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-varst-any
- [ ] │   3:45  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\licensing\+page.svelte
- [ ] │   3:11  warning  'Avatar' is defined but never used     @typescript-eslint/no-unused-vars
- [ ] │   3:19  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-varst-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\forms\+page.svelte
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\docs\sponsorship\licensing\+page.svelte
- [ ] │   3:11  warning  'Avatar' is defined but never used     @typescript-eslint/no-unused-vars
- [ ] │   3:19  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-varst-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\forms\+page.svelte
- [ ] │  34:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   3:11  warning  'Avatar' is defined but never used     @typescript-eslint/no-unused-vars
- [ ] │   3:19  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-varst-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\forms\+page.svelte
- [ ] │   34:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │  37:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   3:19  warning  'CodeBlock' is defined but never used  @typescript-eslint/no-unused-varst-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\forms\+page.svelte
- [ ] │   34:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   37:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │  37:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyage.svelte
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\forms\+page.svelte
- [ ] │   34:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   37:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   37:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyage.svelte
- [ ] │  39:15  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   34:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   37:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   37:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyage.svelte
- [ ] │   39:15  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\scroll-containers\+page.svelte
- [ ] │   37:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   37:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyage.svelte
- [ ] │   39:15  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\scroll-containers\+page.svelte
- [ ] │  73:42  warning  '_' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] │   37:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-anyage.svelte
- [ ] │   39:15  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\scroll-containers\+page.svelte
- [ ] │   73:42  warning  '_' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\typography\+page.svelte
- [ ] │   39:15  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\scroll-containers\+page.svelte
- [ ] │   73:42  warning  '_' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\typography\+page.svelte
- [ ] │  6:22  warning  'Accordion' is defined but never used      @typescript-eslint/no-unused-vars
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\scroll-containers\+page.svelte
- [ ] │   73:42  warning  '_' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\typography\+page.svelte
- [ ] │   6:22  warning  'Accordion' is defined but never used      @typescript-eslint/no-unused-vars
- [ ] │   6:33  warning  'AccordionItem' is defined but never used  @typescript-eslint/no-unused-varsy
- [ ] │   73:42  warning  '_' is defined but never used  @typescript-eslint/no-unused-vars
- [ ] D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\typography\+page.svelte
- [ ] │   6:22  warning  'Accordion' is defined but never used      @typescript-eslint/no-unused-vars
- [ ] │   6:33  warning  'AccordionItem' is defined but never used  @typescript-eslint/no-unused-varsy
- [ ]  D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\+layout.svelte
- [ ]  D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\(inner)\elements\typography\+page.svelte
- [ ] │   6:22  warning  'Accordion' is defined but never used      @typescript-eslint/no-unused-vars
- [ ] │   6:33  warning  'AccordionItem' is defined but never used  @typescript-eslint/no-unused-varsy
- [ ] │D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\+layout.svelte
- [ ] │  121:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   6:22  warning  'Accordion' is defined but never used      @typescript-eslint/no-unused-vars
- [ ] │   6:33  warning  'AccordionItem' is defined but never used  @typescript-eslint/no-unused-varsy
- [ ]  D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\+layout.svelte
- [ ] │   121:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ]  D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\blog\[slug]\+page.svelte
- [ ] │   6:33  warning  'AccordionItem' is defined but never used  @typescript-eslint/no-unused-varsy
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\+layout.svelte
- [ ] │   121:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\blog\[slug]\+page.svelte
- [ ] │   22:56  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   26:53  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │ D:\Code\SkeletonRepo\skeletonfork\sites\skeleton.dev\src\routes\blog\blog-service.ts
- [ ] │    9:54  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- [ ] │   17:58  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

**Comment by endigo9740** [comment]
Give Skeleton v3 is going is going to include a port of the docs to Astro.js. We'll likely tackle this naturally as we go. Given this, we can go ahead and sunset a dedicated ticket for this. Feel free to monitor v3 updates once we go public with them.
