### ISSUE TITLE
Use :host instead of :root to declare theme color variables

### ISSUE THREAD

**Issue by 1mehal** [skeletonlabs/skeleton#2167]
### Current Behavior

I'm using Skeleton to build a Chrome Extension (so using skeleton in shadow-dom), and colors are not working, because :root css value refers to a document, I would suggest switching to use :host variable, if it wouldn't break anything

### Expected Behavior

When using Skeleton in shadow-dom container - colors should work

**Comment by endigo9740** [comment]
@1mehal current we only provide support for Skeleton on SvelteKit. We mention this right at the top of the install page:

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/785b158d-60a7-4427-92f0-7dcbb60602c1)

That said, I have heard of others using Skeleton to create Chrome extensions in the past, and this is the first I've heard of this issue specifically. I might encourage reviewing if there's any other options available on your end.

Additionally I'm willing to keep this open for a bit in case anyone can make suggestions on how to fix this. My immediate concern would be that this might introduce a breaking change. If that's the case, this would have to be designated to a major change.

So I just want to make it clear expectations here - we're open to options, but cannot promise support here.

**Comment by 1mehal** [comment]
@endigo9740 I do use skeleton with SveleKit
My suggestion is to switch to :host instead of root, I did it for my build and everything seems to be working fine

**Comment by endigo9740** [comment]
> I do use skeleton with SveleKit

Gotcha. I think other users making extensions started with a simple Vite project with just Svelte (sans SvelteKit).

> My suggestion is to switch to :host instead of root, I did it for my build and everything seems to be working fine

Right, but we have a responsibility to keep Skeleton working for everyone. Not just you and your project. We typically put a lot of consideration into changes that might have sweeping changes or introduce regressions or new edge cases.

On a different note, I'm going to ping one of our regular contributors that I seem to recall having setup a starter project for creating a Skeleton app for use in building Chrome extensions. He might be able to provide more guidance here.

@luke-hagar-sp @LukeHagar any help here?

**Comment by endigo9740** [comment]
Another mod had this handy. This is an article Luke authored:

https://dev.to/lukehagar/building-a-chrome-extension-with-sveltekit-3kb

**Comment by 1mehal** [comment]
@endigo9740 I very well aware and respect your responsibility and do respect it! 
Again, just to be clear: when I use Skeleton and rendering elements in `shadowDom` and styles are loosing their colors because they are declared under `:root`, when I switch to declaration under `:host`-> everything works
I couldn't find a reference, but seems to me fallback of `:host`, when there is no shadowDom, is to select `:root`, but you might now better.

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/1142
