### ISSUE TITLE
Table Cell  as svelte component

### ISSUE THREAD

**Issue by snk-js** [skeletonlabs/skeleton#2169]
Table components could be of type svelte components

https://github.com/skeletonlabs/skeleton/blob/760e77eac8f78efd9bf12105407aa2d331fb5f66/packages/skeleton/src/lib/components/Table/types.ts

instead of:
```
	const sourceData = [
		{
			button: '<button type="button" class="btn variant-soft-primary">play</button>'
		},

	];
```
importing one
```
	import PlayButton from './PlayButton.svelte';

	const sourceData = [
		{
			button: PlayButton 
		},

	];
```

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@snk-js that's a fairly opinionated change. What we typically recommend is if folks need to insert a Svelte component into the table, to use our Table element styles with native table instead:

https://www.skeleton.dev/elements/tables

I'd recommend this approach, it gives you a lot more control over the contents of the table.
