### ISSUE TITLE
RecursiveTreeView Events

### ISSUE THREAD

**Issue by Coolzie1** [skeletonlabs/skeleton#2170]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

When using the recursive tree view, it isn't possible to use events such as on:click or on:toggle. 

For example, using the tree to display folders and files, the below could pass information about the node clicked to be able to open or download a file.

```
<RecursiveTreeView
            selection
            nodes={myTreeViewNodes}
            relational
            bind:checkedNodes
            bind:indeterminateNodes
            on:click={e => console.log(e)}
/>
```

And when toggled, I presume this would automatically make it a folder due to having children, on:toggle could display the node information / tree below it to be able to show the files/folders within that node dynamically?

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

Attached is a mock Svelte page (.txt as github wont accept the +page.svelte) to demonstrate the functionality and workaround having to be used, but it is likely to be very inefficient and have functional issues as the tree expands, such as when nodes are deleted and IDs start to clash.

[rescursiveTree.txt](https://github.com/skeletonlabs/skeleton/files/13062707/rescursiveTree.txt)
[treeData.json](https://github.com/skeletonlabs/skeleton/files/13062709/treeData.json)

**Comment by endigo9740** [comment]
FYI @Mahmoud-zino

**Comment by Mahmoud-zino** [comment]
@Coolzie1 
Incorporating the click and toggle events appears essential, but it's unnecessary to include additional information in the toggle function. We'll be sending the node's ID, and you can seamlessly manage the display of additional details on your end.

**Comment by Coolzie1** [comment]
@Mahmoud-zino
Sounds good to me! Thank you.
