### ISSUE TITLE
Custom modal was created with unknown prop "parent"

### ISSUE THREAD

**Issue by Carlos-err406** [skeletonlabs/skeleton#2176]
### Current Behavior

Custom modals that don't use the `parent` prop I get the `<SomeModal> was created with unknown prop 'parent'`

### Expected Behavior

not seeing the unknown prop warning in the console when not using the `parent` prop in Modal Components

### Steps To Reproduce

1. Do the modal setup following the [skeleton ui docs](https://www.skeleton.dev/utilities/modals)
2. Create a Modal Component (Custom Modal) without using the `export let parent`
3. trigger the custom modal y see the console for the warning

### More Information

my suggestion is to still pass the parent data but not as a prop to modals, but through `context`, this way is more opt-in and less annoying.

**Comment by endigo9740** [comment]
> my suggestion is to still pass the parent data but not as a prop to modals, but through context, this way is more opt-in and less annoying.

That's an interesting suggestion.

I'm definitely not satisfied with how this works now, it's a very manual process to ensure parity for all props.. The Context API wouldn't solve this issue either. At least if each value is provided piecemeal. Ideally what we need is a way to inherit or retrieve any and all values from the parent automatically (props, functions, etc).

There is some low level access Svelte provides for this, but I've been informed it's part an API that will likely change in the future. My hope is to test our options again when Svelte 5 drops. I'm really hoping for something that makes this more automatic.

In the meantime I think the Context API change can be reserved as our fallback plan.

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2357
