### ISSUE TITLE
Table of Contents: Reintroduce (optional) generation of anchor link tags after headings

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#2178]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

https://discord.com/channels/1003691521280856084/1166271445224132618/1166320780032888842

The new ToC is great, but some people (including myself) have been missing the auto-generated anchor tag links after headings, since the ToC is usually unavailable on mobile.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
I'm fairly so-so about this approach unless it's optional, off by default (given it's a breaking change), and provides is unstyled out of the box. Though we can suggest a set of styles applied in the global stylesheet. Part of the settings for this also need to include an option to set the position either leading or trailing the heading text itself. I'm also unsure how best to handle the icon itself. It will likely need to be customizable SVG passed into the action.

So it's possible, but there's some steep technical challenges to overcome here.

**Comment by Sarenor** [comment]
I wouldn't want it any other way than option & off-by-default and agree with all other points 👍

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2362
