### ISSUE TITLE
Missing import in `localStorageStore` Docs

### ISSUE THREAD

**Issue by Web3NL** [skeletonlabs/skeleton#2179]
### Link to the Page

https://www.skeleton.dev/utilities/local-storage-stores

### Describe the Issue (screenshots encouraged!)

import { localStorageStore } from '@skeletonlabs/skeleton';

**Comment by Sarenor** [comment]
It's right there though? Or am I missing something:
<img width="707" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/31982384/f468c51f-4b65-43cc-aa56-5f437817b48d">

**Comment by Web3NL** [comment]
excuse me! thought i missed it, had to import it myself...

The page does show it now... maybe my glasses have a bug

**Comment by Web3NL** [comment]
closed

**Comment by Sarenor** [comment]
All good, glad we got that solved :)
