### ISSUE TITLE
Integrate a Themer Component into the Core Library

### ISSUE THREAD

**Issue by Typogram** [skeletonlabs/skeleton#2183]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Hello Skeleton UI maintainers,

Firstly, I would like to commend the team on the theme generator provided on the documentation site. It's a great tool and I've found it extremely useful. 

However, I noticed that the process of using the theme generator and integrating it into my development environment can be a bit cumbersome. The current flow involves tweaking the theme on the documentation site, copying the configuration, pasting it into my development environment, seeing how it looks, and then repeating this loop if further modifications are needed. The feedback loop feels prolonged and sometimes hinders the rapid prototyping experience.

To address this, I've developed a local "Themer" component in my setup, which allows me to design and tweak the theme live on my website. The immediacy of this tool has significantly improved my theming process.

I believe that this Themer component could be of immense value to other developers using Skeleton UI. Therefore, I would like to suggest integrating a themer component similar to my solution into the core Skeleton UI library. This would enable developers to have a quicker feedback loop when designing themes and make the customization process even more seamless.

Benefits of this proposal:

1. **Quick Feedback Loop**: Developers can immediately see the impact of their theme changes.
2. **Ease of Access**: Integrating the Themer directly into the core library means that developers won't need to switch contexts between the documentation site and their dev environment.
3. **Improved User Experience**: By streamlining the theming process, we can potentially attract more users to Skeleton UI, given the enhanced user experience.

If the team is interested, I'm more than willing to share my implementation of the Themer component and discuss possible ways to integrate it into Skeleton UI.

Thank you for considering my suggestion. I genuinely believe this feature can bring substantial value to the Skeleton UI community.

### What type of pull request would this be?

New Feature

**Comment by endigo9740** [comment]
@Typogram I'd recommend moving this under this existing issue. We have some big plans for themes in the future, so this feedback would be a valuable part of that. I'm going to close this thread, but will reference this page and of course welcome your direct feedback to the other proposals listed.

https://github.com/skeletonlabs/skeleton/issues/1142
