### ISSUE TITLE
Table props are not overwriting the inherent table element styles

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2189]
### Current Behavior

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/6b51bb65-4798-4e61-a058-f77972d81428)

As discussed on Discord:
https://discord.com/channels/1003691521280856084/1007673252992262215/1166585706676768810

### Expected Behavior

The expectation is the `.table` class will apply some default classes to the HTML table element. Then local props like `text` should be able to override and take precedence for, say, the `text` prop value.

### Steps To Reproduce

You have to be hyper-localized and even include `!`.

- Using `text` only affects the headings
- Using `regionBody` has no effect at all for text styles
- The only working solution is `regionCell="!text-2xl"`

### More Information

This is notable because it may impact the Skeleton "next" concepts.

**Comment by phamduylong** [comment]
I'll give this a try.

**Comment by endigo9740** [comment]
@phamduylong the issue is already assigned.
