### ISSUE TITLE
Have focusTrap action focused on a specific element using tabIndex

### ISSUE THREAD

**Issue by doic** [skeletonlabs/skeleton#2190]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

After discussing this on discord with @endigo9740 :
Let users implement their own tabindex attributes, so they retain full control and encourage best practices
By default, focusTrap should default to the first focusable element in the array
If specified, focusTrap should target the tabindex supplied by the user (I'll discuss how we pass this below)
Update modals/dialogs to accept an optional tabindex, which is passed to the embedded version of focusTrap. Which triggers the above result.
Per the interface for providing the tabindex to the focusTrap, we're unfortunately a bit limited due to the current implementation accepting only a single boolean value:
`<form use:focusTrap={someBoolValue}>`

First instinct is to do something like this - however this would be a breaking change and is not possible until the next major release:
`<form use:focusTrap={{state: someBoolValue, tabindex: 2}}>`

But what we'll likely need to do is use a data attribute as a temporary solution. This is optional and non-breaking:
`<form use:focusTrap={someBoolValue} data-tabindex={2}>`

I'm demonstrating tabindex as a number here, but string might be more appropriate.

We should likely keep the existing logic around a default selection (first focusable). This keeps parity with the existing functionality (prevents a breaking change again), as well as provides a nice fallback if users don't specify tabindex values in their content as expected.

### What type of pull request would this be?

Enhancement

**Comment by doic** [comment]
Limiting the data-tabindex to only form elements may not be the best solution, btw.
tabindex attributes can be added to any HTMLElement:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by doic** [comment]
And after reading a bit more, having tabIndexes > 0 is not recommended (even if they use examples > 0 in the doc)
![image](https://github.com/skeletonlabs/skeleton/assets/33346648/caa0265b-9e98-45f9-861b-f2984b9e6713)

**Comment by doic** [comment]
> Hmm, that does complicate things a bit. In that case, I'd suggest using data attributes:
> 
> ```
> <button data-tabindex="0">...</button>
> <button data-tabindex="1">...</button>
> <div tabindex="0" data-tabindex="2">...</div>
> ```
> 
> This provides a similar interface, but still gives the focusTrap a specific target that's easily queried.

Wouldn't it be easier to have only one data attribute ?
Because if we don't use tabindex, then there is no order to take into consideration, only one element to focus on:
```
<button>...</button>
<button data-focus="true">...</button>
<div tabindex="0">...</div>
```

**Comment by endigo9740** [comment]
Actually yes, that seems much better. Good call!

**Comment by endigo9740** [comment]
I like the simplicity of that, but my concern would obviously be what if that needs to change. What if a condition is in place that requires you to select element A instead of B.

I'm not sure the specific implementation for `ModalSettings` yet, but imagine something like this:

```ts
function triggerModal(someBool: boolean) {
  const modal: ModalSettings = {
    // ...
    tabindex: someBool ? 0 : 2
  };
  modalStore.trigger(modal);
}
```

In this case, it might be nice to quickly be able to jump from selecting the `data-tabindex="0"` or `data-tabindex="2"` based on the condition here.

Again, this does require some setup ahead of time by the user, but it provides a simpler implementation here. Seems more flexible, right?

**Comment by doic** [comment]
To me, it's the same. We can put some logic inside the component template, or in the ModalSettings :-)
I'm just concerned about the "tabindex" property in case of ModalSettings.
I would rather use this:
```typescript
function triggerModal(someBool: boolean) {
  const modal: ModalSettings = {
    // ...
    focus: someBool ? id1 : 'd2
  };
  modalStore.trigger(modal);
}
```
with id1 and id2 being just elementId. This way we don't mess with tabIndexes > 0 :-)

**Comment by doic** [comment]
But I prefer the data-focus="true"; I don't see how we can't condition this:
```svelte
<button>...</button>
<button data-focus="{condition}">...</button>
<div tabindex="0" data-focus="{!condition}">...</div>
```

**Comment by doic** [comment]
Another detail, ModalSettings has nothing to do with focusTrap action :-)
If we narrow the changes to focusTrap only, it will adapt to other / future utilities that will implement focusTrap !

**Comment by endigo9740** [comment]
Typically the goal of your template markup is to provide a definition of the visual and non-visual data (read: attributes) for your component HTML. While you certain can put more of your logic in the template, the questions is if this is the most pragmatic solution. In this case I think most folks would prefer the logic be handled in the Javascript, rather than in the template itself. Keep the template slim and "dumb". Let Javascript do it's job.

I'd also encourage you to think beyond a simple boolean example here. Imagine scenarios that have maybe 5-10 items that could dynamically be selected. The requirements for condition within the template grows with your `data-focus` method, but the upfront requirements are very simple with the `data-tabindex` approach.

`data-focus` approach:

```
<button data-focus={focusedCond === 1}>...</button>
<button data-focus={focusedCond === 2}>...</button>
<button data-focus={focusedCond === 3}>...</button>
<button data-focus={focusedCond === 4}>...</button>
<button data-focus={focusedCond === 5}>...</button>
```

`data-tabindex` approach:

```
<button data-tabindex="0">...</button>
<button data-tabindex="1">...</button>
<button data-tabindex="2">...</button>
<button data-tabindex="3">...</button>
<button data-tabindex="4">...</button>
```

> Another detail, ModalSettings has nothing to do with focusTrap action :-)
> If we narrow the changes to focusTrap only, it will adapt to other / future utilities that will implement focusTrap !

Correct, the initial implementation is modifying the focusTrap - but the end goal is to allow this new forcusTrap feature to work with modals/drawers/etc. We should not ignore this goal when designing this feature. That would be very short sighted.

**Comment by doic** [comment]
Makes sense. I'll see how to be smart about this 😁

**Comment by doic** [comment]
For now, I'm passing **ModalSettings.tabIndex** to focusTrap, so I had to change:
```typescript
function focusTrap(node: HTMLElement), enabled: boolean) {}
```
to
```typescript
type FocusTrapSettings = { enabled: boolean; tabIndex?: number };
function focusTrap(node: HTMLElement, focusTrapSettings: FocusTrapSettings) {}
```
I understand it would be a major change and you don't want that, correct ?

**Comment by endigo9740** [comment]
> I understand it would be a major change and you don't want that, correct ?

Correct, any change that's not backwards compatible with the current implementation would be considered "breaking". We cannot provide breaking changes in minor updates to the library. We would have many upset users if we did :)

I would actually be fine if you want to hold off on modifications to the Modal and Drawer right now. Keep it in mind, but let's talk through that next and separately. I'll likely need to dive into the code and refresh how everything is implemented to provide a suggestion for how we should implement. Unfortunately my time is limited today.

Per the changes to the focusTrap, we need to keep:

```ts
function focusTrap(node: HTMLElement), enabled: boolean) {}
```

Then use the `node` to query for `data-tabindex` items within it. We do something similar with the Table of Contents action, which scans for header elements:

https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/utilities/TableOfContents/crawler.ts#L35

Something like:

```ts
const focusableElems = node.querySelectorAll('[data-tabindex]);
```

You then have an array of elements that use this data attribute, and should be able to locate which matches the desired index value - then set focus on that.

**Comment by endigo9740** [comment]
In the future, we can refactor the focusTrap to our standard `args` format like so:

```
type FocusTrapArgs= { enabled: boolean; tabIndex?: number };

function focusTrap(node: HTMLElement, args: FocusTrapArgs) {}
```

**Comment by doic** [comment]
> In the future, before our next major release, we can refactor the focusTrap to our standard `args` format like so:
> 
> ```ts
> type FocusTrapArgs= { enabled: boolean; tabIndex?: number };
> 
> function focusTrap(node: HTMLElement, args: FocusTrapArgs) {}
> ```

Actually, I'm alreay on it with this:
```typescript
type FocusTrapArgs = boolean | { enabled: boolean; tabIndex?: number };

function focusTrap(node: HTMLElement, args: FocusTrapArgs) {}
```
I took the idea in the Clipboard action ^^
So it doesn't break anything and nobody will be upset :-)

**Comment by endigo9740** [comment]
I was considering something like this. I might still recommend we put a `// TODO:` comment or something similar to clue us into the fact this may need a minor refactor in the future. But I think that's a good happy medium for now. Good call!
