### ISSUE TITLE
ProgressBar transition

### ISSUE THREAD

**Issue by Drelekin** [skeletonlabs/skeleton#2195]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

ProgressRadial supports a transition when value changes by default. I think same behavior should apply for ProgressBar. Currently the workaround to get the same behavior is by setting "transition-all" to ProgressBar meter prop.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@Drelekin I was able to squeeze this in. The next release drops a week from Tuesday so keep an eye out for this. As discussed in Discord, when you update, revert the bg and transition classes you're adding now, as this should be applied by default now. Additionally both the Bar/Radial now include a `transition` prop if you wish to customize this class further.
