### ISSUE TITLE
Relational Selection: Error in RecursiveTreeViewItem when using expandedNodes

### ISSUE THREAD

**Issue by JamesPeck** [skeletonlabs/skeleton#2197]
### Current Behavior

When you use expandedNodes to open the top level parent and then open a child that has children the following error is thrown into the console:

```
Uncaught (in promise) TypeError: expandedNodes.push is not a function
    at toggleNode (RecursiveTreeViewItem.svelte:21:21)
    at Array.toggle_handler_1 (RecursiveTreeViewItem.svelte:96:22)
    at TreeViewItem.toggle_handler_1 (RecursiveTreeViewItem.svelte:127:32)
    at lifecycle.js:105:8
    at Array.forEach (<anonymous>)
    at lifecycle.js:104:22
    at $$self.$$.update (TreeViewItem.svelte:172:3)
    at update (scheduler.js:115:6)
    at flush (scheduler.js:79:5)
```

The error is not thrown if you remove `expandedNodes`
The behavior of the tree seems a bit broken after that.
The `checkedNodes` and  `indeterminateNodes` do not seem to update.
The relationship between the parents and their children no longer works for selection all children, etc.

### Expected Behavior

No error is thrown when using expandedNodes
The checkedNodes and  indeterminateNodes update

### Steps To Reproduce

1. Using RecursiveTreeView like so:

```
<RecursiveTreeView 
        selection 
        multiple 
        relational
        expandedNodes={'parent'}
        nodes={tree} 
        bind:checkedNodes={checkedNodes} 
        bind:indeterminateNodes={indeterminateNodes}/>
```

2. open a child of `parent`
3. See console log

### More Information

`"@skeletonlabs/skeleton": "2.4.0",`
`"@sveltejs/kit": "^1.27.1",`
` "svelte": "^4.2.1",`

**Comment by JamesPeck** [comment]
I understand its in beta but I thought I would still report it

**Comment by endigo9740** [comment]
FYi @Mahmoud-zino

**Comment by artello73** [comment]
@JamesPeck 
According to docs `expandedNodes` value should be an Array type. Please try  `expandedNodes={['parent']}` instead.
Perhaps this will so;ve the issue.

**Comment by Mahmoud-zino** [comment]
@JamesPeck Thank you for reporting the issue, and yup like @artello73 mentioned, `expandedNodes` is an array, using `expandedNodes={['parent']}` should work as expected.
