### ISSUE TITLE
Description List content overflow

### ISSUE THREAD

**Issue by LetrixZ** [skeletonlabs/skeleton#2198]
### Link to the Page

https://www.skeleton.dev/docs/tauri

### Describe the Issue (screenshots encouraged!)

![image0](https://github.com/skeletonlabs/skeleton/assets/25001812/db3bf9f8-c8d5-4127-8002-f31ba6967afb)

With `white-space: break-spaces;`

![www skeleton dev_docs_tauri(Samsung Galaxy S8+)](https://github.com/skeletonlabs/skeleton/assets/25001812/07aedd5c-3acf-48b7-864b-cd6371b0e72d)

**Comment by endigo9740** [comment]
@SebasF1349 I'd welcome a PR for this if you can jump on it before me. No pressure though!
