### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'prefersReducedMotionStore')

### ISSUE THREAD

**Issue by rhyses-pieces** [skeletonlabs/skeleton#2201]
### Current Behavior

Whenever I try to initialize stores with `initializeStores()` in my root layout at `src/routes/+layout.svelte`, I get this Typescript error:

```
TypeError: Cannot read properties of null (reading 'prefersReducedMotionStore')
```

I tried to fix it by importing `prefersReducedMotionStore`, but the error still intermittently shows up and throws a 500 error in my Sveltekit dev environment.

### Expected Behavior

Initialize stores for `<Toast>`, `<Modal>`, and `<Drawer>` components with no issues.

### Steps To Reproduce

1. Create a barebones application with Sveltekit CLI
2. Manually install Skeleton via instructions described in docs
3. Use `initializeStores()` in `src/routes/+layout.svelte`

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/sveltejs-kit-template-default-ciems6?file=src%2Froutes%2F%2Blayout.svelte

### More Information

I'm using Firefox as my default browser.

**Comment by endigo9740** [comment]
Hey @rhyses-pieces I had a similar error right after updating a few personal projects to Skeleton v2. I believe updating my other project dependencies resolved the issue. I don't believe I ever narrowed it down to one in particular, but I believe Typescript might have been the main on.

Feel free to try that and if the issue persists let us know.

**Comment by rhyses-pieces** [comment]
I've just tried updating all dependencies in my project to their latest versions (Typescript is at `^5.2.2`), and I'm still running into this issue. Really not sure what I'm doing wrong...

**Comment by Mahmoud-zino** [comment]
@rhyses-pieces The error in the stackblitz link indicating that you are importing `ToastSettings` as value instead of type.
in `+page.svelte` changed:
```ts
import { getToastStore, ToastSettings } from '@skeletonlabs/skeleton';
```
to
```ts
import { getToastStore, type ToastSettings } from '@skeletonlabs/skeleton';
```
and everything worked as expected.
Please Let us know if this didn't solve your problem.

**Comment by rhyses-pieces** [comment]
@Mahmoud-zino This seems to work!

I've noticed that Typescript expects to see at least one component using the `Toast` store somewhere after its stores are initialized. If `getToastStore` is not used, it seems to throw the `TypeError` error.

I'm gonna consider this closed.

**Comment by endigo9740** [comment]
@AdrianGonz97 any thoughts on this?

> I've noticed that Typescript expects to see at least one component using the Toast store somewhere after its stores are initialized. If getToastStore is not used, it seems to throw the TypeError error.

**Comment by AdrianGonz97** [comment]
@endigo9740 This shouldn't be possible and is more likely some other issue in the code. A reproduction would be required to confirm.

**Comment by endigo9740** [comment]
Good to know Adrian, @rhyses-pieces if you can provide a repro, then we're happy to take a look.

**Comment by rhyses-pieces** [comment]
@endigo9740 Hey there, I just realized that there had been a critical issue on my end. There was a mistake on my `tailwind.config.ts` file. 🤦 Instead of `join(require.resolve('@skeletonlabs/skeleton'), '../**/*.{html,js,svelte,ts}')`, I only had `join(require.resolve('@skeletonlabs/skeleton'))`, which is probably why I kept having weird Typescript issues. I apologize for my mistake!
