### ISSUE TITLE
Transparent header for appBar

### ISSUE THREAD

**Issue by gzuuus** [skeletonlabs/skeleton#2206]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I would like to know if there is any possibility to make the appBar transparent or translucent so that you can see the page content through it. I'm using 'background="bg-transparent"' as prop, but this only makes the background colour change to the same colour as the background, however the page content is hidden behind the menu once you scroll. I would like to know if it is possible to reduce or eliminate this opacity.

### What type of pull request would this be?

Enhancement

**Comment by Sarenor** [comment]
In theory, that should already work.
Are you using the AppBar together with the AppShell and if so, in which slot did you put your AppBar?

**Comment by gzuuus** [comment]
Yes, something like this code in my root +layout.svelte
```
</svelte:head>
<Modal components={modalRegistry} />
<Toast position="t" />
<Drawers />
<AppShell>
<svelte:fragment slot="header">
    <Header />
</svelte:fragment>
  <div class="grid place-content-center h-full sm:py-6">
    <slot />
  </div>
</AppShell>
```
And then in my component 'Header' using app bar 
`<AppBar background="bg-transparent" slotTrail="!space-x-2">`

Is there any way to get a transparent background?

**Comment by endigo9740** [comment]
What you're doing should make the AppBar transparent, as desired. But what you may be seeking is a sticky header that also overlaps the page contents. See the docs here for details on this. It requires moving the AppBar to the AppShell `pageHeader` slot and setting some additional CSS styling:

https://www.skeleton.dev/components/app-shell#using-an-app-bar

**Comment by gzuuus** [comment]
Not exactly, my intention is not a sticky header, it's to make the page visible through the appBar, as a transparent header, actually it takes on the colours of the background, but the content is covered by the header.
Thank you in any case for your answers :)

**Comment by endigo9740** [comment]
@gzuuus then again, what you provided should work. Here's a quick example with/without the transparent background prop set:

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/9f76e6eb-5690-4333-adbe-c59a8e03a223)
![image](https://github.com/skeletonlabs/skeleton/assets/1509726/2d2e9e78-2215-4197-8132-1b8f44b25972)

**Comment by gzuuus** [comment]
> @gzuuus then again, what you provided should work. Here's a quick example with/without the transparent background prop set:

Yes, but I have this behaviour, you can see how the content is cut from the header.
![Screenshot from 2023-11-02 01-24-23](https://github.com/skeletonlabs/skeleton/assets/116975404/46e4257b-dd6a-40d7-b531-f9f0ec7ca0da)

**Comment by endigo9740** [comment]
@gzuuus this is because it's in the `header` slot which is fixed ABOVE the `page` content. It'll never overlap the content - which is why you see that harsh looking line. This is why we suggested migrating to the sticky header approach. By default the sticky header will be above the content, but as you scroll it'll overlap while remaining affixed to the top.

Once again, I'd highly encourage you follow the directions for this linked above:
https://www.skeleton.dev/components/app-shell#using-an-app-bar

We use this setup for the Skeleton Labs website, though with a semi-transparent AppBar rather than one that's fully transparent:
https://www.skeletonlabs.co/
