### ISSUE TITLE
Transition between themes

### ISSUE THREAD

**Issue by gzuuus** [skeletonlabs/skeleton#2209]
It would be interesting to be able to have some sort of transition effect between the switch of themes. I don't know if this is possible at the moment, but it could be a very interesting visual effect.

**Comment by endigo9740** [comment]
@gzuuus we're very much welcoming ideas like this for our next major iteration of the theme system. Would you mind folding this request here. Just responding in the thread is perfect, we'll see it:

https://github.com/skeletonlabs/skeleton/issues/1142

I'd also encourage you to read through the ideas we do have proposed already. It's not a complete list, but should shed some light on the general direction we're heading with this
