### ISSUE TITLE
Drawers not animating smoothly on close

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2212]
### Current Behavior

When opening the drawer the default animation is smooth. When closing the panel seems to just fade away quickly.

### Expected Behavior

The drawer panel should mirror the open animation.

### Steps To Reproduce

Open a drawer -> close a drawer

**Comment by endigo9740** [comment]
@Mahmoud-zino may be related to our animation changes, so I figured I'd ping you.

**Comment by Mahmoud-zino** [comment]
@endigo9740 can you please post a video displaying the problem, I tested it and it seems to work as intended....

**Comment by endigo9740** [comment]
@Mahmoud-zino I'm limited on time today, but it's more noticeable when the drawer is resized to something like 300px wide.  I think it's actually the transition speed that may be at fault. When the drawer close animation seems nearly 2x faster than the drawer open speed. At least tested in Chrome.
