### ISSUE TITLE
Interactive chip examples should use button tags

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2213]
### Link to the Page

https://www.skeleton.dev/elements/chips#action-chips

### Describe the Issue (screenshots encouraged!)

Any interactive chip that uses `on:click` should also be set as a `<button>` element to prevent a11y warnings. This includes:

- action chips
- single selection
- multi-selection

This should be a super simple and easy fix!

**Comment by jwatts777** [comment]
🖐️
