### ISSUE TITLE
Popup tooltips should not have interactions when hidden

### ISSUE THREAD

**Issue by dldx** [skeletonlabs/skeleton#2214]
### Current Behavior

At present, a hidden popup can still be interacted with.

### Expected Behavior

Hidden popups should have their pointer-events set to none to be disabled. 

### Steps To Reproduce

1. This can be seen on the [documentation site]( https://www.skeleton.dev/utilities/popups)
2.  It is possible to click on a button within a hidden popup and trigger some changes.
3. In the case below, it is possible to randomly change the theme of the site because the theme buttons are interactive.

![Screenshot from 2023-11-06 11-29-56](https://github.com/skeletonlabs/skeleton/assets/107700/19a56bab-a571-4f14-99d3-f9f681006840)

### More Information

All this requires is a single line of code in popup.js at line 132:
```js
        elemPopup.style.pointerEvents = 'none';
```

There is a line that is supposed to make the popup inert but seemingly does nothing.

**Comment by Mahmoud-zino** [comment]
@dldx Please add what browser and version you are using?

**Comment by dldx** [comment]
I am using Vivaldi (which is chromium based). I don't seem to have the same issue in chrome, admittedly.

**Comment by Mahmoud-zino** [comment]
@dldx just downloaded the latest version (6.4.3160.41) and can't reproduce it. please update your browser and test again.

**Comment by dldx** [comment]
> @dldx just downloaded the latest version (6.4.3160.41) and can't reproduce it. please update your browser and test again.
> 

You are right about that. It does work with the latest version of Vivaldi! Perhaps no need to fix then, unless there is a need to support older browsers.

**Comment by Mahmoud-zino** [comment]
@dldx, usually we provide support only for newer browsers, but we have encountered similar issues multiple times already. Therefore, I believe @endigo9740 can make the best decision here. 😉

**Comment by endigo9740** [comment]
Given Vivaldi is Chromium-based and it's much smaller user base, we typically don't test it specifically. However, I'm glad to hear the latest update resolved the issue. In that case I may recommend we just go ahead let folks update and avoid changes to the popup feature, as we currently have a code freeze in effect for this:

https://github.com/skeletonlabs/skeleton/issues/1916
