### ISSUE TITLE
Modal Components Props and Slots example missing a comma

### ISSUE THREAD

**Issue by phamduylong** [skeletonlabs/skeleton#2221]
### Link to the Page

https://www.skeleton.dev/utilities/modals

### Describe the Issue (screenshots encouraged!)

As shown below, I believe a comma is missing after the **ref** property of this object.
![skeleton_bug](https://github.com/skeletonlabs/skeleton/assets/69810988/910d7cd2-048e-4787-afda-342fed0dfdfe)

**Comment by phamduylong** [comment]
Is this something I can take and make a PR for? Looks easy enough. 
@Bandit @juangiordana @delight @carlosg2

**Comment by delight** [comment]
Knock yourself out but why would you ping me for such a minor doc typo?

**Comment by endigo9740** [comment]
@phamduylong a PR would be welcome, just please be careful with pings. Ping myself or another maintainer if you need approval in the future.

I've edited your post to remove the pings in case anyone is wondering.

**Comment by phamduylong** [comment]
Thanks 😄 it wasn't clear in the Contributing Guide who to mention in the PR specifically, sorry to bother. I'll make the changes soon.

**Comment by endigo9740** [comment]
The maintainers monitor all issues and PRs, so we'll see things. Typically within around 24-48 hours.
