### ISSUE TITLE
Popup is broke

### ISSUE THREAD

**Issue by snk-js** [skeletonlabs/skeleton#2225]
### Current Behavior

The popup is braking due to `computePosition` as its store is undefined

and receives error in clientside:
![image](https://github.com/skeletonlabs/skeleton/assets/34718184/7cc1f28f-146f-433d-917d-c82873592d6b)

### Expected Behavior

expected to work as the demo shows
https://www.skeleton.dev/components/autocomplete

### Steps To Reproduce

reproduce demo for select popup

```
<input
							class="input autocomplete"
							type="search"
							name="autocomplete-search"
							bind:value={inputPopupDemo}
							placeholder="Search..."
							use:popup={popupSettings}
						/>
						<div data-popup="popupAutocomplete">
							<Autocomplete
								bind:input={inputPopupDemo}
								options={timeStrategies}
								on:selection={onSelected}
							/>
						</div>
```

at https://www.skeleton.dev/components/autocomplete

https://github.com/skeletonlabs/skeleton/blob/85b69544e512645738d4c4135ff17a6e71641159/packages/skeleton/src/lib/utilities/Popup/popup.ts#L5

**Comment by endigo9740** [comment]
@snk-js the autocomplete feature makes use of the Popups feature. The popup feature, however, has a few prerequisite steps. Can you confirm you've followed these and report back:

https://www.skeleton.dev/utilities/popups#installation
