### ISSUE TITLE
Input text style incorrect

### ISSUE THREAD

**Issue by Adam1901** [skeletonlabs/skeleton#2229]
### Current Behavior

![image](https://github.com/skeletonlabs/skeleton/assets/16060576/2cb1830b-dfcc-437b-aafb-5e8b424cee09)
 
Text input box missing padding and styles

### Expected Behavior

![image](https://github.com/skeletonlabs/skeleton/assets/16060576/ed0efd6b-cd7d-4484-a2d0-41a3d1f3aab1)

### Steps To Reproduce

        <Label label="Full Name" classes="mt-5">
                <input id="fullName" name="fullName" type="text" class="input" value={form?.full_name ?? fullName}/>
            </Label>

### Link to Reproduction / Stackblitz

a

**Comment by endigo9740** [comment]
@Adam1901 it looks like you missed the prerequisite steps here. When using forms, we require the use of the official Tailwind Forms plugin:

https://www.skeleton.dev/elements/forms#install-the-forms-plugin

Just FYI, this plugin normalizes most input styles, which them more easily customized between browsers.

**Comment by Adam1901** [comment]
Serves me right for not reading the documentation.
May I suggest a migration page betwenn1 and 2.

Thank you!

**Comment by Sarenor** [comment]
@Adam1901 if you mean between versions 1 and 2: https://github.com/skeletonlabs/skeleton/discussions/1947

**Comment by endigo9740** [comment]
Yeah the migration guide is part of the pinned v2 Announcement post here: https://github.com/skeletonlabs/skeleton/discussions/1945
