### ISSUE TITLE
Input group resizing broken on Firefox

### ISSUE THREAD

**Issue by precision-cancer-research** [skeletonlabs/skeleton#2230]
### Current Behavior

On Firefox, if you use the input group component as described in the [documentation](https://www.skeleton.dev/elements/forms), the input section reaches a minimum width and causes the shims to be hidden. You can actually see this happen in the docs themselves. ![Screenshot_select-area_20231108083856](https://github.com/skeletonlabs/skeleton/assets/41386058/7260fefb-a595-46d0-bd22-a568f8549a81)Only seems to be an issue for shims on the right. When I changed the styling to use `grid-cols-[auto_minmax(0, 1fr)_auto]` that seemed to fix it, but then if you type past the width of the input everything gets moved around.

### Expected Behavior

The input should resize as the screen gets smaller the way it does in chrome.

### Steps To Reproduce

1) Add the example code from the docs:
```html
<p>Amount</p>
<div class="input-group input-group-divider grid-cols-[auto_1fr_auto]">
  <div class="input-group-shim">(icon)</div>
  <input type="text" placeholder="Amount" />
  <select>
    <option>USD</option>
    <option>CAD</option>
    <option>EURO</option>
  </select>
</div>
```
2) Decrease the width of the screen until the shim starts clipping.

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/sveltejs-kit-template-default-pb9d92?description=The%20default%20SvelteKit%20template,%20generated%20with%20create-svelte&file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2F%2Blayout.svelte&title=SvelteKit%20Default%20Template

**Comment by djdembeck** [comment]
This also happens on Safari on iOS, using an iPhone.

**Comment by gRamos02** [comment]
I tried removing the `input-group-divider` class and seems to fix it.

**Comment by precision-cancer-research** [comment]
> I tried removing the `input-group-divider` class and seems to fix it.

Not sure what you mean. I tried removing that class and all it did was remove the dividers as well as break the resizing on Chrome and Firefox.

**Comment by endigo9740** [comment]
FYI I have a PR incoming here:
https://github.com/skeletonlabs/skeleton/pull/2343

This does NOT yet address the core issue described. But rather just updates our doc to provide a better example of the intended use case. This is what I'm going to consider a "band-aid" fix or recommendation for now. To avoid using these complex inputs in places where there's limited horizontal space.

However, and this is the import part, please be aware we're about to kick off the Skeleton v3 updates. As part of this we'll be evaluating every feature of Skeleton top to bottom, especially as we port components to the new Svelte 5 syntax (runes, snippets, etc). As part of this we're going to also be evaluating all our Tailwind provided styling as well. So expect to see more updates per this issue as part of that update.

I understand if that's not what was wanted here, but given the sizable changes incoming I think this is better handle as part of those updates. Thanks for your understanding!

**Comment by f1nzer** [comment]
I had a similar issue before, but setting `style="min-width: 0 !important;"` on the input fixed the issue for me in Firefox.
