### ISSUE TITLE
Migrate to @sveltejs/enhanced-img

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2233]
### Link to the Page

https://kit.svelte.dev/docs/images

### Describe the Issue (screenshots encouraged!)

This was launched as part of the Svelte Summit. We should look to migrate all image examples to using this. However, we should not migrate any code examples to use it, as it's limited to SvelteKit.

For example, we update the implemented images displayed here, but not the user-facing code snippets:
https://www.skeleton.dev/elements/image-layouts

**Comment by Mahmoud-zino** [comment]
@endigo9740 so we should make the changes only in docs? shouldn't our avatar for example use it also?

**Comment by Sarenor** [comment]
> shouldn't our avatar for example use it also?

That'd mean that we'd use SvelteKit code in something that could be used in just Svelte. So, probably better not

**Comment by endigo9740** [comment]
@Mahmoud-zino what @Sarenor said - we might be able to enable this in the future iteration with something like Svelte 5 snippets. But for now we can't bake in a SvelteKit only feature.

**Comment by Mahmoud-zino** [comment]
@Sarenor , @endigo9740 makes sense 👍

**Comment by endigo9740** [comment]
@Mahmoud-zino ugh that's annoying. Let me think about this one and I'll get back to you. I don't really want to self host if we can avoid it. We may just forego this for now.

**Comment by endigo9740** [comment]
This won't make much sense for the v2 docs, and in v3 we'll be using Astro - which has it's own image features built in. Given this we'll go ahead and sunset this.
