### ISSUE TITLE
Cleaner method of applying default + external classes for components

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#2236]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently components have default classes by taking ``$$props.class`` which works but forces Skeleton to prune out the ``class`` prop from restProps to ensure Skeleton's class attribute is used (it would otherwise be completely overwritten by restProps).
This is very verbose and messy.
A cleaner way of solving this would be through a ``class`` prop, sadly ``class`` is a reserved keyword but you can workaround it by use an alias.
Current way:
```html
<script>
	function prunedRestProps() {
		delete $$restProps.class;
		return $$restProps;
	}
</script>

<element class="... {$$props.class ?? ''}" {...prunedRestProps()} />
```
Suggested way:
```html
<script>
	let clazz = '';
	export { clazz as class };
</script>

<element class="... {clazz}" {...$$restProps} />
```
### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

Repl showcasing this idea: https://svelte.dev/repl/7ca9f9a830be4d69bae161c8515e08d9?version=4.2.2

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2361
