### ISSUE TITLE
Modal sliding to the right while opening

### ISSUE THREAD

**Issue by CoreyT355** [skeletonlabs/skeleton#2239]
### Current Behavior

With a basic modal component in use I am seeing the modal slide to the right by about 5px while opening. 

### Expected Behavior

When the modal opens it should transition in, but not slide to the right after it displays. 

### Steps To Reproduce

1. Open the stackblitz below
2. Click the "Open Modal" button
3. Watch the modal open and slide to the right as it becomes visible

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-repl-g8eubt

**Comment by endigo9740** [comment]
Hey this one has been bugging me lately as well. @Mahmoud-zino any chance you would have time to take a look?

**Comment by Mahmoud-zino** [comment]
@endigo9740 I will check the solution suggested in the other issue and see if it fits our needs 👍

**Comment by mattmccray** [comment]
As a workaround, I added a `no-scrollbar` class:

```html
<Modal regionBackdrop="no-scrollbar" />
```

Which is just:

```css
.no-scrollbar { overflow: hidden !important; }
```
