### ISSUE TITLE
Add accordion example without autocollapse

### ISSUE THREAD

**Issue by SebasF1349** [skeletonlabs/skeleton#2240]
### Link to the Page

https://www.skeleton.dev/components/accordions

### Describe the Issue (screenshots encouraged!)

A recurrent question in our server it's if all `AccordionItem` can be closed, as the docs example uses `autocollapse`. As Chris suggested,  "We should probably update the example and docs to make this more clear. I'm thinking a toggle on the preview, plus a callout in the page"

**Comment by endigo9740** [comment]
FYI we do talk about it here, but perhaps an example or toggle as mentioned above would suffice:

https://www.skeleton.dev/components/accordions#autocollapse-mode

**Comment by phamduylong** [comment]
I can take this.
