### ISSUE TITLE
btn-icon disabled state issue

### ISSUE THREAD

**Issue by karianpour** [skeletonlabs/skeleton#2243]
### Current Behavior

The btn-icon does not have a disabled state style.

### Expected Behavior

to have disabled style

### Steps To Reproduce

```
            <button
              class="btn-icon variant-filled"
              disabled
              on:click={() => console.log('clicked')}
            >
              <SomeIcon />
            </button>
```
the appearance is not 

### More Information

I copied the style from `.btn` class and added to my styles to fix the `issue`
```
  .btn-icon:disabled:hover {
    --tw-brightness: brightness(1);
    filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);
  }
  .btn-icon:disabled {
    cursor: not-allowed !important;
    opacity: 0.5 !important;
  }
  .btn-icon:disabled:active {
    --tw-scale-x: 100%;
    --tw-scale-y: 100%;
  }

```

**Comment by phamduylong** [comment]
What's the icon here? Is it Font Awesome or your custom made components?

**Comment by Mahmoud-zino** [comment]
@karianpour It seems to work as expected for me, tested on linux -> chrome, brave, firefox.
Please provide more info about the system and browser you are using so we can investigate further.

**Comment by endigo9740** [comment]
I've confirmed this is working as expected. I seem to recall another ticket coming through for this issue recently though, so it may have already been sorted. Hope this helps!

![Screenshot 2023-12-20 at 4 14 04 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/57711ca4-6e1e-4957-a83b-4281ed37b02a)
