### ISSUE TITLE
ToC: Feedback

### ISSUE THREAD

**Issue by gdude2002** [skeletonlabs/skeleton#2247]
Just some quick feedback on the [Table of Contents component](https://www.skeleton.dev/utilities/table-of-contents), having tried it and chatted with Chris on Discord. I'm updating this over time as I discover more about it.

- There doesn't seem to be a way to change the title? It'd be nice to be able to change it - for example, in an integrated navigation, I might want to set it to "Page Contents".
- Classes supplied in the `regionAnchor` property are applied too early, meaning they're overridden by the default classes provided by Skeleton. I'm not sure whether this applies to the other region properties, but it's worth checking.
- It'd be useful to be able to insert content into the `<a>` elements directly, maybe via a slot - for example, it'd be nice if I could insert an icon into my ToC links to make them look consistent with the rest of my navigation.
- ToC anchors are not full-width, whereas the `<li>` elements are. This means that you have to click directly on the link text, which is probably not ideal for a navigation component.
- ToC active styling is applied to the `<a>` element instead of the `<li>`, which results in inconsistent styling.
- ToC active styling seems to only be applied when you click on a ToC entry, and not when you scroll. Not sure why this is.

---

It's also difficult to combine some types of styles, for some reason. Let's say I have a setup that looks like this:

```css
/* 
	app.postcss
	
	Required for consistency as my ToC is placed within a list-nav, and other entries within have icons. 
*/
nav.toc li a {
	padding-left: 3em;
	color: inherit !important;
}
```
```html
<TableOfContents
		activeId="top"
		active="!bg-surface-200 dark:!bg-surface-700"

		regionAnchor="!bg-transparent !opacity-100"
		regionList="!mt-0"
		regionListItem="hover:!variant-filled-surface"
/>
```

This style doesn't work as expected. The hover style works correctly when there are no active items, but let's see what happens when we do have an active ToC item:

1. Click to get an active item 
    ![image](https://github.com/skeletonlabs/skeleton/assets/204153/76f68552-d24f-4feb-842a-b60467592f39)
2. Hover the active item
    ![image](https://github.com/skeletonlabs/skeleton/assets/204153/c6454fe0-c5a3-4820-898b-c949461a93a8)
3. Comparison when we hover an inactive item
    ![image](https://github.com/skeletonlabs/skeleton/assets/204153/d3624686-b345-4e2d-85ce-a0dbacd316b8)

I've thought about this a little, and I can't for the life of me figure out how I should be styling this. You'd think you'd remove the `!` from the active styles, but that means there's no active style at all!

---

Otherwise, this is quite a useful component - thanks to everyone for the work that's gone into it!

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2362
