### ISSUE TITLE
Tree view item indentation

### ISSUE THREAD

**Issue by acedeb** [skeletonlabs/skeleton#2249]
### Current Behavior

Hi,

Not sure if this belongs in Bug  or Feature request.

Currently the items in the treeview gets indented in their entirety.
It would be nice to only indent the "inner" item, hence the content, and not the entire item, which would follow what most treeviews out there are doing.

![Screenshot from 2023-11-19 13-34-14](https://github.com/skeletonlabs/skeleton/assets/119374510/43f47d20-303d-4e57-89fd-d1b7903cbcc6)

![Screenshot from 2023-11-19 13-37-02](https://github.com/skeletonlabs/skeleton/assets/119374510/f63b503e-91ce-4736-901f-669a8d6076bf)

#### Possible solution
In the current implementation of `TreeView` we are specifying indentation with classes:
```ts
  /** Provide classes to set the tree children 
  export let indent: CssClasses = 'ml-4';
```

but I'm not sure we would still be able to do this if we would want to change this behavior. A possible solution could be to specify a number e.g. in rem (or px); `TreeView`:
```svelte
<script lang="ts">
  export let indentRem: number = 0.5; // rem

  setContext('depth', 0);
</script>
```

And add a `style` in the `TreeViewItem` where we set the indentation depending on the depth:
```svelte
<script lang="ts">
  export let indentRem: number = getContext("indent");

  const depth: number = getContext("depth");
  setContext("depth", depth + 1);
</script>

<details
  ...
>
  <summary
    ...
    style="padding-left: {(depth + 1) * indentRem}rem"
  >
```

### Expected Behavior

There are several examples of treeview indentation, like vscode etc, but this one also is showing [fluentui treeview](https://react.fluentui.dev/?path=/docs/components-tree--default)

Notice how the border is around the entire width for each level, but this would also be noticeable when hovering:

![Screenshot from 2023-11-19 13-35-14](https://github.com/skeletonlabs/skeleton/assets/119374510/0a123206-b460-422b-ae23-b3f05060e896)
![Screenshot from 2023-11-19 13-37-46](https://github.com/skeletonlabs/skeleton/assets/119374510/6aefe012-d519-4bd7-97c7-707f47abc584)

### More Information

- https://react.fluentui.dev/?path=/docs/components-tree--default

**Comment by Mahmoud-zino** [comment]
This is not really a bug, it was designed this way. 
However I understand the logic behind the request, and I think we should consider a way to supply both styles depending on user preference.

**Comment by acedeb** [comment]
Thank you for answering. Yes, that makes sense.

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2358
