### ISSUE TITLE
Weird text selecting behaviour with <LightSwitch  /> component

### ISSUE THREAD

**Issue by nmalchy** [skeletonlabs/skeleton#2250]
### Current Behavior

I added the <LightSwitch  /> component to my routes/+layout.svelte file and when I flip it on and off it starts to select the "Welcome to Skeleton." header text, it's not a crazy bug but it is annoying the fact it does this at all. I also tried with SSR mode on and off and same behaviour.

### Expected Behavior

Switch between light and dark mode without overtly selecting text on the screen.

### Steps To Reproduce

1. Spin up a new Skeleton app
2. Add <LightSwitch  /> component to routes/+layout.svelte file
3. Flip the switch on and off a bunch of times and it will start to select the "Welcome to Skeleton." text

**Comment by endigo9740** [comment]
@nmalchy that's just stock browser behavior. If you double click fast enough it tries to select the region of the page you're on. Not sure there's anything we could do to help here.
