### ISSUE TITLE
Chips Fix/ Fix Code Examples

### ISSUE THREAD

**Issue by jwatts777** [skeletonlabs/skeleton#2251]
@endigo9740 it looks although the demos were changed, the actual code examples were not. If that's just an oversight, happy to open a little PR to fix that.
![image](https://github.com/skeletonlabs/skeleton/assets/12853597/1e1d6315-89a7-4106-a4db-ace6474a3d8f)

_Originally posted by @hmnd in https://github.com/skeletonlabs/skeleton/issues/2222#issuecomment-1818826545_

**Comment by endigo9740** [comment]
Thanks for creating an issue @jwatts777

@hmnd, definitely an oversight, so a PR would be welcome!
