### ISSUE TITLE
When using modal of type prompt the styling of the input is off

### ISSUE THREAD

**Issue by ChrisPoul** [skeletonlabs/skeleton#2256]
### Current Behavior

When using modal of type prompt the styling of the input is off.

<img width="242" alt="Screenshot 2023-11-22 000103" src="https://github.com/skeletonlabs/skeleton/assets/68830860/174e7be6-7f23-4e7b-9aef-8cccb3fbe4e8">

### Expected Behavior

On the skeleton.dev website the input looks great on the example prompt modal, I want the imput of all my prompt modals to look like that.

<img width="564" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/68830860/ab76009f-fce7-47d2-8351-fca680de2baf">

I've tried changing the theme and restarting my app but it didn't work, maybe this isn't a bug and I'm just missing a configuration step or something, but I would love to know how to configure it if that's the case.

### Steps To Reproduce

Use the prompt modal with the exact same code as in the example on the website.

**Comment by Mahmoud-zino** [comment]
@ChrisPoul have you installed the tailwind-forms plugin? if not please install it by following the instructions here: https://www.skeleton.dev/elements/forms#install-the-forms-plugin

**Comment by ChrisPoul** [comment]
Yes that was what I was missing, thank you!

**Comment by ChrisPoul** [comment]
Yes that was what I was missing, thank you!
