### ISSUE TITLE
Safari rendering of ProgressRadial issue when view is not Actual Size

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#2258]
### Current Behavior

There seems to be an offset/transform issue happening when zoomed in Safari for Progress Radials

https://github.com/skeletonlabs/skeleton/assets/52020637/9bbde31e-7e7e-4837-9055-a47165e98c7f

### Steps To Reproduce

You can preview it on [the docsite](https://www.skeleton.dev/components/progress-radials)

Or using this snippet:
```html
 <div class="w-[80px]">
  <ProgressRadial
    width="w-full"
    font={120}
    stroke={80}
    meter="stroke-primary-500"
    track="stroke-primary-500/30"
    strokeLinecap="butt"
    value={myValue}
  </ProgressRadial>
</div>
```

### Link to Reproduction / Stackblitz

https://www.skeleton.dev/components/progress-radials

### More Information

Reported by Geoff on Discord

**Comment by endigo9740** [comment]
After doing some research and testing on this, it seems to be a known issue in Safari. There's a slew of workarounds floating around, but none have worked as expected. I'd suggest we revealable this when updating for v3.

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2391
