### ISSUE TITLE
Light and dark mode not being derived from os when ssr is disabled

### ISSUE THREAD

**Issue by ChrisPoul** [skeletonlabs/skeleton#2259]
### Current Behavior

I am trying to make my website derive it's theme from the os, I followed the instructions on from the [docs](https://www.skeleton.dev/utilities/lightswitches) but it's just not working and I have no idea why. It's odd because I followed the same steps on another site I'm working on and there it worked without issue.

### Expected Behavior

The theme should match that of the operating system

**Comment by Sarenor** [comment]
Sadly, you have provided no actionable information for us.
Do you have a repository or a minimum reproduction to share?

**Comment by ChrisPoul** [comment]
Yes, you can check out my project https://github.com/ChrisPoul/finance-app

**Comment by jwatts777** [comment]
![image](https://github.com/skeletonlabs/skeleton/assets/91865823/2084481a-617a-455e-b946-822ad812a05e)
Do you have any actionable screenshots? The page seems fine as is.

**Comment by ChrisPoul** [comment]
I think you didn't underestand my question, I don't want my theme to be dark all the time, I want the theme to match that of the `Operating System Preferences`, not from that class you are pointing out. Currently the theme is just dark, if I remove the class you are highlighting then it is just light, that is `not` what I want.

**Comment by jwatts777** [comment]
A minimal repro on a fresh skeleton install works.
Most likely will have to go component by component checking until you find what is causing it.

**Comment by ChrisPoul** [comment]
Okay I was removing stuff and it wasn't doing anything, then I saw that the problem is in this section of code:

```svelte
<svelte:head>
	{@html `<script>${autoModeWatcher.toString()} autoModeWatcher();</script>`}
</svelte:head>
```

As it says in the svelte docs:

"This element makes it possible to insert elements into document.head. During server-side rendering, head content exposed separately to the main html content." 

The problem is that I have `ssr` disabled , when I enable ssr again it works as expected. This is not ideal since it is a requirement for my app that `ssr` is disabled.

**Comment by jwatts777** [comment]
SSR being disabled *should* not be your issue. 
A simple reproduction is linked here that has SSR disabled. https://github.com/jwatts777/autoModeWatcher-test

**Comment by ChrisPoul** [comment]
Yeah it looks like that shouldn't be the case, altho it does fix it for me, I will keep looking for the root cause of this

**Comment by ChrisPoul** [comment]
I found that you made a typo on your [reproduction](https://github.com/jwatts777/autoModeWatcher-test), you are missing a plus sign on the name of your layout file, so right now it's `layout.ts` when it should be `+layout.ts`. If you correct that then you can see the same error I'm facing.

**Comment by rbaprado** [comment]
> I found that you made a typo on your [reproduction](https://github.com/jwatts777/autoModeWatcher-test), you are missing a plus sign on the name of your layout file, so right now it's `layout.ts` when it should be `+layout.ts`. By correcting it I was able to reproduce the error I'm facing.

I am having the exact same problem, auto mode switching was not working and I narrowed it down to the SSR flag

**Comment by jwatts777** [comment]
That piece of code is a workaround for SSR to add to `document.head`
If you have truly disabled SSR at **root** level of your project, just onMount() everything between the script tag.
Sorry for the typo that caused this mess.
[reproducable demo](https://github.com/jwatts777/autoModeWatcher-test)
[relevant lines](https://github.com/jwatts777/autoModeWatcher-test/blob/08403d584fb745611487e4623679e2b3861a647f/my-skeleton-app/src/routes/%2Blayout.svelte#L10)

**Comment by ChrisPoul** [comment]
> That piece of code is a workaround for SSR to add to `document.head` If you have truly disabled SSR at **root** level of your project, just onMount() everything between the script tag. Sorry for the typo that caused this mess. [reproducable demo](https://github.com/jwatts777/autoModeWatcher-test) [relevant lines](https://github.com/jwatts777/autoModeWatcher-test/blob/08403d584fb745611487e4623679e2b3861a647f/my-skeleton-app/src/routes/%2Blayout.svelte#L10)

Yes this works perfectly, thanks for the help
