### ISSUE TITLE
Add option to make a Modal that can't be exited until accepted

### ISSUE THREAD

**Issue by ChrisPoul** [skeletonlabs/skeleton#2261]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I am trying to create a modal that prompts the user and asks them to give a name, I want it so that the user can't exit the modal until they've given the name. I have a work around for this but I think it would be cool to have an option to make an uncancelable and unclosable modal.

### What type of pull request would this be?

Enhancement

**Comment by Sarenor** [comment]
[No.](https://www.skeleton.dev/utilities/modals#accessibility)
Skeleton won't do this for the accessibility reasons outlined in the link above.

**Comment by ChrisPoul** [comment]
> [No.](https://www.skeleton.dev/utilities/modals#accessibility) Skeleton won't do this for the accessibility reasons outlined in the link above.

That makes sense, thanks for the fast response
