### ISSUE TITLE
Safari on MacOS messes up progress radials when zoomed out

### ISSUE THREAD

**Issue by lia-07** [skeletonlabs/skeleton#2262]
### Current Behavior

When the zoom of the page is increased OR decreased in Safari, the inward part of the progress radial becomes detached from the background part. From my testing, this does not seem to affect Chrome or Firefox.
<img width="699" alt="Screenshot 2023-11-24 at 4 13 38 PM" src="https://github.com/skeletonlabs/skeleton/assets/107384739/53c786a2-9d02-4668-bf1e-f376257b3bbf">

### Expected Behavior

The progress radials should look and function the same as they do when the zoom of the page is normal.

### Steps To Reproduce

1. Use the Safari browser on MacOS (I am using version 17.1, but it affected versions prior to this)
2. Navigate to [the Skeleton home page](https://www.skeleton.dev/) or [the Skeleton progress radials page](https://www.skeleton.dev/components/progress-radials)
3. Adjust the page's zoom level (`cmd` + `+` or `cmd`+ `-`)

### More Information

I actually noticed this problem a while ago and reported it (#1370).
However, no one else could reproduce the steps because at the time I was unaware it was caused by the page's zoom level and not just a core fault of my Safari installation, and so the issue was closed.

**Comment by Sarenor** [comment]
Thanks for getting back to us and and reporting it, but we've figured out that the problem comes from zoom level and opened an issue of our own literally yesterday 😁 
So I'll close this one as a duplicate and you can subscribe to https://github.com/skeletonlabs/skeleton/issues/2258 to get notified of a fix.

**Comment by lia-07** [comment]
Thanks you.
Sorry for the duplicate!

**Comment by lia-07** [comment]
> Thanks for getting back to us and and reporting it, but we've figured out that the problem comes from zoom level and opened an issue of our own literally yesterday 😁 So I'll close this one as a duplicate and you can subscribe to #2258 to get notified of a fix.

Thanks you.
Sorry for the duplicate!
