### ISSUE TITLE
Problem with setting id for AccordionItem

### ISSUE THREAD

**Issue by geoffkendall** [skeletonlabs/skeleton#2265]
### Current Behavior

When trying to set an id for an AccordionItem explicitly to "X", the id is actually set to "accordion-control-X".

### Expected Behavior

If overriding the default the expectation is that the id is set to "X".

**Comment by phamduylong** [comment]
Anyone taking this yet? Looks simple enough, I can make a quick fix.

**Comment by endigo9740** [comment]
Go for it @phamduylong

**Comment by geoffkendall** [comment]
Awesome, thanks Chris!
