### ISSUE TITLE
`LocalStorageStore` throws when value is undefined (because of `JSON.parse(undefined))`)

### ISSUE THREAD

**Issue by acedeb** [skeletonlabs/skeleton#2266]
### Current Behavior

When initializing or setting the `localStorageStore` to `undefined` the store throws an error when trying to parse `undefined`. This means the application is showing an `500 Internal Error` when using in from a `+page.ts`.

```ts
export const idStore: Writable<string | undefined> = localStorageStore(
  "some-id",
  undefined,
);
```

```ts
import { idStore } from '$lib/stores';
import { get } from 'svelte/store';
import type { PageLoad } from './$types';

export const load: PageLoad = () => {
        // the following throws
	console.log(`id: ${get(idStore)}`);
};
```

### Expected Behavior

Would expect the store to return `undefined`. This works correctly when using `null` instead, as `JSON.parse(null)` returns null.

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-repl-ggn4mm?file=src%2Froutes%2F%2Bpage.ts

**Comment by endigo9740** [comment]
So a couple things here @acedeb:

1. We don't maintain this feature. It's imported verbatim from JoshNussbaum's iteration, [per our attribution](https://www.skeleton.dev/utilities/local-storage-stores#attribution).
2. Our iteration is based on [v0.40.0](https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/utilities/LocalStorageStore/LocalStorageStore.ts#L3) - which appears to be fairly dated. So we'll keep this issue as a reminder to do so.
3. Finally, LocalStorage is a BROWSER specific API, but `Load()` functions run on the Server. So this will likely never work per your intended use case here. You may need to rethinking your approach.
