### ISSUE TITLE
Provide a way to add classes to a specific tree view item

### ISSUE THREAD

**Issue by JohannesPertl** [skeletonlabs/skeleton#2276]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I'm using tree view items in a RecursiveTreeView for navigation and mark the current active one by applying `bg-primary-active-token` like this:
![image](https://github.com/skeletonlabs/skeleton/assets/45853628/3687362d-e5d6-4900-b2a3-eeb67e473e08)

This is currently only possible with some hacks. A simpler way to access a specific `tree-item-summary` class would be nice.

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2358
