### ISSUE TITLE
AppRail width prop barely works

### ISSUE THREAD

**Issue by nmalchy** [skeletonlabs/skeleton#2278]
### Current Behavior

Setting the width prop anywhere between w-21 to w-39 completely breaks the CSS and makes it full page

### Expected Behavior

For the width to not take up the entire screen and for only the width to change not the height of the tiles (can't customize tile dimensions via props so...)

### Steps To Reproduce

Set <AppRail width="w-25">

### More Information

Setting the width to "w-40" works but it also increases the height of the tiles which I do not want.

the aspectRatio prop also does not work for anything except for the default value so why does this prop even exist?

I think this component needs some love cause it is super important for most apps yet is extremely rigid.

**Comment by endigo9740** [comment]
@nmalchy there's no such Tailwind utility classes for `w-21` or `w-39`:
https://tailwindcss.com/docs/width

The closest I can find are `w-20` (5 rem) and `w-40` (10 rem). If you're inserting invalid width classes then it's likely providing similar results to no width being set at all, such as `width=""`. Please make sure to insert valid classes and confirm the results.
