### ISSUE TITLE
ProgressBar component classesMeter applied twice in the template

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2280]
### Current Behavior

https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/components/ProgressBar/ProgressBar.svelte#L58

### Expected Behavior

Is:

```html
class="progress-bar-meter {classesMeter} {classesMeter}"
```

Should be:

```html
class="progress-bar-meter {classesMeter}"
```

### More Information

It may be worth it to add `regionX` props to the meter/track while we're at it. Not required though!

**Comment by ishaanparlikar** [comment]
Can I pick it up?

**Comment by endigo9740** [comment]
Of course @ishaanparlikar I'll assign this to you now. Thanks!
