### ISSUE TITLE
Add ProgressBar props to control indeterminate animation settings

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2281]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

We have had a Discord user request a way to customize the `indeterminate` mode animation transition speed. We should strive to minimize the `<style>` block animation settings:

https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/components/ProgressBar/ProgressBar.svelte#L64

The goal is to split the shorthand:

```css
animation: animIndeterminate 2s infinite linear;
```

Into dedicated properties like so:

```css
animation-name: animIndeterminate;
animation-iteration-count: infinite;
```

Then implement new component props that handle styles for [transition duration](https://tailwindcss.com/docs/transition-duration) and [transition timing functions](https://tailwindcss.com/docs/transition-timing-function). Suggested prop names would be:

* `indeterminateDuration="duration-75"`
* `indeterminateTransitionDuration="linear"`

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

Discord thread:

https://discord.com/channels/1003691521280856084/1181418447696048218/1181418447696048218

**Comment by Mahmoud-zino** [comment]
@endigo9740 I would like to work on this feat.

**Comment by Mahmoud-zino** [comment]
@endigo9740 @Sarenor 
`duration-75` is targeting transition and not animation, this won't work and tailwind doesn't provide a utility to handle animation duration.
`linear` doesn't exist, and if you meant `ease-linear` it is also targeting the transition and not animation.
the easiest possible solution here is to export the indeterminate animation class as a `CssClass` with a default value of our `animIndeterminate`, this way users can customize the animation as they wish or just use the default value.
If you agree with the solution, I will proceed to implement it and mention it in the docs.

**Comment by endigo9740** [comment]
@Mahmoud-zino I see what you mean, if there's not equivalent ways to handle these animation properties in a piecemeal fashion, then allowing folks to replace the entire animation may be the best route here. I'd suggest researching the former, and if not possible we go with the latter.
