### ISSUE TITLE
Update how keyed feature works in the Table of Contents docs

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2294]
### Link to the Page

https://www.skeleton.dev/utilities/table-of-contents

### Describe the Issue (screenshots encouraged!)

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/5d75f92f-b039-4ad2-b5ae-5824c6a0fe52)

We need a few small changes:

1. Self reference how this is used in the doc site (page tabs update on change)
2. Change the `const` to a `let` to indicate this value can change
3. Implement a simple example of how this can change, and what it will do:

```ts
let tabindex = 0;
// tabindex = 1; -> triggers an update!
```

**Comment by phamduylong** [comment]
I can give this a go.
