### ISSUE TITLE
Table of Contents has trouble with dynamic headings

### ISSUE THREAD

**Issue by garikAsplund** [skeletonlabs/skeleton#2297]
### Current Behavior

I have a component that I use multiple times on the same page for holding information on talks which I would like to have in the table of contents for quick access. So there's "Keynote 1", "Keynote 2", etc. 

```js
<header class="sticky flex justify-between items-baseline pt-12 top-0 px-6 z-10 h-24 bg-surface-100-800-token mb-36">
	<h2 class="h2" id="Keynote {speaker.slot}">Keynote {speaker.slot}</h2>
	<h4 class="h4" data-toc-ignore>{speaker.time}</h4>
</header>
```

But when this is rendered there is no number after the "Keynote" in the table of contents sidebar. The scroll behavior works as expected, but the label is off and it wouldn't make sense for users to use with this.

<img width="827" alt="Screenshot 2023-12-07 at 9 41 53 AM" src="https://github.com/skeletonlabs/skeleton/assets/111464359/ee5a32d2-69b6-4e9e-b541-e0b320054e89">

### Expected Behavior

Each keynote should be labeled with its number in the table of contents.

![image](https://github.com/skeletonlabs/skeleton/assets/111464359/63ae10b0-4940-4df7-ab1b-90ff7b20a642)

### Steps To Reproduce

Set up a table of contents and crawl a page.
Make sure the headers you are crawling have dynamic info rendered. For me it was coming from an array of speakers like this:
	`<h2 class="h2" id="Keynote {speaker.slot}">Keynote {speaker.slot}</h2>`

### More Information

When looking at the [source for the crawler](https://github.com/skeletonlabs/skeleton/blob/7849c406569d26504392c08b945deefced08206b/packages/skeleton/src/lib/utilities/TableOfContents/crawler.ts#L61C23-L61C23) I found some info that is helpful for this particular case. 

When the dynamic info is placed in the header, it is done so as a new child. Since the crawler uses only the firstChild text as reference for the links in the table of contents, the dynamic data in the secondChild is missed. This was done to avoid including badges or other extraneous info in the link seen here:

![image](https://github.com/skeletonlabs/skeleton/assets/111464359/c5e25db8-70ac-4f99-aacd-b9775ec45c84)

```js
// Code as is written
  // Push heading data to the permalink array
  permalinks.push({
    element: elemHeading.nodeName.toLowerCase(),
    id: elemHeading.id,
    text: elemHeading.firstChild?.textContent?.trim() || ''
  });

// Minor change that works in my case
  // Push heading data to the permalink array
    permalinks.push({
      element: elemHeading.nodeName.toLowerCase(),
      id: elemHeading.id,
      text: elemHeading.textContent?.trim() || ''
    });
```

Picture of working implementation:
<img width="1429" alt="Screenshot 2023-12-07 at 2 30 46 PM" src="https://github.com/skeletonlabs/skeleton/assets/111464359/eb6b5a38-caee-4f97-bf5b-2f36f8aee37c">

**Comment by garikAsplund** [comment]
I don't know why this didn't come to me initially, but this is by far the easier solution: 
`<h2 class="h2" id="Keynote {speaker.slot}">{"Keynote " + speaker.slot}</h2>`

This way you can use the library as is and not worry about copy/pasting and modifying. Just have the output text in one line of JS within the HTML tags.

**Comment by Mahmoud-zino** [comment]
@garikAsplund 
Your solution works perfectly, and I think there is no other way to solve the issue without hacking the Table of content, which we should avoid.
I will add a section to the docs to explain this issue and how to solve it using your approach.

**Comment by endigo9740** [comment]
@Mahmoud-zino Gark has provided a very simple solution to this issue in his last post above. Do please feel free to add that to the docs. I think this could help benefit others.
