### ISSUE TITLE
Table word break styles have a breakpoint set too high

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2302]
### Current Behavior

Discord Discussion:
https://discord.com/channels/1003691521280856084/1151213014721241128/1183103664555044974

### Expected Behavior

The `lg` breakpoint here may be too aggressive:
https://github.com/skeletonlabs/skeleton/blob/master/packages/plugin/src/styles/components/tables.css#L58

We should either:
1. adjust this to `md`, or...
2. provide a way for end users to configure this themselves

### Steps To Reproduce

--

### Link to Reproduction / Stackblitz

https://www.skeleton.dev/elements/tables

**Comment by Mahmoud-zino** [comment]
@endigo9740 per the second suggestion, should we extract the whitespace vars to a prop on the table component or do you have something else in mind?

**Comment by endigo9740** [comment]
That's what I was thinking. Additional utility classes on the parent Table element. But it's something that we'll have to tinker with and test. In theory it should work.

**Comment by Mahmoud-zino** [comment]
@endigo9740 the .table css class is being used in both the utility and component table, for the component table a prop solves the probem but what should we do with the utility table?
should we delete the whitespace classes and mention them in the docs or keep them and use "! (important)" on the component table?

**Comment by endigo9740** [comment]
@Mahmoud-zino yeah I know they are shared. I won't have a good answer until I can dig in next week. Feel free to pause on this until then.

**Comment by endigo9740** [comment]
@Mahmoud-zino FYI I'm going to just adjust the breakpoint as is. Breaking the style out to a utility class would be considered a breaking change since it changes the default behavior. So we'll need to keep this in mind for v3. I'll put a "FIXME" comment inline in the stylesheet to help us remember to do this when we get to this.
