### ISSUE TITLE
Add tab deep linking support to DocShell layout

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2303]
### Link to the Page

https://github.com/skeletonlabs/skeleton/blob/dev/sites/skeleton.dev/src/lib/layouts/DocsShell/DocsShell.svelte#L31

### Describe the Issue (screenshots encouraged!)

We should add a means to list to URL params like `?tab=xx` via the SvelteKit `$page` store, then update the

**Comment by Mahmoud-zino** [comment]
@endigo9740 can you please provide more details :smile:

**Comment by Sarenor** [comment]
I know this one: It would be awesome to be able to generate links that open a specific DocShell Tab as in Props, events, etc

**Comment by endigo9740** [comment]
@Mahmoud-zino take a look at the DocShell. See where `tabPanel` is set? See need to update the value of that based on the URL parameter called `tab`. So if I go to:

```
https://www.skeleton.dev/components/accordions?tab=props
```

It'll open the Accordion docs straight to the props tab. To accomplish this, we can listen to and fetch the URL params from $page and populate this value.

As Dom said, this will be used for support to allow us to deep link to a particular tabbed section. Such as when folks miss that the Props tab is a part of the docs.

**Comment by Mahmoud-zino** [comment]
@endigo9740 ok now I get it, and should we target only the main tab of the pages or also other tabs like in the lightswitch page?

and I would like to work on this issue :+1:

**Comment by endigo9740** [comment]
Yeah we'll focus on the tabs built into the DocShell for now. Other tabs are local to individual pages, so those will have to be handled on a case by case basis. Though I'm not too concerned with doing that right this moment.
