### ISSUE TITLE
Lightswitch OS preference failing ESLint

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2308]
### Discussed in https://github.com/skeletonlabs/skeleton/discussions/2306

<div type='discussions-op-text'>

<sup>Originally posted by **travisgalloway** December 11, 2023</sup>
The example code block for the OS preference for the lightswitch utility causes ESLint to fail parsing.

```
<svelte:head>{@html `<script>${autoModeWatcher.toString()} autoModeWatcher();</script>`}</svelte:head>
```

 I'm not sure how to correct or suppress the error. Any suggestions?</div>

**Comment by endigo9740** [comment]
@travisgalloway here's the issue. This week is kind of crazy for me, but I'll plan to run through various bug issues next week. Unless someone else jumps on this sooner, expect an update then. Sorry for the delay!

I might suggest using the class-strategy for now and set/remove the `.dark` class to pin a particular light/dark mode as a temporary work around if you can.

**Comment by phamduylong** [comment]
Looks similar to what I faced [here](https://github.com/skeletonlabs/skeleton/pull/2296/commits/125ff38622e5c7c3c591e95f4b276b7f5d5cf091). Not sure it solves the issue but might worth a try.

[Discord chat](https://discord.com/channels/1003691521280856084/1003699523522142399/1183462228930867311)

**Comment by endigo9740** [comment]
@travisgalloway see @phamduylong suggestion above. I believe this may be the issue. The script tag is breaking this so you have to insert the special characters to help avoid this.

We're going to be looking at other ways to go about this scenario in the next major version of Skeleton, so keep an eye out for that in the future.

**Comment by endigo9740** [comment]
Note, this update should come after this PR is merged due to the number of doc page updates:
https://github.com/skeletonlabs/skeleton/pulls
