### ISSUE TITLE
Links/Buttons flash on click on mobile devices in Chrome/Edge.

### ISSUE THREAD

**Issue by Jabronironi** [skeletonlabs/skeleton#2310]
### Current Behavior

When you are viewing skeleton.dev on mobile and you click on a button or link, you get a square flash covering the item for a brief moment before remaining click animation occurs.  This does not occur on desktop versions of these browsers.  I have found the issue on the following:

- Pixel 8 - Chrome
- Windows 11 - Edge - Mobile Emulation
- Windows 10 - Chrome & Edge - Mobile Emulation

I am sure it is happening on others, but those are the ones I quickly found it on.

### Expected Behavior

The link animation/behavior on mobile should be consistent and match the desktop.  The desktop shows the animation without the flash when clicked.

### Steps To Reproduce

- Visit the skeleton.dev website and view the button component while using mobile Edge, Chrome.
- Click on any button and observe the square box that flashes on click.

Edit - Removed the examples as the video recorded did not record with enough detail to really see the bad behavior.

**Comment by endigo9740** [comment]
@Jabronironi you're describing the mobile focus state. Which is very much an intended feature and not a bug:
https://www.skeleton.dev/elements/core#mobile-focus

Skeleton doesn't introduce this, but merely alters the default color (the default is blue in some mobile browsers). We introduce this as part of our core styling, but you are welcome to customize as you see fit. Just note the warnings we've put in our source about removing this - which would be harmful to accessability:

https://github.com/skeletonlabs/skeleton/blob/master/packages/plugin/src/styles/base/core.css#L17

**Comment by Jabronironi** [comment]
I appreciate the pointer and fast response.  Thank you!
