### ISSUE TITLE
SvelteKit v2 Update!

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2312]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Full announcement:
https://svelte.dev/blog/sveltekit-2
https://svelte.dev/docs/v4-migration-guide

Known Issues:

- [x] PurgeCSS plugin throws error ([now fixed!](https://github.com/AdrianGonz97/vite-plugin-tailwind-purgecss/releases/tag/v0.2.0))

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

As with any major update, we recommend taking care when updating. We'll be testing this internally for Skeleton and will aim to give the go ahead for others early next week. In the meantime, if you update early, feel free to share any Skeleton-related issues you come cross here. Please and thanks!

**Comment by ninogjoni** [comment]
Got an error installing vite-plugin-tailwind-purgecss:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: buy-used-vehicles@0.0.1
npm ERR! Found: vite@5.0.9
npm ERR! node_modules/vite
npm ERR!   dev vite@"^5.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^4.1.1" from vite-plugin-tailwind-purgecss@0.1.4
npm ERR! node_modules/vite-plugin-tailwind-purgecss
npm ERR!   dev vite-plugin-tailwind-purgecss@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
```

Since it is mentioned here in the docs ([Link](https://www.skeleton.dev/docs/purgecss)), I thought I would post the problem here.

**Comment by endigo9740** [comment]
Thanks @ninogjoni, per Nik's updated above he's reported and provided a potential PR fix to [Adrian's PurgeCSS plugin](https://github.com/AdrianGonz97/vite-plugin-tailwind-purgecss). Please follow this for updates. We'll then aim to inform folks to update this plugin alongside any other required migration steps alongside our next release early next week. Thanks!

**Comment by endigo9740** [comment]
@AdrianGonz97 has pushed out a fix for the PurgeCSS plugin. We recommend you updated to v0.20 asap!
https://github.com/AdrianGonz97/vite-plugin-tailwind-purgecss/releases/tag/v0.2.0

ATTN: @ninogjoni @daaa1m

**Comment by endigo9740** [comment]
Looks like we'll have some updates to `viteProcess` and a few dependencies when we update our own doc site:
https://kit.svelte.dev/docs/migrating-to-sveltekit-2#vitepreprocess-is-no-longer-exported-from-sveltejs-kit-vite

**Comment by niktek** [comment]
Just a note for the sites/skeleton.dev migration that the vitePreprocess export is changed: https://kit.svelte.dev/docs/migrating-to-sveltekit-2#vitepreprocess-is-no-longer-exported-from-sveltejs-kit-vite

**Comment by endigo9740** [comment]
Quick update on this: the migration for Svelte 4 went smoothly, however I've hit a roadblock with the SvelteKit 2 update. Three issues specifically:

1. The `hook.server.ts` iteration of `event.cookies.set` [did not set the path as expected](https://kit.svelte.dev/docs/migrating-to-sveltekit-2#path-is-required-when-setting-cookies) in the migration guide. Setting this manually did not seem to make a difference outside of resolving a highlighted error in that page.
2. Our DocSiderbar component was incorrectly using a click listener to trigger `drawer.close()` when an `<li>` tag was tapped - triggering an a11y warning. This has been migrated to automatically close the drawer on navigation instead.
3. Unfortunately we're still getting a slew of errors in the terminal complaining that the Stepper component path cannot be resolved. I have no idea why that component specifically.

> NOTE: that I did upgrade to the latest version of PurgeCSS

@niktek @AdrianGonz97 I have a pending draft PR here if you guys would like to take a stab at this:
https://github.com/skeletonlabs/skeleton/pull/2325

I'll plan to move forward with our new release today and let folks know we're still testing SK2 support. But generally speaking it should be fine for new projects.

**Comment by endigo9740** [comment]
@AdrianGonz97 @niktek I'm going to go ahead and call this a wrap. Feel free to reopen and revisit anytime before we archived the v2 branch, but for now we've got bigger fish to fry.
