### ISSUE TITLE
Create Social Preview image on GitHub

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#2313]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

https://github.com/skeletonlabs/skeleton/settings - Social Preview 3 items down.

 (1280×640px for best display)

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@niktek DONE!

![Screenshot 2023-12-20 at 4 22 04 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/a504f240-1594-4c8a-a20f-a94bf95aa0e3)

Source for future reference:
![skeleton](https://github.com/skeletonlabs/skeleton/assets/1509726/64430401-3279-4c78-b3a3-9f76263488d4)
