### ISSUE TITLE
NEXT: Investigate using OKLCH colors

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#2315]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Seeing as Tailwind has support for it, we should investigate if Themes can (optionally?) make use of [OKLCH colors](https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl)

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@Sarenor thanks for doing this, but I forgot to mention I appended the feedback to the Theme Generator and new i18n tickets:

https://github.com/skeletonlabs/skeleton/issues/1142
https://github.com/skeletonlabs/skeleton/issues/2314

I'll close this out as a duplicate
