### ISSUE TITLE
Input Chips should not trim inner spaces

### ISSUE THREAD

**Issue by Mero-Plaform** [skeletonlabs/skeleton#2349]
### Current Behavior

`<InputChip/>` by default is preventing duplicates, but is timing inner spaces and for this reason, there is a problem: by entering `"t x"` & `"t       x"` we are getting same chip twice `"t x"`.

Input text should not be changed in such a way by component.the 

### Expected Behavior

Input text with spaces inside should remain the same: `"t       x"` -> `"t x"` or at least should be prop to prevent this behavior.

### Steps To Reproduce

1. The code:

```
<script lang="ts">
  import { InputChip } from "@skeletonlabs/skeleton";
</script>

<InputChip name="chip1"/>
```

2. Input `"t       x"` text to <InputChip/>

3. Input `"t x"` text to <InputChip/>

4. You get twice the same chip

**Comment by phamduylong** [comment]
I can take a look at this.

**Comment by phamduylong** [comment]
```ts
function validate(): boolean {
  if (!input) return false;
  // Format: trim value
  input = input.trim();
  ...
}
```

Input string will be trimmed as shown above. @endigo9740 any suggestions/workaround for this? Maybe we only take out spaces infront and behind the string 🤔

**Comment by Mero-Plaform** [comment]
The values list is OK, it's just a default text rendering behavior, which can be solved by using"white-space: pre;" for chip spans.

**Comment by Mero-Plaform** [comment]
The values list is OK, it's just a default text rendering behavior, which can be solved by using"white-space: pre;" for chip spans.
