### ISSUE TITLE
TreeViewItem "leaf" with no children should not show the Pointer Cursor, and can't set it to use default cursor

### ISSUE THREAD

**Issue by ctwobosius** [skeletonlabs/skeleton#2350]
### Current Behavior

Currently, if you hover over a `TreeViewItem` it shows the pointer cursor:
![image](https://github.com/skeletonlabs/skeleton/assets/55601295/a6a22a0f-35e6-4a73-8131-2ab817b689d0)

Trying to set the style using tailwind classes, eg: `<TreeViewItem class="cursor-default">` doesn't work, as the underlying `summary` child element is of class `cursor-pointer` which overrides the TreeViewItem's style.

### Expected Behavior

It should show a default cursor: 
![image](https://github.com/skeletonlabs/skeleton/assets/55601295/21c4b6c3-18bc-4831-b6a6-7e29123ff3a8)
particularly if I try to override the default style with `<TreeViewItem class="cursor-default">`.

### Steps To Reproduce

This is evident on the Skeleton UI's example Tree View documentation page.

### Link to Reproduction / Stackblitz

https://www.skeleton.dev/components/tree-views

### More Information

Maybe if you have the list of children, you can check if the size is 0, and if so, apply `class="cursor-default"` to it. Thanks for reading!

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2358
