### ISSUE TITLE
NEXT: Overlay System (modals/drawers/toasts)

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2357]
This will act as a hub to centralize for this information.

## Proposal

- https://github.com/skeletonlabs/skeleton/discussions/2629

## Maintainer Requests

The following requests are coming straight from the Skeleton team. These are highly likely be implemented:

- [x] Replaces both https://github.com/skeletonlabs/skeleton/issues/2397 and https://github.com/skeletonlabs/skeleton/issues/2398
- [x] Provide more documentation security restrictions for global reactive state.
- [x] Consider consolidating on the "Registry" method rather than the "Direct" or canned options.
- [x] Provide more parity between params and component props for custom components
- [x] Async/await functionality for response function execution so the Modal stays open while the response computes.
- [x] Review using the native [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API)
- [x] Review using the native [Dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) element (likely as a fallback)
- [x] We need to provide more guidance around form handling within modals

## Community Requests

The following requests have come from the community and are under consideration:

* https://github.com/skeletonlabs/skeleton/issues/1655
* https://github.com/skeletonlabs/skeleton/issues/1034
* https://github.com/skeletonlabs/skeleton/issues/1813
* https://github.com/skeletonlabs/skeleton/issues/1865
* https://github.com/skeletonlabs/skeleton/issues/1757
* https://github.com/skeletonlabs/skeleton/discussions/2328#discussioncomment-7993586
* https://github.com/skeletonlabs/skeleton/issues/2409
* https://github.com/skeletonlabs/skeleton/pull/2673
* https://github.com/skeletonlabs/skeleton/pull/2644

## Bugs and Issues

- https://www.youtube.com/watch?v=yZT9906ZCLU
* https://github.com/skeletonlabs/skeleton/issues/2518
* https://github.com/skeletonlabs/skeleton/issues/1591
* https://github.com/skeletonlabs/skeleton/issues/2176

## Resources:

- Native `<dialog>` element:
  - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
  - https://dev.to/thomasvanholder/create-a-modal-with-the-html-dialog-element-tailwind-and-stimulus-573b
  - https://kentondejong.medium.com/we-can-finally-transition-display-none-cbb03831351f
  - https://frontendmasters.com/blog/animating-dialog/

## Feedback

If you have additional updates or requests for this feature, please do so in the comments section below.

**Comment by adamdva** [comment]
Please consider including a means to disable the backdrop's click to close feature. The ARIA APG guidelines do allow for this, marking a dialog modal only when both:
1) Application code prevents all users from interacting in any way with content outside of it.
2) Visual styling obscures the content outside of it.

**Comment by jhechtf** [comment]
Please move Modals away from the singleton pattern.

**Comment by rChaoz** [comment]
Here's a proposal for implementing modals/drawers/popups/whatever: [REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE41SwY6bMBD9lZHTSom0CUmrPSyQqJV67a230gPBAxmtsS3bpEkR_15jCAnalVqJA372vDfz5rWsJIGWxT9bJvMaWcy-as2emLvq_mDPKBz6s1WNKXoktYUh7Q6ZzBzVWhkH3ygXqvqey7xCA6VRNWRsE83gzcCUsYe6FpRGOTyD7t-FaXTXlulcNQpgu7CStEYHPNwuC6EsrrpeNOV0BuuuAvcZ08qSIyVjMChyR2dM4KgMRxODVYI47PQFjiIvXhPQOeckqxg-GawzFkbP3I8TWfBfPmoNaHpsnFPyHaH86Ikb54Wc0jFsN8-eLQFD1cndjhkDJQtBxeu-Da13h0saDZRBNo38FP6vjcZBu-DFKDrVLlewPzy4uxxaXHWBpMenpid6v-RacSoJOYudabB7mjIx8_o_0gGFkg4vzhvgORuBo2ti2gzs4YN1ucOlbIRY9VNkviLkomxk0Xs2G2AF7eDwVM_7czdUTiXBteXbx73K-H4Wo3ZB5djSPSXEfeMDuK6Hoae1t18MSp-T9xI2LYfKYS8hBaFwMae79XePR0kX5MmA_ibuTjHsttuPI3LCISYP0J81-T4uMby8vCS3aa0W-TWGytCNywMFrslhbWMo0K_FjDdHH-7KqEbydaGE8slf7Dz_dvt5m9ytChO8zcav7i_G7V1EOwQAAA==)

While this does still use a "singleton" state under the hood, I'm sure this can be avoided. The idea is that, with snippets, it becomes extremely is to just pass a snippet to a "openModal" function and it gets rendered. No modal store, no anything. This could then easily be refactored into a `<Dialog open={true/false}> ... </Dialog>` for ease of use.

**Comment by endigo9740** [comment]
Thank you @rChaoz - this is actually pretty close to what I have in mind as well. I've been quietly working on a mixture of Popups and Modals this week, so I should have more to show per next week's regular update. [Keep an eye out here](https://github.com/skeletonlabs/skeleton/discussions/2375) or in our Discord `#announcements` channel for that.

But the general idea is we're going to aim for the following:

- Still provide a queue-bases singleton approach. This will default to the registry approach only, while being optional and opt-in.
- We'll also provide styles for the native `<dialog>` component, or a guidance around styling this yourself, for folks that want modals to be a "one-off" per page.
- Finally, we're investigating the use of Floating UI to handle the [overlay display](https://floating-ui.com/docs/dialog) of not just popover elements (menus, tooltips, etc) but also modals/drawers/alerts. Kind of unifying all of these under a single umbrella.

IBut again, I've got some prototypes generated that I'll cover in next week's update.

**Comment by jhechtf** [comment]
Where did we land on not using the registry and just allowing users to simply use the components directly?

**Comment by endigo9740** [comment]
> Where did we land on not using the registry and just allowing users to simply use the components directly?

I'll likely add a guide for integrating the native `<dialog>` component as an alternative for that pattern. Then you, as the user, have full control over the state and display locally. It won't be as robust, but it's really the only logical step to support both patterns.

**Comment by jhechtf** [comment]
So Skeleton will default to the registry? If so, sad to hear.

**Comment by TweedChristian** [comment]
Something to consider is the push on progressive enhancement in the SvelteKit ecosystem (e.g., [superforms](https://superforms.rocks/), so it would be great if we could have a JS-less version for server-side rendering the modals and overlays. 

While popover API is nice, it is still only at 85% [availability](https://caniuse.com/?search=popover) as of today. If we could get first-class support for dialog elements via tailwind utility classes than it would definitely further the progressive enhancement of Skeleton.

**Comment by endigo9740** [comment]
@jhechtf sorry for the late reply, but the registry system will be the right approach for a "system". Remember the goal is a universal queue globally scoped throughout your app. If you're just aiming for a quick one-off, the native `<dialog>` and upcoming Popover API already solve those situations really well. I know a lot of folks were turned off by the complexity in v2, but that'll be highly stripped away in this future iteration.

@TweedChristian you've touched on a couple topics here, so let me break this down

1. There's been a lot of confusion around form submission within modals since the earliest days of Skeleton. In that time we've seen Load functions and Form Actions come to be available in SvelteKit, which have greatly improved the DX for most use cases. But *really good* modals are inherently portable - which disconnects them from the co-located load functions per load/page section. Really the best approach for this for the forms to submit to internal SvelteKit [API routes](https://kit.svelte.dev/docs/routing#server) (aka endpoints). That way they can submit from any portion of the app. As such we do hope to cover this in this next iteration. And btw Superform (while very cool) are just additional tooling on top of these underlying tools.
2. We're well aware of the status of the Popover API and CSS Anchoring APIs, which is why @Hugos68 and I have been quietly working on [Floating UI Svelte](https://floating-ui-svelte.vercel.app/) - a full fledge Svelte 5 port of [Floating UI React](https://floating-ui.com/docs/react). We feel this will help bridge the gap until the native APIs catch up. And of course we'll have an [integration guide for Skeleton v3](https://next.skeleton.dev/docs/integrations/popovers/svelte) asap.
3. Finally, in regards to the native `<dialog>` component. We have no qualms with folks using that as I mentioned to Jim above. We'll likely provide some additional guidance for that. But I'm not fully convince it's a drop-in solution for our overlay -system-. We need to do things like queue modals, which the native element doesn't excel at IMO. But if we can find a way to make it work we will, because Skeleton leans into native-first by default.

Thanks for your feedback though! And obviously keep an eye out for more updates in the future.

**Comment by jhechtf** [comment]
@endigo9740 I greatly disagree with your decision and am immensely disappointed. I hope we will still be able to make our own modals that fit within the Skeleton system as we are now as your previous system did not work for me.

**Comment by endigo9740** [comment]
Quick update here - I'm in the process of researching modal options for Skeleton v3 and wanted to share that even fi we go all in on the "queue system", the browser native `<dialog>` element pairs just fine with Skeleton styles. Here's a quick example I worked up within a Astro component (which is fairly close to native html/css/js)

https://github.com/user-attachments/assets/376640ec-772c-4557-91c5-64a352b9d6f2

Here's the code used to test:

```html
<div class="w-full">
	<!-- Dialog -->
	<dialog
		data-modal
		class="dialog rounded-container bg-surface-100-900 text-inherit max-w-[640px] p-4 space-y-4 z-10 backdrop:bg-surface-50/75 dark:backdrop:bg-surface-950/75"
	>
		<h2 class="h3">Example</h2>
		<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
		<form method="dialog" class="flex justify-end">
			<button type="button" class="btn preset-tonal" data-modal-close>Close</button>
		</form>
	</dialog>
	<!-- Interface -->
	<div class="flex justify-center items-center">
		<!-- Trigger -->
		<button class="btn preset-filled" data-modal-show>Open Modal</button>
	</div>
</div>

<script is:inline>
	// DOM Elements
	const elemDialog = document.querySelector('[data-modal]');
	const elemTrigger = document.querySelector('[data-modal-show]');
	const elemClose = document.querySelector('[data-modal-close]');
	// Listeners
	elemTrigger.addEventListener('click', () => elemDialog.showModal());
	elemClose.addEventListener('click', () => elemDialog.close());
</script>

<style>
	.dialog,
	.dialog::backdrop {
		--anim-duration: 250ms;
		transition:
			display var(--anim-duration) allow-discrete,
			overlay var(--anim-duration) allow-discrete,
			opacity var(--anim-duration);
		opacity: 0;
	}
	/* Animate In */
	.dialog[open],
	.dialog[open]::backdrop {
		opacity: 1;
	}
	/* Animate Out */
	@starting-style {
		.dialog[open],
		.dialog[open]::backdrop {
			opacity: 0;
		}
	}
</style>
```

Note that there's various ways to approach defining the DOM references and for handling the animations. In a more flushed out example I'd probably use [transition-behavior](https://kentondejong.medium.com/we-can-finally-transition-display-none-cbb03831351f) as I expect it'll have the best cross-browser support long term. This would serve as a progress enhancement means it only displays animations when the browser support the feature.

But everything here is using a mix of Skeleton v3 primitive styles + Tailwind-specific variants, such as `backdrop:`. You can honestly do quite a lot with this!

I'll continue testing this over the next couple weeks though and when we settle on our solution I'll share more in public announcements.

**Comment by entrenadorhispano** [comment]
Please, consider getting away from singleton patterns.

They seems cool but are very painful to use, also Svelte kit shallow routing is very important on android mobile devices and is difficult to manage on singleton patterns.

Also, focus trap on skeleton 2 is making some components to render user-agent outline which is a very bad orange color in some cases, absolutely odd to the rest of the UI system. 

Thanks for all your time and effort, Skeleton is VERY good and simple to use in general 💯

**Comment by endigo9740** [comment]
I'll be posting a new [Discussions](https://github.com/skeletonlabs/skeleton/discussions) announcement tomorrow that details our solutions for Modals in v3. Anyone wishing to move away from the Singleton-based approach should be please with the new offering! Please also refer to [this PR](https://github.com/skeletonlabs/skeleton/pull/2872) and the new [Popover Integrations](https://next.skeleton.dev/docs/integrations/popover/react) section within the v3 docs.

Additionally, please refer to this post regarding [Toasts](https://github.com/skeletonlabs/skeleton/issues/2884), which will be split off to a new dedicated component. Full details can be found in the linked post.

Finally, note that work on [Floating UI Svelte](https://floating-ui-svelte.vercel.app/) will continue beyond the Skeleton v3 launch. Progress for that should be [tracked on GitHub](https://github.com/skeletonlabs/floating-ui-svelte/issues).
