### ISSUE TITLE
Autocomplete: Bind a second, hidden input

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#2365]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Users have often requested to use the Autocomplete to display one value to their end users, while submitting another value (an ID, for example) to the server.

This is impossible with a single text input bound to ``bind:value`` that displays the display value of the selected Autocomplete Option.
If a second bind point would be provided, users could bind this to a hidden input that then can be submitted to the server. The autocomplete would need to optionally set that input, if it is present.

### What type of pull request would this be?

New Feature

**Comment by endigo9740** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2366
