### ISSUE TITLE
NEXT: Autocomplete

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#2366]
## Floating UI Integration

https://floating-ui.com/docs/useTypeahead

## Maintainer Requests

The following requests are coming straight from the Skeleton team. These are highly likely be implemented:

* We need better documentation around how to combine and use this with input chips and popups. People have struggled with this in the past.
* https://github.com/skeletonlabs/skeleton/issues/2365
* The type for the `input` prop should be changed to `string | number | undefined`. See: https://github.com/skeletonlabs/skeleton/issues/2647#issuecomment-2096708848
* (expect this to expand over time)

## Community Requests

The following requests have come from the community and are under consideration:

* https://github.com/skeletonlabs/skeleton/issues/1939
* https://github.com/skeletonlabs/skeleton/issues/1967
* Grouping Autocomplete options
* https://github.com/skeletonlabs/skeleton/issues/2406 (TLDR; deny all options when allowList is empty and allow all when undefined or null)
* https://github.com/skeletonlabs/skeleton/issues/2493
* https://github.com/skeletonlabs/skeleton/issues/2536

## Bugs And Known Issues

* https://github.com/skeletonlabs/skeleton/issues/2536

## Feedback

If you have additional updates or requests for this feature, please do so in the comments section below.

**Comment by gstrand99** [comment]
I would love to have the ability to add an on:hover event to the Autocomplete component so that I could display a popup while hovering over one of the list items with more details about that specific item. It would be useful for adding longer descriptions for that specific item.

**Comment by endigo9740** [comment]
This will now be handled by the same solutions covered in the Modals milestone post.

https://github.com/skeletonlabs/skeleton/issues/2357
