### ISSUE TITLE
NEXT: Range Slider

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2367]
## Zag Implementation

https://zagjs.com/components/react/range-slider

## ARIA Guidelines

-  [Single Slider](https://www.w3.org/WAI/ARIA/apg/patterns/slider/)
- [Multi Slider](https://www.w3.org/WAI/ARIA/apg/patterns/slider-multithumb/)

## Maintainer Requests

The following requests are coming straight from the Skeleton team. These are highly likely be implemented.

- [x] Rename the component to `<Slider>` to match other libraries
- ~~Meet feature parity with Skeleton v2~~
- ~~Should bind one or more embedded range inputs (regardless of type)~~
- ~~Native-only: https://github.com/skeletonlabs/skeleton/issues/1066~~

## Community Requests

The following requests have come from the community and are under consideration:

- [x] https://github.com/skeletonlabs/skeleton/issues/2224 ([reference](https://www.w3.org/WAI/ARIA/apg/patterns/slider/))

## Bugs and Issues

* ...

## References

* [Skeleton v2](https://www.skeleton.dev/components/range-sliders)
* [Skeleton v3 progress bars](https://next.skeleton.dev/docs/components/progress/react)
* [Shadcn](https://ui.shadcn.com/docs/components/slider)
* [Mantine](https://mantine.dev/core/slider/)
* [Material Design](https://m3.material.io/components/sliders/overview)

## Feedback

If you have additional updates or requests for this feature, please do so in the comments section below.

**Comment by Silvallis** [comment]
In my proposal ([Dual Range Slider #2224](https://github.com/skeletonlabs/skeleton/issues/2224)) there where concerns regarding the accessibility of such an component. Therfore I am linking the ARIA Guideline for the multithumb pattern:
https://www.w3.org/WAI/ARIA/apg/patterns/slider-multithumb/

**Comment by Elliott-Green** [comment]
+1, come across needing a dual range slider today and found this, showing interest.
