### ISSUE TITLE
Disabled scroll after closing Popup on Safari

### ISSUE THREAD

**Issue by louiskhub** [skeletonlabs/skeleton#2368]
### Current Behavior

I have a page that's scrollable and one component has a [popup](https://www.skeleton.dev/utilities/popups).
The popup itself is scollable, when opened.
After closing the popup, the user is unable to scroll in the area where the popup was visible. This only happens on Safari.

### Expected Behavior

Be able to scroll in the section where the popup was open previously.

### Steps To Reproduce

Click on a (scrollable) popup and close it. Try to scroll inside of the area where the popup was.

Use this example-code with the latest version of Skeleton (2.6.1) and Svelte (4.2.1):

```html
<script lang="ts">

	import {
		Autocomplete,
		popup,
		type PopupSettings,
		InputChip
	} from '@skeletonlabs/skeleton';

	const examplePopup: PopupSettings = {
		event: 'click',
		target: 'examplePopup',
		placement: 'bottom',
		closeQuery: '.listbox-item'
	};
	const exampleOptions = [
		{ label: 'option1', value: 'option1' },
		{ label: 'option2', value: 'option2' },
		{ label: 'option3', value: 'option3' },
		{ label: 'option4', value: 'option4' },
		{ label: 'option5', value: 'option5' },
		{ label: 'option6', value: 'option6' },
		{ label: 'option7', value: 'option7' },
		{ label: 'option8', value: 'option8' },
		{ label: 'option9', value: 'option9' },
		{ label: 'option10', value: 'option10' },
		{ label: 'option11', value: 'option11' },
		{ label: 'option12', value: 'option12' },
		{ label: 'option13', value: 'option13' }
	];
</script>

<div class="flex w-screen justify-between gap-5 px-5 py-4">
	<button
		class="btn w-min justify-between border-2 border-surface-500 bg-surface-200 shadow-lg"
		use:popup={examplePopup}>Open/Close Popup</button
	>

	<div
		data-popup="examplePopup"
		class="card hide-scrollbar z-10 h-min max-h-[20rem] w-max max-w-full overflow-y-scroll border-2 border-surface-500 p-4 shadow-2xl"
		tabindex="-1"
	>
		<InputChip name="chips" />
		<Autocomplete options={exampleOptions} />
	</div>
</div>

<div class="flex flex-1 overflow-y-hidden">
	<div
		class="hide-scrollbar mt-4 flex h-full w-fit flex-col items-center gap-4 overflow-y-scroll bg-green-500 px-5 pb-14"
	>
		<p>Item 1</p>
		<p>Item 2</p>
		<p>Item 3</p>
		<p>Item 4</p>
		<p>Item 5</p>
		<p>Item 6</p>
		<p>Item 7</p>
		<p>Item 8</p>
		<p>Item 9</p>
		<p>Item 10</p>
		<p>Item 11</p>
		<p>Item 12</p>
		<p>Item 13</p>
	</div>
</div>
```

**Comment by louiskhub** [comment]
Update: It seems like this issue is weirdly related to older MacOS versions.
Everything behaves as expected on Sonoma 14.1.
On Monterey 12.7.2, the issue occurs. Can't test for any versions in-between. Can anyone test and confirm?

**Comment by endigo9740** [comment]
Hey @louiskhub, so versions are Safari are typically related to OS updates in macOS. So updating the OS would update Safari. My guess is you ran afoul of some CSS or JS property that was not supported in older versions of Safari. Something Svelte/Kit or Tailwind used that wasn't supported. You also mentioned popups, would would include Floating UI in that list as well.

And FYI we're looking to provide more details in Skeleton v3 docs that will showcase what versions of the tech we support. To help folks that are trying to run a version too new or too old. Keep an eye out for that in the future.
