### ISSUE TITLE
Popup error: (intermediate value)(...) is undefined trying to create inline tooltip

### ISSUE THREAD

**Issue by glenatron** [skeletonlabs/skeleton#2369]
### Current Behavior

I suspect this is a documentation problem rather than a functional problem but I will report what is happening and we can see.

I am trying to create some tooltips as described in the [documentation](https://www.skeleton.dev/utilities/popups) but when I try and open the view that contains the tooltip I'm getting the following error:
``` 
Uncaught (in promise) TypeError: (intermediate value)(...) is undefined
    popup popup.js:6
    mount +page.svelte:787
    m svelte-hooks.js:291
    mount_component Component.js:44 
   // and so on
```

### Expected Behavior

When I hover the password label a tooltip appears below it.

### Steps To Reproduce

I have the following code in my root `layout.svelte`: 
```
<script>
	import '../app.pcss';
	import { AppShell } from '@skeletonlabs/skeleton';
	import { computePosition, autoUpdate, offset, shift, flip, arrow } from '@floating-ui/dom';
	import { storePopup } from '@skeletonlabs/skeleton';

        storePopup.set({ computePosition, autoUpdate, offset, shift, flip, arrow });
</script>
```
Note that the documentation is confusing here because it tells you to import the floating-ui stuff in the root layout and then puts the skeletonlabs stuff in a separate box in the document and it isn't totally clear that you have to put it into the same file, so this may be in the wrong place.

Looking for a way to have multiple tooltips in a page without having to declare a lot of global constants, I found an old issue suggesting that the way to achieve this is by inlining the popup call but I couldn't find any documentation for how to do this, so in my `+page.svelte` I set it up like this:
```
<script lang="ts">
	import { popup, type PopupSettings } from '@skeletonlabs/skeleton';
        // a bunch of logic
</script>
          <div>
              <label class="label" for="password" use:popup={{event:"hover",placement:"bottom",target:"aboutPassword"};}>
                  <span>Your password</span>
              </label>
              <input name="password" id="password-input" class="input" title="password" type="password" />
           </div>
           <div class="card p4 w72 shadow-xl" data-popup="aboutPassword">
            <p>Your password should be long and complicated</p>
           </div>
          <div>
``` 
I tried using `const popupProperties: PopupSettings = { event: "hover", placement: "bottom", target: "aboutPassword" };` in the script section and `use:popup={popupProperties}` so I don't think it is just a problem with the inlining.

### More Information

The line where the error arises is `const { computePosition, autoUpdate, offset, shift, flip, arrow, size, autoPlacement, hide, inline } = get(storePopup);` in `popup.js` so it does seem quite likely that there's a problem with my setting of the `storePopup` parameter

Versions from my package.json: `"@skeletonlabs/skeleton": "^2.6.1", "@floating-ui/dom": "^1.5.3"`

**Comment by Sarenor** [comment]
You can use the popup in whichever place you want, you just need to define the store in your upper most layout, the root layout, so the one here ``routes/+layout.svelte``. Then, since you can't break out of the root layout as far as I know, it should always be available.

**Comment by endigo9740** [comment]
Hey @glenatron, sorry the docs gave you trouble. So to make sure it's clear. These values go in your root layout as Dom mentioned above:

```html
<script>
	import { computePosition, autoUpdate, offset, shift, flip, arrow } from '@floating-ui/dom';
	import { storePopup } from '@skeletonlabs/skeleton';
        storePopup.set({ computePosition, autoUpdate, offset, shift, flip, arrow });
</script>
```

This does three things:

1. Imports the modules from Floating UI that we need to make globally available
2. Imports the `storePopup`, which will house these modules and make them global
3. Then we drop the modules into the store with the `.set()` method.

With that done you now should now be able to setup popups through any part of your app under the scope of that layout. Emphasis on that last part, in case you're using multiple layouts by chance.

Then from there you're safe to import the popup action and settings type anywhere you wish to trigger a popup:

```html
<script lang="ts">
	import { popup, type PopupSettings } from '@skeletonlabs/skeleton';
</script>
```

Finally you implement the popup as you've done in your example. You certainly *can* implement the settings inline, but we advise doing this in your `<script>` tag so you can make use of the type here, to verify the settings defined meet the requirements. For example:

```html
<script lang="ts">
    import { popup, type PopupSettings } from '@skeletonlabs/skeleton';

    // ...

    const myPopupSettings: PopupSettings = { // <-- verifies your settings!
	 event: "hover",
	 placement:" bottom",
	 target: "aboutPassword"
    };
</script>
```

From that point it's just a matter of setting up the trigger button (to consume these settings) and the popup with the `data-popup` attribute.

Do note these values need to match:

```
target: "aboutPassword"
```
```
data-popup="aboutPassword"
```

> NOTE: which yours does!

So the only thing of note beyond that is you appear to be putting an extra `;` when you inline here:

```html
<label ... use:popup={{event:"hover",placement:"bottom",target:"aboutPassword"};}> <-- note the semicolon
```

Let me know if any of this helps though. Happy to help debug further!

**Comment by endigo9740** [comment]
No response so we'll consider this one complete. Thanks!
