### ISSUE TITLE
Code block not preserving initial white space

### ISSUE THREAD

**Issue by wtfacoconut** [skeletonlabs/skeleton#2372]
### Current Behavior

I'm using a code block in a modal (not sure if the modal is important to mention.
In the code block I have some code that has some whitespace at the very beginning of the code, but the code block is not preservinc that white space.  Instead, it almost looks like the code block component is trimming white space.

### Expected Behavior

Preserve whitespace at the beginning.

### Steps To Reproduce

<img width="553" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/5297545/de5248ab-a0a8-4cfe-a485-978b5bc8f44d">

<img width="1013" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/5297545/f6998b06-a3f4-4203-9431-b69e85a1b575">

**Comment by endigo9740** [comment]
That's correct, we trim whitespace:
https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/utilities/CodeBlock/CodeBlock.svelte#L74

You might be able to work around this by inserting `\n` to insert a new line near the end of your code markup. But this is intended behavior and I don't believe we'll be changing this.

If you would like to have more control over the syntax highlighting, you could opt for forego the CodeBlock component and implement Highlight.js directly. Instructions are provided on their documentation:
https://highlightjs.org/
