### ISSUE TITLE
NEXT: Focus Trap action

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2380]
> [!WARNING] 
> This issue is a work in progress.

This will act as a hub to centralize this information.

## Maintainer Requests

The following requests are coming straight from the Skeleton team. These are highly likely be implemented:

> NOTE: Currently this is expected to be a straight power. It seems to do everything required.

## Community Requests

The following requests have come from the community and are under consideration:
 
* n/a

## Bugs and Issues

* n/a

## Feedback

If you have additional updates or requests for this feature, please do so in the comments section below.

**Comment by TheEisbaer** [comment]
focus trap for modals doesn't seem to work as expected:

When creating a modal, the little x close button in the corner gets focused but I'd like to have it focused on the abort button (or any other doesn't really matter) 

I've tried setting the tabindex to -1 but then pressing tab switches through the element in the background
I've also tried using the data-focusindex but that doesn't change the behaviour at all

[https://stackblitz.com/edit/skeletonlabs-repl-fky8vw](https://stackblitz.com/edit/skeletonlabs-repl-fky8vw)

**Comment by endigo9740** [comment]
Now covered by the new modals solution:

- https://github.com/skeletonlabs/skeleton/issues/2357
