### ISSUE TITLE
NEXT: Switch

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2394]
This will act as a hub to centralize all requirements for this component.

## Maintainer Requests

The following requests are coming straight from the Skeleton team. These are highly likely be implemented:

- [x] Must meet all required [ARIA APG guidelines](https://www.w3.org/WAI/ARIA/apg/patterns/switch/)
- [x] Consider using [preset](https://next.skeleton.dev/design/presets) utility classes to style the track and thumb elements
- [x] Rename from `<SlideToggle>` to `<Switch />` to match the overall convention
- [x] Add slots to insert text/icons/etc in the thumb region in the on/off states

Not moving forward:

- ~~Consider [moving from a component to Element styles](https://github.com/skeletonlabs/skeleton/issues/2394#issuecomment-1986321598) per Hugo's request below.~~
- ~~(element-only) feature this on the [Forms & Inputs documentation](https://next.skeleton.dev/tailwind/forms)~~
- ~~(Safari-only) Apple now supports a [non-standard native implementation](https://webkit.org/blog/15054/an-html-switch-control/). Consider mentioning this.~~

## Community Requests

The following requests have come from the community and are under consideration:
 
* n/a

## Bugs and Issues

* n/a

## References

- Skeleton v2: https://www.skeleton.dev/components/slide-toggles
- Shadcn: https://ui.shadcn.com/docs/components/switch
- Mantine: https://mantine.dev/core/switch/
- Material Design: https://m3.material.io/components/switch/overview
- Bits: https://www.bits-ui.com/docs/components/switch
- Melt UI: https://melt-ui.com/docs/builders/switch

## Feedback

If you have additional updates or requests for this feature, please do so in the comments section below.

**Comment by Hugos68** [comment]
IMO we need to rethink simple components like the slidetoggle that are purely representational. Wrapping in the component does nothing except maybe give a semantic name to what you're using, this blocks all ways of intereacting with the DOM element being use. This can be *huge* for example in svelte where all the directives like `class:`, `style:`, `use:`, `animate:`, `transition:`, `in:` and `out:` are stripped away. [This is an incredibly simple implementation fo the slidetoggle using a class](https://play.tailwindcss.com/3zD7GHXgvT).

**Comment by endigo9740** [comment]
@Hugos68 I like it, my only concern is we lose the ability to press `enter` to toggle, which is part of the ARIA APG, but technically they have marked as "optional" in the guidelines:

https://www.w3.org/WAI/ARIA/apg/patterns/switch/

If you can tweak your repro to follow all guidelines here then I'm all for it. We can fold this into the Forms & Inputs page on the v3 docs and the styles will come as part of the new wave of plugin updates scheduled to start soon (next week?)

**Comment by endigo9740** [comment]
Just a follow up - @Hugos68 and I agree there's no great way to handle keyboard inputs (ex: Enter to toggle) with a styled checkbox alone. So we're going to keep that concept, but still wrap this in a dedicated component. Keep an eye out for an upcoming PR around this.

**Comment by endigo9740** [comment]
The attached PR is ready for review. Feel free to post your comments in the PR thread. If there's no major changes by next week I'll aim to merge and provide this as part of our upcoming release on Tuesday!
