### ISSUE TITLE
Tree component WAI-ARIA Down and Up Arrow not supported

### ISSUE THREAD

**Issue by mmailaender** [skeletonlabs/skeleton#2403]
### Current Behavior

![image](https://github.com/skeletonlabs/skeleton/assets/87228994/584ceb30-032a-4d2e-8450-2fb49784e07b)
Currently, the Down and Up Arrow are not supported, which are defined as mandatory in WAI-ARIA

### Expected Behavior

![image](https://github.com/skeletonlabs/skeleton/assets/87228994/983fca37-d41a-4e13-a567-03cb919c2a38)
Down and Up Arrow are working

**Comment by Mahmoud-zino** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

- https://github.com/skeletonlabs/skeleton/issues/2358
