### ISSUE TITLE
Collapse in Recursive Mode

### ISSUE THREAD

**Issue by dror-weiss** [skeletonlabs/skeleton#2405]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I would like to collapse the entire Recursive Tree View, but it doesn't have that kind of support.

### What type of pull request would this be?

Enhancement

**Comment by Mahmoud-zino** [comment]
@dror-weiss 
You can achieve the same effect by emptying the `expandedNodes` array.
no expanded nodes = collapsed nodes, and for sure you can do the opposite by including all nodes in the array.

if you have other feature requests in regard of the tree-view, please include them in #2358 , so we can evaluate and prepare them for v3.
