### ISSUE TITLE
Autocomplete: empty allowlist displays all values

### ISSUE THREAD

**Issue by Shackless** [skeletonlabs/skeleton#2406]
### Current Behavior

I'm binding an `allowlist` array to my `<Autoselect />`. If the `allowlist` is empty, **all** results are displayed. I can't use a custom filter function here because other components are filtering the list, so I have to way to call the custom filter when I need to.

### Expected Behavior

I'd expect the list to show "No results" because it means I filtered out all available items.

I didn't look into the code but I guess that `allowlist` probably has an empty array as default value so that it's optional and now you can no longer separate default value from user value. If that's the problem, maybe `null` or `undefined` could be used as default or an artificial value like "*" in the allowlist could be used to tell the component: "Display nothing!" (?)

### Workaround

I set all available choices as `denylist` if my `allowlist` is empty. 

The workaround works fine, so the issue is probably very low priority. I'll leave the ticket here in case somebody else struggles with this. Feel free to close this.

**Comment by Mahmoud-zino** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please do so here:

- https://github.com/skeletonlabs/skeleton/issues/2366
