### ISSUE TITLE
Divider token doesn't apply to children

### ISSUE THREAD

**Issue by ixora-0** [skeletonlabs/skeleton#2412]
### Current Behavior

This doesn't work, the dividers are set to white:

```svelte
<div class="divide-primary-400-500-token flex divide-x-2">
	<div>a</div>
	<div>b</div>
	<div>c</div>
</div>
```

### Expected Behavior

Expected dividers to be set to the correct colors like when specifying the class to each child elements:

```svelte
<div class=" flex divide-x-2">
	<div class="divide-primary-400-500-token">a</div>
	<div class="divide-primary-400-500-token">b</div>
	<div class="divide-primary-400-500-token">c</div>
</div>
```

### More Information

Works if not using design token
```svelte
<div class="flex divide-x-2 divide-primary-500">
	<div>a</div>
	<div>b</div>
	<div>c</div>
</div>
```

Versions
@sveltejs/kit@1.27.5
svelte@4.2.3
@skeletonlabs/skeleton@2.7.0
@skeletonlabs/tw-plugin@0.3.1

**Comment by endigo9740** [comment]
Hey @ixora-0. This is somewhat a documentation mistake. The only implementation of Dividers on our end is:
https://github.com/skeletonlabs/skeleton/blob/master/packages/plugin/src/styles/components/dividers.css

But yet the docs show this should cover all color pairings as well:
https://www.skeleton.dev/docs/tokens#divide

What I'd suggest doing in the meantime is manually setting the pairings for light/dark mode like so:

```html
<div class="divide-primary-400 dark:divide-primary-500">
```

We'll keep this ticket open and try to address this in two ways:

1. In the short term, we'll update the docs to better represent the utility class available
2. In v3 we'll review the implementation of divider styles

I'll update the labels accordingly.

**Comment by Rupsnigdha** [comment]
Hey can I update the doc and submit a pr for now?

**Comment by Sarenor** [comment]
Sure thing!

**Comment by Rupsnigdha** [comment]
no worries! what would you like me to edit? maybe put in a warning that it doesn't work and the workaround?
