### ISSUE TITLE
[Stepper] Step term applies to the `<Stepper>` component, not to the `<Step>` component

### ISSUE THREAD

**Issue by Sharknoon** [skeletonlabs/skeleton#2418]
### Link to the Page

https://www.skeleton.dev/components/steppers#step-term

### Describe the Issue (screenshots encouraged!)

In the docs, the example for the `stepTerm` shows a `<Step>` component. It should be a `Stepper` component instead:
![grafik](https://github.com/skeletonlabs/skeleton/assets/16149608/04b318d2-43e5-4763-a24c-b5eab37842db)
[Link](https://www.skeleton.dev/components/steppers#step-term)

For reference, here is is listed as a prop for the `<Stepper>` component:
![grafik](https://github.com/skeletonlabs/skeleton/assets/16149608/3a078bce-4922-48fd-bfb1-66aa0a1e95f3)
[Props](https://www.skeleton.dev/components/steppers?tab=properties#stepper)

I have also tested it locally and it only worked on the `<Stepper>` component.

Thank you so much

Kind regards from germany

Sharknoon

**Comment by Sarenor** [comment]
It can be applied to the Step and will then override the default Content & Header, but yes, the documentation is easy to missunderstand there. Thanks for reporting!

**Comment by endigo9740** [comment]
Thanks for the PR @Sarenor. We'll leave this thread open until that's merged.

@Sharknoon note that we do mention the step can be mentioned in the docs, you've just gotta scroll down a bit further. See below the table here:
![Screenshot 2024-01-16 at 10 27 06 AM](https://github.com/skeletonlabs/skeleton/assets/1509726/e76643de-3eb7-4d8a-8b09-18b4d2d05e02)

We use this pattern for props that are inherited via the Context API.

**Comment by Sharknoon** [comment]
@endigo9740 Thank you for explaining this. I didn't knew about this pattern and got confused, why the component suddenly changed. With the updated docs, it is crystal clear 👍 @Sarenor Thanks for your work. I really like to use Skeleton 😀
