### ISSUE TITLE
Svelte 5 Support

### ISSUE THREAD

**Issue by adminy** [skeletonlabs/skeleton#2434]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

As you know, svelte 5 is no longer compatible with svelte 4 and all the stores probably have to be re-written to the new synax.

### What type of pull request would this be?

Other

### Provide relevant links or additional information.

https://svelte-5-preview.vercel.app

https://github.com/sveltejs/svelte/releases/tag/svelte%405.0.0-next.37

**Comment by endigo9740** [comment]
hey @adminy, we're already WAY ahead of you here. See the following:

- https://github.com/skeletonlabs/skeleton/discussions/2400
- https://github.com/skeletonlabs/skeleton/discussions/2375

Lots of work going on for this right now, but we're aiming to put out regular updates though, like this one this week:

- https://github.com/skeletonlabs/skeleton/discussions/2424
