### ISSUE TITLE
Tailwind Plugin HRM bug for Color Pairings

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2438]
### Current Behavior

**UPDATE**: I've managed to replicate this on `dev` branch, so this is an existing issue. Not related to our changes on `next` or next feature branches.

Hot Module Reloading (HMR), or "live updates" if you prefer, breaks when we modify any of the plugin "token" styles that consume `settings.colorPairings`. This seems to be due to an error that's being thrown silently. This issue is non-recoverable. Once those changes happen, there's no coming back from it. Not even after a server restart.

### Expected Behavior

To not break :)

### Steps To Reproduce

Step to replicate...

Working State:
- Pull the `next` branch
- Browse to the Astro doc project in `/sites/next.skeleton.dev` and run the dev server `pnpm dev` (have it visible)
- Browse to the `/packages/skeleton` repo, which now contains the `/plugin` (tailwind plugin)
- Browse to `/plugin/tailwind/themes/wintry.ts` and replace the properties with any from another theme
- This will cause the doc site preview to update and show the changes after 1-2 seconds
- Revert this change

Broken State:
- Browse to `/plugin/tailwind/core.ts` then comment out any of the following lines:
```
...tokensBackgrounds(),
...tokensBorders(),
...tokensBorderRadius(),
...tokensFills(),
...tokensText(),
...tokensRings()
```
- Follow the steps above to update the `wintry` theme with new properties
- Note that no visible HRM changes occur on the site, no errors are thrown in the browser, no errors in the console

### More Information

For some reason this is VERY specific to the color pairings. Modifying any other `settings.ts` configurations has no bearing on this. It doesn't matter if you change the source pairings or any usage of this within the "token" files. The moment this is modified HMR just halts and fails silently.

**Comment by niktek** [comment]
One option might be to use the following in `.vscode/launch.json` :
```
// Astro
{
	"version": "0.2.0",
	"configurations": [
		{
			"command": "pnpm dev",
			"name": "Development server",
			"request": "launch",
			"type": "node-terminal",
			"autoAttachChildProcesses": true,
			"cwd": "${workspaceFolder}/sites/next.skeleton.dev/",
			"skipFiles": [
				"<node_internals>/**",
				"**/node_modules/pnpm/**",
				"**/node_modules/@babel*/**",
			]
		},
		{
			"command": "pnpm build",
			"name": "Build",
			"request": "launch",
			"type": "node-terminal"
		}
	]
}
```
Use F5 to launch with debugging, have to press F5 to continue through an error on startup about no postcss config (we still want to debug postcss so we don't want to add it to the skipFiles in launch.json ).  I also checked Caught and Uncaught Exceptions in the Breakpoints pane:
<img width="227" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/52020637/65d2d2df-f2dc-49ba-9f27-6a6429714104">
To help try and identify if anything is quietly capturing the errors and not passing them through to console.

When commenting out the `...tokensBackgrounds()` line, I am now shown an error of:
```
Exception has occurred: CssSyntaxError: /Users/nik/code/skeleton/packages/skeleton/src/plugin/styles/components/typography.css:44:3: The `bg-surface-300-600-token` class does not exist. If `bg-surface-300-600-token` is a custom class, make sure it is defined within a `@layer` directive.
  at Input.error (/Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/postcss@8.4.24/node_modules/postcss/lib/input.js:148:16)
    at AtRule.error (/Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/postcss@8.4.24/node_modules/postcss/lib/node.js:60:32)
    at processApply (/Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/tailwindcss@3.3.2/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:380:29)
    at /Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/tailwindcss@3.3.2/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:532:9
    at /Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/tailwindcss@3.3.2/node_modules/tailwindcss/lib/processTailwindFeatures.js:57:50
    at plugins (/Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/tailwindcss@3.3.2/node_modules/tailwindcss/lib/plugin.js:38:63)
    at LazyResult.runOnRoot (/Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/postcss@8.4.24/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/postcss@8.4.24/node_modules/postcss/lib/lazy-result.js:393:26)
    at transpileCssToJs (/Users/nik/code/skeleton/packages/skeleton/scripts/compile-css-to-js.ts:41:18)
    at exec (/Users/nik/code/skeleton/packages/skeleton/scripts/generate-jss.ts:15:32)
    ```

Which makes sense as the background tokens shouldn't be there, but hopefully this now surfaces the other errors you were encountering during dev.

**Comment by endigo9740** [comment]
This has been resolved due to Nik's findings and Adrians's updates to the pending PR:
https://github.com/skeletonlabs/skeleton/pull/2431/commits
