### ISSUE TITLE
Radio Group Transitions

### ISSUE THREAD

**Issue by thepersonthatexists** [skeletonlabs/skeleton#2439]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Transition support for radio groups would make them look much slicker and attractive - such as in this example answer: https://stackoverflow.com/questions/37299403/css3-transition-how-to-for-radio-choice-buttons#answers

### What type of pull request would this be?

Enhancement

**Comment by Mahmoud-zino** [comment]
In an effort to prepare for Skeleton v3, we're consolidate some related issues down to a single ticket. This will ensure that we can see the full context of requests when the time comes to refactor and update this feature going forward. If you wish to add additional feedback or suggestions, please so here:

https://github.com/skeletonlabs/skeleton/issues/2393
