### ISSUE TITLE
NEXT Animation Solution

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2449]
After testing and discussing this, we're going to opt for a framework-specific solutions for now. This will include:

* Svelte: the built in transition system
* React: introduce Framer Motion as a peer dependency

The associated PR will handle setup and delivery of this, including implementing new animations into the React Accordion component as reference.

When we introduce our next supported framework (likely Vue), we'll review the status of Anime.js v4 and consider migrating to this as a universal solution. But only if it meets our full requirements.

---

> NOTE: all information below will be persisted for future reference.

---

## Goal

We need to identify how we wish to handle animations across all frameworks. Currently Svelte has it's own animation system built in, which works great. But this may not be 1:1 with the solution selected for React. This leaves us with two options:

1. Universal: implement a single cross-framework compatible solution for all framework component packages.
2. Per Framework: implement a unique "best in class" solution per each framework package.

![Screenshot 2024-04-01 at 3 47 38 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/e6f40a3e-474f-4a3e-aeac-5a9e1f82f1d2)

## Maintainer Requests

The following requests are coming straight from the Skeleton team. These are highly likely be implemented.

Libraries to test:

- [x] Universal (cross-framework)
  - [x] [GSAP](https://gsap.com/) - [React hooks](https://github.com/greensock/react) | [Video](https://www.youtube.com/watch?v=l0aI8Ecumy8)
  - [x] [Anime.js](https://animejs.com/) - [v4 incoming](https://github.com/juliangarnier/anime/wiki/What's-new-in-Anime.js-V4)
- [x] React-only:
  - [x] [Framer Motion](https://www.framer.com/motion/)
  - ~~[React Spring](https://www.react-spring.dev/)~~
  - ~~[Lottie](https://lottiefiles.com/)~~
  - ~~[Ant Motion](https://motion.ant.design/)~~
- [x] Svelte-only:
  - [x] [Svelte Animate](https://svelte.dev/docs/svelte-animate)
- [x] Vue-only:
  - [x] [Transition](https://vuejs.org/guide/built-ins/transition.html) and [TransitionGroup](https://vuejs.org/guide/built-ins/transition-group.html)

## Resources

* [Joy of Code - GSAP FLIP Animations](https://www.youtube.com/watch?v=idD9DA9eR_A)

## Community Requests

The following requests have come from the community and are under consideration:

- [ ] https://github.com/skeletonlabs/skeleton/issues/1630

## Bugs and Issues

- [x] Note that we will NOT be carrying over the dynamic transition system from Skeleton v2

## Feedback

If you have additional updates or requests for this feature, please do so in the comments section below.

**Comment by techwizard31** [comment]
can i work on this?

**Comment by endigo9740** [comment]
Hey @techwizard31, this isn't a single issue so much as we need to audit and explore the variety of animation libraries and options for use in multiple components. If you're familiar with animation tech in React then the most useful thing you could do is help us build a list of tech to review.

Off the top of my head I am aware of options like [Framer Motion](https://www.framer.com/motion/animation/) and [React Spring](https://www.react-spring.dev/), but I'm sure there's more.

That said, I'll probably need to be heavily involved in this audit to determine which option will be fit for Skeleton. But we can start there. Thanks!

**Comment by endigo9740** [comment]
https://github.com/skeletonlabs/skeleton/assets/1509726/624e3691-8cc3-4afb-ab62-57dbd37bbcd3

Just sharing my initial tests. I've currently created the same "Collapsable" component in three frameworks.

## GSAP

Pros
- Feels relatively modern
- Turnkey React hook built in for proper setup/teardown
- Fairly simple to get started
- Framework agnostic

Cons:
- Docs a very confusing to navigate
- The modular structure is very confusing, the `registerPlugin()` feature is annoying
- Animates aren't working as expected; trigger on load and don't run the first time

## Framer Motion

Pros
- By far the simplest to dive into and use
- The documentation is top notch
- Everything worked right out of the box
- Only option to provide an `<AnimatePresence>` option for animating show/hide
- Feels extremely flexible with a single module

Cons
- React only
- No search in the documentation
- Requires special `<motion.div>` components (supports Tailwind just fine)
- The Motion component props are a bit verbose

## Anime.js

Pros
- Feels the most date; import is not ESM
- Documentation is a bit scattered, no search
- v4 seems to be on the horizon

Cons
- v4 is limited to sponsors-only atm
- Only handle numeric animation, so `height: 0 -> auto` is not possible
- Animation is probably the worse due to height pop-in

**Comment by endigo9740** [comment]
Our first React animations are now live on the doc site. Check the updates Accordion component docs!
https://next.skeleton.dev/docs/components/accordion/react
