### ISSUE TITLE
Stepper - unable to cancel events and event dispatch order bug

### ISSUE THREAD

**Issue by Adriani6** [skeletonlabs/skeleton#2457]
### Current Behavior

1. The CustomEvent which is generated by `dispatch` is not cancelable using `event.preventDefault()`

2. While investigating the above, I've noticed `next`/`back` and `step` events are fired right after another. Documentation either needs to be updated or code changed as the behavior is not what happens.

### Expected Behavior

1. The CustomEvent which is generated by `dispatch` I would expect to be cancelable using `event.preventDefault()` - doing so has no effect - seeing the source for the Stepper, line 112 & 119 should be changed to check if the event has been canceled by passing "cancelable: true" as options to the dispatch method, before the `$state.current` is updated.

112:		`const shouldContinue = dispatch('next', { step: stepIndex, state: $state }, { cancelable: true });`
119:		`const shouldContinue = dispatch('back', { step: stepIndex, state: $state }, { cancelable: true });`

2. Based on the documentation, I would expect the `$state.current` to be updated between the two events.

### Steps To Reproduce

Having this step inside my Stepper:

```
<Step on:onBack={canGoBack}>
	<svelte:fragment slot="header">Complete</svelte:fragment>
	Final step
</Step>
```

and this function:

```
function canGoBack(e){
	if (e.detail.step + 1 == e.detail.state.total){
		e.preventDefault();
	}
}
```

The step event is not prevented and state on the stepper is updated.

### More Information

Happy to make the necessary changes if/when this is ok'd.

**Comment by Sarenor** [comment]
That's because the events are not intended to be cancelable. They're just there to inform you of what has happened as far as I know.

Something we can take into account for v3 though, if you would care to add it there: https://github.com/skeletonlabs/skeleton/issues/1780

Currently, the way to prevent a step from being continued is to use the ``locked`` prop.

**Comment by endigo9740** [comment]
Consolidated under: https://github.com/skeletonlabs/skeleton/issues/1780

We'll review this as part of our Skeleton v3 implementation of this feature.
