### ISSUE TITLE
ReferenceError: Request is not defined at getRequest (file:///../node_modules/@sveltejs/kit/src/exports/node/index.js:107:2) at file:///../node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:497:27

### ISSUE THREAD

**Issue by squatchydev9000** [skeletonlabs/skeleton#2461]
### Current Behavior

ReferenceError: Request is not defined at getRequest (file:///../node_modules/@sveltejs/kit/src/exports/node/index.js:107:2) at file:///../node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:497:27

After running npm run dev... this error persists in the localhost browser... site will not load.

ReferenceError: Request is not defined at getRequest (file:///../node_modules/@sveltejs/kit/src/exports/node/index.js:107:2) at file:///../node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:497:27

I've lost days...

Just wanted to move from svelte to sveltkit for the routes...

Tried:

Sveltekit cli install - tailwind, typescript, prettier, eslint
SkeltonUi cli install - same as above
Repeated attempts to change node version via NVM
Manually altering the different config files
Endless github, youtube, stackoverflow nonsense...
The Vite troubleshooting docs
The Sveltekit docs
A lot of back and forth with Chat-GPT and PerplexityAI...

### Expected Behavior

Was expecting the localhost browser window to be filled with skeletonUi magic....

### Steps To Reproduce

CLI install from SkeltonUI website... choose eslint, prettier, etc.. all of the options.

Npm run dev... annnnnnnd. boom.  error.

MacOS 14.2.1 (23C71)
ARC Browser
Node versions tried: 18, 19, 20

Tried removing config files and re-building them... etc.

**Comment by endigo9740** [comment]
@squatchydev9000 unfortunately nothing about the errors seems to be coming from Skeleton. Our Issues board and bug tickets should be strictly limited to issues within Skeleton itself.

Moving from Svelte -> SvelteKit probably won't be a trivial process. I'd be cautious of thinking you could just easily copy things over and expect it to work. You may need something closer to a proper rebuild of your project here.

While we don't support Svelte/Kit issues, they do have a great community on GitHub and Discord. Likewise we have a `#svete-sveltekit` for community support. I'd recommend bring this issue up there. You should be able to link to this issue, even if it's closed.

Good luck!
