### ISSUE TITLE
Add `btn-disabled`

### ISSUE THREAD

**Issue by PerchunPak** [skeletonlabs/skeleton#2474]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I want to create navigation buttons (next and previous) on `a` tags (to preload pages with [`data-sveltekit-preload-data`](https://kit.svelte.dev/docs/link-options#data-sveltekit-preload-data)), so if a user is on the first item, I want to disable "previous" button.

Currently, styles for disabled button work only with `<button disabled=... />`

https://github.com/skeletonlabs/skeleton/blob/3ee82280b22f42f961943ed4feff68fdc4354943/packages/plugin/src/styles/components/buttons.css#L21-L23

Fix should be in one line + docs
```diff
-.btn-group > *:disabled {
+.btn-group > *:disabled,
+.btn-disabled {
```

### What type of pull request would this be?

Enhancement

**Comment by PerchunPak** [comment]
If there are no problems (e.g. if it was a design decision to not do `btn-disabled`), I could make a PR.

**Comment by endigo9740** [comment]
@PerchunPak there's no such thing as a `disabled` state on an anchor tag. This is why we limited this to buttons. You can visually make an anchor look like it's disabled by fading the opacity and setting `pointer-events-none`, but this doesn't disable the things like tab selection + enter.

If you need to have a disabled button UI, consider using an actual button and programmatically routing users using SvelteKit's `goto()` feature.
