### ISSUE TITLE
RecursiveTreeView on:toggle unexpected events

### ISSUE THREAD

**Issue by nonvenomous** [skeletonlabs/skeleton#2491]
### Current Behavior

- parent 1 (toggled 1st)
  - child 1 (toggled 2nd
- parent 2 (toggled 3rd)
  - ...
  
Toggling `parent 2` after toggling `parent 1` and `child 1` causes one unexpected event to dispatch which implies that `child 1` was toggled again after `parent 2`.

### Expected Behavior

Clicking on one parent shouldn't cause a `on:toggle` on a different element

### Steps To Reproduce

In my repo

1. Click on first parent
2. Click on first child
3. Click on second parent
4. **unexpected event for first child**

![image](https://github.com/skeletonlabs/skeleton/assets/37549874/b152d0ed-0094-4224-b1a9-6e4de500abcc)

### Link to Reproduction / Stackblitz

https://stackblitz.com/~/github.com/nonvenomous/skeleton-tree-view-duplicate-events

**Comment by Mahmoud-zino** [comment]
@nonvenomous This should be solved with the new version of the tree-view in Skeleton-Next.
However, I will mention this bug in the central issue there to make sure we test for this case when we are done with the implementation :+1: 
https://github.com/skeletonlabs/skeleton/issues/2358
