### ISSUE TITLE
Allow individual styling of items

### ISSUE THREAD

**Issue by precision-cancer-research** [skeletonlabs/skeleton#2493]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I would like to be able to set the styling of each individual item inside of the autocomplete dropdown. Currently, any styles applied affect all of the items. Converting the `regionItem` to take a function may be a possible solution: 

```html
<Autocomplete
      type="search"
      placeholder="Search..."
      {options}
      on:selection={handleSelect}
      bind:input
      regionItem={(item) => item.value > 0 ? 'bg-primary-500' : 'bg-error-500'}
/>
```

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Thanks for the feature request. Definitely something we'll look at as part of the v3 update! I've included on this list here, so I'll go ahead and close this ticket:

- https://github.com/skeletonlabs/skeleton/issues/2366
