### ISSUE TITLE
favicon.png

### ISSUE THREAD

**Issue by neonira** [skeletonlabs/skeleton#2511]
### Current Behavior

favicon.png is used for display of tab icon and for display on UI. 

Although using the same name for two different purposes in two different sub directories is already quite tricky, I face a strange issue that is tied to interoperability I guess. 

Under Ubuntu 22.04 LTS, here is what I get from file command line **file favicon.png**

favicon.png: MS Windows icon resource - 3 icons, 48x48, 32 bits/pixel, 32x32, 32 bits/pixel

When trying to open this file under some other tools, like Gimp, answer is corrupted file. 
 

### Expected Behavior

Main issue I faced, is replacing favicon.png with an equivalent file. 

When I build a pure png (1 icon only) file, it brings a 500 internal error related to animation.

I would suggest either 

a.  split the file in order to get individual image files, to ease customization and change for everyone
b. or provide a way to build the format file from  a set of images to comply with expected hidden requirements . I guess this is trickier and less reliable indeed. 

### Steps To Reproduce

use same command line as above

**Comment by Sarenor** [comment]
I have to admit that I am confused by this issue. Skeleton is a UI Library. Yes we have our own ``favicon`` for the Skeleton docs ( [Skully](https://github.com/skeletonlabs/skeleton/blob/dev/sites/skeleton.dev/static/favicon.png) ), but apart from that, we have no impact on your favicon or how you handle it.

Favicons are a web/browser feature: https://developer.mozilla.org/en-US/docs/Glossary/Favicon

**Comment by endigo9740** [comment]
The only thing I can add to this is the location in which the favicon lives in a SvelteKit project:
https://kit.svelte.dev/docs/configuration#files

And this is configured in the `/src/index.html` (in the head of the page)
