### ISSUE TITLE
Modals prerequisites should also import Modal

### ISSUE THREAD

**Issue by MarcoPeretti** [skeletonlabs/skeleton#2512]
### Link to the Page

https://www.skeleton.dev/utilities/modals

### Describe the Issue (screenshots encouraged!)

The documentation says we must import initializeStores as follows:

import { initializeStores } from '@skeletonlabs/skeleton';

but I think it should also import Modal, right?

import { initializeStores, Modal } from '@skeletonlabs/skeleton';

**Comment by salisshuaibu11** [comment]
@endigo9740 assign this to me

**Comment by salisshuaibu11** [comment]
@endigo9740 It seems the issue extends beyond just the Modal; we're encountering the same problem with the Toast, and Drawer utilities as well. Should we address this in a separate pull request?

**Comment by Sarenor** [comment]
It's a small enough docs issue that it's probably fine to do all in 1 PR
