### ISSUE TITLE
Progress Bars: discrepancy in usage code

### ISSUE THREAD

**Issue by gsass1** [skeletonlabs/skeleton#2516]
### Link to the Page

https://www.skeleton.dev/components/progress-bars

### Describe the Issue (screenshots encouraged!)

The example code for ProgressBar refers to a "label" prop when in fact no such prop exists.

<img width="820" alt="Screenshot 2024-02-27 at 07 45 16" src="https://github.com/skeletonlabs/skeleton/assets/4589491/9565fcde-0948-4ea5-8c55-e19b468d7b92">
<img width="848" alt="Screenshot 2024-02-27 at 07 45 29" src="https://github.com/skeletonlabs/skeleton/assets/4589491/451112bc-1ae0-4bf7-80d1-c28f3ece1c16">

**Comment by Mahmoud-zino** [comment]
Closed by  #2545
