### ISSUE TITLE
Installing with bun hits exception

### ISSUE THREAD

**Issue by khionu** [skeletonlabs/skeleton#2534]
### Current Behavior

Running `bun create skeleton-app@latest path` exits with an exception of `A retry listener has been attached already.` It seems that the installation may be completing successfully otherwise? But I'm relatively new to this so I can't be 100% sure.

### Expected Behavior

Parity with `npm create`.

### Steps To Reproduce

1. Install Bun
2. Run `bun create skeleton-app@latest test`
3. Follow wizard.

I've not tried reproducing with many combinations of features, but I can reproduce with
- Bare Bones
- Modern, Gold Nouveau
- Tailwind Forms, Tailwind Typography, CodeBlock
- using Typescript
- ESLint, Prettier, Playwright, Vitest, and Svelte Inspector

**Comment by niktek** [comment]
Hi @khionu,

Would you be able to supply the bun version and maybe what OS you are on ?  Here is my results on macOS Sonoma 14.4 with bun v1.0.29:
<img width="1405" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/52020637/4c620ebe-c1d3-45d3-ab91-4d9392cc15f8">

**Comment by khionu** [comment]
I'm on NixOS and I was using a flake. I'm unsure what the version may have been before because I had to re-add bun, but it's currently the same version, and.... it works now. It's possible my lockfile had 1.0.28.

Thanks for the quick response at least, sorry to have wasted your time.
