### ISSUE TITLE
progressbar.css in build

### ISSUE THREAD

**Issue by multipliedtwice** [skeletonlabs/skeleton#2547]
### Current Behavior

https://www.skeleton.dev/ loads progressbar.css
My app that uses skeleton does same

### Expected Behavior

Let a user to bundle it up manually into main CSS file

### Steps To Reproduce

Open https://www.skeleton.dev/
Open network tab of chrome inspector, find progressbar.css

**Comment by Sarenor** [comment]
Our currently recommended solution for that is https://www.skeleton.dev/docs/purgecss :)
