### ISSUE TITLE
card-header and card-footer need radius overrides when bg-color-X set

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#2562]
### Current Behavior

When setting a bg color on a `card-header` or `card-footer` it will overpaint the containing `card` and its border-radius setting.  I think if the user is opting into a card then it should carry through the expected border-radius to the child elements. The following uses tokens to re-apply the border radius on the card-header, but removing them will make it appear like card-footer.

```
<div class="p-5">
	<div class="card my-10 ">
		<header class="card-header bg-primary-500 rounded-tl-container-token rounded-tr-container-token">Actions</header>
		<section class="p-4">
			<button class="btn variant-filled">Save</button>
		</section>
		<footer class="card-footer bg-primary-500">(footer)</footer>
	</div>
</div>
```

It also raises a question of whether we should also extend the rounded tokens to match the options TW provides as we are missing tokens for (would we still keep container in there?):
```
rounded-s-container-token
rounded-e-container-token
rounded-t-container-token
rounded-r-container-token
rounded-b-container-token
rounded-l-container-token
rounded-ss-container-token
rounded-se-container-token
rounded-ee-container-token
rounded-es-container-token
```

**Comment by endigo9740** [comment]
@niktek I think this would be easier to understand with a screenshot.

That said, rounded styles now extend Tailwind's default border radius styles in v3. So this issue would be limited to v2.

**Comment by niktek** [comment]
<img width="613" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/52020637/40f810fb-7b4b-4ff6-9f4b-6ca88e92a768">

```
<div class="p-5">
	<div class="card">
		<header class="card-header">Actions</header>
		<section class="p-4">
			<button class="btn variant-filled">Save</button>
		</section>
		<footer class="card-footer">(footer)</footer>
	</div>
</div>

<div class="p-5">
	<div class="card">
		<header class="card-header bg-primary-500">Actions</header>
		<section class="p-4">
			<button class="btn variant-filled">Save</button>
		</section>
		<footer class="card-footer bg-primary-500">(footer)</footer>
	</div>
</div>

<div class="p-5">
	<div class="card">
		<header class="card-header bg-primary-500 rounded-tl-container-token rounded-tr-container-token">Actions</header>
		<section class="p-4">
			<button class="btn variant-filled">Save</button>
		</section>
		<footer class="card-footer bg-primary-500 rounded-bl-container-token rounded-br-container-token">(footer)</footer>
	</div>
</div>
```

It's not a show stopper at all, but it also doesn't feel right either.

**Comment by endigo9740** [comment]
@niktek sorry for the delay on this one. Now that I've had a chance to read through this with a clear mind I see what you mean. The goal with the v2 implementation was to keep a unified spacing around the edge of the screen, as well as between sections.

For example, all yellow lines shown should have uniform spacing:

![Screenshot 2024-04-05 at 4 08 55 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/1642745f-169d-4486-9bd8-2d269c871d7c)

Unfortunately, if you double up the spacing by adding padding within the children, this will lead to a poor result where space appears doubled (or tripled) between the children. This can result in styles that feel very uneven:

![Screenshot 2024-04-05 at 4 13 10 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/8b400443-e2eb-4069-bc15-518a62052a38)

Here's how I'd tackle a couple different scenarios for this. This should work in both v2 and v3:

```html
<!-- Gap -->
<div class="card p-4 space-y-4">
	<header class="bg-primary-500">Header</header>
	<section>Content</section>
	<footer class="bg-primary-500">Footer</footer>
</div>

<!-- Flush -->
<div class="card">
	<header class="p-4 bg-primary-500">Header</header>
	<section class="p-4">Content</section>
	<footer class="p-4 bg-primary-500">Footer</footer>
</div>
```

Given the header/footer concepts won't be carrying forward to Skeleton v3, I'd recommend following the pattern above for now. I don't think there's a sane way we can handle every use case folks might in v2, so we'll call this a wash.
