### ISSUE TITLE
W3C validator complains

### ISSUE THREAD

**Issue by multipliedtwice** [skeletonlabs/skeleton#2569]
### Current Behavior

Multiple components throwing multiple errors in https://validator.w3.org/

**Comment by endigo9740** [comment]
This is probably too broad to be useful I'm afraid. I'm not sure we'll be able to promise major changes on this front before Skelton v3 is ready. v3 features a vast number of changes to adhere to ARIA and WGAC guidelines. I'll keep this validator in mind for future testing, but unfortunately I don't think this is actionable for us...yet!
