### ISSUE TITLE
[Maybe DUP] Modal stack, without closing prev modal (modal on modal on modal...)

### ISSUE THREAD

**Issue by ktarmyshov** [skeletonlabs/skeleton#2570]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I think I have seen the similar discussions in the issues already, and maybe it's being worked on currently. But I want to add another use case, where it is required.

I have a form modal, so when user is pressing the save button, I use native sveltekit actions to run the communication with the server. After the comm is complete and it's an error - I want to show the modal error and then return back to the form.

Current skeleton modals implementation: I insert the error as first into the queue (not trigger, but update). Error is displayed, but form is destroyed and starts from anew unless I cache the input data and re-init on show-up again. But even in that case it is not exactly the same state.

Would be very helpful to have another modal opened without closing the prev one.

Thank you guys!
K

### What type of pull request would this be?

New Feature

**Comment by endigo9740** [comment]
@ktarmyshov you're correct, this is a duplicate. We're going to be evaluating support for this as part of Skeleton v3. You can track modal-related requests here:

https://github.com/skeletonlabs/skeleton/issues/2357

Search the page for "stack" and you'll see an other issue is present describing this request.

I'll go ahead and close this out a a dupe. Thanks!
