### ISSUE TITLE
A small typo in the props of the App Rail - background and border

### ISSUE THREAD

**Issue by Leonhart130** [skeletonlabs/skeleton#2576]
![issue](https://github.com/skeletonlabs/skeleton/assets/53121384/847d4aaf-534e-4279-b29d-2c683678abf5)
### Link to the Page

https://www.skeleton.dev/components/app-rail?tab=properties

### Describe the Issue (screenshots encouraged!)

the description of the props is the same for background and border

**Comment by endigo9740** [comment]
Done, thanks @salisshuaibu11 and good to see you again!
