### ISSUE TITLE
Be able to get a reference to <input> inside InputChip, and a way to forward actions to button

### ISSUE THREAD

**Issue by tobiasBora** [skeletonlabs/skeleton#2577]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

My goal was to provide something like the really cool [Select](https://ant.design/components/select) feature of AntDesign

![Peek 27-03-2024 03-42](https://github.com/skeletonlabs/skeleton/assets/2164118/8e45ca65-1d27-404e-911c-2a33f3e75a2b)

Unfortunately, it seems not so trivial to do with skeleton, notably to be sure that the popup does not close after selecting an item:

![Peek 27-03-2024 02-56](https://github.com/skeletonlabs/skeleton/assets/2164118/a92596aa-cb00-473b-9d87-fa01966aa8cc)

Part of the issues are that:
- [ ] it is not possible to write `use:popup` (and actions in general) on non-DOM elements. One solution is to wrap InputChip within a Dom… but it is not really practical and not equivalent, as a Div has no notion of focus.
- [ ] it is also not possible, as far as I see, to get a reference to the inner `<input>`, for instance to force the focus on that field after clicking in the popup.
- [ ] the popup is located in a weird position, either too high or too low, not sure why.

Code:
```
<script lang="ts">
  import { Avatar, InputChip, Autocomplete, popup } from '@skeletonlabs/skeleton';
  import type { AutocompleteOption, PopupSettings } from '@skeletonlabs/skeleton';
  let inputChip = '';
  let inputChipRef = null;
  let inputChipList: string[] = ['vanilla', 'chocolate'];
  const flavorOptions: AutocompleteOption<string>[] = [
    { label: 'Vanilla', value: 'vanilla', keywords: 'plain, basic', meta: { healthy: false } },
    { label: 'Chocolate', value: 'chocolate', keywords: 'dark, white', meta: { healthy: false } },
    { label: 'Strawberry', value: 'strawberry', keywords: 'fruit', meta: { healthy: true } },
    { label: 'Neapolitan', value: 'neapolitan', keywords: 'mix, strawberry, chocolate, vanilla', meta: { healthy: false } },
    { label: 'Pineapple', value: 'pineapple', keywords: 'fruit', meta: { healthy: true } },
    { label: 'Peach', value: 'peach', keywords: 'fruit', meta: { healthy: true } }
  ];
  

  function onFlavorSelection(event: CustomEvent<AutocompleteOption<string>>): void {
    //inputChip = event.detail.label;
    inputChipList = [...inputChipList, event.detail.value];
    inputChipRef.focus();
  }


  let popupSettings: PopupSettings = {
    event: 'focus-click',
    target: 'popupAutocomplete',
    placement: 'bottom',
  };


  const popupClick: PopupSettings = {
    event: 'click',
    target: 'popupClick',
    placement: 'top'
  };
  
  
</script>

<div class="container mx-auto p-8 space-y-8">
  <h1 class="h1">Hello Skeleton</h1>
  <Avatar src="https://i.pravatar.cc/" />
  <p>LLLorem ipsum dolor sit amet consectetur adipisicing elit.</p>
  <section>
    <a class="btn variant-filled-primary" href="https://kit.svelte.dev/">SvelteKit</a>
    <a class="btn variant-filled-secondary" href="https://tailwindcss.com/">Tailwind</a>
    <a class="btn variant-filled-tertiary" href="https://github.com/">GitHub</a>
  </section>
  <div use:popup={popupSettings}>
    <InputChip bind:input={inputChip} bind:this={inputChipRef} bind:value={inputChipList} name="chips" />
  </div>
  <div data-popup="popupAutocomplete">
    <div class="card w-full max-w-sm max-h-48 p-4 overflow-y-auto" tabindex="-1">
      <Autocomplete
        on:selection={onFlavorSelection}
        bind:input={inputChip}
        options={flavorOptions}
        denylist={inputChipList}
      />
    </div>
  </div>

  <button class="btn variant-filled" use:popup={popupClick}>Click</button>
  
<div class="card p-4 variant-filled-primary" data-popup="popupClick">
  <p>Click Content</p>
  <div class="arrow variant-filled-primary" />
</div>

</div>

``` 

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

Might be related to https://github.com/skeletonlabs/skeleton/issues/1916 and https://github.com/skeletonlabs/skeleton/issues/2366

**Comment by endigo9740** [comment]
@tobiasBora as mentioned on Discord, we're currently consolidating more sweeping updates or requests under issues for Skeleton v3. I've gone ahead and linked to your issue here, so we can review and consider your request in detail as part of that process:

- https://github.com/skeletonlabs/skeleton/issues/2577

Likewise if there's any other features you would like to make requests for, please try to keep them in the relevant threads here:

- https://github.com/skeletonlabs/skeleton/milestone/5

Thanks for your suggestions though!

**Comment by tobiasBora** [comment]
Ok, thanks!
