### ISSUE TITLE
Provide less cartoonish styles

### ISSUE THREAD

**Issue by tobiasBora** [skeletonlabs/skeleton#2578]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Skeleton's default styles are cool, but most of them have a very cartoonish style, and might not fit all applications.

It would be really cool to provide a more epurated style that users can easily select without writing their own style, following for instance [AntDesign](https://ant.design/) or [TailwindUI](https://tailwindui.com/):

![image](https://github.com/skeletonlabs/skeleton/assets/2164118/82e66a09-c729-4454-92b6-a47e6017e27a)

### What type of pull request would this be?

New Feature

**Comment by endigo9740** [comment]
Hey @tobiasBora, if you haven't already I'd highly suggest checking out our progress on Skeleton v3. It's a pretty hefty overhaul we've been working on the last few months. This may address some of your design concerns.
https://github.com/skeletonlabs/skeleton/discussions/2375

I posted a new update today here, which talks through some recent updates:
https://github.com/skeletonlabs/skeleton/discussions/2574

We very much want the look and feel of Skeleton to be in your control. As such we've been a massive update to the theme generator and theme format to enable this:
https://github.com/skeletonlabs/skeleton/discussions/2544

Likewise you can preview the current progress on a few of the new built-in themes on the upcoming documentation site:
https://next.skeleton.dev/

We understand design is subjective, but we hope v3 goes a long ways towards enable new and more unique styling options.

**Comment by tobiasBora** [comment]
Awesome, looking forward to see great looking modern styles.
