### ISSUE TITLE
Embedding the changelog of skeleton packages into the doc website.

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#2579]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

All github content is fetchable, see: https://github.com/orgs/community/discussions/44370 on how to do that.
This means the docs can fetch the generated CHANGELOG.md and render it out on a page.

This has the benefit of users being able to stay on the docs site when wanting to view changes without needing to go 5 layers of files deep on github.

### What type of pull request would this be?

Docs

**Comment by endigo9740** [comment]
Note: This may replace the current Blog section.

**Comment by endigo9740** [comment]
Folded into:
https://github.com/skeletonlabs/skeleton/issues/2353
