### ISSUE TITLE
Update docs tabs with Skeleton-Next React Tabs

### ISSUE THREAD

**Issue by Mahmoud-zino** [skeletonlabs/skeleton#2591]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

We want to switch the docs tabs with the new implementation of Skeleton-Next React tabs.

### What type of pull request would this be?

Docs

**Comment by endigo9740** [comment]
Astro has some quirks when it comes to how children slots work within the Astro environment (or MDX). We'll attempt to use the Tabs component directly, but if it does not work, we'll need to create a facsimile via Astro. Basically an doc-only React component that imitates the default Tab design.
