### ISSUE TITLE
Tailwind PurgeCSS Config - Highlight.js - Incorrectly Typed (Docs/Installation)

### ISSUE THREAD

**Issue by je-movers-market** [skeletonlabs/skeleton#2610]
### Current Behavior

The [Skeleton docs about highlight.js](https://www.skeleton.dev/utilities/codeblocks), and the skeleton-app CLI project, include the purgeCSS config like so for highlight.js:
```
purgeCss({
	safelist: {
		// any selectors that begin with "hljs-" will not be purged
		greedy: [/^hljs-/]
	}
}),
```
However, this isn't correctly typed and doesn't work, as the safelist can only be applied if the config is explicitly marked as legacy (which is very much recommended against by vite-plugin-tailwind-purgecss) like so:
```
purgeCss({
	legacy: true,
	safelist: {
		// any selectors that begin with "hljs-" will not be purged
		greedy: [/^hljs-/]
	}
}),
```
or if the safelist is simply removed:
```
purgeCss()
```
So I suppose the latter would be more sensible, but even if not, the legacy flag at the very least needs to be included.

### Expected Behavior

TS2345 error

### Steps To Reproduce

Simply look at the TS errors on the default project with vite-plugin-tailwind-purgecss updated to the latest version.

**Comment by endigo9740** [comment]
@je-movers-market there's been major update to the PurgeCSS plugin this week, and we [have a pending PR](https://github.com/skeletonlabs/skeleton/pull/2604) to update the instruction on our documentation.

I'm going to alert @AdrianGonz97 to this callout on the Code Block section as I'm not sure he was aware of of this snippet. I'll also defer to him for providing the proper instructions here as I'm not fully up to date on the recent changes.

**Comment by AdrianGonz97** [comment]
The config is no longer necessary and `purgeCss()` should be sufficient. This change for CSA to remove it is already noted in [my PR](https://github.com/skeletonlabs/skeleton/pull/2604).

**Comment by AdrianGonz97** [comment]
Completed as of #2604
