### ISSUE TITLE
Issue with breadcrums with 3 entries or more

### ISSUE THREAD

**Issue by acerasoni** [skeletonlabs/skeleton#2613]
### Current Behavior

When I create a breadcrum with three or more entries, it gets cut to two entries when viewed on mobile

Example code, taken directly from the documentation

<ol class="breadcrumb">
	<li class="crumb"><a class="anchor" href="/elements/breadcrumbs">Skeleton</a></li>
	<li class="crumb-separator" aria-hidden>&rsaquo;</li>
	<li class="crumb"><a class="anchor" href="/elements/breadcrumbs">Elements</a></li>
	<li class="crumb-separator" aria-hidden>&rsaquo;</li>
	<li>Breadcrumbs</li>
</ol>

Desktop:
![image](https://github.com/skeletonlabs/skeleton/assets/32521086/69f4385e-b9d3-4a81-ade8-83ec3aa5770d)

Mobile:
![image](https://github.com/skeletonlabs/skeleton/assets/32521086/9686cb14-39be-49f2-83de-c56527d20daf)

Threshold of bug: 768 pixels and below

### Expected Behavior

All breadcrums are expected to be rendered rather than only the last 2

### Steps To Reproduce

1. Any Svelte page with breadcrums with 3 or more elements
2. Mobile view (less than 768 pixels) 

### More Information

Skeleton v2.3.0

**Comment by Sarenor** [comment]
I'm afraid to say that we call that [a feature, not a bug](https://www.skeleton.dev/elements/breadcrumbs#nonresponsive)
