### ISSUE TITLE
v2 Stackblitz dependency updates

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2630]
I've noted our dependencies are getting a bit dated. Let's update update these. This will likely represent the last big update before v3.

https://github.com/skeletonlabs/repl

**Comment by thetechguyseth** [comment]
@endigo9740 I went ahead and published a PR here https://github.com/skeletonlabs/repl/pull/4

(it's my first public PR so let me know if I missed something / didn't understand the issue)
