### ISSUE TITLE
Add style prop to TreeViewItem to allow control of content's width

### ISSUE THREAD

**Issue by HenryRocha** [skeletonlabs/skeleton#2631]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

When using the component `TreeViewItem` the content does not fill the full width. To allow better control of this component's contents the users should be able to pass a style prop to customize the container's width.

Here's a simple example code:
```js
<script lang="ts">
    import { TreeView, TreeViewItem } from '@skeletonlabs/skeleton';
</script>

<div class="flex flex-row h-screen">
    <div class="w-1/2 p-4 flex flex-col items-center bg-white"></div>
    <div class="w-1/2 p-4">
        <div class="flex flex-row">
            <h1 class="w-full text-center text-5xl">Content</h1>
        </div>

        <TreeView open={true}>
            <TreeViewItem>
                <h1 class="text-3xl">Basic Information</h1>

                <svelte:fragment slot="children">
                    <TreeViewItem>
                        <div class="flex items-center space-x-5">
                            <h1 class="w-1/6 text-xl">Email:</h1>

                            <label class="w-5/6 label">
                                <input class="input" type="text" placeholder="john@doe.com" />
                            </label>
                        </div>
                    </TreeViewItem>
                </svelte:fragment>
            </TreeViewItem>
        </TreeView>
    </div>
</div>
```

Here's a screenshot of the current result:
![image](https://github.com/skeletonlabs/skeleton/assets/21242383/8ea1c3cc-e2db-4435-8c97-4d2e795c4652)

To make it work we currently need to make use of the `regionSummary` prop:
```html
<TreeViewItem regionSummary="[&>.tree-item-content]:grow">
```

### What type of pull request would this be?

New Feature

**Comment by salisshuaibu11** [comment]
@endigo9740 i would like to work on this

**Comment by endigo9740** [comment]
Thank you Salisu, but I need to talk this over with @Mahmoud-zino before we act on it. We may hold off on this for v3.

**Comment by Mahmoud-zino** [comment]
This for sure should be added in v3 (I will note it there), but I think we can easily add it to v2 if we have the capacity :+1:

**Comment by endigo9740** [comment]
Since it's been folded into the v3 issue, I'm going to close this as a duplicate.
