### ISSUE TITLE
LightSwitch breaks in multiple tabs

### ISSUE THREAD

**Issue by m93a** [skeletonlabs/skeleton#2635]
### Current Behavior

Setting the value of `modeCurrent` store does not update the root element's `dark` class, which breaks UX in a multi-tabbed setting.

### Steps To Reproduce
1. Open [`https://www.skeleton.dev/docs/dark-mode`](https://www.skeleton.dev/docs/dark-mode) twice, in two browser tabs
2. Click on the LightSwitch in one of the tabs
3. See that in the other tab, the switch has flipped, but the page's style did not change

... or alternatively:
1. Import `modeCurrent` from Skeleton in your code
2. Set its value via `modeCurrent.set(...)`
3. See that the page's style has not updated

### Expected Behavior

The root element's `dark` class should update whenever the `modeCurrent` store updates.

### Walkaround
```ts
import { modeCurrent } from '@skeletonlabs/skeleton';

modeCurrent.subscribe((lightMode) => {
    document.documentElement.classList.toggle('dark', !lightMode);
});
```

**Comment by endigo9740** [comment]
@m93a I'm not sure this is a use case we ever intended to solve with the LightSwitch component. As such, this would fall more into the category of a feature request than a bug.

While I can understand the frustration with the page display not updating when the toggle is flipped in a non-active tab, the page will correct itself the next time the other tab page are refreshed.

This is one of the contributing reasons the Lightswitch component will not be carrying forward to Skeleton v3. Including:

1. You need very different solutions for mode state handling in Svelte/React and respective meta-framework (including Astro).
2. We will now be natively supporting BOTH [dark mode strategies](https://tailwindcss.com/docs/dark-mode) Tailwind provides without the need for additional utility classes
3. Honestly the component design is too opinionated and feature set too limited. This edge case you've highlighted is an excellent case in point.

That said, I'd rather recommend you follow your work around solution for Skeleton v2 for now. But, consider following the advise in either the Tailwind [dark mode docs](https://tailwindcss.com/docs/dark-mode#supporting-system-preference-and-manual-selection), or rolling your own solution going forward. This will better align with the upcoming changes in Skeleton v3.

**Comment by m93a** [comment]
Can you at least close it as "not planned" rather than "completed", since you didn't complete anything.

**Comment by Sarenor** [comment]
If that helps you along, sure. If there's anything we can do to alleviate confusion, we're willing to keep discussing/communicating, too.
Either in a Discussion, Discord or whatever else works for you.
