### ISSUE TITLE
Svelte v5 RC: TreeView component is non-function

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2639]
### Current Behavior

This component works as expected in Svelte v4. However, while testing the Svelte v5 RC, there are a number of errors present when using this component. See the screenshot below:

![Screenshot 2024-04-30 at 1 17 26 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/981555e7-ccbb-481f-87ba-f6f08bc77aab)

a11y warning:

```
2:16 The `accessors` option has been deprecated. It will have no effect in runes mode
```

### Expected Behavior

While we won't be utilizing Svelte v5 features in Skeleton until our v3 release, we do expect users to migrate to Svelte v5 prior to migrating to Skeleton v3. This means there will be a period of time while they are running Skeleton v2 + Svelte v5. As such, we should try to resolve these errors as they are breaking issues.

### Steps To Reproduce

You can temporarily switch to Svelte v5 RC to test and develop your changes using:

```
pnpm i -D svelte@next
```

The doc site should remain fully functional during this. Just make sure to revert these changes before we merge these changes in to the `dev` branch.

### More Information

It's of the upmost importance that we do not merge the Svelte v5 RC dependency change into `dev` branch, so take care to add a big markdown note in the PR message please!

ETA for this change is before the Svelte v5 stable release, but the sooner the better for early adopters!

**Comment by Mahmoud-zino** [comment]
Regrettably, the `tree-view` component will not maintain compatibility with both Svelte 4 and Svelte 5 simultaneously due to its dependency on the Svelte 4 API. 

---

In Svelte 4, components are represented as classes, which are utilized within the tree-view to allocate events to its children. 
But in Svelte 5, components are functions, so it's impossible to find a solution that fits both Svelte 4 and Svelte 5 methodologies.

see: https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes

**Comment by linkfang** [comment]
> Regrettably, the `tree-view` component will not maintain compatibility with both Svelte 4 and Svelte 5 simultaneously due to its dependency on the Svelte 4 API.
> 
> In Svelte 4, components are represented as classes, which are utilized within the tree-view to allocate events to its children. But in Svelte 5, components are functions, so it's impossible to find a solution that fits both Svelte 4 and Svelte 5 methodologies.
> 
> see: https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes

Hi Mahmoud, are there any plan to add tree views components (`TreeView`, `TreeViewItem`, etc.) in Skeleton 3? I don't see them in current beta version. Thanks!

**Comment by linkfang** [comment]
> @linkfang current plans are as follows:
> 
> * Skeleton v2 with Svelte v4 -> the v2 TreeView will work as expected
> * Skeleton v2 with Svelte v5 -> you'll need to find your own substitute for the TreeView component
> * Skeleton v3 (at launch) -> will not have the TreeView as we're awaiting the [Zag.js version to launch](https://zagjs.com/components/react/tree-view)
> * As soon as this leaves beta we'll implement in v3. I'd expect this will be shortly after our launch.
> 
> It's not ideal, but this there's a lot of changes happening, and we're not going to implement a beta feature within our stable release.

Sounds good! Thanks for the detailed info!
