### ISSUE TITLE
Why Paginator pagging component is theme inverted?

### ISSUE THREAD

**Issue by koakh** [skeletonlabs/skeleton#2645]
### Current Behavior

when I use paginator, in my project or in the docs page <https://www.skeleton.dev/components/paginators>

the right component, the pagging component **is dark when we have light theme enabled**, 
and is **light when we have dark theme enabled**, like **inverted**, 

the left component the dropDown for numberItems is ok, and work has expected

IMHO this don't makes sense, both components should have the same theme dark, or light, just a opinion
maybe this is intentional, is so, how can I change this behavior and invert it in pagging component?

### Expected Behavior

I want to have the the right component, the pagging component, to be darker when we are in dark theme, and lighter when we are in light theme

### Steps To Reproduce

1. just navigate to docs page https://www.skeleton.dev/components/paginators and see it

### Link to Reproduction / Stackblitz

https://www.skeleton.dev/components/paginators

**Comment by endigo9740** [comment]
If you browse the Skeleton documentation you'll notice most button elements use this neutral tone by default. It's a stylistic choice.

https://www.skeleton.dev/components/paginators

If you would like to change this, we provide a slew of style props for doing so:

https://www.skeleton.dev/components/paginators?tab=properties

**Comment by koakh** [comment]
hello, first thank for the quick answer

it make sense if is a stylistic choice
sorry to ask, you are referring the `controlVariant` property?

if so, can you help me to use the mentioned property to invert the stylistic choice,
for me is not clear how can I do that,

a simple snippet example will be appreciated

in my case I prefer a dark in dark theme, and a white in white theme, is a matter of "taste",

I will appreciate any help

thanks in advance

**Comment by endigo9740** [comment]
@koakh controls contain a set of buttons, so you'll want to adjust he styles of the buttons.

Here's where it's detailed in the docs:
![image](https://github.com/skeletonlabs/skeleton/assets/1509726/950b782d-0bb9-48ae-b366-923de5e8de3d)

Here's an example changing it:

```html
<Paginator ... controlVariant="variant-filled-secondary" />
```
You can preview other button styles using variants here:
https://www.skeleton.dev/elements/buttons

And learn more about variants here:
https://www.skeleton.dev/docs/variants

If there's not a variant that applies the styles you want, then you my have to create your own custom option. In most cases these are a combination of light/dark styles for background, text, and fills. Here's the source for a more specific example:
https://github.com/skeletonlabs/skeleton/blob/master/packages/plugin/src/styles/components/variants.css

**Comment by koakh** [comment]
@endigo9740 

I opted to use a custom variant, that works with both theme flavours and I'm happy with it for now
I leave it here, maybe can be useful for others like me that prefer dark on dark, white on white option

```css
	.variant-filled-paginator {
		@apply bg-surface-200 text-surface-900 dark:bg-surface-700 dark:text-on-surface-token;
	}
```

thanks @endigo9740 really appreciate your hell

I love skeleton ui, 
it's a great for persons like me that just want to use some ready made opinionated components and move on coding
