### ISSUE TITLE
Fast hover breaks popup

### ISSUE THREAD

**Issue by NikitaZelenskis** [skeletonlabs/skeleton#2646]
### Current Behavior

https://github.com/skeletonlabs/skeleton/assets/28757930/116fb610-5693-492a-8eeb-518e3bdae05b

Hovering multiple times over a popup element with a 'hover' event type causes the popup to stop appearing, even when the element is actively hovered on. (See video)

Additionally, when multiple popup elements with the same hover trigger are located near each other, it causes similar issues, breaking the functionality of the popups.

### Expected Behavior

Have popup element always visible when it is hovered over.

### Steps To Reproduce

1. Rapidly hover over an element with a 'hover' event and then stop with the cursor remaining on the element.

Or

1. Place multiple elements with the same 'hover' event trigger close to each other.
2. Quickly move the cursor between these elements.

### More Information

Tested on Firefox and Google Chrome

**Comment by endigo9740** [comment]
I'd suggest reading what our plans are for this feature going forward. This is currently under a development freeze:
https://github.com/skeletonlabs/skeleton/issues/1916

Additionally our most recent progress update for Skeleton v3:
https://github.com/skeletonlabs/skeleton/discussions/2629

And finally keep an eye out for a new announcement coming out on Tuesday of this week.

I've mentioned your issue in the main feature thread above, so I'll go ahead and close this one. Thanks
