### ISSUE TITLE
Autocomplete: input should be of type string.

### ISSUE THREAD

**Issue by KitsuneDev** [skeletonlabs/skeleton#2647]
### Current Behavior

Autocomplete's `input` prop is of the `Value` generic type, which is used as the data type for `AutocompleteOption.value`.

### Expected Behavior

Autocomplete's `input` prop should be of `string` type, as it binds to [`HTMLInputElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#value) which is of type `string`.

### Link to Reproduction / Stackblitz

https://stackblitz.com/~/github.com/KitsuneDev/repro-skeletonlabs-autocompleter-generic

### More Information

* Discord Server Thread: https://discord.com/channels/1003691521280856084/1237072865883586661

**Comment by AdrianGonz97** [comment]
Thanks for raising the issue!

Took me a bit to understand the problem, but I eventually got there. We essentially want to decouple the generic type of the component from the input. However, I don't think setting it to `string` is the right fix for this issue. Changing it to `string` is considered a breaking change, so we'll have to set it to a wider type. Setting it to `unknown` instead should work. In v3, we can revisit and change it's type to `string | number | undefined`.

---

As a quick aside, I noticed you're using `CustomEvent` for a component event. Instead, you should use the [`ComponentEvents` helper type](https://svelte.dev/docs/typescript#types-componentevents) that's provided by Svelte like so:
```ts
function onSelected(e: ComponentEvents<Autocomplete<User | null>>["selection"]){
	selectedUser = e.detail.value;
	input = selectedUser?.username;
}
```

**Comment by KitsuneDev** [comment]
@AdrianGonz97 Sounds lovely! I appreciate the attention and the help.
Apologies for not providing a response earlier today, let's just say my sleep schedule has it's own... technical debt.

Regarding the use of `ComponentEvents`, it sounds lovely! [The docs probably should be updated to use that](https://www.skeleton.dev/components/autocomplete#demo), although I believe that would be an entirely different issue \:P.

Again, thank you very much for your attention, and I hope you have a lovely day.
