### ISSUE TITLE
Finalize v3 installation instructions for all meta-frameworks

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2653]
### Link to the Page

https://next.skeleton.dev/docs/get-started/installation

### Describe the Issue (screenshots encouraged!)

We should continue expanding this until it covers all support frameworks:

- [x] SvelteKit
- [x] NextJS
- [x] Vite/Svelte
- [x] Vite/React
- [x] Astro

### Related Task

- https://github.com/skeletonlabs/skeleton/issues/2714

**Comment by phamduylong** [comment]
@endigo9740 I can do that, but it would need careful reviewing from someone who knows better

**Comment by endigo9740** [comment]
Absolutely, I'll do a final review and modify as needed before we merge.
