### ISSUE TITLE
Document minimum versions for all dependencies and supported platforms

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#2658]
We should document the minimal versions we support in terms of browsers/features.

This can cover any and all of the following:

- Dependencies (Svelte/Kit, Next, Tailwind, etc)
- Browsers
- OS - if it differs from browsers
- Devices - it if differs from browsers/OS
- (we'll expand this as needed)

This may need to be broken down by each framework and meta-framework we support.

**Comment by endigo9740** [comment]
Folding this under the following ticket: https://github.com/skeletonlabs/skeleton/issues/2900
