### ISSUE TITLE
TabGroup spacing prop does not seem to override default value

### ISSUE THREAD

**Issue by torchello** [skeletonlabs/skeleton#2663]
### Current Behavior

```html
<TabGroup class="flex-1 basis-2/3" justify="justify-center" spacing="space-y-0">
```
generates the following HTML:
```html
<div class="tab-group space-y-4 flex-1 basis-2/3 space-y-0" data-testid="tab-group">
```
and `space-y-0` is not applied:
<img width="1032" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/897885/fb9be41d-20cb-4669-88a2-206efc12b8f3">

### Expected Behavior

Produced HTML should be:
```html
<div class="tab-group flex-1 basis-2/3 space-y-0" data-testid="tab-group">
```
and result should look like:
<img width="1027" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/897885/6dafdbf2-6e89-420c-82b0-fdbce441489c">

### Steps To Reproduce

Add `spacing="space-y-0"` as shown above.

**Comment by endigo9740** [comment]
Hey @torchello this one is a bit confusing, but `spacing` is not actually used in the group - but rather passed down to each `<TabItem>` reference. It's then used to set the spacing between the icon and label text for each tab. If you're not using icons in your tabs, this won't appear to do anything.

If you're wanting to affect the spacing between the tab list and panels, you can do this for now:

```html
<TabGroup class="space-y-0">...</TabGroup>
```

I 100% agree, this is confusing naming and behavior. In fact, this is one of the core tenets we're addressing in the upcoming Skeleton v3 release. I'd recommend you check out the following discussing the new approach. Style props will be much more semantic and behave closer to what you're expecting.

https://github.com/skeletonlabs/skeleton/discussions/2521

**Comment by endigo9740** [comment]
I'll go ahead and close this, given a solution is provided above. But if you have any further questions about this or v3, please do reach out. Thanks!
