### ISSUE TITLE
Update README assets for Skeleton v3

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2671]
### Link to the Page

https://github.com/skeletonlabs/skeleton

### Describe the Issue (screenshots encouraged!)

We should aim to improve these for not just the monorepo root, but also each individual site or package.

This will include:

- New banner image
- New badges per package: NPM, Discord, etc
- Overhaul the information
- Update the social links
- Link to Figma assets
- Etc

NOTE: this can and should be one of the last changes we make prior to release.

**Comment by endigo9740** [comment]
The README banner image should be updated to:

![github-banner](https://github.com/skeletonlabs/skeleton/assets/1509726/f5f38eb9-d7c6-4387-a4d6-4369e06868dd)

**Comment by endigo9740** [comment]
@phamduylong similar to the onboarding sections, I could use a head start on this.

- The banner is linked above
- We should drop the Twitter link in favor of [Bluesky](https://bsky.app/profile/skeletonlabs.bsky.social)
- NPM Package Badges:
  - Skeleton Core: https://www.npmjs.com/package/@skeletonlabs/skeleton
  - Skeleton React: https://www.npmjs.com/package/@skeletonlabs/skeleton-react
  - Skeleton Svelte: https://www.npmjs.com/package/@skeletonlabs/skeleton-svelte

Leave the text changes and Figma asset links to me to implement.

**Comment by phamduylong** [comment]
I'll try to have some baseline changes ready.

**Comment by phamduylong** [comment]
@endigo9740 do we want the old direct links to be updated as well?

For example, [https://skeleton.dev/docs/contributing](https://skeleton.dev/docs/contributing) to be updated to [https://next.skeleton.dev/docs/resources/contribute](https://next.skeleton.dev/docs/resources/contribute)

**Comment by endigo9740** [comment]
@phamduylong nah, the `next.` links are temporary and represent our "next major version". When v3 is merged into the mainline branch everything will live on the former URL. Then when we start v4 in the future, it'll resume using `next.`

**Comment by phamduylong** [comment]
@endigo9740 that's fine, however some links might not work after you change the domain in Vercel. The URL origin is the same, but I think some routing stuff changed, I first noticed it with this contributing page. I was thinking maybe we go with next.skeleton.dev and after the domain change we can just do a replace all or something, but however you feel like it.

**Comment by endigo9740** [comment]
No worries, there will probably be a few small things to tweak here and there around launch. I've created this thread to help track stuff like that though. I'll mention this.

https://github.com/skeletonlabs/skeleton/issues/2910
