### ISSUE TITLE
NEXT Doc Search

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/skeleton#2675]
### Describe the Issue (screenshots encouraged!)

Now we have a static website we can use tools like https://pagefind.app/ to implement search.

**Comment by TazorDE** [comment]
In order to best support skeleton v3 it might be a good idea to enable filtering for frameworks in the search that ignores the preferredFramework.
An example query would be 
`Accordion svelte` for the svelte version of the docs or
`Accordion react` for the react version

**Comment by endigo9740** [comment]
If possible, it would be great if we could display the URL path along with the page title and highlighted content. It would help differentiate different framework pages that have similar content.

Likewise, if possible, add a way to filter by `all | react | svelte` to help narrow the search on demand.

**Comment by Hugos68** [comment]
Both of the comments above are now implemented, feedback still very much appreciated

**Comment by endigo9740** [comment]
@Hugos68 Looks like some overflows are trimming the edges of the input here.

![Screenshot 2024-05-21 at 9 52 18 AM](https://github.com/skeletonlabs/skeleton/assets/1509726/f44bea6b-f7e4-42af-84b7-0ba373557a39)

Also you can't seem to click outside to close the modal. Not sure the method you're implementing the modal yet but that should be something Floating UI React can handle with with the Floating Overlay feature:

https://floating-ui.com/docs/FloatingOverlay

If you've opted for Floating UI Svelte, we can obvious revisit when this feature is available.

**Comment by Hugos68** [comment]
I'm currently using the `<dialog>` element. Do you really want to throw javascript at this problem when a native solution already exists? Also @endigo9740 let's move this discussion to the PR #2677.

**Comment by endigo9740** [comment]
I haven't had a chance to view how the dialog was handled. If that's the case it should be fine, but I still think click to close on the backdrop should be possible.

**Comment by Hugos68** [comment]
> I haven't had a chance to view how the dialog was handled. If that's the case it should be fine, but I still think click to close on the backdrop should be possible. In fact I understood it to be default behavior.

Sadly this is not the case, I think I'll be able to do this though. Give me an hour 😄, shouldn't be too difficult
