### ISSUE TITLE
NEXT: Installation page misspells "configure" twice

### ISSUE THREAD

**Issue by JohnnyJTH** [skeletonlabs/skeleton#2682]
### Link to the Page

https://next.skeleton.dev/docs/get-started/installation

### Describe the Issue (screenshots encouraged!)

![image](https://github.com/skeletonlabs/skeleton/assets/64006750/358b8a7b-4fc0-44ff-9d79-6bca05d8b78f)

**Comment by endigo9740** [comment]
Of course we would miss that - it's only been front end center for us over the last week! :)
