### ISSUE TITLE
Web site Theme Error On Arc

### ISSUE THREAD

**Issue by Johjoh-6** [skeletonlabs/skeleton#2683]
### Current Behavior

# Bug
On the page 
https://www.skeleton.dev/docs/generator
I got an error console `Invalid RGB value` when using _Arc_. But not with _Firefox_ or _Safari_.

This error stops the Js from working. 

### Expected Behavior

Working as expected.

### Steps To Reproduce

1. Open Arc.
2. Go to the home page of skeleton. https://www.skeleton.dev/
3. Then navigate to the theme generator. https://www.skeleton.dev/docs/generator
4. You will get the error message of `Invalid RGB value` in the console.

**Comment by Sarenor** [comment]
Try it in Incognito Mode & with another chromium based browser please. Not sure if this is a browser specific problem, I tend to guess that it's a machine-specific problem and you might need to clear your local state for the site.

Definitely doesn't break in Vivaldi, Chrome and Edge for me, which are all also chromium based.

**Comment by Johjoh-6** [comment]
Hi, 
I try with other chromium (Chrome) and Incognito mode. And It's working. 

I cleared all the cache and now it's working. 

Actually, I haven't played with the Theme generator since the V1. So it might explain this bug. 
But now compare to before I clear the cache I got this new warning.

![Screenshot 2024-05-24 at 11 16 36](https://github.com/skeletonlabs/skeleton/assets/74215632/d78d1c53-c294-4187-a6a6-27feb52e3809)

I don't know if this can help.

**Comment by endigo9740** [comment]
@Johjoh-6 we use localstorage for some of the data persistence, my assumption is you had some old values set that were interfering with the generator. Clearing your cache would resolve this, producing the results you're seeing. So we'll call this resolved. But let us know if you run into any other issues! Thanks
