### ISSUE TITLE
ListBox + Popup on a Modal

### ISSUE THREAD

**Issue by MugenTwo** [skeletonlabs/skeleton#2685]
### Current Behavior

The current behaviour is that when you click the button to open the dropdown, the list box is being shown behind the Modal.

### Expected Behavior

The Listbox should be shown on the Modal itself.

### Steps To Reproduce

This is a sample code

```html
{#if $modalStore[0]}
    <div class={cBase}>
        <header class={cHeader}>
            {$modalStore[0].title ?? "(title missing)"}
        </header>

        <form class="modal-form {cForm}">
            <label class="label">
                <div >
                <span>Fruit</span>
                <button class="btn variant-filled w-24 justify-between" use:popup={popupCombobox}>
                    <span class="capitalize">{userFruit ?? 'ORANGE'}</span>
                    <span>↓</span>
                </button>
                <div class="card w-24 shadow-xl py-1" data-popup="popupCombobox">
                    <ListBox rounded="rounded-none">
                        <ListBoxItem bind:group={userFruit} name="medium" value="APPLE">APPLE</ListBoxItem>
                        <ListBoxItem bind:group={userFruit} name="medium" value="ORANGE">ORANGE</ListBoxItem>
                        <ListBoxItem bind:group={userFruit} name="medium" value="PINEAPPLE">PINEAPPLE</ListBoxItem>
                    </ListBox>
                    <div class="arrow bg-surface-100-800-token" />
                </div>
                </div>
            </label>
            <label class="label">
                <span>Amount</span>
                <input
                    class="input"
                    type="number"
                    bind:value={amount}
                    placeholder="Enter fruits amount..."
                />
            </label>
        </form>
    <footer class="modal-footer">
        <button class="btn variant-filled" on:click={onOrderFruits}>Order</button>
    </footer>
</div>
{/if}
```

**Comment by endigo9740** [comment]
@MugenTwo I'm away from my workstation this weekend, but I'm not sure what you mean by "behind". Do you mean it's not visible or not interactive? Can you grab a screenshot or video of this in action, or perhaps create a Stackblitz minimal reproduction? It might also be helpful to know what OS/Browser you're testing one too.

**Comment by MugenTwo** [comment]
Hi! Yes, it's behind the modal. It's not visible at all. I am testing on Firefox.
This is how it looks like. It looks the same whether I click on it or not. And I know that the listbox actually gets generated behind when I check the HTML and also I quickly see it when I click outside of the modal (when I close the modal).

![image](https://github.com/skeletonlabs/skeleton/assets/17546545/314dd688-bce5-4ae1-aab6-a667d9536c64)

**Comment by endigo9740** [comment]
@MugenTwo so I'm at a bit of a loss here. As you can see here, Listboxes can and do work fine with modals (tap the List option):
https://www.skeleton.dev/utilities/modals#component-modals

Here's the source:
https://github.com/skeletonlabs/skeleton/blob/master/sites/skeleton.dev/src/lib/modals/examples/ModalExampleList.svelte

I might recommend you compare what you're doing to what we do in this example.

If you cannot find the issue, then we'll likely need a minimal reproduction to properly identify the issue. I might also recommend dropping the output of `npm list` here, which will log what specific version of each dependency you're running. I'm expecting you're running a recent version of Skeleton, but cannot know that for certain.

**Comment by MugenTwo** [comment]
Hi! Sorry, I forgot to specify that it's a listbox on a popup which opens with a button that is in a modal.

**Comment by endigo9740** [comment]
@MugenTwo that's a fairly complex UX flow, but nothing about that should prevent this from operating to my knowledge. Perhaps you're looping through the listbox with an `#each` statement? If so, you might verify your data is accurate and actually rendering? An empty listbox might appear missing or blank.

As it stands, there's not enough information provided for us to help troubleshoot your issue. I've now requested both a minimal reproduction as well as the output of your installed dependencies using the `list` command. Neither of which have been provided. We can't help you if you don't help us.

I'm going to close this out, but will consider reopening if the requested information can be submitted in full.
