### ISSUE TITLE
Tailwind v4 Oxide <--> Skeleton v3

### ISSUE THREAD

**Issue by oneezy** [skeletonlabs/skeleton#2689]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Is skeleton v3 going to work with Tailwind v4?
 
I've been playing around w/ the skeleton's `next` version (specifically themes) and it's nice, but i wasn't sure if there was a way to use it yet with Tailwind v4 since TW is _somewhat_ doing away with the `tailwind.config` and skeleton v3 is still generating css in js.

### What type of pull request would this be?

None

### Provide relevant links or additional information.

- [Tailwind v4](https://tailwindcss.com/blog/tailwindcss-v4-alpha#roadmap-to-v4-0) 
- [theme.css (v4)](https://github.com/tailwindlabs/tailwindcss/blob/next/packages/tailwindcss/theme.css)

**Comment by endigo9740** [comment]
@oneezy of course, but Tailwind v4 and Oxide is still VERY early days from their last public discussion on it and [missing many features](https://tailwindcss.com/blog/tailwindcss-v4-alpha#roadmap-to-v4-0). I could easily see it being a year out or more. We very much do want to support the new approach to styling, but this will likely involves a large breaking change to do so. Including themes possibly returning back to a CSS-based format. So I anticipate this taking the predominate focus of a future Skeleton release - call it v4 or v5.

Again, this will be a ways out, so I'll go ahead close out this request. But essentially the shorter answer is "yes, when it's ready".

**Comment by oneezy** [comment]
@endigo9740 , honestly i don't think it's as much of a breaking change as you might expect. I've been upgrading a few projects and I'm super impressed with how easy it's been!

here's a few words from the man himself:

https://x.com/adamwathan/status/1770979061721919598
> _"Shipped Tailwind CSS v4.0-alpha.10 today, which now uses CSS variables for each utility by default"_ ✨

[![image](https://github.com/skeletonlabs/skeleton/assets/7369575/6aafb3c3-3077-4555-bcf4-e389d86f33b2)](https://x.com/adamwathan/status/1770979061721919598)


https://x.com/adamwathan/status/1771914137615954352
> _"Really surprised by how many people think this is some dramatic shift in the framework! You have been able to use this approach to naming colors since the framework was released, and it's been in the documentation for years"_

[![image](https://github.com/skeletonlabs/skeleton/assets/7369575/979bf21d-1e61-43ed-bf99-beb6f2452c54)](https://x.com/adamwathan/status/1771914137615954352)

**Comment by endigo9740** [comment]
@oneezy ahh, I quite Twitter/X a while back, so I'm out of the loop if they don't share on their blog or other mediums.

And yeah I'm thrilled for all the options and simplicity it brings to the table. But we're kind pushing the limits on what Tailwind can do in our plugin. Feel free to browse our v3 plugin for to see what I mean.
https://github.com/skeletonlabs/skeleton/tree/next/packages/skeleton/src/plugin

We use JS to loop through, generate, and implement whole swathes of features. So the new CSS syntax would be a detriment in many regards. Trying to maintain all this by hand would be a nightmare:
https://github.com/skeletonlabs/skeleton/blob/next/packages/skeleton/src/plugin/utilities/color-pairings.ts

I hope to be wrong on this, but I don't think it'll be a trivial process for us. Especially if we need to maintain feature parity. But I do hope it helps streamline as much as possible.

**Comment by oneezy** [comment]
@endigo9740 yeah I see what you mean! You would definitely need to think about a few things before you make a deep dive on an upgrade, but I do think it's possible. It would definitely be a nightmare maintaining all of the by hand! You could keep all the JS but instead generate CSS files instead. Whatever you need a utility class for, you would wrap in a `@theme {}` , (you would also do your overwrites, extends, ect. here). The `@theme` can only contain `--properties` but I believe it can be used everywhere.

Eventually whenever you have it sorted I think it would be as easy importing your plugin: 
```css
/* app.css */
@import 'tailwindcss';
@import 'skeleton';

/* Themes */
@import 'skeleton/cerebus';
```
I mentioned this already in a TW 4 this feature request, But you could make use of the `light-dark()` function for your color pairings. It's simplifies light and dark mode so much! I'm just getting my feet wet with it but I do see how all of this new stuff can be leveraged.

**Comment by Sarenor** [comment]
You're completely right about ``light-dark()`` oneezy, but it only became "mainstream available" in [the last Safari release](https://developer.apple.com/documentation/safari-release-notes/safari-17_5-release-notes).   
If you check some of our other issues, we have people still using and wanting to support Macbooks from 2012.

As much as we'd love to simplify our lives like that, it's going to take a bit longer, I'm afraid...

**Comment by oneezy** [comment]
hey @Sarenor , yeah it is brand new out of the box 😅 I randomly found it the other days.

With **TW4 + Lightning CSS _(included with v4)_** , i believe it's handled for you out of the box _(replacing the need for postcss)_. 

> _"Lightning CSS includes support for transpiling modern CSS syntax to support older browsers, including vendor prefixing and syntax lowering."_

doing a quick search i found this:
- https://lightningcss.dev/transpilation.html#light-dark()-color-function
- https://github.com/tailwindlabs/tailwindcss/discussions/13698#discussioncomment-9473386
- https://vite-plugin-lightningcss.vercel.app/
