### ISSUE TITLE
computed styles not being applied

### ISSUE THREAD

**Issue by polaroidkidd** [skeletonlabs/skeleton#2706]
### Current Behavior

So I have this `SimpleButton.svelte` component, which I use to abstract some of the styling logic away. It looks like this
```svelte
<script lang="ts">
	import type { FORM_ACTIONS } from '@lib/routing/formActions';
	import classNames from 'classnames';
	
	export let disabled = false;
	export let formAction: FORM_ACTIONS | null = null;
	export let ariaLabel: string | null = null;
	export let type: "button" | 'reset' | 'submit' | null | undefined = null;
	export let variant:
		| 'surface'
		| 'primary'
		| 'secondary'
		| 'tertiary'
		| 'success'
		| 'warning'
		| 'error'
		| undefined = undefined;
	export let filled: 'filled' | 'ghost' | 'soft' | 'ringed' | undefined = undefined;
	let clazz = '';
	export { clazz as class };
	let style =
		!variant && !filled
			? 'variant-filled'
			: !variant && filled
				? `variant-${filled}`
				: !filled && variant
					? `variant-filled-${variant}`
					: `variant-${filled}-${variant}`;

	export let id: string | undefined = undefined;
</script>

<button
	{id}
	{type}
	aria-label={ariaLabel}
	formaction={formAction}
	on:click
	class={classNames('btn', style, clazz)}
	{disabled}
>
	<slot />
</button>
```

It can be used like this for example
```svelte
<SimpleButton

	type="submit"
	filled="ghost"
	variant="warning"
	on:click={openConfirmModal}
>
	Delete Collection
</SimpleButton>
```

This would result in the a button element like this
```html
<button type="submit" class="btn variant-ghost-warning">Delete Collection</button>
```

However, the styles are not applied in light mode. Only in dark mode is the `variant-ghost-warning` style applied . If pass `variant-ghost-warning` as a class to the `SimpleButton` component, then the styles are applied as expected.

Oddly enough, if I pass `variant-ghost-warning` as a separate "class" attribute to `SimpleButton` component, the styles are applied as expected.

Are computed styles somehow treated different by skeleton or tailwind?

### Expected Behavior

Computed styles apply in light and dark mode correctly

### App.postcss
```postcss
@tailwind base;
@tailwind components;
@tailwind utilities;
@tailwind variants;

:root [data-theme='gold-nouveau'] {
	--theme-rounded-base: 4px;
	--theme-rounded-container: 2px;
	--theme-font-family-base: 'Quicksand', sans-serif;
	--theme-font-family-heading: 'Quicksand';
}
/*place global styles here */
html,
body {
	@apply h-full;
}

@font-face {
	font-family: 'Quicksand';
	src: url('/fonts/Quicksand.ttf');
	font-display: swap;
}

```
### sveltekit config
```js
import adapter from '@sveltejs/adapter-cloudflare';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import preprocess from 'svelte-preprocess';
/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [
		vitePreprocess(),
		preprocess({
			postcss: true
		})
	],

	kit: {
		prerender: {
			handleHttpError: ({ message }) => {
				throw new Error(message);
			}
		},
		adapter: adapter({
			// See below for an explanation of these options

			routes: {
				include: ['/*'],
				exclude: ['<all>']
			}
		}),

		alias: {
			'@mocks/*': './src/__mocks__/*',
			'@hooks/*': './src/hooks/*',
			'@model/*': './src/model/*',
			'@components/*': './src/lib/components/*',
			'@icons/*': './src/lib/components/icons/*',
			'@lib/*': './src/lib/*',
			'@pages/*': './src/pages/*',
			'@services/*': './src/lib/services/*',
			'@styles/*': './src/styles/*',
			'@utils/*': './src/lib/utils/*',
			'@assets/*': './src/assets/*'
		}
	}
};

export default config;
```
### Tailwind config
```ts
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';
import { join } from 'path';
import type { Config } from 'tailwindcss';

// 1. Import the Skeleton plugin
import { skeleton } from '@skeletonlabs/tw-plugin';

const config = {
	// 2. Opt for dark mode to be handled via the class method
	darkMode: 'class',
	content: [
		'./src/**/*.{html,js,svelte,ts}',
		// 3. Append the path to the Skeleton package
		join(require.resolve('@skeletonlabs/skeleton'), '../**/*.{html,js,svelte,ts}')
	],
	theme: {
		extend: {}
	},
	plugins: [
		forms,
		typography,
		// 4. Append the Skeleton plugin (after other plugins)
		skeleton({
			themes: {
				// Register each theme within this array:
				preset: [{ name: 'gold-nouveau', enhancements: true }]
			}
		})
	]
} satisfies Config;

export default config;
```

**Comment by polaroidkidd** [comment]
I've added a stackblitz https://stackblitz.com/edit/vitejs-vite-sa3fmn?file=src%2Froutes%2F%2Bpage.svelte

**Comment by endigo9740** [comment]
@polaroidkidd you're running into one of the notable limitations of Tailwind, you cannot use constructed classes:

https://tailwindcss.com/docs/content-configuration#dynamic-class-names

The best way to understand this is to understand how the Tailwind compiler works:

1. It scans all files you provide it access to in your Tailwind Config > Context section
2. It scans these styles looking for full CSS utility classes, it cannot "see" partials
3. Finally it adds any classes it finds to your CSS bundle

In your case the compiler is missing all your classes because they are not able to be read verbatim. 

Another thing, we follow Tailwind's recommendation to avoid abstracting utility classes to a component like this. We follow their utility-first approach:

https://tailwindcss.com/docs/utility-first

This means that the classes themselves ARE the abstraction, and the expectation is you will mix and match the utility classes  as you implement your interface (buttons, etc).

If you have any questions about these topics let me know, but please do make sure you read those sections I linked in full. They will provide a lot of help in understanding how this works.

**Comment by polaroidkidd** [comment]
Oh wow. I had 100% forgotten about that. Thanks for the in-depth response. I was taring my hair out over this one. I really appreciate it.
