### ISSUE TITLE
v3 - consistency -D and --save-dev

### ISSUE THREAD

**Issue by mmailaender** [skeletonlabs/skeleton#2714]
### Link to the Page

https://next.skeleton.dev/docs/get-started/installation/sveltekit

### Describe the Issue (screenshots encouraged!)

-D and --save-dev is the same. I would recommend sticking to one 🙂
![image](https://github.com/skeletonlabs/skeleton/assets/87228994/30703fec-6a3f-4ecc-8011-d2fd3d48083d)

**Comment by endigo9740** [comment]
Thanks Micha!

**Comment by salisshuaibu11** [comment]
@endigo9740  assign this to me. which one should we choose?

**Comment by endigo9740** [comment]
Thanks @salisshuaibu11 - let's go with the more explicit option of: `--save-dev`

**Comment by salisshuaibu11** [comment]
@endigo9740 i am getting these errors anytime i run "pnpm dev".

![error2](https://github.com/skeletonlabs/skeleton/assets/26380687/07a1f51f-4fab-40c6-82aa-7ed0ee1c5c37)
![error1](https://github.com/skeletonlabs/skeleton/assets/26380687/76853293-eefa-4f61-8ec2-8aa1791a5032)

**Comment by endigo9740** [comment]
Hey @salisshuaibu11, did you follow these steps when setting up the project?

https://next.skeleton.dev/docs/resources/contribute/get-started

I'll reach out to the other folks on the team and see if they have any ideas.

**Comment by salisshuaibu11** [comment]
Yes, i have followed

**Comment by Hugos68** [comment]
I would recommend to go with `-D` it's the far more modern choice.

**Comment by endigo9740** [comment]
Folding this into:

- https://github.com/skeletonlabs/skeleton/issues/2653
