### ISSUE TITLE
TreeView - Custom Icons. 

### ISSUE THREAD

**Issue by Brown-Dan** [skeletonlabs/skeleton#2722]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Hi, Is there scope for enabling user's to provide custom open/closed icons for the treeview component?

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Hey Dan, unfortunately not at the moment. The Tree View was one of the last components introduced in Skeleton v2, which means it lacks some of the maturity of features of other comparable components. I will say we're absolutely open to adding this, but it'll have to come as part of our next major release (v3) as opposed to the current iteration. In fact next week I'm announcing plans to shift our full weight behind v3. It will be best for us to handle it there.

So here's what I'm going to do:

- If you absolutely need this right now, I might suggest cloning the component to your project and customizing locally. Skeleton is open source, so it's possible. Though obviously this may not be trivial.
- I'm going to link this issue on our pending v3 port of the Tree View component. We're taking into consideration all feature requests at the moment and implementing them there.
- I'm going to go ahead and close this issue out, as it'll be essentially folded the other issue (linked below)

Likewise if you can think if any other similar requests, feel free to include them directly in the thread here:

- https://github.com/skeletonlabs/skeleton/issues/2358
