### ISSUE TITLE
Carousel seems broken on doc page

### ISSUE THREAD

**Issue by jt-dev1** [skeletonlabs/skeleton#2731]
### Link to the Page

https://www.skeleton.dev/elements/scroll-containers

### Describe the Issue (screenshots encouraged!)

I cleared cookies and tried checking in incognito tab.

chrome version: Version 125.0.6422.142 

<img width="954" alt="Screenshot 2024-06-20 at 6 33 05 PM" src="https://github.com/skeletonlabs/skeleton/assets/159801195/fd9e82f0-377a-4606-98e3-4ced73beee11">

**Comment by endigo9740** [comment]
Thanks @jt-dev1 yeah I believe the source we were using has gone down. So we'll look to fix asap. If you insert your own images it should work as expected in the meantime though.
