### ISSUE TITLE
InputChips does not have restProps

### ISSUE THREAD

**Issue by Skyrdow** [skeletonlabs/skeleton#2737]
### Current Behavior

i found out that InputChip does not have restProps implemented as the page says:
![imagen](https://github.com/skeletonlabs/skeleton/assets/102250934/6e539f18-6cb0-49d4-ae23-194e8da3a503)
First i tried to add an aria-label but it didnt work, so went into the source code and it wasnt there

### Expected Behavior

It's actually really simple, FileDropzone uses `prunedRestProps()` to add the props to the input inside the component:
![imagen](https://github.com/skeletonlabs/skeleton/assets/102250934/8fef537b-737f-4783-9e1d-d3e2caddca79)
while InputChip does not have it:
![imagen](https://github.com/skeletonlabs/skeleton/assets/102250934/f05aa8ba-698f-43d1-8030-1dec263739df)

### Steps To Reproduce

1. using InputChip
2. add any aria-label to it
3. inspect the input in any browser, its not there

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/stackblitz-starters-9nyhrh?file=src%2Froutes%2F%2Bpage.svelte

### More Information

adding the `prunedRestProps` function 
```
  function prunedRestProps() {
    delete $$restProps.class;
    return $$restProps;
  }
```
and `{...prunedRestProps()}` to the input fixes the issue, this code is already in [FileDropzone](https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/components/FileDropzone/FileDropzone.svelte)

**Comment by Sarenor** [comment]
We've technically decided to put Skeleton v2 into a Feature Freeze. In theory, this might be small enough to still make the cut, but I'd like to wait for Chris verdict.

**Comment by endigo9740** [comment]
As Sarenor linked above, neither the team or myself have the bandwidth to maintain Skeleton v2 at the moment. So a pull request is welcome here if you would like to see this resolved in the short term. Either from you Skydow, or any other volunteer.
