### ISSUE TITLE
Table of Contents: support setting scrollTarget, scrollOffset

### ISSUE THREAD

**Issue by towel** [skeletonlabs/skeleton#2738]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I enjoy using the ToC Component but found some issues that are hard to work around.

Particularly with pages where the scrollable area is not the `body`, and when `sticky` elements are taking up space in the scrollable area, the coordinates used for correctly updating the active state of the anchors and jumping to anchors are off.

A possible solution would be to make setting `scrollTarget` available as well as introducing `scrollOffset` that will be considered when scrolling and updating the active state of the anchors as well as scrolling to the correct anchor coordinates when navigating in these cases.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
FYI new feature requests are being folded into current progress towards Skeleton v3. As such, I've copied your tasks here:
https://github.com/skeletonlabs/skeleton/issues/2362

I'm going to close this issue but you can now consider this request consolidated into the upcoming v3 changes. If you have similar requests going forward (for any feature) I'd recommend posting them in their respective v3 posts going forward. Thanks!
