### ISSUE TITLE
AppRailTile on:click not working (v2.10.1)

### ISSUE THREAD

**Issue by acerasoni** [skeletonlabs/skeleton#2740]
### Current Behavior

Given an AppRailTile with an attached on:click, the event is not fired upon clicking the tile.

For example:

```
<AppRailAnchor href="/" class="lg:hidden" on:click={() => { drawerStore.close(); }}>
	<svelte:fragment slot="lead"><i class="fa-solid fa-home text-2xl" /></svelte:fragment>
	<span>Home</span>
</AppRailAnchor> 
```

This is very similar to skeleton.dev's own website Sidebar behavior for mobile.

### Expected Behavior

Clicking the AppRailTile is expected to fire the on:click event

### Steps To Reproduce

1. Create an AppRailTile
2. Attach an on:click event
3. Click the tile

### More Information

The expected on:click event behaviour works with version 2.9.2 (previous one I was using), and breaks with latest 2.10.1

**Comment by endigo9740** [comment]
Looks like there is an `on:click` event, but it's not being forward up:
https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/components/AppRail/AppRailTile.svelte#L85

**Comment by clibequilibrium** [comment]
@endigo9740  hi I am having an issue when on 2.10.2 the on:click event is received 3 times now for <AppRailTitle>

**Comment by clibequilibrium** [comment]
Same code:
2.9.2 behavior 

https://github.com/user-attachments/assets/d1cbb59a-0d95-495d-aa77-b37e287a6180

2.10.2 behavior - notice triple click 

https://github.com/user-attachments/assets/cb4f851d-4ff0-4213-b6bc-153b51630d7f

**Comment by endigo9740** [comment]
@clibequilibrium do you mind filing a new ticket for this. The original issue here was raised, solved, and closed. So we won't be addressing anything new here. Please and thanks.

**Comment by clibequilibrium** [comment]
> @clibequilibrium do you mind filing a new ticket for this. The original issue here was raised, solved, and closed. So we won't be addressing anything new here. Feel free to link to this issue as reference though.
> 
> Please and thanks.

Will do!
