### ISSUE TITLE
Missing import of popup

### ISSUE THREAD

**Issue by Ryuno-Ki** [skeletonlabs/skeleton#2749]
### Link to the Page

https://www.skeleton.dev/utilities/popups

### Describe the Issue (screenshots encouraged!)

Hey there :wave: 

We're using Skeleton for developing [Anvil](https://codeberg.org/Anvil/Anvil/) and I like what you have built here!

I ran into an „popup is not defined” issue today and was able to resolve it with the code linked from https://github.com/skeletonlabs/skeleton/issues/2593 (thanks!).

The docs is almost right. I only missed to `import { popup } from '@skeletonlabs/skeleton` in the component I want to attach `use:popup` in.

**Comment by endigo9740** [comment]
Hey, @Ryuno-Ki, I'm not sure I follow. We indicate all required imports at the top of each page:

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/f5a233b7-ff40-4ea9-8133-2d01e30ca0d5)

I understand this approach has tripped some folks up in the past, so we're currently in progress of changing this for Skeleton v3, to provide full scoped examples per each code snippet, imports and all:

https://next.skeleton.dev/docs/components/accordion/svelte

Unless I've missed something, this will be our long term adjustment per your issue. I'd encourage your patience while we migrate towards v3.

**Comment by Ryuno-Ki** [comment]
Ah cool. There's a next subdomain I wasn't aware about :exploding_head: 
I'm happy.

**Comment by endigo9740** [comment]
Yeah Next is for the "next major version" of Skeleton. It's still in development, but we're building it in the open so everyone can monitor the changes and improvements. (of which there will be many)

If you haven't already, you can learn more here:

https://github.com/skeletonlabs/skeleton/discussions/2681
