### ISSUE TITLE
Disabled State for AppRailTiles

### ISSUE THREAD

**Issue by Teichralle** [skeletonlabs/skeleton#2781]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Hey,
i would like to disable certain AppRailTales, to allow the user to only move "backwards" via the apprail navigation and forwards via buttons on the screen. That allows me for easier validation of the page content via the buttons, and prevents the user from stepping over important pages.
Thanks Guys! Really appreceate your work :)

### What type of pull request would this be?

New Feature

**Comment by endigo9740** [comment]
@Teichralle it's taken a while to get back to this, so I've forgot some of the expectations here.

When I hear "disabled" I think like a disabled button state, where it's no longer interactive in any capacity. But I'm not sure sure what you mean by forward/backward here. Are you talking about keyboard-based tab navigation?

If you could please expand on this and help provide more context please.

**Comment by endigo9740** [comment]
No response so I'll go ahead and close this one. If you can let us know your expectations I'm happy to reopen and consider this change. Thanks.
