### ISSUE TITLE
installation instructions for next recommend a deprecated package

### ISSUE THREAD

**Issue by iain3000** [skeletonlabs/skeleton#2798]
### Link to the Page

https://next.skeleton.dev/docs/get-started/installation/sveltekit#install-tailwind

### Describe the Issue (screenshots encouraged!)

The next instructions for SvelteKit recommend using `npx @svelte-add/tailwindcss@latest --typography false` but the https://github.com/svelte-add/tailwindcss package is deprecated:

```
% npx @svelte-add/tailwindcss@latest --typography false

Need to install the following packages:
@svelte-add/tailwindcss@1.0.17
Ok to proceed? (y) 

npm warn deprecated @svelte-add/tailwindcss@1.0.17: Package no longer supported.
Please use npx svelte-add tailwindcss
```

`npx svelte-add@latest tailwindcss` works as expected.

The [live instructions](https://www.skeleton.dev/docs/get-started#install-tailwind) look correct, it's just the `next` branch that's using the deprecated package.

**Comment by endigo9740** [comment]
@iain3000 thanks for pointing this out. Yeah they're in the process of updating things too. We're currently focusing on updating the components themselves, then we'll aim for another round of doc and install instructions - which should include this. However, we would welcome a PR if you think you can handle this sooner. Thanks!
