### ISSUE TITLE
NEXT: Resolve global focus states for native elements and Zag-based components

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2806]
Following our recent [integration of Zag.js](https://github.com/skeletonlabs/skeleton/pull/2778), we've been alerted to the fact that our focus states styles are not consistent within Skeleton. Additionally, Zag handles focus state different than native elements. So we should review our options for providing a unified focus solution, ideally via a global style. Though we may need to replicate some focus states locally due to how Zag handles focus state with `data-focus` attributes.

## Goal

1. Implement a global focus styles within the Skeleton Tailwind plugin global stylesheet
2. Handle focus states per component

## Resources

* [Tailwind Preflight](https://tailwindcss.com/docs/preflight#extending-preflight)
* [Modern-Normalize](https://github.com/sindresorhus/modern-normalize)
* [Tailwind Focus docs](https://tailwindcss.com/docs/hover-focus-and-other-states#hover-focus-and-active)

**Comment by endigo9740** [comment]
Ok, so here's a quick rundown of what I've discovered regarding Tailwind and focus states:
- Tailwind utilizes a CSS reset called Modern-Normalize, but this does not seem to impact global focus states:
https://github.com/sindresorhus/modern-normalize
- Tailwind also implements their own "preflight" styles that made a few specific modifications:
https://tailwindcss.com/docs/preflight#extending-preflight
- Additionally Tailwind's own recommendation for adjusting focus states is IMO kind of bad. As it has you remove outline styles in favor of using `ring`.
https://tailwindcss.com/docs/hover-focus-and-other-states#hover-focus-and-active
- This is what I'd consider harmful - better explained here:
https://www.outlinenone.com/
(though they do say replacing and outline is ok, just not ideal)

What I've done is go ahead and implement [this pull request](https://github.com/skeletonlabs/skeleton/pull/2825) that does two things:

1. Provides an opinionated set of outline color styles to `:focus` using surface 950/50 for light/dark mode respectively
2. Implement a new `.focused` class that can be used by Zag-based components to display when `api.focused` is `true`

The result is more consistent focus styling across the board. Note that the global style does NOT fix the outline issue I brought up before for some browsers. Where you both a double outline (neutral + system OS color outline). An issue present in Chrome/Firefox, bot not Safari. It merely modifies the system color to a fixed light/dark surface shade based on light/dark mode. This results in a "thicker" outline.

Here's a before vs after comparison...

Before (default styles):

![Screenshot 2024-08-16 at 2 23 34 PM](https://github.com/user-attachments/assets/26c4cd0a-2378-4451-b78c-ade888862284)

![Screenshot 2024-08-16 at 2 25 24 PM](https://github.com/user-attachments/assets/8fe93d0d-04cb-45cb-9229-f48e8d162f29)

After (modified):

![Screenshot 2024-08-16 at 2 23 50 PM](https://github.com/user-attachments/assets/9b6e2374-6644-4676-bc00-6622215f6cea)

![Screenshot 2024-08-16 at 2 25 33 PM](https://github.com/user-attachments/assets/ac57a670-8a13-4163-8037-a3327c32ecf9)

The effect is more noticeable for themes that don't use blue by default (everything but Cerberus).

**Comment by bartduisters** [comment]
The default approach does work in Safari. Also, since so many folks are using Tailwind these days, isn't the default behavior what users are used to?

The default approach with the white and blue will work both on light and dark borders/backgrounds. While the `after` shown only has white. I guess it is less clear what would have focus when tabbing?

I guess the question is: would the thicker outline that has one color be sufficient enough if it focuses a button that has the same color as background color?

**Comment by endigo9740** [comment]
@bartduisters this is my concern as well. I'm tempted to drop the global style. But we will have a hard requirement for the `.focused` class in order for these Zag-powered components to work as expected.

**Comment by bartduisters** [comment]
My suggestion would be to take over the Tailwind approach, it might be less visually pleasing. But to me, functionality/accessibility is more important when I'm doing keyboard navigation. I rather clearly see what is selected when tabbing and it being visually less pleasing, than the other way around.

**Comment by endigo9740** [comment]
@bartduisters if you mean to default to Tailwind's default - then we definitely can for the global focus styles. But I don't think we replicate these for the component focus class. Those will likely never be in sync.

**Comment by endigo9740** [comment]
Just a quick update - after reviewing on Discord we've decided to forego the global `:focus` styles. They're likely too opinionated and could easily introduce issues.

Currently we are still using the `.focused` class styles for components. I'd welcome a review for this!

Furthermore, we may follow up with the Zag team in the near future and bring forth some of the pain points we're facing. See if they have any suggestions or are open to some suggestions for improvement in this regard.
