### ISSUE TITLE
NEXT: Improve the default SVG images for the Ratings component

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2808]
Following our recent [integration of Zag.js](https://github.com/skeletonlabs/skeleton/pull/2778), the Ratings component has been updated to embed default star icons using SVG images. Lucide does not provide an adequate icon for half stars, so we've implemented placeholders for now. These images should be reviewed to ensure the display is high quality and consistent.

**Comment by stalkerg** [comment]
Just accidentally I found the same issue for my project. Can we create a ticket on Lucide project?

**Comment by stalkerg** [comment]
Hmm but seems like it's here https://github.com/lucide-icons/lucide/pull/180 but in my case I expected filled star.

**Comment by endigo9740** [comment]
@stalkerg Lucide updates fairly often and this post was created back in August, so I'm not surprised if they've update since then. We may be able to use their version as a foundation for our embedded SVG, as long as their license allows for this. Otherwise I don't mind drawing some custom art.

> but in my case I expected filled star

If I recall correctly you can use `fill` and `stroke` independently for their icons.

**Comment by endigo9740** [comment]
Did a quick check, they use the ISC License which should suffice for this purpose:

> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

We can likely provide attributes as a link within the SVG code.

**Comment by endigo9740** [comment]
I was able to manipulate the SVG code directly to come up with something that should work.

![Screenshot 2024-12-12 at 2 22 15 PM](https://github.com/user-attachments/assets/2d957645-b489-499f-b731-868f43473752)
