### ISSUE TITLE
Is the selection prop in RecursiveTreeView reactive?

### ISSUE THREAD

**Issue by eft** [skeletonlabs/skeleton#2826]
This component has a boolean selection prop.  Can it be changed after the nodes have been rendered.  ie User clicks a button and selection prop is set to false or removed altogether?  I tried 

```svelte
<RecursiveTreeView selection={foo} nodes={myTreeViewNodes} />`
```

But it didn't react to changes to `foo`

Resorted to 

```svelte
{#if foo}
  <RecursiveTreeView selection nodes={bar} />
{:else}
  <RecursiveTreeView nodes={bar} />
{/if}
```

**Comment by endigo9740** [comment]
Hey @eft this is one of the few components built by another member of the team, so I apologize for not having a direct answer for you on this, but typically in Svelte if you want reactive props you need to need to bind them like this:

```html
<RecursiveTreeView bind:selection={foo} ... />`
```

Svelte docs on the subject:

https://svelte.dev/docs/element-directives#bind-property

Just a bit of a guess here, but if that doesn't work I'm going to say it's probably not currently responsive. But we would either welcome a PR changing this, or you are more than welcome to add a feature request for this for the upcoming v3 rebuild of this component:

- https://github.com/skeletonlabs/skeleton/issues/2358

Just drop a comment in that thread and let us know what you would like to see and we'll consider it.

**Comment by eft** [comment]
Thanks Chris.  I love this project.

**Comment by eft** [comment]
@endigo9740 someone one in Svelte discord suggested the selection is not reactive based on 

https://github.com/skeletonlabs/skeleton/blob/dev/packages/skeleton/src/lib/components/TreeView/RecursiveTreeView.svelte#L76

I did try your suggestion, to no avail.  I have a workaround though as per my OP.

**Comment by endigo9740** [comment]
Gotcha, thanks for confirming @eft. I'll go ahead and close this as the team and I have [shifted our full focus to Skeleton v3](https://github.com/skeletonlabs/skeleton/discussions/2729) recently.

I'm going to go ahead and close this ticket, but reference it within our v3 Tree View milestone issues to reference. This is the kind of thing we do want to be mindful of and try to address going forward.
