### ISSUE TITLE
Text in total field for paginator

### ISSUE THREAD

**Issue by ikranhaji8** [skeletonlabs/skeleton#2831]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I don't have the total amount of the data being displayed on table to use for the paginator. Paginator shows this 
<img width="268" alt="Screenshot 2024-08-17 at 7 24 18 PM" src="https://github.com/user-attachments/assets/a19cda3b-40b4-46f3-9a6f-397769e5415b">

### What type of pull request would this be?

New Feature

**Comment by endigo9740** [comment]
Hey @ikranhaji8 just a heads up the team and I have recently [shifted priority to Skeleton v3](https://github.com/skeletonlabs/skeleton/discussions/2729). As such we're still welcoming requests, but they are likely better suited for the v3 milestones as we revisit and update each component. I've gone ahead and linked this request so this will be taken into account.

That said, if you would like to see a change sooner, in v2, we do welcome contributor PRs!
