### ISSUE TITLE
Custom Fonts documentation guide to Preloading fonts affects performance and SEO drastically

### ISSUE THREAD

**Issue by amjadorfali** [skeletonlabs/skeleton#2835]
### Link to the Page

https://www.skeleton.dev/docs/themes#custom-fonts

### Describe the Issue (screenshots encouraged!)

# Problem
If you follow step 5 which is preloading the font, not only is the flicker still visible, but it reduced my Lighthouse score for performance from 100% to 78%, increasing LCP from 1.6s to 6s!

# Solution
There is actually a better CSS solution, we can set the `font-display: swap` property. It does the job, without affecting performance

```
@font-face {
	/* Reference name */
	font-family: 'Inter';
	/* For multiple files use commas, ex: url(), url(), ... */
	src: url('/fonts/Inter-VariableFont_slnt,wght.ttf');
	font-display: swap;
}
```
## Before preloading script, & after removing it
![Screenshot 2024-08-22 at 10 23 10 PM](https://github.com/user-attachments/assets/1fb8b6a5-29c0-4c28-b111-77b41bca1b06)

## When using the guide to preload the font, notice the font blocking the rendering
![Screenshot 2024-08-22 at 10 26 49 PM](https://github.com/user-attachments/assets/8784a2dd-2b77-4c23-90b2-9e36422bb174)

Note: In the 2nd image its a local build, it gives the same results in terms of loading as i added network throttling.

**Comment by endigo9740** [comment]
Sounds like a great improvement @amjadorfali, note that the team and I have [shifted our priorities to to Skeleton v3 recently](https://github.com/skeletonlabs/skeleton/discussions/2729). Which means we're relying on contributors to help with updates like this in the meantime. We welcome very much welcome a PR for this change.

If nothing else, I'll make a note of this so we update in transition to the v3 docs.

**Comment by amjadorfali** [comment]
@endigo9740 i will create a PR for it
