### ISSUE TITLE
Bug or intentional

### ISSUE THREAD

**Issue by eft** [skeletonlabs/skeleton#2844]
### Current Behavior

For the treeview and recursive treeview, if you set the `selection` prop without `multiple` ie single option, this only seems to make nodes at the same level radio buttons.  It's still possible to select more than one option from different branches.  Is this a bug or the way the designers intended it to behave?

![2024-09-01_15-04-09](https://github.com/user-attachments/assets/7e30f98b-90d9-404f-8039-55de8f71b337)

**Comment by endigo9740** [comment]
@eft currently the single selection records the top level and children item state independently. You can test this in the demo in your screenshot above. Monitor the `medium` and `books` selection:

https://www.skeleton.dev/components/tree-views#single

We do not take an opinionated stance on how you you prefer to use this,  however you do have the power to keep these in sync if you wish. To accomplish this use one of the events here:
https://www.skeleton.dev/components/tree-views?tab=events

Then pass the `group` value and use this to update the group state. The interface should adhere to this as long a `bind` is used.

Please note we will also be revisiting this component soon per Skeleton v3. You can see a number of community requests against this feature here:
https://github.com/skeletonlabs/skeleton/issues/2358

If you would like to request a change in this behavior, you can add comment in this thread for this.
