### ISSUE TITLE
File Upload console warnings

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2851]
I'm seeing the following warnings in the console on the `skeleton-svelte` version of the app. These seem to have been introduce in [this PR](https://github.com/skeletonlabs/skeleton/pull/2843), and appear the moment you load the File Upload preview page. They do not appear to impact usability though, so I'm going to suggest we circle back to this asap:

![Screenshot 2024-09-02 at 1 01 12 PM](https://github.com/user-attachments/assets/65f15590-dd8b-4c6b-8215-4a5e6d001ff2)

Hugo, I'd welcome your help troubleshooting these.

**Comment by endigo9740** [comment]
See also: https://github.com/skeletonlabs/skeleton/issues/2882

**Comment by phamduylong** [comment]
Could probably be solved with exposing custom event handlers, then call it along with zag's handler.

**Comment by endigo9740** [comment]
Leave this one to me, I want to follow up on it. Thanks.

**Comment by endigo9740** [comment]
I'm no longer able to replicate these issues. I'm assuming other PRs or dependency updates sorted this.
