### ISSUE TITLE
Integrate with Tailwind CSS VSCode plugin

### ISSUE THREAD

**Issue by benglewis** [skeletonlabs/skeleton#2854]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

It would be nice if the CSS classes and theme files could show a preview of the colors, like regular Tailwind classes show a preview of the color in VSCode:
![image](https://github.com/user-attachments/assets/b183ae3b-87cd-4739-ba76-48006bfa799c)

### What type of pull request would this be?

New Feature

**Comment by endigo9740** [comment]
We cannot integrate directly with Tailwind's extension, but we do have one of our own planned for the future:
https://github.com/skeletonlabs/skeleton/issues/2356

Feel free to add any specific requests there, please and thanks!

**Comment by benglewis** [comment]
@endigo9740 Just a quick question:
Why can you not integrate with the existing TailwindCSS extension?

**Comment by endigo9740** [comment]
@benglewis The Tailwind CSS extension is published by the Tailwind team and company Tailwind Labs, and we are not related or associated with them in any way. Maybe you're under the impression extensions are extensible, but I don't believe that to be the case. Afaik, the only way to get Skeleton-specific functionality in VS Code is to create our own extension - which is planned per the post shared above.

**Comment by benglewis** [comment]
I guess that I just assumed, yes, that it would be possible to use the same approach that Tailwind uses to highlight things and match the same "regexes" or similar. I probably just don't understand/know how Tailwind's extension works 🙊
