### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by Stan-Baumer** [skeletonlabs/skeleton#2855]
### Link to the Page

https://www.skeleton.dev/components/app-shell

### Describe the Issue (screenshots encouraged!)

Hello, for information the link "https://next.skeleton.dev/docs/design/layouts" from "https://www.skeleton.dev/components/app-shell" doesn't work

**Comment by bdeanhardt** [comment]
https://github.com/skeletonlabs/skeleton/pull/2856
