### ISSUE TITLE
next - Segment - Excessive logging

### ISSUE THREAD

**Issue by mwln** [skeletonlabs/skeleton#2857]
### Current Behavior

Currently while working with the library I'm trying to debug some feature behaviour while building a UI with the `@next` version of skeleton. I'm running into excessive logging likely caused by this [`$effect`](https://github.com/skeletonlabs/skeleton/blob/next/packages/skeleton-svelte/src/lib/components/Segment/Segment.svelte#L73-L77) in the `Segement.svelte` component.

I'm not familiar with the `on` function given by `svelte/events`, but upon checking the svelte5 RC I noticed its basically used as a substitute for adding basic event listeners. I'm wondering if this log was left in during some development on the feature?

### Expected Behavior

I wouldn't expect this level of logging while using the library in dev mode, although maybe that's intentional in this component.

### Steps To Reproduce

1. [create a new skeleton project using the `@next` tag](https://next.skeleton.dev/docs/get-started/installation/sveltekit)
2. `import { Segment } from '@skeletonlabs/skeleton-svelte';`
3. `npm run dev`
4. inspect > console > click around the segment
5. see element logs

**Comment by endigo9740** [comment]
I actually noticed this today as well @mwln thanks for creating an issue. And of course a PR would be welcome!
