### ISSUE TITLE
V3: Ordered List Example on Typography Page Wrong

### ISSUE THREAD

**Issue by ArgentumRhodon** [skeletonlabs/skeleton#2865]
### Link to the Page

https://next.skeleton.dev/docs/design/typography/#ordered

### Describe the Issue (screenshots encouraged!)

![image](https://github.com/user-attachments/assets/e508ed69-110e-4966-9c9b-e57cf958ca23)

**Comment by endigo9740** [comment]
Looks like this was an orphaned ticket, the issue was resolved a while back!
