### ISSUE TITLE
Autocompletion popup disappears with mouseup event outside of input field

### ISSUE THREAD

**Issue by dennismeister93** [skeletonlabs/skeleton#2867]
### Current Behavior

Hey :) I am wondering if the following behaviour is expected or actually an issue:

When using the autocompletion component the functionality works without a problem, but when selecting the input text and releasing the mouse click outside of the input field element the popup is disappearing. It only appears again, when clicking somewhere else to lose focus of the input field and focusing the input field again. You can find an example from your documentation:

![autocompletion_behaviour](https://github.com/user-attachments/assets/f02dfa30-a878-4414-b386-c732c6e022cc)

### Expected Behavior

The popup should stay visible after releasing the mouseup event outside of the input field element but the focus is still on the input field.

### Steps To Reproduce

1. Use the standard autocompletion component
2. Trigger the autocompletion by typing anything
3. Select the text inside the input field by clicking and marking the text part
4. Release the mouse click outside of the input field
5. Click somewhere to lose focus from the input field
6. Click the input field again to get focus on it

**Comment by endigo9740** [comment]
@dennismeister93 I can clarify that this is not intended behavior. But I also want to make it clear likely not something we (the Skeleton team) will address directly. We're currently [prioritizing Skeleton v3](https://github.com/skeletonlabs/skeleton/discussions/2729), which will replace Popover features with a new solution. We're evaluating two:

- Utilizing [Zag's](https://github.com/skeletonlabs/skeleton/discussions/2804) popover options - which implement Floating UI
- Utilizing our upcoming [Floating UI Svelte](https://github.com/skeletonlabs/floating-ui-svelte/discussions/50) port

Right now our goal is to actually ship both, but with Zag likely being the solution leading up to launch.

All that said, if this is an issue that's troubling you, I might suggest investing your own fix and sending a PR contribute. That or investigating the use of Floating UI directly, or substituting with a similar tool.
