### ISSUE TITLE
Autocomplete: hide popup on zero suggestions

### ISSUE THREAD

**Issue by MatthiasvB** [skeletonlabs/skeleton#2873]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently, the `emptyState` prop allows us to pass in some HTML to be displayed when no search results match. However, there are usecases where one may not only let the user choose between predefined options but also to provide custom content. In this case, it is annoying to still see "No Results found" or any similar content. I would want the autocomplete popup to simply disappear.

This could be implemented using a simple boolean flag `hideOnNoSuggestions` or, possibly allowing for even greater flexibility, by providing access to the currently available suggestions, allowing the developer to add custom styling (such as `display: none`).

### What type of pull request would this be?

Enhancement

**Comment by phamduylong** [comment]
Never used the Autocomplete component before, but isn't **regionEmpty** prop used for this? I think this could work for your purpose:
```html
<Autocomplete regionEmpty="hidden" />
```

**Comment by endigo9740** [comment]
> Never used the Autocomplete component before, but isn't **regionEmpty** prop used for this? I think this could work for your purpose:
> 
> ```
> <Autocomplete regionEmpty="hidden" />
> ```

Unfortunately no, that's a "style prop" intended for accepting utility class styles for the empty region of the template.

**Comment by phamduylong** [comment]
> > Never used the Autocomplete component before, but isn't **regionEmpty** prop used for this? I think this could work for your purpose:
> > ```
> > <Autocomplete regionEmpty="hidden" />
> > ```
> 
> Unfortunately no, that's a "style prop" intended for accepting utility class styles for the empty region of the template.

Isee. A flag like **hideOnNoSuggestions** should be simple enough. If this is an acceptable solution, can you assign it to me? I'll throw a PR ASAP.

**Comment by endigo9740** [comment]
Just FYI, we've outlined our plans for Skeleton v2 going forward in the post below. I'm am reaching out now as a heads up, as this ticket is slated to be closed when Skeleton v3 is released. Full details can be found here:

- https://github.com/skeletonlabs/skeleton/discussions/3063

If you no longer feel your issue is relevant, please feel free to close it directly.

And if you have any follow up questions, please feel free to reach out in the comments below. Thanks!

**Comment by MatthiasvB** [comment]
> Just FYI, we've outlined our plans for Skeleton v2 going forward in the post below. I'm am reaching out now as a heads up, as this ticket is slated to be closed when Skeleton v3 is released. Full details can be found here:
> 
>     * [Notice of End of Life for Skeleton v2 #3063](https://github.com/skeletonlabs/skeleton/discussions/3063)
> 
> 
> If you no longer feel your issue is relevant, please feel free to close it directly.
> 
> And if you have any follow up questions, please feel free to reach out in the comments below. Thanks!

I believe, since this is a feature request, it may stay relevant

**Comment by endigo9740** [comment]
@MatthiasvB have you had a chance to test our new Combobox feature in Skeleton v3 yet? This is what we're providing as our spiritual successor to the Autocomplete:

https://next.skeleton.dev/docs/integrations/popover/svelte#combobox

Most components in v3 were completely rewritten from the ground up, are now built on top of [Zag.js](https://github.com/skeletonlabs/skeleton/discussions/2804), which means they are fairly feature rich out of the box. This includes all Popover components.

I might suggest you start by confirming if the new components meet your requirements, then we can go from there.

**Comment by endigo9740** [comment]
Quick follow up - I just tested this. Now when the list of options array is empty `[]` the input remains visible, but the popover itself does not appear. I believe this is the behavior requested. Again, I'd suggest you confirm directly, but I think this may already be solved for you in v3!

**Comment by MatthiasvB** [comment]
> Quick follow up - I just tested this. Now when the list of options array is empty `[]` the input remains visible, but the popover itself does not appear. I believe this is the behavior requested. Again, I'd suggest you confirm directly, but I think this may already be solved for you in v3!
> 
> Here's without options first, then a quick reload so the options are present:
> Kapture.2024-12-18.at.15.51.52.mp4

I'll take your word for it. Unfortunately I don't right now have the capacity to upgrade that app to v3, test and report. If stuff is rewritten and feature-enhanced, there's probably no point in keeping this feature request around. Thanks for your efforts!
