### ISSUE TITLE
Skeleton CLI create new project fails

### ISSUE THREAD

**Issue by horakmar** [skeletonlabs/skeleton#2874]
### Current Behavior

Hello.
I am trying to create new project using recommended Skeleton CLI:
`npm create skeleton-app@latest my-skeleton-app`

After selecting options and a few seconds of "Installing..." I get error:
```
■  Canceled
npm error code 1
npm error path /home/horakmar/devel
npm error command failed
npm error command sh -c create-skeleton-app my-skeleton-app
npm error A complete log of this run can be found in: /home/horakmar/.npm/_logs/2024-10-14T07_49_55_626Z-debug-0.log
```

### Expected Behavior

Skeleton project barebones installed in my-skeleton-app folder.

### Steps To Reproduce

1. Environment:
OS: Linux Ubuntu 24.04.1 LTS
NodeJS: v20.18.0
NPM: v10.8.2

2. Selecting components:
App template: Bare Bones
Theme: Skeleton
Other packages: Tailwind forms, Tailwind typography
Typescript: Yes, using TypeScript syntax
Setup: Add ESLint for code linting, Add Prettier for code formatting

3. Got error:
```
■  Canceled
npm error code 1
npm error path /home/horakmar/devel
npm error command failed
npm error command sh -c create-skeleton-app my-skeleton-app
npm error A complete log of this run can be found in: /home/horakmar/.npm/_logs/2024-10-14T08_27_47_230Z-debug-0.log
```

4. Debug log (tail):
```
24 http fetch POST 200 https://artif.apps.corp/artifactory/api/npm/central-npm-ext/-/npm/v1/security/advisories/bulk 227ms
25 silly audit report {}
26 verbose stack Error: command failed
26 verbose stack     at promiseSpawn (/home/horakmar/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
26 verbose stack     at spawnWithShell (/home/horakmar/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
26 verbose stack     at promiseSpawn (/home/horakmar/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
26 verbose stack     at runScriptPkg (/home/horakmar/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
26 verbose stack     at runScript (/home/horakmar/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
26 verbose stack     at run (/home/horakmar/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/libnpmexec/lib/run-script.js:48:10)
26 verbose stack     at async exec (/home/horakmar/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:293:10)
26 verbose stack     at async Init.execCreate (/home/horakmar/.nvm/versions/node/v20.18.0/lib/node_modules/npm/lib/commands/init.js:136:5)
26 verbose stack     at async Init.exec (/home/horakmar/.nvm/versions/node/v20.18.0/lib/node_modules/npm/lib/commands/init.js:44:14)
26 verbose stack     at async Npm.exec (/home/horakmar/.nvm/versions/node/v20.18.0/lib/node_modules/npm/lib/npm.js:207:9)
27 error code 1
28 error path /home/horakmar/devel
29 error command failed
30 error command sh -c create-skeleton-app my-skeleton-app
31 verbose cwd /home/horakmar/devel
32 verbose os Linux 6.8.0-45-generic
33 verbose node v20.18.0
34 verbose npm  v10.8.2
35 verbose exit 1
36 verbose code 1
37 error A complete log of this run can be found in: /home/horakmar/.npm/_logs/2024-10-14T08_27_47_230Z-debug-0.log
```

### More Information

  * Neither work with NodeJS v18.20.4
  * My site is behind corporate proxy, NPM works through Artifactory as a cache.
  My .npmrc:
  ```
engine-strict=true
email=[REDACTED]
always-auth=true
registry=https://artif.apps.corp/artifactory/api/npm/central-npm-ext/
//artif.cc.corp/artifactory/api/npm/central-npm-ext/:_auth="[REDACTED]"
strict-ssl=false
init-author-name=horakmar
init-author-email=[REDACTED]
```

**Comment by horakmar** [comment]
Update:
I tried the same with direct connection to Internet (no proxy, no NPM in-between cache) and it works! So it seems the problem is probably with proxy. It seems to me like some part of installing process cannot reach to it's resource on Internet.

Basically I need better error logging to be able to identify the problem. How to get more verbose error logging?

**Comment by horakmar** [comment]
Hello.
Sorry about commenting so late. Thank you @endigo9740 for at least the basic information. As a javascript newbie I am far from being able to understand create-skeleton source code. But if I understand it at least a bit, it seems to me, that it's fetching some data directly from hardcoded URLs via "got". If it doesn't honor classic proxy env vars (HTTP_PROXY, ...) it cannot reach the destination.

Fortunately I found a way how to do project init by running `create` on machine with direct internet access and cloning folder afterwards. It's awkward, but at least something.

**Comment by horakmar** [comment]
Ehm... I still think, that `npm create skeleton-app` **should** work even behind the proxy, but if no other users have this problem, I understand that it's maybe not worth spending precious developer's time on it. ;-)

**Comment by endigo9740** [comment]
@horakmar let me re-iterate - the contributor that maintained this feature is no longer part of the project. Neither myself or anyone else on the team has any desire to pickup and maintain the CLI. And we will not be utilizing it after our next upcoming major release (v3). So it's essentially reaching end of life, likely by end of year.

We're a small team, so we have limited resources. However, the open source community is vast. If you or someone else would like to jump in and contribute a fix, we'll gladly accept it. I just can't imagine it's useful for the time this will remain the production option for us.

**Comment by horakmar** [comment]
Yes, I see. I'm sorry, I'm still not skilled in JS enough to make a fix for proxy handling. Thank you for v3 Beta link, I should probably start right away with that. Or maybe try Flowbite instead? :-)
Anyway, thank you for very nice library.
