### ISSUE TITLE
LSP-SUGAR: typescript language server raises skeleton module found but not resolved in tailwind.config.ts

### ISSUE THREAD

**Issue by Haiz14** [skeletonlabs/skeleton#2877]
### Current Behavior

This error doesn't affect the working of skeleton, only the lsp complains.

Follow reproducing section, and an error like this will be raised by typescript server language server.

```text
 │     Cannot find module '@skeletonlabs/skeleton/plugin' or its corresponding type declarations. typescript (2307) [3, 26]
 │        There are types at '/data/data/com.termux/files/home/teste-skeleton-next/node_modules/@skeletonlabs/skeleton/dist/plugin/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'. 
```

Typescript language server version `❯ typescript-language-server  --version
4.3.3`

### Expected Behavior

LSP shouldn't raise this error.

### Steps To Reproduce

1. Standard installation of skeleton-next sveltekit via https://next.skeleton.dev/docs/get-started/installation/sveltekit
2. Final `tailwind.config.ts` should be something like 
```ts
import type { Config } from 'tailwindcss';
import { join } from 'path';
import { skeleton } from '@skeletonlabs/skeleton/plugin';
import * as themes from '@skeletonlabs/skeleton/themes';

export default {
	content: [
		'./src/**/*.{html,js,svelte,ts}',
		join(require.resolve('@skeletonlabs/skeleton-svelte'), '../**/*.{html,js,svelte,ts}')
	],

	theme: {
		extend: {}
	},

	plugins: [
		skeleton({
			themes: [
				themes.rose,
				themes.cerberus,
			],
		})
	]
} as Config;
```
3. Check your typescript lsp errors. It should show the expected error.

### More Information

`tsconfig.json` 's `modupeResolution` is `bundler`

**Comment by Haiz14** [comment]
not reproducible in vscode, should i close it? It only occurs in my neovim lsp.

**Comment by endigo9740** [comment]
@Haiz14 we'll leave it for now for documentation sake.

**Comment by Xenon27** [comment]
I have a similar thing in VS-Code

<img width="1055" alt="Bildschirmfoto 2024-10-28 um 17 32 58" src="https://github.com/user-attachments/assets/0bf6a6d0-c778-4e3f-b087-0239e177a4ea">

**Comment by Xenon27** [comment]
I am using SvelteKit

**Comment by Haiz14** [comment]
Sveltekit

**Comment by slythom** [comment]
Same error:
Cannot find module '@skeletonlabs/skeleton/plugin' or its corresponding type declarations.

With SvelteKit. Skeleton v3 beta.

**Comment by endigo9740** [comment]
Just FYI guys, we've made some headway on this. We have a PR pending. We'll test and release a patch asap:
https://github.com/skeletonlabs/skeleton/pull/2931

**Comment by endigo9740** [comment]
@Haiz14 @Xenon27 @slythom we've just pushed out an update to the core package. That should be:

```
@skeletonlabs/skeleton 3.0.0-next.7  
```

If you guys would please update and verify this resolves things on your end. If you're using VS Code, make sure to restart the local environment. You can do this with `shift + control + P` on Windows:

![Screenshot 2024-11-07 at 1 40 01 PM](https://github.com/user-attachments/assets/a97f0c7e-4bbc-49d9-9b86-0ebe7e07fa16)

Either of the first two options should work.

**Comment by slythom** [comment]
Everything is fine now! Well done, thanks!! 
And I didn't need to restart the local environment.

**Comment by endigo9740** [comment]
Glad to hear! We'll await confirmation from a couple other folks before we close out the issue.

**Comment by endigo9740** [comment]
We've had a number of folks confirm this fix on Discord, so I'm going go ahead and close this out. Thanks!
