### ISSUE TITLE
Prevent AccordionItem from toggling open/closed when typing space

### ISSUE THREAD

**Issue by FabianHertwig** [skeletonlabs/skeleton#2878]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Hi,

I want to have an input field in an AccordionItem bar, so that users can change a title.

I have the issue though, that when a user types a space, then the accordion toggles its closed state. Even if I try to stop the propagation of the event, it still happens.

Is there a way to stop the toggling from happening when typing into the input field?

This is a svelte kit application. Below is some example code.

```js
<script>
	import { Accordion, AccordionItem } from '@skeletonlabs/skeleton';

	let title = 'The title';
	let summary = 'The summary';
</script>

<Accordion>
	<AccordionItem open>
		<svelte:fragment slot="lead">
			<input
				type="text"
				bind:value={title}
				class="bg-transparent"
				on:keydown|stopPropagation
				on:keyup|stopPropagation
				on:keypress|stopPropagation
				on:click|stopPropagation
			/>
		</svelte:fragment>
		<svelte:fragment slot="summary">
			<input
				type="text"
				bind:value={summary}
				class="bg-transparent"
				on:keydown|stopPropagation
				on:keyup|stopPropagation
				on:keypress|stopPropagation
				on:click|stopPropagation
			/>
		</svelte:fragment>
		<svelte:fragment slot="content">The content</svelte:fragment>
	</AccordionItem>
</Accordion>
```

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

AccordionItem keyboard events: https://www.skeleton.dev/components/accordions?tab=keyboard

**Comment by FabianHertwig** [comment]
I see, the slots are inside a button element and space triggers a button for accessibility reasons.
https://github.com/skeletonlabs/skeleton/blob/master/packages/skeleton/src/lib/components/Accordion/AccordionItem.svelte

**Comment by endigo9740** [comment]
Hey @FabianHertwig so inputs or other interactive elements inside the lead element are unexpected but I could see how that would cause some issues. Typically that space is reserved specifically for the Accordion label.

It sounds like you've seen, but we implement the keyboard interaction for a11y reasons. Both enter/space should toggle the header when in a focus state:
https://www.w3.org/WAI/ARIA/apg/patterns/accordion/

`stopPropagation` would have been my initial suggestion for a fix. If that's not working we'll need to review further. Off the top of my head this may require a change to the Accordion source to firing the keyboard event when a child of the lead is selected.

If you're open to this, I'd welcome a PR for this, as myself and the team are fully focused on Skeleton v3 at the moment:
https://github.com/skeletonlabs/skeleton/discussions/2729

Speaking of which, we're taking a very different approach to components in v3. So if you have time it may be worth testing your scenario there as well. Off hand I'm not sure if this scenario would remain or not:
https://next.skeleton.dev/docs/components/accordion/svelte

**Comment by FabianHertwig** [comment]
Thanks for your comment @endigo9740 

I just found that `on:keyup|preventDefault` solves my issue!
