### ISSUE TITLE
Switch `onchange` errors

### ISSUE THREAD

**Issue by MrVauxs** [skeletonlabs/skeleton#2882]
### Current Behavior

Documentation states that [Switch](https://next.skeleton.dev/docs/components/switch/svelte) can be used with `onchange` property. However, currently there are two issues regarding it:

1. The property does not exist in the elements types.
2. Adding the property causes a slew of the following warnings: 
![image](https://github.com/user-attachments/assets/8f4849c1-ae1a-4cd7-89fe-a3becb57c092)

The function instead of running returns the same warning whenever the switch state changes. `on:change` does not throw a type error, but does not do anything, not even the aforementioned warning

### Expected Behavior

`onchange` working.

### Steps To Reproduce

Copy paste what the documentation says in the **Lightswitch** example.

### Link to Reproduction / Stackblitz

https://github.com/MrVauxs/skeletonrepro

### More Information

![Code_CcSGg3Kz1L](https://github.com/user-attachments/assets/4e1458e1-ff16-4daf-8d47-390ef72fc23a)
![chrome_NGdFYeAQ5r](https://github.com/user-attachments/assets/fc6033e9-0926-4e2d-9d8c-bbda090d655d)

**Comment by endigo9740** [comment]
See also: https://github.com/skeletonlabs/skeleton/issues/2851

**Comment by phamduylong** [comment]
I'll investigate this issue.

**Comment by phamduylong** [comment]
Perhaps this and #2971 can be closed already.
