### ISSUE TITLE
NEXT: Combobox.svelte:46:15 `$state.frozen` is now `$state.raw`

### ISSUE THREAD

**Issue by TheEisbaer** [skeletonlabs/skeleton#2889]
### Current Behavior

```
[plugin:vite-plugin-svelte] node_modules/.pnpm/@skeletonlabs+skeleton-svelte@1.0.0-next.11_svelte@5.0.5/node_modules/@skeletonlabs/skeleton-svelte/dist/components/Combobox/Combobox.svelte:46:15 `$state.frozen` is now `$state.raw`
node_modules/.pnpm/@skeletonlabs+skeleton-svelte@1.0.0-next.11_svelte@5.0.5/node_modules/@skeletonlabs/skeleton-svelte/dist/components/Combobox/Combobox.svelte:46:15
44 |  
 45 |    // Zag
 46 |    let options = $state.frozen(data);
                                          ^
 47 |    const collection = combobox.collection({
 48 |      items: data,
```

### Expected Behavior

no errors

### Steps To Reproduce

```
"@skeletonlabs/skeleton": "3.0.0-next.5",
		"@skeletonlabs/skeleton-svelte": "1.0.0-next.11",
		"@sveltejs/adapter-auto": "^3.3.0",
		"@sveltejs/kit": "^2.7.2",
		"@sveltejs/vite-plugin-svelte": "^4.0.0",
		"@tailwindcss/forms": "^0.5.9",
		"@types/eslint": "^9.6.1",
		"@types/node": "^22.7.9",
		"autoprefixer": "^10.4.20",
		"eslint": "^9.13.0",
		"eslint-config-prettier": "^9.1.0",
		"eslint-plugin-svelte": "^2.46.0",
		"globals": "^15.11.0",
		"prettier": "^3.3.3",
		"prettier-plugin-svelte": "^3.2.7",
		"prettier-plugin-tailwindcss": "^0.6.8",
		"shiki": "^1.22.0",
		"svelte": "5.0.5",
		"svelte-check": "^4.0.5",
```

**Comment by endigo9740** [comment]
Thanks for the heads up @TheEisbaer, I did a quick check and this originates on Zag's end. We tend to implement verbatim unless we're changing the interface or functionality.
https://github.com/chakra-ui/zag/blob/main/website/data/snippets/svelte/combobox/usage.mdx

It may be worth reporting on their end too!
https://github.com/chakra-ui/zag/issues

**Comment by Karakatiza666** [comment]
This is a blocker - @skeletonlabs/skeleton-svelte cannot be compiled until this is fixed. The previous version - "1.0.0-next.10" - works
The fix is to just replace `$state.frozen` with `$state.raw`, checked locally, this is the only issue that prevents compilation.

**Comment by TheEisbaer** [comment]
@endigo9740 Thanks for the quick response, I will look into reporting it to zag as well.

**Comment by endigo9740** [comment]
This has been resolve as part of this PR: https://github.com/skeletonlabs/skeleton/pull/2892
