### ISSUE TITLE
Do not mount unselected Tab's content in @skeletonlabs/skeleton-svelte

### ISSUE THREAD

**Issue by Karakatiza666** [skeletonlabs/skeleton#2913]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently when Tab list component is mounted it looks like all hidden tab panels are initialized and mounted, too. It would be nice to be able to select behavior:
- Always mounted (like now)
- Lazy mounted (when first opening the tab)
- One tab only (unmount the tab when it is hidden).

In Zag.js reference I did not find a way to adjust this behavior either.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

https://zagjs.com/components/react/tabs

**Comment by endigo9740** [comment]
> In Zag.js reference I did not find a way to adjust this behavior either.

@Karakatiza666 core behavior is now handled by Zag, so if they don't support this, then the issue needs to be reported upstream (to them) rather than to us. We can extend and modify to some degree, but there are limitations.

**Comment by Karakatiza666** [comment]
Got it, thank you! I will note this for all component-related inquiries

**Comment by endigo9740** [comment]
Sounds good. Again, if we can extend feature let us know. I'm interested in doing so. And I can also vouch for the Zag team being receptive to feedback.
