### ISSUE TITLE
Typo in Dark Mode docs

### ISSUE THREAD

**Issue by phamduylong** [skeletonlabs/skeleton#2917]
### Link to the Page

https://www.skeleton.dev/docs/dark-mode

### Describe the Issue (screenshots encouraged!)

Initialize, I think.

![image](https://github.com/user-attachments/assets/efdd0e9d-6f5a-4367-aaaa-1c86254e62e4)

**Comment by endigo9740** [comment]
@phamduylong correct, this will need to be corrected. We welcome a PR for this!
