### ISSUE TITLE
On Pagination's `alternative` mode, the number of pages is not being displayed correctly

### ISSUE THREAD

**Issue by Arro** [skeletonlabs/skeleton#2933]
### Current Behavior

This bug is visible [on the official docs site](https://next.skeleton.dev/docs/components/pagination/react).  

`sourceData` has a length of 4.  `pageSize` is 3.  Therefore there are 2 pages.  

If you run the code yourself, you can see this for yourself by clicking to the next page, and having it being at the end.  However it displays there are 4 pages.  I think it's just displaying the number of records.

### Expected Behavior

It should divide the number of records by the page size, and display that number.

### Steps To Reproduce

See above.

**Comment by endigo9740** [comment]
Thanks Arro, we'll take a look. The team and I are focused on documentation and guides at the moment, so if this is something you need sooner than later, a PR would be more than welcome!

**Comment by endigo9740** [comment]
Resolved by: https://github.com/skeletonlabs/skeleton/pull/2956
