### ISSUE TITLE
Nav.Tile button type as prop

### ISSUE THREAD

**Issue by Uncle798** [skeletonlabs/skeleton#2934]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I would like to use a `Nav.Tile` to trigger a form action and to do that I would need to set the type of the button to submit i.e. 
```svelte
<Nav.Bar bind:value={navValue}>
  <form action="/logout" method="POST" use:enhance>
    <Nav.Tile id='0' label='Logout' type='submit'>
    </Nav.Tile>
  </form>
</Nav.Bar>
```
Currently the button doesn't submit the form and the above throws a type error as `type` isn't a publicly available prop. 

### What type of pull request would this be?

Enhancement

**Comment by phamduylong** [comment]
I'll take a look

**Comment by Hugos68** [comment]
@endigo9740 This can be closed FYI.
