### ISSUE TITLE
Buttons hover effects not noticeable with certain themes and presets

### ISSUE THREAD

**Issue by knd775** [skeletonlabs/skeleton#2938]
### Current Behavior

On darker themes, buttons with `preset-tonal` or `preset-tonal-surface` don't perceptibly change on hover. For darker values, they don't change at all.

### Expected Behavior

Noticeable hover effects on buttons

### Steps To Reproduce

1. Use a darker theme
2. Create a button with `preset-tonal`
3. Hover the button

**Comment by endigo9740** [comment]
@knd775 per my notes here, I've tried a lot of different combinations of brightness / contrast shifts / etc and and what I settled on was a subtle change to the brightness.

https://github.com/skeletonlabs/skeleton/pull/3050

This follows [Shadcn](https://ui.shadcn.com/) and flips the lighten/darken effect in light/dark mode from it's prior iteration. In most scenarios this still produces a subtle hover effect, but all around seems better.

If this does meet your individual theme's requirements, I might consider a local override, mixing presets for standard/hover states, etc.

If we continue to hear feedback around this, then I think that'll be a signal that the styles are too flexible for us to cover all use cases. In that case, we might remove our built-in hover effect and leave this entirely up to end users.
