### ISSUE TITLE
Pagination: Don't show ellipses when there are four pages

### ISSUE THREAD

**Issue by knd775** [skeletonlabs/skeleton#2940]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently, it shows ellipses when it could just show all the pages in the same number of buttons.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

![image](https://github.com/user-attachments/assets/bcc2c6f0-5245-4fb3-82c9-c84789fd49f4)

**Comment by endigo9740** [comment]
@knd775 unfortunately Zag does not appear to offer a setting to modify this behavior. I'm going to recommend you go ahead and file this as a feature request upstream:
https://github.com/chakra-ui/zag/issues

You're welcome to link back to this issue or mention Skeleton - the team is very aware of me and the project! Though I will warn you that they are focused on updates to the Chakra library right now, so ETA may be up in the air.

I also wanted to make it clear this is a fairly niche issue that requires a very specific scenario to play out:

1. You must have a number of data items that enables pagination
2. You must have a `pageSize` sets generates exactly exactly four pages
3. You must be on the first page (on the second the issue resolves itself)

My guess is their math calculations is "off by one" in this very particular scenario to even enough this.

## Quick Sidenote

For Skeleton - I've gone ahead and updated the examples as part of #2956 to change the page size amounts so this doesn't happen. This will also come with a "show all" option for the size picker. Feel free to scope that out as you should be able to apply those changes immediately - with no package update required.
