### ISSUE TITLE
Hidding Modal trigger button leaves an invisible button in markup

### ISSUE THREAD

**Issue by Uncle798** [skeletonlabs/skeleton#2944]
### Current Behavior

When not providing a `{#snippet trigger()}` there is an invisible button left in the markup

### Expected Behavior

There shouldn't be a button left in the markup if no `{#snippet trigger()}` is provided

### Steps To Reproduce

```svelte
<Modal
    bind:open={modalOpen}
    contentBase="card bg-surface-400-600 p-4 space-y-4 shadow-xl max-w-screen-sm"
    backdropClasses="backdrop-blur-sm"
>
    {#snippet content()}
       Some content.....
    {/snippet}
</Modal>
```

### More Information

https://discord.com/channels/1003691521280856084/1191790107867488316/1305590564497920010

**Comment by endigo9740** [comment]
Resolved by: https://github.com/skeletonlabs/skeleton/pull/2947
