### ISSUE TITLE
The React Navigation component show incorrect imports and component names

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2958]
### Link to the Page

https://next.skeleton.dev/docs/components/navigation/react

### Describe the Issue (screenshots encouraged!)

We've now standardized this component to be `<Navigation>` for both React and Svelte. However, the React docs still show `<Nav>`. The component itself is correct, only the documentation is out of date.

We need the following:

- Correct the imports per each example
- Correct any usage of the component
- Correct any reference to the old component name in the doc text

FYI I wouldn't mind a quick sweep of the Svelte version to double-check it's correct as well!

**Comment by phamduylong** [comment]
[Last I checked it was still named "Nav" in React](https://github.com/skeletonlabs/skeleton/blob/32c4c33a0411a90f869f2717cde1c4cfbb028c3c/packages/skeleton-react/src/lib/components/Navigation/Navigation.tsx#L240).  Am I missing something here?

**Comment by endigo9740** [comment]
Correct, both Svelte and React components should now match. Both should be `<Navigation>`. But only the Svelte docs were updated to reflect this. React still shows `<Nav>` for all the examples - which is incorrect:

![image](https://github.com/user-attachments/assets/4f01f29e-1d97-421b-a0cb-1145db0cf26e)

**Comment by phamduylong** [comment]
Do we change the export then? I'd think that makes more sense, something like 
```diff
- export const Nav = Object.assign(() => null, {
+ export const Navigation = Object.assign(() => null, {
	Rail: NavRail,
	Bar: NavBar,
	Tile: NavTile
});
```

then the import could be 

```diff
- import { Nav } from '@skeletonlabs/skeleton-react';
+ import { Navigation } from '@skeletonlabs/skeleton-react';
```

**Comment by endigo9740** [comment]
@phamduylong exactly. Anywhere this is referenced needed to be updated. So:

- The component export
- The `index.ts` file in skeleton-react, which controls the import
- Then all documentation examples (both import and usage on the page)

**Comment by phamduylong** [comment]
This can be closed.
