### ISSUE TITLE
bug: v3: Modal scrolling should be fixed. 

### ISSUE THREAD

**Issue by ddxv** [skeletonlabs/skeleton#2959]
### Current Behavior

![image](https://github.com/user-attachments/assets/e99045cc-d543-4ff4-a8ae-f31d7832d63c)

I had an overflow in X which caused the page's x and y to be too large. This meant that I could scroll to the bottom of the Modal Drawer as seen in the screenshot.

Chris asked for a quick bug report to check:

>  I might need to double check that we're using `fixed` styles over `absolute`.

Please let me know if there is anything further I can add!

**Comment by phamduylong** [comment]
[The example in the docs](https://next.skeleton.dev/docs/integrations/popover/svelte/#modal) uses h-screen, I assume this is why it doesn't take up all the height in the document. If the document body overflow is hidden this should work properly.

**Comment by endigo9740** [comment]
Ideally we would disable page scroll while this is active - in fact, that may be an option Zag provides. Barring that, we should probably switch to position `fixed` over `absolute`.

**Comment by phamduylong** [comment]
> Ideally we would disable page scroll while this is active - in fact, that may be an option Zag provides. Barring that, we should probably switch to position `fixed` over `absolute`.

Yeah the position was the first thing I checked, but it seems that the Modal is using `fixed` instead of `absolute`, so that might not be the cause.

**Comment by endigo9740** [comment]
@ddxv unfortunately I'm not sure enough information has been provided in your ticket for us to help diagnose your issue. To test the Drawer created a small sample project and implemented a Drawer modal per the [documentation instructions](https://next.skeleton.dev/docs/integrations/popover/svelte#modal). Here's the results:

https://github.com/user-attachments/assets/d0951224-e1e7-48e2-a0d8-9f5457ea1c1b

As you can see, the drawer appears over the page contents and spans the full page height. The only change I've made is to enable scrolling on the Drawer panel itself by appending `contentBase="... overflow-y-auto"`. You'll also note it's not technically possible to scroll the page while the Modal is open as it auto-hides the `<body>` scrollbar automatically - which is a typical a11y feature.

Here's the entire page source for reference if you would like to compare:

```html
<script lang="ts">
    import { Modal } from '@skeletonlabs/skeleton-svelte';

    let drawerState = $state(false);

    function drawerClose() {
        drawerState = false;
    }
</script>

<div class="p-10 space-y-10">
    <section>
        <Modal
            bind:open={drawerState}
            triggerBase="btn preset-tonal"
            contentBase="bg-surface-100-900 p-4 space-y-4 shadow-xl w-[480px] h-screen overflow-y-auto"
            positionerJustify="justify-start"
            positionerAlign=""
            positionerPadding=""
            transitionsPositionerIn={{ x: -480, duration: 200 }}
            transitionsPositionerOut={{ x: -480, duration: 200 }}
        >
            {#snippet trigger()}Open Drawer{/snippet}
            {#snippet content()}
                <header class="flex justify-between">
                    <h2 class="h2">Drawer Example</h2>
                </header>
                <article>
                    <p class="opacity-60">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, ab adipisci. Libero cumque sunt quis error veritatis amet, expedita
                    voluptatem. Quos repudiandae consequuntur voluptatem et dicta quas, reprehenderit velit excepturi?
                    </p>
                </article>
                <footer>
                    <button type="button" class="btn preset-filled" onclick={drawerClose}>Close Drawer</button>
                </footer>
                <section class="border border-green-500 h-[9999px] p-10">Force this section to scroll...</section>
            {/snippet}
        </Modal>
    </section>
    <header>
        <h1 class="h1">Hello World</h1>
        <p>Homepage is working.</p>
    </header>
    <section class="border border-green-500 h-[9999px] p-10">Force this section to scroll...</section>
</div>
```

The only thing I could think of here is you've adjusted the modal style props or added a wrapping element that wraps in some fashion. But without a minimal reproduction I'm afraid we can't really troubleshoot and further here.

I'm going to go ahead and close your issue here, and recommend you review how you've implemented this feature. If you can, however, provide a minimal reproduction. I'm more than happy to reopen and investigate that though.

**Comment by ddxv** [comment]
> @ddxv unfortunately I'm not sure enough information has been provided in your ticket for us to help diagnose your issue. To test the Drawer, I created a barebones Skeleton project and implemented a Drawer modal per the [documentation instructions](https://next.skeleton.dev/docs/integrations/popover/svelte#modal). Here's the results:
> Kapture.2024-12-09.at.15.08.56.mp4
> 
> As you can see, the drawer appears over the page contents and spans the full page height. The only change I've made is to enable scrolling on the Drawer panel itself by appending `contentBase="... overflow-y-auto"`. You'll also note it's not technically possible to scroll the page while the Modal is open as it auto-hides the `<body>` scrollbar automatically. Zag implements this for us as an a11y feature.
> 
> Here's the entire page source for reference if you would like to compare:
> 
> ```
> <script lang="ts">
>     import { Modal } from '@skeletonlabs/skeleton-svelte';
> 
>     let drawerState = $state(false);
> 
>     function drawerClose() {
>         drawerState = false;
>     }
> </script>
> 
> <div class="p-10 space-y-10">
>     <section>
>         <Modal
>             bind:open={drawerState}
>             triggerBase="btn preset-tonal"
>             contentBase="bg-surface-100-900 p-4 space-y-4 shadow-xl w-[480px] h-screen overflow-y-auto"
>             positionerJustify="justify-start"
>             positionerAlign=""
>             positionerPadding=""
>             transitionsPositionerIn={{ x: -480, duration: 200 }}
>             transitionsPositionerOut={{ x: -480, duration: 200 }}
>         >
>             {#snippet trigger()}Open Drawer{/snippet}
>             {#snippet content()}
>                 <header class="flex justify-between">
>                     <h2 class="h2">Drawer Example</h2>
>                 </header>
>                 <article>
>                     <p class="opacity-60">
>                     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, ab adipisci. Libero cumque sunt quis error veritatis amet, expedita
>                     voluptatem. Quos repudiandae consequuntur voluptatem et dicta quas, reprehenderit velit excepturi?
>                     </p>
>                 </article>
>                 <footer>
>                     <button type="button" class="btn preset-filled" onclick={drawerClose}>Close Drawer</button>
>                 </footer>
>                 <section class="border border-green-500 h-[9999px] p-10">Force this section to scroll...</section>
>             {/snippet}
>         </Modal>
>     </section>
>     <section>
>         <h1 class="h1">Hello World</h1>
>         <p>Homepage is working.</p>
>     </section>
>     <section class="border border-green-500 h-[9999px] p-10">Force this section to scroll...</section>
> </div>
> ```
> 
> The only thing I could think of here is you've adjusted the modal style props or added a wrapping element that scrolls in some undesired fashion. But without a minimal reproduction I'm afraid we can't really troubleshoot any further here.
> 
> I'm going to go ahead and close your issue here, and recommend you review how you've implemented this feature. If you can, however, provide a minimal reproduction, share it here, then I'm more than happy to reopen and investigate that though.
> 
> _EDIT_
> 
> Also here's the list of project dependencies from `pnpm list`. This shows what versions I'm actually running. If any of your Skeleton dependencies are outdated, you might consider updating to see if this helps.
> 
> ![Screenshot 2024-12-09 at 3 19 11 PM](https://private-user-images.githubusercontent.com/1509726/394014719-0d7e10ce-b399-4052-bd89-7cb938f54e00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3OTM1MTYsIm5iZiI6MTczMzc5MzIxNiwicGF0aCI6Ii8xNTA5NzI2LzM5NDAxNDcxOS0wZDdlMTBjZS1iMzk5LTQwNTItYmQ4OS03Y2I5MzhmNTRlMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTBUMDExMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWJjN2I5MjczNjdmZTYzNmRhNmMzNzIxYWRlMTQyZTZkMWJkNGRjZmI4N2Y5MDg5YTQ1OTZkMTM3ODUyMjdhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._5FP0kbS8hfHM6eUgreY9fTtU-JfSIDyR9UXoknsRkQ)

Oh thanks, no worries, Chris just asked me to make an issue incase it was something that should be fixed. I was able to 'fix' my issue by just not having text incorrectly scrolling off the page.

Just to be sure, I'll keep an eye out if I do it again then compare it to what you shared.

**Comment by endigo9740** [comment]
@ddxv this is Chris! :) Glad to hear you got it sorted. Let us know if we can help with anything else!
