### ISSUE TITLE
Combobox Submits Forms

### ISSUE THREAD

**Issue by MrVauxs** [skeletonlabs/skeleton#2962]
### Current Behavior

Combobox uses buttons (in comparison, [Zag seems to use list elements with listeners on them](https://zagjs.com/components/react/combobox#methods-and-properties)) which do not have the role of `button`, causing form submissions.

### Expected Behavior

Expected not to submit forms.

### More Information

Hugo confirming the issue on Discord: https://discord.com/channels/1003691521280856084/1191790107867488316/1303465018653937685

**Comment by phamduylong** [comment]
Looks like setting the button `type` attribute will do the trick here. I can't see that doing any harm. Can throw a PR if this is approved.

**Comment by endigo9740** [comment]
That was my expectation too. Go for it.
