### ISSUE TITLE
v3 Switch onCheckedChange e.target can't get the Object (just return undefined)

### ISSUE THREAD

**Issue by AI-Tipto** [skeletonlabs/skeleton#2971]
### Current Behavior

  <Switch name="is_wifi_scan_enable" bind:checked={is_wifi_scan_enable} onCheckedChange={(e)=>update(e.target, Flag.IS_WIFI_SCAN_ENABLE)}></Switch>

[svelte] state_snapshot_uncloneableThe following properties cannot be cloned with `$state.snapshot` — the return value contains the originals:- <value>.onCheckedChange

### More Information

Use sveltekit

**Comment by endigo9740** [comment]
I believe this may be a duplicate:

- https://github.com/skeletonlabs/skeleton/issues/2882
- https://github.com/skeletonlabs/skeleton/pull/2967
