### ISSUE TITLE
Tooltip affects width of trigger

### ISSUE THREAD

**Issue by sssilver** [skeletonlabs/skeleton#2988]
### Current Behavior

In skeleton v3, `<Tooltip>` appears to have no `class` attribute, making it difficult to control the width of the trigger that it wraps.

Since it's converted into what appears to be a `<span data-testid="tooltip">`, it ends up affecting the width of any block-level trigger elements it wraps: the trigger's `w-full` starts filling up the inline `<span>` rather than the actual container of the `<Tooltip>`.

Component not wrapped into a tooltip (intended width):
![image](https://github.com/user-attachments/assets/06536507-1e23-45a2-8d24-ec17782c4c0a)

Component wrapped into a tooltip (unintended, shorter width):
![image](https://github.com/user-attachments/assets/2b7ed3fe-66cb-4753-a6f3-339ecff467ee)

**Comment by endigo9740** [comment]
@sssilver it looks like there's an issue with our documentation tool that's not picking up the style property classes available to our popover features. There definitely is available classes. See the source here for a quick reference:

https://github.com/skeletonlabs/skeleton/blob/next/packages/skeleton-svelte/src/lib/components/Tooltip/Tooltip.svelte#L14

You would want to use `triggerClasses` in this case. By default the wrapping element is a `span`, which are inline. So you may want to set `block` like so:

```
triggerClasses="block"
```

We'll keep the ticket present until the documentation issue is resolved. Thanks.

**Comment by endigo9740** [comment]
@Hugos68 FYI - it looks like we have a gap in Necroparser.

**Comment by endigo9740** [comment]
My mistake, we need additional root element props available to the parent `<span>`. Without that, this change will not be possible.

Note to myself: let's investigate this for all four Svelte popover components.

**Comment by Hugos68** [comment]
Why not remove it? 🤔 The span doesn't seem to do anything

**Comment by endigo9740** [comment]
@Hugos68 I think we covered this on Discord - but just for the record, the wrapping parent element removes the trigger/popover from the flow of the DOM. So if you have `space-y-4` this doesn't affect the these elements. They remain relative to one another.

**Comment by endigo9740** [comment]
@sssilver FYI I've made a similar change to the props here where I've added `base` and `classes` to the root element for the Svelte Popover, Tooltip, and Modal components. The Combobox component already had these.

See: #3031
