### ISSUE TITLE
Opening the example Modal has sourcemap warning on next.skeleton.dev

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#2990]
### Current Behavior

Opening the example Modal has sourcemap warning on next.skeleton.dev, but only in Firefox

### Expected Behavior

No Sourcemap Warning

### Steps To Reproduce

https://next.skeleton.dev/docs/integrations/popover/svelte/#modal

### Link to Reproduction / Stackblitz

https://next.skeleton.dev/docs/integrations/popover/svelte/#modal

### More Information

It also appears to happen in user apps.

Error: Attempt to postMessage on disconnected port undefined

Source map error: Error: URL constructor:  is not a valid URL.
Resource URL: wasm:https://next.skeleton.dev/pagefind/pagefind.js
%20line%201%20%3E%20WebAssembly.instantiate
Source Map URL: null

**Comment by endigo9740** [comment]
Hugo reviewed this and stated it's a warning in our doc site related to a missing source map. But this won't be available for Pagefind. This shouldn't cause any harm, so we'll go ahead and close this out as there's nothing actionable on our end.
