### ISSUE TITLE
Option to hide Progress Ring label

### ISSUE THREAD

**Issue by knd775** [skeletonlabs/skeleton#2992]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

This is especially important for small rings where a label cannot fit.

### What type of pull request would this be?

Enhancement

**Comment by phamduylong** [comment]
I might have misunderstood here but isn't there a `labelClasses` prop for Progress Ring? Could that be used to not display the label?

**Comment by knd775** [comment]
You can, that's what I'm doing currently. I'm really not a fan of using css to hide things in svelte when we can remove it from the dom entirely.

**Comment by phamduylong** [comment]
I can cook a PR if the team agrees with this direction. Without looking at the code, most likely a boolean props will do.

**Comment by endigo9740** [comment]
@phamduylong go for it.

We tend to favor style props for manipulating the look and feel of components, but in this case we have a fairly opinionated default - which includes the auto-generated label. So I'm open to an exception here to use a prop to modify this behavior. Something like `hideLabel: boolean` would be fine.

**Comment by phamduylong** [comment]
This can be closed.
