### ISSUE TITLE
[v3] Avatar Fallback mistakenly displayed as soon `w-` is used as sizing class

### ISSUE THREAD

**Issue by mmailaender** [skeletonlabs/skeleton#3003]
### Current Behavior

```
<Avatar src={'/favicon.png'} name="Micha" />
``` 
=> Works as expected
![image](https://github.com/user-attachments/assets/b8e3cc9b-3a4e-495a-9133-e3b9955346d5)

But as soon as I add as size class `w-` the fallback appears:
```
<Avatar src={'/favicon.png'} name="Micha" size="w-10"/>
``` 
![image](https://github.com/user-attachments/assets/2eb3456b-ef90-4d05-bac5-84f85d1ca89d)

Using `size-` bypasses the problem, but I think it would be overall better if the fallback would be really hidden, but somehow it isn't
![image](https://github.com/user-attachments/assets/d3a8ccb6-ae62-4ab9-9525-07fe501df0eb)

**Comment by phamduylong** [comment]
What if you put w-10 in `imageClasses` rather than `size`? Seems like `size` gets angry when you put arbitrary values into it.

**Comment by phamduylong** [comment]
Code looks like this:
```svelte
<figure {...api.getRootProps()} class="{base} {background} {size} {font} {border} {rounded} {shadow} {classes}" data-testid="avatar">
	<!-- Image -->
	{#if src || srcset}
		<img
			{...api.getImageProps()}
			{src}
			{srcset}
			alt={name}
			class="{imageBase} {imageClasses}"
			style:filter={filter && `url(${filter})`}
			data-testid="avatar-image"
		/>
	{/if}
	<!-- Fallback -->
	<span {...api.getFallbackProps()} class="{fallbackBase} {fallbackClasses}" data-testid="avatar-fallback">
		{#if children}
			{@render children()}
		{:else}
			{getInitials(name)}
		{/if}
	</span>
</figure>
```

Do we need an else for the fallback to be displayed?

**Comment by endigo9740** [comment]
@mmailaender 

This is expected, the size property requires `size` classes:

- https://next.skeleton.dev/docs/components/avatar/svelte/#api-reference
- https://tailwindcss.com/docs/size

These work similar to width/height, except it sets both evenly.

**Comment by endigo9740** [comment]
@phamduylong afaik there's no change needed. Just user error here. If someone can show otherwise we can reopen this ticket.
