### ISSUE TITLE
Button with icon - the gap is too big

### ISSUE THREAD

**Issue by completer** [skeletonlabs/skeleton#3052]
### Current Behavior

Using default recommended Lucide icons and Cerberus theme in Skeleton 3.0.0-next.9. The gap between the icon and the text is too big.

<img width="421" alt="image" src="https://github.com/user-attachments/assets/f97809b5-609f-4a09-93f8-53df7dbaceb1" />

This looks bad.

### Expected Behavior

 The gap between the icon and the text should appear to be the same as the gap between the icon and edge of the button, or perhaps slightly smaller -- but not bigger. 

### Steps To Reproduce

Install Lucide and make a button or anchor link with an Icon:

    import { Mail } from 'lucide-svelte';
    <a class="preset-filled-secondary-500 btn btn-lg" href="mailto:me@example.com"><Mail />Send email</a>

**Comment by endigo9740** [comment]
@completer everyone is entitled to their opinion when it comes to design, but these are just our defaults. Definitely not a 
bug. If you wish to change this you can, the style source is linked on every documentation page. For this, you would want to adjust the `gap` size:

https://github.com/skeletonlabs/skeleton/blob/next/packages/skeleton/src/plugin/components/buttons.css#L6

You can do this in your global stylesheet like so:

```css
.btn { @apply gap-2; }
```
