### ISSUE TITLE
Form input validation (V3 documentation)

### ISSUE THREAD

**Issue by P1llus** [skeletonlabs/skeleton#3057]
Was asked to add in a enhancement request on documentation from discord.

While it was clear that v2 and v3 was not going to be 1:1, which is totally fine, I did miss some note on exactly how it is expected we add form validation colors (success,warn,error).

In V2 this existed, though as a separate class, `input-success` etc while it seems we are expected to use `presets` in v3.

I did not manage to get it to look as nicely as before, as usually it can affect both bg, text and border colors in some way. Would be nice to either get a class for it in the future.

However the purpose of this issue was to track a pointer to presets in the docs for forms, or maybe an example of how presets should be used to affect the input fields in the proper way.

Example on the specific I believe most people would expect: https://tailwindcss.com/docs/hover-focus-and-other-states#form-states

**Comment by endigo9740** [comment]
Folding this under a larger content-focused update: https://github.com/skeletonlabs/skeleton/issues/2900

**Comment by PerchunPak** [comment]
This is still not implemented, @endigo9740 could you reopen this please?

**Comment by endigo9740** [comment]
@PerchunPak form states are no longer part of Skeleton itself, but rather we provide guidance for users to implement this yourself. See the docs here.

https://next.skeleton.dev/docs/design/presets#create-a-preset

It's a very small add and allows users to have better control over the display.

**Comment by PerchunPak** [comment]
It wasn't very obvious how to properly implement color hinting for an invalid form - `invalid:ring-error-500`. Would be great if skeleton implemented this, as it is something that I expect library to implement, not me.

It would as easy as

```css
.input:invalid {
  @apply ring-error-500;
}
```
in `packages/skeleton/src/plugin/components/forms.css`
