### ISSUE TITLE
Necroparser API Reference description missing for some component properties

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#3058]
I'm not sure what the pattern is yet, but select descriptions are missing for a number of components:

![Screenshot 2024-12-17 at 2 32 33 PM](https://github.com/user-attachments/assets/6fbabab7-b740-43ff-8575-057306e7cf22)

We've recently updated our dependencies, including some for Zag and Necroparser, so probably worth reviewing this as a regression.

@Hugos68 we don't have to have this for tomorrow's Release Candidate, but we should aim to patch this asap.

**Comment by Hugos68** [comment]
![image](https://github.com/user-attachments/assets/c649e2aa-a0c0-4e62-bedd-3e102f8359e6)
Comments are set in correctly
```js
// This is a comment
```
```js
/** This is a JSDoc comment */
```
The necroparser ignores normal comments and only grabs JSDoc comments

**Comment by endigo9740** [comment]
Yep Long figured it out, it's my bad! He's got a pending PR that will address these and I'll do another audit and pass tomorrow to ensure we didn't miss any others. Thanks!
