### ISSUE TITLE
Pagination not rendering

### ISSUE THREAD

**Issue by s-petey** [skeletonlabs/skeleton#3066]
### Current Behavior

When attempting to render the server paginated result the `<Pagination>` component will not render.

### Expected Behavior

The component should render and allow redirecting to the same page to update query parameters.

### Steps To Reproduce

1. Loading data from the server file
2. Render Pagination component
3. Pass the props

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/sveltejs-kit-template-default-ypuim7rx?file=src%2Froutes%2Flinks%2F%2Bpage.svelte

**Comment by endigo9740** [comment]
Just noting that this is for Skeleton v3, as that was not stated in the post.

@phamduylong this may be worth following to up to ensure it's not an overlapping issue with:

- https://github.com/skeletonlabs/skeleton/issues/3064

**Comment by s-petey** [comment]
I'm not certain, but maybe it is simply that if there is no pagination needed it will not render it at all? Testing when there is a limit that is larger than the number of items in the data it was not rendering.

**Comment by endigo9740** [comment]
@s-petey correct, I do believe how that's setup. Maybe that's what you're seeing here?

**Comment by s-petey** [comment]
Playing with the stackblitz above this does seem to be the case. Would modifying the readme to include a description around this may help ease confusion?

> The pagination component will not be rendered if the `count` does not exceed the `data` length.

I do not know how truthy my write up above is though.

**Comment by endigo9740** [comment]
@s-petey could be. This behavior mimics that of Zag, which these components are built on top of, so I didn't consider that originally. I'd welcome a request to update the documentation. I'm out of office until next week, so don't expect that change until then at the earliest
