### ISSUE TITLE
Doc Site SEO + Open Graph

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#355]
As we prep for the v1 launch we need to revisit the following:

1. SEO / [Metatags](https://github.com/oekazuma/svelte-meta-tags) - ensure we're well optimized for search
2. Implement Open Graph data - consider using [Vercel's Satori tool](https://github.com/vercel/satori)
3. Revisit our blog SEO/Open graph, as Ghost provides some of this turnkey.

@niktek I welcome your support on this one as well!

**Comment by endigo9740** [comment]
https://twitter.com/geoffrich_/status/1580954774434119680

**Comment by niktek** [comment]
Just doing some background research and came across this component for handling metadata in svelte:
https://github.com/oekazuma/svelte-meta-tags

Seems to be recently updated too

**Comment by ak4zh** [comment]
Here's svelte equivalent of vercel-og using satori:
https://github.com/etherCorps/sveltekit-og

**Comment by endigo9740** [comment]
FYI I've tagged myself and Nik since we will need to be involved with this, but I do welcome help from anyone wiling and able to implement the changes in the codebase. Thanks!

**Comment by endigo9740** [comment]
https://www.ogimage.gallery/

**Comment by endigo9740** [comment]
Reference: https://kit.svelte.dev/docs/seo#manual-setup-title-and-meta

**Comment by endigo9740** [comment]
A PR is now available and ready to test here:


Unfortunately it wasn't as trivial as I'd hoped. But here's what the "before" looked like with meta tag tools like:
https://metatags.io/

![image](https://user-images.githubusercontent.com/1509726/212426554-fac1306c-74c8-4b16-9307-4bdcd4451e8a.png)

Then after:

https://cdn.discordapp.com/attachments/1003699523522142399/1063548144538898483/Screen_Shot_2023-01-13_at_1.57.31_PM.png

https://cdn.discordapp.com/attachments/1003699523522142399/1063548144928952400/Screen_Shot_2023-01-13_at_1.57.38_PM.png

However I am getting one odd issue - when testing directly on Twitter, I get inconsistent results.

- For the homepage, the open graph data never appears. Though it's very clearly set.
- For article pages, it never works the first time, but when deleting and paste the URL again it appears

I'm going to chalk up that latter issue to Twitter bugs, but I'm not quite certain why the homepage isn't working

![image](https://user-images.githubusercontent.com/1509726/212426750-ad7feea9-ef8c-4c73-a89b-7a6bf88d55c2.png)

![image](https://user-images.githubusercontent.com/1509726/212426765-7722e1cd-5b2f-448f-abaf-1a99a1ef90d9.png)


I suppose an important detail here is I've had to dramatically change where and how meta tags are rendered. Originally they were set in `app.html` which of course carries through the entire site. Then on a blog article page I'd use `<svelte:head>` to "overwrite" these. Turns out that does work - we end up with duplicate tags. So instead I've followed SvelteKit's advice here regarding `$page.data`:
https://kit.svelte.dev/docs/seo#manual-setup

![image](https://user-images.githubusercontent.com/1509726/212426819-ba7f0d28-8220-40e3-a99f-6f47c23072e3.png)

Now all meta data is set in a `<svelte:head>` element in the root layout. This appears to work in most regards - but I worry this may be the cause of our Twitter issue. If anyone has any ideas I'm all ears. The PR here is here:
https://github.com/skeletonlabs/skeleton/pull/822
