### ISSUE TITLE
Improve events and documentation

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#389]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

This will be a larger scale audit and update, but most components include little to no event bubbling (reading: passing the event up to the component definition). This leaves users to guess or review the source code to know what events are present and available.

The new doc format provides a dedicated tab for Events, so we should look to update each component and document accordingly.

### What type of pull request would this be?

Documentation

### Any links to similar examples or other references we should review?

The SlideToggle component is one that has a lot of events set to bubble. By tapping the Label element the expected event bubbles. Unfortunately these events not currently documented, which illustrates my point.

**Comment by endigo9740** [comment]
Given Sveld can handle events, this should occur after the auto-doc updates.

**Comment by endigo9740** [comment]
Stepper: add `on:next` event. Document missing `on:complete` event

**Comment by Moosieus** [comment]
Paginator component's `on:amount` event doesn't emit the proper amount/page size. To reproduce:
1. Go to [https://www.skeleton.dev/components/paginators](https://www.skeleton.dev/components/paginators)
2. Inspect element anywhere on page and open the JavaScript console
3. Toggle the example paginator's amount
4. Note the resulting `console.log` statement always prints `0` despite the changed page size

**Comment by endigo9740** [comment]
@Moosieus the reported issue will be resolved as part of the incoming PR. Very simple to fix, just wasn't passing the correct data point.
