### ISSUE TITLE
Option to make Steps in Stepper clickable

### ISSUE THREAD

**Issue by pietz** [skeletonlabs/skeleton#408]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It would be nice if I could navigate through Steps in the Stepper component by clicking on their name/number. You could introduce a new setting to activate this behaviour with the options: enabled, disabled and unlocked.

unlocked (as the name suggests) would only allow to click on Steps that have already been completed or is currently active.

**Comment by endigo9740** [comment]
Hi @pietz, this is a request that has come up before. I'd recommend reading the conversation here:
https://github.com/Brain-Bones/skeleton/issues/332

Unfortunately this is not something I can make a priority right now. If it's something you and others feel is valuable then a PR would be welcome.

To anyone that is interested in doing this, I came across this progress stepper build by Geoff Rich. A very talented Svelte developer:
https://geoffrich.net/posts/progress-stepper/

I think there's some lessons to learn from his approach to building this. So I'd recommend making reference to this if you opt to rework the component.

**Comment by endigo9740** [comment]
FYI I've put out a call in the #contributor channel on Discord to see if anyone would be willing to help with this.

**Comment by bennymi** [comment]
@endigo9740 I could have a look at this one

**Comment by endigo9740** [comment]
@bennymi You can, obviously all work is volunteer here. But as far as priority goes this is VERY low.

More critical items would include:

- https://github.com/skeletonlabs/skeleton/issues/516
- https://github.com/skeletonlabs/skeleton/issues/389
- https://github.com/skeletonlabs/skeleton/issues/598

Basically look for items with the `v1.0` milestone and `help wanted`. Those are the priority items. Thanks!
