### ISSUE TITLE
Make tabs in Docs sticky

### ISSUE THREAD

**Issue by ryceg** [skeletonlabs/skeleton#442]
### Describe the Issue

For vertically extensive components, it might be good to make them sticky- it's always a pain to have to scroll back up to tab over to the Props page.

### Are you able to create a Pull Request with the fix?

Yes

**Comment by endigo9740** [comment]
Yeah the current UI is pure utilitarian. I have some ideas to make it fancy! Perhaps as part of: https://github.com/Brain-Bones/skeleton/issues/374

**Comment by endigo9740** [comment]
I think for now I'm going to close this out. The docs will be due a visual overhaul pre-launch, but I'll tackle that as a more comprehensive pass. Thanks for the suggestion, we definitely need something like this!
