### ISSUE TITLE
i18n - remove hardcoded text within components

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#465]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Let's audit and review what components have fixed text within them. Off the top of my head this includes, but is not limited to:

- dialogs
- toasts (dismiss button)
- stepper (next/complete buttons)

This will allow support for non-English languages.

### What type of pull request would this be?

Enhancement

**Comment by moshe5745** [comment]
There is hardcoded text in FileDropZone ether.

I can try to PR this. 
But I need to understand where the text will come from.

**Comment by endigo9740** [comment]
@moshe5745 Hey, yeah the default value is in English, but the entire contents are replaceable. So it's kind of yes and no on this one. So technically this is already possible to replace.

![Screen Shot 2022-11-13 at 1 21 39 PM](https://user-images.githubusercontent.com/1509726/201540142-43b5efac-90d1-4809-a383-22b1bd91c031.png)

**Comment by moshe5745** [comment]
What about the Paginator? (I updated the original comment)

**Comment by endigo9740** [comment]
Funny enough @ryceg and I were just talking about that. See our conversation in his first response here:
https://github.com/Brain-Bones/skeleton/pull/520

This is a likely candidate for change. The Paginator itself needs a bit of a design update, so I might knock this out along side that.

**Comment by moshe5745** [comment]
Ok, but how would you prefer the text "injection"? Props or slots?

**Comment by moshe5745** [comment]
This is the only hard-coded text I found in the dialog:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/7037149/201540666-58faddb2-7424-4cdc-a9b4-bdb41155425b.png">

Interesting what is the best practice for this?

Because it seems a little funny for the developer to enter "Dialog" in the local language.

**Comment by endigo9740** [comment]
@moshe5745 Honestly Mosh this ticket might best left to me. That or at least just give me an opportunity to do a proper audit through each and all features in Skeleton to identify what needs to be changed. That probably won't make it into this release as I'm actively working to complete updates to the dialog/toast/table refactors. But may be something I can get to soon.

**Comment by endigo9740** [comment]
I've completed a final audit of our library, looking for additional instances that might need to be changed. I think with the recent update to Toasts/Drawers we're now good. We'll keep this approach in mind for future components, but I think for now we're good here. Still LOTS to do on the i18n front, but this is a good first step.
