### ISSUE TITLE
New Component: Message Stream

### ISSUE THREAD

**Issue by leranjun** [skeletonlabs/skeleton#469]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Would be good to have a component that looks like a chat/log/event stream with timestamps, icons, etc, something like a terminal console or an IRC client. e.g. Discord's compact mode:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/25704248/198878359-c683a617-4bf3-4e4b-8a61-287e426859fc.png">

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

Haven't found a good UI lib example yet, will keep looking.

Right now I'm trying to implement using a plain list. I'll post a screenshot once I'm finished.

**Comment by leranjun** [comment]
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/25704248/198929694-f36f8e48-2c27-4830-92f5-d6cb90b1ca44.png">

Absolutely terrible mockup and colour choice, but basically something like this.

**Comment by endigo9740** [comment]
Thanks @leranjun. This is definitely something I'm interested in creating at some point. I like the idea of these odd non-standard components. I'm on Twitch and YouTube Live all the time, so I know we can draw some inspiration for what they're doing.

**Comment by leranjun** [comment]
Good point! Livestream chats could be a good ref.

**Comment by leranjun** [comment]
Something I found similar to this: https://dribbble.com/shots/18260734-Cards-Event-Log

**Comment by endigo9740** [comment]
@leranjun I'm sorry it's taken me so long to be back to this issue, but I misunderstood the original intention of this. I was under the impression you were looking for something closer to a chat log. There's been a solution available for this all the time - the list element!

```html
<div class="w-full text-token card p-4 space-y-4">
	<ol class="list">
		{#each listData as v, i}
			<li>
				<small>Jan 05 01:15</small>
				<i class="fa-solid fa-credit-card text-xs" />
				<span>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</span>
			</li>
		{/each}
	</ol>
</div>
```

![Screenshot 2023-04-21 at 4 22 42 PM](https://user-images.githubusercontent.com/1509726/233736999-251083eb-8698-408d-ba88-d9fdd7327418.png)

Obviously you may wish to adjust and customize this a bit further, but this should offer what you're looking for. You might just make considerations for setting a set width for the items within the `<li>`, but it naturally accepts multiple elements as a column per row.

FYI I do have need of a proper chat-style UI (ex: Twitch chat), so I'll open a new ticket that will cover this. I'll be prioritizing this as part of the next release of Skeleton as we have need for it in an upcoming Skeleton Labs project.
