### ISSUE TITLE
Tutorial for Responsive Sidebar when using AppShell

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#496]
### Describe the Issue

Look into creating a clear and simple version of wiring up AppShell, Drawer, SideRail and a simple nav so that people can get a responsive starting shell to help them on their way.

**Comment by endigo9740** [comment]
@niktek I think I'd like this to be a post on our new blog. Maybe the first after the initial "hey we have a new blog" post.

**Comment by endigo9740** [comment]
https://dev.skeleton.dev/blog/how-to-implement-a-responsive-sidebar-drawer

**Comment by M4rk3tt0** [comment]
Hi, I follewed the tutorial and everything is working great, except for one thing.

I added the code to highlight the menu item corresponding to the current url and it works with the navigation in the the Sidebar, but it has a weird behaviour inside the drawer.

The first menu item gets highlighted too, whatever it is. If i try to inspect the item the highlight disappears as shown below.

![Drawer-1](https://user-images.githubusercontent.com/7859305/233775677-ba7714d0-58b9-4dc6-b501-8c64bacee328.gif)

It's weird beacuse sidebar and drawer share the same Navigation component as in the tutorial.

In the next gif you can see how closing the inspection window makes the first menu item flicker. It turns off for a moment and then it turns on again.

![Drawer-2](https://user-images.githubusercontent.com/7859305/233775995-d6be3b34-3e4b-4b82-b581-644b4f631806.gif)

What could the problem be?

**Comment by endigo9740** [comment]
@M4rk3tt0 please don't comment on long closed tickets. This is easy to miss.

Your issue is related to the initial focus state mentioned in this ticket, which will be addressed soon:
https://github.com/skeletonlabs/skeleton/issues/1345
