### ISSUE TITLE
New Component: Bottom Bar - bottom navigation panel

### ISSUE THREAD

**Issue by ak4zh** [skeletonlabs/skeleton#500]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

An iOS like bottom Tabbar for easier navigation on smaller screens which has the option to be moved to top or convert to vertical on large screens.

Something like:
`tabbar md:top-tabbar lg:left-side-tabbar`

### Any links to similar examples or other references we should review?

https://konstaui.com/svelte/tabbar

**Comment by endigo9740** [comment]
Closing this ticket in favor of a more detailed spec here:
- https://github.com/skeletonlabs/skeleton/issues/790
