### ISSUE TITLE
Data Table feature

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#538]
> **Warning**
> This feature is currently delisted per: https://github.com/skeletonlabs/skeleton/issues/930. It will return in the future, but no ETA has been provided yet.
> We are accepting recommendations for alternatives here: https://github.com/skeletonlabs/skeleton/issues/821

---

### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Here's a running list of features and improvements we would like to added to data tables going forward.

- [ ] Review options to sanitize data table content  (missing object keys should be set to `undefined`)
- [ ] Review options to add row selection in addition to cell selection for tableA11y action
- [ ] Evaluate the use of `role="gridcell"` for a11y keyboard interaction. Goes against ARIA guidelines.
- [ ] Consider adding search whitelist, to limit search certain fields
- [ ] Allowing specifying the default sort on load (runs + UI arrow added)
- [ ] Quick mapping of available columns (to add/remove columns on demand)
- [ ] Consider adding [3-stage checkbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes) for select all, including: current page, all results, no results ([Tailwind selector](https://tailwindcss.com/docs/hover-focus-and-other-states#indeterminate))
- [ ] Sticky header: https://twitter.com/CodyWebHouse/status/1592907092226060288
- [ ] Consider support for sorting complex cell data (ex: objects, arrays, etc)

Known Issues:

- Search + Pagination are not working as expected

### What libraries have been reviewed

* [Tanstack](https://github.com/olifolkerd/tabulator) - not recommended, documentation is poor
* [Tabulator](https://tabulator.info/) - data-driven, does not allow for template manipulation
* [Svelte-Headless-Tables](https://github.com/bryanmylee/svelte-headless-table) - documentation has gaps, poor accessibility
* [Svelte Simple Datatables](https://github.com/vincjo/datatables) - recommended, but have not extensively tested extensively

**Comment by endigo9740** [comment]
NOTE: additional suggestions are welcome here!

**Comment by ak4zh** [comment]
Add row grouping
https://datatables.net/examples/advanced_init/row_grouping.html

**Comment by younesk31** [comment]
A more convenient current page selection, since if the table has multiple pages its less suitable to use the arrows alone
[Example](https://svelte.dev/repl/3238e5737f764431a26e243800dccc6d?version=3.16.4)

**Comment by AdrianGonz97** [comment]
Need to fix data table searches #613

**Comment by endigo9740** [comment]
@AdrianGonz97 this may be worth a look:
https://svelte-headless-table.bryanmylee.com/

**Comment by KevM** [comment]
Any chance you are looking at multi-column sorting? Enterprise-y apps use it a lot.

**Comment by endigo9740** [comment]
@KevM Truthfully with today's update we've changed the status of data tables to "experimental", meaning it exists and is available to use, but is not recommended for production use. Going forward, this will not be a priority leading up to v1.0, and I suspect a lot of work will continue through and after the v1.0 of the core library.

The choice is simple, either I can devote the majority of my time to building the data tables (a "single" feature), or I can devote it to finishing the items on our roadmap here:
https://github.com/skeletonlabs/skeleton/discussions/503

That said, @AdrianGonz97 and other contributors are welcome to jump in and help flush things out. But it'll be a mostly voluntary effort until the Skeleton foundation is established. In the meantime we welcome additional suggestions and feedback, but I do ask folks keep expectations within reason given everything mentioned above.

**Comment by KevM** [comment]
Ok. I'm a little bummed to get a nice update (0.8.3) for data tables and then to hear they have been put on the back burner. I understand the reason to focus on 1.0 first. I will continue to use Skeleton's experimental data tables until I have pain. I will move to [svelte-headless-table](https://github.com/bryanmylee/svelte-headless-table) when I run into problems.

**Comment by endigo9740** [comment]
Totally understand, just want to set realistic expectations! Right now I'm the only person contributing full time (plus), so we gotta do our best to prioritize. That said, data tables are an important feature and I want an effective in-house solution. So it's just a matter of time before we return to this.

I've been thinking we may put more time and effort into single but larger scale features like this, date/time pickers, etc post launch though. When we can devote more bandwidth.

In the meantime, I definitely want to encourage folks to jump in and contribute. I know we all want everything right now, but one step in front of the other as they say! Also as far as I'm aware @AdrianGonz97 may return to the above features after we get the Tailwind Intellsense and CSS tree shaking working as needed. Those items are more crucial, but perhaps we can twist his arm :)

**Comment by AdrianGonz97** [comment]
BUG:  Search doesn't work while a sort is active (when you see the arrow pointing up or down in the table headers)

**Comment by thdoan** [comment]
One thing I'd like to see is when you sort a column, the column width shouldn't shift. The experience should be more or less like the data table here (last example): https://sveltematerialui.com/demo/data-table/

**Comment by Rar9** [comment]
Select ALL should only apply for the visible content l.

**Comment by PabloRuizCuevas** [comment]
> Select ALL should only apply for the visible content.

I disagree, select ALL means ALL, not "only visible".

**Comment by AVaunt-consulting** [comment]
It would be great to have resizeable columns and/or the option to shorten the table cell contents for large strings. 
For example shortening a really long string into the first 10 characters + ellipsis (...)
![image](https://user-images.githubusercontent.com/12223621/212684431-60cd7e46-b5c9-4bb3-ac1f-a41017e6da8b.png)

**Comment by AVaunt-consulting** [comment]
Pagination buttons are a bit funky for wide tables. The will go inline once the columns fit the table contents and column headers.
![image](https://user-images.githubusercontent.com/12223621/212685148-491f6783-da5a-40c5-a9f6-9577c1e6406b.png)

**Comment by maxwelldlehmann** [comment]
I think that select all should select all active(?) rows, not just in view, but do omit rows that have been filtered out. 
For example, if you were to filter/search down to certain criteria then you could select all before taking action.
For example, say you had a table of animals and you wanted to export all the mammals. You could filter for "mammals", "select all" then export selected.

It would also be nice to see how many things were filtered out. i.e. `Filter results 157 / 739`

**Comment by endigo9740** [comment]
Folks, we cover the selection in the original post above. See:

> Consider adding [3-stage checkbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes) for select all, including: current page, all results, no results

By using a three stage checkbox we can handle select current page, select all, or select none.

Per @maxwelldlehmann suggestion above, I agree that only filtered results should be selected though, regardless of which page they reside.

**Comment by piperun** [comment]
I think server-side support would be great!

In general, a very good library to use as a reference on all the possible features is:
https://github.com/olifolkerd/tabulator
Some that would be nice is:
- filters (with custom filter)
- formatters (with custom formatter)
- Nested layout

**Comment by endigo9740** [comment]
> I think server-side support would be great!

Server side support is already there. Just use server side features in place of the ones presented here. Most features are opt-in.

- The pagination provides event handlers for changes.
- Search would be something you implement yourself (custom search plus HTTP trigger; then update data)
- Add your own `on:click` handers for table sort

FYI the example on the documentation page uses data from JSON Placeholder. It's remote data we fetch, not locally saved. Check the `page.ts` to see how we're fetching the data and passing it to the route template:
https://github.com/skeletonlabs/skeleton/tree/master/src/routes/(inner)/utilities/data-tables

**Comment by younesk31** [comment]
Expandable table rows 

[Example](https://codepen.io/jopico/pen/kyRprJ)

**Comment by piperun** [comment]
Another thing that would be nice to have is an internal `rowId` or `index` (in case you need to a more static/immutable index), 
essentially:

```javascript
[
    {
    name: 'Steve',
    index: 1
    },
    
    {
    name: 'Amanda',
    index: 2
    },
    {
    name: 'Kim',
    index: 3
    },
]
```
After the user sorts the table by alphabetic order (we can still know which row is which): 
```javascript
[
    
    {
    name: 'Kim',
    index:3
    },
    {
    name: 'Amanda',
    index: 2
    },
    {
    name: 'Steve',
    index: 1
    },
    
]
```

It's something almost every data table framework has, tabulator, ag-grid, tanstack tables and headless-table svelte has this backed in.

**Comment by piperun** [comment]
in `DataTable.ts` you can add the internal `rowId` functionality at line 29:
`return { ...row, rowId: i, dataTableChecked: model.base[i]?.dataTableChecked ?? false };`.
From my testing it seem to work without any hiccups.

**Comment by riziles** [comment]
I think one of the best fully open source libraries I've seen is [Tabulator](https://tabulator.info/). I'm not suggesting it should be fully integrated into Skeleton, but it has a ton of great features to look at, and I was able to deploy a simple example into Skeleton pretty easily: repo: <https://github.com/riziles/skeleton-glitch> , example: <https://flourishing-hotteok-608239.netlify.app/>

**Comment by endigo9740** [comment]
I keep hearing about Tabular. It's at the top of my list to review as I get a chance. Thanks for the suggestion!

**Comment by Rar9** [comment]
Tanstack table is also a great alternative

**Comment by riziles** [comment]
> Tanstack table is also a great alternative

wow. those guys take the term "unstyled" very seriously.

**Comment by endigo9740** [comment]
Hey everyone, given the number comments on this ticket, I thought I'd give you a heads up about a change to the data tables feature. As of tomorrow's release we're delisting the data table feature from our documentation. This means it won't be available as part of the standard navigation in the docs, but will still functionally be part of the library.

- https://github.com/skeletonlabs/skeleton/issues/930

If you are using data tables in your project and need to reference the data table documentation, it can be found here:
https://www.skeleton.dev/utilities/data-tables

To provide an explination - we've had the feature marked "experimental" and noted it was NOT ready for production since launch. But even with this, most folks tend to skim past that and implement it in their production applications. We've received a LARGE number of support tickets both on GitHub and Discord.

Typically this would encourage this type of feedback, but unfortunately we just don't have the time or support team to maintain this feature in it's current state. Given this, we do recommend that you migrate to an alternative at your earliest convenience. We will be taking a hard stance that this is "use as your own risk". No direct support will be provided for now.

Note that we DO intend to flushed out and complete the data table features in the future, but we have no ETA for this at the moment. We're coming up on our release candidate status for the project, which is part of what's encouraging this decision. The data table just does meet our standards of quality. We would rather NOT include it, than include something we feel is subpar.

That said, if you're interested in contributing to the feature and helping build out the feature, we would gladly accept a number of volunteers. That's what open source is all about, right? If you're willing to help, please reach out here or on Discord.

Thanks you for your understanding.

**Comment by endigo9740** [comment]
Here's a wonderful resource for data tables. I'd very much like to reference this when we return to our own iteration:
https://pencilandpaper.io/articles/ux-pattern-analysis-enterprise-data-tables/

**Comment by riziles** [comment]
@endigo9740 ,

Just another entry in the list of third part data table repos: <https://github.com/vincjo/datatables>

It's built for Svelte, very headless and seems to be very much compatible with the existing Skeleton table classes. It adds a search bar, sorters and filters.

I dropped it in to my Skeleton playground and it seems to play nicely:
<https://flourishing-hotteok-608239.netlify.app/ssd>

**Comment by endigo9740** [comment]
I've been eyeing that one as well. As soon as I have the bandwidth I'll put it through it's paces!

**Comment by riziles** [comment]
> > @endigo9740 ,
> > Just another entry in the list of third party data table repos: https://github.com/vincjo/datatables
> 
> This is actually a near perfect replacement, at least for us. The only thing missing is row selection handling, but that's not too hard to implement ourselves.

They actually just added a bunch of functionality. It seems to be in active development, so it might be on the horizon.

**Comment by knd775** [comment]
> I've asked the maintainer if it's possible to add some of those features (selection & rowId).

Yep, my main issue is that it uses a pretty rigid readable store, so you can't add your own `checked` or `selected` properties to then bind to a checkbox. If the store wasn't readonly, it would be much simpler to implement a lot of this on your own.

**Comment by riziles** [comment]
> Yep, my main issue is that it uses a pretty rigid readable store, so you can't add your own `checked` or `selected` properties to then bind to a checkbox. If the store wasn't readonly, it would be much simpler to implement a lot of this on your own.

@knd775 , can I post an issue in their repo and link to this comment? She (he?) would probably appreciate the feedback.

**Comment by ch-lukas** [comment]
Adding to the feature list & suggestions. For enterprise apps and ones with a lot of backend administrative capabilities I would say dataTables and forms are the 2 must have components. However these orgs tend to have a lot of data and client-side rendering of JSON in a dataTable isn't feasible. 
For larger datasets my suggesting is to allow for a configurable API based approach - e.g. something that could handle the query logic in this url. 

**localhost:3000/users?search=Jack&page=3&rowsPerPage=15&orderBy=DESC&returnTotalRows=true**

**Comment by smoyergh** [comment]
As others have already pointed out, [Tabulator](https://github.com/olifolkerd/tabulator) is a mature and fully featured data table library by @olifolkerd that works with Svelte and supports reactive data table updates.  Since Tabulator supports multiple themes (based on SCCS), it might make sense to develop a robust Skeleton theme for Tabulator versus Skeleton-specific data table features.

I'm playing with it in a personal project (Skeleton/SvelteKit), but I'm not a front-end developer so anything I put together isn't going to be something anyone else will want to use.

**Comment by riziles** [comment]
> A datatable solution that requires columns to be defined in code rather than markup goes against the point of svelte, in my opinion. Without jsx, creating complex columns (such as one with multiple buttons) is a really bad experience.

@knd775 , your point is well made. I recommended Tabulator a while back as more of a "look at all the cool features this library has" than a proposal for direct integration. It's a mature and well maintained MIT licensed library. Certainly worth looking at if the Skeleton team wanted to build their own, but not ideal for Svelte + Tailwind integration. 

To @smoyergh 's point, it does work just fine in a Skeleton project, but @vincjo 's [Svelte Simple DataTables](https://github.com/vincjo/datatables) or @bryanmylee 's [Svelte Headless Table](https://github.com/bryanmylee/svelte-headless-table) are easier to style and customize.

**Comment by endigo9740** [comment]
@smoyergh it won't matter how mature it is, it's not the right tool for the job here. I've tested Tabular and it's a lot like our current Table component - that being data-driven rather than template-driven. You feed it data and it builds the cells, which has it's use cases. But for our data table solution need a way to be able to display custom markup and Svelte components within the cells. This would not allow for that. Folks are welcome to use this if it works well for them, but it's a no-go for our recommendation.

@knd775 I disagree, because again, we've followed a similar path with great success. It's useful for presentation components where all you have is data. They're easy to setup and easy to use. However, they do have the limitation you can't modify the template content, which is a big miss here.

Currently we've narrowed down the headless options down to a few options state in this thread repeatedly. If anyone is looking for a solution, please reviews the pros and cons of these. I'm not sure there's going to be such a thing as a silver bullet here.

**Comment by endigo9740** [comment]
We keep getting the same handful of recommendations over and over, so I've update the original post with a list of table solutions and a brief summary. Currently [Simple Svelte Datatables](https://github.com/vincjo/datatables) are the only recommended solution, while I'd highly advise against Tanstack tables if you care about documentation. Last I check their documentation was some of the worst I've experienced in my 20 year career.

**Comment by tachiniererin** [comment]
Just in case anyone wants to try tanstack table nonetheless, svelte support is currently broken: https://github.com/TanStack/table/issues/4778 Spare yourself the hours of fiddling with this, it's not worth it (don't ask how i know).

**Comment by piperun** [comment]
> Just in case anyone wants to try tanstack table nonetheless, svelte support is currently broken: [TanStack/table#4778](https://github.com/TanStack/table/issues/4778) Spare yourself the hours of fiddling with this, it's not worth it (don't ask how i know).

Good thing I dodged a bullet with rage quitting tanstack 😄.
From the issues I experience it was:
* Awful selection performance
* Not feature complete (ColumnHelper did not work)

Highly recommend svelte-headless-table instead if you want datatable that is very similar to tanstack tables.

**Comment by endigo9740** [comment]
Since we're seeing more activity on this thread again I wanted to go ahead and chime in and let folks know that we'll be moving to deprecate our internal data table features soon - not just delisting them. Then, when the next major version of Skeleton drops, we'll be aiming to remove them from the library entirely.

However, when this occurs we'll put forth some kind of official recommendation for a third party library (or a few) with official instructions for integration, likely in the form of a blog tutorial. Right now this is leading the pack as our official recommendation:
https://github.com/vincjo/datatables

No specific time table on any of this, but figured I'd give folks here a heads up what's coming.

**Comment by sledgehammer999** [comment]
My two cents.
Some arguments against [Svelte Simple Datatables](https://github.com/vincjo/datatables) and [Svelte-Headless-Tables](https://github.com/bryanmylee/svelte-headless-table) which may depend on one's needs from a table.
As far as I can tell, they don't allow to set a custom sorting function in the form of:
```typescript
function SortingFn(CellA, CellB, ColumnID): number;
// With return value:
// 0 -> equal
// -1 -> a < b
// 1 -> a > b
```

Their filtering features might suffer from something similar (I haven't investigated yet).

**Comment by endigo9740** [comment]
@sledgehammer999 this thread along has been on-going for 7 months. Trust me, we've been over pretty much every option available in the space. There's no silver bullet. If a dedicated project can satisfy the needs of everyone, it's highly likely a additional feature in our library is going to cover this.

We're going to likely recommend on option that is the "best", but best does not mean perfect for every use case. This is a big part of why we're going to leave it as a recommendation - you can use it or find something that works more as you wish it to.

I would hope that whatever option we recommend receives more attention from our users and additional contributors that might can expand the feature set to cover more of what folks need and want though.

**Comment by sledgehammer999** [comment]
@endigo9740 I understand. My wording was bad. I already knew what you are commenting.
I just wanted to give a heads up to anyone else looking at this thread. Because noone seemed to comment on those 2 things (sorting/filtering).

PS: Tanstack Table looks very configurable and it probably fits my needs. Dunno, if they improved their docs since you last looked, but now they look decent to me.

**Comment by endigo9740** [comment]
Note that as part of #1822 we are permanently removing the Skeleton data tables feature, which has long since between deprecated and unlisted. I've include a zip backup here for any hold outs that wish to continue using and maintaining this themselves:

- https://github.com/skeletonlabs/skeleton/issues/1821#issuecomment-1665963040

What this means is as part of the v2 release (scheduled for next week), Skeleton's data table feature will no longer be part of the Skeleton core library. You will either need to remain on v1.x or migrate to v2 and implement your own data table solution.

As mentioned multiple times in this thread, our official recommended alternative is:

- https://github.com/vincjo/datatables

I plan to write a blog tutorial in the near future that provides a detailed integration guide for using this alongside Skeleton. However, my focus right now is getting v2 out the door. So please be patient if this doesn't come about for a while. If any contributors are interested in helping write a guide sooner - please feel free to do so on our GitHub Discussions section:

 - https://github.com/skeletonlabs/skeleton/discussions
 
 With your permission, I'm happy to adapt that to an official post on our blog (with attribution of course)

**Comment by bryanmylee** [comment]
> My two cents. Some arguments against [Svelte Simple Datatables](https://github.com/vincjo/datatables) and [Svelte-Headless-Tables](https://github.com/bryanmylee/svelte-headless-table) which may depend on one's needs from a table. As far as I can tell, they don't allow to set a custom sorting function in the form of:
> 
> ```ts
> function SortingFn(CellA, CellB, ColumnID): number;
> // With return value:
> // 0 -> equal
> // -1 -> a < b
> // 1 -> a > b
> ```
> 
> Their filtering features might suffer from something similar (I haven't investigated yet).

Just a heads up, I've added support to [Svelte Headless Table's](https://svelte-headless-table.bryanmylee.com/docs/plugins/add-sort-by#comparefn-leftvalue-rightvalue-number) sorting plugin to allow configuring the sort with a `compareFn`.

```ts
const data = readable([
  { name: { first: 'Sam', last: 'Smith' } },
  { name: { first: 'Doja', last: 'Cat' } },
  { name: { first: 'Harry', last: 'Styles' } },
  { name: { first: 'Ariana', last: 'Grande' } },
]);

const table = createTable(data, {
  sort: addSortBy(),
});

const columns = table.createColumns([
  table.column({
    header: 'Name',
      accessor: 'name',
      plugins: {
        sort: {
          compareFn(left, right) {
            if (left.first > right.first) return -1;
            if (left.first < right.first) return 1;
            return 0;
          }
        }
      }
    }),
  }),
]);
```

**Comment by endigo9740** [comment]
Awesome, thanks for letting us know @bryanmylee

**Comment by endigo9740** [comment]
As part of today's launch of Skeleton v2.0, we've now removed the long-deprecated and unlisted Skeleton Data Table feature.

Going forward, Skeleton's official recommendation is to use [Svelte Simple Datatables](https://github.com/vincjo/datatables) paired with [Skeleton's Table Element](https://www.skeleton.dev/elements/tables) styles. I do aim to create an official tutorial for pairing Svelte Simple Datatables with Skeleton in the future, so keep an eye out for that.

For any holdouts wishing to keep the legacy data table feature, you can find a https://github.com/skeletonlabs/skeleton/issues/1821#issuecomment-1665963040.

Given this, we're going to go ahead and close this ticket. It's likely the olden remaining ticket in Skeleton's backlog, so thanks everyone that's participated and chimed in on this.

**Comment by aleksblendwerk** [comment]
@endigo9740 Is that blog post on pairing Skeleton and Svelte Simple Datatables still coming or is there any implementation / example in the wild where I could look things up?

**Comment by endigo9740** [comment]
Hey @aleksblendwerk, we had contributor volunteer to take this over, but then unfortunately nothing came from it. We've been so busy with v3 this just hasn't been on my radar. We're going to have several integration guides as part of v3 though, so maybe keep an eye out then. For the most part, to get started you should just be able to follow the Svelte Simple Datatable docs against a native HTML element, then apply our Table Element styles to that.

**Comment by riziles** [comment]
@endigo9740 & @aleksblendwerk , 
@kmalloy24 (the volunteer) has actually done a quite a bit of work on this. He's got a [GitHub Repo](https://github.com/kmalloy24/simple-datatables-skeleton) and some pretty slick examples: https://simple-datatables-skeleton.vercel.app/

**Comment by kmalloy24** [comment]
Thanks @riziles ! The examples are in a pretty good place, I just have to get around to documenting them still. @endigo9740 sorry for going m.i.a on this. Things have been a little hectic with work/life since the new year. Hopefully the example repo can help some folks for now and I should have a PR for the integration guide for you in the next couple of weeks.
