### ISSUE TITLE
Create welcome page(s) for CLI

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#550]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

These should be inspired by the default setup for SvelteKit, Astro, and other CLI apps. Just a simple welcome pages that display when you run the dev server after install.

- Skeleton Logo
- Welcome text
- Docs Link
- GitHub link
- Social links

Perhaps a small interactive demo page with a few components?

### What type of pull request would this be?

Other

### Any links to similar examples or other references we should review?

![image](https://user-images.githubusercontent.com/1509726/202001167-9d1f1fe2-93b5-4823-bd30-66daf41e451a.png)

**Comment by endigo9740** [comment]
@niktek FYI, I'll get this asap.

**Comment by endigo9740** [comment]
@niktek Here's what I've worked up for the first pass. 

![Screen Shot 2022-11-18 at 12 06 53 PM](https://user-images.githubusercontent.com/1509726/202773243-058c4cfb-c68e-4d80-90e8-3cbc9b6ebee7.png)

[routes.zip](https://github.com/Brain-Bones/skeleton/files/10043790/routes.zip)

NOTE: you'll also need to apply this to the app.html body tag:
`<body data-theme="skeleton">`

**Comment by niktek** [comment]
data-theme is injected into the body dynamically with the theme that was selected in the installer

There are now 3 options:
1. Bare Bones
2. Welcome
3. AppShell, AppBar and Drawer

src/ and static/ dirs are copied over now from source template-sites

Stripped comment to delete everything from layout, as well... it wouldn't be a good idea to remove the imports :P

**Comment by niktek** [comment]
Also, you have to assign this one to me for me to be able to close it out.
