### ISSUE TITLE
Search box should allow navigation to the first entry when you hit Enter

### ISSUE THREAD

**Issue by ryceg** [skeletonlabs/skeleton#568]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Basically the exact same functionality as Tailwind's docs. It would be great to be able to type in "butt" to get to the button page, and then just hit Enter. Mouse = bad, keyboard = good! 

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

https://tailwindcss.com/

**Comment by endigo9740** [comment]
Reference: https://github.com/skeletonlabs/skeleton/pull/575
