### ISSUE TITLE
Search box should have recently searched terms at the top

### ISSUE THREAD

**Issue by ryceg** [skeletonlabs/skeleton#569]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Similar to how Tailwind does it, it would be awesome to have the most recent searches at the top of the search results while the search box is empty, so that you can quickly refer back to things that you've recently needed to search for. This would be super easy to implement considering that we already have an implementation of local storage in place.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

https://tailwindcss.com/

**Comment by endigo9740** [comment]
I'm going to go ahead an nix this one. One of these days we'll get to the point we implement Angolia search, but for now I don't think we have a solid reason to replicate this particular feature. I'm going to leave the other two suggestions related to search as I think those are both valuable though. I may jump on those in the next couple of days.
