### ISSUE TITLE
Remove recommendation for Tailwind aspect-ratio plugin

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#571]
### Link to the Page

https://github.com/tailwindlabs/tailwindcss-aspect-ratio#compatibility-with-default-aspect-ratio-utilities

### Describe the Issue

> Tailwind CSS v3.0 shipped with [native aspect-ratio](https://tailwindcss.com/docs/aspect-ratio) support, and while these new utilities are great, the aspect-ratio property isn't supported in Safari 14, which still has [significant global usage](https://caniuse.com/mdn-css_properties_aspect-ratio). If you need to support Safari 14, this plugin is still the best way to do that.

Safari 14 accounts for less than 2% of usage stats:
https://www.stetic.com/market-share/browser/

Tailwind should probably retire this one on their end TBH. But we'll do the next best thing for now.

### Are you able to create a Pull Request with the fix?

Yes

**Comment by aunumever** [comment]
I'm still receiving this error when installing based on the docs.

**Comment by aunumever** [comment]
after adding this file: `import '@skeletonlabs/skeleton/styles/all.css'`

**Comment by Sarenor** [comment]
What error are you talking about?

**Comment by aunumever** [comment]
```
[plugin:vite:css] [postcss] /Users/.../client/node_modules/@skeletonlabs/skeleton/styles/elements/buttons.css:49:3: The `aspect-square` class does not exist. If `aspect-square` is a custom class, make sure it is defined within a `@layer` directive.
```

**Comment by endigo9740** [comment]
@aunumever you realize you're posting this on a closed ticket where we removed support for this plugin. Which we removed because it no longer has a use case? Tailwind handles this natively as part of the core system. 

Drop the plugin and use this:
https://tailwindcss.com/docs/aspect-ratio

In the future if you have an issue, create a new ticket. Posts like this are easy to miss.
