### ISSUE TITLE
Sveld descriptions not coming through to end dev projects

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#576]
### Current Behavior

So, some bad news.  In projects where Skeleton is installed as a package into node_modules, we no longer get all the description information in intellisense.  I've also tried installing vite-plugin-sveld and sveld as devDep's in the end-dev project, which doesn't improve the situation either.

This also brings up another point - the actual type exports are only available through the sveld cli, which we know only works with Svelte projects.  However, with the upcoming monorepo and the splitting of docsite from the component lib, there may be scope for moving the lib into a pure Svelte project ?  Which could bring the in project descriptions back for end developers.

**Comment by endigo9740** [comment]
I was checking this - so it's the prop descriptions that are not working, not the component description for anyone confused like myself! The former are definitely not working, while the latter are. The Component description is a non-standard comment feature of SvelteKit though so I suppose that's why.

**Comment by endigo9740** [comment]
@niktek You shared some notes on this on Discord - can you reiterate what was learned here to preserve this for this future? If I remember correctly this is a limitation of Typescript (or SvelteKit) and we may not be able to proceed with a fix in the short term.

Is that correct? If so let's remove the `v1` milestone from this please.

**Comment by niktek** [comment]
Long story short - currently svelte-package does not emit JSDoc comments into the .d.ts files.  This is likely not svelte-package's problem at all, but more to do with TS stripping comments: https://github.com/microsoft/TypeScript/issues/14619

Goal: Put the jsdoc comments back into the generated .d.ts files that are created by the svelte-package process.

I've looked at using svelte/compiler's parse() functionality to return an AST that we can then walk through to get to get the docs and related identifier.  This will not work as it requires svelte-preprocess to transform the components into their respective parsed components (TS/CSS/component body HTML/svelte flow control)

I've looked at using svelte-preprocess.   It's not going to work as it expects to be in a Vite environment due to the external plugins it relies on to do the preprocessing.  Whereas our script would be operating in a pure Node environment.

At this point there are two options left to explore: 

- Naive string parsing, super simple to extract the JSDoc blocks, but a bit tricker to reliably find the identifier they are related to - considering that we are only wanting it for exported props and thus have to only check the line following the JSDoc block for an 'export' word, this will probably be the easiest/dumbest route to go.  If it fails, then the description disappears in Intellisense.  Not the end of the world.
- Extract the <script *> portion of each component into a string and then use the acorn package (which SK uses internally) to get an AST that will more reliably find the associated prop.  It's another dep and raises the maintenance requirements both package wise and mentally in terms of a future dev trying to make changes or troubleshoot.

A reluctant third option (but probably the most correct) is to deep dive into svelte-package and try and fix the problem at the source for everyone.

**Comment by endigo9740** [comment]
Thanks Nik. Given this I'm going to drop this from the v1 milestones. This just means is not required for v1, but we can still continue working on as the opportunity arises.

**Comment by endigo9740** [comment]
@niktek this is working now, right?

**Comment by niktek** [comment]
yep!
