### ISSUE TITLE
Click to button 'Gold Nouveau' on Themes page copy wrong code:

### ISSUE THREAD

**Issue by alexander-mart** [skeletonlabs/skeleton#590]
Click to button 'Gold Nouveau' on [Themes page](https://www.skeleton.dev/guides/themes) copy wrong code:
```
// as is:
import '@brainandbones/skeleton/themes/theme-gold nouveau.css';
```
```
// to be:
import '@brainandbones/skeleton/themes/theme-gold-nouveau.css';
```

Maybe, don't copy 'name', but 'url'?
But i'm not sure, because code that we see on L31 can't do that bug, i think.

https://github.com/skeletonlabs/skeleton/blob/d64468dd6f272e6764d2c103092698b64c435066/src/routes/(inner)/guides/themes/%2Bpage.svelte#L31

https://github.com/skeletonlabs/skeleton/blob/d64468dd6f272e6764d2c103092698b64c435066/src/routes/(inner)/guides/themes/%2Bpage.svelte#L25

**Comment by endigo9740** [comment]
Good catch @alexander-mart we'll get that patched up. Thanks!

FYI @niktek if you're looking for low hanging items.

**Comment by endigo9740** [comment]
I've merged a fix for this. Thanks again @alexander-mart
