### ISSUE TITLE
Dev update broken

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#591]
### Current Behavior

just did a package upgrade and things broke.

`Failed to resolve entry for package "@bobthered/tailwindcss-palette-generator". The package may have incorrect main/module/exports specified in its package.json.`

We can keep an eye on things here:
https://github.com/bobthered/tailwindcss-palette-generator/issues/3

**Comment by endigo9740** [comment]
Hmm, if they don't fix in time we'll just revert back a version. The plan will be to replace this at some point, perhaps we bump that up in priority next week.
