### ISSUE TITLE
Blog post updates

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#592]
### Link to the Page

https://dev.skeleton.dev/blog/how-to-implement-a-responsive-sidebar-drawer

### Describe the Issue

`Don't worry if the other pages. These are just placeholders.` footer text under filling the Navigation.svelte listing
`Open your root layout and import the new the new Navigation component in the script tag at the top.` Double the new immediately following the above
`Restart the dev server so that Svelte Kit sees the new lib folder and sets up the $lib alias for you.` to replace the NOTE and the alias config listing.
`cause the drawer appear on demand` add to before appear
`In your root layout, update the App Shell's lead slot with the following changes:` Needs to be the App Bar's lead slot
`please consider the a few other suggestions:` last sentence on article before bullet points, drop the

### Are you able to create a Pull Request with the fix?

No

**Comment by endigo9740** [comment]
@niktek These changes have been applied
