### ISSUE TITLE
REMINDER: do a linting pass for the project

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#607]
Given this process is not automated, we're probably well overdue for a proper linting pass. Let's run the following:

- [x] Prettier
- [ ] ES-Lint
- [x] Svelte-Check

FYI Svelte-Check definitely has a few issues to resolve.

**Comment by endigo9740** [comment]
@niktek Reminder to close this out when you finish your third and final pass with Prettier please.

**Comment by niktek** [comment]
Prettier was the first pass and easiest one.  ES-Lint is the epic one - I'm actually going to put the remainder on hold as we've already got a massive reduction of outstanding linting issues and the ones that remain are all related to upgrading TS types from any to be fully typed - which is going to take a while and can probably be more focussed sub issues related to the area of the lib.
