### ISSUE TITLE
Improve accessibility functions of Menus

### ISSUE THREAD

**Issue by bennymi** [skeletonlabs/skeleton#616]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It would be nice to also support up and down key events in menus and having click events toggle the menu open and closed (currently the menu only opens when the menu button is clicked, but it does not close it again on a second click).

According to this page https://www.w3.org/WAI/ARIA/apg/patterns/menu/ , Tabs and Shift+Tabs should also close the menu.

I could work on this as well.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

[Headless UI](https://headlessui.com/react/menu) has a nice example.

**Comment by endigo9740** [comment]
Absolutely Benny. There's plenty to be done on the a11y front. I'd be glad to have folks help tackle these one by one or in a more dedicated sweep through the project. If you get a chance send a PR and I'll take look!

**Comment by bennymi** [comment]
Great, I'll try to tackle this one for now and maybe have a look at some other components afterwards as well. Should I use a chore/* branch for this?

**Comment by bennymi** [comment]
Nice! Yeah I'm on the discord channel as well. Will check it more often from now on :)

**Comment by endigo9740** [comment]
@bennymi awesome, same username? I'll keep an eye out for you. Don't be afraid to pop into the channel and say hi!
