### ISSUE TITLE
Provide tags input component 

### ISSUE THREAD

**Issue by xmlking** [skeletonlabs/skeleton#629]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

This component help editing  data types like array of string , labels etc. 
Would be nice if it natively work with felte forms. 

internally it should be just standard form  **input**  field , with value bind to string composed of  tags separated by comma.

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

https://github.com/agustinl/svelte-tags-input

**Comment by endigo9740** [comment]
Hey @xmlking, thanks for the request. This is redundant with our Chips component request here, so I'm going to close this out. Please monitor progress there instead please:

- https://github.com/skeletonlabs/skeleton/issues/375

If you're not familiar with chip components you can see a reference from the Angular Material library here. The first example seems to be what's you're seeking:

https://material.angular.io/components/chips/examples
