### ISSUE TITLE
BreadCrump Component in Astro doesn't work correctly

### ISSUE THREAD

**Issue by delight** [skeletonlabs/skeleton#634]
### Current Behavior

I build a little base astro project according to the astro guides on the skeleton [page](https://www.skeleton.dev/guides/frameworks/astro).

The BreadCrump Component doesn't seem to work correctly in this case.

See About  Page inside the started Base Demo Project https://github.com/delight/astro-base-skeleton

<img width="834" alt="image" src="https://user-images.githubusercontent.com/117198/205514205-56f52305-f445-4f28-bb02-f4a286fe7507.png">

### Steps To Reproduce

1. checkout the project https://github.com/delight/astro-base-skeleton
2. start it (npm install / npm run dev)
3. navigate to the about page

**Comment by delight** [comment]
Project is deployed at https://skelastro.amesos.de/about/ 

I had a second look and the problem is, that in Astro the Breadcrump component is not picking up the separator. Therefore the "undefined" String behind the "About"

**Comment by delight** [comment]
I didn't use any hydration, as I didn't know it would need any.
I'll try that - again it is not urgent. Just had a second look.

Breadcrumb works as expected in Sveltekit

**Comment by delight** [comment]
Hydration doesn't fix the problem. Instead on a most of them like client:visible / idle / load  it appears for a fraction of a second and then vanishes.

**Comment by delight** [comment]
> FYI delight, the rule of thumb with Astro is that if a component requires JS logic, then it needs to be hydrated. Have you tried using the Svelte wrapper component strategy detailed in Astro guide?
> 
> https://www.skeleton.dev/guides/frameworks/astro
> 
> ![Screen Shot 2022-12-05 at 10 54 10 AM](https://user-images.githubusercontent.com/1509726/205695642-1415ca9d-db57-43a5-bf8e-46d5e319fdf6.png)
> 
> Just spitballing here until I get the opportunity to test myself.

I know about Astro and Dynamic Islands. The extra wrapper was a good guess - worked (obviously without hydration -> no interactivity needed on a Breadcrump).

- I pushed the change in the repo with the base demo project https://github.com/delight/astro-base-skeleton
- I deployed the working app at https://skelastro.amesos.de/about/

What now:
- If it is a problem with the component, need to look for a fix (low prio)
- Document the workaround / adjust the astro guide in that regard. Right now it suggests to use the Breadcrump without Wrapper.

Honestly I coudn't find the guides in the repos so that I could do some PR for it.

**Comment by endigo9740** [comment]
So it looks like that worked? Yeah it's a bit annoying to have to wrap everything, but it's a weird thing with Astro where Svelte components take props from the outside.

I'm not sure what you mean about updating the guide. Breadcrumbs are not part of the Astro guide, so that would be out of scope. The bit about using the wrapping technique is already on the Astro guide, per the screenshot above.

> Honestly I couldn't find the guides in the repos so that I could do some PR for it.

Try the site search ;)

**Comment by delight** [comment]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/117198/205754885-4e494516-7e50-4d08-8e65-6efe676fb047.png">

or is it ;-) 

https://www.skeleton.dev/guides/frameworks/astro

**Comment by endigo9740** [comment]
Sorry @delight I've been juggling design token updates and tax forms all day, so forgive me. My brain is mush. Thanks for this fix though.
