### ISSUE TITLE
Provide a prepared astro skeleton starter project

### ISSUE THREAD

**Issue by delight** [skeletonlabs/skeleton#636]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Similar to the npm create skeleton-app@latest project it would be nice to offer a base project instead of letting the user work through the guides which is always error prone.
This way the user can start right away instead of setting up the basic configurations, which is a way better starting experience.

For the moment we could promote something based on my little https://github.com/delight/astro-base-skeleton project.

On the longer run I could look into building a astro template. Astro templates are fine, but doesn't offer much of a higher value over a base project + also can go invisible quickly. But I think it still would be worth it creating one for skeleton.

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@delight thanks for the suggestion, however we will be going in a different direction. Our long term goal is to update the new Skeleton CLI to generate a completely up to date project on the fly. While we currently only support SvelteKit, Astro and Vite support are planned.

You can view directions for this as part of our soft launch announcement in the latest release notes:
https://github.com/skeletonlabs/skeleton/discussions/605

And we have plans to make this our default for onboarding for SvelteKit projects in the next release:
https://github.com/skeletonlabs/skeleton/issues/628

If you're interested in contributing to an Astro version, please reach out to @niktek here or on Discord. He's new to Astro so support would be welcome! You can view the project here:
https://github.com/skeletonlabs/create-skeleton-app
