### ISSUE TITLE
Avoid wrapping inputs with label tag

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#642]
### Current Behavior

Source:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#accessibility_concerns

Wrapping forms with label tag might have have a negative impact on ADA/Screen Reader

**Comment by AdrianGonz97** [comment]
Looking at it, I don't really see anything that suggests that it's more difficult having `label` wrapping an `input`. There are suggestions to not include interactive elements like `anchors` and `buttons`, but I don't see anything about `inputs`.

**Comment by endigo9740** [comment]
@AdrianGonz97 Yeah I'm going to do more research on this before I make a definitive decision. No offense to the chatter in the stream, but everyone has opinions. It doesn't always means they are correct.

**Comment by endigo9740** [comment]
This is the bit that caught my eye though. Our spans probably need to go:
![image](https://user-images.githubusercontent.com/1509726/205798642-8c53fb61-f428-47a1-841f-cd5febcd113e.png)

**Comment by endigo9740** [comment]
After viewing this in depth, I'm not seeing anything that matches the original suggestion:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#accessibility_concerns

If you read through this it's discouraging two things:

> Don't place interactive elements such as anchors or buttons inside a label. Doing so makes it difficult for people to activate the form input associated with the label.

We don't do this in any of our examples.

> Placing heading elements within a <label> interferes with many kinds of assistive technology, because headings are commonly used as a navigation aid. If the label's text needs to be adjusted visually, use CSS classes applied to the <label> element instead.If a form, or a section of a form needs a title, use the <legend> element placed within a <fieldset>.

We use span tags, but those should be mostly ignore by screen readers. We never use props headings like h1, h2, h3, etc within any of our examples.

There's nothing stating that embedding the input within the label is bad, and in fact several of their examples show it exactly like do it! The only thing we might want to consider is implementing proper `for=""` examples to showcase best practices. But Svelte does a pretty good job of recommending this for normal use.

I'm going to go ahead and close this and consider what we have to be satisfactory.
