### ISSUE TITLE
ProgressBar.svelte + css leaks into the build 

### ISSUE THREAD

**Issue by delight** [skeletonlabs/skeleton#647]
### Current Behavior

ProgressBar.svelte + css leaks into the build  as soon as a Modal is referenced

created a demo project with 
`npm create skeleton-app@latest`
and switch the adapter to node.

Build looks good up till the moment a Modal is referenced. Then the ProgressBar gets included.

```
- 23:05:04 [vite-plugin-svelte] ssr compile done.
- package         files    time     avg
- progessbar         49   0.12s   2.4ms
- Generated an empty chunk: "hooks"
- .svelte-kit/output/server/vite-manifest.json                                    1.79 KiB
- .svelte-kit/output/server/index.js                                              77.10 KiB
- .svelte-kit/output/server/entries/pages/_layout.svelte.js                       7.47 KiB
- .svelte-kit/output/server/entries/fallbacks/error.svelte.js                     1.50 KiB
- .svelte-kit/output/server/entries/pages/_page.svelte.js                         4.09 KiB
- .svelte-kit/output/server/entries/pages/demo3/_page.svelte.js                   7.65 KiB
- .svelte-kit/output/server/chunks/index.js                                       3.66 KiB
- .svelte-kit/output/server/chunks/index2.js                                      1.29 KiB
- .svelte-kit/output/server/chunks/ProgressBar.svelte_svelte_type_style_lang.js   1.57 KiB
- .svelte-kit/output/server/chunks/hooks.js                                       0.00 KiB
- 
- Run npm run preview to preview your production build locally.
- .svelte-kit/output/client/vite-manifest.json                                                            3.50 KiB
- .svelte-kit/output/client/_app/immutable/components/error.svelte-ce0a0dde.js                            2.07 KiB / gzip: 0.95 KiB
- .svelte-kit/output/client/_app/immutable/components/pages/_page.svelte-37b763a3.js                      6.51 KiB / gzip: 2.72 KiB
- .svelte-kit/output/client/_app/immutable/components/pages/_layout.svelte-b238ad2e.js                    12.17 KiB / gzip: 3.87 KiB
- .svelte-kit/output/client/_app/immutable/chunks/singletons-470bfd41.js                                  2.17 KiB / gzip: 1.14 KiB
- .svelte-kit/output/client/_app/immutable/chunks/index-37c8ca0a.js                                       0.43 KiB / gzip: 0.31 KiB
- .svelte-kit/output/client/_app/immutable/chunks/ProgressBar.svelte_svelte_type_style_lang-3cefb392.js   0.65 KiB / gzip: 0.41 KiB
- .svelte-kit/output/client/_app/immutable/components/pages/demo3/_page.svelte-4699640e.js                11.96 KiB / gzip: 4.80 KiB
- .svelte-kit/output/client/_app/immutable/chunks/index-62954cf4.js                                       11.27 KiB / gzip: 4.68 KiB
- .svelte-kit/output/client/_app/immutable/chunks/0-a0c19778.js                                           0.09 KiB / gzip: 0.10 KiB
- .svelte-kit/output/client/_app/immutable/chunks/2-8bb554ff.js                                           0.09 KiB / gzip: 0.10 KiB
- .svelte-kit/output/client/_app/immutable/start-6b59fec7.js                                              28.30 KiB / gzip: 10.84 KiB
- .svelte-kit/output/client/_app/immutable/chunks/1-d78de3b1.js                                           0.09 KiB / gzip: 0.09 KiB
- .svelte-kit/output/client/_app/immutable/chunks/3-2abda1b6.js                                           0.10 KiB / gzip: 0.10 KiB
- .svelte-kit/output/client/_app/immutable/assets/ProgressBar-a008cc9e.css                                0.45 KiB / gzip: 0.25 KiB
- .svelte-kit/output/client/_app/immutable/assets/_layout-3bf02d91.css                                    57.54 KiB / gzip: 8.87 KiB
- 
- > Using @sveltejs/adapter-node
- Generated an empty chunk: "hooks"
-   ✔ done
```

### Steps To Reproduce

I pushed a demo project to reproduce that problem

https://github.com/delight/progressbar

### Anything else?

Can't think of a reason why ProgressBar gets pulled in

**Comment by endigo9740** [comment]
@niktek If you can get to this one before me please give it a look.

**Comment by delight** [comment]
I did, but I couldn't figure the reason

**Comment by endigo9740** [comment]
@delight I was about to give this a look when I was met with the following. Seems you may need to update to the latest version of Vite and SvelteKit before I can use this. Would you mind doing that and ping me. I'll circle back to this.

![Screen Shot 2022-12-14 at 2 30 59 PM](https://user-images.githubusercontent.com/1509726/207707613-a2bc68e2-5266-4e4c-8284-2a8d3e642b26.png)

**Comment by delight** [comment]
I'll have a look asap. Not feeling well and need some rest.

**Comment by delight** [comment]
sveltekit 1.0 + skeleton 0.80.8 + vite 4.0.1 error remains ... just do a npm rund build do reproduce.

**Comment by niktek** [comment]
This seems to be taking the last file it processed for the <styles> block.  For instance if I create `npm create skeleton-app@latest` with a bare template only import Avatar on +page.svelte I get the same output for build with node adapter.

If I remove the <style> block from ProgressBar in the node_modules/@skeletonlabs/skeleton/components/ProgressBar/ProgressBar.svelte and then do a build, I get FileDropZone as the filename:
![image](https://user-images.githubusercontent.com/52020637/207743506-3a14be6f-b505-4f56-b67e-f0d43934cb8d.png)
 And then AccordionItem after FileDropZone and then after removing those two <style> blocks I don't get any named chunks in the export.

So I don't think this is anything we are doing import/exports wise and it's just how Vite/SK is processing the styles blocks in components.

**Comment by endigo9740** [comment]
Great catch Nik. If that's the case it's upstream and may be worth reporting to Vite/SK @delight Those style blocks are important and useful.

Also hope you get to feeling better, I'm just coming off of having Covid so I get it. Take care of yourself!
