### ISSUE TITLE
New Feature: Change File Drop Zone's text title

### ISSUE THREAD

**Issue by GermanHeim** [skeletonlabs/skeleton#657]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Currently, the [File Drop Zone](https://www.skeleton.dev/components/file-dropzone) component does not have a way to change the "title" without using a custom slot like this:
`<FileDropzone>(message)</FileDropzone>`. Unfortunately, this would require the user to create an entirely new slot (adding an icon and doing a grid manually).
It would be nice to have a property (I would suggest `title`) that works similarly to the `notes` property but changes the title.

Drawing of what I name as title and notes:
![image](https://user-images.githubusercontent.com/77305706/206272818-a84b09a4-b3d4-4a55-a230-c927ba53dca2.png)

Looking through the component, the text is defined as the following:
```<!-- Text -->
<div class="flex flex-col justify-center items-start space-y-0">
   <div class="text-base font-bold">Drop {$$restProps.multiple ? 'files' : 'a file'} or click to select.</div>
      {#if notes}<div class="text-sm opacity-70">{@html notes}</div>{/if}
</div>
````
Maybe doing something like:
```<div class="text-base font-bold">
   {#if title}
        {title}
   {:else}
       (default text)
   {/if}
</div>
```
would work?

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

- https://www.skeleton.dev/components/file-dropzone
- https://github.com/skeletonlabs/skeleton/tree/master/src/lib/components/FileDropzone

**Comment by endigo9740** [comment]
Fixed per: https://github.com/skeletonlabs/skeleton/pull/659

@delight make sure you use the format `fixes #xxx` to sync a PR with a ticket. No need to make it a link, just put the text exactly like shown and it'll create the link automatically!
