### ISSUE TITLE
AppShell: display: content is not a real value?

### ISSUE THREAD

**Issue by Bandit** [skeletonlabs/skeleton#670]
### Link to the Page

https://www.skeleton.dev/components/app-shell

### Describe the Issue

https://github.com/skeletonlabs/skeleton/blob/master/src/routes/(inner)/components/app-shell/%2Bpage.svelte#L99

It says to make the outer SvelteKit `div` `display: content` - as far as I can tell that's a typo, and it should be `display: contents`?

https://developer.mozilla.org/en-US/docs/Web/CSS/display

### Are you able to create a Pull Request with the fix?

No

**Comment by Bandit** [comment]
I can probably create a PR, but want to check that it's actually a typo and not something else?

**Comment by endigo9740** [comment]
@Bandit You're correct, looks to be a typo. A PR would be welcome!
