### ISSUE TITLE
Stepper component has hard coded lock glyph

### ISSUE THREAD

**Issue by KevM** [skeletonlabs/skeleton#672]
### Current Behavior

The lock emoji used for "locked" [Stepper/Steps cannot be changed](https://github.com/skeletonlabs/skeleton/blob/4b7b331e90bb55bb06aebbb29a7a1ece23c6b8ef/src/lib/components/Stepper/Step.svelte#L74). I'm guessing there are users where that look will not mesh with their site design. 

It would be nice to have a `<slot/>` or something for extensibility.

### Steps To Reproduce

1. Using Stepper/Step
2. Configure the Step to be locked. 
3. Notice the Lock Icon displayed. 

![image](https://user-images.githubusercontent.com/1565/206913129-79d043e6-edae-433c-9358-6745a1afbf3e.png)

**Comment by endigo9740** [comment]
FYI this will now use an embedded SVG icon that will auto-adapt the to theme settings using the `fill-token` design token.

![Screen Shot 2022-12-15 at 2 16 25 PM](https://user-images.githubusercontent.com/1509726/207958453-2f206da4-505d-4e08-8a3f-e3296660b27e.png)

**Comment by KevM** [comment]
Excellent. That was fast!
