### ISSUE TITLE
Modals: allow per instance override of button text (ex: Confirm yes/no)

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#683]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Another great idea inspired by @huntabyte 

Use case is someone wanting to use a preset confirm type dialog. In addition to the response callback, we should allow the confirm/cancel button text to be overwritten per instance. This would take precedence over the default set by the Modal props.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

https://www.skeleton.dev/utilities/modals

**Comment by fsrtechnologies** [comment]
In a similar vein, it would be nice to be able to select other types of `<input>` fields - e.g. `<input type="date">` - in a standard one-off Modal without needing to build/import a custom component.

Possibly the "type" property in ModalSettings could be extended ('prompt' for the current text input, plus 'date', 'number', 'tel', 'email', 'password', etc.)  I do realize that this might not make sense for 'checkbox', 'radio', 'color'...
If this suggestion _is_ implemented, may I also suggest adding 'text' as a synonym for 'prompt', just for consistency?

**Comment by endigo9740** [comment]
Very much agreed, this will be a similar change so I'll make it happen. Thanks for the suggestion!

**Comment by endigo9740** [comment]
See also: https://github.com/skeletonlabs/skeleton/issues/693

**Comment by endigo9740** [comment]
FYI I've updated to support overriding the buttons per the original request. This will be provided via a new PR in a moment.

@fsrtechnologies Unfortunately Svelte doesn't seem to support your request given we use `bind:` here:

![Screen Shot 2022-12-16 at 4 04 56 PM](https://user-images.githubusercontent.com/1509726/208197058-1b80499b-54dc-475d-be5b-25c749684391.png)

I could do something hacky like creating a set of if/else blocks for each type we wish to support, but then I'd be repeating the input code over and over in each one - just with the type changed. That seems annoying.

I'd welcome other ideas though!

**Comment by endigo9740** [comment]
The PR is available here to test and provide feedback
- https://github.com/skeletonlabs/skeleton/pull/716

Preview URL:
- https://skeleton-docs-git-feat-expand-modal-options-skeleton-labs.vercel.app/
