### ISSUE TITLE
Add vertical sliders and background color.

### ISSUE THREAD

**Issue by PabloRuizCuevas** [skeletonlabs/skeleton#684]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It would be nice to support more features in the range slider, such as changing the background colour (the part of the bar that is not coloured by the accent-colour) and supporting vertical range sliders. 

Unfortunately due lack of cross compatibility these two features  (in special the combination) are hard to archive as the HTML specification is (flawed and) not implemented in any browser (for vertical sliders) and firefox and webkit have very different approaches.

I didn't manage to do a vertical range slider using tailwinds with these specs as I didn't find any reference to these things in tailwinds, but with normal css. ( Of course I could just rotate a horizontal one, but then it will mess up the size of the box )

I pasted a code example that I did in normal css, but maybe anyone can orientate me a bit how to make this contribution compatible with the tailwinds and skeleton project. 

Thanks in advance.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

This is the code I did  which works in firefox and chromium, but is still not depurated.
```

<script lang="ts">
    export let value: number
    let min = -100
    let max = 100
</script>
<input bind:value={value} 
    min={min}
    max={max}
    type="range"
    orient="vertical" 
  />
    

<style>

    input[type=range][orient=vertical]
    {
        writing-mode: bt-lr; /* IE */
        -webkit-appearance: slider-vertical; /* Chromium */
        width: 10px;  
        accent-color: white;
        background: black;
    }

    /** FF*/
    input[type="range"]::-moz-range-progress {
        background-color: #ffffff; 
        width: 10px;  
    }
    input[type="range"]::-moz-range-track {  
        background-color: #000000;
    }

    
</style>
```

**Comment by endigo9740** [comment]
Hey Pablo, I'll look into the solutions you mentioned, but you put it best here:

> Unfortunately due lack of cross compatibility these two features (in special the combination) are hard to archive as the HTML specification is (flawed and) **not implemented in any browser** (for vertical sliders) and firefox and webkit have very different approaches.

Emphasis mine.

We rely on native inputs to provided maximum accessibility. If a feature either doesn't exist in all browsers or has limited support then it means we will most likely not include it at a this time.

Again you CSS solutions above seem interesting, I've not used these methods personally, but I'll if it works well across OS and desktiop/mobile then we'll consider supporting this. Thanks

**Comment by PabloRuizCuevas** [comment]
ok thanks, I may come back with some test.

**Comment by endigo9740** [comment]
@PabloRuizCuevas For sure, we would welcome a draft PR. I can open that up to everyone on Discord so we can get some broad results cross OS, etc. Folks will typically help if asked!

**Comment by endigo9740** [comment]
As mentioned above we will welcome a draft or further testing of this. I'll keep an eye out for that. In the meantime I'm closing this issue. Thanks
