### ISSUE TITLE
Menu won't open on first click

### ISSUE THREAD

**Issue by AdrianGonz97** [skeletonlabs/skeleton#685]
### Current Behavior

Menus don't open on the first click of a newly loaded page. If you click anywhere on the page and then click on the Menu, it'll work as expected. But, reloading the page and immediately clicking on a Menu will not open it.

### Steps To Reproduce

1. Go here: https://www.skeleton.dev/
2. Immediately click on "Features" in the top right, it won't open on first click.
3. To repeat, refresh the page and try to click on the menu.

### Anything else?

Introduced in the latest release `0.80.8`

**Comment by PabloRuizCuevas** [comment]
I guess you 'immediately' means "so fast that it doesn't give time to the js to be loaded", which can be extremely fast (like in my case) or not so much depending on your connection etc.

**Comment by AdrianGonz97** [comment]
@PabloRuizCuevas No. Immediately, as in, don't click anywhere else in the page except for the menu after initial load. The timing doesn't have anything to do with it. You can reload the page, wait a while, and still click first on the menu, resulting in the same issue.

**Comment by PabloRuizCuevas** [comment]
@AdrianGonz97 , true, I didn't realize that, there is a bug indeed.

**Comment by endigo9740** [comment]
You know what I've been feeling like certain clicks were failing, but I couldn't ever reproduce it. The refresh is what I was missing. Good catch @AdrianGonz97.
