### ISSUE TITLE
The docs removed how to integrate with an existing SvelteKit project.

### ISSUE THREAD

**Issue by AgarwalPragy** [skeletonlabs/skeleton#692]
### Link to the Page

https://www.skeleton.dev/guides/frameworks/sveltekit

### Describe the Issue

For new projects, the heavy lifting is done via the Skeleton CLI. However, for existing projects, the instructions are unclear.

Before the Skeleton CLI was launched, the docs detailed the steps to integrate with an existing SvelteKit application.

### Are you able to create a Pull Request with the fix?

None

**Comment by endigo9740** [comment]
Yes we're aware, this will be returning in the next release per this ticket: https://github.com/skeletonlabs/skeleton/issues/676

We're going to be removing Vite + Svelte instructions and using that space to describe manual installation.

In the meantime, the instructions match that of VIte + Svelte, just with slightly different path location for the root layout and global stylesheets. I'd recommend using that as a reference or waiting until the instructions are updated.

Thanks.

**Comment by endigo9740** [comment]
@AgarwalPragy FYI here's a preview URL to an upcoming PR for implementing the manual install instructions again. Feel free to use this as a temporary solution until these changes are pushed to production:
https://skeleton-docs-git-docs-sveltekit-only-onboarding-skeleton-labs.vercel.app/guides/install
