### ISSUE TITLE
Modals allow any type of property

### ISSUE THREAD

**Issue by limpit666** [skeletonlabs/skeleton#693]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I want to be able to pass any property to a modal component that has exported properties.

At the moment I have to stringify data and I'm unable to pass functions into the component. 

Currently: 
```typescript 
const detailsModal: ModalComponent = {
        ref: modal,
        props: {
            data: JSON.stringify(inData),
        },
        slot: '<p>Skeleton</p>'
    };
```

Expected: 
```typescript 
const detailsModal: ModalComponent = {
        ref: modal,
        props: {
            data: inData,
            callback: inFunction,
        },
        slot: '<p>Skeleton</p>'
    };
```

Maybe there is a different way to do this?

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Any particular reason you stringily your prop data? That's not a requirement or suggestion we put in place. I suppose an additional way to pass data like Drawers would be useful in some scenarios though, so I think we can add something like that. See the `meta` key for Drawers to see what I mean.

I'd also recommend viewing this ticket where we have some expansions planned for the modal system:
https://github.com/skeletonlabs/skeleton/issues/683

I'll cross reference this here as the work will probably be handled for all of these at the same time.

**Comment by endigo9740** [comment]
Here's the updated documentation for this feature. This be available in the next release.

![Screen Shot 2022-12-16 at 4 28 27 PM](https://user-images.githubusercontent.com/1509726/208199344-a942ba1e-13f8-490a-a4bf-3ba2911c269d.png)

**Comment by endigo9740** [comment]
The PR is available here to test and provide feedback
- https://github.com/skeletonlabs/skeleton/pull/716

Preview URL:
- https://skeleton-docs-git-feat-expand-modal-options-skeleton-labs.vercel.app/
