### ISSUE TITLE
`k` key does not work in search

### ISSUE THREAD

**Issue by jameslounds** [skeletonlabs/skeleton#697]
### Link to the Page

https://skeleton.dev/

### Describe the Issue

You can't use the `k` key in any search string on the docs.
Might just be a MacOS issue - I don't have a windows machine on hand to test with.

Tested in webkit, firefox and chromium

### Are you able to create a Pull Request with the fix?

No

**Comment by endigo9740** [comment]
@jameslounds Thanks James, this was already found, fixed, and merged. It'll be part of the next release. Sorry about that!
https://github.com/skeletonlabs/skeleton/pull/686
