### ISSUE TITLE
FileButton component submits the form prematurely

### ISSUE THREAD

**Issue by Caelestis94** [skeletonlabs/skeleton#700]
### Current Behavior

The FileButton is not behaving as expected, it defaults to a submit type and will submit the form immediately upon clicking it.

### Steps To Reproduce

1. Import component.
2. Place component inside a `<form>`
3. Click the FileButton in the browser to upload files.

**Comment by endigo9740** [comment]
@Caelestis94 Hmm, this isn't quite right, it doesn't "default to a submit type". It's set to `type="file"` per the source:
https://github.com/skeletonlabs/skeleton/blob/master/src/lib/components/FileButton/FileButton.svelte#L24

Note this components uses Svelte's `restProps` feature which passes any attribute set on the component down to the input. I'd suggest removing any unnecessary attributes that might be affecting behavior here. Ensure you're not overriding the type for example.
![image](https://user-images.githubusercontent.com/1509726/208020545-98da7d87-796f-4cdd-84ee-70d5e0572762.png)

Unfortunately without more context we're working blind here. I might suggest either posting more of your page source, as you can, or creating a minimal reproduction so we see this occurring in full context.

**Comment by Caelestis94** [comment]
@endigo9740 I can fix it if you want, already got the fork and the branch ready

**Comment by endigo9740** [comment]
That would be wonderful, please do!
