### ISSUE TITLE
Support `disabled` prop for `Patinator`

### ISSUE THREAD

**Issue by tqwewe** [skeletonlabs/skeleton#704]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

`<Paginator disabled … />`
I'd like for the buttons and dropdowns on the paginator to be disabled while loading content.

### What type of pull request would this be?

New Feature

**Comment by endigo9740** [comment]
Done! Expect to see this in the next release. Thanks for the suggestion!

![Screen Shot 2022-12-16 at 3 38 06 PM](https://user-images.githubusercontent.com/1509726/208193183-223fea1b-1e7c-4479-b689-58be34bebd74.png)

I might also point out this will come alongside these changes:

- https://github.com/skeletonlabs/skeleton/issues/710
