### ISSUE TITLE
Docs appbar lacks a bit of padding

### ISSUE THREAD

**Issue by Etchelon** [skeletonlabs/skeleton#709]
### Link to the Page

skeleton.dev

### Describe the Issue

![8D3DE306-601E-470B-A79B-FB437FBCC5E4](https://user-images.githubusercontent.com/4141889/208161129-af9cee52-483f-424a-ab45-c6830c890de1.png)

On mobile browsers (probably all?) the appbar lacks some padding to the right of the GH icon. I tested Edge in iPhone 12 and Chrome on some recent Samsung.
Not a big deal, but since the YT stream is bringing a lot of new devs it might be worth making sure the first impression is good.

### Are you able to create a Pull Request with the fix?

None

**Comment by endigo9740** [comment]
@Etchelon Thank you sir! I'll get this fixed asap!
