### ISSUE TITLE
Support "Next" and "Previous" button labels in Paginator

### ISSUE THREAD

**Issue by MarthinusBosman** [skeletonlabs/skeleton#710]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

The Paginator component has a few built-in buttons for "previous" and "next" that just have left and right arrows defined as default, with no built in way to override them.

Either have optional slots for `previous` and `next`, with the `on:click` functionality moved to a parent div, or I guess another solution would be to just add optional props to Paginator to specify the label of each button.

This is also an issue for the buttons for Steppers. If there was an opinionated icon system, then fine you could use that, but the literal ↓↑→← arrows should definitely be override-able without doing some sort of workaround.

With class overrides already supported for all these, I think being able to just override the label would be a satisfying solution instead of needing a slot for it, which seems like overkill.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
> just come off as ugly and should definitely be override-able without doing some sort of workaround

@MarthinusBosman I'm going to ask you keep your feedback kind and constructive. Everyone here is a volunteer. Remember the folks building this are people. Please treat their work with respect. ;)

That said, I agree with your point and I think this is something we can support. We offer similar solutions in other components to support translation to other languages. I don't think this will be a problem to add. I'll also remind you this is open source, so a PR is welcome!

Here's a reference to draw from if someone gets to this before me:
- https://www.skeleton.dev/components/steppers
- https://github.com/skeletonlabs/skeleton/blob/master/src/lib/components/Stepper/Stepper.svelte#L26

**Comment by MarthinusBosman** [comment]
Hay sorry, updated the issue to remove "comes off as ugly".

I'll try and get a PR in for this myself tomorrow.

**Comment by endigo9740** [comment]
No worries, I appreciate the edit. It's my work you were talking about and I've got thick skin heh. But we definitely don't want to discourage other folks.

I'm actually working through small issues this afternoon so I've just updated to include these changes:

## Paginator
![Screen Shot 2022-12-16 at 3 34 13 PM](https://user-images.githubusercontent.com/1509726/208192700-5b14a11b-8367-48ff-8acc-15e88a2a9440.png)

Note I've also replaced the hardcoded "Amount" text in the select drop down, so it now read "X Items" by default. Plus I replaced `X of Y` for the page state with `X - Y` for better support for i18n and non-English language support.

## Stepper
![Screen Shot 2022-12-16 at 3 30 36 PM](https://user-images.githubusercontent.com/1509726/208192264-07f12440-38de-4f66-9448-38191eea0678.png)

Additionally I expanded the way the classes are set per buttons on both components, which provides a lot more customization.

These changes be merged into dev branch shortly. Expect to see them in the next release. Thanks!
