### ISSUE TITLE
Listbox item is cut off

### ISSUE THREAD

**Issue by thdoan** [skeletonlabs/skeleton#715]
### Current Behavior

I'm not sure if this is a bug with the component itself or the documentation site, but this doesn't look right:

![image](https://user-images.githubusercontent.com/4110567/208196169-ddaf95e3-6bf4-4ae2-9229-eb4ef68c5193.png)

### Steps To Reproduce

1. Go to https://www.skeleton.dev/components/listboxes
2. Click on Single Selection / Item 1
3. Press the Shift key

**Comment by endigo9740** [comment]
Looks like part of the keyboard focus styles are getting cut off. Seems like something we could improve. Thanks for the heads up!

**Comment by endigo9740** [comment]
A PR with fixes is incoming. It's a simple style fix so I'll plan to merge right away.

![Screen Shot 2022-12-16 at 4 44 07 PM](https://user-images.githubusercontent.com/1509726/208201165-58418958-0c03-411d-bc74-378393ee5b20.png)

![Screen Shot 2022-12-16 at 4 44 13 PM](https://user-images.githubusercontent.com/1509726/208201167-13895b07-3b42-4de2-9e89-853523e5f822.png)
