### ISSUE TITLE
Implement a system for reusing custom modals

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#720]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Currently users can call canned options like alerts, confirm, prompt with minimal config - just import the store and pass the appropriate settings. However, each time a custom modal is used it has to be imported, over and over again per page. Let's consider implementing a means to "register" these custom components one time - perhaps with or alongside the implementation of the `<Modal />` itself in the root layout.

Users should then be able to call these just like the canned option with minimal effort.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
View the discussion in this Discord thread:
https://discord.com/channels/1003691521280856084/1062822266032889937

In addition to the above change, we'll want to ensure styling is flexible for custom modals. We should have some way of triggering a "naked" state that's not affected by the standard modal window sizes, styles, etc. That is to say, no card background, shadow, no fixed width, etc.

This will allow for much more dynamic customization and better support for full screen sized modals.

**Comment by gprieto** [comment]
Maybe the following fits in this PR as well. I noticed while using custom ModalComponent, that the following from the docs doesn't work:
```ts
const d: ModalSettings = {
	// ...
	backdropClasses: '!items-start'
	modalClasses: '!p-0 !bg-green-500 !max-w-[75%]'
};
```
Instead only `classes:` is available which is equivalent to `modalClasses`. Haven't found a way to style the backdrop classes yet. But I believe this PR is a great opportunity to fix this inconsistency.

**Comment by endigo9740** [comment]
Solved as part of: https://github.com/skeletonlabs/skeleton/issues/922

Closing this ticket. Please refer any further comments to the ticket linked above.
