### ISSUE TITLE
Replace all imports of `browser` with `esm-env`

### ISSUE THREAD

**Issue by AdrianGonz97** [skeletonlabs/skeleton#722]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It's recommended not to import any Sveltekit specific modules into packages. If we intend on supporting other frameworks in the future, this'll definitely be a must so that we don't have an unnecessary dependency on Sveltekit.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

Docs recommendation: https://kit.svelte.dev/docs/packaging
`esm-env`: https://github.com/benmccann/esm-env

**Comment by endigo9740** [comment]
Per your original comment in Discord Coka I'm copying this over. It's a great summary and reason for this:

![image](https://user-images.githubusercontent.com/1509726/208272657-0b8fcd5e-9f6b-4a7d-9d56-17705c2f4b8d.png)

**Comment by endigo9740** [comment]
I also wanted to clarify we do not use `browser` anywhere within our package contents, but rather `onMount`. We migrated over a while back to get Vite/Astro into working order. But I'm keen to test replacing `onMount` with this method Coka has shared, assuming it's a drop in replacement.

**Comment by AdrianGonz97** [comment]
@endigo9740 Oh, if the case is that we don't already import `browser` from `import { browser } from "$app/environment"` anywhere in the package, then we don't need `esm-env`. `esm-env` is only used as a replacement for `browser` to identify the current context. If that's the case, then we don't need to use that package at all. 

I was under the impression that `LightSwitch` depended on `browser` from #721, but I guess I misunderstood 😅

**Comment by endigo9740** [comment]
Given we're not using browser right now I'm going to opt to close this for now. But we'll have the ticket for future reference if need be!
