### ISSUE TITLE
Make toast optionally unaffected by backdrop backround from modal

### ISSUE THREAD

**Issue by limpit666** [skeletonlabs/skeleton#726]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Currently:

The toast displays with modified brightness when a modal is open. 

Expected:

The toast can display on top of the backdrop from the modal. 

I tried adding a modified z-index to the classes string on ToastSettings, since it seems the backdrop uses z-index 999. 

```typescript
    const toast: ToastSettings = {
        message: error,
        classes: "bg-warning-500 text-on-warning-token z-1000",
        autohide: true,
        timeout: 2000,
    };
```

This still displays the toast with decreased brightness, seems z-index gets overriden to z-[888] either way.

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
Hey @limpit666 I'm not sure we will ever modify this to be the default behavior. Modals include alerts, confirmation, and prompts and should probably take visual precedence in most cases. That said, this can be adjusted for your own projects if you prefer.

If you wish to affect the global defaults for all Toasts to have a higher z-index then you would apply the following on the `<Toast />` component:

```html
<Toast class="!z-[1000]" />
```

I'm not sure if `!` (important) is needed, so try with and without. But I do know for certain your use of `z-1000` won't work as this is not a valid Tailwind utility class. They only support 0-50 out of the box:
https://tailwindcss.com/docs/z-index

**Comment by limpit666** [comment]
Thank you for the explanation and very helpful advice. 

I will try out your suggestions.
