### ISSUE TITLE
AppRailTile throws "Duplicate lexically-declared names are not allowed in an ECMAScript module."

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#727]
### Current Behavior

https://github.com/sveltejs/vite-plugin-svelte/issues/561

Keep in mind that the events are in AppRailTile and Crumb components, but Crumb has not been published with the updates yet.  So only AppRailTile is causing issues for now.

Is it feasible to remove the events until we figure out more what is actually going on ?

**Comment by endigo9740** [comment]
FYI I've made some headway on this. I've ended up reporting the issue to the SvelteKit GitHub issue tracker here. This explains the issue in detail:

- https://github.com/sveltejs/kit/issues/8217

In summary: Any use of `<svelte:element>` with forwarded events is causing an issue when those components are packaged and distributed.

**Comment by endigo9740** [comment]
I've released a hotfix for this as v0.80.9. If anyone is encountering this issue we should encourage them to update:
https://github.com/skeletonlabs/skeleton/releases/tag/0.80.9

Given the root issue is on SK's end, we'll keep an eye on the ticket above, but I'm going to go ahead and close this out. I'll aim to copy the same fix to the Crumb component on the dev branch now, which will be subject to the same problem.
