### ISSUE TITLE
Implement Purge CSS

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#732]
I'm splitting this task off from here:
- https://github.com/skeletonlabs/skeleton/issues/650

General idea is that since we use raw stylesheet imports and do not pass our styles through Skeleton's Tailwind plugin, most of the styles imported via `all.css` make it into the final bundle. Essentially tree shaking is not implemented by default. This isn't horrible (given CSS is not blocking), but we should aim to optimize this.

Looking at Flowbite, they have a recommended step to install Purge CSS, which is available as a PostCSS plugin:

- https://purgecss.com/
- https://purgecss.com/plugins/postcss.html

This needs to be tested and basic installation and configuration decided. Then the documentation should be updated for a "Prepping for Production" or "Optimization" guide. This will remain optional, but recommended for most projects.

**Comment by endigo9740** [comment]
Working with @AdrianGonz97 today we've been able to make some progress on this. Unfortunately it's not completely ready to use.

First off, we tested both the [PostCS plugin](https://purgecss.com/plugins/postcss.html), as well as the [Rollup plugin documented here](https://github.com/FullHuman/purgecss/tree/main/packages/rollup-plugin-purgecss). We did not have success with the Rollup plugin, however did with the PostCSS plugin.

This required the following configuration change:

```js
const tailwindcss = require('tailwindcss');
const autoprefixer = require('autoprefixer');
const purgecss = require('@fullhuman/postcss-purgecss');

const config = {
	plugins: [
		tailwindcss(),
		//But others, like autoprefixer, need to run after,
		autoprefixer,
		purgecss({
			content: [
				'./src/**/*.html',
				'./src/**/*.svelte',
				require('path').join(require.resolve('@skeletonlabs/skeleton'), '../**/*.{html,svelte}')
			]
		})
	]
};

module.exports = config;
```

By doing this we were able to see reduction in the CSS bundle size. Here's the before and after:

![original-css](https://user-images.githubusercontent.com/1509726/208504838-4661a37f-051d-47e5-b9a9-a3ea1a5cfb63.png)

![Screen Shot 2022-12-19 at 1 30 15 PM](https://user-images.githubusercontent.com/1509726/208504878-9abd68b8-9da4-413f-881d-99f6b7a41448.png)

This was for a base CLI welcome app with minimal options selected:

![image](https://user-images.githubusercontent.com/1509726/208505011-029b4e1e-1e16-4c06-8f97-f2c15409dc55.png)

Unfortunately, as soon as @AdrianGonz97 applied this to his personal project, he saw a reduction in bundle size, but visual bugs were introduced due to styles not rendering as expected. The main culprit seem to be items within the AppShell slots and anything with media breakpoint variants like `sm: md: lg:`. Strangely `dark:` variants seem to work as intended when flipping between light/dark mode manually via the app.html .dark class on the HTML element.

It seems more testing will be required to get this fully functional.

**Comment by endigo9740** [comment]
Thanks for taking a look @niktek. I'm really stumped on this one. I'm not sure we have a good solution. I do anticipate some size benefits and DX improvements by getting our styles compiled into the Tailwind plugin. But that's quite a hill to climb. To the point I'm always willing to say it won't be possible. We may just have to make it clear that if you need to dramatically cut down the size of your CSS that you selectively import only the styles you plan to use.

Perhaps something like a "stylesheet import" generator might be useful here. Where it builds a version of what we do in `all.css`, but with only the styles you choose to use. Don't need/want forms - don't include the form.css stylesheet. That kind of thing.

**Comment by niktek** [comment]
https://github.com/carbon-design-system/carbon-preprocess-svelte

This is how they are handling purgecss more directly.

**Comment by AdrianGonz97** [comment]
@endigo9740 @niktek 
I've made a lot of progress this past weekend and I've got some good news! I have a working version of a rollup plugin that will purge _most_ (there are very minor exceptions but it's a whole lot better than before) of the unused CSS. I've forked carbon's preprocessor for svelte and modified it to work for our applications. I would not trust it just yet, but it's something! 😆 I still need to clean it up and continue testing, but I'm hopeful that it'll be the solution to our problems.

**Comment by AdrianGonz97** [comment]
Our custom PurgeCSS Vite plugin is almost complete! It's currently available on npm as [vite-plugin-svelte-purgecss](https://www.npmjs.com/package/vite-plugin-svelte-purgecss) and users can install it by following the instructions that are laid out in the [repo](https://github.com/AdrianGonz97/vite-plugin-svelte-purgecss). 

Here's a quick sneak peek at the gains from using it:
```bash
# Barebones template from our CLI
CSS Bundle without our plugin:   103.28 kB │ gzip: 16.10 kB
CSS Bundle with our plugin:       23.59 kB │ gzip:  6.63 kB

# Our docs site skeleton.dev
CSS Bundle without our plugin:   167.31 kB │ gzip:  20.35 kB
CSS Bundle with our plugin:      129.39 kB │ gzip:  16.13 kB

# results are not as drastic for the docs site as we use every single component available in the lib for demos
```

There's one last thing that I want to smooth out before releasing it out to the masses. I need to fix how our plugin handles svelte components that have been transformed/created by other plugins. For example, [`mdsvex`](https://github.com/pngwn/mdsvex) takes markdown files and transforms them into svelte components. At the moment, I'm not able to analyze these newly generated svelte components. Hopefully I can roll out a fix for it very soon!

**Comment by endigo9740** [comment]
@AdrianGonz97 given that I know you're still working on this and things have dragged out a bit, I'm going to go ahead and close this out. Please feel free to keep us in the loop when this is ready and we'll gladly help signal boost and include it as part of our official recommendation for Skeleton!
