### ISSUE TITLE
Replace Google Analytics

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#736]
Give it the boot, implement something more anonymous and simple.

https://vercel.com/analytics

**Comment by niktek** [comment]
Re-check what Vercel had to offer - I think there was some implementation required and not just server side stuff - though server side only would have been better

**Comment by GermanHeim** [comment]
I wanted to add that Vercel Audience Analytics is free while in beta. Pricing is not confirmed, I believe.

**Comment by luke-hagar-sp** [comment]
I have both methods of vercel analytics deployed, I would be happy to assist with Skeletons implementation, or help with building out a custom solution

**Comment by endigo9740** [comment]
Given we've identified the need for environment variables, I'm going close out your PR @luke-hagar-sp an then we can circle back to this:

https://github.com/skeletonlabs/skeleton/pull/820
