### ISSUE TITLE
Add blog to mobile navigation

### ISSUE THREAD

**Issue by luke-hagar-sp** [skeletonlabs/skeleton#744]
### Link to the Page

https://www.skeleton.dev

### Describe the Issue

Viewing the site on mobile doesn't seem to present you with an option to navigate to the blog

### Are you able to create a Pull Request with the fix?

None

**Comment by endigo9740** [comment]
Done. I've integrated this into the app rail top-level sections.

![Screen Shot 2022-12-28 at 11 08 57 AM](https://user-images.githubusercontent.com/1509726/209847744-a0e263e5-3e80-4a58-98fd-c0fbfb1e800a.png)
