### ISSUE TITLE
[Feature Request] Add text property to Divider component

### ISSUE THREAD

**Issue by thdoan** [skeletonlabs/skeleton#746]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I wish the [Divider component](https://www.skeleton.dev/components/dividers) would accept a `text` prop so that we could do something like this:

![image](https://user-images.githubusercontent.com/4110567/209719326-a595d454-1c49-42dd-9c73-d1653e7b2a09.png)

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

Examples:
https://illright.github.io/attractions//docs/components/divider
https://daisyui.com/components/divider/

**Comment by endigo9740** [comment]
Interesting idea. I was looking for a reason why we would want to keep the divider a component and convert it to an element feature like buttons, badges, cards, etc. This might be the a good reason for that.

**Comment by endigo9740** [comment]
@thdoan given this issue, I'd welcome your feedback on my proposed change here:
https://github.com/skeletonlabs/skeleton/issues/756

You really don't need a component to accomplish what you're trying to do though if you do something like this. It takes very minimal HTML/CSS:

```html
<div class="grid grid-cols-[1fr_auto_1fr] gap-4 items-center">
    <hr />
    <span>text</span>
    <hr />
</div>
```

Grid styles are AWESOME :D

Here's the result:

![Screen Shot 2023-01-02 at 3 45 40 PM](https://user-images.githubusercontent.com/1509726/210279962-6889ecd3-3569-42d3-a5c0-1c02182eeee3.png)

**Comment by thdoan** [comment]
@endigo9740 thanks for suggesting that nifty CSS -- that works for me ^_^.
