### ISSUE TITLE
Listbox selection disabled if store has undefined value

### ISSUE THREAD

**Issue by Etchelon** [skeletonlabs/skeleton#759]
### Current Behavior

When a `ListBox` is bound to a `writable(undefined)`, selection doesn't work.

I noticed it when working on a classic UI with cascading selects, where the store for the second select is initially undefined. Once it becomes usable, the selection doesn't work.

### Steps To Reproduce

1.
```
<script>
  const selected = writable(undefined);
</script>

<ListBox {selected}>
  <ListBoxItem value="1">One</ListBoxItem>
  <ListBoxItem value="2">Two</ListBoxItem>
</ListBox>
```

2. Click on any option --> it doesn't become selected

### Anything else?

Seems to be due to the early return here:

```
function onClickHandler(event) {
    /** @event {{ event }} click - Fires when the component is clicked.  */
    dispatch('click', event);

    if (!$selected || !$$props.value) {
        return; // <---- here
    }

    typeof $selected === 'object'
        ? handleMultiSelect()
        : handleSingleSelect();
}
```

**Comment by Etchelon** [comment]
For the moment I'm working around it with this hack, but it's not ideal:

```
$: {
		const availableModes = $gameModes$;
		const currentDefault = $defaultGameMode$;
		if (availableModes.length === 1) {
			defaultGameMode$.set(availableModes[0]);
		} else {
			if (currentDefault && !availableModes.includes(currentDefault)) {
				defaultGameMode$.set(availableModes[0]);
			}
		}
	}
```

**Comment by bennymi** [comment]
@Etchelon if you know all yuor ListBox values are positive you could also set the initial value of the store to a negative value:

`const selected = writable(-1);` 

That way you also get the effect of none of the list items being selected at first without breaking the ability to select the items. Then you can check if an item was selected by checking if the value is no longer `-1`. Maybe that helps in your usecase as well.

**Comment by Etchelon** [comment]
I could. In my case values are strings, so I could initialize it with a bogus string but that doesn't look right. I haven't checked the source code much more in depth so I don't know if there's a good reason for that `!$selected` check but at a first glance it doesn't seem right.
In a single selection listbox I expect to be able to provide a `nil` value to signify the absence of selection, not some invalid value as a hack. That's the way select components usually work in UI frameworks.

**Comment by Etchelon** [comment]
I guess empty string would meet the same fate if the check remains on the truthyness, but anyway as I said it's not a show stopped by any means for now! Thanks a lot all you guys for this awesome lib 😄

**Comment by endigo9740** [comment]
FYI an empty string evaluates to `false` in Javascript:
https://www.freecodecamp.org/news/falsy-values-in-javascript/

But I get what you mean!

**Comment by endigo9740** [comment]
@Etchelon I've tested and replicated the error, your suggestion was spot on - the extra conditional was preventing this from working. I've pushed out a fix, expect this in the next release a week from today. Thanks!
