### ISSUE TITLE
Disable Modal Backdrop Close Event

### ISSUE THREAD

**Issue by risalfajar** [skeletonlabs/skeleton#764]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I'm creating a mandatory Modal (a Modal that can't be closed until some action is done), but I don't see a way to configure the Modal to not close when the user's clicking the backdrop.

Looking at `Modal.svelte`, maybe we could add some configuration here?
```svelte
function onBackdropInteraction(event) {
    if (!(event.target instanceof Element))
        return;
    if (event.target.classList.contains('modal-backdrop'))
        onClose();
    /** @event {{ event }} backdrop - Fires on backdrop interaction.  */
    dispatch('backdrop', event);
}
```

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

I've created similar FR in Flowbite Svelte
https://github.com/themesberg/flowbite-svelte/issues/323

**Comment by endigo9740** [comment]
We've had a similar request in the past, so you can read the thoughts of the other core contributors and myself here:
https://github.com/skeletonlabs/skeleton/issues/385

In short:

- We feel this is bad practice and bad UX
- A dedicated page is a million times better for this sort of thing
- It's against the WAI-APG guidelines for accessibly, which means it's a no-go for us

We will not be implementing this feature. If you absolutely require this, then keep in mind Skeleton is open source. You can clone any feature we introduce and modify as you see fit.

Thanks for your understanding.
