### ISSUE TITLE
Various Discord and Community Updates

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#781]
With v1 fast approaching we should aim to flush out our Discord experience. This can include, but is not limited to:

- [x] Update our Code of Conduct - which is currently based on Svelte's iteration
- [x] Update our rules (per channel) - help ensure folks aren't posting in the wrong place
- [x] Implement a sticky post at the top of the `#support` channel to cover common rules and expectations
- [x] Enable "Rule Screening" for newly added members
- [x] Introduce a moderation bot that can quick link to useful pages, such as FAQs, blog posts, the website, repo, etc

@Sarenor @LukeHagar I welcome your help with this too!

**Comment by Sarenor** [comment]
Happy to help!
1) I think most of our channel rules are fine, support could use an update and we may want to put a cap on how often you can show of your site in #showcase.
2) Hopefully I can write that up right now
3) I have no experience with moderation bots, but as with Accepting the CoC before being able to interact with the rest of the Discord I can ask around

**Comment by Sarenor** [comment]
Support rules:
To help us support you, please try to follow the following rules:
1) One currently open support post per day. We're a small team of volunteers and don't want to get overwhelmed
2) Before you open a support thread, did you search through the already existing ones? Maybe someone had a similar problem already!
3) Give us as much information as possible in the initial post:
    - Is your project set up by hand or with the Skeleton CLI?
    - What did you expect to happen?
    - What happened instead?
    - Example code or even better a link to the relevant file on GitHub
    - If your project is deployed in a publicly accessible way, a link and a reproduction guide
    - Screenshots or videos sometimes say more than words
4) If you do provide sample code, remember that Discord supports codeformatting with 3 `.
If you put the language behind the opening backticks (html/css/ts/js) it will even provide syntax highlighting which is much appreciated during debugging!

If you don't follow these rules, we may take longer to answer or disregard your post altogether, so please try to work with us!

**Comment by Sarenor** [comment]
Apparently following the rules set out for Discord to be a Community server is a good idea, for minimum verification levels, mods should have mobile authentication, etc.

I don't think we should use the Discovery feature, but the other Community-Features like Server Insights might be helpful and with Discovery being opt-in it might not be a bad idea

**Comment by endigo9740** [comment]
Folding the new Code of Conduct update into this ticket as well:
- https://github.com/skeletonlabs/skeleton/issues/780

**Comment by Sarenor** [comment]
Still gotta think of a way how to put "We don't want web 3 stuff in our community" into the CoC, too

**Comment by endigo9740** [comment]
FYI we've settled on Carl.gg as our mod bot for now. It's fairly power rich and gives us room to grow.
