### ISSUE TITLE
Polish and refine all Skeleton features

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#782]
To prep for v1 I'd like to do one more all-encompassing pass to prepare and polish our various features for launch. This may include, but is not limited to the following:

1. Code review, code cleanup, finalize the API/props
2. Improve the styling, ensure consistency
3. Add or improve animations (where relevant)
4. Improved and expanded interactive examples (where relevant)

We'll break this into sub-tasks to ensure we cover the entire project. But the three main areas of focus will include:

1. https://github.com/skeletonlabs/skeleton/issues/837
2. https://github.com/skeletonlabs/skeleton/issues/857
3. https://github.com/skeletonlabs/skeleton/issues/922
4. Do a `FIXME` pass to find issues documented inline within the codebase

**Comment by endigo9740** [comment]
Selection animation: https://play.tailwindcss.com/Qd98eMhkxy

**Comment by endigo9740** [comment]
Forms: cover additional selectors such as `readonly`:
https://tailwindcss.com/docs/hover-focus-and-other-states#read-only

**Comment by endigo9740** [comment]
Typogrphy.css - consider dropping paragraph styles. Allow them to inherit form the base text color by default:

- https://github.com/skeletonlabs/skeleton/issues/825

**Comment by endigo9740** [comment]
Buttons: click effect stays in pressed state if you click and drag off.

**Comment by endigo9740** [comment]
Form components: test binding and `use:enhance` features for non-standard inputs. Ensure stores work with these.

**Comment by endigo9740** [comment]
Dropzone:

![Uploading image.png…]()

**Comment by endigo9740** [comment]
Move the `SvgIcon` to the `/docs` directory and remove it from the package `index.ts`

**Comment by endigo9740** [comment]
@JustBarnt I've migrated your component issue here: https://github.com/skeletonlabs/skeleton/issues/857

**Comment by endigo9740** [comment]
NOTE: for utility overlays (modals, drawers, toasts, etc) make sure to indicate these should reside ABOVE the app shell, not within it.

**Comment by Sarenor** [comment]
Since ak4zh didn't do it:
![image](https://user-images.githubusercontent.com/31982384/214623340-22252a12-fe33-42c8-9906-c40d385df4b8.png)
We might want to see if we can find a way to move the modal when keyboards reduce the screen space.
Not sure how to go about that though

**Comment by endigo9740** [comment]
@ak4zh @Sarenor 

This is one of those annoying mobile web issue that I've never found a good solution for. The mobile browsers will try and scroll to keep the selected input on the screen, but if there's not enough room to scroll it won't "reach" it. The best part is browsers give zero means to know when the onscreen keyboard is active, so really there's nothing that can be done in the current iteration of the modal system.

What I'll need to do is set a particular breakpoint where modals auto-position near the top rather than remaining in the center. It won't fix every use case (especially large modals) but it'll be a step in the right direction.

**Comment by endigo9740** [comment]
Abstract tooltip type out to external file for use by end users:
https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/utilities/Tooltip/tooltip.ts#L3

**Comment by Sarenor** [comment]
https://captaincodeman.github.io/svelte-headlessui/popover/
Daniel_hayes on Discord switched to this to be able to open a popover/menu from 2 different buttons

**Comment by endigo9740** [comment]
https://www.scottohara.me/blog/2023/01/26/use-the-dialog-element.html

**Comment by endigo9740** [comment]
@riziles suggested a method to improve the modal scrollbars here. We'll investigate this when we get to Modals:
https://github.com/skeletonlabs/skeleton/issues/890

**Comment by endigo9740** [comment]
Reminder: toast buttons need a named selector wrapping class.

**Comment by endigo9740** [comment]
All reported Utility improvement comments have been noted on the new Utilities polish pass ticket here:
https://github.com/skeletonlabs/skeleton/issues/922

Those respective comments have been removed from this thread.

**Comment by endigo9740** [comment]
Given that all child tickets have now been created, I'm going to go ahead and close this out. This ticket has served it's purpose and is now redundant.
