### ISSUE TITLE
Pagination breaks when using search in Data Table

### ISSUE THREAD

**Issue by dmlayton** [skeletonlabs/skeleton#788]
I'm using 0.86.9. Using pagination and search in the same data table, when I search, the pages are limited to the first page.

I've not fully tested, but I think the issue is here:
https://github.com/skeletonlabs/skeleton/blob/d73bd810337b82a85c180af5f3e56b27eca36b90/src/lib/utilities/DataTable/DataTable.ts#L140:L142
It looks like the pagination size is being set based on the results filtered by pagination. It seems to "work" if you set `store.filtered` first like so:
```          // Set Current Size
            store.pagination.size = store.filtered.length;
            // Then apply the page filter
            store.filtered = store.filtered.slice(0, store.pagination.limit);
```
By work, I mean you see the correct size and can click to the next page, but the offset remains 0 and you only see the first page of results. I'll keep looking into this.

**Comment by dmlayton** [comment]
Okay so this is what I arrived at:
```
            store.pagination.size = store.filtered.length;
            // Then apply the page filter
            store.filtered = store.filtered.slice(store.pagination.offset * store.pagination.limit, // start
                store.pagination.offset * store.pagination.limit + store.pagination.limit);
            // Set the current page to the first page
            // store.pagination.offset = 0;
```
If you set the pagination offset to `0` here, you can't go past the second page. I'm not sure how the handler are setup as I haven't made much attempt, but if this handler handles pagination existing and then pagination actions and likewise the search handler handles changes in the search term, then the setting of the pagination offset to zero should happen in the search handler.

One idea would be to model ordered filters and just append pagination as a filter rather than having two dueling filter handlers.  IDK

**Comment by endigo9740** [comment]
Hi @dmlayton this is a known issue. We're tracking these here:
https://github.com/skeletonlabs/skeleton/issues/538

Given the experimental status of the feature we know there are several issues and we're limiting the number of tickets created. We've seen this one come through no short of about 5 times. Trust us, we know heh.

That said if you're interesting in working on this feel free to reach out to myself and @AdrianGonz97 (CokaKoala). We may not have the opportunity to revisit for a while. Thanks
