### ISSUE TITLE
Bottom Navigation Bar

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#790]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Reference:
- v2: https://m2.material.io/components/bottom-navigation
- v3: https://m3.material.io/components/bottom-app-bar/guidelines

These are typically referred to as a "bottom nav" or "bottom app bar". Note that this will NOT be related to the App Rail. These are separate components with separate specs and requirements.

Summary:

- App Rail - vertical rail that can accept many options and potentially even support vertical scrolling
- Bottom Navigation Bar - horizontal bar with a fixed or max set of navigation options and does not allow for scrolling.

This new component can draw from a similar source of data for the navigation links, but given the horizontal orientation we have to be very careful, as space is limited on small mobile screens.

Here's a quick mock of what I'm proposing. This would be limited to up to 5 link options and styled similar to the Material Design v2 iteration. I'm not too fond of the v3 version.

![Screen Shot 2023-01-10 at 11 06 41 AM](https://user-images.githubusercontent.com/1509726/211616376-6578d5ac-280f-4577-b87c-d1fdfbe281cf.png)

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

Based on this request:
- https://github.com/skeletonlabs/skeleton/issues/500

**Comment by salisshuaibu11** [comment]
I feel like I should take this ticket

**Comment by endigo9740** [comment]
Hey @salisshuaibu11, while I'm going through the polish phase tickets pinned at the top of the Issues board, we're not really accepting new features. But I'll try to remember to ping you when we're accepting new entries. I'd appreciate the help!

**Comment by endigo9740** [comment]
So interesting finding as part of the component updates for the Tab component:
https://github.com/skeletonlabs/skeleton/issues/857

By using a few small style adjustments, I've been able to create a pretty decent bottom navigation bar. See the screenshot and video below:

![Screenshot 2023-02-01 at 11 48 00 AM](https://user-images.githubusercontent.com/1509726/216123772-b9e15042-f6b6-45f9-bf07-6a61c52a8096.png)

https://user-images.githubusercontent.com/1509726/216123774-e67a3366-b012-4656-8c44-74640dfbaa4f.mp4

```html
<!-- Desktop -->
<div class="bg-surface-100-800-token">
	<TabGroup justify="justify-center" active="variant-filled-primary" hover="hover:variant-soft-primary" rounded="" borderWidth="">
		<Tab bind:group={tabsFancy} name="books" value={0}>
			<svelte:fragment slot="lead"><i class="fa-solid fa-book" /></svelte:fragment>
			Books
		</Tab>
		<Tab bind:group={tabsFancy} name="movies" value={1}>
			<svelte:fragment slot="lead"><i class="fa-solid fa-film" /></svelte:fragment>
			Movies
		</Tab>
		<Tab bind:group={tabsFancy} name="tv" value={2}>
			<svelte:fragment slot="lead"><i class="fa-solid fa-tv" /></svelte:fragment>
			Television
		</Tab>
	</TabGroup>
</div>
```

```html
<!-- Mobile -->
<div class="bg-surface-100-800-token max-w-[480px] mx-auto">
	<TabGroup
		justify="justify-center"
		active="variant-filled-primary"
		hover="hover:variant-soft-primary"
		rounded=""
		borderWidth=""
		flex="flex-1"
	>
		<Tab bind:group={tabsFancy} name="books" value={0}>
			<svelte:fragment slot="lead"><i class="fa-solid fa-book" /></svelte:fragment>
			Books
		</Tab>
		<Tab bind:group={tabsFancy} name="movies" value={1}>
			<svelte:fragment slot="lead"><i class="fa-solid fa-film" /></svelte:fragment>
			Movies
		</Tab>
		<Tab bind:group={tabsFancy} name="tv" value={2}>
			<svelte:fragment slot="lead"><i class="fa-solid fa-tv" /></svelte:fragment>
			Television
		</Tab>
	</TabGroup>
</div>
```

**Comment by endigo9740** [comment]
FYI I've added the desktop variant to the Tab examples on the doc page. Using `flex="flex-1 lg:flex-0"` would make for a very that switches between either mode automatically, but it appears Tailwind doesn't allow the `flex-x` property with breakpoints like `md:` or `lg:`!

Let's perhaps circle back to this in future Tailwind versions and see if it's fixed.

**Comment by endigo9740** [comment]
Now resolved as part of: https://github.com/skeletonlabs/skeleton/issues/857

Please test and post feedback in that ticket please.

**Comment by salisshuaibu11** [comment]
Well done @endigo9740, it makes sense will surely look into it.

**Comment by ak4zh** [comment]
Tabs may not be the optimal choice for the Navigation Bar as they mandate the use of `bind:group` and do not allow `href`. Navigation sounds more connected to links.
