### ISSUE TITLE
Remove legacy components now converted to Tailwind Elements

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#793]
The components and paired documentation pages should be removed. The Tailwind Elements version of these will remain.

- [x] Alerts
- [x] Breadcrumbs
- [x] Dividers
- [x] Gradient Heading

There's three parts to this:

1. Remove the components themselves
2. Remove their documentation page (be sure to leave the Elements versions)
3. Update the `index.ts` file to drop these as well

I'd recommend browsing through the doc site to ensure no remnants are left - an old import, etc.

**Comment by ryceg** [comment]
I'll take this!

**Comment by endigo9740** [comment]
The gradient heading documentation has been repurposed to show how to generate this type of element using pure Tailwind utility classes.

![Screen Shot 2023-01-15 at 12 29 19 PM](https://user-images.githubusercontent.com/1509726/212560000-9532a1e5-b394-4718-a18a-09df2a8c99c6.png)
