### ISSUE TITLE
dev dist-tag version of the package auto published

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#798]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Get a @dev dist-tagged version of the package auto-published on commits to dev branch using GH actions

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Haven't seen any motion on this so I'm going to close it out. Feel free to reopen if/when relevant.
