### ISSUE TITLE
typescript errors when assigning `class` attribute to LightSwitch

### ISSUE THREAD

**Issue by AgarwalPragy** [skeletonlabs/skeleton#800]
### Current Behavior

[LightSwitch seems to support adding custom classes](https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/utilities/LightSwitch/LightSwitch.svelte#L81)

```typescript
$: classesBase = `${cTrack} ${$$props.class ?? ''}`;
```

### Steps To Reproduce

```svelte
  <LightSwitch class="top-10 right-10 absolute hover:ring-secondary-500-400-token" />
```

The above works, however, since the props don't declare the `class` prop it leads to a type error

```
Error: Type 'string' is not assignable to type 'never'. (ts)
```

**Comment by endigo9740** [comment]
@AgarwalPragy I'm unable to recreate this error. Can you send a minimum reproduction please? I'm worried something else may be affecting your project to cause this issue.

**Comment by AgarwalPragy** [comment]
1. Create a barebones skeleton project using the CLI. Use typescript.
2. src/routes/+page.svelte
    ```svelte
    <script lang="ts">
    	    import { LightSwitch } from '@skeletonlabs/skeleton'
    </script>
    
    <LightSwitch class="some-class" />
    ```

Editor shows the following error

<img width="661" alt="image" src="https://user-images.githubusercontent.com/7423639/212576757-72b19a4f-a340-4745-a39c-edd5db27fde2.png">


Running `pnpm check` produces the following

```
pnpm check

> class-bug@0.0.1 check .
> svelte-kit sync && svelte-check --tsconfig ./tsconfig.json


====================================
Loading svelte-check in workspace: .
Getting Svelte diagnostics...

src/routes/+page.svelte:5:14
Error: Type 'string' is not assignable to type 'never'. (ts)

<LightSwitch class="some-class" />

====================================
svelte-check found 1 error and 0 warnings
 ELIFECYCLE  Command failed with exit code 1.
```

It happens because the generated `LightSwitch.svelte.d.ts` has the following type for `props`
```typescript
props: {
    [x: string]: never;
};
```

I think adding the following in every component that uses `$$props.class` should fix the issue
```typescript
let klass = ''
export { klass as class }
```

**Comment by niktek** [comment]
I think something else is going on here.  I did a new app via CLI with TS enabled and have the following in my +page.svelte:
```
<script lang="ts">
	import { AccordionGroup, AccordionItem, LightSwitch } from "@skeletonlabs/skeleton";
	let isCollapsed = false;
</script>

<AccordionGroup collapse={isCollapsed} hover='bg-slate-200' padding='' class='from-orange-100' >
	<AccordionItem class='bg-slate-300'>
	</AccordionItem>
</AccordionGroup>
<LightSwitch class='foo' />
```
Running svelte-check returns 0 errors for me:
![image](https://user-images.githubusercontent.com/52020637/212596654-0a190c48-38e9-427b-a64c-3550fc76a197.png)

Any chance you're running a TS nightly VS Code extension, or some other global TS config is creeping into your project ?  Can you show your package.json?

**Comment by AgarwalPragy** [comment]
@niktek 
Super weird!

Here's a minimal reproduction: https://github.com/AgarwalPragy/exposed-props

To verify that the issue is not purely with my machine, I tested it in github codespace, and got the same error

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7423639/212623068-d5177f80-8e86-4f4f-ac57-5fa15b663961.png">

**Comment by AgarwalPragy** [comment]
PS: This isn't a VSCode issue either since I'm just using it for the screenshots because the dev community is more familiar with it. I code in WebStorm and first noticed the issue there when I tried to run `pnpm build`

**Comment by niktek** [comment]
Okay, this is just.... bizarre.  I can repro what you are seeing.  But what makes it happen is whether ESLint is installed or not.  Your project takes No for every option which results in:

![image](https://user-images.githubusercontent.com/52020637/212632172-c8934263-dfaa-4ae1-9711-20d4ea7246af.png)
Which will show the error.

But if you install with ESLint (I'm sure there is an eternal debate about whether you should or not), it results in these being your packages:
![image](https://user-images.githubusercontent.com/52020637/212632376-d13fddf1-e320-4359-9f7d-12c8ba02573d.png)

If you have ESLint selected, no error.

Now what to do with the actual issue. 
a) This is not a Skeleton issue. 
b) ESLint is something that I would consider mandatory (debatable by other reasonable people) 
c) that this causes an error is probably indicative of an upstream issue more than anything else.

At this point I'm inclined to monitor the problem to assess scope of people affected and whether there is an upstream issue that makes this go away.

**Comment by AgarwalPragy** [comment]
umm.. enabling ESLint seems to have no effect - still gives me the same error.

```
npm run check

> exposed-props@0.0.1 check
> svelte-kit sync && svelte-check --tsconfig ./tsconfig.json


====================================
Loading svelte-check in workspace: /Users/pragy/exposed-props
Getting Svelte diagnostics...

/Users/pragy/exposed-props/src/routes/+page.svelte:5:14
Error: Type 'string' is not assignable to type 'never'. (ts)

<LightSwitch class="some-class" />


====================================
svelte-check found 1 error, 0 warnings, and 0 hints
```

```
bat package.json
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: package.json
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {
   2   │     "name": "exposed-props",
   3   │     "version": "0.0.1",
   4   │     "private": true,
   5   │     "scripts": {
   6   │         "dev": "vite dev",
   7   │         "build": "vite build",
   8   │         "preview": "vite preview",
   9   │         "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
  10   │         "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
  11   │         "lint": "eslint ."
  12   │     },
  13   │     "devDependencies": {
  14   │         "@skeletonlabs/skeleton": "^0.92.2",
  15   │         "@sveltejs/adapter-auto": "^1.0.0",
  16   │         "@sveltejs/kit": "^1.0.0",
  17   │         "@typescript-eslint/eslint-plugin": "^5.45.0",
  18   │         "@typescript-eslint/parser": "^5.45.0",
  19   │         "autoprefixer": "^10.4.13",
  20   │         "eslint": "^8.28.0",
  21   │         "eslint-plugin-svelte3": "^4.0.0",
  22   │         "postcss": "^8.4.21",
  23   │         "svelte": "^3.54.0",
  24   │         "svelte-check": "^2.9.2",
  25   │         "svelte-preprocess": "^5.0.0",
  26   │         "tailwindcss": "^3.2.4",
  27   │         "tslib": "^2.4.1",
  28   │         "typescript": "^4.9.3",
  29   │         "vite": "^4.0.0"
  30   │     },
  31   │     "type": "module"
  32   │ }
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

I've included an ESLint version in the `with-eslint` branch https://github.com/AgarwalPragy/exposed-props/tree/with-eslint

**Comment by AgarwalPragy** [comment]
Honestly, it is pretty obvious where the error is coming from. The error is expected, since the component doesn't declare `class` as a prop. I'm more surprised that you folks are unable to reproduce it.

**Comment by niktek** [comment]
Ok, we are on Mac mini's - there is something definitely needs to be investigate so that we are at least ware of what is going on.  Will report back when I've done so.

**Comment by niktek** [comment]
> Honestly, it is pretty obvious where the error is coming from. The error is expected, since the component doesn't declare `class` as a prop. I'm more surprised that you folks are unable to reproduce it.

No that's the problem - the code that you quoted about the indexer:

```
props: {
    [x: string]: never;
};
```
makes zero sense as that would be about using component as <ComponentName>[someprop] - which is not the case, it has nothing to do with the class prop.

**Comment by AgarwalPragy** [comment]
Oh. I didn't know that.

The error that `npm run check` says `Error: Type 'string' is not assignable to type 'never'. (ts)`, so I just assumed that they're related.

I'm not very good with typescript and its nuances.

**Comment by niktek** [comment]
Also furthermore:

this is the d.ts output for Lightswitch:
```
import { SvelteComponentTyped } from "svelte";
declare const __propDef: {
    props: {
        [x: string]: any;
    };
    events: {
        keyup: KeyboardEvent;
        keypress: KeyboardEvent;
        /** {{ event }} click - Fires when the component is clicked.*/
        click: CustomEvent<any>;
        /** {{ event }} keydown - Fires when the component has keydown event.*/
        keydown: CustomEvent<any>;
    } & {
        [evt: string]: CustomEvent<any>;
    };
    slots: {};
};
export type LightSwitchProps = typeof __propDef.props;
export type LightSwitchEvents = typeof __propDef.events;
export type LightSwitchSlots = typeof __propDef.slots;
export default class LightSwitch extends SvelteComponentTyped<LightSwitchProps, LightSwitchEvents, LightSwitchSlots> {
}
export {};
```

So I can't replicate where you are getting never from as it also doesn't make sense - all components need to be able to have arbitrary values assigned to them due to HTMLspec.  So it's really a case of trying to figure out what is actually happening here.

**Comment by AgarwalPragy** [comment]
That's even more bizzare! On my system, the type shows up as `never`

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/7423639/212639616-af2c35cf-d48a-4478-ab65-65a1a1f49b51.png">

My system is

```
MacBook Pro
13-inch, M1, 2020

Chip: Apple M1
macOS: Ventura 13.1
```

**Comment by AgarwalPragy** [comment]
```
npm -v
9.2.0
node -v
v19.3.0
which npm
/opt/homebrew/bin/npm
which node
/opt/homebrew/bin/node
```

**Comment by niktek** [comment]
Out of curiosity - are you getting these from doing a `package` on your project that doesn't have ESLint ?

**Comment by AgarwalPragy** [comment]
I'm not sure I understand what doing a package means?

These are the steps that I'm following, from scratch

PS: the code is available in the `with-eslint` branch here: https://github.com/AgarwalPragy/exposed-props/tree/with-eslint

```
rm -rf exposed-props/
```
<img width="260" alt="image" src="https://user-images.githubusercontent.com/7423639/212642000-e5a60a6b-7904-4414-8b7e-0b49d793bb1a.png">

```
which node && which npm
node -v && npm -v
```
<img width="250" alt="image" src="https://user-images.githubusercontent.com/7423639/212642104-5084e288-db51-43a7-ab7e-7b18f3466a5c.png">

```
npm create skeleton-app@latest exposed-props
```
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/7423639/212642396-62d85e8c-3c9b-495d-ad82-639b2aa1756b.png">

```
cd exposed-props/
vim src/routes/+page.svelte
# paste in the code
bat src/routes/+page.svelte
```
<img width="628" alt="image" src="https://user-images.githubusercontent.com/7423639/212642663-9f4488bd-3432-4aec-adca-9a34dd4713ab.png">

```
npm run check
```
<img width="586" alt="image" src="https://user-images.githubusercontent.com/7423639/212642847-ecb21e4a-baa4-4b4a-a662-feddcc7c42c3.png">

**Comment by AgarwalPragy** [comment]
This should prove my case once and for all! I've created a dockerfile to guarantee reproducibility! 

DockerFile
```dockerfile
FROM node:19
WORKDIR /usr/src/app
RUN npm create skeleton-app@latest exposed-props -- --types=typescript --prettier=false --eslint --playwright=false --vitest=false --inspector=false --typography=false --forms=false --lineclamp=false -t skeleton --skeletontemplate=bare
WORKDIR /usr/src/app/exposed-props
RUN echo "<script lang='ts'>import { LightSwitch } from '@skeletonlabs/skeleton';</script><LightSwitch class='some-class' />" > ./src/routes/+page.svelte
RUN npm run check
```

Save it to `DockerFile` and run `docker build - < DockerFile`

<img width="997" alt="image" src="https://user-images.githubusercontent.com/7423639/212649411-821e12d6-5145-4d24-8114-da1e438e96e6.png">

**Comment by AgarwalPragy** [comment]
> 1. Is this issue blocking for you - does it prevent your application from running?

Not blocking. Easy workaround is to wrap it into a div and apply the classes on the div

> 2. Can you perhaps try rolling back a version or two and see if the issue was present then

Will test that out tomorrow.

-- --

I understand your situation. Please take your time :)

Honestly, I'm equally surprised at this, since the docker file reproduces my issue and @niktek was able to reproduce my issue too.

**Comment by endigo9740** [comment]
@AgarwalPragy @niktek Sorry for the delay, it's been a busy week. I've finally had a chance to return to this. Here's my findings.

Using Agarwal's repro in the main branch or `with-eslint` branches I am seeing the class error on the LightSwitch:

![Screen Shot 2023-01-19 at 3 32 11 PM](https://user-images.githubusercontent.com/1509726/213566750-b2f47627-e731-4a43-8430-0e7589b6bf2e.png)

Viewing the `LightSwitch.svelte.d.ts` I see the following, not `x: string]: never;` is present:
 
![Screen Shot 2023-01-19 at 3 32 52 PM](https://user-images.githubusercontent.com/1509726/213566914-79600ed9-33eb-4393-ac75-37aa8a2caa46.png)

However, testing another CLI project generate on my computer, I get different results. No error with class, the the `d.ts` file shows type `any`:

![Screen Shot 2023-01-19 at 3 34 20 PM](https://user-images.githubusercontent.com/1509726/213567107-e760ec98-5e9e-4684-8247-7e341ed5afbd.png)

So nothing really new to add here, other than I can reproduce this error with Agarwal's repro, but not with a newly generated CLI app. Until we can find out the reason this type differs we're roadblocked unfortunately.

But, given we now know the issue is introduced as initialization of the project, I've created a zip of a CLI project generated locally on my machine. Feel free to use this as a temporary starting point for new projects until we figure this out. This is based on [v0.92.2](https://github.com/skeletonlabs/skeleton/releases/tag/0.92.2).

[skeleton-0-92-2.zip](https://github.com/skeletonlabs/skeleton/files/10461278/skeleton-0-92-2.zip)

We have a new release dropping on Tuesday of next week - if nothing else maybe give that a shot? I'll sync with Nik to see if we can come up with any other ideas. Sorry for the issues!

**Comment by endigo9740** [comment]
Just for documentation sake I'm running on the following:

- Device: M1 Mac Mini (2020)
- Node/NPM: `v18.8.0`

Here's the `npm list` out put for the newly generated project:

```
skeleton-0-92-2@0.0.1 /Users/chris/Development/testbed/skeleton-0-92-2
├── @skeletonlabs/skeleton@0.92.2
├── @sveltejs/adapter-auto@1.0.2
├── @sveltejs/kit@1.1.4
├── autoprefixer@10.4.13
├── postcss@8.4.21
├── svelte-check@2.10.3
├── svelte-preprocess@5.0.0
├── svelte@3.55.1
├── tailwindcss@3.2.4
├── tslib@2.4.1
├── typescript@4.9.4
└── vite@4.0.4
```

**Comment by AgarwalPragy** [comment]
umm.. this seems to be automagically fixed? 🤣 

Both Skeleton and Sveltekit have received updates. Not sure which contributed to the fix. Still, since it is no longer an issue, I'm closing it 👍

**Comment by endigo9740** [comment]
Well that's the best kind of problem! :) I wonder what did it though?
