### ISSUE TITLE
Inconsistent font-size for headings in version 0.92.0

### ISSUE THREAD

**Issue by AgarwalPragy** [skeletonlabs/skeleton#802]
Note the difference in font-size for the heading titled `Non-Linear Notes` between the below two images

**Comment by endigo9740** [comment]
@AgarwalPragy We are fine tuning and adjusting various styles as an ongoing process. Expect more before we reach v1 status. See our guide for customizing the default element styles if you wish to adjust these.

https://www.skeleton.dev/blog/deep-dive-skeleton-styling

**Comment by AgarwalPragy** [comment]
@endigo9740 The issue seems to be between the development server and production build.

## Reproduce

- Create a new barebones skeleton app using the Skeleton CLI (no extensions)
- Run `npm run dev -- --open`
- Run `npm run build && npm run preview`
- Compare the size of heading b/w the two pages in Desktop view

## Results

### Dev server
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/7423639/212237552-9e967068-a019-4b40-9b04-0f629b8e8cea.png">

### Build Preview
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7423639/212237580-bda96c6d-8b8c-4678-939d-e5f42e521e02.png">


Note that this difference happens in Desktop mode at a screen size of 1440x900. In responsive mode set to Iphone 13, the issue doesn't appear

**Comment by endigo9740** [comment]
@AgarwalPragy This is interesting. Ok, I'll reopen this so we can investigate.

@AdrianGonz97 Styles issues that differ between dev and production make me think of the transpiler. Any thoughts?

**Comment by thefewunshaken** [comment]
It looks like the new opt-in typography feature may have brought this bug back in `1.5.0`? It seems to be overriding the media queries with a dupe of the base styles.

I was able to hack around, and remove the `@tailwind component` directive which removed my duped header styles. I also noticed when also adding `@tailwind component` in the `app.css` (I know I'm not supposed to do that), I noticed a second dupe for the `.h1` styles.  Not sure what's up with that, but I thought that might be helpful 👍🏻

You can easily see all the expected heading styles when you view the page source ~line 30, and the duped one ~`line 1550`

Reproduction steps are the same as above:
- Create a new barebones skeleton app using the Skeleton CLI (no extensions)
- Run `npm run dev -- --open`
- Run `npm run build && npm run preview`
- Compare the size of the headings (Dev font-size is not responsive)

### Dev
<img width="1680" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/31196158/a16e2482-5a54-404f-b674-b14168f5ccdd">

### Build Preview
<img width="1680" alt="image" src="https://github.com/skeletonlabs/skeleton/assets/31196158/4f41ffca-3181-45d7-953c-6aa4bf1e7978">

**Comment by AdrianGonz97** [comment]
@thefewunshaken This has been fixed as part of #1495 and will be released tomorrow.
