### ISSUE TITLE
`<p>` tags don't respect `text-on-X-token`

### ISSUE THREAD

**Issue by AgarwalPragy** [skeletonlabs/skeleton#825]
### Current Behavior

Seems like the color of text inside `<p>` tags is always black or white depending on the dark-mode. It doesn't respect the `text-on-X-token`

### Steps To Reproduce

```html
<p class="bg-primary-500 text-on-primary-token">The quick brown fox jumps over the lazy dog.</p>
<div class="bg-primary-500 text-on-primary-token">The quick brown fox jumps over the lazy dog.</div>
```

<img width="338" alt="image" src="https://user-images.githubusercontent.com/7423639/212403297-2ec077b4-3c6a-4196-877c-a2f87ad363d9.png">

### Anything else?

This is an issue especially when the container has the `text-on-primary-token` set, and there is a `<p>` tag nested inside the container.

**Comment by endigo9740** [comment]
Some properties require `!` to take precedence. In this case you would use:

```html
<p class="bg-primary-500 !text-on-primary-token">Text</p>
```

Optionally, paragraph elements support the `.unstyled` class, which would strip all defaults. So you could do something like this if you do not wish to set `!important`:

```html
<p class="unstyled bg-primary-500 text-on-primary-token">Text</p>
```

We've observed this behavior before, but the source is Tailwind itself. Class inheritance does not match vanilla CSS style inheritance, which can be very confusing the first time you experience it.

**Comment by AgarwalPragy** [comment]
@endigo9740 As I mentioned, this issue is especially troublesome when the container has the `text-on-primary-token` applied.

```html
<div class="bg-primary-500 text-on-primary-token">
    <div>This respects the containers text-color</div>
    <h4>So does this</h4>
    <p>But this does not</p>
</div>
```

The container is being styled. The `<p>` tag is coming from a child component. This, along with svelte's scoped styling behavior makes it so that it is impossible to color the text inside `<p>` tags without passing a class prop to every single component across the entire tree.

**Comment by endigo9740** [comment]
In that case you would need to use:

``html
<div class="bg-primary-500 !text-on-primary-token">
    <div>This respects the containers text-color</div>
    <h4>So does this</h4>
    <p class="unstyled">But this does not, despite the !</p>
</div>
```

Were the P tag was set to `.unstyled`

`<p class="unstyled">`

I agree it's not a ideal solution, but we're juggling a lot of different settings here, including the need to exclude styles on demand. So currently this is the solution I'm aware of.

**Comment by endigo9740** [comment]
One idea might be to exclude the paragraph styles altogether and allow them to inherit from the overall page text colors. I'm going to note this as something to test here:

https://github.com/skeletonlabs/skeleton/issues/782

**Comment by AgarwalPragy** [comment]
In my case, the content is coming from a CMS, so I can't really control it.

This issue isn't due to tailwind as far as I can see https://play.tailwindcss.com/67W7GSQi7a
It seems to stem from the custom `unstyled` class.

**Comment by endigo9740** [comment]
My only concern with the above proposal would be unintended consequences. Folks relying on those to have a hard set color, but then suddenly not. But overall it might be a better experience. It'll definitely require some degree of testing, so I would ask for your patience until we can both get to that ticket, and test this specifically.

Thanks!

**Comment by AgarwalPragy** [comment]
I understand. No hurry - Skeleton is pre-1.0 so changes are a given. Plus one can't complain about FOSS :)

**Comment by AgarwalPragy** [comment]
It seems that code blocks have the same issue? Skeleton seems to be forcing a style on codeblocks which renders all text in primary color for some reason.
I'm trying to use highlight.js to render content coming from a CMS

**Comment by endigo9740** [comment]
@AgarwalPragy I'd recommend creating a new ticket for a new issue. Otherwise it's easy for stuff to get lost.

It depends how you're generating the page and how the content is coming into wether or not you can use a Svelte component like that. For example, on our blog, we don't use our Code Block component, but rather native `pre` tags and utilize Highlight.js directly after mount:

https://github.com/skeletonlabs/skeleton/blob/dev/src/routes/blog/%5Bslug%5D/%2Bpage.svelte#L19
