### ISSUE TITLE
Alignment of <a> on doc site

### ISSUE THREAD

**Issue by niktek** [skeletonlabs/skeleton#830]
### Current Behavior

![image](https://user-images.githubusercontent.com/52020637/212520359-60ad6fc0-e20a-4b51-8672-37debca6b9a3.png)

something for the polish pass- <a> tags spacing is a little weird (from @ryceg :P)

**Comment by endigo9740** [comment]
Folded here: https://github.com/skeletonlabs/skeleton/issues/782#issuecomment-1382430688
