### ISSUE TITLE
Toast `preset` setting currently only works with success and error

### ISSUE THREAD

**Issue by JustBarnt** [skeletonlabs/skeleton#839]
### Current Behavior

Currently when using the Toast utility, the `preset` property only works when using success or error. This is because tailwind classes cannot be constructed dynamically the way its done with the `Toast` component. @endigo9740 Is aware of this bug and request a ticket is made so it doesn't get forgotten

### Work Around
You can just use the `classes` property in `toastSettings` to set the color. E.G `!bg-warning-500`

### Steps To Reproduce

Follow steps on Skeleton.dev for creating a `Toast` element, set preset to "warning" and it defaults to secondary color.

**Comment by endigo9740** [comment]
General idea is we've set this up to dynamically generate the Tailwind class within the toastStore. But Tailwind doesn't allow for this. So we need to instead pass a direct reference for the class through or ensure we expand the Switch/Case to cover all color options.

**Comment by endigo9740** [comment]
@JustBarnt This has been resolved and will be part of the new release next week. Thanks!
