### ISSUE TITLE
[ListBox] Non array objects cannot be used for single selection

### ISSUE THREAD

**Issue by bugproof** [skeletonlabs/skeleton#845]
### Current Behavior

Stores holding non array objects passed in `selected` are treated like array objects

### Steps To Reproduce

 e.g.:

```jsx
const selectedPerson = writable(people[0]);
// ...
<ListBox selected={selectedPerson}>
```

Is not supported.

### Anything else?

Possible fix is adding `Array.isArray` check here:
https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/components/ListBox/ListBoxItem.svelte#L34

**Comment by endigo9740** [comment]
Merging the following from: https://github.com/skeletonlabs/skeleton/issues/846

---

### Current Behavior

This might be expected or not. At least it should be mentioned in the docs. If you try to use `enum` value it naturally starts from 0 so this might not be expected.

### Steps To Reproduce

```jsx
const storeSingle: Writable<number> = writable(0);

<ListBox selected="{storeSingle}" label="Single Selection">
	<ListBoxItem value={0}>Selection Example 1</ListBoxItem>
	<ListBoxItem value={1}>Selection Example 2</ListBoxItem>
</ListBox>
```

### Anything else?

Personally if https://github.com/skeletonlabs/skeleton/issues/845 is fixed  then I wouldn't have this issue.

**Comment by endigo9740** [comment]
@bugproof I've submitted a PR fix here:

- https://github.com/skeletonlabs/skeleton/pull/856

1. I used the `Array.isArray()` syntax to differentiate between single and multiple items. Good call there.
2. I updated the single list docs to be zero-based, which might help clarity.

These changes will be part of the new release on Tuesday of next week. Thanks for the submission!
