### ISSUE TITLE
[ListBox] Undefined behaviour when 0 is passed as selection value

### ISSUE THREAD

**Issue by bugproof** [skeletonlabs/skeleton#846]
### Current Behavior

This might be expected or not. At least it should be mentioned in the docs. If you try to use `enum` value it naturally starts from 0 so this might not be expected.

### Steps To Reproduce

```jsx
const storeSingle: Writable<number> = writable(0);

<ListBox selected="{storeSingle}" label="Single Selection">
	<ListBoxItem value={0}>Selection Example 1</ListBoxItem>
	<ListBoxItem value={1}>Selection Example 2</ListBoxItem>
</ListBox>
```

### Anything else?

Personally if https://github.com/skeletonlabs/skeleton/issues/845 is fixed  then I wouldn't have this issue.

**Comment by endigo9740** [comment]
Included this with #845 so I'm closing this out. We'll address both issues at once time so it's simpler if they're in one place. Thanks for reporting!
