### ISSUE TITLE
Uncaught type error

### ISSUE THREAD

**Issue by gwww** [skeletonlabs/skeleton#854]
### Current Behavior

While "clicking" around, this popped up in the console. 

<img width="1497" alt="Screenshot 2023-01-19 at 12 13 15" src="https://user-images.githubusercontent.com/3060128/213513953-ea466258-2f37-44c5-9d3a-adc4c5b83b28.png">

I'm not sure how to reproduce. It happened when I was on the "File buttons" page and I scrolled down to the bottom.

### Anything else?

I will add more if/when I discover something.

**Comment by endigo9740** [comment]
@gwww I've followed your instructions provided:

1. Opened the doc site in Firefox
2. Navigated to the File Button section
3. Scrolled up and down the page

There's a bunch of warnings, but no error is reported for me:

![Screen Shot 2023-01-19 at 3 03 47 PM](https://user-images.githubusercontent.com/1509726/213559039-cfedf6c3-97eb-4fba-b09a-6617fd36c5b6.png)

Even interacting with the file button itself worked fine.

One suggestion I might have to is browse the site in Incognito. Sometimes when one user is seeing issues and another is not, it can be a rogue extension causing issues. Most extensions should be disabled in Incognito mode which can provide an experience closer to what I'm seeing.

For now there's not enough info for us to act on this, so I'm going to close this ticket. But if you figure out specific steps to reproduce please let me know in this ticket and we can reopen. Thanks.

**Comment by gwww** [comment]
Thanks for looking. I tried for about 30 minutes to reproduce with no luck. I will reopen when it happens again.
