### ISSUE TITLE
skeleton.dev website stops responding,

### ISSUE THREAD

**Issue by manoocher** [skeletonlabs/skeleton#870]
### Current Behavior

In console, it throws a TypeError complaining a missing ('id'). 
Clicking on navigation links changes the url but it doesn't open that page. 

![image](https://user-images.githubusercontent.com/7288815/213992730-2a47ed8c-eb04-4f22-bd73-049d0acdba90.png)

**Comment by endigo9740** [comment]
Already found, fixed, and resolved as part of: https://github.com/skeletonlabs/skeleton/pull/861

This will go live with our next release tomorrow. Thanks!

**Comment by manoocher** [comment]
Great, thanks. Can't wait to see the version 1 release. This is awesome.
