### ISSUE TITLE
Themes: Manual Install instructions

### ISSUE THREAD

**Issue by tafakkur** [skeletonlabs/skeleton#879]
### Link to the Page

https://www.skeleton.dev/guides/themes

### Describe the Issue

The page mentions:
Import your desired preset into `/src/main.js` before your global stylesheet.

This should be either `+layout.svelte` or `hooks.client.js`

### Are you able to create a Pull Request with the fix?

Yes

**Comment by endigo9740** [comment]
@tafakkur I'm so sorry, I'm not sure why that says `main.js`. I think this might be a remnant from removing our previous Astro support. The correct location should be the same as all other stylesheets, in your `/src/routes/+layout.svelte` (the root layout)

Thanks for reporting, we'll get this patched up asap!

**Comment by endigo9740** [comment]
Fixed here: https://github.com/skeletonlabs/skeleton/commit/95afe76a26de1d70480285f31da34746981bdbb3

**Comment by tafakkur** [comment]
@endigo9740 Thanks for the fix.
