### ISSUE TITLE
Bug when updating to skeleton 0.92.2 to  0.99.5 

### ISSUE THREAD

**Issue by PabloRuizCuevas** [skeletonlabs/skeleton#887]
### Current Behavior

I get this error when installing the last verision of skeleton:

node_modules/@skeletonlabs/skeleton/styles/tailwind.css:13:1: The `bg-surface-50-900-token` class does not exist. If `bg-surface-50-900-token` is a custom class, make sure it is defined within a `@layer` directive.

### Steps To Reproduce

Go to package json in a "old" project (2 weeks old) and write:

"@skeletonlabs/skeleton": "^0.99.5",

npm update

### Anything else?

I'm happy to help solving the issue, with a little guidance,

**Comment by endigo9740** [comment]
We've seen this come up a few times, please make sure you have followed the migration steps provided in our release notes here:
https://github.com/skeletonlabs/skeleton/discussions/872

![Screenshot 2023-01-27 at 10 38 32 AM](https://user-images.githubusercontent.com/1509726/215142728-d67e863a-f3fb-4a0a-9a91-e3ff3db3ceab.png)

if the issue persists after that, let us know and we'll help debug.

**Comment by PabloRuizCuevas** [comment]
Does work!, many thanks! it is quite clear there, but I still forgot the dots.
