### ISSUE TITLE
Strange css inheritance for inputs

### ISSUE THREAD

**Issue by Seluj53** [skeletonlabs/skeleton#888]
### Current Behavior

I want to use a dark mode text input, but the border-color isn't right when using dark mode.
I think this is due to intellisense classes that take precedence over the theme defined border-color classes.

I can solve this problem by disabling the skeleton tailwind intellisense plugin.

### Steps To Reproduce

1. Using a text input `<input type="text" />` and @tailwindcss/forms plugin

2. With the svelte config
```js
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
	darkMode: 'class',
	content: [
		'./src/**/*.{html,js,svelte,ts}',
		require('path').join(require.resolve('@skeletonlabs/skeleton'), '../**/*.{html,js,svelte,ts}')
	],
	plugins: [
		require('@tailwindcss/forms'),
		...require('@skeletonlabs/skeleton/tailwind/skeleton.cjs')({ intellisense: true }),
	]
};
```

3. Activate dark mode

4. The `border-color` is not `--color-primary-500` but `--color-surface-500`

### Anything else?

Bug:

<img width="1680" alt="Capture d’écran 2023-01-28 à 00 57 09" src="https://user-images.githubusercontent.com/52790189/215227498-4d869a54-f34d-4e70-8f08-e3e7ee7d0598.png">

It should be:

<img width="1680" alt="Capture d’écran 2023-01-28 à 00 59 25" src="https://user-images.githubusercontent.com/52790189/215227613-039bc4ac-d290-4f1a-964f-595a3194a122.png">

**Comment by endigo9740** [comment]
@Seluj53 I'm not sure I understand your issue. We'll need more info to debug.

You mentioned trying to override input styles, but didn't provide any CSS or inline classes for us to view what you're doing. Please share the exact code you're using and ensure you're using the `dark:` variant to target dark mode.

Additionally, disabling the IntelliSense feature is not intended for folks using the library I don't recommend doing that. That said, you've actually done the opposite, setting `{ intellisense: true }` doesn't disable the IntelliSense portion of the plugin. True would set it enabled.

**Comment by endigo9740** [comment]
Looks like @AdrianGonz97 got this sorted. Merging now and this will be part f the next release.

**Comment by Seluj53** [comment]
Thank you for your help, I'll wait until next release to see if it is resolved and reopen the issue with more information if not.
