### ISSUE TITLE
breadcrumb-nonresponsive does not seem to work with 0.99.5

### ISSUE THREAD

**Issue by polyzen** [skeletonlabs/skeleton#889]
### Current Behavior

breadcrumb-nonresponsive behaves the same as breadcrumb

### Steps To Reproduce

```html
 <ol class="breadcrumb-nonresponsive">                       
   <li class="crumb"><span>🏠</span><a href="/">Home</a></li>
   <li class="crumb-separator" aria-hidden>&rsaquo;</li>     
   <li class="crumb"><a href="/Blah">Blah</a></li>           
   <li class="crumb-separator" aria-hidden>&rsaquo;</li>     
   <li>Current</li>                                          
 </ol>                                                       
```

**Comment by endigo9740** [comment]
Hey @polyzen unfortunately this bit of code isn't operating as expected:
https://github.com/skeletonlabs/skeleton/blob/master/src/lib/styles/elements/breadcrumbs.css#L8

This will be the fix:
```css
.breadcrumb,
.breadcrumb-nonresponsive {
	@apply flex items-center space-x-4 w-full hide-scrollbar overflow-x-auto;
}
```

We'll get this in place and it'll be resolved in the next release. Sorry the trouble!

**Comment by polyzen** [comment]
Sorry thought I had created a PR, doing that now.
