### ISSUE TITLE
Add note regarding `vitePreprocess` configuration

### ISSUE THREAD

**Issue by cesarnml** [skeletonlabs/skeleton#891]
### Link to the Page

https://www.skeleton.dev/guides/tailwind

### Describe the Issue

Currently when one creates a SvelteKitv1.0.0 project via `npm create svelte@latest` the default `config.preprocess` is `vitePreprocess()` from `@sveltejs/kit/vite`, but this needs to be configured as `vitePreprocess({postcss: true})` in order for Skeleton's `theme-[preset].css` and `all.css` to be imported properly. 

It would be nice to note this required config change in `svelte.config.js`, because the resulting import bug is rather difficult to troubleshoot for beginners 🙂.

The above only applies to the **Manual Install** documentation.

### Are you able to create a Pull Request with the fix?

Yes

**Comment by niktek** [comment]
Worked through this on Discord and made the relevant updates in the CSA CLI
