### ISSUE TITLE
Add more preview examples in Theme Generator

### ISSUE THREAD

**Issue by AgarwalPragy** [skeletonlabs/skeleton#893]
When using the theme generator, it displays various elements and their variants on top of the `surface` color.

However, when the container itself uses a `variant-filled-X` token - for example in alerts, cards, and toasts, the various elements like links, buttons, and others end up looking bad.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
This may be related to the other issue you mentioned here:
https://github.com/skeletonlabs/skeleton/issues/894

Let's circle back and test this after that has been resolved.

**Comment by AgarwalPragy** [comment]
> This may be related to the other issue you mentioned here:
> 
> * [`text-on-X-token` isn't respected inside `alert` containers in dark-mode #894](https://github.com/skeletonlabs/skeleton/issues/894)
> 
> Let's circle back and test this after that has been resolved.

This is more about allowing the client to choose better colors when deciding the theme.

For example, on the [Theme Generator page](https://www.skeleton.dev/guides/themes/generator) the preview section uses a card with a forced transparent background `<section class="card !bg-transparent p-4 space-y-8 col-span-2 lg:col-span-1">` and looks like the following

<img width="512" alt="image" src="https://user-images.githubusercontent.com/7423639/215288529-695ce64b-73ee-4cfd-ab9b-9b0b67df624a.png">


If on the other hand we use a `variant-filled-X` token `<section class="card variant-filled-success p-4 space-y-8 col-span-2 lg:col-span-1">` it looks really ugly

<img width="514" alt="image" src="https://user-images.githubusercontent.com/7423639/215288703-f35d16c8-c036-4a8e-a630-6530342b919f.png">

Additionally, Skeleton renderes `a` tags with `color: rgb(var(--color-primary-500) / var(--tw-text-opacity));` and the chosen primary color often looks bad on success, error and warning backgrounds.

Using a color variant for containers like cards, alerts and toasts is a common usecase.

**Comment by endigo9740** [comment]
Well that's what this tool is for, giving you a preview of how colors are affecting things, and giving you the opportunity to adjust as needed. I'm not sure we can build any sort of intelligence into this to prevent bad color combinations, because a lot of times that's about personal preference in aesthetics.

@ryceg is, however, working on some mechanism to giving you a better indication of color ratios for a11y in regards to "on" colors. You can track progress on that change here:
https://github.com/skeletonlabs/skeleton/pull/847

He's also investigating a means to provide better quality color steps using HSL colors here:
https://github.com/skeletonlabs/skeleton/pull/858

But as for "what looks good", that's where the saying "beauty is in the eye of the beholder" comes in. I'm not sure there's anything more programmatic that can be done to affect that. At least not with a level of effort that's beyond the scope of what we had in mind for this tool.

**Comment by endigo9740** [comment]
@AgarwalPragy Also just to make sure you're aware, you're not confined to the theme generator page and the handful of elements presented there. You can navigate the ENTIRE documentation site while Edit mode is enabled. The entire site reflects to your generated theme.

**Comment by AgarwalPragy** [comment]
I agree that adding intelligence to prevent bad color choices is a difficult task.

This is precisely why I'm suggesting adding more examples in the preview section 😅 

If the user can see what various elements look like not just on the surface background but also on other background colors, it will allow the user to make better color choices.

**Comment by AgarwalPragy** [comment]
> @AgarwalPragy Also just to make sure you're aware, you're not confined to the theme generator page and the handful of elements presented there. You can navigate the ENTIRE documentation site while Edit mode is enabled. The entire site reflects to your generated theme.

Yes, but the website doesn't have any examples of links / buttons and other styled elements on top of containers with color variants!

**Comment by endigo9740** [comment]
I mean yeah, but where do we draw the line here? We're not going to be able to cover every single combination of every single element or container in the library.

If you need to preview a particular combination of elements, take the theme, drop it into your project, build the combination of features you want and preview them there.

I'm not sure we're going to be able to solve the issue you're facing with the generator so I'm going to go ahead and close out this thread. I appreciate the suggest, but again, we can only do so much. Right now the generator is meeting our expectations so we'll leave it at that.

**Comment by AgarwalPragy** [comment]
I understand. No worries. 😄 

-- --

> I mean yeah, but where do we draw the line here? We're not going to be able to cover every single combination of every single element or component in the library.

Every color combination is needed (6*6), not every component combination.

1. Put the preview items inside a tabbed container. Different tabs show various elements inside a different variant of the container
2. Add some preview items for text and links

<img width="776" alt="image" src="https://user-images.githubusercontent.com/7423639/215292544-e0a83be7-e52e-485d-b780-26b36c6f4e46.png">

**Comment by endigo9740** [comment]
@AgarwalPragy even though I've closed this out I will keep your suggestions in mind. The main reason I'm not keen to do this YET, is that things are still in flux. Perhaps once things settle down we can revisit this idea?
