### ISSUE TITLE
Nested AccordionGroups doesn't work

### ISSUE THREAD

**Issue by mifegui** [skeletonlabs/skeleton#895]
### Current Behavior

When you nest an AccordionGroup inside an AccordionItem that is inside another AccordionGroup, toggling the last AccordionTiem also toggles the AccordionItem on the first AccordionGroup.

### Steps To Reproduce

Having this structure:
```html
<AccordionGroup spacing="space-y-0" class="border-2 drop-shadow-xs w-full mr-2">
	<AccordionItem regionSummary="font-bold">
		<svelte:fragment slot="content">
			<AccordionGroup class="border-2 drop-shadow-xs w-full mr-2">
				<AccordionItem>
					<svelte:fragment slot="content">Ni hao</svelte:fragment>
				</AccordionItem>
			</AccordionGroup>
		</svelte:fragment>
	</AccordionItem>
</AccordionGroup>
```
		
I can't open the second AccordionItem. Clicking on it closes the first AccordionItem.

A workaround is to put collapse={false} on the first AccordionGroup.

**Comment by endigo9740** [comment]
Hi @mifegui that's a kind of strange behavior, we never really built the accordion with this use case in mind. It seems like a sub par user experience. I might suggest looking into alternative ways to display your UI.

That said, if you're determined to go tris route, I might suggests you wait and test this again in the next release. We've actually refactored and rebuilt the accordion. It operates in a means where state won't spill from one accordion into another. You can preview this here:
https://skeleton-docs-git-chore-component-actions-6f245c-skeleton-labs.vercel.app/components/accordions

In additional to the state being more embedded, this also comes with some cosmetic improvements, such as the animation open/close. And the collapse modes are a bit easier to use:

1. By default any child can be opened and closed independently
2. By setting the `autocollapse` prop only one child item can be open at a time (the demo shows this)

Given the bug you're experiencing is in a version of the component that's no longer component, I'll go ahead and close this ticket out. Please do report back if you have issues with the next release though. That release is scheduled to drop a week from this upcoming Tuesday.

Thanks!
