### ISSUE TITLE
Sticky header in table

### ISSUE THREAD

**Issue by AlexBitsTech** [skeletonlabs/skeleton#898]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I do not know if this can currently be done (I've already spent a few hours on this and haven't succeeded) but it would be great if the table headers (on the simple table in my case, not the datatable) could stay on screen when scrolling down.  
To precisely describe my use case, I am using your table style (with container) with the svelte-headless-table framework.

Is there any way to make this possible with the code as is?

Thanks in advance for the help.

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
@AlexBitsTech we had this question come up on Discord a couple days ago. I'll refer you to the post here if you can access it:
https://discord.com/channels/1003691521280856084/1067852301492039761/1067852301492039761

You might need to join our Discord first to view this:
https://discord.gg/EXqV7W8MtY

The short version is it is possible, some code snippets were shared there, and we're going to look to implement this as a proper feature in the near future. Possibly the next release or the one following.

**Comment by endigo9740** [comment]
Given this is already mentioned in the Tables section here:
https://github.com/skeletonlabs/skeleton/issues/857#issue-1550029193

You are more than welcome to close out this ticket if you're keen to wait on those changes. This will help prevent duplicate issues. Thanks!

**Comment by AlexBitsTech** [comment]
The temporary fix suggested on the discord page has worked perfectly for me.
Thank you very much for the quick help!
Closing this issue as it is a ducplicate.
