### ISSUE TITLE
Customize Prompt Modal's Submit disabled State

### ISSUE THREAD

**Issue by ranielzed** [skeletonlabs/skeleton#899]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It would be nice if we can customize when the submit button is disabled or not based on the prompt value.

This would limit the possible values for prompt value

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Solved as part of: https://github.com/skeletonlabs/skeleton/issues/922

Closing this ticket. Please refer any further comments to the ticket linked above.
