### ISSUE TITLE
Accordion Summary caret scales down with more lines on the summary

### ISSUE THREAD

**Issue by zachsa999** [skeletonlabs/skeleton#907]
### Current Behavior

In the accordian Component the caret shrinks when there are multiple lines in the Summary. 

To replicate open Chrome devtools at  set mobile view and shrink down the width of the page. Here's a screenshot
<img width="417" alt="image" src="https://user-images.githubusercontent.com/56491639/216078731-0b327edf-a50f-43cd-bdda-6deee56189ed.png">

### Steps To Reproduce

1. Open chrome devtools at the url [https://www.skeleton.dev/components/accordions](https://www.skeleton.dev/components/accordions)
2. Set mobile view and shrink down the page to 318 or less
3. Add text to the page if wanting an extreme case.

### Anything else?

Solution. Add a static width to the Caret?

**Comment by endigo9740** [comment]
Hey @zachsa999, so I've recently complete a rebuild of the Accordion as part of this ticket:
https://github.com/skeletonlabs/skeleton/issues/857

The entire underlining markup and styles are different than before, so I went ahead and tested. Doesn't look like this is an issue any further:

![Screenshot 2023-02-01 at 10 50 49 AM](https://user-images.githubusercontent.com/1509726/216108527-b52f945d-6f14-425e-8f48-8ced55c633b1.png)

You can expect this to be part of the release on Tuesday of next week (US time), and you're welcome to try it here. Use your inspector tool in Chrome to manipulate the markup on the page:
https://skeleton-docs-git-chore-component-actions-6f245c-skeleton-labs.vercel.app/components/accordions

Thanks for reporting though!
