### ISSUE TITLE
Toast enhancement

### ISSUE THREAD

**Issue by shadowempire123** [skeletonlabs/skeleton#909]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Hi,
could you please add the possibility to hide the Close button -> The circle with the X -->  (X)
https://www.skeleton.dev/utilities/toasts
For my use case it is just necessary to have short toast which disappears after 2 seconds.

for example use the parameter closeButton:
```
toastStore.trigger({
   preset: 'error',
   autohide: true,
   timeout: 2000,
   closeButton: false,
   message: 'Please select the Option x!'
})

```
thx

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@shadowempire123 2 seconds is pretty short, is that long enough for people to read the messages you're showing? If this is for an app yourself you might have a peer, friend, or family member try to read that and see if it's enough time.

Generally speaking removing the close button is not great UX. However, a solution does exist for you if you need to do this via CSS:

```css
.toast button { display: none; }
```

If you want to selectively target only certain instances you would use the `classes` setting on the toast payload, then do something like:

```css
.my-custom-class button { display: none }
```

It just occurred to me that we don't have a named selector class for the element wrapping buttons in toasts, but I'll put that on my list to resolve. That most likely won't make it this upcoming release, but the one after.

It'll be something like `.toast .toast-actions`
