### ISSUE TITLE
Property to place cursor on the left hand side in a prompt modal

### ISSUE THREAD

**Issue by lem6ns** [skeletonlabs/skeleton#925]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

![image](https://user-images.githubusercontent.com/62519659/216799510-26a59fb4-139b-4660-8b1b-06b1a5769ffd.png)

Pseudo-code:
```ts
const prompt: ModalSettings = {
            type: "prompt",
			title: "Rename File",
			body: "Enter the new name for \"x.png\".",
			value: ".png",
			cursor: "left" // "left" || "right",
			...
}
```

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

Google Drive File Rename Prompt

**Comment by endigo9740** [comment]
@lem6ns I"m not really seeing a sane way to do this. I don't really understand the use case either. Users are typically going to either:

1. Continue writing, which means the cursor is best left at the far right of the contents
2. Select all and delete (control/command + a, then delete on your keyboard)

For now I'm going to mark this "won't fix" and close this issue. I do encourage you to look at the host of other updates coming here though:
https://github.com/skeletonlabs/skeleton/issues/922
