### ISSUE TITLE
Caret is not present in Accordion in Safari

### ISSUE THREAD

**Issue by huantrinh1802** [skeletonlabs/skeleton#926]
### Current Behavior

![Screen Shot 2023-02-05 at 16 05 50](https://user-images.githubusercontent.com/6076614/216802773-892c3032-5685-4f8d-915b-2e228b8a23dc.png)

I am implemented the accordion with dynamic items. In Firefox and Chrome, I can see the caret as the attached screenshot (left) but in Safari (version 16.3 (17614.4.6.11.4, 17614), I cannot see the caret. 

### Steps To Reproduce

1. Using the default accordion

**Comment by endigo9740** [comment]
@huantrinh1802 we have rebuilt the accordion as part of the next release coming on Tuesday. You can preview it here:
https://dev.skeleton.dev/components/accordions

Per:
https://github.com/skeletonlabs/skeleton/issues/857

Any issues with the prior version of the accordion are no longer relevant. Please retest on the new version and if the issues persists let us know. But I'd anticipate it will work as intended.
