### ISSUE TITLE
Remove btn-base class

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#927]
### Current Behavior

Currently, the ``btn-base`` class gets suggested with autocomplete when typing ``btn`` although it shouldn't be necessary to get a button of the correct default size, the class should be removed.

It should also be removed in the docs:
https://github.com/skeletonlabs/skeleton/blob/3f2287605da10b0dffc693523f5d0852cfd7b04d/src/routes/(inner)/elements/buttons/+page.svelte#L33

### Steps To Reproduce

Got to:
https://github.com/skeletonlabs/skeleton/blob/3f2287605da10b0dffc693523f5d0852cfd7b04d/src/lib/styles/elements/buttons.css#L34

The class is included and will therefore get suggested during autocomplete

**Comment by endigo9740** [comment]
Removed as part of: https://github.com/skeletonlabs/skeleton/commit/d94732d702c43bd030e67bf382dfbb7b2f1b9a54
