### ISSUE TITLE
Can no longer override all button classes on Paginator

### ISSUE THREAD

**Issue by knd775** [skeletonlabs/skeleton#934]
### Current Behavior

When setting the `buttonClasses` prop on the Paginator component, `btn-icon` is not overridden, leading to styling issues with text more than a couple characters long.

Before `0.124.2`:
![before](https://user-images.githubusercontent.com/1235055/217330792-13210a7e-fee4-4366-af71-bbfe781b7e4c.png)

After:
![after](https://user-images.githubusercontent.com/1235055/217330808-498c828f-0391-4c07-99dd-75da9cbc7c93.png)

### Steps To Reproduce

1. Use paginator with `buttonClasses` and text labels for the buttons
```svelte
<Paginator
  bind:settings={$tableStore.pagination}
  buttonClasses="btn variant-filled"
  buttonTextPrevious="Previous"
  buttonTextNext="Next"
  {disabled} /
```

**Comment by endigo9740** [comment]
FYI the fix is to move `btn-icon` from the inline HTML button classes, back up to the `buttonClasses` prop. I'd welcome a PR if someone can jump on this sooner than myself!
