### ISSUE TITLE
Make confirm modal async

### ISSUE THREAD

**Issue by jrsamuel** [skeletonlabs/skeleton#937]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It seems like a common use case for the confirm Modal in SvelteKit will be to confirm something BEFORE a Form Action is submitted.  While SvelteKit provides a SubmitFunction for use:enhance, you can't easily wait for the response of the Modal confirm before the form is submitted to the server.

Something like...
```
 async function confirmDelete(cancel) {
    const confirm: ModalSettings = {
      type: 'confirm',
      title: 'Are you sure you wish to delete?',
      body: 'This will delete things. ',
      buttonTextCancel: 'Cancel',
      buttonTextConfirm: 'Delete',
    }
     const res = await modalStore.trigger(confirm)
     if (!res) cancel()
    // otherwise submission continues
  }



<form ... use:enhance={({cancel}) => confirmDelete(cancel}>
// cancel function is supplied by enhance
```

BTW, I've been coding for a while and this is the first issue I have ever filed.  It is because I like Skeleton UI so much and I want it to get better. Hope my proposal is clear.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

Here is an example from SweetAlert...

```
Swal.fire({
  title: 'Do you want to save the changes?',
  showDenyButton: true,
  showCancelButton: true,
  confirmButtonText: 'Save',
  denyButtonText: `Don't save`,
}).then((result) => {
  /* Read more about isConfirmed, isDenied below */
  if (result.isConfirmed) {
    Swal.fire('Saved!', '', 'success')
  } else if (result.isDenied) {
    Swal.fire('Changes are not saved', '', 'info')
  }
})

```

**Comment by endigo9740** [comment]
Noting the Discord discussion for this topic here:
https://discord.com/channels/1003691521280856084/1072620613908316260

**Comment by endigo9740** [comment]
Reference: https://sweetalert.js.org/guides/

**Comment by endigo9740** [comment]
FYI I did give this a quick look as part of: https://github.com/skeletonlabs/skeleton/issues/922

Unfortunately I think this is going to be beyond the current scope of our current iteration of the Modal feature. The issue being we'll need to make asynchronous tasks operate within a reactive store queue. This is going to take further researching and prototyping before we have a definitive answer to how this can implemented.

Given this I'm bumping this from the pre-v1 milestone to post-v1 milestone. I do very much want to have a solution for this, but currently our timeline isn't going to allow this right now. I appreciate your understanding.

This ticket will remain and we'll get back to it asap. Not ETA for that right now though.

**Comment by endigo9740** [comment]
@jrsamuel so a thought just occurred to me - have you tried wrapping the entire modal process in a JS Promise?

```ts
function doSomething(): void {
    new Promise((resolve) => {
        const d: ModalSettings = {
            type: 'confirm',
            title: 'Please Confirm',
            body: 'Are you sure you wish to proceed?',
            response: (r: boolean) => {
                resolve(r);
            }
        };
        modalStore.trigger(d);
    }).then((r: any) => {
        console.log('response:', r);
        // (handle the submissions here based on the response)
    });
}
```

General idea is when `doSomething()` is triggered it immediately generates the promise and triggers the confirm modal. When the modal response is triggered, the promise is resolved. When this is resolved then `then()` block is triggered. You then have an async pattern for your modal.

It's a bit of work around, but totally valid way to tackle this for now.

**Comment by endigo9740** [comment]
No response so we'll assume this worked or this is no longer an issue. Closing this out for now.

**Comment by jrsamuel** [comment]
Sorry, I've been on vacation.  I like the idea you suggested.  I will make that work until a longer term solution is done.  Thanks for the response.

**Comment by zachsa999** [comment]
This is cool, thanks
