### ISSUE TITLE
Currently selected select Elements in Dark Theme have very low contrast

### ISSUE THREAD

**Issue by Sarenor** [skeletonlabs/skeleton#940]
### Current Behavior

By default, Selects look pretty good in Dark theme:
<img width="446" alt="image" src="https://user-images.githubusercontent.com/31982384/217528777-fdfdfd7a-64f5-42d2-991f-edd57c4201ca.png">
As soon as an element is actively clicked and selected by the mouse, the ``color`` changes to white automatically which leads to very low contrast:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/31982384/217528976-1df937c6-10b4-437a-8f0f-81eb13f26919.png">

I would have thought that something like
```css
	.select option::selection {
		@apply text-surface-50-900-token;
	}
```
Would fix that but I couldn't get it to work because my CSS-Fu is to weak.

### Anything else?

1) Go to http://localhost:5173/elements/forms
2) Make sure your selected theme is in dark mode
3) Click on a select option

**Comment by endigo9740** [comment]
The issue with this one is it's a hack of sorts to apply the background color to select elements at all - actually using a gradient that fades from two version of the same color. It's not just a normal "background = whatever" situation.

Given this, the only way I can get consistent results seems to be using a primary color, which uses the same text color for either light or dark mode. This provide the desired results - even if it's more opinionated. This will do for now.

![Screenshot 2023-02-10 at 11 14 55 AM](https://user-images.githubusercontent.com/1509726/218154527-39a443b8-76fc-4aa3-9947-e686dfe3bc98.png)
