### ISSUE TITLE
RadioItem on:click event triggers twice

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#956]
### Current Behavior

As reported by @SebasF1349 on Discord.

```html
<RadioGroup>
  <RadioItem bind:group={date} on:click={dateChange} name="date" value={'week'}>week</RadioItem>
  <RadioItem bind:group={date} on:click={dateChange} name="date" value={'month'}>month</RadioItem>
</RadioGroup>
```

### Steps To Reproduce

When a log is set in `dateChange()` it triggers the following:

1. The on:click event triggers twice (one with pointerType: "mouse", the other one with pointerType: "").
2. Date updates "later". If someone press on month, date is still equal to week (the default). You need to click again in month to see it update (the same happens if then I want to change to week). It's like dateChange is being run way before date changes.

### Anything else?

My current theory is that the component forwards `on:click` on the Label, but when clicked the label triggers a click on the hidden input within as well. This hidden input uses `restProps`, so MAYBE the `on:click` is being passed redundantly to to this input?

If this is the case, we should check other form elements, which use a similar pattern, such as listbox.

**Comment by SebasF1349** [comment]
I can confirm that my guess with the second point is correct. `dateChange` is async and if I log at the start and at the end the value of `date` is different.

**Comment by endigo9740** [comment]
I created a REPL to try and replicate this issue, sure enough the click event on the label causes a dupe:
https://svelte.dev/repl/c4c89b56a7b146609a352ee18e6f64a1?version=3.55.1

```html
<label on:click on:keypress>
    <input type=radio bind:group {name} {value}>
    <slot />
</label>
```

However if we move the event forwarding to the Input, it's no longer duped:

```html
<label>
    <input type=radio bind:group {name} {value} on:click on:keypress>
    <slot />
</label>
```

This will be the fix. Note that other form components that use a combination of wrapping Label element + hidden Input.

**Comment by endigo9740** [comment]
@SebasF1349 I've gone ahead and filed this as a bug ticket on Svelte's side as well. Not sure they can do anything with it, but it's definitely not expected behavior:
https://github.com/sveltejs/svelte/issues/8278

**Comment by endigo9740** [comment]
@SebasF1349 I ended up addressing this for Listbox, RadioItem, and Tabs which all have a similar structure. Instead of moving ALL events to the hidden input, I only moved `click` and added `change`. This should now work as expected.

**Comment by SebasF1349** [comment]
Confirmed: on:click only triggers once now and the on:change event is exactly what I needed. Thanks!
