### ISSUE TITLE
Movable Modals

### ISSUE THREAD

**Issue by jamesnewportbeach** [skeletonlabs/skeleton#959]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

We want the modals to be movable. Great work so far!!!

### What type of pull request would this be?

None

**Comment by Sarenor** [comment]
There's an ongoing polishing pass for Utilities, which modals are a part of.
If you could provide some more examples of what you mean with "movable modals". maybe an example from another framework or something similar, that may be incorporated there: https://github.com/skeletonlabs/skeleton/issues/922
