### ISSUE TITLE
Range sliders Min props 

### ISSUE THREAD

**Issue by jfinet** [skeletonlabs/skeleton#962]
### Current Behavior

The range sliders min property doesn't seem to work as attended. 

I set up `min: 100` to the `RangeSlider` prop, and still manage to set the `value: 0` when sliding the cursor to the far left of the slider (screenshot attached below)

### Steps To Reproduce

```ts
$: props = {
	label: "Collection size",
	value: 100,
	min: 100,
	max: 10000,
	step: 100,
	ticked: false,
	accent: "!accent-secondary-500",
};
```

```html			
<svelte:component
	this={RangeSlider}
	name="range-slider-example"
	label={props.label}
	bind:value={props.value}
	max={props.max}
	step={props.step}
	ticked={props.ticked}
	accent={props.accent}
	class="w-full max-auto"
>
	<div class="flex justify-between items-center">
		<div class="font-bold">{props.label}</div>
		<div class="text-xs">{props.value} / {props.max}</div>
	</div>
</svelte:component>
```

### Anything else?

<img width="967" alt="Screenshot 2023-02-12 at 20 09 12" src="https://user-images.githubusercontent.com/112434201/218332437-5b59465e-f7ad-4c82-8069-90ec02194e67.png">

The [documentation](https://www.skeleton.dev/components/range-sliders) is off. The rows are shifted:
<img width="643" alt="Screenshot 2023-02-12 at 20 02 56" src="https://user-images.githubusercontent.com/112434201/218332429-df6b426b-6526-41c3-bb5e-ac8f1c52404f.png">

**Comment by endigo9740** [comment]
I've corrected the mismatched prop descriptions. As discussed on Discord the other issues reported are related to breaking the rules define - you're setting a value below your minimum.

![Screenshot 2023-02-16 at 4 13 46 PM](https://user-images.githubusercontent.com/1509726/219499064-c5d170ed-7a93-487a-826b-1a1a10f7a670.png)
