### ISSUE TITLE
Undocumented classes  `listbox`,  `listbox-item`, `listbox-label`, `listbox-label-lead`, `listbox-label-content`, and `listbox-label-trail`

### ISSUE THREAD

**Issue by AgarwalPragy** [skeletonlabs/skeleton#963]
### Link to the Page

https://www.skeleton.dev/components/listboxes

### Describe the Issue

The classes `listbox`,  `listbox-item`, `listbox-label`, `listbox-label-lead`, `listbox-label-content`, and `listbox-label-trail` are being used in the components (although I can't find any place that they're defined)

https://github.com/skeletonlabs/skeleton/blob/bf4dde5aa499fa3b404fa36a7af7944c74a59910/src/lib/components/ListBox/ListBox.svelte#L42
https://github.com/skeletonlabs/skeleton/blob/bf4dde5aa499fa3b404fa36a7af7944c74a59910/src/lib/components/ListBox/ListBoxItem.svelte#L75
https://github.com/skeletonlabs/skeleton/blob/bf4dde5aa499fa3b404fa36a7af7944c74a59910/src/lib/components/ListBox/ListBoxItem.svelte#L95
https://github.com/skeletonlabs/skeleton/blob/bf4dde5aa499fa3b404fa36a7af7944c74a59910/src/lib/components/ListBox/ListBoxItem.svelte#L97
https://github.com/skeletonlabs/skeleton/blob/bf4dde5aa499fa3b404fa36a7af7944c74a59910/src/lib/components/ListBox/ListBoxItem.svelte#L99
https://github.com/skeletonlabs/skeleton/blob/bf4dde5aa499fa3b404fa36a7af7944c74a59910/src/lib/components/ListBox/ListBoxItem.svelte#L101

### Are you able to create a Pull Request with the fix?

None

**Comment by endigo9740** [comment]
Search for `selector` classes in this tutorial post, we cover the use case for these:
https://www.skeleton.dev/blog/deep-dive-skeleton-styling

Likewise we cover this in the Styling documentation (near the bottom):
https://www.skeleton.dev/guides/styling
![image](https://user-images.githubusercontent.com/1509726/218341304-5e3fbf9f-f348-4f4b-88b5-4e96d139c8dd.png)

**Comment by AgarwalPragy** [comment]
Ah, interesting. Thanks!
