### ISSUE TITLE
Accordion: Allow the default caret positions to be changed, for both open & closed, when required

### ISSUE THREAD

**Issue by jasonahern** [skeletonlabs/skeleton#965]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

When an Accordion is used within the AppBar --> sidebarLeft, from a UI perspective it's more natural for the Accordion's default caret position to be pointing towards the right, when closed, for the caret to then point downwards, on open, on a full desktop app.

Granted that the default caret positions make sense when used on mobile, or in the middle of a layout, but when the Accordion is used on the left-hand side of a full desktop layout, the following change feels more natural.

Therefore, please can you consider adding in the ability to do the following :

![image](https://user-images.githubusercontent.com/21026263/218568087-172265de-7be2-432a-a661-3a6101f5af33.png)

![image](https://user-images.githubusercontent.com/21026263/218568726-56289ce4-2943-4097-9943-bfa31f7adf03.png)

### What type of pull request would this be?

Enhancement

**Comment by endigo9740** [comment]
Just a quick note - if we set props to control the reactive rotation states this should provide easy customization:

```ts
$: classesCaretState = openState ? 'rotate-180' : '';
```

Becomes

```ts
export let caretOpen = 'rotate-180';
export let caretClosed = '';

$: classesCaretState = openState ? caretOpen : caretClosed;
```

**Comment by endigo9740** [comment]
This can now be configured through two new props:

``
caretOpen = ''
caretClosed = '-rotate-90'
```

Preview:

![Screenshot 2023-02-16 at 4 19 44 PM](https://user-images.githubusercontent.com/1509726/219500489-d9003d46-38c6-4644-a5cd-eae6259e68a8.png)
