### ISSUE TITLE
Tooltip "regionTooltip" prop cannot take multiple classes

### ISSUE THREAD

**Issue by noblepen8723** [skeletonlabs/skeleton#967]
### Current Behavior

When trying to style a tooltip on a button, using multiple classes on a regionTooltip prop breaks things and yields `Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('text-sm uppercase') contains HTML space characters, which are not valid in tokens.` in console.

### Steps To Reproduce

`<button class="btn variant-filled-primary" use:tooltip={{ content: 'Hello', regionTooltip: 'text-sm uppercase' }}>I'm a button</button>`

Using a single regionTooltip class yields the expected result.

### Anything else?

My apologies if I'm just making a dumb mistake here!

**Comment by endigo9740** [comment]
@noblepen8723 Just FYI we're in the midst of changes to how Utility features like Tooltips work:
https://github.com/skeletonlabs/skeleton/issues/922

It's very likely these will work in a different fashion in the next release. I'll circle back on this and try to test and confirm soon. But keep an eye out for the next release.

**Comment by endigo9740** [comment]
Please refer to: https://github.com/skeletonlabs/skeleton/issues/922

As of the last couple days we've completely replaced Menus/Tooltips with a new "Popups" feature, which you can preview here:
https://skeleton-docs-git-chore-utilities-polish-pass-skeleton-labs.vercel.app/utilities/popups

Tooltips now operate much more like Menus, where the popup UI itself is created locally (like a sibling to the trigger). This means all styles can be set directly on the UI you're generating. It's a lot simpler and more intuitive. I think folks are going to enjoy it. 

Given this, the issue in the original post is no longer relevant, so I'm closing this out. Expect to see these changes alongside the new release on Tuesday (US time) next week! Thanks!
