### ISSUE TITLE
Revisiting usage of the app shell without named slots...

### ISSUE THREAD

**Issue by bertmad3400** [skeletonlabs/skeleton#968]
### Current Behavior

_(Due to the relatively complex nature of this problem, I decided against going to the Discord, and choose to open an actual issue instead. I hope this is within the realms of what is allowed to open an issue for, and if not, I'm genuinely sorry for having wasted your time)_

Hi there!

Back when the app shell component was introduced in #158, it was discussed how it would be beneficial if it was possible to use named slots, to use the app shell with nested layouts, with the purpose of having each +layout.svelte file add to a different section of the app shell. As inheriting named slot from a parent layout was never implemented in SvelteKit, this was unfortunately not a possibility, and the Skeleton framework stuck with a more "component-like" approach, where the app shell is supposed to be imported like a component, and then filled out with other components. The problem here is that when dealing with more complex applications, this - in my experience at least - makes the app shell - which is otherwise a great concept - more or less useless, and therefore I kind of wanted to revisit this issue. Following will be an example of when this could be problematic:

Take a SvelteKit app with the following structure:

**routes**
- +layout.svelte
- +page.svelte
- **feed**
  - +layout.svelte
  - +layout.ts
  - +page.svelte
- **blog**
  - +layout.svelte
  - +layout.ts
  - +page.svelte

Here, much like the webpage at https://www.skeleton.dev, the layout.svelte at the root would be containing a topbar, that should be persistent for every page on the site, and the page.svelte at the root would be containing a standard hero and possibly some navigation to the sub-pages like /feed.

The problem now arise if subpages like /blog and /feed need to have their own structural elements (like a sidebar), that's different for every subpage, a problem that only becomes larger if the content of this structural element is dynamically generated/queried from external source. As the layouts are nested, it doesn't make much sense to have a shell in the root layout along with one in every sub-layout, and trying to get around it with a component based approach really doesn't do the routing system in SvelteKit justice. While it would be possible to make the sidebar a separate component for every  single subpage, this would not only need to result in some messy conditional logic in the root layout, along with completely decoupling every sidebar from the corresponding route, but should the content of the sidebar need to be dynamically generated, then this logic would also have to be moved from the layout.ts to a completely different place.

How do you deal with this problem? To me it seems like the simplest way of handling this would be to simply not use the app shell, despite the fact that it is a great concept.

**Comment by Sarenor** [comment]
Hello!
While there's currently no rule forbidding you from opening an issue, the ``#support`` channel on Discord kind of exists for exactly that reason. In fact, we've had a similar question just yesterday where I gave an innofficial recommendation:
https://discord.com/channels/1003691521280856084/1075027968449069166/1075032991132291113

The issue with the AppShell and a layered layout like that is that - as far as I'm aware - you can't have a named slot in the top level of a Svelte-Component that then get's resolved in the containing Svelte-Component/layout/etc.

A ``page.svelte`` like this
```svelte
<div slot="pageHeader">header content</slot>
<p> actual page content</>
```

with a ``layout.svelte``:
```svelte
<AppShell>
[...]
<svelte:fragment slot="pageHeader"><slot name="pageHeader"></slot></svelte:fragment>
```
currently doesn't work in svelte and leads to an error that you can't assign a slot name to a div if it's not the child of a component.

**Comment by endigo9740** [comment]
@bertmad3400 See Sarenor's message above, he nailed our thoughts on this subject.

> But also yes, the AppShell is a great concept especially intended to help you get started in the easiest way possible. As soon as you are using advanced features like nested layouts or highly dynamic page layouts you will quickly run into limitations. It's there as an offer, not as a requirement.

In no way, shape, or form is the App Shell ever a hard requirement. It's a tool like any other tool, you use it when it's apt, you put it aside when it's not. If you find it's getting in your way more than it's helping, then perhaps you've outgrown it's usefulness.

In the example you presented above the best bet will be to either use multiple instances of the App Shell - in each of these sections you would have a unique layout where you can choose to use the App Shell OR build your own custom layout structure from the ground up.

But this isn't a problem Skeleton or the App Shell introduces, this is just how SvelteKit and multiple layouts work. I might direct you to the SvelteKit documentation and specifically route groups:

https://kit.svelte.dev/docs/advanced-routing#advanced-layouts

These are great for sectioning off your application and using unique layouts per each. Using this your example above becomes:

**routes**
- +layout.svelte
- +page.svelte
- **(feed)**
  - +layout.svelte
  - +layout.ts
  - +page.svelte
- **(blog)**
  - +layout.svelte
  - +layout.ts
  - +page.svelte
  
  > While it would be possible to make the sidebar a separate component for every single subpage, this would not only need to result in some messy conditional logic in the root layout, along with completely decoupling every sidebar from the corresponding route, but should the content of the sidebar need to be dynamically generated, then this logic would also have to be moved from the layout.ts to a completely different place.

  
I'm struggling to think of a well design sidebar that would be unique for every subpage - every GROUP, maybe, but not every page. You might take a look at how we constructed our sidebar for the Skeleton doc site local components. It might help.

https://github.com/skeletonlabs/skeleton/blob/dev/src/docs/DocsNavigation/DocsSidebar.svelte

And FYI this is getting a bit beyond the scope of Skeleton and more into the territory of just how SvelteKit operates. In that case. Hopefully the above guides you, but I'm not seeing an actionable item to address here. Just a question that was asked. I'm going to go ahead and close this out, but if you wish to continue this conversation let me know and I can reopen and migrate this ticket to a Discussion - which is much more appropriate for this. Per the Q&A category.

Thanks!

**Comment by lnfel** [comment]
Well said, with the limitations of svelte components named slots we cannot simply have dynamic pageHeaders. AppShell can only be used as a component wrapper and it easily made sveltekit app into react real quick. This is the reason I dropped using AppShell today and do the layouts in much more svelte-esque way.
