### ISSUE TITLE
FileDropzone relative height

### ISSUE THREAD

**Issue by lic-8** [skeletonlabs/skeleton#989]
### Current Behavior

FileDropzone component doesn't seem to accept relative heights like `h-full`.

**Comment by endigo9740** [comment]
Hey @lic-8 This is very much possible, you can always apply arbitrary classes to the parent element within a component uses the standard `class` attribute:

```html
<FileDropzone ... class="h-full" />
```

In testing this I realized we have a minor issue where the middle contents aren't centered when this occurs:

![Screenshot 2023-02-20 at 11 26 15 AM](https://user-images.githubusercontent.com/1509726/220170432-6bd1d4a4-b5ed-4c5f-9e50-f33022859b1a.png)

So I've put in a quick fix to resolve this. This will be part of tomorrow release.

![Screenshot 2023-02-20 at 11 26 04 AM](https://user-images.githubusercontent.com/1509726/220170460-7f53f576-af28-4fff-8650-c79f0282799b.png)
