### ISSUE TITLE
[Feature] Min/Max range slider

### ISSUE THREAD

**Issue by lic-8** [skeletonlabs/skeleton#990]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Like a range slider but with a low and high value

### What type of pull request would this be?

None

**Comment by Sarenor** [comment]
Could you elaborate a bit what you would like here? Like a range slider with 2 moveable chevrons?

Screenshots or links to a similar component would also be appreciated

**Comment by endigo9740** [comment]
Our range slider relies on the native input of the same name. We're limited by the capabilities of what it provides as far as functionality. Currently features like vertical and labeled stops are a possibility if browser support increases, but unfortunately I've not seen any talk of a min/max version:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

This is not one we'll be able to fulfill, sorry. I'd suggest introducing a custom element if you need this.
