### ISSUE TITLE
New to Tailwind and SkeletonLabs - using @apply and @layer for global styles

### ISSUE THREAD

**Issue by FernieRealEstate** [skeletonlabs/skeleton#992]
Hi, nice job!

I am trying to make your style `variant-ghost-tertiary` global on a .btn. How do I do this?  This is the error if I just add it to the app.postcss with the other classess:

.btn {
	@apply variant-ghost-tertiary px-4 py-1 ml-1;
}

[vite:css] [postcss] /Volumes/Data/Websites-Current/FernieRealEstateApp/sveltekit-edge-functions/sveltekit-edge-functions/src/app.postcss:21:2: The `variant-ghost-tertiary` class does not exist. If `variant-ghost-tertiary` is a custom class, make sure it is defined within a `@layer` directive.

**Comment by FernieRealEstate** [comment]
Also, a separate question. Is there a way to strip out unused CSS during vite build and sveltekit?  These file sizes look to big for a simple app:
.svelte-kit/output/client/_app/immutable/assets/_page-76d40a00.css                                  5.11 kB │ gzip:   1.38 kB
.svelte-kit/output/client/_app/immutable/assets/MapBox-5d54fb70.css                                37.05 kB │ gzip:   4.98 kB
.svelte-kit/output/client/_app/immutable/assets/_layout-bd264ebd.css                               88.20 kB │ gzip:  12.27 kB

**Comment by endigo9740** [comment]
The error in an indication of the current situation - this is not possible. It's a limitation of Tailwind, there's nothing we can do to support this, sorry.

I'd advise using this as utility class as intended, and pairing both your `btn` and `variant-ghost-tertiary` classes when needed on the HTML element. This is the approach Tailwind recommends as well:
https://tailwindcss.com/docs/utility-first

Per your second question, see this ticket. We expect this to launch very soon:
- https://github.com/skeletonlabs/skeleton/issues/732

**Comment by FernieRealEstate** [comment]
Thank you!
